### ISSUE TITLE
I would like to be able to marshal protobufs reliably to YAML

### ISSUE THREAD

**Issue by ebilling** [golang/protobuf#1001]
**Is your feature request related to a problem? Please describe.**
JSON marshaling of protobufs is very good, but I have a need to create YAML versions of my protos.  Unfortunately, the names that go into the YAML are differing due to how camel case of go names are interpreted by the YAML parser. 

**Describe the solution you'd like**

I would like to add field tags for YAML like we have for JSON already.

**Describe alternatives you've considered**
I first tried to get the go-yaml project to adopt a change where I could ask them to use an alternative language's field tags, but there has been no interest in adopting it.

Ideally we could have several common outputs defined such as YAML, XML, etc. and a directive in the protobuf definition on which ones to use.  This could be made completely configurable and essentially give a printf format string with a space for the name.

ex.)
```
option go_additional_field_tags="format1:\"%s,omitempty\" format2:\"%s,format2_specific_instruction\""
```

produces:
```
// name of the thing
Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" format1:"name,omitempty" format2:"name,format2_specific_instruction"`

```

**Comment by ebilling** [comment]
Happy to implement this is there is an appetite to take the change.

**Comment by dsnet** [comment]
The purpose of this project is to be a faithful implementation of the protobuf language (see https://github.com/protocolbuffers/protobuf). It is outside our scope of work to develop and/or maintain features that are not supported by the other language implementations. Specifically, there exists no protobuf-to-yaml mapping specified by the protobuf team, as such we cannot accept this feature request.

If you want finer granularity control of the generated tags, then #52 might interest you.
