### ISSUE TITLE
protoc-gen-go: drop ExtensionRangeArray method?

### ISSUE THREAD

**Issue by neild** [golang/protobuf#1007]
Consider not generating the ExtensionRangeArray method on generated message structs. It's no longer used by the implementation, and isn't a useful user-facing API.

**Comment by dsnet** [comment]
Strictly speaking, [our compatibility agreement](https://github.com/golang/protobuf#compatibility) only reserves the right to add/remove methods with an `XXX` prefix. Even though this has little useful value to the user, isn't removal of it going against that document?

**Comment by neild** [comment]
We're already marking it as deprecated in the v2 generator; remove six months after APIv2 is released per breaking change policy?

**Comment by dsnet** [comment]
> We're already marking it as deprecated in the v2 generator; remove six months after APIv2 is released per breaking change policy?

SGTM. The `blocks-v2` label was confusing me since it seemed to suggest that we would remove this before we release v2.

**Comment by neild** [comment]
More of a "decide if we're going to remove this before releasing". I'm going to leave the label on to make sure we include the appropriate deprecation notice in the v2 release.

**Comment by dsnet** [comment]
Related to this. I'd like to see the following removed as well:
1. `Enum.UnmarshalJSON` for proto2.
2. `Enum.EnumDescriptor`; replaced by native protobuf reflection
3. `Message.Descriptor`; replaced by native protobuf reflection
4. `protobuf` struct field tags on messages
5. `json` struct field tags on messages

The justification for 1 and 5 is that they give the illusion that `encoding/json` works on generated types, when they actually do not. The [`jsonpb` package even states this](https://godoc.org/github.com/golang/protobuf/jsonpb). Their existence cause greater harm when people mistakenly rely on them.

The justification for 2 and 3 is that these methods are superseded by protobuf reflection which is the flagship feature of `APIv2`.

The justification for 4 is that this tag should never be relied upon by users. We can ensure that `proto.GetProperties` continues to work even if they're missing. However, users should never have used Go reflection to manually look at this tag.

**Comment by puellanivis** [comment]
:+1: all of these are good arguments. Especially the `json` struct tag.

**Comment by dsnet** [comment]
In our offline discussion @neild and I decided that we will announce (at v2 release time) the deprecation of `ExtensionRangeArray` and the items listed https://github.com/golang/protobuf/issues/1007#issuecomment-573263370 with the warning that we probably will remove them in 6 months. Whether we actually carry through with it is to be TBD (pending user feedback).

**Comment by dsnet** [comment]
Dropping of `ExtensionRangeArray` is already announced in the `v1.20.0` release. Do we still want to keep this open?

**Comment by puellanivis** [comment]
I think until we actually drop it, the issue should stay open?

**Comment by dsnet** [comment]
I analyzed all modules in the Go proxy and found no direct calls to the `ExtensionRangeArray` method. It's probably say to treat it as equivalent to the `XXX` fields and methods and to remove it. I don't think we can remove the other stuff mentioned in https://github.com/golang/protobuf/issues/1007#issuecomment-573263370, though.

**Comment by dsnet** [comment]
http://golang.org/cl/305574 removes `ExtensionRangeArray`.

For the other stuff I proposed in https://github.com/golang/protobuf/issues/1007#issuecomment-573263370, I don't think we can safely change those given that there are too many static or dynamic references to them.
