### ISSUE TITLE
APIv2: encoding/protojson: more specific resolver errors

### ISSUE THREAD

**Issue by dsnet** [golang/protobuf#1008]
In the case where the resolver could not resolve an extension or Any message, it returns a `protoregistry.NotFound` error. This is unhelpful to users. We should have it specifically say which message or extension could not be resolved.

Same for `prototext`.

**Comment by cybrcodr** [comment]
I just peruse the codebase and I think this only happens in ...
https://go.googlesource.com/protobuf/+/refs/heads/master/encoding/prototext/encode.go#346

which should be fixed in https://golang.org/cl/204602

**Comment by cybrcodr** [comment]
My bad, the link I showed in previous posting does not actually use the error text.  So yeah, V2 codebase does not return such error as far as I know of.  Closing this out.
