### ISSUE TITLE
APIv2: update protojson and prototext tests to use internal/testprotos/...

### ISSUE THREAD

**Issue by cybrcodr** [golang/protobuf#1009]
Current tests for encoding/{prototext,protojson} uses test protos under encoding/testprotos/...  We should migrate the tests to use protos under internal/testprotos/... to be consistent with other features and also expand the scope as much as possible.

**Comment by neild** [comment]
We might do this, but I don't think it's important enough to warrant leaving a bug open for it. The current tests are fine, just a bit inconsistent in design between `proto` and `encoding/proto{json,text}`.
