### ISSUE TITLE
APIv2: write release notes

### ISSUE THREAD

**Issue by neild** [golang/protobuf#1012]
This issue is for tracking notable changes that need to appear in the APIv2 release notes.

**Comment by neild** [comment]
From #964: `nil` map values are no longer preserved across `Marshal`/`Unmarshal` operations. A `([]byte)(nil)` will become a non-nil `[]byte{}`, and a message `(*T)(nil)` will become an empty `&T{}`.

**Comment by neild** [comment]
Also on `nil`: `nil` message values are now permitted in repeated fields, and are treated identically to a non-`nil`, empty message. Previously, `nil` message values were treated as an error in a wire marshaling and other places.

**Comment by neild** [comment]
From #1007: Document that the ExtensionRangeArray on generated messages is deprecated and will be removed.

Mention other changes to XXX_ methods/fields in generated code.

**Comment by neild** [comment]
Deliberate instability in the text format.

We should also have a FAQ, and put this in it.

**Comment by neild** [comment]
The gRPC generator is now a separate protoc plugin.

**Comment by dsnet** [comment]
Notes are in a draft, ready to click release. Marking as done.
