### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by zhb1207** [golang/protobuf#1015]
Hi I'm using protoc to generate pb.go files but I met the errors below:
**files:**

- A/protobuf/message.proto
- A/protobuf/temp.proto

------------------------------------------------------------------------------------------------------------------------------
COMMAND LINE: 
user@device:~/go/src/A/protobuf$ protoc --proto_path=$GOPATH/src/A/ --go_out=. *.proto
OUTPUT: 
message.proto: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).
------------------------------------------------------------------------------------------------------------------------------
COMMAND LINE: 
user@device:~/go/src/A/protobuf$ protoc --proto_path=$GOPATH/src/A/protobuf/ --go_out=. *.proto
OUTPUT:
/protobuf/temp.proto: File not found.
message.proto: Import "/protobuf/temp.proto" was not found or had errors.
message.proto:148:12: "Block" is not defined.
------------------------------------------------------------------------------------------------------------------------------
I searched the problems in google, but I am still confused with the output above: I just changed the --proto_path parameter and the output error is totally different, what's the root cause of that?

Thanks.

**Comment by neild** [comment]
This is `protoc` complaining that `--proto_path` must be a prefix of each file compiled. The actual string value.

So `protoc --proto_path=$GOPATH/src/A message.proto` is invalid because `message.proto` doesn't start with `$GOPATH/src/A`. You instead need to write:

```
protoc --proto_path=$GOPATH/src/A $GOPATH/src/A/protobuf/message.proto
```
