### ISSUE TITLE
about package name

### ISSUE THREAD

**Issue by liuhanlcj** [golang/protobuf#102]
I write a proto file like this:
```
syntax = "proto3";

package ygoproto.users;
```
Then I find build .go files package name like this:
```
package ygoproto_users
```

But i want to get the name like
```
package users
```

Because my path struct like ./ygoproto/users/.

What should I do?

**Comment by zeroZshadow** [comment]
you can use "option go_package=users" to set the package name if i recall correctly

**Comment by liuhanlcj** [comment]
I tried this method,but I get the error : "option: No such file or directory".And I have many files, I must set name by myself,I want to get a better method.I think i must fork and change code...
