### ISSUE TITLE
APIv2: define structured errors

### ISSUE THREAD

**Issue by neild** [golang/protobuf#1021]
We should return structured errors of some form. There doesn't need to be a lot of complexity here and it's best to start by providing as little information as possible and expand from there, but some degree of structure beyond `nil`/non-`nil` would be good.

At a minimum, all proto module errors should match (with `errors.Is`) some common error. I'm cleaning up cases inside Google that depend on exact error text, and "is this a proto error" is both common and reasonable to ask in tests.

```go
if errors.Is(err, proto.Error) {
  // This error was returned by some function in the proto module.
}
```

Possible additional errors to consider:

* initialization check failure (missing required fields)
* parse error (bad wire/text/json data)
   * Do we have one category for all parse errors, or specific errors in `proto`/`prototext`/`protojson`?
   * On a related note, we shouldn't return irrelevant detail from `proto.Unmarshal`--"unknown wire type 16" is confusing, "invalid proto wire format" is better.
* `protoregistry.NotFound` already exists

In all cases, we should consistently return errors that wrap a sentinel (like `protoregistry.NotFound`) instead of returning the sentinel directly, to permit us to include additional information in the error text.

**Comment by dsnet** [comment]
SGTM.

> Do we have one category for all parse errors, or specific errors in proto/prototext/protojson?

I think we should just start with `proto.Error` and expand from their in minor releases after v2.

> In all cases, we should consistently return errors that wrap a sentinel (like protoregistry.NotFound) instead of returning the sentinel directly, to permit us to include additional information in the error text.

+1. Let's do that now so that basic "== NotFound" doesn't work.

**Comment by puellanivis** [comment]
Just a thing `errors.Is(…)` checks against a specific sentinel error value, (like `protoregistry.NotFound`, where as we probably want `proto.Error` to be a type that can be used with `errors.As(…)`.

Ideally, even the sentinels should be `proto.Error` assignable, so that we can have a simple `var pErr proto.Error; if errors.As(err, &pErr) { /* it’s a protobuf error */ }`

**Comment by neild** [comment]
What information do you envision as appearing in the `proto.Error` type? If it's just a classification ("this error came out of the proto package"), a sentinel seems like all we need.

**Comment by puellanivis** [comment]
As a sentinel it could not even have a different text string… unless you expect to just have each internal error to have: `Unwrap() error { return proto.Error }`?

**Comment by cybrcodr** [comment]
Current `prototext` and `protojson` returns `proto.Error` as well as `io.ErrUnexpectedEOF`.  Should the latter be wrapped in `proto.Error`?

**Comment by neild** [comment]
Yes, we should wrap every returned error in a proto.Error.

**Comment by cybrcodr** [comment]
Speaking of wrapping.  Do we want to have 1.13+ version that uses %w to expose underlying error?

Based on above conversations, I'm guessing we'll punt on this for now and not expose such?

**Comment by puellanivis** [comment]
Yes, we probably want to punt on using the `%w` stuff until go1.12 is out of support.

**Comment by dsnet** [comment]
I think we're mixing two things. The use of `%w` requires go1.12 at minimum, but the use of error wrapping is something we can support today since it only requires satisfaction of certain interfaces.
