### ISSUE TITLE
APIv2: finalize ProtoMethods magic method

### ISSUE THREAD

**Issue by neild** [golang/protobuf#1022]
The v2 API has one magic method: `ProtoMethods`, defined in the `protoiface.Methoder` interface, and associated with a type implementing `protoreflect.Message`. This method is currently defined as a magic method as opposed to part of the `protoreflect.Message` interface to avoid polluting the `protoreflect` package with the details of the fast-path implementation which are not (or should not be) of interest to anyone other than implementers.

In some very fast operations, type assertions from `protoreflect.Message` to `protoiface.Methoder` show up as a significant item in CPU profiles. Type assertions to an interface type are relatively expensive at this time.

Options I see:

1. Accept the performance hit of requiring at least one interface->interface type assertion on every fast-path operation. This is really only a concern for very fast operations, after all; for more expensive ones the cost of the type assertion is relatively negligible. (Fast: Unmarshaling a couple of fields in a message that requires no allocation. Slow: Unmarshaling a complex, deeply-nested message which requires hundreds of allocations.) This has the advantage of not requiring a last-minute API change.
2. Move the `Methoder` interface into `protoreflect`, accepting the additional complexity in the package. The package is already large, so perhaps adding more won't hurt much.
3. Remove the `protoreflect.ProtoMessage` type and define it directly in `proto.Message`, changing its definition to include the . (The latter is an alias to the former at the moment.) This would require changing a couple `ProtoMessage` return parameters in `protoreflect` into `interface{}`.

Maybe there's something else I'm missing. At the moment, I'm inclined to option (3). Concretely, change `proto.Message` to:

```go
package proto
type Message {
  ProtoReflect() interface {
    protoreflect.Message
    protoiface.Methoder
  }
}
```

Change `protoreflect.Descriptor.Options` to return `interface{}`.

Change `protoreflect.Message.Interface` to:

```go
// Interface unwraps the message reflection interface and
// returns the underlying message type.
Unwrap() interface{}
```

This last change has one other advantage: It would allow unwrapping a `protoreflect.Message` into a legacy type which doesn't implement the `ProtoMessage` interface.

**Comment by puellanivis** [comment]
Hm, how much of an impact on using the API would there be to the end-user from changing the returns to an `interface{}` which will require a type-assertion into a `proto.Message`?

Is that use case reasonably common, such that complicating it all would be tedious?

How likely it is that an end user could be tempted to just use `msg.Unwrap().(proto.Message).ProtoReflect()` which could panic unexpectedly on an exceptional return from `Unwrap()`?

**Comment by neild** [comment]
For the `Options` methods, returning `interface{}` vs. `Message` shouldn't really be any difference. In both cases, the caller is almost certainly going to type assert the result to a concrete options type:

```go
opts := messagedesc.Options().(*descpb.MessageOptions)
```

(It'd be nice if we didn't need the type assertion at all, but without it we'd have an import cycle between `protoreflect` and the generated descriptor package.)

The `(protoreflect.Message).Interface()` method is the inverse of `(protoreflect.ProtoMessage).ProtoReflect()`. A user might need it for two reasons I can think of: To pass a `protoreflect.Message` to a function that expects a `protoreflect.ProtoMessage`, and to recover the original typed message value. Recovering the typed value from an `interface{}` is no harder than from a `ProtoMessage`.

It would be most unfortunate if passing a `protoreflect.Message` to `proto.Marshal` required a type assertion, however. That's probably sufficient cause to argue against changing the `Interface` method to return `interface{}`.

**Comment by neild** [comment]
Another option:

```go
package proto

type Message interface {
  ProtoReflect() MessageReflect
}

type MessageReflect {
  Message
  protoreflect.Message
  protoiface.Methoder
  Unwrap() interface{}  // maybe?
}
```

Drop `protoreflect.ProtoMessage` entirely.

Under this approach, the reflective message type users interact with is usually `proto.MessageReflect`, which:

* Implements the reflective `protoreflect.Message` interface.
* Is a `proto.Message`, and can be passed directly to `proto.Unmarshal` etc.
* Is a `protoiface.Methoder`, providing access to the fast path without a type assertion.

**Comment by neild** [comment]
In offline discussion, Joe convinced me that last idea won't work. (You need to be able to go from a `protoreflect.MessageType` to a `proto.Message`, which this doesn't allow for.)

I think we're agreed that we need to move the magic `ProtoMethods` method into the `protoreflect.Message` interface. We don't want to force the cost of the type assertion, and avoiding magic methods entirely is the more principled approach.

There are two options on the table that we see:

1. Move all of `runtime/protoiface/methods.go` directly into `protoreflect` as exported types. This adds a number of types to `protoreflect`: `Methods`, `SupportFlags`, `MarshalOptions`, and `UnmarshalOptions`. Possibly a few more after some upcoming methods changes.

2. Move these types into `protoreflect` as *unexported*, unnamed types. Maintain two identical copies of the types--as exported types in `protoiface`, and as unexported ones in `protoreflect`.

Option (2) means some code bloat and duplication, but keeps the `protoreflect` package API clean.

**Comment by neild** [comment]
With  [CL 215718](https://go-review.googlesource.com/c/protobuf/+/215718) and [CL 215877](https://go-review.googlesource.com/c/protobuf/+/215877), I think we're in a pretty good state.
