### ISSUE TITLE
Regression in handling of 0 values for google.protobuf.Int64Value types (and maybe others)

### ISSUE THREAD

**Issue by shidel-dev** [golang/protobuf#1027]
**What version of protobuf and what language are you using?**
Version: Ruby 3.11.2

**What did you do?**
Simplified/Minimal Example.

```
message Wrapper {
  google.protobuf.Int64Value id = 1;
}
```

```ruby
  Wrapper.decode(Wrapper.new( id: Google::Protobuf::Int64Value.new( value: 0) ).to_proto)
```

OUTOUT ` <Wrapper: id: nil>`

**What did you expect to see?**
`<Wrapper: id: <Google::Protobuf::Int64Value: value: 0>>`

**What did you see instead?**
` <Wrapper: id: nil>`
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment?**

This works on version `3.7.1` of the gem as expected. This is a very dangerous bug in my opinion, as it can break applications...

**Comment by dsnet** [comment]
This is the repository for the Go implementation of protobufs, I believe you want to file this at https://github.com/protocolbuffers/protobuf instead. We don't maintain the Ruby implementation.

**Comment by shidel-dev** [comment]
Sorry about that
