### ISSUE TITLE
Support for architecture to cross-compile

### ISSUE THREAD

**Issue by mickep76** [golang/protobuf#1028]
Be able to specify arch like linux or darwin there are cases where you only want a module for a specific architecture. It would be nice if the generator could create the proper prefix in the file and set filename to _linux or _darwin.

**Describe the solution you'd like**
Should be able to incl. as a parameter in the go_package option.

**Describe alternatives you've considered**
Compile using protoc then template output separately. This is obv. a simple workaround but less elegant solution.

**Comment by dsnet** [comment]
Hi, I'm not entirely sure what you're are expecting us to do. Is this about the generated code or the protobuf runtime library? I should note that none of the protobuf code makes assumptions about the specific architecture that its built for (we do use `unsafe`, but in architecture agnostic ways).

**Comment by dsnet** [comment]
Closing as inactionable.
