### ISSUE TITLE
Getting unknown import in compiled .pb.go

### ISSUE THREAD

**Issue by Gacnt** [golang/protobuf#103]
I've installed `protoc-gen-go` following all the steps on the main page

When I compile using `protoc --go_out=. *.proto` I get my files that that have `import google_protobuf "google/protobuf"` and `import _ "google/protobuf"` in my files but I have no idea where to get this package or what I'm doing wrong, there's zero documentation on this issue on [dev.google](https://developers.google.com/protocol-buffers/docs/reference/go-generated#invocation)

The protobufs I'm compiling are located here: https://github.com/SteamRE/SteamKit/tree/master/Resources/Protobufs/csgo

**Comment by dsymonds** [comment]
google/protobuf/descriptor.proto and friends are in https://github.com/google/protobuf, I think. #50 covers better handling of these "standard" protos; right now you have to handle them yourself.
