### ISSUE TITLE
types/known: typed error for non-linked in Any message

### ISSUE THREAD

**Issue by nylar** [golang/protobuf#1037]
**Is your feature request related to a problem? Please describe.**
We use an `Envelope` `message` that has an `Any` field for holding another `message`. In our services whenever we add a new message we must go through each service and recompile our protos just so this new message is linked in, most of the time a new proto is ignored when switching on the type but an error is raised when we do `ptypes.UnmarshalAny` which happens before. At the moment, a non-typed error is returned: https://github.com/golang/protobuf/blob/d23c5127dc24889085f8ccea5c9d560a57a879d8/ptypes/any.go#L97

**Describe the solution you'd like**
A typed error that we can type switch against:
```go
type NonLinkedInMessageError struct {
	message string
}

func (e *NonLinkedInMessageError) Error() string {
	return fmt.Sprintf("any: message type %q isn't linked in", e.message)
}

...

if t == nil {
	return nil, &NonLinkedInMessageError{message: aname}
}
```

**Describe alternatives you've considered**
We can either painfully go through each service and update the protos or we can do a clunky string check on the error `strings.Contains(err, "isn't linked in")`.

**Additional context**
N/A

**Comment by dsnet** [comment]
This is a reasonable feature request, but we are no longer accepting changes to the v1 API. The v2 protobuf API provides this feature through the [`protoregistry.NotFound`](https://pkg.go.dev/google.golang.org/protobuf/reflect/protoregistry?tab=doc#NotFound) error value. We're focusing all our efforts on getting v2 out the door than trying to maintain v1. A stable v2 release is slated for the next week or two.

**Comment by dsnet** [comment]
Fixed by https://golang.org/cl/225298. It will be available in the next release of the google.golang.org/protobuf module, to be released within a week or so.

That CL adds specialized APIs for the generated Any message. The `UnmarshalNew` method returns a `protoregistry.NotFound` if it is not found.
