### ISSUE TITLE
protoc-gen-go: Plugin output is unparseable: Active code page: 65001 , os windows 10 1903; system page code (65001)utf-8; protoc.exe version  3.11.4;  protoc-gen-go newest

### ISSUE THREAD

**Issue by Sunknight945** [golang/protobuf#1042]
PS E:\1Go\src\MyProjectsFloder> protoc --java_out=. *.proto                                
PS E:\1Go\src\MyProjectsFloder> protoc --go_out=. *.proto  
--go_out: protoc-gen-go: Plugin output is unparseable: Active code page: 65001\r\nz\2230\n\ntest.pb.goz\2040// Code g
enerated by protoc-gen-go. DO NOT EDIT.\n// source: test.proto\n\npackage packet\n\nimport (\n\tfmt \"fmt\"\n\tproto
\"github.com/golang/protobuf/proto\"\n\tmath \"math\"\n)\n\n// Reference imports to suppress errors if they are not o
therwise used.\nvar _ = proto.Marshal\nvar _ = fmt.Errorf\nvar _ = math.Inf\n\n// This is a compile-time assertion to
 ensure that this generated file\n// is compatible with the proto package it is being compiled against.\n// A compila
tion error at this line likely means your copy of the\n// proto package needs to be updated.\nconst _ = proto.ProtoPa
ckageIsVersion3 // please upgrade the proto package\n\ntype Header struct {\n\tMessageId            *string  `protobu
f:\"bytes,1,req,name=messageId\" json:\"messageId,omitempty\"`\n\tTopic                *string  `protobuf:\"bytes,2,r
eq,name=topic\" json:\"topic,omitempty\"`\n\tXXX_NoUnkeyedLiteral struct{} `json:\"-\"`\n\tXXX_unrecognized     []byt
e   `json:\"-\"`\n\tXXX_sizecache        int32    `json:\"-\"`\n}\n\nfunc (m *Header) Reset()         { *m = Header{}
 }\nfunc (m *Header) String() string { return proto.CompactTextString(m) }\nfunc (*Header) ProtoMessage()    {}\nfunc
 (*Header) Descriptor() ([]byte, []int) {\n\treturn fileDescriptor_c161fcfdc0c3ff1e, []int{0}\n}\n\nfunc (m *Header)
XXX_Unmarshal(b []byte) error {\n\treturn xxx_messageInfo_Header.Unmarshal(m, b)\n}\nfunc (m *Header) XXX_Marshal(b [
]byte, deterministic bool) ([]byte, error) {\n\treturn xxx_messageInfo_Header.Marshal(b, m, deterministic)\n}\nfunc (
m *Header) XXX_Merge(src proto.Message) {\n\txxx_messageInfo_Header.Merge(m, src)\n}\nfunc (m *Header) XXX_Size() int
 {\n\treturn xxx_messageInfo_Header.Size(m)\n}\nfunc (m *Header) XXX_DiscardUnknown() {\n\txxx_messageInfo_Header.Dis
cardUnknown(m)\n}\n\nvar xxx_messageInfo_Header proto.InternalMessageInfo\n\nfunc (m *Header) GetMessageId() string {
\n\tif m != nil && m.MessageId != nil {\n\t\treturn *m.MessageId\n\t}\n\treturn \"\"\n}\n\nfunc (m *Header) GetTopic(
) string {\n\tif m != nil && m.Topic != nil {\n\t\treturn *m.Topic\n\t}\n\treturn \"\"\n}\n\ntype BytesMessage struct
 {\n\tHeader               *Header  `protobuf:\"bytes,1,req,name=header\" json:\"header,omitempty\"`\n\tBody
        []byte   `protobuf:\"bytes,2,req,name=body\" json:\"body,omitempty\"`\n\tXXX_NoUnkeyedLiteral struct{} `json:
\"-\"`\n\tXXX_unrecognized     []byte   `json:\"-\"`\n\tXXX_sizecache        int32    `json:\"-\"`\n}\n\nfunc (m *Byt
esMessage) Reset()         { *m = BytesMessage{} }\nfunc (m *BytesMessage) String() string { return proto.CompactText
String(m) }\nfunc (*BytesMessage) ProtoMessage()    {}\nfunc (*BytesMessage) Descriptor() ([]byte, []int) {\n\treturn
 fileDescriptor_c161fcfdc0c3ff1e, []int{1}\n}\n\nfunc (m *BytesMessage) XXX_Unmarshal(b []byte) error {\n\treturn xxx
_messageInfo_BytesMessage.Unmarshal(m, b)\n}\nfunc (m *BytesMessage) XXX_Marshal(b []byte, deterministic bool) ([]byt
e, error) {\n\treturn xxx_messageInfo_BytesMessage.Marshal(b, m, deterministic)\n}\nfunc (m *BytesMessage) XXX_Merge(
src proto.Message) {\n\txxx_messageInfo_BytesMessage.Merge(m, src)\n}\nfunc (m *BytesMessage) XXX_Size() int {\n\tret
urn xxx_messageInfo_BytesMessage.Size(m)\n}\nfunc (m *BytesMessage) XXX_DiscardUnknown() {\n\txxx_messageInfo_BytesMe
ssage.DiscardUnknown(m)\n}\n\nvar xxx_messageInfo_BytesMessage proto.InternalMessageInfo\n\nfunc (m *BytesMessage) Ge
tHeader() *Header {\n\tif m != nil {\n\t\treturn m.Header\n\t}\n\treturn nil\n}\n\nfunc (m *BytesMessage) GetBody() [
]byte {\n\tif m != nil {\n\t\treturn m.Body\n\t}\n\treturn nil\n}\n\ntype StringMessage struct {\n\tHeader
    *Header  `protobuf:\"bytes,1,req,name=header\" json:\"header,omitempty\"`\n\tBody                 *string  `proto
buf:\"bytes,2,req,name=body\" json:\"body,omitempty\"`\n\tXXX_NoUnkeyedLiteral struct{} `json:\"-\"`\n\tXXX_unrecogni
zed     []byte   `json:\"-\"`\n\tXXX_sizecache        int32    `json:\"-\"`\n}\n\nfunc (m *StringMessage) Reset()
     { *m = StringMessage{} }\nfunc (m *StringMessage) String() string { return proto.CompactTextString(m) }\nfunc (*
StringMessage) ProtoMessage()    {}\nfunc (*StringMessage) Descriptor() ([]byte, []int) {\n\treturn fileDescriptor_c1
61fcfdc0c3ff1e, []int{2}\n}\n\nfunc (m *StringMessage) XXX_Unmarshal(b []byte) error {\n\treturn xxx_messageInfo_Stri
ngMessage.Unmarshal(m, b)\n}\nfunc (m *StringMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {\n\t
return xxx_messageInfo_StringMessage.Marshal(b, m, deterministic)\n}\nfunc (m *StringMessage) XXX_Merge(src proto.Mes
sage) {\n\txxx_messageInfo_StringMessage.Merge(m, src)\n}\nfunc (m *StringMessage) XXX_Size() int {\n\treturn xxx_mes
sageInfo_StringMessage.Size(m)\n}\nfunc (m *StringMessage) XXX_DiscardUnknown() {\n\txxx_messageInfo_StringMessage.Di
scardUnknown(m)\n}\n\nvar xxx_messageInfo_StringMessage proto.InternalMessageInfo\n\nfunc (m *StringMessage) GetHeade
r() *Header {\n\tif m != nil {\n\t\treturn m.Header\n\t}\n\treturn nil\n}\n\nfunc (m *StringMessage) GetBody() string
 {\n\tif m != nil && m.Body != nil {\n\t\treturn *m.Body\n\t}\n\treturn \"\"\n}\n\nfunc init() {\n\tproto.RegisterTyp
e((*Header)(nil), \"packet.Header\")\n\tproto.RegisterType((*BytesMessage)(nil), \"packet.BytesMessage\")\n\tproto.Re
gisterType((*StringMessage)(nil), \"packet.StringMessage\")\n}\n\nfunc init() { proto.RegisterFile(\"test.proto\", fi
leDescriptor_c161fcfdc0c3ff1e) }\n\nvar fileDescriptor_c161fcfdc0c3ff1e = []byte{\n\t// 153 bytes of a gzipped FileDe
scriptorProto\n\t0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,\n\t0
xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0x48, 0x4c, 0xce, 0x4e, 0x2d, 0x51, 0xb2,\n\t0xe1, 0x62, 0xf3, 0
x48, 0x4d, 0x4c, 0x49, 0x2d, 0x12, 0x92, 0xe1, 0xe2, 0xcc, 0x4d, 0x2d, 0x2e,\n\t0x4e, 0x4c, 0x4f, 0xf5, 0x4c, 0x91, 0
x60, 0x54, 0x60, 0xd2, 0xe0, 0x0c, 0x42, 0x08, 0x08, 0x89,\n\t0x70, 0xb1, 0x96, 0xe4, 0x17, 0x64, 0x26, 0x4b, 0x30, 0
x81, 0x65, 0x20, 0x1c, 0x25, 0x2f, 0x2e,\n\t0x1e, 0xa7, 0xca, 0x92, 0xd4, 0x62, 0x5f, 0x88, 0x3a, 0x21, 0x35, 0x2e, 0
xb6, 0x0c, 0xb0, 0x69,\n\t0x60, 0x03, 0xb8, 0x8d, 0xf8, 0xf4, 0x20, 0xd6, 0xe8, 0x41, 0xec, 0x08, 0x82, 0xca, 0x0a, 0
x09,\n\t0x71, 0xb1, 0x24, 0xe5, 0xa7, 0x54, 0x82, 0x0d, 0xe3, 0x09, 0x02, 0xb3, 0x95, 0xbc, 0xb9, 0x78,\n\t0x83, 0x4b
, 0x8a, 0x32, 0xf3, 0xd2, 0x29, 0x31, 0x8c, 0x13, 0x62, 0x18, 0x20, 0x00, 0x00, 0xff,\n\t0xff, 0x49, 0xa1, 0x42, 0x85
, 0xeb, 0x00, 0x00, 0x00,\n}\n
PS E:\1Go\src\MyProjectsFlod

**Comment by dsnet** [comment]
Thanks for the report. However, without knowing what version of `protoc-gen-go` this is and also the `.proto` file that was used to produce this issue, it is very difficult for us to do anything with this report.

**Comment by Sunknight945** [comment]
os win 10, system encoding is utf-8,  protoc is 3.11.4  , protoc-gen-go newest

the *.proto file content 
"
syntax = "proto2";
package packet;
message Header {
    required string messageId = 1;
    required string topic = 2;
}
message BytesMessage {
    required Header header = 1;
    required bytes body = 2;
}
message StringMessage {
    required Header header = 1;
    required string body = 2;
}
\"
This is all the clues I can provide.

**Comment by dsnet** [comment]
I tried `protoc` v3.11.4 with `protoc-gen-go` v1.3.3 and am unable to reproduce the problem. However, I am running on Linux. The developers of this project do not use Windows, so we are unable to render direct assistance there.

For `protoc` to parse the output of `protoc-gen-go` incorrectly, it seems that there is some type of issue with regard to how subprocess communication works between `protoc` and `protoc-gen-go` in Windows.

I'm not sure there's anything actionable here for us to do.

**Comment by dsnet** [comment]
Tried this on Windows with the exact version and files. Still cannot reproduce. I suspect something is going on in the Windows environment with regard to how IPC is done. I don't think there's anything actionable for us.

**Comment by TeslaCN** [comment]
I have the same problem, too.

```
--go_out: protoc-gen-go: Plugin output is unparseable:
```

system: Win10 1909
protoc version: protoc-3.11.4-win64, (I tried 3.9.1 still has the same problem)
protoc-gen-go: v1.3.4

room.proto
```
syntax = "proto3";
package register;
option go_package = "github.com/TeslaCN/compass/proto";
service Room {
    rpc Create (RoomInfo) returns (Response) {}
    rpc HeartBeat (RoomInfo) returns (Response) {}
    rpc Destroy (RoomInfo) returns (Response) {}
}
message RoomInfo {
    string id = 1;
    string addr = 2;
}
message Response {
    int32 code = 1;
    string msg = 2;
}
```

Output:
```
PS C:\Users\sia\GolandProjects\compass\proto> protoc --go_out=.  room.proto
--go_out: protoc-gen-go: Plugin output is unparseable: Active code page: 1252\r\nz\332&\n+github.com/TeslaCN/compass/proto/room.pb.goz\252&// Code generated by protoc-gen-go. DO NOT EDIT.\n// source: room.proto\n\npackage proto\n\nimport (\n\tfmt \"fmt\"\n\tproto \"github.com/golang/protobuf/proto\"\n\tmath \"math\"\n)\n\n// Reference imports to suppress errors if they are not otherwise used.\nvar _ = proto.Marshal\nvar _ = fmt.Errorf\nvar _ = math.Inf\n\n// This is a compile-time assertion to ensure that this generated file\n// is compatible with the proto package it is being compiled against.\n// A compilation error at this line likely means your copy of the\n// proto package needs to be updated.\nconst _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package\n\ntype RoomInfo struct {\n\tId                   string   `protobuf:\"bytes,1,opt,name=id,proto3\" json:\"id,omitempty\"`\n\tAddr                 string   `protobuf:\"bytes,2,opt,name=addr,proto3\" json:\"addr,omitempty\"`\n\tXXX_NoUnkeyedLiteral struct{} `json:\"-\"`\n\tXXX_unrecognized     []byte   `json:\"-\"`\n\tXXX_sizecache        int32    `json:\"-\"`\n}\n\nfunc (m *RoomInfo) Reset()         { *m = RoomInfo{} }\nfunc (m *RoomInfo) String() string { return proto.CompactTextString(m) }\nfunc (*RoomInfo) ProtoMessage()    {}\nfunc (*RoomInfo) Descriptor() ([]byte, []int) {\n\treturn fileDescriptor_c5fd27dd97284ef4, []int{0}\n}\n\nfunc (m *RoomInfo) XXX_Unmarshal(b []byte) error {\n\treturn xxx_messageInfo_RoomInfo.Unmarshal(m, b)\n}\nfunc (m *RoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {\n\treturn xxx_messageInfo_RoomInfo.Marshal(b, m, deterministic)\n}\nfunc (m *RoomInfo) XXX_Merge(src proto.Message) {\n\txxx_messageInfo_RoomInfo.Merge(m, src)\n}\nfunc (m *RoomInfo) XXX_Size() int {\n\treturn xxx_messageInfo_RoomInfo.Size(m)\n}\nfunc (m *RoomInfo) XXX_DiscardUnknown() {\n\txxx_messageInfo_RoomInfo.DiscardUnknown(m)\n}\n\nvar xxx_messageInfo_RoomInfo proto.InternalMessageInfo\n\nfunc (m *RoomInfo) GetId() string {\n\tif m != nil {\n\t\treturn m.Id\n\t}\n\treturn \"\"\n}\n\nfunc (m *RoomInfo) GetAddr() string {\n\tif m != nil {\n\t\treturn m.Addr\n\t}\n\treturn \"\"\n}\n\ntype Response struct {\n\tCode                 int32    `protobuf:\"varint,1,opt,name=code,proto3\" json:\"code,omitempty\"`\n\tMsg                  string   `protobuf:\"bytes,2,opt,name=msg,proto3\" json:\"msg,omitempty\"`\n\tXXX_NoUnkeyedLiteral struct{} `json:\"-\"`\n\tXXX_unrecognized     []byte   `json:\"-\"`\n\tXXX_sizecache        int32    `json:\"-\"`\n}\n\nfunc (m *Response) Reset()         { *m = Response{} }\nfunc (m *Response) String() string { return proto.CompactTextString(m) }\nfunc (*Response) ProtoMessage()    {}\nfunc (*Response) Descriptor() ([]byte, []int) {\n\treturn fileDescriptor_c5fd27dd97284ef4, []int{1}\n}\n\nfunc (m *Response) XXX_Unmarshal(b []byte) error {\n\treturn xxx_messageInfo_Response.Unmarshal(m, b)\n}\nfunc (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {\n\treturn xxx_messageInfo_Response.Marshal(b, m, deterministic)\n}\nfunc (m *Response) XXX_Merge(src proto.Message) {\n\txxx_messageInfo_Response.Merge(m, src)\n}\nfunc (m *Response) XXX_Size() int {\n\treturn xxx_messageInfo_Response.Size(m)\n}\nfunc (m *Response) XXX_DiscardUnknown() {\n\txxx_messageInfo_Response.DiscardUnknown(m)\n}\n\nvar xxx_messageInfo_Response proto.InternalMessageInfo\n\nfunc (m *Response) GetCode() int32 {\n\tif m != nil {\n\t\treturn m.Code\n\t}\n\treturn 0\n}\n\nfunc (m *Response) GetMsg() string {\n\tif m != nil {\n\t\treturn m.Msg\n\t}\n\treturn \"\"\n}\n\nfunc init() {\n\tproto.RegisterType((*RoomInfo)(nil), \"register.RoomInfo\")\n\tproto.RegisterType((*Response)(nil), \"register.Response\")\n}\n\nfunc init() {\n\tproto.RegisterFile(\"room.proto\", fileDescriptor_c5fd27dd97284ef4)\n}\n\nvar fileDescriptor_c5fd27dd97284ef4 = []byte{\n\t// 215 bytes of a gzipped FileDescriptorProto\n\t0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xb1, 0x4e, 0xc3, 0x30,\n\t0x10, 0x86, 0x49, 0x28, 0x25, 0xbd, 0x01, 0xa1, 0x9b, 0x2a, 0xa6, 0xca, 0x13, 0x93, 0x83, 0x5a,\n\t0xf1, 0x02, 0x2d, 0x03, 0x2c, 0x0c, 0x16, 0x13, 0x9b, 0x1b, 0x1f, 0xc1, 0x12, 0xee, 0x45, 0x77,\n\t0x66, 0xe0, 0x85, 0x78, 0x4e, 0x14, 0x2b, 0x91, 0x18, 0x61, 0xf2, 0xa7, 0xdf, 0xfa, 0xf4, 0x49,\n\t0x07, 0x20, 0xcc, 0xc9, 0x0e, 0xc2, 0x99, 0xb1, 0x11, 0xea, 0xa3, 0x66, 0x12, 0x63, 0xa1, 0x71,\n\t0xcc, 0xe9, 0xe9, 0xf4, 0xc6, 0x78, 0x05, 0x75, 0x0c, 0xeb, 0x6a, 0x53, 0xdd, 0xae, 0x5c, 0x1d,\n\t0x03, 0x22, 0x2c, 0x7c, 0x08, 0xb2, 0xae, 0xcb, 0x52, 0xd8, 0xdc, 0x41, 0xe3, 0x48, 0x07, 0x3e,\n\t0x29, 0x8d, 0xff, 0x1d, 0x07, 0x2a, 0xc6, 0x85, 0x2b, 0x8c, 0xd7, 0x70, 0x9e, 0xb4, 0x9f, 0x94,\n\t0x11, 0xb7, 0xdf, 0x15, 0x2c, 0xc6, 0x04, 0x6e, 0x61, 0x79, 0x10, 0xf2, 0x99, 0x10, 0xed, 0xdc,\n\t0xb7, 0x73, 0xfc, 0xe6, 0xf7, 0x36, 0x05, 0xcc, 0x19, 0xde, 0xc3, 0xea, 0x91, 0xbc, 0xe4, 0x3d,\n\t0xf9, 0xfc, 0x0f, 0x6d, 0x07, 0x97, 0x0f, 0xa4, 0x59, 0xf8, 0xeb, 0xef, 0xd2, 0xde, 0xbc, 0x6e,\n\t0xfa, 0x98, 0xdf, 0x3f, 0x8f, 0xb6, 0xe3, 0xd4, 0xbe, 0x90, 0x7e, 0xf8, 0xc3, 0x73, 0xdb, 0x71,\n\t0x1a, 0xbc, 0x6a, 0x5b, 0x0e, 0x77, 0x5c, 0x96, 0x67, 0xf7, 0x13, 0x00, 0x00, 0xff, 0xff, 0xb6,\n\t0xf4, 0x05, 0x73, 0x4d, 0x01, 0x00, 0x00,\n}\n
PS C:\Users\sia\GolandProjects\compass\proto>
```

**Comment by dsnet** [comment]
Can you try `protoc-gen-go@v1.4.0-rc.4`?

**Comment by Badgain** [comment]
Faced with the same problem. 
I dropped HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor\AutoRun value and problem was solved

**Comment by IvanTvardovsky** [comment]
> Faced with the same problem. I dropped HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor\AutoRun value and problem was solved

helped, thanks a lot

**Comment by FlameJoy** [comment]
> Faced with the same problem. I dropped HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor\AutoRun value and problem was solved

Win 11 - same problem, same decision, thx
