### ISSUE TITLE
reflect/protoreflect: better document conversion between DescriptorProto and Descriptor

### ISSUE THREAD

**Issue by ribrdb** [golang/protobuf#1048]
**Is your feature request related to a problem? Please describe.**
protoreflect.Descriptors say they wrap a corresponding DescriptorProto, but there's no way to access that raw proto. In particular that would be helpful because I can easily marshal the pb to text for debugging, but there doesn't seem to be any way to do the same with a protoreflect.Descriptor.

**Describe the solution you'd like**
The Descriptor interface could have a new method such as
```go
  DescriptorProto() ProtoMessage
```

**Comment by ribrdb** [comment]
Hmm, actually it seems like there's other important use cases for getting the actual proto, such as sending the descriptor over grpc.

**Comment by dsnet** [comment]
The [`protodesc`](https://pkg.go.dev/google.golang.org/protobuf/reflect/protodesc) package converts a `protoreflect.XXXDescriptor` to/from the descriptor proto message forms. Does that do what you want?

**Comment by ribrdb** [comment]
ah yeah, thanks. I thought I had to be missing something.
Maybe the protoreflect docs should mention this package somewhere?

**Comment by dsnet** [comment]
Would https://golang.org/cl/221611 suffice?

**Comment by dsnet** [comment]
Closing as cl/221611 is submitted.
