### ISSUE TITLE
cannot find package "google/api"

### ISSUE THREAD

**Issue by bfosberry** [golang/protobuf#105]
```
myapp.pb.go:82:8: cannot find package "google/api" in any of:
	/usr/local/go/src/google/api (from $GOROOT)
	/home/bfosberry/.go/src/google/api (from $GOPATH)
```

The generator has stopped commenting out the discarded and un-used import, and now requires it. This results in our protoc failing to build. 

It seems related to this change:

https://github.com/golang/protobuf/commit/a1dfa5ef89a13a0aa4be5a6f81179db10bfeea36#diff-8c603013608023320d5242916c4ea03bR1281

**Comment by dsymonds** [comment]
You need to have imported protos available somehow. Either drop the import (if it is unused), or make the relevant .proto and its generated code accessible.

**Comment by bfosberry** [comment]
The issue is it's code used in the proto file only for generation, not in the generated file go file, so when the import gets passed into the generated go file, it breaks. We build using a -I flag to provide a source o the google/api proto, but beyond generation its not used. Whats the suggested approach for this to avoid that import getting generated?

**Comment by dsymonds** [comment]
I understand; my previous comment mentions the two possible approaches.

Because of how file descriptors work, there's really no such thing as "not in the generated file". If it's imported in the .proto then it'll be in the binary.
