### ISSUE TITLE
protoc-gen-go-grpc: program not found or is not executable when using APIv2

### ISSUE THREAD

**Issue by AyushG3112** [golang/protobuf#1053]
`go version`: go version go1.14 linux/amd64

go.mod

``` go
module [redacted]

go 1.14

require (
	github.com/golang/protobuf v1.4.0-rc.2
	google.golang.org/grpc v1.27.1
	google.golang.org/protobuf v1.20.0 // indirect
)
```

I installed `protoc-gen-go` via:

``` console
go get google.golang.org/protobuf/cmd/protoc-gen-go
```

I am running the following command:

``` console
protoc -I ./src/pbdefs/protos/ --go-grpc_out=. src/pbdefs/protos/*.proto
```

to generate my GRPC output files from `.proto` files, with I am getting  an error

```
protoc-gen-go-grpc: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--go-grpc_out: protoc-gen-go-grpc: Plugin failed with status code 1.
```

**Comment by AyushG3112** [comment]
OK, just found out, as per https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.20.0

> The v1.20 `protoc-gen-go` does not support generating gRPC service definitions. In the future, gRPC service generation will be supported by a new protoc-gen-go-grpc plugin provided by the Go gRPC project.
>
>The `github.com/golang/protobuf` version of protoc-gen-go continues to support gRPC and will continue to do so for the foreseeable future.

**Comment by HakShak** [comment]
For those we find this, watch here for the gRPC support: https://github.com/grpc/grpc-go/pull/3453

**Comment by dsa0x** [comment]
> OK, just found out, as per https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.20.0
> 
> > The v1.20 `protoc-gen-go` does not support generating gRPC service definitions. In the future, gRPC service generation will be supported by a new protoc-gen-go-grpc plugin provided by the Go gRPC project.
> > The `github.com/golang/protobuf` version of protoc-gen-go continues to support gRPC and will continue to do so for the foreseeable future.

You found out. How did you solve it please???

**Comment by dbyington** [comment]
If you stumbled upon this issue, you're probably want to do this:
```
go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
```

**Comment by manjutengale** [comment]
@dbyington thank you

**Comment by LordMoMA** [comment]
I used the official:

protoc --go_out=. --go_opt=paths=source_relative \
    --go-grpc_out=. --go-grpc_opt=paths=source_relative \
    routeguide/route_guide.proto

it worked in the official file, not workable in mine after I changed the "routeguide/route_guide.proto" into my own file name
