### ISSUE TITLE
Can't parse Services from ProtoSet

### ISSUE THREAD

**Issue by utrack** [golang/protobuf#1057]
Hi! I've hit a weird bug when working on our proto compiler, wonder if anyone else has encountered it?

I have a proto with Service defined:
```
service Foo {
  rpc Search(BulletList) returns (BulletList) {
    option (google.api.http) = {
      post : "/navi/v1/catalog/search"
      body : "*"
    };
  }
}
```

I invoke `protoc` using my own plugin.

If I invoke `protoc` on raw protofiles, then Service is there.
But, if I compile protoset like this: `protoc --proto_path=. --descriptor_set_out=proto.bin --include_imports ./**/*.proto`
then I get a file with all the messages, but services are empty. Why could it happen?

I can read and inspect the resulting ProtoSet in grpc_cli successfully (service is there).

relevant snip from a plugin:
```
import (
	"fmt"
	"io"
	"io/ioutil"

	"github.com/golang/protobuf/proto"
	plugin "github.com/golang/protobuf/protoc-gen-go/plugin"
)

// codegenParseRequest parses a code generator request from a proto Message.
// grpc-gateway/internal/codegenerator
func codegenParseRequest(r io.Reader) (*plugin.CodeGeneratorRequest, error) {
	input, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, fmt.Errorf("failed to read code generator request: %v", err)
	}
	req := new(plugin.CodeGeneratorRequest)
	if err = proto.Unmarshal(input, req); err != nil {
		return nil, fmt.Errorf("failed to unmarshal code generator request: %v", err)
	}
	fmt.Println(req.GetProtoFile()[0].Service)
	return req, nil
}
```

**Comment by dsnet** [comment]
I think this is a question for how `protoc` operates and should be filed at github.com/protocolbuffers/protobuf. It seems that the only tangential relationship to this project is the fact that this is written in Go.
