### ISSUE TITLE
Json tags missing for auto generated fields in the struct

### ISSUE THREAD

**Issue by mnkg561** [golang/protobuf#1058]
For some reason, I'm not getting json tags for auto generated fields(state, sizeCache and unknownFields). Anything specific I need to specify in the .proto files to get the json tag `json:_` for those?

Can you please let me know if I'm missing something here?

My generated file looks like this

```
type Cluster struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//Name contains cluster name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	//Type contains kubernetes cluster installation type. ex: AWS, GCP
	// +optional
	Cloud string `protobuf:"bytes,2,opt,name=cloud,proto3" json:"cloud,omitempty"`
	//Config contains info to connect to the target cluster
	//This is same as config struct in https://github.com/kubernetes/client-go/blob/master/rest/config.go
	// but have to define it again here with whatever we need
	// +optional
	Config *Config `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
}
```

and I used this command to generate the files
```
protoc --go_out=paths=source_relative:. pkg/proto/cluster/cluster.proto
```

I have 1.20.1 version if that matters
```
mtvl15367e28a:manager nmogulla$ go install google.golang.org/protobuf/cmd/protoc-gen-go
go: finding google.golang.org/protobuf v1.20.1
go: downloading google.golang.org/protobuf v1.20.1
go: extracting google.golang.org/protobuf v1.20.1
mtvl15367e28a:manager nmogulla$ 
```

**Comment by cybrcodr** [comment]
Those are unexported fields.  Why do you need the `json` tags on those unexported fields?

Also, note that the `json` tags are a deprecated API.  See https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.20.0#v1.20-deprecated-generated.

**Comment by mnkg561** [comment]
My use case is to use this same struct in the kubernetes CRD controller too and CRD specs are auto generated based on the kubebuilder annotations in the struct. Kubebuilder is not able to auto generate anything due to json tags missing on some of those fields in the struct. Its mandatory to include json tags for kube builder code generator.

**Comment by mnkg561** [comment]
The main reason why i used latest protobuf-go version is to retain the comments as per this issue:
https://github.com/golang/protobuf/issues/666. If comments can be retained in other older versions, i can use older version for now unless if there are any other flags i can provide to get the json tags for each field.

**Comment by dsnet** [comment]
This sounds like something to file against the Kubernetes CRD. The Go protobuf protobuf project has always reserved the right to add/modify/remove XXX prefixed fields. Any attempts to depend on such fields is beyond our responsibility of support.

**Comment by mnkg561** [comment]
Based on the release notes from 2nd major revision which is "protobuf/cmd/protoc-gen-go", golang/protobuf/protoc-gen-go will continue to support old way of generation for foreseeable future which does include json tags for auto generated fields.

P.S: Now, if i think about is, this issue/question should have been created in other repo  "protobuf/cmd/protoc-gen-go" and not here. Thank you!!
