### ISSUE TITLE
DynamicMessage

### ISSUE THREAD

**Issue by albertog** [golang/protobuf#106]
Exists a plan to implement this feature similarity to java. Or can you point me a example or tutorial to deserialize a message with only data a his generated descriptor dinamically.

thanks

**Comment by dsymonds** [comment]
We don't support that.

**Comment by ethernetdan** [comment]
@dsymonds: Is DynamicMessage completely off the roadmap of this implementation? I do see that encoding/decoding are pretty tightly tied to the field layout of structs.

**Comment by dsymonds** [comment]
It's pretty unlikely to be implemented.
