### ISSUE TITLE
How to go from serialized fully-contained FileDescriptorSet to {Extension,Message}TypeResolver?

### ISSUE THREAD

**Issue by bufdev** [golang/protobuf#1065]
I may just be missing something here.

- Say I have a fully-contained `FileDescriptorSet`, created with `protoc --include_imports`, i.e. a slice of `[]*descriptorpb.FileDescriptorProtos`.
- I want to be able to go from this, to an `protoreflect.ExtensionTypeResolver` and `protoreflect.MessageTypeResolver`, for use in i.e. `protojson.MarshalOptions`, so I can marshal messages using `descriptorpb.*DescriptorProto` types from another location/off the wire (i.e. not loaded into Golang via imports).

Is there a way to do this?

Here's my understanding:

- `protoreflect.ExtensionTypeResolver` and `protoreflect.MessageTypeResolver` effectively require you to create an instance of `*protoreflect.Types`.
- To populate a new instance of `*protoreflect.Types`, you need to call the functions `RegisterEnum`, `RegisterMessage`, and `RegisterExtension`.
- These methods all take an instance of `protoreflect.*Type`, not `protoreflect.*Descriptor`, which require a Golang type, not a `descriptorpb.*DescriptorProto` type off the wire.

Even if these functions were "relaxed" to just require the `protoreflect.*Descriptor` types (assuming not possible), you'd have another issue:

- To get the `protoreflect.*Descriptor` types, you need to go from a `*descriptorpb.FileDescriptorProto` to `protoreflect.FileDescriptor`.
- To do this, you assumedly should use `protodesc.NewFile`.
- `protodesc.NewFile` takes in a `protodesc.Resolver`, which effectively means an instance of `*protoregistry.Files`.
- To create a populated `*protoregistry.Files`, you need to call the function `RegisterFile`, which itself takes in a `protoreflect.FileDescriptor`. So this is a chicken or egg problem.

What am I missing?

**Comment by neild** [comment]
To create `FileDescriptor`s from `FileDescriptorProto`s:

1. Start with an empty `protoregistry.Files`.
2. Use `protodesc.NewFile` to convert each `FileDescriptorProto` to a `FileDescriptor`.
    2(a). Pass the `protoregistry.Files` to `NewFile`.
    2(b). Register each `FileDescriptor` in the `protoregistry.Files` immediately after creating it.
    2(c). Note that you're responsible for processing the files in dependency order.

Perhaps there should be a function in `protodesc` that takes a `FileDescriptorSet` and does this for you, but it's pretty straightforward.

To create a type resolver, you need to associate descriptors with a concrete implementation. The `dynamicpb` package can provide a concrete implementation for arbitrary types if you don't have anything else.

You can either implement the `{Extension,Message}TypeResolver` interfaces yourself, or iterate over all the descriptors and add corresponding types to a `protoregistry.Types`.

**Comment by neild** [comment]
Perhaps `dynamicpb` should have a function which takes a `*protoregistry.Types` and returns a value that implements `protoregistry.{Extension,Message}TypeResolver`. Again this is pretty straightforward, but having a canonical example might be useful.

**Comment by bufdev** [comment]
That's all really helpful. I didn't see the `dynamicpb` package

Couple notes from this:

- Is there any need to worry about `RegisterEnumType`? The `dynamicpb` package only seems to cover messages and extensions. I can probably answer this myself but figured you'd likely know :-)
- I would say it would be very helpful to have a single, correct implementation for the above `protodesc.NewFile` logic within `protodesc` itself. Perhaps `protodesc.NewFiles` that takes a slice of `*descriptorpb.FileDescriptorProtos`, and does the above? This will definitely be used by others, and could be a common source of errors if not done properly.

**Comment by neild** [comment]
Nothing in the `google.golang.org/protobuf` module uses the enum registry. If you don't have a need for it yourself, you can ignore it. The `dynamicpb` package doesn't provide a dynamic enum at the moment because we didn't see a need for it, although it's something that could be added in the future.

**Comment by dsnet** [comment]
Given that https://go-review.googlesource.com/c/protobuf/+/226237 is merged, anything more to do here?

**Comment by bufdev** [comment]
Assuming RegisterEnumType won’t be added, yep I think all good
