### ISSUE TITLE
jsonpb: `Marshaler.marshalValue()` incorrectly marshals nil slice elements

### ISSUE THREAD

**Issue by dragonsinth** [golang/protobuf#1067]
#1066 

**What version of protobuf and what language are you using?**
master, golang

**What did you do?**
Tried to jsonpb marshal a protobuf with a repeated message field that contained a `nil` element in Go.

**What did you expect to see?**
An error indicating that this is illegal.

**What did you see instead?**
The nil element was translated into JSON as a `null` value.

**Comment by dsnet** [comment]
Thanks for the issue, but the `jsonpb` implementation is no longer maintained. Please use the [`protojson`](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson?tab=doc) package instead. It correctly handles this case (where it treats a nil message within a repeated field as simply being an empty message.
