### ISSUE TITLE
How to generate grpc service with the new module v1.4.0-rc.4

### ISSUE THREAD

**Issue by nigeltiany** [golang/protobuf#1068]
This is what I tried
```bash
protoc --proto_path=. \
--plugin="protoc-gen-go-grpc=/usr/local/bin/protoc-gen-go" \
--go-grpc_out=./lang/go/api api.proto
```
```
go build -o protoc-gen-go-grpc
mv ./protoc-gen-go-grpc /usr/local/bin
protoc --proto_path=. \
--go-grpc_out=./lang/go/api api.proto
```
GRPC services are not generated

**Comment by dsnet** [comment]
v1.4.0 still produces grpc bindings the same way as the versions below v1.4.0. That is:
```
protoc --go_out=plugins=grpc:. *.proto
```

**Comment by nigeltiany** [comment]
Using the recommended: https://github.com/protocolbuffers/protobuf-go does not accept the plugin option

**Comment by nigeltiany** [comment]
Nevermind. Just saw this

> Code generated by either plugin should be compatible with either module.
