### ISSUE TITLE
jsonpb: panic when attempting to Marshal Any

### ISSUE THREAD

**Issue by froodian** [golang/protobuf#1074]
Apologies if this is simply something I'm doing incorrectly, but I can't seem to get the json representation for an Any field?  The following example panics, like `panic: reflect.Value.Interface: cannot return value obtained from unexported field or method`. Is there something I am doing wrong here?

```
import (
	"bytes"
	"github.com/golang/protobuf/jsonpb"
	"github.com/golang/protobuf/ptypes"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
)

buffer := &bytes.Buffer{}
pbAny, _ := ptypes.MarshalAny(&wrappers.StringValue{Value: "hello"})
(&jsonpb.Marshaler{}).Marshal(buffer, pbAny)
```

**Comment by dsnet** [comment]
What version of `github.com/golang/protobuf` are you using? I can't reproduce at v1.3.5 or v1.4.0-rc.4

**Comment by froodian** [comment]
Interesting... I thought I was on `v1.4.0-rc.4` already, but I re-pulled to be sure and now it functions, I must have had an outdated package somewhere in my GOPATH. Thanks for the sanity-check.
