### ISSUE TITLE
panic after using google.golang.org/protobuf/cmd/protoc-gen-go

### ISSUE THREAD

**Issue by maoxs2** [golang/protobuf#1083]
**What version of protobuf and what language are you using?**

libprotoc 3.11.4
protoc-gen-go v1.21.0 (from `go install google.golang.org/protobuf/cmd/protoc-gen-go`)

**What did you do?**

run `protoc -I=. --go_out=paths=source_relative:. *.proto` to generate new `types.pb.go`

source code for `types.proto`
```
syntax = "proto3";

package ngtypes;
option go_package = "github.com/ngchain/ngcore/ngtypes";

message Account {
    uint64 num = 1;
    bytes owner = 2; // pk -> balance in anonymous fields
    uint64 nonce = 4;

    bytes contract = 5; // separate the code and state
    bytes state = 6;
}

message BlockHeader {
    uint64 height = 1;
    int64 timestamp = 2;

    bytes prev_block_hash = 3;
    bytes sheet_hash = 4; // assemble vault into block
    bytes trie_hash = 5;

    bytes target = 6;
    bytes nonce = 7;
}

message Sheet {
    map<uint64, Account> accounts = 2;
    map<string, bytes> anonymous = 3;
}

... and other messages in one file. It works while using gogo v1.3
```

**What did you expect to see?**

works fine

**What did you see instead?**

```
panic: runtime error: index out of range [5] with length 0

goroutine 1 [running]:
github.com/ngchain/ngcore/ngtypes.(*Sheet).ProtoReflect(0xc00006c740, 0x0, 0x0)
        C:/Users/C/OneDrive/ngcore/ngtypes/types.pb.go:518 +0x133
google.golang.org/protobuf/proto.MarshalOptions.Marshal(0x100, 0x1744fa0, 0xc00006c740, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Users/C/go/pkg/mod/google.golang.org/protobuf@v1.21.0/proto/encode.go:83 +0x74
github.com/ngchain/ngcore/ngtypes.(*Sheet).CalculateHash(0xc00006c740, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Users/C/OneDrive/ngcore/ngtypes/sheet.go:104 +0xb8
github.com/ngchain/ngcore/ngtypes.init()
        C:/Users/C/OneDrive/ngcore/ngtypes/sheet.go:127 +0x943

```

**Anything else we should know about your project / environment?**

https://code.ngin.cash/C/ngcore/src/commit/d09e1e9a0040d725abc02e04bff04e23cd3ceae5/ngtypes/types.proto

**Comment by dsnet** [comment]
Thanks for the report. However, without an actual program that we can run that reproduces that problem, there's little that we can do.

**Comment by dsnet** [comment]
Have you tried running your program with the race detector? That stack trace is indicative of a problem that can never happen. The panic is apparently coming from [here](https://code.ngin.cash/C/ngcore/src/commit/d09e1e9a0040d725abc02e04bff04e23cd3ceae5/ngtypes/types.pb.go#L518). However, the `file_types_proto_msgTypes` slice is [allocated at init with a size of 8](https://code.ngin.cash/C/ngcore/src/commit/d09e1e9a0040d725abc02e04bff04e23cd3ceae5/ngtypes/types.pb.go#L643
) and it is never cleared afterwards. Therefore, it could only have gotten a length of 0 if there is memory corruption going on in your program.

**Comment by maoxs2** [comment]
Thanks for your answer. I have found my mistake.

I have created some global hash for convinence, like this

```go
// GetGenesisBlock will return a complete sealed GenesisBlock
func GetGenesisBlock() *Block {
	txs := []*Tx{
		GetGenesisGenerateTx(),
	}

	header := &BlockHeader{
		Height:        0,
		Timestamp:     1500000000,
		PrevBlockHash: nil,
		SheetHash:     GenesisSheetHash,
		TrieHash:      NewTxTrie(txs).TrieRoot(),
		Target:        genesisTarget.Bytes(),
		Nonce:         genesisBlockNonce.Bytes(),
	}

	return &Block{
		Network: Network,
		Header:  header,
		Sheet:   GetGenesisSheet(),
		Txs:     txs,
	}
}

// CalculateHash will help you get the hash of block
func (m *Block) CalculateHash() ([]byte, error) {
	raw, err := utils.Proto.Marshal(m)
	if err != nil {
		return nil, err
	}
	hash := sha3.Sum256(raw)
	return hash[:], nil
}

var GenesisBlockHash, _ = GetGenesisBlock().CalculateHash()
```

`Block` is a protobuf message, and these codes are in the same folder with `types.pb.go`.

I fix the bug by changing `var GenesisBlockHash, _ = GetGenesisBlock().CalculateHash()` to `func GetGenesisBlockHash() []byte`

```go
func GetGenesisBlockHash() []byte {
	hash, _ := GetGenesisBlock().CalculateHash()
	return hash
}
```

then it works fine as before.

**Comment by maoxs2** [comment]
But, is there any method to safely create a global variable as I did before? That would be more convenient. This hash will be used many times and I dont wanna calculate it everytime I use the func.
