### ISSUE TITLE
Migrate fuzz to use native go-fuzz

### ISSUE THREAD

**Issue by inferno-chromium** [golang/protobuf#1084]
See
https://github.com/google/oss-fuzz/pull/3633
https://github.com/google/oss-fuzz/pull/3638

Need to update doc, https://github.com/protocolbuffers/protobuf-go/blob/master/internal/fuzz/oss-fuzz-build.sh

**Comment by neild** [comment]
Going to wait for https://github.com/mdempsky/go114-fuzz-build/commit/df9b762fa80f6ffac8a321cc321c23830e6a2617 to appear in the OSS-Fuzz base image, since it simplifies the migration (I think).

**Comment by inferno-chromium** [comment]
Should be there now, i made the build 2-3 hrs back.
You can do 
python infra/helper.py pull_images
and then retry.

**Comment by neild** [comment]
Hmm. Perhaps that change isn't a sufficient fix to build outside of GOPATH, then:

```
++ go-fuzz -tags=protolegacy -func Fuzz -o jsonfuzz.a ./internal/fuzz/jsonfuzz
internal/fuzz/jsonfuzz/fuzz.go:9:2: cannot find package
internal/fuzz/jsonfuzz/fuzz.go:12:2: cannot find package
internal/fuzz/jsonfuzz/fuzz.go:10:2: cannot find package
2020/04/14 22:35:25 failed to build packages:exit status 1
```

**Comment by neild** [comment]
Ah, never mind, I think the problem is that I had an old version of oss-fuzz.

**Comment by inferno-chromium** [comment]
:) yes since it worked for me for other project - https://github.com/google/oss-fuzz/pull/3646

**Comment by inferno-chromium** [comment]
i think it is loading fuzz.go correctly but failing on the imports, maybe they need to "go get" explicitly in dockerfile.
