### ISSUE TITLE
Use Custom Type Registry with UnmarshalAny

### ISSUE THREAD

**Issue by Rossiar** [golang/protobuf#1085]
**Is your feature request related to a problem? Please describe.**

The `protoregistry` is a very powerful tool that allows users to register their own types at runtime. I have made use of this feature along with [`protojson.UnmarshalOptions`](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson?tab=doc#UnmarshalOptions) to supply my own `Resolver` that is backed by a `protoregistry.Types` that I fill dynamically with my own types.

Unfortunately I am also using `any.Any` within my message to specify a generic "payload" and when I come to unmarshal that payload I receive `err == protoregistry.NotFound`.
```
var x ptypes.DynamicAny
if err := ptypes.UnmarshalAny(a, &x); err != nil { ... }
fmt.Printf("unmarshaled message: %v", x.Message)
```
This is due to [the use of the `protoregistry.GlobalTypes` inside `ptypes.Empty`](https://github.com/golang/protobuf/blob/v1.4.0/ptypes/any.go#L66)  (which in turn is used by [`ptypes.UnmarshalAny`](https://github.com/golang/protobuf/blob/v1.4.0/ptypes/any.go#L79) to generate an empty `proto.Message` for the type inside the `TypeURL` of the `Any` message).

As described below, I want to be able to inject my own registry and not rely on the global one for resolution.

**Describe the solution you'd like**

I have one way forward and two places it can be added, the solution is to add an `UnmarshalAnyOptions`/`MarshalAnyOptions` with a `Resolver` interface that can be supplied by the user, exactly the same as the implementation in `protojson`.

1. Refactor the api inside `ptypes/any.go` (I assume you do not want to do this)
2. Add this new functionality to the [v2 API types package](https://github.com/protocolbuffers/protobuf-go/tree/master/types)

**Describe alternatives you've considered**

I briefly considered using `protoregistry.GlobalTypes` throughout my application, but it does not support the following use case:

> I have a new version of an existing MessageType (maybe with a field added) that needs to be registered that I want to replace the existing type.

The `protoregistry.GlobalTypes` does not support this because I cannot remove the old entry and if I register the new type it will be ignored with a [type already registered error](https://github.com/protocolbuffers/protobuf-go/blob/v1.20.1/reflect/protoregistry/registry.go#L497).

An alternative solution would be to extend the protoregistry.GlobalTypes to support removal/replacement of types, but this is a much larger change than the one I have proposed here. (although maybe necessary in future).

For now I have simply copied the UnmarshalAny / AnyMessage / Empty methods from the source into my application, where I can use my own registry instead of `protoregistry.GlobalTypes`.

**Additional context**
I am attempting to build a dynamic registry similar to the one mentioned [in this tech blog by Deliveroo](https://deliveroo.engineering/2019/02/05/improving-stream-data-quality-with-protobuf-schema-validation.html#managing-schema-artefacts-and-the-path-towards-a-dynamic-registry).

I am using [this parser](https://pkg.go.dev/github.com/jhump/protoreflect/desc/protoparse?tab=doc#Parser.ParseFiles) to read the protos from a GCS bucket when they are uploaded, and then using them to validate that the structure of incoming events is correct.

I am happy to provide a sample repository if the explanation given here is not sufficient to debug this issue.

**Comment by dsnet** [comment]
Given a manually populated `protoregistry.Types`, would the following work?
```go
var any *apb.Any = ...
mt, err := myResolver.FindMessageByURL(any.GetTypeUrl());
if err != nil {
    log.Fatalf("could not resolve %q: %v", any.GetTypeUrl(), err)
}
m := mt.New().Interface()
if err, _ := proto.Unmarshal(any.GetValue(), m); err != nil {
    log.Fatalf("unmarshal error: %v", err)
}
```

**Comment by Rossiar** [comment]
Thanks this worked for me perfectly, I feel like I should have looked harder now before asking. :D

I'm not sure if it's worth making a doc update to outline the v2 path for `any.Any` type resolution, but if you don't feel it's necessary then I'm happy for this to be closed.

**Comment by dsnet** [comment]
https://go-review.googlesource.com/c/protobuf/+/225298 adds first-class support for well-known types (including Any). I'll keep in mind this issue as I continue to work on it.
