### ISSUE TITLE
wrappers.proto file

### ISSUE THREAD

**Issue by philipgriggs** [golang/protobuf#1087]
The `protobuf/ptypes/wrappers/wrappers.proto` file has disappeared between releases v1.3.5 and v1.4.0. Is is moved somewhere else or is it now deprecated?

https://github.com/golang/protobuf/blob/6c65a5562fc06764971b7c5d05c76c75e84bdbf7/ptypes/wrappers/wrappers.proto

**Comment by neild** [comment]
The canonical source for this file is:
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto

**Comment by dsnet** [comment]
Closing as there is nothing actionable for us here. As mentioned, the canonical source for this file is in the official protobuf toolchain.
