### ISSUE TITLE
Assignment to value returned from protoreflect.Message.Interface() causes panic on next Interface() call 

### ISSUE THREAD

**Issue by skipor** [golang/protobuf#1089]
**What version of protobuf and what language are you using?**
Version: `v1.4.0`, go `1.13.4`

**What did you do?**
I'm implementing fuzzer of proto messages using `protoreflect` package.
While implemented hooks, I got situation when there is `protoreflect` message value `rv protoreflect.Message`, it's underlying value is overwrote  using `rv.Interface()` in one place, then next usage of `rv` in another place causes unexpected and difficult to debug nil-pointer panic somewhere in protobuf package internals.

Here is minimal test, that reproduces problem.
```go
import (
	"testing"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/durationpb"
)

func TestProtoReflectOverwriteByPointer(t *testing.T) {
	d := &durationpb.Duration{Seconds: 1}
	rv := d.ProtoReflect()
	t.Log(rv.Interface())
	*rv.Interface().(*durationpb.Duration) = durationpb.Duration{Seconds: 2}
	t.Log(rv.Interface())
}
```

**What did you expect to see?**
It just works. 

**What did you see instead?**
```
--- FAIL: TestProtoReflectOverwriteByPointer (0.00s)
    protoreflect_test.go:22: seconds:1
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11d1c66]

goroutine 4 [running]:
testing.tRunner.func1(0xc0000d2100)
	/usr/local/Cellar/go/1.13.4/libexec/src/testing/testing.go:874 +0x3a3
panic(0x12250a0, 0x143ac30)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:679 +0x1b2
google.golang.org/protobuf/internal/impl.(*messageState).protoUnwrap(0xc000010900, 0x1244420, 0xc000010900)
	/Users/skipor/dev/pkg/mod/google.golang.org/protobuf@v1.21.0/internal/impl/message_reflect_gen.go:27 +0x26
google.golang.org/protobuf/internal/impl.(*messageState).Interface(0xc000010900, 0x12b1c40, 0xc000010900)
	/Users/skipor/dev/pkg/mod/google.golang.org/protobuf@v1.21.0/internal/impl/message_reflect_gen.go:24 +0x2b
github.com/skipor/scratches.TestProtoReflectOverwriteByPointer(0xc0000d2100)
	/Users/skipor/dev/src/github.com/skipor/scratches/protoreflect_test.go:24 +0x132
testing.tRunner(0xc0000d2100, 0x12752e8)
	/usr/local/Cellar/go/1.13.4/libexec/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/Cellar/go/1.13.4/libexec/src/testing/testing.go:960 +0x350

```
---

If use in this test  Go `reflect` package instead of `protoreflect` it works as expected.
```go
import (
	"reflect"
	"testing"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/durationpb"
)

func TestGoReflectOverwriteByPointer(t *testing.T) {
	d := &durationpb.Duration{Seconds: 1}
        // rv := d.ProtoReflect()
	rv := reflect.ValueOf(d) // Use `reflect`, instead `protoreflect`, everything else is not chagned.
	t.Log(rv.Interface())
	*rv.Interface().(*durationpb.Duration) = durationpb.Duration{Seconds: 2}
	t.Log(rv.Interface())
}
```
So, assignment to `*rv.Interface()` intuitively it seems the only correct solution, when there is need to set value into `protoreflect.Message`, so many people  will have to face this problem.

For those who have faced this problem, a workaround is use `proto.Reset` and `proto.Merge` instead of assignment - this saves unexported field values so doesn't invalidate reflect wrapper.
```
proto.Reset(m.Interface())
proto.Merge(m.Interface(), &durationpb.Duration{Seconds: 2})
```

**Comment by dsnet** [comment]
The issue at hand is that `*(*durationpb.Duration) = durationpb.Duration{...}` performs a shallow copy into the destination, which mutates the unexported fields in ways that violates invariants that the implementation are depending on. It was never intended that shallow-copies be performed on generated message types.

**Comment by skipor** [comment]
> If you run go vet on the code, I believe that it will warn you about the shallow copy.

Seems it don't. Just tested on this example:
```
import (
	"fmt"
	"reflect"
	"sync"

	"google.golang.org/protobuf/types/known/durationpb"
)

func VetCopyMutex() {
	m := sync.Mutex{}
	fmt.Printf("%T", m)
}

func VetDurationCopy() {
	d := &durationpb.Duration{Seconds: 1}
	rv := reflect.ValueOf(d)
	fmt.Println(rv.Interface())
	*rv.Interface().(*durationpb.Duration) = durationpb.Duration{Seconds: 2}
	fmt.Println(rv.Interface())
}
```

`go vet` run reports mutex copy to printf, but do not warn about duration copy.
```
$ go vet
# github.com/skipor/scratches
./protoreflect.go:13:19: call of fmt.Printf copies lock value: sync.Mutex
```
If comment first function with problem, `go vet` passes.
Have tested on go `1.13.4` and `1.14.2`.


> It was never intended that shallow-copies be performed on generated message types.

It is because, it is impossible to support this feature in good enough way?
I believe that people will do this anyway and will face this problem.

If it is not possible to support, I hope, there is a way to make fail message more understandable, not just nil-pointer panic somewhere in internals, this will make problem debug much more happy.

Please, consider to warn about this dangerous behaviour in doc to `Interface()` method.
Also it would be great to provide explicit solution for assigning one `protereflect.Message` value to another in safe and efficient way.

Thanks for `protereflect` again, it's great.

**Comment by dsnet** [comment]
> It is because, it is impossible to support this feature in good enough way?

Prior to stable release, there [used to be a "shallow" merge feature](https://go-review.googlesource.com/c/protobuf/+/213131), but we [removed it because we weren't comfortable with the exact semantics](https://go-review.googlesource.com/c/protobuf/+/219145). It's something I would like to see provided at some point, but getting the semantics right is tricky.

> If it is not possible to support, I hope, there is a way to make fail message more understandable, not just nil-pointer panic somewhere in internals, this will make problem debug much more happy.

I'll see what I can do.

**Comment by dsnet** [comment]
https://go-review.googlesource.com/c/protobuf/+/232339 improves panic messages, in particular it suggests that a nil panic in the message state is likely a result of memory corruption or shallow copies (which itself is a form of memory corruption).
