### ISSUE TITLE
Using go protobuf with proto2 produces 'fileDescriptor0 redeclared in this block' error

### ISSUE THREAD

**Issue by kashishm** [golang/protobuf#109]
I have four proto files in one project, I used to generate go implementaion by running the following commands.
protoc --go_out=../ v1.proto
protoc --go_out=../ v2.proto
protoc --go_out=../ m1.proto
protoc --go_out=../ s1.proto

It has stopped working after I updated {proto,protoc-gen-go} using the following command 
```
go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
```
Stacktrace :
```
v2.pb.go:204: fileDescriptor0 redeclared in this block
	previous declaration at v1.pb.go:1078
m1.pb.go:1258: fileDescriptor0 redeclared in this block
	previous declaration at v2.pb.go:204
s1.pb.go:1257: fileDescriptor0 redeclared in this block
	previous declaration at m1.pb.go:1258
```
protoc version : 2.6.1

**Comment by zeroZshadow** [comment]
Why not compile them all in 1 go? `protoc --go_out=../*.proto`

**Comment by kashishm** [comment]
Thanks. It worked, if I compile using `protoc --go_out=../*.proto`.
