### ISSUE TITLE
proto: Unmarshal does not error if byte slice is nil/empty

### ISSUE THREAD

**Issue by ggordan** [golang/protobuf#1091]
**What version of protobuf and what language are you using?**

- `github.com/golang/protobuf v1.4.0`
- `google.golang.org/protobuf v1.21.0`
- `protoc        v3.11.4`
- `protoc-gen-go v1.21.0`

<details><summary>Contents of go.mod</summary>
<p>

```golang
module test

go 1.14

require (
	github.com/golang/protobuf v1.4.0
	google.golang.org/protobuf v1.21.0
)
```
</p>
</details>

<details><summary>Header of generated file</summary>
<p>

```golang
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: message.proto
```
</p>
</details>

**What did you do?**

<details><summary>message.proto</summary>
<p>

```protobuf
syntax = "proto3";

package example;

option go_package="main";

message Test {
    string hello = 1;
}

```
</p>
</details>

```golang
package main

import "google.golang.org/protobuf/proto"

func main() {
	var t Test
	if err := proto.Unmarshal(nil, &t); err != nil {
		panic(err)
	}
}
```

**What did you expect to see?**

I expected a call to `proto.Unmarshal` to error.

**What did you see instead?**

Call succeeded and resulted in a zero'd message.

**Anything else we should know about your project / environment?**

No

**Comment by dsnet** [comment]
Hi, thanks for the report, but this is working as intended.

The Go type for the first argument is a `[]byte`, where a `nil` slice is semantically equivalent to an empty buffer. In the protobuf wire format, an empty buffer is the proper representation for an empty message.

**Comment by ggordan** [comment]
Thanks for the quick reply @dsnet. I think I've made
