### ISSUE TITLE
Is there a way to extract MethodOption using golang/protobuf v1.4.x or google.golang.org/protobuf v1.2x.x?

### ISSUE THREAD

**Issue by noissefnoc** [golang/protobuf#1097]
I want to extract custom option info from Protocol Buffer's method. Is there a way to extract `MethodOption` using `golang/protobuf` v1.4.x (or `google.golang.org/protobuf` v1.2x.x) reflection?

For example, my proto is following

```proto
rpc GetBook(GetBookRequest) returns (Book) {
  option (google.api.http) = {
    get: "/v1/{name=publishers/*/books/*}"
  };
}
```

and I want to extract the `google.api.http` annotation block info. 

I read [A new Go API for Protocol Buffers - The Go Blog](https://blog.golang.org/protobuf-apiv2) and extract `FieldOptions` success. But I don't know how to extract `MethodOption`.

Looking at past issue, https://github.com/golang/protobuf/issues/794#issuecomment-519649834 is similar to my situation. After this issue, [googleapis/api-linter](https://github.com/googleapis/api-linter) seems to use [jhump/protoreflect](github.com/jhump/protoreflect) with `v1.3.5`. But this decision makes before `v1.4.x` release. Is there any update in `v1.4.x` ?

**Comment by noissefnoc** [comment]
I'm sorry for editing many times. But `MessageOption` case was self resolved. (This occurred because of my `.proto` file misspelling.) But I'm in trouble with `MethodOption`.

**Comment by neild** [comment]
Given a [`protoreflect.MethodDescriptor`](https://pkg.go.dev/google.golang.org/protobuf/reflect/protoreflect?tab=doc#MethodDescriptor), you can get a `MethodOption` in the same way you would for a field:

```go
opts := methodDesc.Options().(*descpb.MethodOptions)
```

One way to get the `MethodDescriptor` is to probably to start with the `FileDescriptor`:

```go
methodDesc := fileDesc.Services().ByName("ServiceName").Methods().ByName("MethodName")
```

To get the `FileDescriptor`, you might look it up in the [`protoregistry`](https://pkg.go.dev/google.golang.org/protobuf@v1.21.0/reflect/protoregistry) package (`protoregistry.GlobalFiles.FindFileByPath(filename)`). The generated `.pb.go` will also contain a package var with the `FileDescriptor`, assuming a recent `proto-gen-go`.

**Comment by noissefnoc** [comment]
Thank you for your kind and quick answer. I can get `MethodOptions` and method option value with `proto.GetExtension` like follows.

```
methodDesc := fileDesc.Services().ByName("ServiceName").Methods().ByName("MethodName").(*descpb.MethodOptions)
optValue := proto.GetExtension(methodDesc, mypb.E_MthdOpt).(*mypb.MtdOpt)
```
This is very helpful. Thanks again!
