### ISSUE TITLE
protojson - support custom message marshalling/unmarshalling

### ISSUE THREAD

**Issue by yinzara** [golang/protobuf#1098]
There are often times a user of the protojson package may want custom unmarshalling/marshalling of certain message types. 

My specific use case of this functionality is to support encoding and decoding of some of the most accepted date types (i.e. https://github.com/googleapis/googleapis/blob/master/google/type/date.proto) into the ISO 8601 format for those types. 

I would also like to support flexible decoding to allow multiple Json values to represent the same deserialized data. (i.e. in this example, the date could be specified as an ISO 8601 string or as an object with a "year", "month" and "day" fields).

Currently this is no functionality that allows this.

**Comment by yinzara** [comment]
I have create an initial suggested implementation for this.
https://go-review.googlesource.com/c/protobuf/+/229557

This PR adds a "Marshallers" parameter to MarshalOptions and an "Unmarshallers" parameter to UnmarshalOptions that allows the user to define custom marshalling/unmarshalling functions for specific message types.  I've added a test case to illustrate the use with a custom message type.

Because this relies on the functionality in "internal/encoding/json" package, I have exposed the Kind type and multiple interfaces in the "protojson" package that correspond to the types defined in the internal package.  Since JSON itself is a well defined standard, the Kind(s) are unlikely to change.

This should provide sufficient flexibility in implementations.

**Comment by neild** [comment]
The purpose of the `protojson` package is to encode and decode the canonical protobuf JSON mapping, as described here and elsewhere:
https://developers.google.com/protocol-buffers/docs/proto3#json

The canonical JSON mapping is a portable format that can be consumed by many different protobuf implementations in many different languages. Producing a custom, non-portable encoding is out of scope for the `protojson` package.

**Comment by dsnet** [comment]
Per [our FAQ](https://developers.google.com/protocol-buffers/docs/reference/go/faq#new-feature):

>The Go implementation of protocol buffers strives to be consistent with the other language implementations. As such, we tend to shy away from feature that are overly specialized to just Go. Go-specific features hinder the goal of protocol buffers being a language-neutral data interchange format.

As @neild mentioned, this feature would 1) be unique to Go, and 2) goes against protobuf's goal of being a playform neutral way to serialize data. As such, we're unable to accept this feature request.

Some of the [well-known types](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf) are blessed in the protobuf-to-JSON specification with special output. If you believe that https://github.com/googleapis/googleapis/blob/master/google/type/date.proto is sufficiently common and special that it should receive special treatment, then you should propose to the protobuf team at https://github.com/protocolbuffers/protobuf/issues that it be blessed. Unless it is codified as being treated special, our hands our bound here with regards to what we can do/accept.

**Comment by dsnet** [comment]
I just noticed that you filed an issue at https://github.com/protocolbuffers/protobuf/issues/7411. I'm going to close this issue here 1) since we won't be adding a general purpose way to over-ride JSON serialization and output something different than what is specified, and 2) if the protobuf team accepts the propose changes, we will implement it. If they do not, then we cannot.

**Comment by yinzara** [comment]
I appreciate the time you spent on responding to me (even if it didn't result in my preferred outcome).  I should have started in the with a WKT proposal originally since that was my primary use case.

If you feel obliged, I would also appreciate your opinion on my proposal in:
https://github.com/protocolbuffers/protobuf/issues/7411
