### ISSUE TITLE
protoc-gen-go: Regression in generated output

### ISSUE THREAD

**Issue by aldelucca1** [golang/protobuf#1100]
**What version of protobuf and what language are you using?**
Version: 1.4 in go

**What did you do?**
Generated protobuf types from a proto containing a grpc service interface

**What did you expect to see?**
Protoc would generate a default implementation of the service interface in the form of
```go
type UnimplementedXXXServer struct {
}
```
with all methods implemented to return an error with code `codes.Unimplemented`.

In addition, the `NewXXXClient` would take an `grpc.ClientConnInterface` instead of the concrete `*grpc.ClientConn`

```go
func NewXXXClient(cc grpc.ClientConnInterface) XXXClient {
	return &xxxClient{cc}
}
```
**What did you see instead?**

Instead there is no **Unimplemented** server type put out and the client stub relies on the `*grpc.ClientConn` directly

```go
func NewXXXClient(cc *grpc.ClientConn) XXXClient {
	return &xxxClient{cc}
}
```
It appears this regression occurred between the 1.3.5 and 1.4.0-rc1 tags

**Comment by dsnet** [comment]
The grpc generator is technically owned by the grpc-go project even though the code is hosted in this repo. We are in the process of transferring code ownership over to grpc-go. I suggest filing a bug at https://github.com/grpc/grpc-go/

**Comment by aldelucca1** [comment]
👍 will do, much appreciated
