### ISSUE TITLE
README: add direct link to the developer guide

### ISSUE THREAD

**Issue by denizetkar** [golang/protobuf#1101]
OS: Windows 10
Go version: 1.14.2

I had my `%GOPATH%` environment variable correctly set up and I downloaded the [protoc for win64 zip file](https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protoc-3.11.4-win64.zip) and unzipped its contents as follows: copied contents of `bin` folder into `%GOPATH%\bin`, copied contents of `include\google` folder into `%GOPATH%\src` as suggested by [this instructive video](https://www.youtube.com/watch?v=uaMyiOFXs5U) due to the desperate lack of documentation for installation. Then again as suggested by the video, I tried to run the following command from cmd terminal: `go get -u -v github.com/golang/protobuf` which produces the following error:
```
github.com/golang/protobuf (download)
package github.com/golang/protobuf: no Go files in D:\Users\deniz\go\src\github.com\golang\protobuf

```

Can someone please explain me in detail how one can install Go language protobuf support in Windows 10?

**Comment by dsnet** [comment]
Does https://developers.google.com/protocol-buffers/docs/reference/go-generated help?

**Comment by denizetkar** [comment]
It does indeed, however it would be much better to have a reference to such an information on the [README file](https://github.com/golang/protobuf/blob/master/README.md). Also even [the link above](https://developers.google.com/protocol-buffers/docs/reference/go-generated) does not describe everything needed. For instance the installation of [protobuf protocol compiler](https://github.com/protocolbuffers/protobuf) which I found this information from the video I mentioned [before](https://github.com/golang/protobuf/issues/1101#issue-605888756).

**Comment by dsnet** [comment]
I'll adjust the README.

**Comment by dsnet** [comment]
This is done.
