### ISSUE TITLE
proto: concurrent map iteration and map write

### ISSUE THREAD

**Issue by awinlei** [golang/protobuf#1107]
**What version of protobuf and what language are you using?**
Version: 3.6.1

I use the proto message 
message Body{
	uint32 ret= 1;
	map<uint32,msg> info= 2;
	uint32 state= 3;
	uint32 state2= 4;
}

I use this message in main process  and send it in network process, then I have this issue:

fatal error: concurrent map iteration and map write

goroutine 43 [running]:
runtime.throw(0x186c838, 0x26)
	/usr/local/go/src/runtime/panic.go:1112 +0x72 fp=0xc00035b838 sp=0xc00035b808 pc=0x435d72
runtime.mapiternext(0xc006d303c0)
	/usr/local/go/src/runtime/map.go:853 +0x552 fp=0xc00035b8b8 sp=0xc00035b838 pc=0x411052
reflect.mapiternext(0xc006d303c0)
	/usr/local/go/src/runtime/map.go:1337 +0x2b fp=0xc00035b8d0 sp=0xc00035b8b8 pc=0x411fcb
reflect.Value.MapKeys(0x14ef500, 0xc005ccef88, 0x195, 0x14ef500, 0xc005ccef88, 0x195)
	/usr/local/go/src/reflect/value.go:1204 +0x10a fp=0xc00035b960 sp=0xc00035b8d0 pc=0x497efa
github.com/golang/protobuf/proto.makeMapMarshaler.func2(0xc005ccef88, 0x1, 0x2)
	/data/workspace/publish/server/code/go/src/github.com/golang/protobuf/proto/table_marshal.go:2319 +0xce fp=0xc00035ba40 sp=0xc00035b960 pc=0x556e1e
github.com/golang/protobuf/proto.(*marshalInfo).size(0xc00617ebd0, 0xc005ccef80, 0x2788040)
	/data/workspace/publish/server/code/go/src/github.com/golang/protobuf/proto/table_marshal.go:183 +0x9d fp=0xc00035baa8 sp=0xc00035ba40 pc=0x52e97d
github.com/golang/protobuf/proto.(*InternalMessageInfo).Size(0x2788040, 0x1b43800, 0xc005ccef80, 0x7f186e7ab0a0)
	/data/workspace/publish/server/code/go/src/github.com/golang/protobuf/proto/table_marshal.go:125 +0x66 fp=0xc00035bad8 sp=0xc00035baa8 pc=0x52e536

**Comment by dsnet** [comment]
Hi, your bug reports is suggestive of a race condition in your own code when you're marshaling a message while also modifying it. Have you tried running your program with the race detector enabled?

Also, the stacktrace is indicative of an old version of the `proto` library, which has completely been rewritten since. Even if this were an issue with the `proto` library, it is unlikely that it still persists in the new implementation.

**Comment by dsnet** [comment]
Closing due to lack of response after a week and that there is nothing actionable for us to do here.
