### ISSUE TITLE
1.4.0 not using google.golang.org/protobuf?

### ISSUE THREAD

**Issue by lizfeed** [golang/protobuf#1110]
I'm taking a look at the release notes and they say after 1.4.0, everything is implemented in terms of the new project. But looking at Encoder and Decoder, both have a const ([`wrapJSONMarshalV2`](https://github.com/golang/protobuf/blob/master/jsonpb/encode.go#L26) and [`wrapJSONUnmarshalV2`](https://github.com/golang/protobuf/blob/disable-html-encoding/jsonpb/decode.go#L25)) that's set to false. Is a future release intending to set this true?

**Comment by dsnet** [comment]
https://github.com/golang/protobuf/releases#v1.4-json-text-serialization states:

> The implementations do not use the new protojson or prototext packages in order to maintain a higher degree of backwards compatibility. Our analysis unfortunately showed us that too many tests rely on their output being stable by performing byte-for-byte comparisons. Even though the compatibility promise gives us the freedom to change the output, we have chosen not to do so for pragmatic reasons. The implementations are now functionally frozen (bugs and all) and will not receive future improvements. Users are encouraged to migrate to the protojson or prototext packages instead.

**Comment by dsnet** [comment]
Closing as there's nothing actionable for us to do here. I wanted to make v1 and thin wrapper of v2, but the amount brittle tests it broke was overwhelming.
