### ISSUE TITLE
grpc code generator in v1.4.0 (and master) is outdated

### ISSUE THREAD

**Issue by menghanl** [golang/protobuf#1111]
**What version of protobuf and what language are you using?**
v1.3.5, v1.4.0 and master

---

Latest commit on tag v1.4.0 is from Nov 2018

https://github.com/golang/protobuf/tree/v1.4.0/protoc-gen-go/grpc
![image](https://user-images.githubusercontent.com/960845/80843466-3dc8c580-8bb9-11ea-941f-19255c9dbefb.png)

---

Latest commit from v1.3.5 is from Jan 2020

https://github.com/golang/protobuf/tree/v1.3.5/protoc-gen-go/grpc
![image](https://user-images.githubusercontent.com/960845/80843398-1245db00-8bb9-11ea-856b-d97abb34c59a.png)

---

Master is missing commits, too

https://github.com/golang/protobuf/tree/master/protoc-gen-go/grpc
![image](https://user-images.githubusercontent.com/960845/80843565-78326280-8bb9-11ea-9abc-cc513ef62e4c.png)

**Comment by dsnet** [comment]
The `protoc-gen-go/grpc` package is dead code. The underlying implementation for grpc is in [`github.com/golang/protobuf/internal/gengogrpc`](https://github.com/golang/protobuf/blob/master/internal/gengogrpc/grpc.go), which at the time created was a direct copy of the code in [`google.golang.org/protobuf/cmd/protoc-gen-go-grpc/internal_gengogrpc`](https://github.com/protocolbuffers/protobuf-go/blob/0232edc1d77867cb7425954dfc6759c90e552d97/cmd/protoc-gen-go-grpc/internal_gengogrpc/grpc.go).

The commit you [think is missing](https://github.com/golang/protobuf/commit/d23c5127dc24889085f8ccea5c9d560a57a879d8#diff-4377492e5c5620bde90e4b987bc5fba9) was simultaneously [committed to the new implementation here](https://github.com/protocolbuffers/protobuf-go/commit/5e73c4cec291ce9a2236b182e17eba758d5bbcfe).

**Comment by menghanl** [comment]
This will break users using `grpc` as a library (instead of using the binary generator). I'm verifying with the user now, in https://github.com/grpc/grpc-go/issues/3591.

But even though using the library isn't expected, was there any particular reason to have outdated code there?
It's an exported package (probably should have been, but..), and I don't see any reason to break it.

**Comment by dsnet** [comment]
> This will break users using grpc as a library (instead of using the binary generator).

If that's the case, then that use case is unfortunately unsupported. Any uses of `generator` as a library has explicitly been stated to be outside our compatibility policy. That said, we may consider making the `grpc` package identical to what it was in v1.3.5 even though it's on the chopping block for being removed in the future.
