### ISSUE TITLE
grpc.ServiceDesc support export

### ISSUE THREAD

**Issue by yankooo** [golang/protobuf#1117]
https://github.com/golang/protobuf/blob/6c66de79d66478d166c7ea05f5d2ccaf016fbd6b/protoc-gen-go/grpc/grpc.go#L170

I'm confused that Why doesn't it support exporting `ServiceDesc`.

**Comment by dsnet** [comment]
I recommend filing this at https://github.com/grpc/grpc-go/issues. Even though the grpc generator is hosted here, the code is owned by a different team.

**Comment by yankooo** [comment]
ok,thanks
