### ISSUE TITLE
how can i define map[string]map[string]string type？

### ISSUE THREAD

**Issue by lddlww** [golang/protobuf#1118]

**Comment by dsnet** [comment]
The protobuf language does not have the concept of a map type as a first-class type. A map is a property of a message field. Therefore it is not possible to express `map[string]map[string]string`.

**Comment by lddlww** [comment]
message Resp{
   map<string,map<string,string>> data =1 ;//error 
}

the data type is map[string]map[string]string in golang

how can i define the data type in protobuf?

**Comment by meling** [comment]
Would this server your need?
```proto
message Resp { map<string, M> data = 1; }

message M { map<string, string> d = 1; }
```

**Comment by lddlww** [comment]
@meling ，
in golang，it would be contains struct：
```
type Resp struct{
    Data  map[string]M
}
type M struct{
   D  map[string]string
}
```
but i want the follow type:
```
 type Resp struct{
   Data map[string]map[string]string
}
```

**Comment by puellanivis** [comment]
You cannot define a map-type as the `value_type`.

The specification directly calls out that the `value_type` cannot be another map type: https://developers.google.com/protocol-buffers/docs/proto3#maps

The best you can do is have a message type that contains a map, and then have a map type from `string→message` as meling pointed you to.

**Comment by dsnet** [comment]
Closing as there is nothing actionable here since this is fundamentally a limitation of the protobuf language. If you want to propose that protobuf maps should allow nested map values, then I recommend opening an issue at https://github.com/protocolbuffers/protobuf
