### ISSUE TITLE
How to handle compatibility issues with v1.4?

### ISSUE THREAD

**Issue by RainbowMango** [golang/protobuf#1126]
The struct type `InternalMessageInfo` has been deprecated by `github.com/golang/protobuf@v1.4.0`: 
https://github.com/golang/protobuf/blob/00998c7dd9d789e353c9518d13864b75cd23c55d/proto/deprecated.go#L85-L92

But there are a whole bunch of modules still using `*.pb.go` file which contains a reference of `InternalMessageInfo`, such as 
- [grpc/grpc-go/health](https://github.com/grpc/grpc-go/blob/a6ab4473c5a469332c1bdee691293affeaaece25/health/grpc_health_v1/health.pb.go#L88)
- [grpc/grpc-go/binary](https://github.com/grpc/grpc-go/blob/a6ab4473c5a469332c1bdee691293affeaaece25/binarylog/grpc_binarylog_v1/binarylog.pb.go#L215)

Kubernetes wants to involve a new module version which depends on `github.com/golang/protobuf@v1.4.0`, but this work has been blocked as several modules in Kubernetes' vendor still referring `InternalMessageInfo`, more details please refer to https://github.com/kubernetes/kubernetes/pull/90582#discussion_r423290877.

Does it's the right approach to update all those modules by re-compile `*.proto`?
If yes, there are two `protoc-gen-go`, [one](https://github.com/protocolbuffers/protobuf-go) and [two](https://github.com/golang/protobuf), which one should I choose? and should I use the latest version?

@dsnet I will be appreciate if you can give some guidence.

**Comment by dsnet** [comment]
> Does it's the right approach to update all those modules by re-compile *.proto?

There shouldn't be a need to regenerate existing `.pb.go` files for things to work with v1.4.0. However, it is certainly recommended to do regenerate with a newer version of `protoc-gen-go`. In what ways was this causing a "compatibility issue"?

The `InternalMessageInfo` is a pseudo-internal type that should be only referenced by generated `.pb.go` files. They are used to implement the `XXX_Marshal`, `XXX_Size`, etc methods. However, the 
[compatibility document](https://github.com/golang/protobuf/tree/v1.3.5#compatibility) explicitly calls out identifiers with an `XXX` prefix as being internal. The v1.3.x runtime used the `XXX` methods to perform serialization, however the v1.4.x runtime uses an entirely different implementation to do its work (but one that should be backwards compatible), so the `XXX` methods are effectively dead code.

> If yes, there are two protoc-gen-go, one and two, which one should I choose? and should I use the latest version?

`github.com/golang/protobuf/protoc-gen-go@v1.4.1` and `google.golang.org/protobuf/cmd/protoc-gen-go@v1.22.0` are identical except that the former has support for grpc bindings, while the latter does not. We are in the process of trying to pass off ownership of the grpc generator over to the grpc-go project.

* If you do not use grpc, I recommend using `protoc-gen-go@v1.22.0`.
* If you use grpc, I recommend using `protoc-gen-go@v1.4.1`. Once https://github.com/grpc/grpc-go/pull/3453 is merged, I recommend eventually migrating to `protoc-gen-go@v1.22.0` and calling the grpc-specific generator to produce grpc bindings.

**Comment by RainbowMango** [comment]
> In what ways was this causing a "compatibility issue"?

I tried to update `github.com/golang/protobuf` to v1.4.0 in Kubernetes, but found a panic. I suggest you can check [the discussion here](https://github.com/kubernetes/kubernetes/pull/90582#discussion_r421901531) for more details.

The panic triggered by `github.com/gogo/protobuf` which called `XXX_Size()` method.

> There shouldn't be a need to regenerate existing .pb.go files for things to work with v1.4.0.

The thing is there are a bunch of `.pb.go` files which generated by older protoc-gen-go, thus the `InternalMessageInfo` is exported, How can we check if the methods of  `InternalMessageInfo` will be called?

Involve @liggitt here too, there is a huge effort to regenerate existing `.pb.go` files.

**Comment by dsnet** [comment]
> The panic triggered by github.com/gogo/protobuf which called XXX_Size() method.

There's the problem. The `gogo/protobuf` module is calling an internal method to this module that is explicitly documented as not for external use:
https://github.com/golang/protobuf/blob/84668698ea25b64748563aa20726db66a6b8d299/proto/table_marshal.go#L2679-L2682

We're technically under no obligation to address this regression, but to ease migration, #1129 adds minimal functionally back to `InternalMessageInfo` so that panics don't happen. Can you verify that it resolves the issues you're encountering?

**Comment by RainbowMango** [comment]
> Can you verify that it resolves the issues you're encountering?

Yes it works! And I answered [here](https://github.com/kubernetes/kubernetes/pull/90582#discussion_r424998496) too.

I'm looking forward to new release now.

**Comment by dsnet** [comment]
[v1.4.2](https://github.com/golang/protobuf/releases/tag/v1.4.2) is released.
