### ISSUE TITLE
[Bug Report]internal compiler error: conflicting package heights 21 and 11

### ISSUE THREAD

**Issue by fwhezfwhez** [golang/protobuf#1128]
- golang 1.12.17 win64
- github.com/golang/protobuf@00998c7dd9d789e353c9518d13864b75cd23c55d

issues:
```go
internal compiler error: conflicting package heights 21 and 11 for path "github.com/golang/protobuf/proto"
```

I fix this by resetting protobuf to older version and guess this bug might occur in latest pr.

```go
cd %GOPATH%/github.com/golang/protobuf
git reset --hard e91709a02e0e8
```

**Comment by dsnet** [comment]
Hi, thanks for the report. This error is clearly indicative of something wrong with the Go toolchain. Given that go1.12 is somewhat dated, I recommend trying to go1.14. If the problem persists, this should be filed against the main Go toolchain.

**Comment by fwhezfwhez** [comment]
@dsnet My company is using go-binary which is supported by go version less than go 1.12.17.
Can't upgrade to go1.14.

**Comment by dsnet** [comment]
I'm sorry to hear that you can't upgrade, but I don't think there's anything actionable for us to do here. This is clearly a Go toolchain bug.

**Comment by fwhezfwhez** [comment]
ok,I'll report error to go repo

**Comment by dsnet** [comment]
Closing as this inactionable.

**Comment by fwhezfwhez** [comment]
@dsnet I'm confused that older protobuf version will not occur this error, but latest will. Even if this bug is produced by go tool chain, but clearly protobuf doesn't upgrade itself compatiblely to some go version.
