### ISSUE TITLE
Is plugin for Go protobuf written in Go?

### ISSUE THREAD

**Issue by Aniket21mathur** [golang/protobuf#1136]
I have observed that the [plugins](https://github.com/protocolbuffers/protobuf/tree/master/src/google/protobuf/compiler) for other languages that protobuf support are written in C++. But in this repository, I don't see any C++ code. 

So the plugin is written in Go? How exactly it interacts with the compiler APIs?

Thanks!

**Comment by dsnet** [comment]
Yes, it's written in Go. See https://github.com/protocolbuffers/protobuf-go/tree/master/cmd/protoc-gen-go

**Comment by dsnet** [comment]
The "API" that it uses to communicate with the compiler are the messages declared in [descriptor.proto](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/descriptor.proto), which essentially describes the protobuf type system in the form of protobuf messages. The `protoc` compiler communicates with the `protoc-gen-go` plugin by passing it a set of descriptor messages via a [`CodeGeneratorRequest`](https://github.com/protocolbuffers/protobuf/blob/39d730dd96c81196893734ee1e075c34567e59ae/src/google/protobuf/compiler/plugin.proto#L67-L96) and the `protoc-gen-go` plugin responds via a [`CodeGeneratorResponse`](https://github.com/protocolbuffers/protobuf/blob/39d730dd96c81196893734ee1e075c34567e59ae/src/google/protobuf/compiler/plugin.proto#L98-L178).

**Comment by Aniket21mathur** [comment]
I see a lot of imports on the plugin side like https://github.com/protocolbuffers/protobuf-go/blob/master/cmd/protoc-gen-go/main.go#L20, where is the source code of these files? Are these files also written in Go?

I am just trying to figure out the difference in plugin for let's say `python` and `Go`. The python [plugin](https://github.com/protocolbuffers/protobuf/tree/master/src/google/protobuf/compiler/python) is written in `C++` and uses modules from the compiler like [code_generator.cc](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/code_generator.cc) and so do the plugins for other languages in the official repo. In any way the `code_generator.cc` file used in `Go`? Can we have a plugin written in `C++` for `Go`? Please correct me If I am missing something.

I am working on to extend protobuf support to a new language. I am planning to write a plugin in C++ as done in most other cases. I am surprised to see the `Go` way, but not able to figure out how exactly it is working.

Thanks!

**Comment by dsnet** [comment]
The entire implementation is in the same repository. [The `compiler/protogen` package is here](https://github.com/protocolbuffers/protobuf-go/tree/master/compiler/protogen).

Essentially, everything under `google.golang.org/protobuf` is relative to https://github.com/protocolbuffers/protobuf-go.

**Comment by dsnet** [comment]
> In any way the code_generator.cc file used in Go? 

No.

> Can we have a plugin written in C++ for Go?

It's technically doable, but I don't see the purpose for it. It be extra maintenance cost for little to no gain.

**Comment by Aniket21mathur** [comment]
> The entire implementation is in the same repository and all in Go. [The `compiler/protogen` package is here](https://github.com/protocolbuffers/protobuf-go/tree/master/compiler/protogen).

Thanks! Just got confused between the 2 different repositories :sweat_smile: .

> It's technically doable, but I don't see the purpose for it. It be extra maintenance cost for little to no gain. You'd also lose access to functionality in the Go standard library for dealing with Go ASTs. It makes sense writing the generator for Go in Go.

Yeah! thanks for explaining.
