### ISSUE TITLE
could not import google.golang.org/protobuf/reflect/protoreflect (no package for import google.golang.org/protobuf/reflect/protoreflect)

### ISSUE THREAD

**Issue by dasuma** [golang/protobuf#1143]
hi, 
i generate de proto.file but when y try the run, the terminal said 
could not import google.golang.org/protobuf/reflect/protoreflect (no package for import google.golang.org/protobuf/reflect/protoreflect)
i try go get google.golang.org/protobuf/reflect/protoreflect but dont work

**Comment by dasuma** [comment]
go get google.golang.org/protobuf/reflect/protoreflect: module google.golang.org/protobuf@upgrade found (v1.24.0), but does not contain package google.golang.org/protobuf/reflect/protoreflect

**Comment by dsnet** [comment]
Hi, that is quite the surprising error you got there. It's almost certainly some time of Go toolchain configuration problem and not something specific to this project.

What version of Go are you using?
What are the exact commands you are using and where are you running them from?
Are you using GOPATH mode or module mode?

**Comment by dasuma** [comment]
> vaya a buscar google.golang.org/protobuf/reflect/protoreflect: módulo google.golang.org/protobuf@upgrade encontrado (v1.24.0), pero no contiene el paquete google.golang.org/protobuf/reflect/protoreflect

**Comment by dsnet** [comment]
Closing as inactionable due to lack of response.

**Comment by Pac23** [comment]
> hi,
> i generate de proto.file but when y try the run, the terminal said
> could not import google.golang.org/protobuf/reflect/protoreflect (no package for import google.golang.org/protobuf/reflect/protoreflect)
> i try go get google.golang.org/protobuf/reflect/protoreflect but dont work

what version of protoc compiler are you using ? because when i used the ubuntu stable bundled apt-get protoc package it generated this and used the newer proto api whereas the current version of the protoc compiler(3.11) from the snap store uses the older proto api for older syntax like proto v2 which does not use the protoreflect package and you have to use older packages like jsonpb,github.com/protobuf etc rather than the newer ones.

**Comment by AlephAlpha** [comment]
I had the same problem, and it turned out that I just forgot to add protobuf to go.mod.

**Comment by samnayak1** [comment]
> I had the same problem, and it turned out that I just forgot to add protobuf to go.mod.

@AlephAlpha how do we do that?
