### ISSUE TITLE
pb to go struct ,can you specify parameters to generate json tag “omitempty”

### ISSUE THREAD

**Issue by fansking** [golang/protobuf#1145]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

when i use pb to go struct. There is a tag like `json:"xxx,omitempty"`
but if I want to send http request,I must use json . **when this field is 0 (int), i can't find this field.** This thing bothered me long time. So, i want to delete 'omitempty'. But i find this tag is hard code!!!! 
https://github.com/golang/protobuf/blob/master/protoc-gen-go/generator/generator.go#L2500

**Describe the solution you'd like**
Add a parameters to control ‘omitempty’ tag generation.

**Comment by neild** [comment]
The way to convert a protobuf message to or from JSON is to use the [`"google.golang.org/protobuf/encoding/protojson"`](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson) package, which will produce a standard JSON serialization form used by all protobuf implementations.

The `json:"..."` field tags are generated for backwards compatibility with code that relies on their presence, but we do not recommend using the `"encoding/json"` package with protobuf messages. I'm sorry, but we're not going to make further changes to the content of those tags.

**Comment by fansking** [comment]
thank you!
