### ISSUE TITLE
proto:can't skip unknown wire type 4

### ISSUE THREAD

**Issue by linww** [golang/protobuf#1147]
I use a http request to receive byte data from a java server in golang client,then it occurs an error:proto, can't skip unknown wire type 4.
BTW,it works well in my local environment and test environment,but it occurs the error when it runs in another test environment.

**Comment by dsnet** [comment]
Hi, without a reproduction, this is pretty close to impossible for us to diagnose.

**Comment by linww** [comment]
> Hi, without a reproduction, this is pretty close to impossible for us to diagnose.

what other information do I need to provide?

**Comment by linww** [comment]
> Hi, without a reproduction, this is pretty close to impossible for us to diagnose.

I marshal the proto object into byte in the java server,and then transfer it in http,then I unmarshal the byte data into object in the golang client.

**Comment by dsnet** [comment]
A high-level description isn't the same thing as a reproduction. Ideally you be able to provide us an actual program to run that reproduces the problem. Before you do that, I suggest that you check other parts of the system. The error you're seeing is indicative of data corruption coming from somewhere else.

**Comment by linww** [comment]
> A high-level description isn't the same thing as a reproduction. Ideally you be able to provide us an actual program to run that reproduces the problem. Before you do that, I suggest that you check other parts of the system. The error you're seeing is indicative of data corruption coming from somewhere else.

it's solved!
thank you!

**Comment by gonzaloserrano** [comment]
how did you solve it? different proto versions in java and go?

**Comment by dsnet** [comment]
Errors of this nature is almost because someone is passing something that is not the wire format to the `proto.Unmarshal`, or having some framing added to the wire format, and forgetting to strip it before passing to `proto.Unmarshal`.

The protobuf wire format does not have any magic numbers to give an obvious error when the input isn't the wire format.
\cc @neild who is consider removing any unmarshal error specific to the wire format since they're almost never useful.

**Comment by gonzaloserrano** [comment]
Understood, thank you very much @dsnet for the quick response

**Comment by linww** [comment]
> how did you solve it? different proto versions in java and go?

the request url is error,so the response of it is in a wrong format,so it can't be unmarshaled into a proto object;
