### ISSUE TITLE
protoc-gen-go: Unable to instal protoc-gen-go in Windows 64bit

### ISSUE THREAD

**Issue by Sreezz** [golang/protobuf#1148]
Hi

I have to generate go file from protofiles. so I have downloaded golang and setup the settings. Also downloaded golang/protobuf and extract the zip file into $GOPATH/src/github.com/golang/. 
Then I run 'go install github.com/golang/protobuf/protoc-gen-go'. 
it is showing following error 

`go\src\github.com\golang\protobuf\protoc-gen-go\main.go:28:2: cannot find package "google.golang.org/protobuf/cmd/protoc-gen-go/internal_gengo" in any of:
        c:\go\src\google.golang.org\protobuf\cmd\protoc-gen-go\internal_gengo (from $GOROOT)
         $GOPATH\go\src\google.golang.org\protobuf\cmd\protoc-gen-go\internal_gengo (from $GOPATH)

go\src\github.com\golang\protobuf\internal\gengogrpc\grpc.go:13:2: cannot find package "google.golang.org/protobuf/compiler/protogen" in any of:
        c:\go\src\google.golang.org\protobuf\compiler\protogen (from $GOROOT)
         $GOPATH\go\src\google.golang.org\protobuf\compiler\protogen (from $GOPATH)

go\src\github.com\golang\protobuf\internal\gengogrpc\grpc.go:15:2: cannot find package "google.golang.org/protobuf/types/descriptorpb" in any of:
        c:\go\src\google.golang.org\protobuf\types\descriptorpb (from $GOROOT)
         $GOPATH\go\src\google.golang.org\protobuf\types\descriptorpb (from $GOPATH)`

I checked downloaded golang/protobuf . Here following folders are missing.
protobuf\cmd\protoc-gen-go\internal_gengo
protobuf\compiler\protogen
protobuf\types\descriptorpb

How to resolve this this. Otherwise how to install protoc-gen-go in windows64

Thanks 
Sree

**Comment by dsnet** [comment]
I don't use windows, but the error is indicative of a setup problem with GOPATH.

**Comment by dsnet** [comment]
Closing as inactionable on our end.

**Comment by puellanivis** [comment]
You are manually installing the code for `protoc-gen-go'` into your GOPATH. That means you are not additionally installing the dependencies on `google.golang.org/protobuf` that the new APIv2 wrapper depends on.

Either also install the `google.golang.org/protobuf` files manually, or do a `go get …` to get the source rather than doing it manually, which will download and install all dependencies into your GOPATH as well.
