### ISSUE TITLE
Omitting default values in JSON representations

### ISSUE THREAD

**Issue by mtsgrd** [golang/protobuf#115]
@dsymonds I see you've done some work on this library, and I'm trying to understand something about jsonpb.go. There's a [note in there that says](https://github.com/golang/protobuf/blob/master/jsonpb/jsonpb.go#L110): ```// TODO: proto3 objects should have default values omitted```. Do you know what specification or reasoning it refers to?

The reason I bring it up is because I make use of the [grpc-gateway](https://github.com/gengo/grpc-gateway/) and its clients aren't aware of default values where keys are missing.

**Comment by dsymonds** [comment]
The spec is https://developers.google.com/protocol-buffers/docs/proto3#json. I'll add a link to the package doc.

It isn't harmful that jsonpb emits default (zero) values; it is just a bit suboptimal.

**Comment by mtsgrd** [comment]
I understand, and I also realize that the including default values becomes inefficient if you have some larger number of fields that are sparsely populated. Thanks for the quick response!
