### ISSUE TITLE
protoc-gen-go: --version should exit 0, not nonzero

### ISSUE THREAD

**Issue by kevinburkemeter** [golang/protobuf#1153]
Currently, if you run `protoc-gen-go --version`, the command prints the version and then exits 1, not 0. 

Fundamentally, we are asking the command for the version and we are getting back the version, so the command is doing what we want. It seems like the right exit code should be 0. `protoc --version` exits with 0, as does `go version`.

**Comment by dsnet** [comment]
Seems reasonable. Would you like to contribute the change? Relevant line is here: https://github.com/protocolbuffers/protobuf-go/blob/b0c4001c72b8713ce4c2f5c72909d0967b22d90a/cmd/protoc-gen-go/main.go#L27

Otherwise I can do it.

**Comment by kevinburkemeter** [comment]
Sure, on it.

**Comment by dsnet** [comment]
Unfortunately, we don't have dual-sync setup for this repository, so you'll need to submit the change through Gerrit. See https://github.com/protocolbuffers/protobuf-go/blob/master/CONTRIBUTING.md

If that's too much setup for a small change, I can make this change.

**Comment by kevinburkemeter** [comment]
Ah, no worries, I have a Gerrit account, give me a few minutes.

**Comment by kevinburkemeter** [comment]
Just submitted on Gerrit and assigned you as a reviewer.
