### ISSUE TITLE
Could not resolve Any message type BoolValue (or any primitive wrapper)

### ISSUE THREAD

**Issue by naoko** [golang/protobuf#1156]
I'm reading JSON file and have proto field type Any.
`jsonpb.Unmarshal(jsonFile, &protoMessage)` works for Any field
```
 "@type": "type.googleapis.com/google.protobuf.Timestamp",
```
as well as 
```
"@type": "type.googleapis.com/google.protobuf.Duration",
```

but it does not work with
```
"@type": "type.googleapis.com/google.protobuf.BoolValue",
```

saying that `could not resolve Any message type: type.googleapis.com/google.protobuf.BoolValue
`
However, when I marshal with 
```
A := &wrappers.BoolValue{Value: true}
any, err := ptypes.MarshalAny(A)
&pb.MyMessage {AnyValue: any}
```
it generates JSON like this
```
"anyValue":{"@type":"type.googleapis.com/google.protobuf.BoolValue","value":true}
```
Could someone point me to the right direction?
Thank you.

**Comment by dsnet** [comment]
Whether the message could be resolved or not depends on whether the message has been linked into your Go binary or not. Try importing "google.golang.org/protobuf/types/wrapperspb" in your main package. So long as your program transitively depends on the generated package for the type, it should appear in the global type registry.

**Comment by naoko** [comment]
Thank you very much! Adding import statement `_ "github.com/golang/protobuf/ptypes/wrappers"` did it.

**Comment by fedemengo** [comment]
```go
type ProtoResolver interface {
	protoregistry.MessageTypeResolver
	protoregistry.ExtensionTypeResolver
	RegisterMessage(mt protoreflect.MessageType) error
}

var protoResolver ProtoResolver

func init() {
	protoResolver = new(protoregistry.Types)

	type1 := protoimpl.X.MessageTypeOf(&proto.Type1{})
	type2 := protoimpl.X.MessageTypeOf(&proto.Type2{})

	protoResolver.RegisterMessage(type1)
	protoResolver.RegisterMessage(type2)
}

func f() {
	unmarshaler := protojson.UnmarshalOptions{
		Resolver: protoResolver,
	}

        if err := unmarshaler.Unmarshal(body, &data); err != nil {
		return fmt.Errorf("cannot unmarshal: %w", err)
	}
}
```
