### ISSUE TITLE
Weird chars after proto message is marshalled

### ISSUE THREAD

**Issue by nebiros** [golang/protobuf#1160]
**What version of protobuf and what language are you using?**
Version: v1.4.2

**What did you do?**
With the proto file below, we are sending a message (`PubsubMessage`), `PubsubMessage` has a field `data` as `bytes`, we filled from GO with a `[]byte` from a JSON object, when the `proto.Message` is "marshalled" a lot of weird chars are appended to the `[]byte`. Here's the GO source:

Original `Data` field, `[]byte` printed as `string`:

```
{"some_random_id":"410a64c3-43ca-42f1-b18a-0eb0374b0b65","another_random_id":"f06f015a-9f36-41bd-9dd3-b2b5fe44fa90"}
```

After `marshalAppend (proto/wire.go:32)` func is executed, `[]byte` printed as `string`:

```
x{"some_random_id":"410a64c3-43ca-42f1-b18a-0eb0374b0b65","another_random_id":"f06f015a-9f36-41bd-9dd3-b2b5fe44fa90"}�������
```

The GO source:

```go
type PubsubMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data        []byte               `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Attributes  map[string]string    `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	PublishTime *timestamp.Timestamp `protobuf:"bytes,3,opt,name=publish_time,json=publishTime,proto3" json:"publish_time,omitempty"`
}
```

The proto source:

```proto
syntax = "proto3";

option go_package = "proto/pub";

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

service Pub {
  rpc CreateTopic(CreateTopicRequest) returns (Topic) {}
  rpc Publish(PublishRequest) returns (google.protobuf.Empty) {}
  rpc GetTopic(GetTopicRequest) returns (Topic) {}
}

message Topic {
  string name = 1;
}

message CreateTopicRequest {
  Topic topic = 1;
}

message GetTopicRequest {
  string topic = 1;
}

message PublishRequest {
  string topic = 1;
  repeated PubsubMessage messages = 2;
}

message PublishResponse {
  repeated string message_ids = 1;
}

message PubsubMessage {
  bytes data = 1;
  map<string, string> attributes = 2;
  google.protobuf.Timestamp publish_time = 3;
}
```

**What did you expect to see?**
No weird chars

**What did you see instead?**
Original `Data` field, `[]byte` printed as `string`:

```
{"some_random_id":"410a64c3-43ca-42f1-b18a-0eb0374b0b65","another_random_id":"f06f015a-9f36-41bd-9dd3-b2b5fe44fa90"}
```

After `marshalAppend (proto/wire.go:32)` func is executed, `[]byte` printed as `string`:

```
x{"some_random_id":"410a64c3-43ca-42f1-b18a-0eb0374b0b65","another_random_id":"f06f015a-9f36-41bd-9dd3-b2b5fe44fa90"}�������
```

**Anything else we should know about your project / environment?**
- go version go1.14.4 darwin/amd64
- github.com/golang/protobuf v1.4.2
- google.golang.org/protobuf v1.23.0

[protobuf-error-marshall.zip](https://github.com/golang/protobuf/files/4848335/protobuf-error-marshall.zip)

**Comment by dsnet** [comment]
This is certainly strange behavior, but without a runnable reproduction, there isn't much that we can do on our end.

**Comment by nebiros** [comment]
> This is certainly strange behavior, but without a runnable reproduction, there isn't much that we can do on our end.

Should I provide the code?

**Comment by dsnet** [comment]
Yes, please.

**Comment by nebiros** [comment]
> Yes, please.

Gonna isolate it, hold on

**Comment by nebiros** [comment]
> Yes, please.

[protobuf-error-marshall.zip](https://github.com/golang/protobuf/files/4848335/protobuf-error-marshall.zip), it's gonna thrown an error about the service, but, if you go step-by-step until `marshalAppend` at `proto/wire.go:32` you will see the weird chars

**Comment by dsnet** [comment]
This is working as expected. The "weird chars" at the end is the serialized message in the binary format.

The exact string being serialized is: "\nt{\"another_random_id\":\"1f22ad00-04ba-4db9-ae32-5e0d007ee1f5\",\"some_random_id\":\"5d0e1133-48f3-4ce0-a4de-871d265940f5\"}\x1a\v\b\xb9\xda\xe9\xf7\x05\x10\x82\xab\x98+"

Passing this data to to the [`protopack`](https://pkg.go.dev/google.golang.org/protobuf/testing/protopack?tab=doc) package shows that this is indeed valid wire data:
```
$ cat dump | pbdump -messages 3
Message{
	Tag{1, Bytes}, Bytes(`{"another_random_id":"1f22ad00-04ba-4db9-ae32-5e0d007ee1f5","some_random_id":"5d0e1133-48f3-4ce0-a4de-871d265940f5"}`),
	Tag{3, Bytes}, LengthPrefix(Message{
		Tag{1, Varint}, Uvarint(1593470265),
		Tag{2, Varint}, Uvarint(90576258),
	}),
}
```

**Comment by nebiros** [comment]
> This is working as expected. The "weird chars" at the end is the serialized message in the binary format.
> 
> The exact string being serialized is: "\nt{"another_random_id":"1f22ad00-04ba-4db9-ae32-5e0d007ee1f5","some_random_id":"5d0e1133-48f3-4ce0-a4de-871d265940f5"}\x1a\v\b\xb9\xda\xe9\xf7\x05\x10\x82\xab\x98+"
> 
> Passing this data to to the [`protopack`](https://pkg.go.dev/google.golang.org/protobuf/testing/protopack?tab=doc) package shows that this is indeed valid wire data:
> 
> ```
> $ cat dump | pbdump -messages 3
> Message{
> 	Tag{1, Bytes}, Bytes(`{"another_random_id":"1f22ad00-04ba-4db9-ae32-5e0d007ee1f5","some_random_id":"5d0e1133-48f3-4ce0-a4de-871d265940f5"}`),
> 	Tag{3, Bytes}, LengthPrefix(Message{
> 		Tag{1, Varint}, Uvarint(1593470265),
> 		Tag{2, Varint}, Uvarint(90576258),
> 	}),
> }
> ```

Thank you. And how I can unserialized it to get only the `[]byte` from the `Data` field?. Right now I get a `*ReceivedMessage` via stream, and I'm getting that string in binary format this way:

```go
d := message.GetMessage().GetData()
```

How can I get the `[]byte` from the protobuf message, `*PubsubMessage`, to be "unserialized"?

This is the struct I'm getting through a gRPC stream:

```go
type ReceivedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AckId           string         `protobuf:"bytes,1,opt,name=ack_id,json=ackId,proto3" json:"ack_id,omitempty"`
	Message         *PubsubMessage `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DeliveryAttempt int32          `protobuf:"varint,3,opt,name=delivery_attempt,json=deliveryAttempt,proto3" json:"delivery_attempt,omitempty"`
}

type PubsubMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data        []byte               `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Attributes  map[string]string    `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	MessageId   string               `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	PublishTime *timestamp.Timestamp `protobuf:"bytes,4,opt,name=publish_time,json=publishTime,proto3" json:"publish_time,omitempty"`
	OrderingKey string               `protobuf:"bytes,5,opt,name=ordering_key,json=orderingKey,proto3" json:"ordering_key,omitempty"`
}
```

**Comment by nebiros** [comment]
> This is working as expected. The "weird chars" at the end is the serialized message in the binary format.
> 
> The exact string being serialized is: "\nt{"another_random_id":"1f22ad00-04ba-4db9-ae32-5e0d007ee1f5","some_random_id":"5d0e1133-48f3-4ce0-a4de-871d265940f5"}\x1a\v\b\xb9\xda\xe9\xf7\x05\x10\x82\xab\x98+"
> 
> Passing this data to to the [`protopack`](https://pkg.go.dev/google.golang.org/protobuf/testing/protopack?tab=doc) package shows that this is indeed valid wire data:
> 
> ```
> $ cat dump | pbdump -messages 3
> Message{
> 	Tag{1, Bytes}, Bytes(`{"another_random_id":"1f22ad00-04ba-4db9-ae32-5e0d007ee1f5","some_random_id":"5d0e1133-48f3-4ce0-a4de-871d265940f5"}`),
> 	Tag{3, Bytes}, LengthPrefix(Message{
> 		Tag{1, Varint}, Uvarint(1593470265),
> 		Tag{2, Varint}, Uvarint(90576258),
> 	}),
> }
> ```

Doing this:

```go
b, _ := message.Descriptor()
buf := proto.NewBuffer(b)

var psm pb.ReceivedMessage

if err := buf.DecodeMessage(&psm); err != nil {
	log.Error(err)
}
```

I got this error now: `proto: invalid field number`

**Comment by nebiros** [comment]
NVM, was my issue, I was unmarshalling the wrong struct, 🤦‍♂️
