### ISSUE TITLE
protoc-gen-go: maps in options

### ISSUE THREAD

**Issue by katallaxie** [golang/protobuf#1162]
I wanted to ask the question, if it is possible to have a map in a Protobuf option. Because the example are working with `oneof`, and scalar types, but as you can also specify a map (e.g. `map<string,string> = 1;` it should also be possible to specify the value of the map. But I did not find an example how to actually write this option. 

Let me give you an example.

```
// Specific Service ...
message MyService {
   message UpdateItemInput {
    string Name    = 1;
   // Having a map of attributes for the options.
    map<string,string> Attributes = 2;
  }

  oneof input {
    UpdateItemInput UpdateItem = 3;
  }
}

// Service mapping ...
message Services {
  string selector = 1;

  oneof pattern {
    MyService MyService = 1;
  }
}

// providing the options
extend google.protobuf.MethodOptions {
  Services services = 12345678;
}

```

When specifying the option, the `string` gets parsed by `protoc` and the go generator and works. But I don't know how to actually specify the values for the map for `Attributes` 🤔 . If this is actually in the the language or should not be possible. 

```
// Example ...
service Example {
  // Update ...
  rpc Update(Update.Request) returns (Update.Response) {
    option (com.example.services).MyService.UpdateItem = {
      Name: "example"
      Attributes: { { "key": "value" } }
    };
  };
  // ListItems ...
  rpc ListItems(ListItems.Request) returns (stream ListItems.Response);
}
```

Thanks for any guidance.

**Comment by neild** [comment]
Options are in protobuf text format.

Text format doesn't have custom syntax for maps. Instead, a map field is represented as a repeated field, each item of which is an entry message with key and value fields.

For your above example, I believe the syntax would be:

```
    option (com.example.services).MyService.UpdateItem = {
      Name: "example"
      Attributes: [
        { key: "key", value: "value" },
      ]
    };
```

**Comment by katallaxie** [comment]
🤔  that is what I thought and tried. But when I tried to generate the code from it with `protoc-gen-go` then this errors occurs `Error while parsing option value for "UpdateItem": Expected "{", found "]".` Which yields to me that you can have a message as the type of the field, or simple type, but oddly not a map.

**Comment by neild** [comment]
I had a spurious comma. Try:

```
    option (com.example.services).MyService.UpdateItem = {
      Name: "example"
      Attributes: [
        { key: "key", value: "value" }
      ]
    };
```

**Comment by katallaxie** [comment]
👍  I just realized that I mixed two things with my approach.
