### ISSUE TITLE
Allow Omitempty to be toggleable in protobuf

### ISSUE THREAD

**Issue by mornindew** [golang/protobuf#1164]
There are some cases where I marshal my generated protobuf struct directly over to JSON. It can get a bit confusing when zero/default values are not marshalled into JSON. Especially when they were explicitly set as such (e.g. false in the database or 0 is a valid value). If the consumer of the API has properly set their default values then this isn't an issue but that is a major assumption.

Alternatively, I can marshal the protobuf struct to a different struct (with identical values) and not use the "omitempty" tag before marshaling over to json but this will impact performance.

In addition, I have seen solutions/scripts that will update any generated protobuf files to remove the "omitempty" tag. This is a bit of a hack and an anti-pattern to modify autogenerated files.

I understand the desire to not send over default values and ensure that they aren't necessarily marshaled over but there are cases where I would be willing to sacrifice some performance implications for simplicity in the code.

Proposed Solution
I propose that we add a mechanism to our proto files to not allow the omitempty tag to get set. Without the toggle then omitempty will be set but allowing it to be overwritten seems more flexible for the development community.

Please let me know if I am under thinking the solution and the ramifications of it.

**Comment by dsnet** [comment]
Have you considered using the [`protojson`](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson?tab=doc)? The generation of the `json` struct tags was a historical mistake and there unfortunately isn't a way to signal that `encoding/json` is recommended for use with protobuf messages.

**Comment by mornindew** [comment]
@dsnet  - Thank you very much.  No, i didn't even know about that package.  i will check it out, thanks!

I am not sure that I fully understand the historical mistake.  I thought that it was nice to have but even better if I could control the JSON parsing behavior.  Are you saying that it is an anti-pattern to ever marshal a grpc struct to JSON and I should never do it?

**Comment by dsnet** [comment]
> I am not sure that I fully understand the historical mistake.

It's a lesson in why we should be careful about adding new features and also doing anything that deviates from the main protobuf project.

The `json` tags in the generated struct were add in the distant past when people thought: "wouldn't it be useful if we could serialize protobufs as JSON?" This desire in itself is a reasonable, and so the generation of the `json` tags were added.

However, several problems arise in the years after: 1) the protobuf language continued to evolved and gained new features that the `json` tags were not suited for (e.g., oneofs), 2) the protobouf project defined its own [official mapping for how to serialize as JSON](https://developers.google.com/protocol-buffers/docs/proto3#json) and the JSON format that Go came up with using the `json` tags is unfortunately incompatible.

> Are you saying that it is an anti-pattern to ever marshal a grpc struct to JSON and I should never do it?

I would say it's an anti-pattern to use `encoding/json` with a generated protobuf message.

An upcoming feature in the `encoding/json` package (hopefully for go1.16) is that you can [specify type overrides](https://github.com/golang/go/issues/5901). This would enable someone to use `encoding/json` and `google.golang.org/protobuf/encoding/protojson` together in a more compatible way by doing something like this:
```go
e := json.NewEncoder(w)
e.RegisterFunc(protojson.Marshal)
e.Encode(v) // where v is a generated message or a composite type that contains protobuf messages
```

**Comment by mornindew** [comment]
I really appreciate your insights here.  Thank you!

**Comment by dsnet** [comment]
Closing this issue as we don't intend change the generated `json` tags (other than possibly removing them in the future). If `protojson` is insufficient as a replacement, then that's a separate issue and we can open a different issue for that.
