### ISSUE TITLE
golang ByteString.copyFrom

### ISSUE THREAD

**Issue by Molecular-Future** [golang/protobuf#1165]
```
syntax = "proto3";

package entity;

message OrganizationInfo {
	bytes name = 1;
}
```

java code 
```
OrganizationInfo.Builder oOrganizationInfo1 = OrganizationInfo.newBuilder();
oOrganizationInfo1.setName(ByteString.copyFrom("企业名称1".getBytes()));
```

How to implement golang？thanks!

**Comment by dsnet** [comment]
Hi, we're not familiar with the generated code for Java, but perhaps this does what you want?

```go
var oi1 OrganizationInfo
oi1.Name = append([]byte(nil), oi2.GetName()...)
```

This relies on the [builtin `append` function in the language](https://golang.org/ref/spec#Appending_and_copying_slices).

Closing this issue, as we try to keep the issue tracker about actual work to be done to the module. If you would need more assistance, I recommend [asking on the #protobuf channel on Slack](https://invite.slack.golangbridge.org/).
