### ISSUE TITLE
reflect/protoreflect: add API for obtaining the wire type for a given protobuf kind

### ISSUE THREAD

**Issue by dylan-bourque** [golang/protobuf#1167]
**What version of protobuf and what language are you using?**
Go 1.14 and v1.4/v1.25 of the Go protobuf packages (github.com/golang/protobuf and google.golang.org/protobuf)

From my `go.mod`
```
module github.com/example/repo

go 1.14

require (
	...
	github.com/golang/protobuf v1.4.1
	google.golang.org/protobuf v1.25.0
)
```

**What did you do?**
I'm working on porting some code that currently uses Gogo Protobuf's [`proto.Properties`](https://pkg.go.dev/github.com/gogo/protobuf@v1.3.1/proto?tab=doc#Properties) to retrieve the wire type for a given field.  
While attempting to port that code to use the new Protobuf APIs, I noticed that there is currently no exported API that returns the [`protowire.Type`](https://pkg.go.dev/google.golang.org/protobuf@v1.25.0/encoding/protowire?tab=doc#Type) value that represents the wire type for a given field of a [`proto.Message`](https://pkg.go.dev/google.golang.org/protobuf@v1.25.0/proto?tab=doc#Message)

**What did you expect to see?**
Some documented API provided by the library that returns the wire type for a given field

**What did you see instead?**
No API is present

I wrote a rough version for myself based on the existing code in Gogo's library and in `protoc-gen-go`.
```
func getWireType(m *proto.Message, fieldName string) (wireType protowire.Type, err error) {
	field := m.ProtoReflect().Descriptor().Fields().ByName(protoreflect.Name(fieldName))
	kind := field.Kind()
	switch kind {
	case protoreflect.BoolKind, protoreflect.EnumKind:
		wireType = protowire.VarintType
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Uint32Kind:
		wireType = protowire.VarintType
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Uint64Kind:
		wireType = protowire.VarintType
	case protoreflect.Sfixed32Kind, protoreflect.Fixed32Kind:
		wireType = protowire.Fixed32Type
	case protoreflect.FloatKind:
		wireType = protowire.Fixed32Type
	case protoreflect.Sfixed64Kind, protoreflect.Fixed64Kind:
		wireType = protowire.Fixed64Type
	case protoreflect.DoubleKind:
		wireType = protowire.Fixed64Type
	case protoreflect.StringKind, protoreflect.BytesKind, protoreflect.MessageKind:
		wireType = protowire.BytesType
	case protoreflect.GroupKind:
		wireType = protowire.VarintType
	default:
		err = fmt.Errorf("unknown/unsupported field kind: %s", kind)
	}
	return wireType, err
}
```

**Comment by neild** [comment]
What's the wire type of a packed field?

A field in packed encoding will always have a wire type of `BytesType`, but decoders should handle either the packed or non packed encodings. This means that there isn't a 1-1 mapping between fields and wire types.

**Comment by dylan-bourque** [comment]
For Go, the `switch`/`case` example I posted covers all of the logic that emits the `protobuf: .....` struct tag.  While this proposed API certainly wouldn't (and maybe couldn't) cover every case, it would still be potentially useful.  It would also be, in a way, just exposing the existing logic that `protoc-gen-go` uses internally to emit that struct tag.

**Comment by neild** [comment]
I don't think we want to expose a function like this.

It is simple to implement outside the protobuf module (as demonstrated by the sample implementation above), does not seem widely useful, and does not seem to have a clear definition with regards to packed fields.

**Comment by dylan-bourque** [comment]
I'll concede that my case is certainly specialized.  The code I'm working on is a deserialization optimization that probably only comes up at the volume we're dealing with.

My reason for asking for a library-provided API was more around future-proofing.  Anyone who has actually written their own version of that logic will be broken in the event that a new `protoreflect.Kind` value is added or the mapping in my snippet changes.

**Comment by dsnet** [comment]
I don't feel strongly about whether to add this or not.

If it were to be added, it'd probably be a method on `protoreflect.Kind` or `protoreflect.FieldDescriptor` rather than a standalone function.

> does not seem to have a clear definition with regards to packed fields.

If added, I'd argue that it use the wire type associated with the non-packed representation. It seems easy to do something like:
```go
wt := fd.WireType()
if fd.IsPacked() {
    wt = protowire.BytesType
}
```

> does not seem widely useful

I had thought that we had a number of replicated switches in our codebase converting a `protoreflect.Kind` to a `protowire.Type`, but it seems that there are far fewer than I thought. This does seem to suggest that the utility for this is low (even within our own module).

In contrast, there does seem to be a number of replicated switches converting `protoreflect.Kind` to the Go type that commonly represents that kind (a feature I still think we should provide at some point).

**Comment by dsnet** [comment]
I've been extensively migrating Google code over from `github.com/golang/protobuf` to `google.golang.org/protobuf` and this not common operation to warrant exposed API for it. A litmus test for whether we want to have this feature is whether the C++ protobuf reflection API provides a similar helper function. My brief glance at their API (which is large) didn't reveal anything. As such, I'm inclined to decline adding this feature. Leaving open for a few days for final comments.

**Comment by dylan-bourque** [comment]
I can understand that stance, although I'm sad that I will have to maintain my DIY implementation.

**Comment by dsnet** [comment]
Closing per https://github.com/golang/protobuf/issues/1167#issuecomment-663192404.
