### ISSUE TITLE
all: fail to run test on 32bit arch

### ISSUE THREAD

**Issue by zhsj** [golang/protobuf#1168]
**What version of protobuf and what language are you using?**
Version: (e.g., `v1.1.0`, `89a0c16f`, etc)

v1.25.0

**What did you do?**
If possible, provide a recipe for reproducing the error.
A complete runnable program is good with `.proto` and `.go` source code.

GOARCH=386 go test ./...

**What did you expect to see?**

No error

**What did you see instead?**

```
# google.golang.org/protobuf/internal/encoding/text_test [google.golang.org/protobuf/internal/encoding/text.test]
internal/encoding/text/decode_test.go:1024:17: constant 9223372036854775807 overflows int
internal/encoding/text/decode_test.go:1025:17: constant -9223372036854775808 overflows int
# google.golang.org/protobuf/internal/protobuild
internal/protobuild/build.go:114:16: constant 4294967295 overflows int
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment?**

**Comment by dsnet** [comment]
Thanks for the report, the finding in `internal/protobuild/build.go` looks concerning as its not within a test case.

**Comment by dsnet** [comment]
Fixed with https://go-review.googlesource.com/c/protobuf/+/241537
