### ISSUE TITLE
Recommended approach for custom RPC usage (google.golang.org/protobuf)

### ISSUE THREAD

**Issue by palsivertsen** [golang/protobuf#1169]
For the new module (google.golang.org/protobuf), what's the recommended approach for using custom RPC implementations (not gRPC)?

As far as I can see there's no support for RPC yet, but is it in the road map and if so are there any details/discussions around the implementation? It would be really nice to have a looser coupling between generated code and RPC implementation. E.g. the previous implementation of proto services generated types specific for gRPC, making it really hard to use other implementations.

**Comment by meling** [comment]
The new protobuf module only generates protobuf code, so there is no gRPC specific code. That is, if you want both, you should specify both `--go_out` and `--go-grpc_out` flags to the `protoc` compiler. This results in two separate files in the same package, and so the gRPC code can use the protobuf messages directly. That is, if you want to generate gRPC code, you need to install the corresponding grpc-go generator, i.e. [this module](https://github.com/grpc/grpc-go/tree/master/cmd/protoc-gen-go-grpc).

Feel free to take a look at our [Gorums project](https://github.com/relab/gorums), which implements a multiparty RPC solution aimed at building quorum-based systems, such as distributed storage algorithms and state machine replication. Gorums uses gRPC streams and some unary RPCs, although we are moving away from unary RPCs. In particular, you might want to look at the Makefile, e.g. the `tools` target and the corresponding `tools.go` files.

**Comment by neild** [comment]
An RPC implementation will have either a custom code generator (such as the [`protoc-gen-go-grpc`](https://github.com/grpc/grpc-go/tree/master/cmd/protoc-gen-go-grpc) generator @meling references), or be written so that it doesn't need a code generator (like the [`rpc`](https://pkg.go.dev/net/rpc) package).

If you are writing an RPC implementation, `protoc-gen-go-grpc` may serve as a useful reference.

**Comment by dsnet** [comment]
Closing as inactionable. One of the goals of the `google.golang.org/protobuf` module is to be agnostic towards any specific service generation approach. This is one of the reasons why we moved the grpc implementation out of `github.com/golang/protobuf` over to `google.golang.org/protobuf/grpc`. As @neild mentioned, `protoc-gen-go-grpc` may serve as inspiration.
