### ISSUE TITLE
proto: invalid UTF-8 string error from Marshal is not a Error

### ISSUE THREAD

**Issue by sykesm** [golang/protobuf#1174]
**What version of protobuf and what language are you using?**
Version: google.golang.org/protobuf v1.25.0, protoc 3.12.3

**What did you do?**
Files for a simple recreate can be found [here](https://gist.github.com/sykesm/9e70bb092ed05f05068b8639c5ce33cb) but the basic outline is that `expected impl.errInvalidUTF8{} to be a proto.Error` is the result of running

```go
package main

import (
	"errors"
	"log"
	"proto-utf8/testproto"

	"google.golang.org/protobuf/proto"
)

func main() {
	message := &testproto.Message{
		Str: string([]byte{200, 200, 200}),
	}

	_, err := proto.Marshal(message)
	if err == nil {
		log.Fatalf("expected marshal to fail")
	}
	if !errors.Is(err, proto.Error) {
		log.Fatalf("expected %#v to be a proto.Error", err)
	}
}
```

with a trivial message
```proto
syntax = "proto3";

package testproto;

message Message {
    string str = 1;
}
```

**What did you expect to see?**
According to the [FAQ](https://developers.google.com/protocol-buffers/docs/reference/go/faq#unstable-errors), errors returned from the protobuf module are guaranteed to match `proto.Error` according to `errors.Is`. So, when I attempted to marshal a message containing an invalid UTF-8 string, I expected to receive an error that `errors.Is` a `proto.Error`.

**What did you see instead?**
The error returned from `proto.Marshal` was an instance of `impl.errInvalidUTF8{}`. When that value was compared with `proto.Error`, `errors.Is` returned false.

**Comment by dsnet** [comment]
Thanks for the report. \cc @neild since he's making other changes to error reporting.

**Comment by neild** [comment]
Yep, that's a bug all right. Thanks for the report.
