### ISSUE TITLE
Trying to UnmarshalAny

### ISSUE THREAD

**Issue by naoko** [golang/protobuf#1175]
I have a simple message with just one field Any
```
message MyMessage {
    google.protobuf.Any anything = 2;
}
```
and
```
msg := &pb.MyMessage{Anything: &any.Any{
			TypeUrl: "type.googleapis.com/google.protobuf.StringValue",
			Value:   []byte("I'm string")}}
out, err := proto.Marshal(msg)

msg2 := &pb.MyMessage{}
var s wrappers.StringValue
err = ptypes.UnmarshalAny(msg2.Anything, &s)
```
the last line error out and the message reads: ` proto: cannot parse reserved wire type`

Not certain what it means :( 
Could you advise? Thank you!

**Comment by cybrcodr** [comment]
```
msg := &pb.MyMessage{Anything: &any.Any{
			TypeUrl: "type.googleapis.com/google.protobuf.StringValue",
			Value:   []byte("I'm string")}  //   This is not a valid proto binary message.
}
```

The Value field of the message Any has to contain a serialized binary proto message of type specified in TypeUrl field.  See https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#any.

**Comment by naoko** [comment]
@cybrcodr , thank you for the advice. I need a bit more assistance. Sorry :(

So I changed it to the way I thought it is asking but I'm getting this
`cannot use &wrapperspb.StringValue literal (type *wrapperspb.StringValue) as type []byte in field value
`
could you please provide me with an example? Thank you

**Comment by naoko** [comment]
Got it. thank you!

**Comment by cybrcodr** [comment]
```
sv := &wrappers.StringValue{Value: "hello"}
value, err := proto.Marshal(sv)
if err != nil {
    // ... handle marshaling error
}

msg := &pb.MyMessage{
    Anything: &any.Any{
        TypeUrl: "type.googleapis.com/google.protobuf.StringValue",
        Value:   value,
    },
}

// Calling ptypes.UnmarshalAny on msg.Anything will then get you back sv.
// same as what you have above.
```

I'd also suggest using the [google.golang.org/protobuf/proto](https://pkg.go.dev/google.golang.org/protobuf/proto) library if possible which is V2 of the proto library.  The generated [anypb package](https://pkg.go.dev/google.golang.org/protobuf@v1.25.0/types/known/anypb) contains an easy to use `New` func that will marshal the value and construct an Any message with it.  The Any message type also contains a method `UnmarshalTo` which is similar in effect to `ptypes.UnmarshalAny`.

```
any, err := anypb.New(&wrappers.StringValue{Value: "hello"})
if err != nil {
    // handle marshaling error.
}

msg := &pb.MyMessage{
    Anything: any,
}

b, err := proto.Marshal(msg)
...
```

If you have unserialized `MyMessage`, you can then retrieve the `StringValue` via ...

```
sv := &wrappers.StringValue{}
err := msg.Anything.UnmarshalTo(sv)
```

Btw, looking at your original post, I'm now not sure if msg2 there came from unmarshaling a proto binary bytes or if that was really empty message.
