### ISSUE TITLE
How to use protoc to generate code when the base package contains minus sign ?

### ISSUE THREAD

**Issue by konnase** [golang/protobuf#1181]
Here is the proto file I used -- pkg/apis/workflow/v1alpha1/generated.proto
```proto
syntax = 'proto2';

package go-server.com.argo-new.pkg.apis.workflow.v1alpha1;

import "k8s.io/api/core/v1/generated.proto";
import "k8s.io/api/policy/v1beta1/generated.proto";
import "k8s.io/apimachinery/pkg/apis/meta/v1/generated.proto";
import "k8s.io/apimachinery/pkg/runtime/generated.proto";
import "k8s.io/apimachinery/pkg/runtime/schema/generated.proto";

// Package-wide variables from generator "generated".
option go_package = "v1alpha1";

// ArchiveStrategy describes how to archive files/directory when saving artifacts
message ArchiveStrategy {
  optional TarStrategy tar = 1;

  optional NoneStrategy none = 2;
}
```
When I tried to use `protoc -I /usr/local/include -I . -I ./vendor -I /root/go/src -I /root/go/pkg/mod/github.com/gogo/protobuf@v1.3.1/gogoproto -I /root/go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.12.2/third_party/googleapis --include_imports --gogofast_out=plugins=grpc:/root/go/src --grpc-gateway_out=logtostderr=true:/root/go/src --swagger_out=logtostderr=true,fqn_for_swagger_name=true:. pkg/apis/workflow/v1alpha1/generated.proto` to compile the proto file, it reminds me `pkg/apis/workflow/v1alpha1/generated.proto:6:11: Expected ";".`

It's a compile error which means the package name should not contain "-". Are there any methods to use "-" in package name or any workaround ?

Thanks!

**Comment by dsnet** [comment]
The `package` in the `.proto` file is a distinctly different concept from the Go package path. In the protobuf language, the syntax for a valid protobuf package are `[_a-zA-Z][_a-zA-Z0-9]+([.][_a-zA-Z][_a-zA-Z0-9]+)*`.

The `go_package` option in the `.proto` file is where you specify the _full_ Go package path. Thus, `v1alpha1` is incorrect.

Also, it seems that you are using `protoc-gen-gogo`, but this repository is for `protoc-gen-go`, perhaps you should be asking these questions on [that project's issue tracker](https://github.com/gogo/protobuf) if you're using that plugin?

**Comment by dsnet** [comment]
Our issue tracker is intended to track work that needs to be done. For questions that are better resolved through a series of back-and-forth questions and responses, this is [probably best asked on Slack](https://invite.slack.golangbridge.org/). There's a `protobuf` channel where similar questions are usually asked.

**Comment by konnase** [comment]
Thanks
