### ISSUE TITLE
How to implement a general tool that can deserialize any proto message's serialization? 

### ISSUE THREAD

**Issue by Hank00AAA** [golang/protobuf#1191]
I have a {key, value} pair which value is proto.Message 's serialization. Now I want to implement a tool that can tell me what the value  store exactly. 

Assuming that we have a  ```struct { "helloInt" : 99,  "helloStr" : "hello world"}``` ,  and we serialized it to k-v pair ``` {"testStr", struct's pb serialization data }  ```. 

After a long time, I forget what the <"testStr", value> 's meaning, I have to deserializd the value to the following proto message, and get the result ``` struct { "helloInt" : 99,  "helloStr" : "hello world"} ``` again.

So I input ``` {"testStr", message HelloStruct } ``` to the tool and it will tell me, " yes Sir, the pair's value is equal to ``` struct { "helloInt" : 99,  "helloStr" : "hello world"} ```  not just a <"testStr", a proto seralization binary data>

And My problem is how to implement the tool ?

```
message HelloStruct {
    int helloInt = 1;
   string helloStr = 2;
}
``

**Comment by puellanivis** [comment]
I’m not wholly sure what you are asking for here. The title asks about “decode”, but the body speaks about taking a proto message and generating the `fmt.Printf("%+v", value)` encoding of only the value.

The `Hello` message type should be a struct like any other, and allow you to use `fmt.Printf("%+v", value)` on it, which will yield `test:1 testStr: "hello world"`. At that point, you really just need `fmt.Printf("{%+v}", value)` to get that enclosed in `{…}`.

But this doesn’t seem like “decoding” to me, but rather “encoding”.

(unrelated lint) in a proto file you should try to use `snake_case`, the proto code generators will take care of converting that to the appropriate `camelCase` or `CamelCase` based on the conventions used in that language.

**Comment by Hank00AAA** [comment]
Thanks for your reply.  I find  pkg:github.com/jhump/protoreflect useful.  I use it to finish the tool. But I meet problem, when I use ``` fmt.Printf("%+v", value) ```, it can't printf repeated field. My code is like that
```
     data := GetBinaryValue()
    msg := dynamic.NewMessage(valueStruct)
    msg.Unmarshal(data)
   fmt.Printf("%v", msg)
```
I use API https://github.com/jhump/protoreflect/blob/master/dynamic/dynamic_message.go#L106

**Comment by dsnet** [comment]
If you want to the ability to define a subset of the message at runtime, you could also do that with the [`google.golang.org/protobuf/types/dynamicpb`](https://pkg.go.dev/google.golang.org/protobuf/types/dynamicpb?tab=doc) package.

That said, I still don't understand what the original post is actually asking for.

**Comment by Hank00AAA** [comment]
> If you want to the ability to define a subset of the message at runtime, you could also do that with the [`google.golang.org/protobuf/types/dynamicpb`](https://pkg.go.dev/google.golang.org/protobuf/types/dynamicpb?tab=doc) package.
> 
> That said, I still don't understand what the original post is actually asking for.

I update the issue, Is it clear enougn? 0 0

**Comment by dsnet** [comment]
> I update the issue, Is it clear enougn? 0 0

It's better. From what I can gather, yes, `dynamicpb` will do what you want. However, it will be the user's responsibility to provide the protobuf type information needed to parse arbitrary messages. The `dynamicpb` package creates dynamic messages when given a `protoreflect.Message`. A `protoreflect.Message` can be dynamically constructed at runtime using the [`google.golang.org/protobuf/reflect/protodesc`](https://pkg.go.dev/google.golang.org/protobuf/reflect/protodesc?tab=doc) package.

**Comment by Hank00AAA** [comment]
> > I update the issue, Is it clear enougn? 0 0
> 
> It's better. From what I can gather, yes, `dynamicpb` will do what you want. However, it will be the user's responsibility to provide the protobuf type information needed to parse arbitrary messages. The `dynamicpb` package creates dynamic messages when given a `protoreflect.Message`. A `protoreflect.Message` can be dynamically constructed at runtime using the [`google.golang.org/protobuf/reflect/protodesc`](https://pkg.go.dev/google.golang.org/protobuf/reflect/protodesc?tab=doc) package.

Thanks. I search in this pkg for long time, but I don't find a method can parse *.proto to FileDescriptor. Could you tell me how to link these method together to implement the tool? @dsnet

**Comment by dsnet** [comment]
There is no `.proto` parser implementation in this module. You can consider using https://pkg.go.dev/github.com/jhump/protoreflect/desc/protoparse?tab=doc
