### ISSUE TITLE
reflect/protodesc: FileDescriptorProto emits an empty non-nil package for a file with no package

### ISSUE THREAD

**Issue by jhump** [golang/protobuf#1195]
**What version of protobuf and what language are you using?**
v1.25.1-0.20200805231151-a709e31e5d12 (latest as of August 5th).
It's also in the latest release (v.1.25.0) and in current master (as of this writing).

**What did you do?**
Used `protodesc.ToFileDescriptorProto` with a `FileDescriptor` that had no package (e.g. no package statement in the source file; `file.Package()` returns empty string).

**What did you expect to see?**
A descriptor proto where the `Package *string` field is nil. That is what the actual descriptor proto looks like as parsed/produced by `protoc`.

**What did you see instead?**
A descriptor proto where the `Package *string` field is non-nil and points to an empty string.

[This code](https://github.com/protocolbuffers/protobuf-go/blob/master/reflect/protodesc/proto.go#L22)
```go
	p := &descriptorpb.FileDescriptorProto{
		Name:    proto.String(file.Path()),
		Package: proto.String(string(file.Package())),
		Options: proto.Clone(file.Options()).(*descriptorpb.FileOptions),
	}
```
should probably instead look like so
```go
	p := &descriptorpb.FileDescriptorProto{
		Name:    proto.String(file.Path()),
		Options: proto.Clone(file.Options()).(*descriptorpb.FileOptions),
	}
	if file.Package() != "" {
		p.Package = proto.String(string(file.Package()))
	}
```

**Comment by dsnet** [comment]
Seems reasonable. Would you like to contribute a fix?

**Comment by jhump** [comment]
> Seems reasonable. Would you like to contribute a fix?

@dsnet, I might. I am knee-deep in a fairly major refactor of some of my stuff right now. Before I try to contribute anything, I'll probably try to get to the end of that and see if I find anything else.
