### ISSUE TITLE
How understand ExtensionDesc options and this value without convert to string?

### ISSUE THREAD

**Issue by mrfoe7** [golang/protobuf#1198]
Hi, everyone

How understand field options type without convert to string?

Example part of code:
```
...
 rpc Encode (EncodeRequest) returns (EncodeResponse) {
        option (google.api.http) = {
            post: "/Encode"
            body: "option"
        };
    }
...

message EncodeRequest {
    string str = 1;
    Option option = 2 [(gogoproto.nullable) = false]; // <- this filed option
}
```

I realized in my code by call `FieldDescriptorProto.GetOptions().String()` and compare with const nullable string value. Do you have any ways understand to it?

**Comment by dsnet** [comment]
I apologize, but I don't understand what this is asking. Can you be more specific about what you trying to do?

Also, it seems like you're using `gogoproto.nullable`. Perhaps you should be asking this over at https://github.com/gogo/protobuf/issues?

**Comment by mrfoe7** [comment]
> Can you be more specific about what you trying to do?

@dsnet, Yeap, sure. 

In code I am used descriptor from `protobuf/proton-gen-go`.
Code parsed `proto-file`(example in upper) and by them generate `swagger-file`. I wanna get nullable option field, but I don’t know how compare different options between themself. May be you know best way to compare field options between themself than transform field option to string.

I hope, you can understand my problem))

**Comment by mrfoe7** [comment]
I find this interesting protosal - https://github.com/golang/protobuf/issues/555

i wanna get setted value from `ExtensionDesc` witch setted into proto-file. How to do it?

**Comment by dsnet** [comment]
You have have an ExtensionDesc and want to retrieve the value for a field that the extension descriptor represents, you can use [`proto.GetExtension`](https://pkg.go.dev/google.golang.org/protobuf/proto?tab=doc#GetExtension).

(FYI, we try to keep our issue tracker about actionable issues. Questions like this are best asked on Slack or someone other means where you can more readily get immediate help. Consider joining the `#protobuf` channel or the Gophers slack workspace: https://gophers.slack.com/?redir=%2Fmessages%2Fgeneral%2F)

**Comment by mrfoe7** [comment]
Thanks for you, @dsnet
