### ISSUE TITLE
panic when use github.com/google/go-cmp on generated messages

### ISSUE THREAD

**Issue by tiagomelo** [golang/protobuf#1201]
I have the exact same scenario as described here: https://github.com/golang/protobuf/issues/1086

But I do not get; is it or is not possible to really make `cmp.Diff()` to work in conjunction with `google.golang.org/protobuf/testing/protocmp`? If so, how can I achieve this?

**Comment by neild** [comment]
See the [`google.golang.org/protobuf/testing/protocmp`](https://pkg.go.dev/google.golang.org/protobuf/testing/protocmp) package:

`cmp.Diff(a, b, protocmp.Transform())`

**Comment by dsnet** [comment]
> is it or is not possible to really make cmp.Diff() to work in conjunction with google.golang.org/protobuf/testing/protocmp

Is this a typo? `protocmp` exists to work with `cmp.Diff`. Did you mean to ask whether it's possible to use `cmp.Diff` _without_ `protocmp`? If so, it was never the intention of `cmp` since it was created to be used to compare protobuf messages. In fact, `protocmp` was something I wanted to have available when `cmp` first became available, but we needed to build protobuf reflection first.

**Comment by tiagomelo** [comment]
> > is it or is not possible to really make cmp.Diff() to work in conjunction with google.golang.org/protobuf/testing/protocmp
> 
> Is this a typo? `protocmp` exists to work with `cmp.Diff`. Did you mean to ask whether it's possible to use `cmp.Diff` _without_ `protocmp`? If so, it was never the intention of `cmp` since its creation to be used to compare generated protobuf messages. In fact, `protocmp` was something we wanted to have available when `cmp` first became available, but we needed to build protobuf reflection first.

What I want to know is what's the right way of being able to make a diff between protobuf messages.

```
if diff := cmp.Diff(a, b, <protocmp option here>); diff != "" 
```
what should be the protocmp option to use so it can ignore these autogenerated fields:

```
state         protoimpl.MessageState
sizeCache     protoimpl.SizeCache
unknownFields protoimpl.UnknownFields
```

?

**Comment by tiagomelo** [comment]
> See the [`google.golang.org/protobuf/testing/protocmp`](https://pkg.go.dev/google.golang.org/protobuf/testing/protocmp) package:
> 
> `cmp.Diff(a, b, protocmp.Transform())`

so... should it be 

`cmp.Diff(a, b, <protocmp option to ignore some fields>, protocmp.Transform())` ?

**Comment by dsnet** [comment]
If you want to ignore fields in a protobuf message, then you can use [`protocmp.IgnoreFields`](https://pkg.go.dev/google.golang.org/protobuf/testing/protocmp?tab=doc#IgnoreFields).
If you want to ignore fields in a normal Go struct, then you can use [`cmpopts.IgnoreFields`](https://pkg.go.dev/github.com/google/go-cmp/cmp/cmpopts?tab=doc#IgnoreFields).
You can compose the two options together if needed.

**Comment by tiagomelo** [comment]
I'll take a look. Thanks!

**Comment by 00Chaotic** [comment]
Hi @tiagomelo, did you find a solution for this problem? If so, could you elaborate on it?

Was your case simple enough to be able to directly specify each struct to be ignored?

I have a similar case but I have multiple levels of nested structs which means I would need to list over a dozen types if I were to ignore them all one by one. I'm considering just recursively iterating through each struct but I'd like to see if there may be a better way to do it.
