### ISSUE TITLE
all: cyclic imports bloat go.sum

### ISSUE THREAD

**Issue by 2767mr** [golang/protobuf#1204]
**What version of protobuf and what language are you using?**

`github.com/golang/protobuf/protoc-gen-go`: `v1.4.2`
`github.com/golang/protobuf`: `v1.4.2`
`google.golang.org/protobuf`: `v1.25.0`
`go`: `go version go1.15.1 windows/amd64`

**What did you do?**

Generated a simple message using `go:generate protoc --go_opt=paths=source_relative --go_out=. example.proto`
`example.proto`:
```proto
syntax = "proto3";

option go_package = "github.com/2767mr/prototest";

message Empty {

}
```

Then I run `go mod tidy`

**What did you expect to see?**

A simple `go.sum` without duplicated entries for `github.com/golang/protobuf` or `google.golang.org/protobuf`

**What did you see instead?**

A lot of duplicated entries referencing old version. Full content:
```go.sum
cloud.google.com/go v0.26.0/go.mod h1:aQUYkXzVsufM+DwF1aE+0xfcU+56JwCaLick0ClmMTw=
github.com/BurntSushi/toml v0.3.1/go.mod h1:xHWCNGjB5oqiDr8zfno3MHue2Ht5sIBksp03qcyfWMU=
github.com/census-instrumentation/opencensus-proto v0.2.1/go.mod h1:f6KPmirojxKA12rnyqOA5BBL4O983OfeGPqjHWSTneU=
github.com/client9/misspell v0.3.4/go.mod h1:qj6jICC3Q7zFZvVWo7KLAzC3yx5G7kyvSDkc90ppPyw=
github.com/envoyproxy/go-control-plane v0.9.1-0.20191026205805-5f8ba28d4473/go.mod h1:YTl/9mNaCwkRvm6d1a2C3ymFceY/DCBVvsKhRF0iEA4=
github.com/envoyproxy/protoc-gen-validate v0.1.0/go.mod h1:iSmxcyjqTsJpI2R4NaDN7+kN2VEUnK/pcBlmesArF7c=
github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b/go.mod h1:SBH7ygxi8pfUlaOkMMuAQtPIUF8ecWP5IEl/CR7VP2Q=
github.com/golang/mock v1.1.1/go.mod h1:oTYuIxOrZwtPieC+H1uAHpcLFnEyAGVDL/k47Jfbm0A=
github.com/golang/protobuf v1.2.0/go.mod h1:6lQm79b+lXiMfvg/cZm0SGofjICqVBUtrP5yJMmIC1U=
github.com/golang/protobuf v1.3.2/go.mod h1:6lQm79b+lXiMfvg/cZm0SGofjICqVBUtrP5yJMmIC1U=
github.com/golang/protobuf v1.4.0-rc.1/go.mod h1:ceaxUfeHdC40wWswd/P6IGgMaK3YpKi5j83Wpe3EHw8=
github.com/golang/protobuf v1.4.0-rc.1.0.20200221234624-67d41d38c208/go.mod h1:xKAWHe0F5eneWXFV3EuXVDTCmh+JuBKY0li0aMyXATA=
github.com/golang/protobuf v1.4.0-rc.2/go.mod h1:LlEzMj4AhA7rCAGe4KMBDvJI+AwstrUpVNzEA03Pprs=
github.com/golang/protobuf v1.4.0-rc.4.0.20200313231945-b860323f09d0/go.mod h1:WU3c8KckQ9AFe+yFwt9sWVRKCVIyN9cPHBJSNnbL67w=
github.com/golang/protobuf v1.4.0/go.mod h1:jodUvKwWbYaEsadDk5Fwe5c77LiNKVO9IDvqG2KuDX0=
github.com/golang/protobuf v1.4.1/go.mod h1:U8fpvMrcmy5pZrNK1lt4xCsGvpyWQ/VVv6QDs8UjoX8=
github.com/golang/protobuf v1.4.2 h1:+Z5KGCizgyZCbGh1KZqA0fcLLkwbsjIzS4aV2v7wJX0=
github.com/golang/protobuf v1.4.2/go.mod h1:oDoupMAO8OvCJWAcko0GGGIgR6R6ocIYbsSw735rRwI=
github.com/google/go-cmp v0.2.0/go.mod h1:oXzfMopK8JAjlY9xF4vHSVASa0yLyX7SntLO5aqRK0M=
github.com/google/go-cmp v0.3.0/go.mod h1:8QqcDgzrUqlUb/G2PQTWiueGozuR1884gddMywk6iLU=
github.com/google/go-cmp v0.3.1/go.mod h1:8QqcDgzrUqlUb/G2PQTWiueGozuR1884gddMywk6iLU=
github.com/google/go-cmp v0.4.0/go.mod h1:v8dTdLbMG2kIc/vJvl+f65V22dbkXbowE6jgT/gNBxE=
github.com/google/go-cmp v0.5.0 h1:/QaMHBdZ26BB3SSst0Iwl10Epc+xhTquomWX0oZEB6w=
github.com/google/go-cmp v0.5.0/go.mod h1:v8dTdLbMG2kIc/vJvl+f65V22dbkXbowE6jgT/gNBxE=
github.com/prometheus/client_model v0.0.0-20190812154241-14fe0d1b01d4/go.mod h1:xMI15A0UPsDsEKsMN9yxemIoYk6Tm2C1GtYGdfGttqA=
golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2/go.mod h1:djNgcEr1/C05ACkg1iLfiJU5Ep61QUkGW8qpdssI0+w=
golang.org/x/exp v0.0.0-20190121172915-509febef88a4/go.mod h1:CJ0aWSM057203Lf6IL+f9T1iT9GByDxfZKAQTCR3kQA=
golang.org/x/lint v0.0.0-20181026193005-c67002cb31c3/go.mod h1:UVdnD1Gm6xHRNCYTkRU2/jEulfH38KcIWyp/GAMgvoE=
golang.org/x/lint v0.0.0-20190227174305-5b3e6a55c961/go.mod h1:wehouNa3lNwaWXcvxsM5YxQ5yQlVC4a0KAMCusXpPoU=
golang.org/x/lint v0.0.0-20190313153728-d0100b6bd8b3/go.mod h1:6SW0HCj/g11FgYtHlgUYUwCkIfeOF89ocIRzGO/8vkc=
golang.org/x/net v0.0.0-20180724234803-3673e40ba225/go.mod h1:mL1N/T3taQHkDXs73rZJwtUhF3w3ftmwwsq0BUmARs4=
golang.org/x/net v0.0.0-20180826012351-8a410e7b638d/go.mod h1:mL1N/T3taQHkDXs73rZJwtUhF3w3ftmwwsq0BUmARs4=
golang.org/x/net v0.0.0-20190213061140-3a22650c66bd/go.mod h1:mL1N/T3taQHkDXs73rZJwtUhF3w3ftmwwsq0BUmARs4=
golang.org/x/net v0.0.0-20190311183353-d8887717615a h1:oWX7TPOiFAMXLq8o0ikBYfCJVlRHBcsciT5bXOrH628=
golang.org/x/net v0.0.0-20190311183353-d8887717615a/go.mod h1:t9HGtf8HONx5eT2rtn7q6eTqICYqUVnKs3thJo3Qplg=
golang.org/x/oauth2 v0.0.0-20180821212333-d2e6202438be/go.mod h1:N/0e6XlmueqKjAGxoOufVs8QHGRruUQn6yWY3a++T0U=
golang.org/x/sync v0.0.0-20180314180146-1d60e4601c6f/go.mod h1:RxMgew5VJxzue5/jJTE5uejpjVlOe/izrB70Jof72aM=
golang.org/x/sync v0.0.0-20181108010431-42b317875d0f/go.mod h1:RxMgew5VJxzue5/jJTE5uejpjVlOe/izrB70Jof72aM=
golang.org/x/sync v0.0.0-20190423024810-112230192c58/go.mod h1:RxMgew5VJxzue5/jJTE5uejpjVlOe/izrB70Jof72aM=
golang.org/x/sys v0.0.0-20180830151530-49385e6e1522/go.mod h1:STP8DvDyc/dI5b8T5hshtkjS+E42TnysNCUPdjciGhY=
golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a h1:1BGLXjeY4akVXGgbC9HugT3Jv3hCI0z56oJR5vAMgBU=
golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a/go.mod h1:STP8DvDyc/dI5b8T5hshtkjS+E42TnysNCUPdjciGhY=
golang.org/x/text v0.3.0 h1:g61tztE5qeGQ89tm6NTjjM9VPIm088od1l6aSorWRWg=
golang.org/x/text v0.3.0/go.mod h1:NqM8EUOU14njkJ3fqMW+pc6Ldnwhi/IjpwHt7yyuwOQ=
golang.org/x/tools v0.0.0-20190114222345-bf090417da8b/go.mod h1:n7NCudcB/nEzxVGmLbDWY5pfWTLqBcC2KZ6jyYvM4mQ=
golang.org/x/tools v0.0.0-20190226205152-f727befe758c/go.mod h1:9Yl7xja0Znq3iFh3HoIrodX9oNMXvdceNzlUR8zjMvY=
golang.org/x/tools v0.0.0-20190311212946-11955173bddd/go.mod h1:LCzVGOaR6xXOjkQ3onu1FJEFr0SW1gC7cKk1uF8kGRs=
golang.org/x/tools v0.0.0-20190524140312-2c0ae7006135/go.mod h1:RgjU9mgBXZiqYHBnxXauZ1Gv1EHHAz9KjViQ78xBX0Q=
golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543/go.mod h1:I/5z698sn9Ka8TeJc9MKroUUfqBBauWjQqLJ2OPfmY0=
google.golang.org/appengine v1.1.0/go.mod h1:EbEs0AVv82hx2wNQdGPgUI5lhzA/G0D9YwlJXL52JkM=
google.golang.org/appengine v1.4.0/go.mod h1:xpcJRLb0r/rnEns0DIKYYv+WjYCduHsrkT7/EB5XEv4=
google.golang.org/genproto v0.0.0-20180817151627-c66870c02cf8/go.mod h1:JiN7NxoALGmiZfu7CAH4rXhgtRTLTxftemlI0sWmxmc=
google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55/go.mod h1:DMBHOl98Agz4BDEuKkezgsaosCRResVns1a3J2ZsMNc=
google.golang.org/genproto v0.0.0-20200526211855-cb27e3aa2013 h1:+kGHl1aib/qcwaRi1CbqBZ1rk19r85MNUf8HaBghugY=
google.golang.org/genproto v0.0.0-20200526211855-cb27e3aa2013/go.mod h1:NbSheEEYHJ7i3ixzK3sjbqSGDJWnxyFXZblF3eUsNvo=
google.golang.org/grpc v1.19.0/go.mod h1:mqu4LbDTu4XGKhr4mRzUsmM4RtVoemTSY81AxZiDr8c=
google.golang.org/grpc v1.23.0/go.mod h1:Y5yQAOtifL1yxbo5wqy6BxZv8vAUGQwXBOALyacEbxg=
google.golang.org/grpc v1.27.0/go.mod h1:qbnxyOmOxrQa7FizSgH+ReBfzJrCY1pSN7KXBS8abTk=
google.golang.org/protobuf v0.0.0-20200109180630-ec00e32a8dfd/go.mod h1:DFci5gLYBciE7Vtevhsrf46CRTquxDuWsQurQQe4oz8=
google.golang.org/protobuf v0.0.0-20200221191635-4d8936d0db64/go.mod h1:kwYJMbMJ01Woi6D6+Kah6886xMZcty6N08ah7+eCXa0=
google.golang.org/protobuf v0.0.0-20200228230310-ab0ca4ff8a60/go.mod h1:cfTl7dwQJ+fmap5saPgwCLgHXTUD7jkjRqWcaiX5VyM=
google.golang.org/protobuf v1.20.1-0.20200309200217-e05f789c0967/go.mod h1:A+miEFZTKqfCUM6K7xSMQL9OKL/b6hQv+e19PK+JZNE=
google.golang.org/protobuf v1.21.0/go.mod h1:47Nbq4nVaFHyn7ilMalzfO3qCViNmqZ2kzikPIcrTAo=
google.golang.org/protobuf v1.22.0/go.mod h1:EGpADcykh3NcUnDUJcl1+ZksZNG86OlYog2l/sGQquU=
google.golang.org/protobuf v1.23.0/go.mod h1:EGpADcykh3NcUnDUJcl1+ZksZNG86OlYog2l/sGQquU=
google.golang.org/protobuf v1.23.1-0.20200526195155-81db48ad09cc/go.mod h1:EGpADcykh3NcUnDUJcl1+ZksZNG86OlYog2l/sGQquU=
google.golang.org/protobuf v1.25.0 h1:Ejskq+SyPohKW+1uil0JJMtmHCgJPJ/qWTxr8qp+R4c=
google.golang.org/protobuf v1.25.0/go.mod h1:9JNX74DMeImyA3h4bdi1ymwjUzf21/xIlbajtzgsN7c=
honnef.co/go/tools v0.0.0-20190102054323-c2f93a96b099/go.mod h1:rf3lG4BRIbNafJWhAfAdb/ePZxsR/4RtNHQocxwk9r4=
honnef.co/go/tools v0.0.0-20190523083050-ea95bdfd59fc/go.mod h1:rf3lG4BRIbNafJWhAfAdb/ePZxsR/4RtNHQocxwk9r4=
```

**Anything else we should know about your project / environment?**

An example repo can be found at https://github.com/2767mr/prototest.

This issue does not seem to affect actual downloads. `go mod download` seems to only download the newest version.

A visualisation of the mod graph can be found at https://github.com/2767mr/prototest/blob/master/graph.png. There one can easily see that `github.com/golang/protobuf` imports an old version of `google.golang.org/protobuf` which imports an even older version of `github.com/golang/protobuf`.

**Comment by dsnet** [comment]
This is a known issue. It's unfortunate, but relatively harmless. The cyclic dependency is necessary:
* `github.com/golang/protobuf` depends on `google.golang.org/protobuf` because v1.4+ is implemented in terms of the newer module.
* `google.golang.org/protobuf` "depends" on `github.com/golang/protobuf` only to enforce that v1.4+ be used. Aside from that constraint, it requires nothing from the older module. This is necessary to avoid problems with disjoint sets of type registries.

The cyclic relationship can't be broken. 

If there's anything to be done, it probably be with the Go toolchain to prune useless go.sum entries for cyclic dependencies. If so, there's not much this project can do about this issue.

**Comment by 2767mr** [comment]
I did some experiments and I think I came up with a workaround:

It is possible to reference future releases inside a `go.mod`. This means that if both modules reference a future version and then both publish that version it will resolve. I made an example at https://github.com/2767mr/prototest2 v0.0.4 which refences https://github.com/2767mr/prototest3 v0.0.2 and the other way around.

Since `google.golang.org/protobuf` only "depends" on `github.com/golang/protobuf` as a constraint (that is also locked behind a build flag) I recommend never updating that reference in the future. That way a maximum of 2 separate entries in the `go.sum` can be achieved.

**Comment by dsnet** [comment]
> It is possible to reference future releases inside a go.mod.

Yes, for the `go.mod` file, but not for the `go.sum` file. The `go.sum` file contains a hash of the dependencies, but there's a problem. The hash of the dependencies covers the forward version reference to some unreleased module for which we do not know (or rather cannot compute) the hash for.

**Comment by 2767mr** [comment]
The `go.sum` of the imported package doesn't seem to matter. Even though the `go.sum` of  https://github.com/2767mr/prototest2 and https://github.com/2767mr/prototest3 contain references to v0.0.3, v0.0.2 and v0.0.1 but when importing `github.com/2767mr/prototest2@v0.1.0` it results in this `go.sum`: 

```
github.com/2767mr/prototest2 v0.1.0 h1:VPBoYfI30vH+NyVowwfApjdhJs3RWZSksFJ15cmsUkA=
github.com/2767mr/prototest2 v0.1.0/go.mod h1:bgQNNDqWYqKPhU7fSfR+O40OHJBYAHv8ICPzpXGVJj4=
github.com/2767mr/prototest3 v0.1.0 h1:BHRrPhhBo4fwqPw7OVl+8KEo6QCNr88dAvIQqmSSI+g=
github.com/2767mr/prototest3 v0.1.0/go.mod h1:5IVjxmYTIaB2hQkZG1fsTJ40IJTauWED2kdJk0v99+g=
```

**Comment by dsnet** [comment]
I'm not sure how your test repos address the root issue. Both https://github.com/2767mr/prototest2/blob/master/go.sum and https://github.com/2767mr/prototest3/blob/master/go.sum and contain cyclic references to the past history of the other's module.

Stepping back a bit, can you explain why this is an issue that needs resolving? Is this purely a bloat issue or is there a technical issue involved?

**Comment by 2767mr** [comment]
It is true that both test repos contain old versions in their `go.sum`. However, if you import one of these test repos from another module only the newest versions are written to the `go.sum` instead of all the current ones (see my previous comment)

The issue here is indeed simply a bloat issue, no technical issue involved. I found this while looking for potentially bad/unsafe/unused/outdated modules that were used by my project. At first I was quite shocked when I looked into my `go.sum` and found that more than half of my imports were either outdated, dev versions or completely unused. As a user I want to know what I am importing and if I see dev versions in there I have to assume it's not safe to use. I'd also appreciate if third party dependencies would be avoided but it's acceptable as is.

**Comment by dsnet** [comment]
Given that this isn't a pressing issue, we're not going to do anything about this at the moment. It's a significant amount of release tooling work with little gain. Furthermore, it's really something the Go toolchain should do a better job at pruning useless `go.sum` entries.

**Comment by puellanivis** [comment]
I ran into this issue from a situation that happens in prometheus client as well, where this cyclic dependency causes a deep walk down a dependency spiral. It’s not really an easy thing to really fix for reasons laid out already. In their case, they’re only depending on the other module in order for their own internal stuff, which ends up getting pulled into every repo that depends on it.

It’s fine almost all the time, the walk is only made the first time to setup the `go.sum`, and check availability, and go.mod files from the dependencies. Then the solver decides on the newest versions and done, the older versions only ever get their `go.mod` downloaded, and they’re now in the module cache, with no need to download them again.

Really, the only negative is that it creates an unexpected scenario, where after cleaning out your dependencies and your `go.sum`, you find that there’s a whole lot more there than you expect. (And sometimes, in CI, you’ll get a fully clean build with no caching, and see the dependency walk again regularly.) But they’ve decided not to address the issue either, because it’s not really that big of an issue in the larger priorities of projects.

**Comment by dsnet** [comment]
[`google.golang.org/protobuf@v1.26.0`](https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.26.0) and [`github.com/golang/protobuf@v1.5.1`](https://github.com/golang/protobuf/releases/tag/v1.5.1) did a little dance to clear out the go.sum bloat.

For those interested:
1. [drop the dependency on `github.com/golang/protobuf` from `google.golang.org/protobuf`](https://golang.org/cl/262683)
2. release `google.golang.org/protobuf@v1.26.0-rc.1`
3. [add a dependency on `google.golang.org/protobuf@v1.26.0-rc.1` from `github.com/golang/protobuf`](https://github.com/golang/protobuf/commit/f746d3b8ecd31eac7c04a954f3905d46b09f8114).
4. release `github.com/golang/protobuf@v1.5.0`
5. [add a dependency on `github.com/golang/protobuf@v1.5.0` from `google.golang.org/protobuf`](https://golang.org/cl/262684)
6. release `google.golang.org/protobuf@v1.26.0`
7. [upgrade the dependency to `google.golang.org/protobuf@v1.26.0` from `github.com/golang/protobuf`](https://github.com/golang/protobuf/commit/a36a1a1c346d5cb6951b9440755adb530334f910)
8. release `github.com/golang/protobuf@v1.5.1`
