### ISSUE TITLE
How to get a field valued zero through reflection in proto3?

### ISSUE THREAD

**Issue by alpaca2333** [golang/protobuf#1212]
If we had a type
```protobuf
message A {
  int32 a = 1;
}
```
And thus we had the go struct 
```go
type A struct {
  A int32 `...`
}
```
if we use reflection lib to go through A's fields like this:
```go
var a A
a.A = 0 // of course this is not neccessary
proto.MessageReflect(&a).Range(func(fd pref.FieldDescriptor, v pref.Value) bool {
   ... // process here
})
```
then we would not get a field named ‘A’ with value '0'.
Isn't this dumb? if i need a common API which accept all proto.Message to update some data in db, how can i accept a zero value?

**Comment by dsnet** [comment]
The `protoreflect.Message.Range` method is documented as:

> Range iterates over every __populated__ field in an undefined order

Under proto3 semantics, the zero value is not a populated field.

If you want to iterate over every message field regardless of whether it is populated, you can iterate over all the declared fields:
```go
message := m.ProtoReflect()
fields := message.Descriptor().Fields() // all the declared fields in this message type
for i := 0; i < fields.Len(); i++ {
    v := message.Get(fields.Get(i))
    ... // do something with v
}
```

**Comment by alpaca2333** [comment]
@dsnet thanks, perfectly solved my problem. My apologize for not reading the api thoroughly.
