### ISSUE TITLE
growslice issue

### ISSUE THREAD

**Issue by linchuan4028** [golang/protobuf#1213]
When using proto repeated type field, I encounter the growslice performance issue as call unmarshal function.
Do we have a initilize method to pre allocate slice size for a repeated fields.

here is the schema
```
message User_Data_Record {
    message KVR {
    }
    message NPSegment {
        repeated KVR kv = 1; /// this filed encoutner the growslice performance issue
    }
    repeated NPSegment segments = 1;
   
}
```

**Comment by dsnet** [comment]
Without a reproduction, there is not much we can do with this report. Furthermore, it's unclear what "the growslie performance issue" is.

**Comment by linchuan4028** [comment]
There are too much KVR data in the repeated fields and it show that the unmarshal operation is too much slow as I use pprof in golang service
![image](https://user-images.githubusercontent.com/12349182/94402866-2ceba280-019f-11eb-8f24-8b6aa386d717.png)

**Comment by dsnet** [comment]
This identifies gogo/protobuf as the code being use. I think you are filing this bug in the wrong module.

**Comment by dsnet** [comment]
Closing as inactionable. The report does not concern the main protobuf implementation.
