### ISSUE TITLE
Type mismatch - unable to implement gRPC server.

### ISSUE THREAD

**Issue by Shanduur** [golang/protobuf#1218]
**What version of protobuf and what language are you using?**
libprotoc 3.6.1

**What did you do?**
1. Generate grpc from .proto file,
2. Implement server in another package,

**What did you expect to see?**
Working server.

**What did you see instead?**
Bunch of errors, described bellow.

**Anything else we should know about your project / environment?**
I was following [tutorial](https://www.youtube.com/playlist?list=PLy_6D98if3UJd5hxWNfAqKMr15HZqFnqf) and everything worked fine, until today. I had to reinstall my environment, and there appeared error while generating code from Proto files:
```
$ protoc \
--proto_path=pkg/proto \
--go_out=plugins=grpc:. \
pkg/proto/*.proto
--go_out: protoc-gen-go: plugins are not supported; use 'protoc --go-grpc_out=...' to generate gRPC
```

So I changed it to:
```
protoc \
    --proto_path=pkg/proto \
    --go_out=. \
    --go-grpc_out=. \
    pkg/proto/*.proto
```
which generated code successfully.

But my server was implemented inside other package which now causes this error:
```
cmd/server/main.go:27:30: cannot use umServ (type *service.UserManagementServer) as type pb.UserServiceServer in argument to pb.RegisterUserServiceServer:
        *service.UserManagementServer does not implement pb.UserServiceServer (missing pb.mustEmbedUnimplementedUserServiceServer method)
```

**Comment by Shanduur** [comment]
Also, after doing `go get -u github.com/golang/protobuf/protoc-gen-go` I got the following:
```
protoc \
--proto_path=pkg/proto \
--go_out=plugins=grpc:. \
pkg/proto/*.proto
protoc-gen-go: program not found or is not executable
--go_out: protoc-gen-go: Plugin failed with status code 1.
```

**Comment by dsnet** [comment]
Hi, I recommend filing this at https://github.com/grpc/grpc-go/issues, as that repository is responsible for designing and maintaining the grpc framework.
