### ISSUE TITLE
jsonpb: unexpected output for small negative google.protobuf.Duration (again)

### ISSUE THREAD

**Issue by AlekSi** [golang/protobuf#1219]
**What version of protobuf and what language are you using?**
Version: v1.4.2

**What did you do?**
https://github.com/AlekSi/go-bug/tree/master/jsonpb
```go
func TestDuration(t *testing.T) {
	d := -time.Nanosecond
	dp := ptypes.DurationProto(d)
	m := &jsonpb.Marshaler{}
	s, err := m.MarshalToString(dp)
	if err != nil {
		t.Fatal(err)
	}
	if s != `"-0.000000001s"` {
		t.Errorf("Unexpected result: %s", s)
	}
}
```

**What did you expect to see?**
`"-0.000000001s"`

**What did you see instead?**
`Unexpected result: "0.-00000001s"`

**Anything else we should know about your project / environment?**
Issue #883 is back for 1.4.2.

**Comment by AlekSi** [comment]
https://github.com/golang/protobuf/issues/883

> can you confirm whether this was fixed in v2?
> This is fixed in v2.

It is broken again in 1.4.2. @dsnet, @cybrcodr

**Comment by AlekSi** [comment]
It seems to be fixed by https://github.com/protocolbuffers/protobuf-go/commit/e96d591a68bbf65b74ea9756927efaba4e459f57. May you tag a new release please

**Comment by cybrcodr** [comment]
Sorry about that, it probably regressed when jsonpb was rewritten in terms of protoreflect.  The PR you pointed to is not the fix for it.

This issue does not exist in V2, i.e. [google.golang.org/protobuf](https://pkg.go.dev/google.golang.org/protobuf).  It was fixed for V1 in https://github.com/golang/protobuf/pull/885.

Anyways, I'll send a PR to fix this.

**Comment by dsnet** [comment]
This is not a regression starting in v1.4.x, but one that has been there since v1.1.0. The bug was introduced in #492 over 2.5 years ago. If anything, we probably had the bug in the new module in the first place because we copied similar logic over.

**Comment by AlekSi** [comment]
Well, we observed exactly the same behaviour in v1.3.1, reported it as https://github.com/golang/protobuf/issues/883, and it was fixed by https://github.com/golang/protobuf/pull/885 in v1.3.2. Maybe the root cause is different, but the observable behaviour regressed.

**Comment by AlekSi** [comment]
Thank you for resolving that issue quickly, and for the new tag!
