### ISSUE TITLE
jsonpb marshals empty fields

### ISSUE THREAD

**Issue by peter-edge** [golang/protobuf#122]
Which is not what the stdlib json library does, i.e. given:

```
message Foo {
  string one = 1;
  int32 two = 2;
  string string_field = 3;
  int32 int32_field = 4;
```

And the golang message:

```go
foo := &Foo{
  StringField: "one",
  Int32Field: 2,
}
```

This is the result:

```go
data, err := json.Marshal(foo)
fmt.Println(string(data)) // {""string_field":"one","int32_field":2}

buffer := bytes.NewBuffer(nil)
err := jsonpb.Marshal(buffer, foo)
fmt.Println(buffer.Bytes()) // {"one":"","two":0,"string_field":"one","int32_field":2}
```

Is this by design? Or can we change this?

**Comment by dsymonds** [comment]
I believe there's a TODO in `jsonpb.go` to address exactly this.

I can't remember why it hasn't been done yet. Let me look into it.

**Comment by dsymonds** [comment]
Fix is coming.

FWIW, alignment with the standard library's `encoding/json` package is a non-goal. There's a proto3 JSON spec that the `jsonpb` package follows.

**Comment by peter-edge** [comment]
Ya I understand, make sense - I figured this one would be nice to clean up :)

**Comment by hermanschaaf** [comment]
Is there a way to get the old behavior back? ie. in my case I would like to marshal empty fields.

**Comment by hermanschaaf** [comment]
Ah, EmitDefaults=true, ok 👍
