### ISSUE TITLE
compiler/protogen: switch warnings to hard errors

### ISSUE THREAD

**Issue by adambabik** [golang/protobuf#1223]
**Is your feature request related to a problem? Please describe.**
[github.com/grpc-ecosystem/grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway) started using [protogen](https://pkg.go.dev/google.golang.org/protobuf/compiler/protogen) to compile protobuf files to Go. It contains a lot of tests and examples and some of them do not have, for example, `go_package` defined. This results in a flood of warnings when running tests and makes it harder to debug the actual problem.

**Describe the solution you'd like**
[The solution](https://github.com/protocolbuffers/protobuf-go/blob/42cc4c592f87f9c4fa8c52df6a1c0abd6c7fb571/compiler/protogen/protogen_test.go#L21-L23) already exists:

```go
func init() {
	warnings = false // avoid spam in tests
}
```

Which suggests that protobuf-go has the same problem. However, this is private and it's not possible to change `warnings` value from outside of the `protogen` package.

Making it public or introducing a function to change it does not sound good because it will pollute the public interface with functionality which is useful only for tests.

My proposal is to disable warning using an environment variable. It can look like this:

```go
func init() {
	warnings = false // avoid spam in tests
	
	if os.Getenv("PROTOGEN_WARNINGS") == "off" {
		warnings = false
	}
}
```

**Describe alternatives you've considered**
Providing a function to set `warnings` value, as I said above, would pollute the public interface.

A real alternative could be using a build tag to set `warnings` to false, however, this requires to change the code orchestrating tests execution which might introduce additional problems. Defining an environmental variable is more neutral.

**Additional context**
I can work on the implementation if this feature request will be accepted.

**Comment by neild** [comment]
I believe all cases of warnings emitted by `protogen` are ones which we intend to convert to a hard error in the future. I don't think we want to make it easier to ignore these warnings, which would make it likely that users will be unexpectedly broken in the future.

**Comment by adambabik** [comment]
The proposal above would only work in test code. `func init() { ... }` is taken from a `protogen_test.go`. We can change the env name to `PROTOGEN_TEST_WARNINGS` to further indicate it. It would be never available or documented for end users. It would be available only for developers and when warnings are converted to hard errors, the tests would fail even if the env is set.

**Comment by neild** [comment]
The protobuf module has the ability to suppress these warnings, because we need to test the deprecated-but-still-supported cases that we warn on. No other module should be exercising these code paths. Any that are will suddenly break when we promote the warnings to errors, which is exactly the case the warnings are trying to avoid.

**Comment by adambabik** [comment]
I generally agree with this approach, however, the context of grpc-gateway is a bit different. It extends the protobuf module (more precisely the protogen package). The expectation is that it will support the same features as protogen so it also contains tests that check deprecated cases.

Again, the proposed warnings suppression will only work when executing the protobuf source files with `go test`.

**Comment by neild** [comment]
This means that when we convert those warnings to errors, the grpc-gateway module's tests will break. That's unfortunate. I don't think we want to make it easier to ignore that fact.

**Comment by dsnet** [comment]
It's been about 6 months since the initial release of the `google.golang.org/protobuf` module. It's probably about time we turn these warnings into hard errors anyways.

**Comment by adambabik** [comment]
@neild that will be fine, I think (I am not a maintainer) that the goal of grpc-gateway module is to follow whatever and however protobuf-go supports these common features because it ultimates depends on protobuf-go capabilities. I believe that it's also good from the end user perspective. Furthermore, in my opinion, anything using protogen to generate Go files should align the support of common features.

If we can turn the warnings into hard errors soon that would be great!

**Comment by dsnet** [comment]
v1.26, which will be released either this week or next week will make warnings a hard errors.

See https://golang.org/cl/301953
