### ISSUE TITLE
jsonpb allows unmarshaling invalid date

### ISSUE THREAD

**Issue by cedric-parisi** [golang/protobuf#1226]
**What version of protobuf and what language are you using?**
protobuf v1.4.0
go 1.15.1

**What did you do?**
Unmarshal a json request containing an invalide date into a proto.Message struct

**example:**
```go
dest := &Message{} // Which has a UpdatedAt *timestamp.Timestamp attr
err := jsonpb.Unmarshal(strings.NewReader(`{"updated_at":"0000-12-31T23:45:00Z"}`), dest)
assert.Error(t, err)
```

**What did you expect to see?**
A successful test, an error should be returned as the date is invalid according to [validateTimestamp](https://github.com/golang/protobuf/blob/master/ptypes/timestamp.go#L89) method.

**What did you see instead?**
The test fails, there is no error returned.

**Comment by neild** [comment]
The [`google.golang.org/protobuf/encoding/protojson`](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson) package should handle this correctly.

**Comment by cedric-parisi** [comment]
Thanks! I’ll have a look at it!

**Comment by dsnet** [comment]
The [following snippet](https://play.golang.org/p/NGVuJsVgw4y) on the `google.golang.org/protobuf` module:
```go
ts := new(timestamppb.Timestamp)
err := protojson.Unmarshal([]byte(`"0000-12-31T23:45:00Z"`), ts)
fmt.Println(ts, err)
```
correctly fails with:
```
proto: (line 1:1): google.protobuf.Timestamp value out of range: "0000-12-31T23:45:00Z"
```

The `github.com/golang/protobuf` module is frozen for any changes except for regression fixes. This issue is not seem to be a regression. Closing this as "wont fix".
