### ISSUE TITLE
types/known/fieldmaskpb: special parsing behaviour for struct.proto types

### ISSUE THREAD

**Issue by johanbrandhorst** [golang/protobuf#1227]
**Is your feature request related to a problem? Please describe.**
The grpc-gateway needs to be able to parse incoming JSON and generate a field mask from it. This works fine for most types, but specifically for the generic types `google.protobuf.Struct` and `google.protobuf.Value`, the existing `fieldmaskpb.New` and `.Append` behaviour does not allow generic uses of these types. We cannot use the fieldmask helpers in the grpc-gateway until this is supported.

For example, given a field named `struct_field` with a type `google.protobuf.Struct` and the incoming JSON:
```
{"struct_field": {"name":{"first": "bob"}, "amount": 2}}
```

We would like to produce a `paths` slice that looks like:

```
["struct_field.name.first", "struct_field.amount"]
```

**Describe the solution you'd like**
I'd like there to be a special case for these generic, well known types _only_, in the behaviour of the fieldmask helpers.

**Describe alternatives you've considered**
Keeping our own home grown field mask generation and validation logic.

**Additional context**
See [here](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/fieldmask.go) for our current field mask generation logic.

**Comment by neild** [comment]
The field mask syntax is defined here, and is common across languages:
https://developers.google.com/protocol-buffers/docs/reference/csharp/class/google/protobuf/well-known-types/field-mask

If I follow correctly, you're asking for a change to that syntax. Changes that affect multiple protobuf implementations are out of scope for this repository; you should raise the issue on the general [protobuf discussion group](http://groups.google.com/group/protobuf).

Note that if you just want to add a path to a `FieldMask` without validation, `fieldmask.New` and `FieldMask.Append` aren't giving you anything useful. All they do is validate.

(Apologies if I misunderstand the change you're looking for.)

**Comment by dsnet** [comment]
It sounds like you want a `FieldMask`-like message that is specific to JSON, which is an entirely reasonable use case. However, the `FieldMask` well-known type is clearly intended to operate on the semantics of the protobuf type system, not arbitrary JSON objects. It's not clear to me that conflating these two semantics is necessarily a good idea. Either way, I think this needs to be discussed with the main protobuf project since semantics like this would affect all the language implementations of protobufs, not just Go.

**Comment by puellanivis** [comment]
Yeah, definitely sounds like a wider-discussion sort of thing.

**Comment by johanbrandhorst** [comment]
I think I agree, this definitely conflates JSON and general field mask behaviour. Thanks for your thoughts on the topic, I'll put something out on the general protobuf discussion group, since I still think this would be a valuable addition.

**Comment by johanbrandhorst** [comment]
I created a discussion on the protobuf mailing list: https://groups.google.com/g/protobuf/c/Lwm3X-uokBc.
