### ISSUE TITLE
protoc compiler is not generating correct golang *pb.go file

### ISSUE THREAD

**Issue by gaurav36** [golang/protobuf#123]
Hi Team,

I am using protobuf for doing serialization/de-serialization of my data in my golang application. But problem here is that when i execute     "protoc --go_out=. *.proto" command its seems giving some additional (might be wrong) information in *.pb.go file. 

While doing make install in my application its giving following error
rpc/services/peer-svc.pb.go:145: undefined: proto.RegisterType
rpc/services/peer-svc.pb.go:146: undefined: proto.RegisterType
rpc/services/peer-svc.pb.go:147: undefined: proto.RegisterType
rpc/services/peer-svc.pb.go:148: undefined: proto.RegisterType

Anyone aware about this issue ??
If yes, could you tell me what's going wrong here.

Thanks in Advance :)

**Comment by dsymonds** [comment]
Your protoc-gen-go is out of date with the proto package. Make sure they are both synced to tip.
