### ISSUE TITLE
No alternative to jsonpb.UnmarshalNext in v1.25

### ISSUE THREAD

**Issue by mostrows2** [golang/protobuf#1231]
**What version of protobuf and what language are you using?**
Version: 1.25

**What did you do?**
Code using v1.4 and earlier uses `jsonpb.UnmarshalNext()`. There is no equivalent function in v1.25.

I'd like to see a `protojson.UnmarshalNext()`,  but there's only `protojson.Unmarshal()`.
None of the code in `protojson` gives me access to the `Decoder` or lets me inject my own.
As a result in order to reproduce the functionality of `jsonpb.UnmarshalNext` I'd have to make my own copy of the protojson module.

**Comment by dsnet** [comment]
The `UnmarshalNext` function was seldom used and would force the `protojson` package to have a hard dependency on `encoding/json` that can never be removed (should a v2 version of `encoding/json` one day come). There is no need to carry this helper function into the new module.

It's equivalent functionality can be accomplished with:
```
func UnmarshalNext(d *json.Decoder, m proto.Message) error {
	var b json.RawMessage
	if err := d.Decode(&b); err != nil {
		return err
	}
	return protojson.Unmarshal(b, m)
}
```
