### ISSUE TITLE
cmd/protoc-gen-go: generate wrong function name for initialization of imported protofile

### ISSUE THREAD

**Issue by hitzhangjie** [golang/protobuf#1232]
**What version of protobuf and what language are you using?**
Version: porotc-gen-go v1.25.0
              protoc              v3.12.4

**What did you do?**
If possible, provide a recipe for reproducing the error.
A complete runnable program is good with `.proto` and `.go` source code.

I have wrote two protocolbuffer file, as following:

pathto/a.proto:

```
package hello

import "pathto/b.proto"

message Hello {
    xx b.XX
}
```

pathto/b.proto:

```
pakcage hello

message XX{}
```

run `protoc --go_out=source_relative:. pathto/a.proto`, in generated a.pb.go, we have following code:

```go
func file_a_proto_init() {
       file_pathto_b_proto_init()   // which should be `file_b_proto_init`
}
```

the function `file_pathto_b_proto_init` should be `file_b_proto_init`, or the function `file_b_proto_init` in generated b.pb.go should be renamed to `file_pathto_b_proto_init`.

I think it's a bug caused by the import path parsing.

**What did you expect to see?**

I think the generated function name in both file should be the same, like `file_pathto_b_proto_init` in both files a.pb.proto, b.pb.proto.

Causing the function name not matched, it failed when building the programme.

**What did you see instead?**

I see the generated function names in a.pb.go and b.pb.go are not matched.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

I think this problem could be fixed here: 

https://github.com/protocolbuffers/protobuf-go/blob/d3470999428befce9bbefe77980ff65ac5a494c4/cmd/protoc-gen-go/internal_gengo/reflect.go#L160

**Comment by hitzhangjie** [comment]
It is caused by the path parsing:

`protoc -I pathto a.proto` is different from `protoc pathto/a.proto`, the FileDescriptorProto.Name has different value, the latter one contains the directory info, while the former one doesn't.

I think it should contain the path name in either cases.

**Comment by neild** [comment]
> I think it should contain the path name in either cases.

As you note, this isn't something we have any control over; the filenames are provided by `protoc`.  I don't really see any way it could change at this time without causing widespread breakage.

**Comment by hitzhangjie** [comment]
> > I think it should contain the path name in either cases.
> 
> As you note, this isn't something we have any control over; the filenames are provided by `protoc`. I don't really see any way it could change at this time without causing widespread breakage.

OK, Thanks.
