### ISSUE TITLE
protobuf-go: why not make EnumNumber as alias of int32

### ISSUE THREAD

**Issue by timestee** [golang/protobuf#1234]
@dsnet 
// EnumNumber is the numeric value for an enum.
type EnumNumber int32

https://github.com/protocolbuffers/protobuf-go/blob/d3470999428befce9bbefe77980ff65ac5a494c4/reflect/protoreflect/proto.go#L396

Why not make `EnumNumber` as alias of type `int32`. then we could call `.Number()` to compare with `int32` as the old version does.

**Comment by dsnet** [comment]
We need the ability to distinguish between int32 and enums in a type switch. Thus, they are distinctly different types. Regardless, such change can't be made anymore without breaking backwards compatibility.
