### ISSUE TITLE
cant go get github.com/golang/protobuf/protoc-gen-go

### ISSUE THREAD

**Issue by xfarm001** [golang/protobuf#124]
nobody get github.com/golang/protobuf/protoc-gen-go by "go get"

there is a error.
root@ubuntu:~/go# go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
# github.com/golang/protobuf/protoc-gen-go/descriptor
src/github.com/golang/protobuf/protoc-gen-go/descriptor/descriptor.pb.go:33: import /root/go/pkg/linux_amd64/github.com/golang/protobuf/proto.a: not a package file
root@ubuntu:~/go#

**Comment by dsymonds** [comment]
I suspect your Go installation is broken. It's also pretty risky running it all as root. Try clearing out your $GOPATH and trying again.
