### ISSUE TITLE
proto.Unmarshal consumes a lot of cpu, any idea to fix this?

### ISSUE THREAD

**Issue by ricoyoung345** [golang/protobuf#1242]
env:
protobuf: github.com/golang/protobuf v1.4.3
protoc: 3.5.1
golang: go1.13 linux/amd64

in my application, the whole process work like this:
* start a thrift server
* accept request, an get pb_bytes from cache
* unmarshal all the pb_bytes, and do my business logic
* return my response to the client

pb_bytes is of avg size of 50kB

each request will unmarshal 100 pb_bytes

when i call the thrift server with 20 request per second, 2 of 8 cores is occupied by the thrift server, most of the cpu cost is doing unmarshal.

as you can see from the pprof flame graph:
![image](https://user-images.githubusercontent.com/11331995/98507480-a1365d00-2298-11eb-9839-6deaa08ef3c1.png)

![image](https://user-images.githubusercontent.com/11331995/98507598-dfcc1780-2298-11eb-9eba-4a41fddaa6fa.png)

![image](https://user-images.githubusercontent.com/11331995/98507580-d5118280-2298-11eb-93f4-d90396d140ce.png)

even after i depoly my application to an docker env, the cpu&memory metrics really seems wired:
![image](https://user-images.githubusercontent.com/11331995/98507841-5c5ef600-2299-11eb-98c3-28040d5420b8.png)

**Comment by ricoyoung345** [comment]
after the proto unmarshal part every seems normal.
![image](https://user-images.githubusercontent.com/11331995/98509200-ba8cd880-229b-11eb-8cd9-d24aaea99e4c.png)

**Comment by ricoyoung345** [comment]
progress:
use latest protoc-gen-go(v1.25.0) seems reduces cpu cost by about 30%.
old version: can't see detail, below v1.20.0, https://github.com/golang/protobuf/issues/524

**Comment by neild** [comment]
This looks like a server which is doing inexpensive per-request work, so overall CPU time is dominated by decoding.

2000 decodes per second isn't much (20qps * 100 decodes/request), so the individual messages seem to be quite expensive. If changing the structure of your messages is an option, you can probably get some gains there. I notice that map decoding is quite significant in your profile--protobuf map decoding is relatively poorly optimized. Deeply nested messages also tend to be more expensive, so flattening out the message structure can help.

**Comment by ricoyoung345** [comment]
> This looks like a server which is doing inexpensive per-request work, so overall CPU time is dominated by decoding.
> 
> 2000 decodes per second isn't much (20qps * 100 decodes/request), so the individual messages seem to be quite expensive. If changing the structure of your messages is an option, you can probably get some gains there. I notice that map decoding is quite significant in your profile--protobuf map decoding is relatively poorly optimized. Deeply nested messages also tend to be more expensive, so flattening out the message structure can help.

Thanks a lot. There are indeed many deeply nested map structures, i will give an update after I optimize the  proto structure.

**Comment by dsnet** [comment]
Closing as inactionable. Deeply nested data structures are unlikely to perform well due to the many allocations of disjoint objects, and there's not much we can do about that since now we're now in the territory of the Go memory allocator.

The above identified maps as one possible area of improvement, but we already have an open issue regarding optimization of specialized map types (#781). Since maps have an opaque implementation in Go, it's hard to write a generic high-performance map implementation for all combination of types. We can probably optimize `map[string]string` and `map[string]*Message` types, though.
