### ISSUE TITLE
How to get the type message info with a field whose type is another message?

### ISSUE THREAD

**Issue by Abbyyan** [golang/protobuf#1243]
Very awesome project. But i have some question in use. Hope for  your help. Thanks a lot.

i have two protos like follows.
`a.proto`
```shell
package testA;
messaage message_in_testA {
    int i;
}
```
`b.proto`
```shell
import a.proto
message message_in_testB{
   int j;
   message_in_testA k;
}
```
How can i get the info of message `message_in_testA`(such as its full name of file name ) after parsing `b.proto` please?
With c++, i can get this by 
```c++
if (message->field(j)->message_type()){
    const google::protobuf::Descriptor* field_message = message->field(j)->message_type();
}
```
and `field_message` will return a `FileDescriptor` of `a.proto`. Is there any method like this in go please? Thanks a lot!

**Comment by puellanivis** [comment]
I’m not wholly certain if I understand correctly what you’re asking for, but I will answer to the best that I can guess what you’re trying to ask about.

I think what you want is do do a fair amount of reflection on a protobuf message, and the `protoreflect` package provides most of the functionality of reflection on types and information that I think you’re trying to get at here:
```
var B pbB.MessageInTestB

// parse B

// If you know specifically what field is a mesage type, and just want the message descriptor directly:
if B.K != nil {
  messageDescriptor := B.K.ProtoReflect().Descriptor()
  // At this point consult https://pkg.go.dev/google.golang.org/protobuf@v1.25.0/reflect/protoreflect#MessageDescriptor
}

// or, if you need more generic access, because you don’t already know which field is a message:
// (this should also work even if the message is nil)
fieldDescs := B.ProtoReflect().Fields()
for i := 0; i < fieldDescs.Len(); i++ {
  fieldDesc := fieldDescs.Get(i)

  switch fieldDesc.Kind() {
  case protoreflect.MessageKind:
    // if you don’t need to consider other Kind()s, you could also just check `msgDesc != nil`
    msgDesc := fieldDesc.Message()
    // at this point you have another MessageDescriptor same as above
  }
}
```

Note, I’m just reading the docs and trying to give you a direction or breadcrumbs to follow. None of the above is certain to be what you’re looking for, or best practice. Mostly, because I’m unsure of what particular concrete problem you’re trying to address, so I have to give a very generic, broad, and kind of vague answer.

**Comment by Abbyyan** [comment]
Thanks for your help.
I've read https://pkg.go.dev/google.golang.org/protobuf@v1.25.0/reflect/protoreflect#MessageDescriptor and it seems like it will return the message which contains the field other than the message of the field type.
For example, I have a message A and contains a field `info` with type `B`, while `B` is in another `proto file`(That is to say, belong to another `FileDescriptor`). 
```shell
message A{
    optional B info;
}
```
When i use `FieldDescriptor.ProtoReflect().Descriptor()` on `info`, it will return the `Descriptor` of message `A` (which is the parent of field `info`) other than the `Descriptor` of message `B`(which is the type of field `info`). Is there any methods i can get the `message B`'s Descriptor when i'm dealing with the field `info` please?  If there are some mistakes in my understanding, help to point it out please.  Thanks a lot.

**Comment by neild** [comment]
Given a message of type `bpb.MessageInTestB`, you can get the descriptor of `apb.MessageInTestA` with:

```go
var b *bpb.MessageInTestB
mdA := b.ProtoReflect().Fields().ByName("k").Message()
```

(There are a number of other ways you could do this, but this is the one that follows the protoreflect types from the containing message to the field.)

**Comment by dsnet** [comment]
Closing as inactionable. We try to keep this issue tracker about actionable issue. For questions regarding usage, it is better to ask on Slack or someone other means where you can more readily get immediate help. Consider joining the #protobuf channel or the Gophers slack workspace: https://gophers.slack.com/messages/general/
