### ISSUE TITLE
How do I pass the Descriptor to javascript after the DescriptorProto Deprecated?

### ISSUE THREAD

**Issue by dkishere** [golang/protobuf#1244]
My use case is the server-side will pack & tree-shake all the protos required to works with APIs and generate a typescript file to frontend. It works well with DescriptorProto. But it will disappear soon. Could you tell me how to do that with protoreflect as I don't found any marshalble struct in the new Descriptor type? Is that I have to manually implement the method in the current descriptor package?

Thank you

**Comment by dsnet** [comment]
Does [`protodesc.ToDescriptorProto`](https://pkg.go.dev/google.golang.org/protobuf/reflect/protodesc#ToDescriptorProto) do what you want?

**Comment by dkishere** [comment]
looks good, will try thank you!
