### ISSUE TITLE
How to make jsonpb marshal and unmarshal Any like the MarshalTextString and UnmarshalText

### ISSUE THREAD

**Issue by Skywalkerr** [golang/protobuf#1246]
Hi, we are currently using the jsonpb to marshal and unmarshal a proto message with Any type. But we are getting errors as the type in the Any does not exist in the server, we just want to save the raw type_url and value like the proto's `MarshalTextString` and `UnmarshalText`.

We have tried https://github.com/i9/bar/blob/master/bar.go, but it does not save the value of the Any type.

Are there any suggestions? Thanks!

**Comment by dsnet** [comment]
The [JSON mapping for protobufs](https://developers.google.com/protocol-buffers/docs/proto3#json) defines no semantics for `Any` to be represented as the raw `type_url` and `value` fields. The `protojson` and `jsonpb` packages are intended to be faithful implementations of the JSON mapping specification. We cannot change this behavior unless the official protobuf project amends the specification to allow this case.

**Comment by Skywalkerr** [comment]
@dsnet  Thanks for explanation!

**Comment by dsnet** [comment]
Closing this as inactionable on our end. If you think `protojson` should support this, then you should probably file a bug at https://github.com/protocolbuffers/protobuf. This project endeavors to implement the semantics defined by the main protobuf project.
