### ISSUE TITLE
protoc-gen-openapiv2: program not found or is not executable

### ISSUE THREAD

**Issue by true-eye** [golang/protobuf#1247]
**What version of protobuf and what language are you using?**
Version: (e.g., `v1.1.0`, `89a0c16f`, etc) 

**What did you do?**
If possible, provide a recipe for reproducing the error.
A complete runnable program is good with `.proto` and `.go` source code.
I use `protoc` with `--openapiv2_out`

**What did you expect to see?**

**What did you see instead?**
```
protoc-gen-openapiv2: program not found or is not executable
--openapiv2_out: protoc-gen-openapiv2: Plugin failed with status code 1.
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment?**
go version: go version go1.14 linux/amd64
ubuntu: 20.04

**Comment by dsnet** [comment]
There is no such binary as `protoc-gen-openapiv2`. I'm not sure where you got this binary name from. The name of the Go plugin is just `protoc-gen-go`. Which you can obtain with:
```
go install google.golang.org/protobuf/cmd/protoc-gen-go
```
