### ISSUE TITLE
please add `Before` function to timestamp

### ISSUE THREAD

**Issue by mattharrigan** [golang/protobuf#1248]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
I need to sort a slice of timestamps, which needs a comparison function

**Describe the solution you'd like**
A 'Before' function like there is for [time](https://godoc.org/time#Time.Before).

**Describe alternatives you've considered**
Writing the function myself, but this seems common enough that I shouldn't have to.

**Additional context**
Thank you for a very useful module.

**Comment by dsnet** [comment]
Can you justify why `Before` needs to be added when you can do something like:
```go
ts1.AsTime().Before(ts2.AsTime())
```

The moment we add a `Before` helper method, it opens the door to adding all other helper methods defined on `time.Time` to `timestamppb.Timestamp`. We don't want to duplicate all the methods of `time.Time` onto `timestamppb.Timestamp`.

**Comment by mattharrigan** [comment]
I cannot justify it. What you proposed is a better solution. Thank you for a quick reply.
