### ISSUE TITLE
Vendor support

### ISSUE THREAD

**Issue by itsjamie** [golang/protobuf#125]
Hello!

We ran into a issue where a build was failing when using the 15 Vendor experiment. It seems like it is due to this repository importing a `testdata` directory inside protobuf/proto.pb.go. The vendoring tool godep by default doesn't include `testdata` directories or `*_test.go` files when vendoring.

Is there a reason by it is required for operation, or could it be stripped from the generated file? If it can, I'd be happy to figure it out and submit a PR.

**Comment by dsnet** [comment]
The `dev` branch renamed `testdata` as `test_proto`
