### ISSUE TITLE
Documentation is a little misleading and it should be updated

### ISSUE THREAD

**Issue by yehudamakarov** [golang/protobuf#1252]
(Was redirected here at https://github.com/protocolbuffers/protobuf/issues/8090#issue-750929662)

See https://developers.google.com/protocol-buffers/docs/reference/go-generated#invocation

> If the --go_opt=paths=source_relative flag is given to protoc, the output file is placed in the same relative directory as the input file. For example, the file protos/foo.proto results in a file named protos/foo.pb.go.
When you run the proto compiler like this:
`protoc --proto_path=src --go_out=build/gen --go_opt=paths=source_relative src/foo.proto src/bar/baz.proto`
the compiler will read the files src/foo.proto and src/bar/baz.proto. It produces two output files: build/gen/foo.pb.go and build/gen/bar/baz.pb.go.

The problem here is 
> the output file is placed in the same relative directory as the input file

and then 
> It produces two output files: build/gen/foo.pb.go and build/gen/bar/baz.pb.go.

Why are the new files not placed where the docs say they should be placed i.e. `src/` and are instead placed where the flag `--go_out=build/gen` dictates? It seems if both flags are provided there is special behavior where the compiler doesn't guess the output directory based on the package name, but it _**doesn't**_ necessarily put the output files where `--go_opt=paths=source_relative` dictates they should go. Seems like the special behavior is when both are provided just use `--go_out` to calculate the output directory from the root.

Either way, can we please make this more clear? I can't find the repo for the google-developers documentation as it is probably not open.

**Comment by neild** [comment]
This is because of the option `--proto_path=src`, which tells the compiler to consider filenames under `src` as relative to that directory.

The documentation here could probably be clearer.

**Comment by yehudamakarov** [comment]
So
> the output file is placed in the same relative directory as the input file

But with --proto_path, the "input file" is the argument to --proto_path. And output files go in the same relative directory as the argument to --proto_path. 

Is this sounding correct?

If it is I'll play with protoc to make sure it checks out. Then I can leave some sentences here to clarify the docs a bit.

**Comment by neild** [comment]
Every `.proto` file touched by `protoc` essentially has two filenames: The one in the local filesystem, and the one in the protobuf namespace. The name in the protobuf namespace is the one that `import` statements in other `.proto` files use.

For example, on my laptop, `google/protobuf/descriptor.proto` has the local filename  `/usr/local/include/google/protobuf/descriptor.proto`.

`protoc` looks in a list of directories on the local filesystem for files to compile. By default, I think this is the current directory and the common include directory for the system. (So `/usr/local/include` on my laptop.) The `--proto_path` or `-I` flag adds a directory to this list.

When you give `protoc` a filename to compile, it looks in all the search directories to find the file. Then it strips off the longest search directory prefix matching that filename. (If no search directory prefix matches the filename, it prints an error and exits.)

So:

```
protoc --proto_path=src src/foo.proto
```

`protoc` will look for a file to compile in the following locations (I think in this order, but I could be wrong):

* `src/foo.proto` (current directory)
* `/usr/local/include/src/foo.proto` (system include dir)
* `src/src/foo.proto` (src, provided on the command line)

It finds the file named `src/foo.proto`. Then it goes down its list of search prefixes, looking for the longest one which can be stripped. That's 'src', so the filename becomes `"foo.proto"`.

This all happens before `protoc-gen-go` is invoked; all we ever see is `foo.proto`.

(I think this is how it all works, but you should trust the implementation over my recollection.)

**Comment by yehudamakarov** [comment]
Thanks for the thorough explanation. I'm thinking:

To get protoc set up I consulted the documentation where I quoted above. Then I got a little confused while using the different flags. It seems like the docs there can be much clearer. 

In general the flags of protoc should be thoroughly explained somewhere in one place and maybe they are. I couldn't find one place to rule them all. 

We can either 
- Improve or add to the sentences here. 
- Link to _the_ place where the flags of protoc are thoroughly explained. 
- Do both. 
- Do neither (but eh).

I initially opened this directly in protobuf but it was closed right away. 

What would be coolest?

**Comment by yehudamakarov** [comment]
If I saw this while I was reading I would have figured out what I needed to quicker me thinks. 

> If the `--go_opt=paths=source_relative` flag is given to protoc, the output file is placed in the same relative directory as the input file. For example, the file `protos/foo.proto` results in a file named `protos/foo.pb.go` which is then appended (first minus anything that was passed in `-I` or `--proto_path`) to what was passed in the  `--go_out` flag .

I added to the last part. This is compared to what is currently there to read:

> If the --go_opt=paths=source_relative flag is given to protoc, the output file is placed in the same relative directory as the input file. For example, the file protos/foo.proto results in a file named protos/foo.pb.go.

Now, the "minus" part is how I understand what is going on, and you explain it here:
> Then it goes down its list of search prefixes, looking for the longest one which can be stripped. That's 'src', so the filename becomes "foo.proto".

Did you mean: 
> That's 'src/src' so the filename becomes "foo.proto"

**Comment by hitzhangjie** [comment]
any.proto has package directive and go_pacakge file option.

run `protoc --go_out=paths=source_relative:. path-to/any.proto`, any.pb.go isn't put into the same directory where the protofile is.

What's the meaning of `source_relative`?
Doesn't it mean the same directory of proto file?

I think I misunderstand it.

**Comment by hitzhangjie** [comment]
Hi, as @neild  said, 

>When you give protoc a filename to compile, it looks in all the search directories to find the file. Then it strips off the longest search directory prefix matching that filename. (If no search directory prefix matches the filename, it prints an error and exits.)

In my testcase, I found that it didn't strip off the `longest` search directory, it behaves like that only the first matched search directory is stripped off, which maybe not the longest match.

Let me show the testcase:

this is my test script:

```bash
protoc \
    --proto_path=$HOME/test/pb/proto \
    --proto_path=$HOME/test/pb/proto/trpc/video_app_short_video/subscribe \
    --go_out=paths=source_relative,Msubscribe_backend_rpc.proto=git.code.oa.com/vlib/go/proto/trpc/video_app_short_video/subscribe,Mcom/tencent/qqlive/protocol/pb/subscribe_rpc.proto=git.code.oa.com/vlib/go/proto/com/tencent/qqlive/protocol/pb:. \
    $HOME/test/pb/proto/trpc/video_app_short_video/subscribe/subscribe_backend_rpc.proto
```

As we see that, I passed paths=source_relative option, and I expect the generated subscribe_backend_rpc.pb.go will be in current directory.

the filepath is `$HOME/test/pb/proto/trpc/video_app_short_video/subscribe/subscribe_backend_rpc.proto`,
the longest matched search path is --proto_path=$HOME/test/pb/proto/trpc/video_app_short_video/subscribe,
so the generated *.pb.go should be `$(pwd)/subscribe_backend_rpc.pb.go`.

If I run protoc as mentioned above, the generated *.pb.go is at `$(pwd)/trpc/video_app_short_video/subscribe`, but if I swap the two --proto_path options, it works as expected.

I haven't check the protoc-gen-go source code. There may be a bug.

**Comment by neild** [comment]
> In my testcase, I found that it didn't strip off the longest search directory, it behaves like that only the first matched search directory is stripped off, which maybe not the longest match.

I probably was mistaken about that, then. This behavior is implemented by `protoc`, not `protoc-gen-go`, and I'm significantly less familiar with its internals.

In the interest of clarity, it is probably best to avoid overlapping `--proto_path` options.

**Comment by dsnet** [comment]
Documentation has been updated.
