### ISSUE TITLE
Better document setting oneof fields

### ISSUE THREAD

**Issue by grantwwu** [golang/protobuf#1255]
The [documentation](https://developers.google.com/protocol-buffers/docs/reference/go-generated#oneof) states:

> For a oneof field, the protobuf compiler generates a single field with an interface type isMessageName_MyField.

And so it states that the generated structs look like this:

```
type Profile struct {
        // Types that are valid to be assigned to Avatar:
        //      *Profile_ImageUrl
        //      *Profile_ImageData
        Avatar isProfile_Avatar `protobuf_oneof:"avatar"`
}
```

However, then in the example code it goes on to set it this way:

```
p1 := &account.Profile{
  Avatar: &account.Profile_ImageUrl{"http://example.com/image.png"},
}
```

Note that the field name is `Avatar` not `isProfile_Avatar`.

Am I missing something with my understanding of golang or this package?

**Comment by puellanivis** [comment]
I think you have read the ordering of field and type backwards in the struct? The generated `struct` code says the field is `Avatar` and is of type `account.isProfile_Avatar`, and then the assignment assigns into the field name `Avatar` the actual concrete value of a complex literal of type `*account.Profile_ImageURL` which implements `account.isProfile_Avatar`.

**Comment by grantwwu** [comment]
Oops, I think you are right.
