### ISSUE TITLE
protojson does not properly unmarshal WKT Struct

### ISSUE THREAD

**Issue by cretz** [golang/protobuf#1256]
**What version of protobuf and what language are you using?**

google.golang.org/protobuf v1.25.0

**What did you do?**

This:

```go
func temp() error {
	var any anypb.Any
	err := protojson.Unmarshal([]byte(`{
		"@type": "type.googleapis.com/google.protobuf.StringValue",
		"value": "some string"
	}`), &any)
	if err != nil {
		return err
	}
	fmt.Printf("Any: %v\n", &any)
	return nil
}
```

Properly outputs:

    Any: [type.googleapis.com/google.protobuf.StringValue]:{value:"some string"}

But this:

```go
func temp() error {
	var any anypb.Any
	err := protojson.Unmarshal([]byte(`{
		"@type": "type.googleapis.com/google.protobuf.Struct",
		"foo": "bar"
	}`), &any)
	if err != nil {
		return err
	}
	fmt.Printf("Any: %v\n", &any)
	return nil
}
```

Fails with:

    proto: (line 3:3): unknown field "foo"

Same if I try to use the "fields" key too.

**What did you expect to see?**

A properly unmarshaled struct

**What did you see instead?**

An error

**Comment by cybrcodr** [comment]
https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#any

> If the embedded message type is well-known and has a custom JSON representation,
> that representation will be embedded adding a field **value** which holds the custom
> JSON in addition to the @type field.
> 

Here's the corrected valid JSON instead for what you posted --

```
{
    "@type": "type.googleapis.com/google.protobuf.Struct",
    "value": { "foo": "bar" }
}
```
