### ISSUE TITLE
json_name option is not populated to go tag

### ISSUE THREAD

**Issue by kazegusuri** [golang/protobuf#126]
It seems protobuf3 supports explicit json name by `json_name` option for each field, but not populated to json field in go tag in generated go files.

In this proto file:

```
message Msg {
 int64 MyFieldName = 1 [json_name="my_field_name"];
}
```

I expect  the following proto.pb.go is generated:

```
type Msg struct {
        MyFieldName int64 `protobuf:"varint,1,opt,name=MyFieldName" json:"my_field_name,omitempty"`
}
```

But generated:

```
type Msg struct {
        MyFieldName int64 `protobuf:"varint,1,opt,name=MyFieldName" json:"MyFieldName,omitempty"`
}
```

**Comment by dsymonds** [comment]
I'm waiting on protoc to plumb that through to the plugins that it executes (in this case, protoc-gen-go). It's due to happen for their 3.0.0 release.
