### ISSUE TITLE
devsite: fix documentation regarding "M" flag

### ISSUE THREAD

**Issue by Antonboom** [golang/protobuf#1264]
From https://developers.google.com/protocol-buffers/docs/reference/go-generated

```
As an alternative to the go_package option, the Go import path for a .proto
file may be specified on the command line with the --go_opt=M=$FILENAME=$IMPORT_PATH flag to protoc.
```

```
$ tree proto/testroot                               
proto/testroot
├── test
│   └── a.proto
└── testb
    └── b.proto
```

**a.proto:**
```proto
syntax = "proto3";

option go_package = "a;aproto";
package a;

message A {

}
```

**b.proto:**
```proto
syntax = "proto3";

import "test/a.proto";

option go_package = "b;bproto";
package b;

message B {
  repeated a.A fields = 1;
}
```

Run
```
protoc \
         -I proto/testroot \
         --go_opt=M=test/a.proto=TESTTESTTESTTEST \
         --go_out=prototest \
         proto/testroot/*/*.proto
```

**b.pb.go:**
```golang
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: testb/b.proto

package bproto

import (
	a "a" // <------ "TESTTESTTESTTEST" was expected
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)
```

### Why do i want to use this option? 
So that clients using my contracts do not depend on the import path hardcoded in it (through `go_option`).

**Comment by dsnet** [comment]
I think the documentation has a typo, it should be:
> --go_opt=Mtest/a.proto=TESTTESTTESTTEST

Notice the lack of an equals sign after the `M` flag? If it works, I'll fix the documentation.

**Comment by Antonboom** [comment]
@dsnet, you are amazing!

Everything works as expected with
```
--go_opt=Mtest/a.proto=TESTTESTTESTTEST
```

If it doesn't bother you, can you show the place in the code where this option is processed? I dug in the source and could not find anything except processing the `import_prefix` :(

**Comment by dsnet** [comment]
> If it doesn't bother you, can you show the place in the code where this option is processed?

https://github.com/protocolbuffers/protobuf-go/blob/160c7477e0e899d5072bb25635f46053df619fbf/compiler/protogen/protogen.go#L200-L212

**Comment by mieubrisse** [comment]
Just stumbled over this too - was confused by `M=` notation wasn't doing anything, and only found the correct answer through https://github.com/golang/protobuf/issues/1266 . @dsnet , I can confirm that nothing happens with `M=` and just `M` is required

**Comment by dsnet** [comment]
Seems that @neild fixed this.
