### ISSUE TITLE
How to stop protoc-gen-go from downgrading to the previous version (1.23.0)

### ISSUE THREAD

**Issue by Neats29** [golang/protobuf#1268]
I can't work out why all of a sudden when I run `protoc -I . <service>.proto` it generates a pb.go file with an older version of protoc-gen-go (see image below)

![Screenshot 2021-01-11 at 12 31 44](https://user-images.githubusercontent.com/9632022/104182924-17764d80-5409-11eb-9973-f41dbc548f7f.png)

## Environment
- I have protobuf version **3.14.0** installed globally via homebrew (`brew info protobuf` or `protoc --version`)
- in the project, I have `google.golang.org/protobuf v1.25.0` and `github.com/golang/protobuf v1.4.3`  installed via go.mod – but this happens for me across all the services which suggests the problem is to do with the global module
- My go version is: `go1.15.6 darwin/amd64` (the latest)

I appreciate any suggestions.
Thanks

**Comment by puellanivis** [comment]
> `I have google.golang.org/protobuf v1.25.0` installed via go.mod …

The `protoc-gen-go` binary has to be v1.25.0, and it will not automatically use the value in the go.mod, you have to manage the binary yourself.

**Comment by Neats29** [comment]
Thank you. I resolved my issue by using a different version of protobuf.
