### ISSUE TITLE
get map values

### ISSUE THREAD

**Issue by juceberipe** [golang/protobuf#127]
I have this proto:

message ProductoUpdate {
  map<int32, Valor> map_valor = 1;
}

message Valor {
  oneof kind {
    int32 integer32_value = 1;
    int64 integer64_value = 2;
  }
}

can you provide a example or link of how can i get map map_valor?

**Comment by dsymonds** [comment]
Have you looked at the generated code?

That isn't a valid proto definition; you've left something out.

**Comment by juceberipe** [comment]
sorry, this is the valid proto

message ProductoUpdate {
  map<int32, Valor> map_valor = 1;
}

message Valor {
  oneof kind {
    int32 integer32_value = 1;
    int64 integer64_value = 2;
  }
}

**Comment by dsymonds** [comment]
So did you look at the generated code? The ProductoUpdate struct will have a map field.
