### ISSUE TITLE
Patch request with field_masks got syntax error

### ISSUE THREAD

**Issue by renyijiu** [golang/protobuf#1273]
I have created an issue in `gateway` project but developer thinks it is a problem of protobuf, so i ask for help here. [https://github.com/grpc-ecosystem/grpc-gateway/issues/1930#issue-795030441](https://github.com/grpc-ecosystem/grpc-gateway/issues/1930#issue-795030441)

### Steps
I have an api defined as follows:
```
  rpc UpdateMission(UpdateMissionRequest)
      returns (Mission) {
    option (google.api.http) = {
      patch: "/v1alpha2/{mission.name=missions/*}"
      body: "*"
    };
  }

message UpdateMissionRequest {
  Mission mission = 1;
  google.protobuf.FieldMask update_mask = 2;
}
```

according to the [https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/patch_feature](https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/patch_feature), if i send a request with body as follows:
```
{
    "mission": {
        "name": "missions/5ceebd25-b73f-40fb-8597-e36657e24275",
        "driver": {
            "email": "hello"
        }
    },
    "update_mask": "driver"
}

```
it works fine and updates record success. But if i use update_mask with `paths` then will get error
```
{
    "mission": {
        "name": "missions/5ceebd25-b73f-40fb-8597-e36657e24275",
        "driver": {
            "email": "hello"
        }
    },
    "update_mask": {
        "paths": [
            "driver"
        ]
    }
}
```

#### response
```
{
    "code": 3,
    "message": "proto: syntax error (line 8:20): unexpected token {"
}
```

and `config` as flows
```
runtime.WithMarshalerOption(runtime.MIMEWildcard, &runtime.HTTPBodyMarshaler{
	Marshaler: &runtime.JSONPb{
		MarshalOptions: protojson.MarshalOptions{
			UseProtoNames:   true,
			EmitUnpopulated: false,
		},
		UnmarshalOptions: protojson.UnmarshalOptions{
			DiscardUnknown: true,
		},
	},
}),
```

So i want to know v2 no longer support the `paths`  grammar or i miss something ? thanks.

**Comment by neild** [comment]
Field masks have special syntax in the JSON encoding:
https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#json-encoding-of-field-masks

**Comment by renyijiu** [comment]
> Field masks have special syntax in the JSON encoding:
> https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#json-encoding-of-field-masks

Thanks, it looks grammar has changed. In gateway(v1) can be used as flow: 
```
  "update_mask": {
      "paths": [
          "hello",
          "world"
      ]
  }
```

but in gateway(v2) need to update the field format
```
"update_mask":  "hello,world"
```

**Comment by dsnet** [comment]
The v1 implementation was unfortunately in violation of the specified behavior for `FieldMask`. The v2 implementation correctly implements how `FieldMask` is supposed to be serialized. I don't think there's anything we can do about this unfortunate situation. Making v2 accept the older form will make it non-compliant. Existing usages that needs compatibility can continue to use the v1 `jsonpb` package.

**Comment by renyijiu** [comment]
> The v1 implementation was unfortunately in violation of the specified behavior for `FieldMask`. The v2 implementation correctly implements how `FieldMask` is supposed to be serialized. I don't think there's anything we can do about this unfortunate situation. Making v2 accept the older form will make it non-compliant. Existing usages that needs compatibility can continue to use the v1 `jsonpb` package.

Thanks，i understand the difference between the v1 and v2, i will update my application to support this.
