### ISSUE TITLE
Reflection issues

### ISSUE THREAD

**Issue by FedorLap2006** [golang/protobuf#1274]
My reflection on protobuf server just gone crazy.
I have two services located like that
```
services/
    a/
       api/
             a.proto
       Makefile
     b/
         api/
               b.proto
         Makefile
```
And `b` depends on `a`, so I include it like that: `a/api/a.proto` using `-I ../` include path.
On compilation - everything works fine... but when I'm trying to access my server with, for example, `grpcurl` or `evans` - they both don't want to detect my service (package, messages, services) at all.

Earlier `grpcurl` was showing me something like `Symbol not found: project.services.b.MyService, caused by: File not found: a/api/a.proto`. So, I thought that maybe problem in the path, but I don't know exactly where is the problem, that's why I went here.
Note: service `a`, which is standalone (doesn't depend on anything), works fine with both clients.

**Comment by FedorLap2006** [comment]
Or wait... maybe I should go into `grpc` repo with this issue?

**Comment by puellanivis** [comment]
Hm, yeah, it depends likely on what issues you’re running into. If they’re all gRPC related, you should probably take this to them. If you cannot even access the protobuf messages themselves, then that might be a this-repo issue.

You could try taking this over to the gRPC repo, and see if someone there knows what’s going on. Especially with `grpcurl` they’re going to have a lot more experience and knowledge about that than here.

**Comment by FedorLap2006** [comment]
It seems messages can't be accessed too, but I not quiet sure

**Comment by FedorLap2006** [comment]
```
grpc.reflection.v1alpha.ServerReflection is a service:
service ServerReflection {
  rpc ServerReflectionInfo ( stream .grpc.reflection.v1alpha.ServerReflectionRequest ) returns ( stream .grpc.reflection.v1alpha.ServerReflectionResponse );
}``` this is the only thing it gives by invocation of `grpcurl -plaintext localhost:8083 describe`.

**Comment by FedorLap2006** [comment]
Oh, wait, lol, all of my services show only grpc server reflection service :laughing:

**Comment by FedorLap2006** [comment]
Well, I have one more detail: using `grpcurl -plaintext localhost:8083 describe` I found that `grpcurl` can't resolve my service because it can't find `a/api/a.proto`. So... the problem is clearly that protobuf strangely registered my `a/api/a.proto` and now it can't find it.

**Comment by puellanivis** [comment]
I don’t know how we can help you here. But I believe the issue is that you need to match the `-I` option that you used during compilation of the `b.proto` files. Other programs will not magically know where `a/api/a.proto` is unless you tell them, and so far, I think you have only told `protoc` where to find it.

**Comment by FedorLap2006** [comment]
Wait, so you're saying that the problem is in client?

**Comment by FedorLap2006** [comment]
Also, what do you mean by 
>  `-I` option that you used during compilation of the `b.proto` files
If I've already done `-I .` (from `services` directory)

**Comment by dsnet** [comment]
It's not clear to me that's there anything to do on our end. All messages generated by `protoc-gen-go` are available for reflection introspection through the [`protoregistry`](https://pkg.go.dev/google.golang.org/protobuf/reflect/protoregistry) package. If they service reflection is not working, I suspect that the problem exists elsewhere?

I should note that the main reasons why messages might not show up in the global registry is if the official `protoc-gen-go` is not being used to generate messages, or the `.proto` files have insufficiently unique namespaces such that there is a collision in the protobuf namespace.

**Comment by FedorLap2006** [comment]
Well, I solved the problem, using `cd .. && protoc ...` to compile everything from my `services` directory.

**Comment by FedorLap2006** [comment]
Should I close this issue because I already solved the problem?

**Comment by dsnet** [comment]
> Should I close this issue because I already solved the problem?

That would be appropriate. The issue tracker is primarily for actionable items. There doesn't seem to be anything we can do since the root problem seems to be a UX issue with the `protoc` tool itself (which we don't maintain).
