### ISSUE TITLE
protoc-gen-go: Confusing/wrong warning when explicit package name begins with _

### ISSUE THREAD

**Issue by neild** [golang/protobuf#1276]
A `go_package` option of `"example.com/m/type"` will produce a warning suggesting `"example.com/type;_type";`. (Because `type` is a Go keyword, so we can't have a package named "type".)

A `go_package` option of `"example.com/m/type;_type"` will produce a warning suggesting `"example.com/type;__type";`, because [`strs.GoSanitized`](https://go.googlesource.com/protobuf/+/refs/heads/master/internal/strs/strings.go#71) strips the leading `_` before checking for keyword conflicts.

And so on.

Example:

```proto
syntax = "proto3";
package type;
option go_package = "example.com/type;_type";
message Type {}
```

```
$ protoc --go_opt=paths=source_relative --go_out=out m.proto
2021/02/16 10:42:43 WARNING: Malformed 'go_package' option in "m.proto", please specify:
	option go_package = "example.com/type;__type";
A future release of protoc-gen-go will reject this.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.
```

**Comment by dsnet** [comment]
This is no longer relevant with https://golang.org/cl/301953 since we don't suggest any `go_package` options since we're almost certainly going to suggest something wrong.
