### ISSUE TITLE
cmd/protoc-gen-go: print version to stdout

### ISSUE THREAD

**Issue by iamniting** [golang/protobuf#1279]
**What version of protobuf and what language are you using?**
$ ./protoc-gen-go --version
protoc-gen-go v1.25.0

**What did you do?**
I am checking a version of `protoc-gen-go`. The binary prints version as an stderr. 

**What did you expect to see?**
$ ./protoc-gen-go --version 2> /dev/null
protoc-gen-go v1.25.0

**What did you see instead?**
$ ./protoc-gen-go --version 2> /dev/null
`no output here`

**Anything else we should know about your project / environment?**
I have downloaded pkg from https://github.com/protocolbuffers/protobuf-go/releases/download/v1.25.0/protoc-gen-go.v1.25.0.linux.386.tar.gz

I guess this is the right place to file this issue as I did not see issues section https://github.com/protocolbuffers/protobuf-go/

**Comment by puellanivis** [comment]
This is an artifact of how `protoc` itself works with plugins. It opens up a pipe to the standard in and out of the plugin, and writes the compiled proto descriptors to the pipe that leads to the plugin’s STDIN, and the plugin in exchange writes out its code to STDOUT, which `protoc` receives and then turns into the actual files.

There is simply nothing that can be done about this, the version can only at best be printed to STDERR, as STDOUT would be potentially incompatible with the plugin contract.

**Comment by dsnet** [comment]
> There is simply nothing that can be done about this, the version can only at best be printed to STDERR, as STDOUT would be potentially incompatible with the plugin contract.

The "plugin" contrast is pretty ill-defined unfortunately. To my knowledge, `protoc` will never call `protoc-gen-go` with the `--version` flag directly. I kinda wish there was an explicit environment variable or flag that `protoc` would pass to signal that it was running `protoc-gen-go` in plugin mode, but that ship has sailed long ago. 

Switching this to stdin would at least get `protoc-gen-go` to be consistent with other common tools like `ls`, `gzip`, `tar`, etc.

**Comment by puellanivis** [comment]
> The "plugin" contrast is pretty ill-defined unfortunately. To my knowledge, protoc will never call protoc-gen-go with the --version flag directly.

Indeed. I think just a bit of the SRE in me going, “ 😬 we gotta be overly safe!”

**Comment by dsnet** [comment]
Actually, it further occurred to me that even if `protoc` did call `protoc-gen-go` with the `--version` flag, the current behavior is to `os.Exit(0)` immediately anyways. So `protoc` today can't possibly be expecting `protoc-gen-go` to do anything useful if `--version` is passed.

**Comment by neild** [comment]
AFAIK, there are no circumstances under which `protoc` will pass a command-line flag to a plugin. It communicates solely through the `CodeGeneratorRequest` message.

**Comment by dsnet** [comment]
Fixed with https://go-review.googlesource.com/c/protobuf/+/301952
