### ISSUE TITLE
new proto3 types

### ISSUE THREAD

**Issue by awalterschulze** [golang/protobuf#128]
Are you considering given a message like the following:
```
message A {
   optional Duration Dur = 1;
}
```
to generate the following go code
```
type A struct {
    Dur time.Duration
}
```
or to generate
```
type A struct {
    Dur *duration.Duration
}
```
, because I can only imagine my first feature request and I really hope to not have to support this fork as well, but I am not trying to pick a battle.  I am just a little anxious to know so I can mentally prepare myself for the work.

**Comment by dsymonds** [comment]
It'll generate the second code. There will be a support package to make it easier to convert between `*duration.Duration` and `time.Duration` (and similarly for other WKTs).

**Comment by awalterschulze** [comment]
Interesting :)  Ok so would the GetDur() method maybe use this support package? 
Or would the support package be separate and up to the users discretion to use?
Or?

**Comment by dsymonds** [comment]
That's still up for debate, but the current expectation is the latter: entirely up to user discretion. We want these types to be otherwise regular proto messages. (For instance, the getters returning something else would then also have to return an error.)

**Comment by awalterschulze** [comment]
Ok I'll wait to see what you decide.
Thank you for sharing in the meantime.
