### ISSUE TITLE
`protoreflect.Value.Interface()` returns incorrect `interface{}` type for oneof field values that are messages

### ISSUE THREAD

**Issue by chkohner** [golang/protobuf#1283]
**What version of protobuf and what language are you using?**

Version: 1.4.3, go version go1.15.7 windows/amd64

**What did you do?**

`protoreflect.Value` does not seem to provide the correct type attached to the `interface{}` for message oneof fields. For example, given the following protobuf:

```protobuf
syntax = "proto3";

message Image {
    string mime_type = 1;
    bytes data = 2;
}

message Person {

    string name = 1;

    oneof avatar {
        string url = 2;
        Image image = 3;
    }
}
```

And the following program:

```go
func main() {

	a := &person.Person{
		Name: "A",
		Avatar: &person.Person_Url{
			Url: "https://...",
		},
	}

	b := &person.Person{
		Name: "B",
		Avatar: &person.Person_Image{
			Image: &person.Image{
				MimeType: "image/png",
				Data:     []byte{ /*...*/ },
			},
		},
	}

	fmt.Printf("A:\n")
	a.ProtoReflect().Range(func(fd pref.FieldDescriptor, val pref.Value) bool {
		fmt.Printf("  %s = %T\n", fd.Name(), val.Interface())
		return true
	})

	fmt.Printf("B:\n")
	b.ProtoReflect().Range(func(fd pref.FieldDescriptor, val pref.Value) bool {
		fmt.Printf("  %s = %T\n", fd.Name(), val.Interface())
		return true
	})

	msg := b.ProtoReflect()
	imageFd := msg.Descriptor().Fields().ByName("image")
	fmt.Printf("has image = %v\n", msg.Has(imageFd))
	ival := msg.Get(imageFd).Interface() // incorrectly has type *impl.messageState
	fmt.Printf("type = %T\n", ival)

	// pointer address seems correct, however
	im := (*person.Image)(unsafe.Pointer(reflect.ValueOf(ival).Pointer()))
	fmt.Printf("mime type = %s\n", im.MimeType)
}
```
It prints out the following:

```console
> go run main.go
A:
  name = string
  url = string
B:
  name = string
  image = *impl.messageState
has image = true
type = *impl.messageState
mime type = image/png
```

**What did you expect to see?**

The value obtained from the message's `image` field should have a type of `*person.Image`.

**What did you see instead?**

The interface is of type `*impl.messageState` which prevents expected normal interface coercion to the proper type. i.e. `val.Interface().(*person.Image)`

**Comment by dsnet** [comment]
I don't think this has anything to do with oneofs.

The issue that [`protoreflect.Value`](https://pkg.go.dev/google.golang.org/protobuf/reflect/protoreflect#Value) operates on a `protoreflect.Message` types for a message, and not a `proto.Message`.

To obtain on a `proto.Message`, you'll need to additionally call the [`protoreflect.Message.Interface` method](https://pkg.go.dev/google.golang.org/protobuf/reflect/protoreflect#Message.Interface).

This should do what you want:
```go
b.ProtoReflect().Range(func(fd pref.FieldDescriptor, val pref.Value) bool {
	v := val.Interface()
	if m, ok := v.(pref.Message); ok {
		v = m.Interface()
	}
	fmt.Printf("  %s = %T\n", fd.Name(), v)
	return true
})
```

**Comment by chkohner** [comment]
Ah, indeed, you are correct!
