### ISSUE TITLE
failed to parse trace: no consistent ordering of events possible

### ISSUE THREAD

**Issue by Tovi163** [golang/protobuf#1289]
curl http://ip:port/debug/pprof/trace?seconds=5 > trace.out
go tool trace trace.out

with error:
2021/03/10 20:04:36 Parsing trace...
failed to parse trace: no consistent ordering of events possible

anyone meet this error, thanks!

note:
go version: go1.14
protobuf version: github.com/golang/protobuf v1.4.2

**Comment by puellanivis** [comment]
I don’t see how protobuf is related to this issue? Perhaps you could add more details?

**Comment by dsnet** [comment]
Closing as inactionable on our end.
