### ISSUE TITLE
Imports of google/protobuf/*.proto should point to types packages in generated code

### ISSUE THREAD

**Issue by aaronbee** [golang/protobuf#129]
Now that #50 has been implemented (thanks!), it would be nice if the code generated by protoc-gen-go pointed to the included compiled files.

For example, if a .proto files imports google/protobuf/any.proto, I need to pass
`Mgoogle/protobuf/any.proto=github.com/golang/protobuf/types/any`
to the protoc-gen-go plugin.

Is the plan to update protoc-gen-go to automatically handle these imports?

**Comment by dsymonds** [comment]
It's a good idea. There's another issue open for figuring out how to improve the `M` mapping in general, but perhaps these special types deserve special treatment.

**Comment by dsymonds** [comment]
I think the better plan is in #139, namely letting the .proto file declare its import path. Then we don't need to bake it in to protoc-gen-go.

**Comment by peter-edge** [comment]
The problem here is that the well-known type files in google/protobuf do not have this - I would think it should either be added to google/protobuf, or we should not assume this in golang/protobuf
