### ISSUE TITLE
earthly for builds?

### ISSUE THREAD

**Issue by vladaionescu** [golang/protobuf#1291]
Hi there,

I'm wondering if you're interested in trying out [Earthly](https://github.com/earthly/earthly) for builds. I'd be happy to help with a PR.

Earthly could help with:
* reproducing CI failures locally, via containers
* testing against multiple versions of Go in parallel

Happy to do this work myself if this is of interest. Let me know!

**Comment by dsnet** [comment]
Hi, thanks for the suggestions, but GitHub actions suites our usage needs. We'll continue using that for the time being.

**Comment by vladaionescu** [comment]
Sounds good, no worries. Earthly can work on top of GHA BTW.
