### ISSUE TITLE
fieldmaskpb.Normalize() puts repeated fields out of place

### ISSUE THREAD

**Issue by pcriadoperez** [golang/protobuf#1295]
**What version of protobuf and what language are you using?**
Version: v.1.26.0

**What did you do?**
```
fm := &fieldmaskpb.Fieldmask{Paths: [] string{"x_field", "repeated_field"}
fm.Normalize()

// Expected Paths: [] string{"x_field", "repeated_field"}
// Actual Paths: [] string{"repeated_field", "x_field"}
```

**What did you expect to see?**
Normalize converts the mask to its canonical form where all paths are sorted, with repeated fields last and redundant paths are removed.

**What did you see instead?**
Repeated field gets sorted as any other path.

Repeated fields must be last: https://go-review.googlesource.com/c/protobuf/+/246097/

**Comment by neild** [comment]
A repeated field must be the last component of a path. For example, the path `"a.b.c"` consists of three components: `a`, `b`, and `c`. `a` and `b` must not be repeated fields.


A FieldMask contains a set of paths. The order of the paths in a FieldMask is not generally significant. The `Normalize` operation sorts the paths in the `FieldMask`, not the components of a path.
