### ISSUE TITLE
Prebuilt binaries are missing from 1.26.0

### ISSUE THREAD

**Issue by sagikazarmark** [golang/protobuf#1299]
**What version of protobuf and what language are you using?**
Version: 1.26.0

**What did you do?**
Tried to download the prebuilt binaries from https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.26.0

**What did you expect to see?**
Prebuilt binaries

**What did you see instead?**
There are no prebuilt binary assets uploaded

**Comment by dsnet** [comment]
My apologies for forgetting to upload them. Fixed.

**Comment by sagikazarmark** [comment]
Thanks for the quick fix!
