### ISSUE TITLE
Unexpected underscore in generated name of nested message

### ISSUE THREAD

**Issue by jmalloc** [golang/protobuf#1303]
**What version of protobuf and what language are you using?**

- go v1.16.2
- libprotoc v3.15.6
- proto-gen-go v1.26.0

**What did you do?**

- Defined a message called `Outer`
- Defined a nested message within `Outer` called `Inner`
- User `Inner` inside a `oneof` with a name that differs only by case (`inner`, note lower case `i`).

`underscore.proto`:
```go
syntax = "proto3";
package underscore;

option go_package = "./underscore";

message Outer {
  message Inner {}

  oneof value {
    Inner inner = 1;
  }
}
```

`go.mod`:
```
module underscore

go 1.16

require (
	github.com/golang/protobuf v1.5.1
	google.golang.org/protobuf v1.26.0
)
```

Generated with:

```bash
protoc --go_out=paths=source_relative,plugins=grpc:. ./*.proto
```

**What did you expect to see?**

I expected the `Inner` message be represented in Go by a struct named `Outer_Inner`.

**What did you see instead?**

An unexpected trailing underscore, such that the type name is `Outer_Inner_`.

**Anything else we should know about your project / environment?**

This looks very similar to https://github.com/golang/protobuf/issues/780, insofar as I think there is a perceived conflict that does not actually exist. 

The unexpected underscore is not present if the field name within the `oneof` is changed, for example:

```proto
oneof value {
    Inner something_else = 1;
  }
```

/cc @danilvpetrov

**Comment by dsnet** [comment]
This is working as expected, as `protoc-gen-go` is generating:
* a Go struct called `Outer_Inner` for the `underscore.Outer.Inner` message.
* a Go struct called `Outer_Inner_` as the wrapper type to represent the `underscore.Outer.inner` oneof field.

They obviously cannot be the same name due a namespace conflict.

The rules for how `protoc-gen-go` avoids namespace conflicts are obscure and grew organically over the years. Unfortunately, we also cannot change them without breaking many existing usages.

**Comment by jmalloc** [comment]
Oops, my apologies! Thank you for pointing that out :)
