### ISSUE TITLE
What's the real differences between github.com/golang/protobuf and google.golang.com/protocolbuffers/protobuf-go?

### ISSUE THREAD

**Issue by hitzhangjie** [golang/protobuf#1305]
I have several questions:
- what's the differences between the two repos? will I benefit from it?
- how to migrate from this repo to google.golang.com/prototocolbuffers/protobuf-go? do we have a guide?
  ps: really hard to remember and type.
- which version of protoc, protoc-gen-go should I use?

I'm a little confused about this.

I see the README says, the repo github.com/golang/protobuf is implemented by google.golang.com/protoco...../protobuf-go, then do we need to explicitly change the import path from github.com/golang/protobuf to google.golang.com/protoco..../protobuf-go?

**Comment by neild** [comment]
I have not heard of `google.golang.com/protocolbuffers/protobuf-go`. Are you thinking of `google.golang.org/protobuf`? If so, see this FAQ entry:

**Comment by neild** [comment]
I have not heard of `google.golang.com/protocolbuffers/protobuf-go`. Are you thinking of `google.golang.org/protobuf`? If so, see:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#modules

There is also a mirror of `google.golang.org/protobuf` at https://github.com/protocolbuffers/protobuf-go. You may safely ignore this mirror; the source of truth for the code is https://go.googlesource.com/protobuf and the import path is `"google.golang.org/protobuf"`.

**Comment by hitzhangjie** [comment]
@neild Thank you.
