### ISSUE TITLE
Need an advice on how to check if a struct is a right proto.Message

### ISSUE THREAD

**Issue by sirkon** [golang/protobuf#1308]
Hi!

We have some (strange) structs that implement `proto.Message` interface while not being a real `proto.Message`.

Is there the WAY™®© to check if a value is a real `proto.Message`? I did this is and it works in cases I tried it, just want to be sure if there are best practices on the issue.

```go
func getProtoMessage(msg interface{}) (proto.Message, bool) {
	v, ok := msg.(proto.Message)
	if !ok {
		return nil, false
	}

	var ext proto.ExtensionDesc
	if _, err := proto.GetExtension(v, &ext); err != nil {
		return nil, false
	}

	return v, true
}

```

**Comment by neild** [comment]
> Is there the WAY™®© to check if a value is a real proto.Message?

The simple answer is: No.

I strongly recommend against creating types that pretend to be something they are not.

**Comment by dsnet** [comment]
Closing as inactionable. We try to keep this issue tracker about actionable issue. For questions regarding usage, it is better to ask on Slack or someone other means where you can more readily get immediate help. Consider joining the #protobuf channel or the Gophers slack workspace: https://gophers.slack.com/messages/general/
