### ISSUE TITLE
Any known issues with Unmarshal and small messages (in wire format)?

### ISSUE THREAD

**Issue by ryanleesmith** [golang/protobuf#1309]
I have what might be a bit of a wonky setup, but it's working generally well:
* Small lib written in Go for interfacing with grpcurl plugin, just exports a few methods
* All the method signatures take in a `request []byte` parameter, which is meant to be a Proto message in binary wire format
* All the methods start with unmarshalling via `if err := proto.Unmarshal(request, {insert Proto message class}); err != nil {...`
* This is then built with the `c-archive` option, and the corresponding .h and .a output files are referenced in a SwiftUI project
* The aforementioned Proto schema I use is compiled for both Go and Swift, so I have generated classes for Swift here as well
* The Go/C code that ultimately gets generated for Swift basically requires me to pass in a GoSlice for the []byte param

So taking a very simple message example such as:
`message Request {
    string host = 1;
}`

The Swift code for building an instance of this request and then calling my lib would look something like:
```
let request = Request.with {
    $0.host = host
}
var slice: GoSlice?
var data = try! request.serializedData()
let length = Int32(data.count)

data.withUnsafeMutableBytes { (rawBufferPtr: UnsafeMutableRawBufferPointer) in
    if let rawPtr = rawBufferPtr.baseAddress {
        slice = grpc.GoSlice(data: rawPtr, len: grpc.GoInt(length), cap: grpc.GoInt(length))
    }
}
return lib.sendRequest(slice!)
```

This all works perfectly fine...as long as the request payload is big enough. In this case, host is the only field, and it requires a min of 13 characters it seems. The actual size in bytes is n+2, so if host == "1", `length` will be 3 (I assume a byte for the field number and one other I'm unsure of). It seems that length must == 15 bytes before it "works". Anything smaller and I get `proto: invalid field number`

One thing I did notice is that if I just print out the []byte var on Go side, I'll get something like `[0 139 254]` if host == "1". I noticed that if the first elem is 0, it doesn't work. Once I hit 13+ chars, the first elem switches to "10" and it works (this test was not exhaustive, it's just one example).

I really don't have anything to pad the request with, so I'm wondering if I'm missing something obvious here to resolve it without hacking.

**Comment by ryanleesmith** [comment]
FWIW, this is reproducible for a message with two fields, same symptoms: if the total size is < 15 bytes, it fails.

**Comment by neild** [comment]
There are no valid proto wire encodings that start with a 0 byte.

I'm not familiar with Swift's protobuf support and don't know what might be going wrong on that side, but [0, 139, 254] is not valid protobuf wire format. I suspect the bytes you're seeing for longer messages are wrong as well; have you confirmed that they're decoding to the message you expected?

**Comment by dsnet** [comment]
The data being passed to Go looks corrupted and/or is not the protobuf wire format.

The [`protopack`](https://pkg.go.dev/google.golang.org/protobuf/testing/protopack) package provides the ability to parse the protobuf wire format.

In this example, we see it [parses [0, 139, 254] as](https://play.golang.org/p/2Rtrup9s6rO):
```
Message{
	Tag{0, Varint},
	Raw("\x8b\xfe"),
}
```

The presence of a `Raw` token means that `protopack` was unable to interpret those bytes and just shoved them in at the end. Also, as Damien noted, a tag of zero is invalid since field numbers must be positive.

**Comment by ryanleesmith** [comment]
Yea, I thought the 0 was telling, although some other examples result in data such as "208, 58, 252, 3, 0, 112, 0, 0, 48, 238, 171", so I won't fixate on that exactly (the code snippet helps visualize it, though, thanks).

As far as longer messages go...I wasn't seeing it on that end of the spectrum. I tried up to 1572929 bytes and it was still working fine. Regarding Swift support, I'm using https://github.com/apple/swift-protobuf and according to the documentation:
```
Efficient binary serialization: The .serializedData() method returns a Data with a compact binary form of your data.
You can deserialize the data using the init(serializedData:) initializer.
```

That is the method I'm using to get the supposed binary format. I could not find a way to get this to work using the JSON/UTF-8 format. Admittedly, the code for taking the Data object and transforming into a GoSlice was the result of many hours of searching and piecing together a solution. I'm by no means comfortable in this space, I only had two requirements to work with:
* Apple's protobuf plugin returns a Data object
* The generated GoSlice class takes in an UnsafeMutableRawPointer?

From there I just found a way to create an instance of UnsafeMutableRawPointer from an instance of Data. Given that it worked, I didn't think anything more of it until I introduced a smaller message. I suppose at this point the `data.withUnsafeMutableBytes...` code might be suspect.

I do appreciate the responses, though.

**Comment by ryanleesmith** [comment]
Taking your playground example, I did the reverse and built a small message and printed what Swift _should_ be coming up with as well: [https://play.golang.org](https://play.golang.org/p/mJkU1wEIP0j)

Playground prints out: [10 1 49]
Swift (using my Proto message that just has one string field, numbered "1", with a value of "1"), prints out [0 59 202]

**Comment by neild** [comment]
If you haven't already, you should probably check what the data is on the Swift side before passing it to Go. I'm not very familiar with Swift, but the use of `UnsafeMutableRawBufferPointer` looks like it could easily result in the data being reclaimed and reallocated by the Swift garbage collector before you're done with it.

**Comment by ryanleesmith** [comment]
Thanks - will spend more time on that side. The specificity of this is what threw me off (it's consistently broken under 15 bytes, but not over). I was thinking the "Mutable" part was also a bit alarming - will see if I can use the immutable variants.

**Comment by ryanleesmith** [comment]
Okay, the reallocated/GC comment led me down a path to piecing together the following code:
```
private func getRequestSlice(_ data: Data) -> GoSlice {
        let bits = data.map { UInt8(String(format: "%02x", $0), radix: 16) }
        let count = bits.count
        let stride = MemoryLayout<UInt8>.stride
        let alignment = MemoryLayout<UInt8>.alignment
        let byteCount = stride * count
        let pointer = UnsafeMutableRawPointer.allocate(byteCount: byteCount, alignment: alignment)
        defer {
            pointer.deallocate()
        }
        bits.enumerated().forEach { idx, bit in
            pointer.storeBytes(of: bit!, toByteOffset: idx, as: UInt8.self)
        }
        return grpc.GoSlice(data: pointer, len: grpc.GoInt(count), cap: grpc.GoInt(count))
    }
```

Where the input data is the serialized proto message (as provided by swift-protobuf). Yes...I'm basically building it out by hand. There should be and probably is a one or two liner for doing this, but I cannot for the life of me find it.

**Comment by ryanleesmith** [comment]
As expected, there is a two liner variant (ran into the issue again with a seemingly random payload of 240 bytes). I have since swapped with the following:
```
private func getRequestSlice(_ data: Data) -> GoSlice {
        let bits = data.map { UInt8(String(format: "%02x", $0), radix: 16)! }
        let count = bits.count
        let pointer = UnsafeMutablePointer<UInt8>.allocate(capacity: count)
        pointer.initialize(from: bits, count: count)
        return grpc.GoSlice(data: pointer, len: grpc.GoInt(count), cap: grpc.GoInt(count))
    }
```
In any case, I'll close this since it's not an issue with this plugin. Thanks again for the tips.
