### ISSUE TITLE
Is it possible to keep bytes for unknown fields by marshaling and unmarshaling?

### ISSUE THREAD

**Issue by blanet** [golang/protobuf#1311]
Hello everyone!

If we have some **on-wire** formatted bytes of a protobuf message and we already know the referenced struct(of type `proto.Message`), but our struct missed references to some numbered fields.

We can use unmarshal  and get `proto.Message` from the bytes, but if we marshal the struct again, the bytes of unknown fields would be lost.

In my situation I  wanna change some fields of the proto message and keep the rest unchanged, is it possible by doing some extra job before unmarshaling and marshaling?

**Comment by dsnet** [comment]
Hi, whether unknown fields is preserved is dependent on whether the message struct has Go struct field to contain the unknown fields. All structs generated by `protoc-gen-go` at at least v1.1.x (from April, 2018) and latter support unknown fields.

If they are not being preserved, can you provide a reproduction showing the behavior?

**Comment by blanet** [comment]
Thanks for your quick response. In fact I am worrying about the compatibility for proto message version changes.

If we have some proto messages like this:
```protobuf
message DemoMsgV1 {
  string name = 1;
  int32 age = 2;
}

message DemoMsgV2 {
  string name = 1;
  string address = 3;
}
```

The go types(compiled using `protoc@3.12.4` and `protoc-gen-go@v1.3.3`) will be
```golang
type DemoMsgV1 struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

type DemoMsgV2 struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}
```

I made some experiments and see that the bytes marshaled is indeed the same!
```golang
demoMsgV1 := &example.DemoMsgV1{Name: "name", Age:  100,}
bytesV1, _ := proto.Marshal(demoMsgV1)

demoMsgV2 := &example.DemoMsgV2{}
_ = proto.Unmarshal(bytesV1, demoMsgV2)
bytesV2, _ := proto.Marshal(demoMsgV2)
```

So it seems that my worry was unwarranted and `XXX_unrecognized` is making the magic. Is this compatibility guaranteed for more complex proto messages(I mean fields for `oneof`, embedded types etc)?

**Comment by dsnet** [comment]
Unknown field preservation is a first-class feature of the protobuf wire format. It should work as expected so long as the field number for any removed fields is not re-used. For example, in DemoMsgV2, it seems that the `age` field was removed and the `address` field was added. Since the field removed was number 2, and the field added is number 3, there is no conflict. However, if the newly added `address` field was also number 2, then unknown field preservation will not work as expected.

If you aren't already, you can use the [`reserved` feature](https://developers.google.com/protocol-buffers/docs/proto3#reserved) to ensure that the field numbers for removed fields are not accidentally re-used.

**Comment by dsnet** [comment]
Also, the generated API guarantees unknown field preservation, does not guarantee exactly how that is implemented. Starting with v1.4 and above, we no longer generate a publicly visible `XXX_unrecognized` Go struct field, but rather generate an internal field. The same unknown field preservation behavior is still there though for marshaling and unmarshaling.

**Comment by blanet** [comment]
Thanks again, now I have a deeper understanding of protobuf, great job!
