### ISSUE TITLE
Marhal/Unmarshal of map with key but no value does not work as expected

### ISSUE THREAD

**Issue by chris-rock** [golang/protobuf#1312]
**What version of protobuf and what language are you using?**
Version: (e.g., `v1.1.0`, `89a0c16f`, etc)

v1.26.0

**What did you do?**

I created a message that contains a map with another message

```proto
syntax = "proto3";

package prototest;
option go_package = "prototest";

message Container {
  string a = 1;
  map<string,Content> b = 2;
}

message Content {
  string a = 1;
  string b = 2;
}
```

Then I create a new object

```
cj := &Container{
  A: "1",
  B: map[string]*Content{"1": nil},
}
```

I expect that marshal/unmarshal generates equal objects.

```golang
func TestSimpleMarshalUnmarshal(t *testing.T) {
	cj := &Container{
		A: "1",
		B: map[string]*Content{"1": nil},
	}
	assert.Nil(t, cj.B["1"])

	// marshal
	reqBodyBytes, err := proto.Marshal(cj)
	require.NoError(t, err)

	// unmarshal
	out := &Container{}
	err = proto.Unmarshal(reqBodyBytes, out)
	require.NoError(t, err)

	assert.Nil(t, out.B["1"]) // This will fail
}
```

**What did you expect to see?**

I expect that this object is identical after marshal/unmarshal.

**What did you see instead?**

The unmarshaled object contains an empty object in the map.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment?**

**Comment by neild** [comment]
The protobuf data model has no concept of a `nil` map value. (The wire encoding does permit representing this concept, but the text encoding does not and no other language's protobuf API provides a way to distinguish between empty and missing map values.)

Since there is no concept of a `nil` map value in the protobuf data model, the Go protobuf API treats a `nil` value as an empty message. We also treat a `nil` value in a slice representing a repeated message field as an empty message.

**Comment by chris-rock** [comment]
Understood. I'd like to mention that this is different from the v1 implementation though.

**Comment by dsnet** [comment]
Understood. The change was made deliberately since the v1 behavior is incorrect. See https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.20.0#v1.20-nil-values for details.

**Comment by chris-rock** [comment]
I was thinking about this a bit more. The most "annoying" part about this behavior is that `proto.Marshal` eats  data that is not properly covered/specified in protobuf spec. Personally, I would prefer if the go marshaller would be more strict (maybe via an optional "Strict" option) to fail properly. This would enable users of this implementation to see issues way more early, especially when they are migrating from v1 to v2.

**Comment by kumari-jyoti** [comment]
I have a requirement where I need to proto.Unmarshal a map<string, ABVariantEntries> where ABVariantEntries is a struct
I am trying below approaches but none of them work. Kindly let me know what would be the correct way
```
styleVariants := make(map[string]*style_fetch.ABVariantEntries)
proto.Unmarshal([]byte(value), &styleVariants)// gives `cannot use &styleVariants (value of type *map[string]*style_fetch.ABVariantEntries) as protoiface.MessageV1 value in argument to proto.Unmarshal: *map[string]*style_fetch.ABVariantEntries does not implement protoiface.MessageV1 `
```
```
styleVariants := map[string]*style_fetch.ABVariantEntries{}
proto.Unmarshal([]byte(value), &styleVariants)// gives `cannot use &styleVariants (value of type *map[string]*style_fetch.ABVariantEntries) as protoiface.MessageV1 value in argument to proto.Unmarshal: *map[string]*style_fetch.ABVariantEntries does not implement protoiface.MessageV1`
```

I had to instead define another strict on top of below proto, and use struct StyleVariant
```
message StyleVariant {
  map<string, ABVariantEntries> style_variants = 1;
}
```
```
styleVariants := &style_fetch.StyleVariant{}
proto.Unmarshal([]byte(value), styleVariants)
```
Is there a way to directly use `map<string, ABVariantEntries>` in proto.Unmarshal and not define another struct on top of it? 
Any help is appreciated

**Comment by puellanivis** [comment]
This seems like something that should have been posted to a new issue, rather than a closed one.

There is no way to marshal/unmarshal individual fields. Protobuf is designed to marshal/unmarshal protobuf `Message`s only.
