### ISSUE TITLE
Why are repeated fields only allowed at the last position of a paths string?

### ISSUE THREAD

**Issue by nnutter** [golang/protobuf#1315]
https://github.com/golang/protobuf/issues/1179 broke us and I don't understand why this constraint exists.  It noted,

> [field_mask.proto](https://github.com/protocolbuffers/protobuf/blob/9b0fa3e7fbaf3463c3afa1c9ab111682108eeadb/src/google/protobuf/field_mask.proto) mentions that ...
> 
> ```protobuf
> // Field masks are used to specify a subset of fields that should be
> // returned by a get operation or modified by an update operation.
> 
> ...
> 
> // # Field Masks in Projections
> // ...
> // A repeated field is not allowed except at the last position of a
> // paths string.
> 
> ...
> 
> // # Field Masks in Update Operations
> // ...
> // Note that a repeated field is only allowed in the last position of a `paths` string.
> ```
> 
> Given those statements, I think FieldMask.IsValid should return false if a path contains a repeated field that is not in the last position.

Given the example in https://github.com/golang/protobuf/issues/1179 why is `nests.s` not a reasonable path?  Imagine extending `Nested` with a second field.  It seems reasonable to say you want one of those fields but not both.

**Comment by cybrcodr** [comment]
You'll need to bring this up on the main Protocol Buffers site at https://github.com/protocolbuffers/protobuf/issues as the Go implementation is simply following the guidelines mentioned in the proto definition.

For a repeated field to not be in the last position, I think they may need to also define a way to reference a specific item (or items) in the repeated field, which they currently don't.  It's possible that it implies that a subfield applies to all items, but again I prefer not to speculate as there is no specification for this.

**Comment by dsnet** [comment]
Hi @nnutter, I'm sorry to hear that you were broken by the change. The purpose of this project is to comply with the semantics defined by the main protocol buffer project. Since the documentation of `field_mask.proto` explicitly calls out rejecting repeated fields not in the last position, it seems we're compelled to comply. @cybrcodr is right that the right place to bring this up is at https://github.com/protocolbuffers/protobuf/issues if you think the semantics should be loosened.

**Comment by nnutter** [comment]
Thanks @dsnet and @cybrcodr.  I've created a feature request over there, https://github.com/protocolbuffers/protobuf/issues/8547.
