### ISSUE TITLE
Enable golint on generated protobuf files.

### ISSUE THREAD

**Issue by gabelev** [golang/protobuf#132]
The generated protobuf files (*.pb.go) fail golint. These files could be generated so that they can pass golint.

**Comment by dsymonds** [comment]
Don't run golint on generated .pb.go files. They're never going to meet the standard of human written code.

**Comment by zellyn** [comment]
If it's not that hard to make them pass, after gofmt/goimports, it's probably not a bad idea to make them pass. Not that people _should_ be using `golint` as a git commit hook, but they're going to…

**Comment by dsymonds** [comment]
It would be hard.

**Comment by gabelev** [comment]
Do you think it would be so hard? I definitely think it would be worth the effort. Do you not want to encourage usage of golint as a hook?

**Comment by zellyn** [comment]
No. It's somewhat documented [here](https://github.com/golang/lint), and strongly reinforced inside Google that golint should not be run as a hook.

**Comment by gabelev** [comment]
That makes sense. If golint is checking for for "mechanically checkable items" may as well make the mechanically generated code at least meet those items as well. ?

**Comment by zellyn** [comment]
Not that my opinion carries any weight here, but I agree with @dsymonds on this one. I probably have a higher desire than most to make the generated output pretty (eg. I may try to send a PR that stops names like context, context1, context2 being generated for the same import), but it would probably never pass `golint`, nor should it. As an example, `foo_id` will get turned into `FooId`, which golint won't like.

**Comment by gabelev** [comment]
Well I would definitely encourage you to do that PR. Regarding generated pretty code, it reminded of me of this: 
https://blog.golang.org/generate
But yes, I think it could be prettier. Why not?

I see what you both are saying, and although my opinion also matters not here, I can get on board with that.
