### ISSUE TITLE
when i install the protobuf my goland was showing  waring

### ISSUE THREAD

**Issue by wwwworkhard** [golang/protobuf#1321]
**What version of protobuf and what language are you using?**
Version: (e.g., `v1.1.0`, `89a0c16f`, etc)

D:\GOPATH\src\mypro\message>protoc --version
libprotoc 3.17.0
golang 1.6

What causes it?
What should I do about it？
Const initializer 'protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)' is not a constant

![image](https://user-images.githubusercontent.com/12581016/118399902-f4e39200-b691-11eb-814e-17d73a408548.png)

**What did you do?**
If possible, provide a recipe for reproducing the error.
A complete runnable program is good with `.proto` and `.go` source code.

**What did you expect to see?**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment?**

**Comment by puellanivis** [comment]
🤔 This is werid. [`protoimpl.EnforceVersion`](https://pkg.go.dev/google.golang.org/protobuf/runtime/protoimpl#EnforceVersion) is a type and both `protoimpl.MinVersion` and `protoimpl.MaxVersion` are declared in a `const ( … )` grouping. So, these expressions should be a constant.

What is your `go.mod`? Perhaps you are picking up some odd version, or something else that is confusing your goland?

**Comment by dsnet** [comment]
This error suggests that somehow the wrong version of the `google.golang.org/protobuf` is being used by your development environment.

**Comment by dsnet** [comment]
Closing as inactionable. We try to keep this issue tracker about actionable issue. For questions regarding usage, it is better to ask on Slack or on some other means where you can more readily get immediate help. Consider joining the #protobuf channel or the Gophers slack workspace: https://gophers.slack.com/messages/general/
