### ISSUE TITLE
encoding/protojson: Is there a way to override marshalling/unmarshalling logic for specific messages?

### ISSUE THREAD

**Issue by svelez** [golang/protobuf#1322]
As was possible in jsonpb?
https://github.com/golang/protobuf/blob/ae97035608a719c7a1c1c41bed0ae0744bdb0c6f/jsonpb/encode.go#L53-L63

The deprecation comment says to use protobuf reflection, but assuming that I do discover how to completely implement my own message without relying on protoc, I don't see how I can use reflection to have the json structure be different from the proto message structure (as is the case with several well known types)

I am assuming that the comment `The JSON marshaling must follow the proto to JSON specification:` implies that serialization to json should not utilize arbitrary structure, and that the ability to do this as been dropped from the current library, but I would just like to make sure.

**Comment by neild** [comment]
There is no way to override the JSON representation for specific messages in `encoding/protojson`.

The purpose of this package is to (de)serialize messages in the standard protobuf JSON encoding, which is supported by many different implementations in many different languages. Custom encodings for specific messages would prevent cross-implementation interoperability.

**Comment by svelez** [comment]
K.  That's what I suspected.  Thanks.
