### ISSUE TITLE
has a name conflict over pb.Response ?

### ISSUE THREAD

**Issue by benyu** [golang/protobuf#1325]
Has two rpc services in app

app
----/b
-----/b.proto
----/c
-----/c.proto

in files a.proto and b.proto with define
Response {
  fields ...
}

there will throw conflicts errors while includes a,b services ?
```
panic: proto: file "a.proto" has a name conflict over pb.Response
	previously from: "github.com/x/app/a/service/pb"
	currently from:  "github.com/x/app/b/service/pb"
```

**Comment by dsnet** [comment]
This is expected behavior. Please see https://developers.google.com/protocol-buffers/docs/reference/go/faq#fix-namespace-conflict

**Comment by dsnet** [comment]
Closing as inactionable. We try to keep this issue tracker about actionable issue. For questions regarding usage, it is better to ask on Slack or on some other means where you can more readily get immediate help. Consider joining the #protobuf channel or the Gophers slack workspace: https://gophers.slack.com/messages/general/
