### ISSUE TITLE
docs reference nonexistent flag

### ISSUE THREAD

**Issue by kevinburkemeter** [golang/protobuf#1328]
This page: https://developers.google.com/protocol-buffers/docs/reference/go-generated

makes several references to a "go_opt" flag, which as far as I can tell, does not exist with the latest installed protoc version.

**Comment by kevinburkemeter** [comment]
Thanks for the help - I ended up getting it sorted out here, https://github.com/ttacon/libphonenumber/pull/107

**Comment by LordMoMA** [comment]
Sorry, may I know why you fix "Unknown flag: --go_opt"? I tried almost every method available but in vain.
