### ISSUE TITLE
protoc-gen-go: support using proto field names as JSON names

### ISSUE THREAD

**Issue by joeblubaugh** [golang/protobuf#1329]
**Is your feature request related to a problem? Please describe.**
protoc-gen-go turns this message:
```
message A {
  repeated integer msg_numbers = 1;
}
```

into (roughly, details omitted)

```
type A struct {
  msgNumbers []int `json:"msgNumbers,omitempty"`
}
```

the proto3 [json encoding spec](https://developers.google.com/protocol-buffers/docs/proto3#json_options) states:
> Use proto field name instead of lowerCamelCase name: By default proto3 JSON printer should convert the field name to lowerCamelCase and use that as the JSON name. An implementation may provide an option to use proto field name as the JSON name instead. Proto3 JSON parsers are required to accept both the converted lowerCamelCase name and the proto field name.

snake-case naming is very commonly used in JSON, while lowerCamelCase feels "unnatural" to many developers.

**Describe the solution you'd like**
Support a protoc-gen-go option that will use the exact field name as the JSON serialization name. Suppose it's:
`protoc --go_out=./ --go_opt=json-names:proto-fields ./myfile.proto`

**Describe alternatives you've considered**
On a message-by-message basis, we can do

```
message A {
  repeated integer msg_numbers = 1 [json_name = "msg_numbers"];
}
```
but this needs to be added to each field, in each message.

**Comment by neild** [comment]
Using proto field names rather than lowerCamelCase is enabled by setting the `(protojson.MarshalOptions).UseProtoNames` field:
https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson#MarshalOptions

We strongly recommend using the `protojson` package to marshal protobuf messages to JSON. The `json` field tags on generated struct fields predate the existence of a specified common protobuf JSON encoding, and marshaling a message with the `encoding/json` package will produce incorrect results under some circumstances. The tags are still generated for backwards compatibility, but new uses should use `protojson`.

**Comment by joeblubaugh** [comment]
I created this issue specifically on github.com/golang/protobuf because that's the API that my team uses. We use the `jsonpb` package provided by this library to marshal our protobufs to JSON so that we can use the `json_name` standard proto option - that's how we currently solve this problem on a case-by-case basis.

It looks like the golang/protobuf equivalent to what you've said is `jsonpb.Marshaler{OrigName: true}`. So that's one way of solving the problem. Thank you for the pointer!

I'm asking for a compile-time option because having to set the options in each marshaler wherever they're used is significantly more finicky than generating code that always does the right thing when it's run through jsonpb.

**Comment by neild** [comment]
I don't think a language-specific compile-time option makes sense here. The default field name encoding seems like something that is cross-language, and any option like this should also be cross-language. You could file a general feature request at: https://github.com/protocolbuffers/protobuf/issues

**Comment by joeblubaugh** [comment]
Thanks @neild  - feel free to resolve this issue.

**Comment by kedacoinfloww** [comment]
```
message PayoutResponse {
  int32 code = 1;
  string message = 2;
  int64 payout_id = 3;
  string bank_transaction_id = 4 ;
}
```

protoc out

```
type PayoutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code              int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message           string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PayoutId          int64  `protobuf:"varint,3,opt,name=payout_id,json=payoutId,proto3" json:"payout_id,omitempty"`                          
	BankTransactionId string `protobuf:"bytes,4,opt,name=bank_transaction_id,json=bankTransactionId,proto3" json:"bank_transaction_id,omitempty"`
}
```

`json=payoutId` in `protobuf:"varint,3,opt,name=payout_id,json=payoutId,proto3"`

I really don't understand why **camelCase** is used here

**Comment by puellanivis** [comment]
It is `camelCase` because the protobuf standard establishes it: https://protobuf.dev/programming-guides/proto3/#json “Message field names are mapped to lowerCamelCase…”

If you don’t want `camelCase`, you can use the `protojson.MarshalOption{ UseProtoNames: true }`

**Comment by jroper** [comment]
What I'd like to know is why the name passed to the `json` tag is snake case? Shouldn't that be camel case? It's really confusing, leads to bugs, and just, wrong. You mentioned it's for backwards compatibility, but shouldn't there be migration path to make it right? The "correct" way of encoding as JSON has existed for many years now, if people are still using `encoding/json`, that's on them.

**Comment by puellanivis** [comment]
> Parsers accept both the lowerCamelCase name (or the one specified by the json_name option) and the original proto field name.

While it is “wrong” it’s not incompatibly wrong (using `encoding/json` is broken at a far deeper structual way). And the only thing using this value is code that would be using `encoding/json, as the `protojson` and `jsonpb` both do not consult this value at all in anyway.

So, “fixing” it to be `camelCase` would solely and exclusively break code using `encoding/json`… which means that there’s really no reason to “fix” it at all.

**Comment by jroper** [comment]
Then why not remove them entirely? If I open the generated source files, and see that there are `encoding/json` tags, would I be wrong to assume that therefore using `encoding/json` is a valid way to encode as JSON according to the protobuf spec? Or should I somehow know that I'm meant to search and find this particular GitHub issue, read the explanations here, to know that actually, that's not the way to do it?

It's the confusion that having these there that I have an issue with. It leads people to do the wrong thing.

**Comment by puellanivis** [comment]
Because existing code may already be using it, and we don’t want to break that code. It’s not _wrong_ it’s just not compliant with the standards that were later setup by the protobuf team.

There is a wide amount of thing in Go, which exist only because we accidentally made the wrong choice initially, and it’s now too late to fix them. The very conservative Go v1 compat guarantee is largely the reason.
