### ISSUE TITLE
why protobuf costs so much time?

### ISSUE THREAD

**Issue by smartczy** [golang/protobuf#133]
Hello, everyone.

I use protocol buffers to encode and decode a string. At first, the string is short.
```go
type Info struct {
	Id string
	Ts int64
	Vs map[string]float64
}

s := Info{Id: "if_192.168.91.22_T1_0_52", Ts: 1452476100, Vs: map[string]float64{"crcerr": 0, "inbps": 0, "inerr": 0, "inpps": 0, "outbps": 0, "outerr": 0, "outpps": 0}}
```
My test codes are as follows:
```go
//pb_benchmark_test.go
package pb

import (
	"testing"
)

func Benchmark_Marshal(t *testing.B) {
	t.N = 10000000
	for i := 0; i < t.N; i++ {
		pb_marshal()
	}
}

func Benchmark_Unmarshal(t *testing.B) {
	t.N = 10000000
	raw_data := pb_marshal()
	for i := 0; i < t.N; i++ {
		pb_unmarshal(raw_data)
	}
}
```
The test result  is
```
testing: warning: no tests to run
PASS
Benchmark_Marshal-8  	10000000	      5813 ns/op
Benchmark_Unmarshal-8	10000000	      3041 ns/op
ok  	_/home/benchmark/protobuf	8.86s
```

Then change the length of the string.
```go
s := Info{Id: "if_192.168.91.22_T1_0_52", Ts: 1452476100, Vs: map[string]float64{"crcerr": 123456789, "inbps": 123456789, "inerr": 123456789, "inpps": 123456789, "outbps": 123456789, "outerr": 123456789, "outpps": 123456789}}
```
There is no changes of test code and the result is:
```
testing: warning: no tests to run
PASS
Benchmark_Marshal-8  	10000000	      5801 ns/op
Benchmark_Unmarshal-8	10000000	      3035 ns/op
ok  	_/home/benchmark/protobuf	88.384s
```

As we can see from these two results,  the loop ran 1000000 times at the speed of about 5800ns per loop when encode the string and 3040ns per loop when decode the string. But the total time of the whole progress is 8.8s in first picture while 88s in second.  It increases almost 10 times. 

When we test in this way:
```go
//pb.go
func main() {
	for i := 0; i < 1000000; i++ {
		pb_marshal()
	}
	res := pb_marshal()
	for i := 0; i < 1000000; i++ {
		pb_unmarshal(res)
	}
}
```
and execute 
```
time go run pb.go
```
and then we get 
```
[protobuf]$ time go run pb.go

real	0m9.986s
user	0m13.018s
sys	0m0.765s
```

These result looks right.

Why the results are so difference? Why the second situation cost so much time?

Thanks for your help.

**Comment by dsymonds** [comment]
I'm not sure, but you aren't meant to change `t.N` inside your benchmark function. You should only be reading it and doing that many iterations.

This isn't the best place to discuss performance issues. Try the golang-nuts mailing list.
