### ISSUE TITLE
How to get raw bytes of a nested message?

### ISSUE THREAD

**Issue by markandpathak** [golang/protobuf#1331]
I am new to protobuf. Protobuf is a fantastic package. But, I could not find a method to fit my scenario. Any guidance is appreciated.
Consider this message:
```
syntax = "proto3";

package somepackage;

message parent {
    mainMsg data = 1;
    bytes signature = 2;
}

message mainMsg {
   int id = 1;
   int somedata = 2;
}
```
What I want to achieve is `mainMsg` should contain actual data required by the application. `parent` is sent to the application which includes `mainMsg` along with calculated signature of the `mainMsg` in bytes format so that receiving application can verify integrity of the `mainMsg`.  

On receiver side I want to calculate signature from raw bytes of  `mainMsg`. Is there any way to get raw bytes of nested message apart from unmarshaling the `parent` and marshaling only `mainMsg` struct again to obtain bytes? I referred to package documentation but could not find any function which directly provides this.

**Comment by cybrcodr** [comment]
There is no API to get the serialized bytes of a field given serialized bytes of a message.  To get serialized bytes of a message field from given serialized bytes of a message, unmarshal the message and marshal the message field as you've already pointed out.

**However**, for what you want to achieve, beware that generating a signature based off serialized bytes of a proto Message is not advisable -- https://developers.google.com/protocol-buffers/docs/encoding#implications.

**Comment by markandpathak** [comment]
Thank you very much for pointing out possible implications. I will look into it to make sure things work out perfectly.
