### ISSUE TITLE
protoc-gen-go: Silently won't generate code if no service is defined in the proto file

### ISSUE THREAD

**Issue by sfro** [golang/protobuf#1334]
**What version of protobuf and what language are you using?**
Golang 1.16.5
protoc v3.17.3
protoc-gen-go v1.27.1
protoc-gen-go-grpc v1.1

**What did you do?**
Try to generate code with two different proto files:
test.proto:
```
syntax = "proto3";

package test;
option go_package = "./pb";

message TestMessage {
    string id = 1;
}
```

`protoc --proto_path=. --go-grpc_out=. test.proto`. <-- No files produced

test-with-service.proto
```
syntax = "proto3";

package test;
option go_package = "./pb";

message TestMessage {
    string id = 1;
}

service Test {
}
```
`protoc --proto_path=. --go-grpc_out=. test-with-service.proto` <-- pb/test-with-service_grpc.pb.go generated

**What did you expect to see?**
Code generated for both files.

**What did you see instead?**
Code was only generated for the file with a service defined. The command that failed gives no output, it just silently fails.
I am able to generate for both files with an older version of the plugin, but it's such an old version I can't print out the version:

```
protoc-gen-go --version
protoc-gen-go: unknown argument "--version" (this program should be run by protoc, not directly)
protoc-gen-go -version 
protoc-gen-go: unknown argument "-version" (this program should be run by protoc, not directly)
```

**Anything else we should know about your project / environment?**
I am trying to get this working with github actions, so protoc is installed with arduino/setup-protoc@v1. Then Go v1.16 is installed and this is run:
```
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
```

**Comment by sfro** [comment]
Installing the old protoc-gen-go works:
```
go install github.com/golang/protobuf/protoc-gen-go@v1.5.2
```

**Comment by neild** [comment]
You need to run both the Go plugin (`--go_out`) to generate type definitions and the Go-gRPC plugin (`--go-grpc_out`) to generate service definitions. For example:

```
protoc --go_out=. --go-grpc_out=. test.proto
```

See:
https://grpc.io/docs/languages/go/basics/#generating-client-and-server-code

(I'm not how clear on installing an older `protoc-gen-go` would help, since the command you give doesn't run it. If you only provide a `--go-grpc_out` flag, you only get service definitions.)
