### ISSUE TITLE
Can you please DEPRECATE this Github project?

### ISSUE THREAD

**Issue by frederikhors** [golang/protobuf#1335]
Can you please DEPRECATE this Github project?

Many people who are starting out with Go and Proto use this - wrongly.

Please.

**Comment by neild** [comment]
The github.com/golang/protobuf module is marked as deprecated (superseded by `"google.golang.org/protobuf"`):
https://github.com/golang/protobuf/blob/v1.5.2/go.mod#L1

Every package in this module is also marked as deprecated.

We still use this GitHub project's issue tracker for both modules, however.

**Comment by dsnet** [comment]
This is already documented in several places:
* https://github.com/golang/protobuf/blob/ae97035608a719c7a1c1c41bed0ae0744bdb0c6f/go.mod#L1
* https://github.com/golang/protobuf/blob/ae97035608a719c7a1c1c41bed0ae0744bdb0c6f/proto/proto.go#L12

What else do you suggest?

**Comment by frederikhors** [comment]
If you still use this issue tracker {
    forget it
} else {
    deprecate the project with Github settings option
}

**Comment by neild** [comment]
We do still use this issue tracker. (As documented here: https://github.com/protocolbuffers/protobuf-go#reporting-issues)
