### ISSUE TITLE
API/Documentation for Any Type?

### ISSUE THREAD

**Issue by psanford** [golang/protobuf#134]
Will there be additional work done to make using the Any type easier? Right now it is not clear exactly how you are supposed to use it from Go. 

If Any is complete and ready to use could we add some documentation showing how to use it?

**Comment by dsymonds** [comment]
Yes, it is far from complete. It's in progress. There will be more pieces in the `ptypes` package, as well as better support in the text formatter/parser and the `jsonpb` package.

**Comment by psanford** [comment]
Thanks.
