### ISSUE TITLE
Conversion from `protogen.Message` to `proto.Message`

### ISSUE THREAD

**Issue by thepabloaguilar** [golang/protobuf#1340]
Hello all, sorry if this question is duplicated but I didn't find other question that I could use to clarify my doubts

I'm writing a __protoc__ plugin to generate some contract tests, so, I need to check on _generating file time_ if the user provided the expected values with the right types, what I wish to do is:
```go
marshaledRequest, _ := json.Marshal(...)
err = protojson.Unmarshal(marshaledRequest, method.Input)  // `method` type is `*protogen.Method`
if err != nil { panic(err) }
```

But `method.Input` type is `protogen.Message` and `protojson.Unmarshal` needs `proto.Message` as second argument, the way I've found to make that works is using `dynamicpb`:
```go
methodInputMessage := dynamicpb.NewMessage(method.Input.Desc)
err = protojson.Unmarshal(marshaledRequest, methodInputMessage)
if err != nil { panic(err) }
```

I'd like to know if that way is the best way to do what I want!

**Comment by neild** [comment]
It sounds like @puellanivis answered this, but to expand a bit:

* [`descriptorpb.DescriptorProto`](https://pkg.go.dev/google.golang.org/protobuf/types/descriptorpb#DescriptorProto) describes a protobuf message type. A `DescriptorProto` is itself a protocol buffer, and `protoc` can produce these from a `.proto` file.
* [`protoreflect.MessageDescriptor`](https://pkg.go.dev/google.golang.org/protobuf/reflect/protoreflect#MessageDescriptor)  also describes a protobuf message type. This is a more convenient representation for Go programs than the raw `DescriptorProto`. The [`protodesc`](https://pkg.go.dev/google.golang.org/protobuf/reflect/protodesc) package can convert between a `DescriptorProto` and a `MessageDescriptor`.
* [`protogen.Message`](https://pkg.go.dev/google.golang.org/protobuf/compiler/protogen#Message) is a `MessageDescriptor` with some additional information that is useful for code generators.
* [`proto.Message`](https://pkg.go.dev/google.golang.org/protobuf/proto#Message) is an *instance* of a message. All the types above describe a *type* of message; `proto.Message` is an instantiation of that type.
* The [`dynamicpb`](https://pkg.go.dev/google.golang.org/protobuf/types/dynamicpb) package provides a way to take an arbitrary `protoreflect.MessageDescriptor` and create a `proto.Message`.

**Comment by thepabloaguilar** [comment]
Yeap, thanks @puellanivis and @neild!
