### ISSUE TITLE
How does one get the correct go module imports when using `import public` 

### ISSUE THREAD

**Issue by zachgersh** [golang/protobuf#1342]
Hey All,

Apologies if this label if the format of this question is incorrect:

I recently stumbled upon `import public` and it allowed me to easily refactor a bunch of my proto types in go. I had one small problem that I couldn't quite figure out, in the generated code my new package import ended up coming out incorrect (it almost looked like it wasn't module aware). 

Here's an example

```
proto/
├── example
│   └── v1
│       └── new.proto
└── shared.proto
```

For this example lets pretend this is in the repo `github.com/test/service`.

Now, I would have expected for the code generated off of the `shared.proto` with the correct `import public` statement
to have reference to the types in `new.proto` via an import like this:

```
import "github.com/test/service/proto/example/v1"
```

but what I got is this instead unresolvable module instead:

```
import "example/v1"
```

I could be doing something wrong here but would love to hear thoughts.

**Comment by neild** [comment]
This probably indicates that you're missing an `option go_package = "github.com/test/service/proto/example/v1";` in `new.proto`. The `go_package` option specifies the Go package associated with a `.proto` file.

Alternatively, you can specify the package on the command line with the `M` option.

See:
https://developers.google.com/protocol-buffers/docs/reference/go-generated#package

**Comment by zachgersh** [comment]
That's exactly it! Thank you.
