### ISSUE TITLE
Marshal struct with field  int K=0 ，the result  is  {"k":"0"}, but it supposed to be     {"k":0}

### ISSUE THREAD

**Issue by yangtao596739215** [golang/protobuf#1345]
**What version of protobuf and what language are you using?**
Version: (e.g., `v1.1.0`, `89a0c16f`, etc)

**What did you do?**
If possible, provide a recipe for reproducing the error.
A complete runnable program is good with `.proto` and `.go` source code.

**What did you expect to see?**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment?**

**Comment by yangtao596739215** [comment]
as the title

**Comment by dsnet** [comment]
Assuming you are using JSON serialization with a 64-bit integer field, this is working as intended.

Many JSON parsers cannot parse JSON numbers that do not fit within a IEEE-754 double-precision number, which is the case for all 64-bit numbers. As such, the [specification specifies that the output is a JSON string](https://developers.google.com/protocol-buffers/docs/proto3#json):
> JSON value will be a decimal string.
