### ISSUE TITLE
protobuf/encoding/protojson.Marshal outputs different comma spacing in between runs/on different 1.16.* versions

### ISSUE THREAD

**Issue by pigfrown** [golang/protobuf#1351]
**What version of protobuf and what language are you using?**

google.golang.org/protobuf v1.26.0
go 1.16.*
linux
 
**What did you do?**

Generated JSON from a protobuf message on go 1.16.6 and got different output strings depending on calling code. See https://github.com/pigfrown/protojsonissue/ for minimal example + output. The JSON strings sometimes have spaces after commas, sometimes they don't.

Although output is still valid JSON the different output breaks my unit tests when they are running on different machines/different versions of go. In particular tests pass on local machines but fail on github actions. 

**What did you expect to see?**

The same JSON output regardless of which patch version of go 1.16 is used.

The same JSON output regardless of the context in which protojson.Marshal is called.

**What did you see instead?**

Running the example (https://github.com/pigfrown/protojsonissue/) on different go version (1.16.6 and 1.16.7) produces different output. (spaces or no spaces after commas in generated JSON).

When running on 1.16.6: Modifying the example (https://github.com/pigfrown/protojsonissue/) to call protojson.Marshal twice instead of once produces different spacing in the output JSON, even though the input message is identical.

**Anything else we should know about your project / environment?**

Updating to 1.16.7 appears to have fixed the trivial example but the more complicated example in my unit tests still exhibits this behaviour.

**Comment by neild** [comment]
This is intended behavior. From [the FAQ](https://developers.google.com/protocol-buffers/docs/reference/go/faq#unstable-json):

>  **Why does the output of protojson keep changing?**
>
> We make no promises about the long-term stability of Go's implementation of the JSON format for protocol buffers. The specification only specifies what is valid JSON, but provides no specification for a canonical format for how a marshaler ought to exactly format a given message. To avoid giving the illusion that the output is stable, we deliberately introduce minor differences so that byte-for-byte comparisons are likely to fail.
>
> To gain some degree of output stability, we recommend running the output through a JSON formatter.
