### ISSUE TITLE
consider improving purego support by not requiring os.Executable

### ISSUE THREAD

**Issue by mvdan** [golang/protobuf#1354]
The library currently relies on `os.Executable` to get a deterministic random seed: https://github.com/protocolbuffers/protobuf-go/blob/5aec41b4809b9822a34e17acd06ae9ae9f41c13d/internal/detrand/rand.go#L42

I presume this is done so that the random seed changes if the software version or binary changes, so that software incorrectly relying on semi-random behavior will break while developing and testing with `go test`. And I also presume a completely random seed (such as the current Unix time) is avoided so that a specific binary or version of a program behaves the same today and tomorrow, preventing issues when reproducing bugs.

I also seem to understand that the Protobuf library attempts to support `purego` platforms; the tag is currently defined by https://github.com/golang/go/issues/23172#issuecomment-359569548, as far as I can tell.

Unfortunately, support for `js/wasm` does not work even with `purego` today; https://github.com/protocolbuffers/protobuf-go/blob/5aec41b4809b9822a34e17acd06ae9ae9f41c13d/internal/detrand/rand.go#L42 calls `os.Executable`, and that assumes the full executable is available as a file somewhere on the running environment. At least as of today, that's not true for wasm - it always errors: https://cs.opensource.google/go/go/+/refs/tags/go1.16.7:src/os/executable_procfs.go

TinyGo also lacks the API entirely: https://github.com/tinygo-org/tinygo/issues/1778. Arguably they should add it, but I imagine on `js/wasm` it would simply error, like Go's own one.

I think it would make sense to put that `binaryHash` function behind a `!purego` build tag, and have a `purego` implementation that allows for `os.Executable` to not exist or to always error. It could fall back to a fixed hash, or to hashing something else that is more likely to work on `purego` platforms like https://pkg.go.dev/runtime#Version or https://pkg.go.dev/runtime/debug#ReadBuildInfo.

**Comment by neild** [comment]
If `os.Executable` returns an error, everything should still work (albeit without randomness). The `detrand.binaryHash` just returns 0 if the call fails.

**Comment by mvdan** [comment]
You are absolutely right - I'm not sure how I missed that :) Tinygo currently fails to build, but that's just on them - they could easily add a stub that always errors, like Go's js/wasm port.
