### ISSUE TITLE
Due to google.protobuf.Timestamp and time.Time datatype mismatch not able to create cloudEvent conformant event

### ISSUE THREAD

**Issue by baleshk** [golang/protobuf#1355]
I am creating a proto file (and following cloudEvents standards).

```
syntax = "proto3";
option go_package = "/events";

import "google/protobuf/timestamp.proto";
import "google/protobuf/any.proto";

message Event {
    string specversion = 2;
    string type = 3;
    string source = 4;
    string id = 5;
    google.protobuf.Timestamp time = 6;
    google.protobuf.Any data = 7;
    map<string, CloudEventAttributeValue> attributes = 8;
    string datacontenttype = 9;
    string test = 10;
}
```
It works well between client and server. I also want to make sure that this object is totally conformant to cloudevents standard. To test this out I tried marshalling this object using json.marshal() and then unmarshal using json.unmarshal into a cloudEvent object. In this test deserialization is breaking due to time field datatype mismatch between proto object and cloudEvents.

```
bytes, _ := json.Marshal(ev)
fmt.Println(string(bytes))

e := cloudevents.NewEvent()
json.Unmarshal(bytes, &e)
```

But if I remove the time field, everything works well. Any idea what am I missing? Due to this limitation, I am not able to create an event in proto which follow cloudevent standards, please help.

**Comment by puellanivis** [comment]
Are you using `protojson` to marhsal and unmarshal JSON with protobufs?

**Comment by baleshk** [comment]
Super @puellanivis, this worked. I was wondering if this can be case in other languages as well where we have to use some special marshalling/un-marshalling techniques to use protobuf messages. Wouldn't it better if protobuf messages just worked without any special treatment?

**Comment by puellanivis** [comment]
I cannot speak to other languages, but it is a possibility.

Unfortunately, the `protojson` package was built because there are specific features of the proto3 JSON mapping that made implementing it with the `encoding/json` package infeasible.

**Comment by cybrcodr** [comment]
The protobuf guide dictates specific JSON transformations -- https://developers.google.com/protocol-buffers/docs/proto3#json.  It also specifies special ones for Well-Known Types.  Other supported languages do have their own JSON serialization library as well, e.g.

C++: https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.util.json_util
Java: https://developers.google.com/protocol-buffers/docs/reference/java
