### ISSUE TITLE
`proto.Merge` with `durationpb` is incoherent.

### ISSUE THREAD

**Issue by lahabana** [golang/protobuf#1359]
**What version of protobuf and what language are you using?**
Version: @5aec41b (master at time of opening) and before

**What did you do?**

This test should pass and it doesn't:

```go
func TestMerge(t *testing.T) {
	d1 := durpb.New(time.Second)
	d2 := durpb.New(time.Millisecond * 100)
	proto.Merge(d1, d2)

	if d1.AsDuration() != time.Millisecond * 100 {
		t.Errorf("Merge result is not valid: %s expected %s", d1.AsDuration(), time.Millisecond * 100)
	}
}
```

**What did you expect to see?**

The fact that duration is composed of seconds and milliseconds should make 

**What did you see instead?**

```
=== RUN   TestMerge
    duration_test.go:38: Merge result is not valid: 1.1s expected 100ms
--- FAIL: TestMerge (0.00s)
```

Seconds and Nanos are merged separately which goes against what people would expect.

**Anything else we should know about your project / environment?**

Fixing this would be a breaking change.
Maybe making it easier for people to specify custom merge functions on specific types is sufficient.
From a quick look at the code it seems that it might be possible to expose "options" to customise merge behaviour.

**Comment by neild** [comment]
The behavior here is unfortunate, but consistent with the definition of the `Duration` message and the `Merge` operation. A `Duration` has two fields, and `Merge` operates on a per-field basis.

To the best of my knowledge, this behavior is consistent across protobuf implementations. I would expect the same result from C++'s [`MergeFrom`](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.message#Message.MergeFrom.details) method, for example.

We try to avoid adding Go-specific features, so unless other protobuf APIs provide per-message-type customization of merge operations (which, as far as I knowm they do not), we're not likely to add that feature to the Go API.

I don't think there's much we can do here, I'm afraid.

**Comment by neild** [comment]
I'm going to close this, since while the behavior is indeed unfortunate, I don't see anything we can do in the Go implementation to correct it.

**Comment by jpeach** [comment]
> We try to avoid adding Go-specific features, so unless other protobuf APIs provide per-message-type customization of merge operations (which, as far as I knowm they do not), we're not likely to add that feature to the Go API.

Thanks for the update @neild . We ended up [vendoring](https://github.com/kumahq/kuma/blob/master/pkg/util/proto/google_proto.go) the`proto.MergeFrom` so that we could access the internal per-message-type options.
