### ISSUE TITLE
protojson Marshal does not use name or value map to resolve

### ISSUE THREAD

**Issue by TVictor** [golang/protobuf#1360]
Enum in proto:

```
  enum Action {
    ACTION_UNSPECIFIED = 0;
    ACTION_APPROVED = 1;
    ACTION_DECLINED = 2;
    ACTION_CHALLENGE = 3;
    ACTION_CANCELLED = 4;
    ACTION_CANCELLATION_FAILED = 5;
    ACTION_ADD = 6;
    ACTION_UPDATE = 7;
    ACTION_ACTIVATE = 8;
    ACTION_SUSPEND = 9;
    ACTION_RESUME = 10;
    ACTION_DELETE = 11;
    ACTION_PENDING = 12;
  }
```

which will become this in pb.go:

```go
type Result_Action int32

const (
	Result_ACTION_UNSPECIFIED         Result_Action = 0
	Result_ACTION_APPROVED            Result_Action = 1
	Result_ACTION_DECLINED            Result_Action = 2
	Result_ACTION_CHALLENGE           Result_Action = 3
	Result_ACTION_CANCELLED           Result_Action = 4
	Result_ACTION_CANCELLATION_FAILED Result_Action = 5
	Result_ACTION_ADD                 Result_Action = 6
	Result_ACTION_UPDATE              Result_Action = 7
	Result_ACTION_ACTIVATE            Result_Action = 8
	Result_ACTION_SUSPEND             Result_Action = 9
	Result_ACTION_RESUME              Result_Action = 10
	Result_ACTION_DELETE              Result_Action = 11
	Result_ACTION_PENDING             Result_Action = 12
)

// Enum value maps for Result_Action.
var (
	Result_Action_name = map[int32]string{
		0:  "ACTION_UNSPECIFIED",
		1:  "ACTION_APPROVED",
		2:  "ACTION_DECLINED",
		3:  "ACTION_CHALLENGE",
		4:  "ACTION_CANCELLED",
		5:  "ACTION_CANCELLATION_FAILED",
		6:  "ACTION_ADD",
		7:  "ACTION_UPDATE",
		8:  "ACTION_ACTIVATE",
		9:  "ACTION_SUSPEND",
		10: "ACTION_RESUME",
		11: "ACTION_DELETE",
		12: "ACTION_PENDING",
	}
	Result_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED":         0,
		"ACTION_APPROVED":            1,
		"ACTION_DECLINED":            2,
		"ACTION_CHALLENGE":           3,
		"ACTION_CANCELLED":           4,
		"ACTION_CANCELLATION_FAILED": 5,
		"ACTION_ADD":                 6,
		"ACTION_UPDATE":              7,
		"ACTION_ACTIVATE":            8,
		"ACTION_SUSPEND":             9,
		"ACTION_RESUME":              10,
		"ACTION_DELETE":              11,
		"ACTION_PENDING":             12,
	}
)
````
We then run a script to strip the prefix from the map:

```// Enum value maps for Result_Action.
var (
	Result_Action_name = map[int32]string{
		0:  "UNSPECIFIED",
		1:  "APPROVED",
		2:  "DECLINED",
		3:  "CHALLENGE",
		4:  "CANCELLED",
		5:  "CANCELLATION_FAILED",
		6:  "ADD",
		7:  "UPDATE",
		8:  "ACTIVATE",
		9:  "SUSPEND",
		10: "RESUME",
		11: "DELETE",
		12: "PENDING",
	}
	Result_Action_value = map[string]int32{
		"UNSPECIFIED":         0,
		"APPROVED":            1,
		"DECLINED":            2,
		"CHALLENGE":           3,
		"CANCELLED":           4,
		"CANCELLATION_FAILED": 5,
		"ADD":                 6,
		"UPDATE":              7,
		"ACTIVATE":            8,
		"SUSPEND":             9,
		"RESUME":              10,
		"DELETE":              11,
		"PENDING":             12,
	}
)
```
The following go code will produce JSON with the ACTION_ prefix still there
```
	mops := &protojson.MarshalOptions{}
	bin, _ := mops.Marshal(in)
        log.Println("Proto message to JSON", string(bin))
```
```
2021/09/01 09:13:56 Proto message to JSON {"messageID":"15cc1183-6ada-44df-9455-28183b1807d2","result":{"action":"ACTION_APPROVED"}}
```
The expectation is that this will be converted to *APPROVED*

**Comment by dsnet** [comment]
The `Result_Action_name` and `Result_Action_value` are not used by the runtime to determine any of the protobuf type information. All of that is derived from the raw `FileDescriptorProto` which are usually generated into the `.pb.go` file under the `file_XXX_rawDesc` variable ([for example](https://github.com/protocolbuffers/protobuf-go/blob/5aec41b4809b9822a34e17acd06ae9ae9f41c13d/types/known/anypb/any.pb.go#L419-L435)). That binary blob is provided to `protoc-gen-go` by `protoc`. The only supported way to affect the enum values itself is to change it in the `.proto` file.

**Comment by TVictor** [comment]
We are building a translator from grpc to json rest directly, the problem is that according to the style guide the enums need to be prefixed or they will be seen as duplicated because it uses C++ scoping rules, like UNSPECIFIED and APPROVED is found in different enum types.
We are struggling to find a way to have ACTION_APPROVED be only APPROVED when calling the Rest service.

**Comment by dsnet** [comment]
Unfortunately, I know of no way to accomplish what is desired except to break the recommendation in the style guide.

For historical context: When the protobuf language was developed, it adopted the C++ namespace rules for enum values, which meant that enum values were in the same scope _alongside_ the enum type itself (rather than being within it's own namespace _under_ the enum type). This meant that enum values could easily clash with another enum value with the same name. The style guide recommendation is an attempt to provide a separate namespace for each enum's values by prepending a prefix. It's a hack, but does a mostly okay job at preventing accidental conflicts.

**Comment by TVictor** [comment]
This used to work with protobuf lib v1 and jsonpb we moved to bufbuild and the latest versions and now it is not working with protojson or jsonpb

**Comment by dsnet** [comment]
While that may be, "it used to work" is not a valid justification for why it must continue to work that way. The [compatibility agreement](https://github.com/golang/protobuf#compatibility) documents that the module has the right to make "breaking" changes to any unexported detail of the generated code. The runtime in much older versions of relying directly on the `Result_Action_name` and `Result_Action_value` maps is an internal implementation details that was changed in newer versions for a number of reasons (e.g., better init performance, type consistency, smaller binaries, etc.).

**Comment by TVictor** [comment]
Thanks, I agree you have the full right. Just wanted to make sure I am not going bonkers or missing something on my end.

**Comment by dsnet** [comment]
I'm sorry to hear about the troubles. Some of the more recent changes in the last year or two have certainly caused some friction, but they were trying to nail down behavior to be more consistent and more obvious to users when they might be depending on something that is undefined behavior in the hopes that it avoids untold amounts of friction in the future for new code being written today.
