### ISSUE TITLE
newEnumConverter panic

### ISSUE THREAD

**Issue by victor9382** [golang/protobuf#1366]
**What version of protobuf and what language are you using?**
Version: (e.g., `v1.1.0`, `89a0c16f`, etc)

**What did you do?**
If possible, provide a recipe for reproducing the error.
A complete runnable program is good with `.proto` and `.go` source code.

**What did you expect to see?**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment?**

**Comment by victor9382** [comment]
/internal/impl/convert.go
when repeated list is empty
fd.Enum().Values().Get(0) panic

**Comment by neild** [comment]
Please provide a way to reproduce the problem, preferably as a complete runnable program with `.proto` and `.go` source code. Thanks.

**Comment by dsnet** [comment]
Can you provide a reproducer for this? If I remember correctly, `protoc` refuses to compile a `.proto` with an empty enum set.

**Comment by victor9382** [comment]
my mistake using gogofast.
