### ISSUE TITLE
Add a method to marshal message to bytes map

### ISSUE THREAD

**Issue by zjj9850** [golang/protobuf#1367]
**Is your feature request related to a problem? Please describe.**
I need a map,the key is the message field number and the value is the encoding binary of field's value. 

**Describe the solution you'd like**
I modify the original code,add a method that name is MarshalToMap,it can marshal message to a map of encoding binary.
Also can export the method of marshalField.

**Additional context**
Just like this...

```golang
func (o MarshalOptions) marshalToMap(message Message) (map[int32][]byte, error) {
        m := message.ProtoReflect()
	var wire_map map[int32][]byte = make(map[int32][]byte)
	var err error
	o.rangeFields(m, func(fd protoreflect.FieldDescriptor, v protoreflect.Value) bool {
		b, err := o.marshalField(nil, fd, v)
		if err == nil {
			wire_map[int32(fd.Number())] = b
		}
		return err == nil
	})
	return wire_map, err
}
```

**Comment by puellanivis** [comment]
I’m not sure I see much general utility for this function? I imagine you have good cause for wanting this feature, and it looks like you could implement this yourself with a `func marshalToMap(o MarshalOptions, message Message) …` function.

**Comment by neild** [comment]
New API additions need to be generally useful and/or provide equivalent functionality to APIs present in other protobuf implementations, preferably both.

I'm sorry, but this isn't something we're going to add.
