### ISSUE TITLE
Report a coding bug about unused result.

### ISSUE THREAD

**Issue by guodongli-google** [golang/protobuf#1369]
**What version of protobuf and what language are you using?**
Version: the current version

**What did you do?**
Used a static analyzer tool **DeepGo** to scan this repo, and investigated a finding by the "unusedwrite" checker:
https://github.com/protocolbuffers/protobuf-go/blob/master/proto/encode.go#L317

**What did you expect to see?**
The correct code should be:
```
	b = protowire.AppendVarint(b[:pos], uint64(mlen))
	return b
```

**What did you see instead?**
In the current code, 
```
	protowire.AppendVarint(b[:pos], uint64(mlen))
	return b
```
where function [`AppendVarint`](https://github.com/protocolbuffers/protobuf-go/blob/master/encoding/protowire/wire.go#L180-L257) creates new slices `b` (with new memory) using `append` operations:
```
func AppendVarint(b []byte, v uint64) []byte {
	switch {
	case v < 1<<7:
		b = append(b, byte(v))
	...
	}
	return b
}
```
 
Found by #deepgo

**Comment by dsnet** [comment]
I think this code is correct. It's certainly tricky, but the code is speculatively writing some length in `appendSpeculativeLength`, hoping that it is the right size . Later, in `finishSpeculativeLength`, it checks whether the size really was correct, and shifts the buffer around if necessary. Afterwards, it then writes the correct length, which is occurring on L317 (the line being flagged by deepgo). We depend on the append operation having mutated the buffer, but don't need the returned result.

**Comment by dsnet** [comment]
I don't have any great suggestions for how to improve deepgo to avoid false positives here. In general, not using the return value of `append` is highly suspicious, so deepgo is using a reasonable heuristic.

Fundamentally, this code relies on knowing that `protowrite.AppendVarint` will not allocate because `b[:pos]` has enough capacity, and purely relying on the side effects of the operation.

**Comment by neild** [comment]
As Joe says, the code is correct.
