### ISSUE TITLE
protopack: UnmarshalAbductive quality

### ISSUE THREAD

**Issue by wxolp** [golang/protobuf#1370]
Using this file [1], with this code:

~~~go
package main

import (
   "fmt"
   "google.golang.org/protobuf/testing/protopack"
   "os"
)

func main() {
   data, err := os.ReadFile("details.txt")
   if err != nil {
      panic(err)
   }
   var mes protopack.Message
   mes.UnmarshalAbductive(data, nil)
   fmt.Printf("%+v\n", mes)
}
~~~

I am getting unexpected results on the Unmarshal. For example, here is part of the result:

~~~
Message{
   Tag{13, Type(7)},
   Raw("m.google.android.youtube"),
},
~~~

The string is supposed to be `com.google.android.youtube`, so it seems the `co` is being recognized as something else. Am I able to get better results somehow?

1. https://github.com/golang/protobuf/files/7307091/details.txt

**Comment by neild** [comment]
`UnmarshalAbductive` makes a best-effort guess at trying to figure out what might be a message. In this case, you've probably got a field which is not a message, but which has wire-format contents that look enough like one that `UnmarshalAbductive` is getting confused.

The way to get better results is to use `(*protopack.Message).UnmarshalDescriptor`. Or better, `proto.Unmarshal`; `protopack` is extremely specialized and not expected to be of use if you are not intimately familiar with the wire format.

**Comment by wxolp** [comment]
> You might also find the [pbdump](https://go.googlesource.com/protobuf/+/refs/heads/master/internal/cmd/pbdump/) utility useful in analyzing wire-format data for an unknown protobuf. 

That is really cool, but it seems to have the same problem reported in the original post above :(

**Comment by wxolp** [comment]
I tried this just to see what would happen:

~~~go
package main

import (
   "fmt"
   "google.golang.org/protobuf/proto"
   "google.golang.org/protobuf/types/known/structpb"
)

func main() {
   data := []byte("\x12\x02\b\x01")
   v, err := structpb.NewList(nil)
   if err != nil {
      panic(err)
   }
   proto.Unmarshal(data, v)
   fmt.Println(v) // 2:"\x08\x01"
}
~~~

It started out OK, but seems to get tripped up on LengthPrefix.

**Comment by wxolp** [comment]
I think I found a fix. This seems to parse the original file correctly:

~~~go
package proto

import (
   "google.golang.org/protobuf/encoding/protowire"
)

type token struct {
   Tag struct {
      Num protowire.Number
      Typ protowire.Type
   }
   Length int
   Tokens interface{}
}

func parseUnknown(b []byte) []token {
   var toks []token
   for len(b) > 0 {
      n, t, fieldlen := protowire.ConsumeField(b)
      if fieldlen < 1 {
         return nil
      }
      var tok token
      tok.Tag.Num = n
      tok.Tag.Typ = t
      _, _, taglen := protowire.ConsumeTag(b[:fieldlen])
      if taglen < 1 {
         return nil
      }
      var (
         v interface{}
         vlen int
      )
      switch t {
      case protowire.VarintType:
         v, vlen = protowire.ConsumeVarint(b[taglen:fieldlen])
      case protowire.Fixed32Type:
         v, vlen = protowire.ConsumeFixed32(b[taglen:fieldlen])
      case protowire.Fixed64Type:
         v, vlen = protowire.ConsumeFixed64(b[taglen:fieldlen])
      case protowire.BytesType:
         v, vlen = protowire.ConsumeBytes(b[taglen:fieldlen])
         sub := parseUnknown(v.([]byte))
         if sub != nil {
            v = sub
         }
      case protowire.StartGroupType:
         v, vlen = protowire.ConsumeGroup(n, b[taglen:fieldlen])
         sub := parseUnknown(v.([]byte))
         if sub != nil {
            v = sub
         }
      }
      if vlen < 1 {
         return nil
      }
      tok.Length = vlen - taglen
      tok.Tokens = v
      toks = append(toks, tok)
      b = b[fieldlen:]
   }
   return toks
}
~~~

**Comment by neild** [comment]
Closing: UnmarshalAbductive is best-effort, and will always make mistakes. This doesn't preclude improving its heuristics in the future, but the nature of the protobuf wire format means it will never be perfect.

**Comment by wxolp** [comment]
I think I found a fix for ambiguous data. From my testing, problems only happen with `protowire.BytesType`, as the result can be a `string`, `bytes` or `message`. You can solve some cases by seeing if the data will parse as a message, or by checking if the data is binary [1]. However if the data can parse as a message, the result could be multiple types.

To solve this, I wrote a package that has separate types for message, string and bytes. If I encounter ambiguous data, I add two entries. One as a string (or bytes) and one as a message. I give both the same field number, and use my new types as the discriminator.

1. https://github.com/golang/go/blob/go1.17.6/src/net/http/sniff.go#L297-L309

**Comment by wxolp** [comment]
I found a model that seems to work in all cases:

~~~go
package protobuf
import "google.golang.org/protobuf/encoding/protowire"

type Message map[protowire.Number]any

type Bytes struct {
   Raw []byte
   Message
}
~~~

If it encounters BytesType, then it just adds the raw bytes to the output. If the bytes can also be a valid message, then a message is added as well, otherwise `nil`.
