### ISSUE TITLE
Add flag to control pb struct tag `omitempty`

### ISSUE THREAD

**Issue by astraw99** [golang/protobuf#1371]
**Is your feature request related to a problem? Please describe.**
In the code, the `omitempty` tag is hard-coded: https://github.com/golang/protobuf/blob/5d5e8c018a13017f9d5b8bf4fad64aaa42a87308/protoc-gen-go/generator/generator.go#L2225
thus it will shadow some of zero field values, like 
errCode int32 = 1, if errCode = 0 then it will not be showed in the output.

**Describe the solution you'd like**
Hope add tag flag like below is preferred:
```
message test {
 bool someone = 1 [json_omitempty=false];
}
```

**Describe alternatives you've considered**
A hack method is:
```
sed -i "" -e "s/,omitempty//g" ./api/proto/*.go
```
Obviously it is not elegant, hope pb add flag officially, thanks.

**Comment by neild** [comment]
Closing: The `json:` struct tags exist for backwards compatibility, but no new code should rely on them and we do not intend to add new features related to them.

**Comment by astraw99** [comment]
Got it, thanks.
