### ISSUE TITLE
Generating `protoreflect.Value` and `protogen.Field`

### ISSUE THREAD

**Issue by thepabloaguilar** [golang/protobuf#1372]
Hello guys, I writing a plugin to generate some gRPC contract tests! Now I made some changes to support attributes that are messages like this:
```proto
message NiceMessage {}

message AwesomeMessage {
    NiceMessage nice_message = 1;
}
```

The code is working as expected but I want to create some test cases in order to maintain the same expected behavior, I have some sort of tests testing fields that are int-ish, float-ish, bool and etc. I'm having some troubles to try to build the values need for my function! This is its signature:
```go
func FormatFieldValue(
	identFunc IdentFunc, // represents the `protogen.GeneratedFile.QualifiedGoIdent` method
	field *protogen.Field,
	value protoreflect.Value,
) (string, error)
```

I can easily generate the `value` with this code:
```go
simpleMessageValue, _ := structpb.NewValue(map[string]interface{}{
	"Name": "Name",
	"Age": 10,
})
simpleMessage := simpleMessageValue.ProtoReflect()
```

I didn't find a way to generate the `protogen.Field`, also, I can't instantiate it by myself because the `Desc` attribute is an interface, `protoreflect.FieldDescriptor`, that's a huge interface!

You guys can help me to figure out how to generate that, please?

**Comment by neild** [comment]
The easiest way to test code using `protogen` is to probably to call [`protogen.Options.New`](https://pkg.go.dev/google.golang.org/protobuf/compiler/protogen#Options.New) with a test `CodeGeneratorRequest` message. You can either build the `CodeGeneratorRequest` by hand, or use `protoc` to create one.
