### ISSUE TITLE
jsonpb -> protojson: incompatibility unmarshaling Duration types

### ISSUE THREAD

**Issue by howardjohn** [golang/protobuf#1374]
**What version of protobuf and what language are you using?**
v1.27.1, golang

**What did you do?**

Marshaled some Duration types from Json:
```go
func TestMarshal(t *testing.T) {
	s := []byte(`{"dns_refresh_rate": "500ms"}`)
	{
		c := &cluster.Cluster{}
		t.Log(protojson.Unmarshal(s, c), c)
	}
	{
		c := &cluster.Cluster{}
		t.Log(jsonpb.Unmarshal(bytes.NewReader(s), c), c)
	}
}
```

**What did you expect to see?**
Behavior is the same

**What did you see instead?**
```
=== RUN   TestMarshal
    validation_test.go:54: proto: syntax error (line 1:22): unexpected token "500ms" 
    validation_test.go:58: <nil> dns_refresh_rate:{nanos:500000000}
```

**Anything else we should know about your project / environment?**

I am aware that the `duration.proto` clearly states the allowed formats, and thus the new version is actually probably _more correct_. While this makes sense in principle, its is tricky in practice.

Because of the old jsonpb marshaling rules, we have now effectively committed to accepting strings like `500ms` in our API. This means that upgrading the protobuf v2 library is a breaking change for us. Even if it wasn't, IMO the old way was more ergonomic, but that is less important. Unfortunately, there does not seem to be any way to get the old behavior. This leaves us with an easy choice: Use a deprecated library or make a breaking change - we will never do the latter, so we are stuck with the old library for now.

Would a PR to make this configurable, if not outright accept the old format in all cases, be acceptable?

**Comment by howardjohn** [comment]
By the way, I don't care about the marshalled outputs - only the accepted unmarshalling inputs

**Comment by neild** [comment]
Accepting invalid input is a real problem, because it leads to inputs which can only be parsed by specific implementations.

In this case, so far as I know `jsonpb` has never output durations with a `ms` suffix. So this case applies strictly to manually-produced data making use of an undocumented feature of `jsonpb`. I don't think there's a good case for adding this quirk to `protojson`.

Note that you can upgrade to the `"google.golang.org/protobuf"` module for other operations while still using `"github.com/golang/protobuf/jsonpb"`; the package continues to exist specifically to support cases which depend on its exact quirks.

**Comment by howardjohn** [comment]
If (3) is the way to go I am happy to close this. I was surprised I wasn't able to find much obvious references to the incompatibilities between the two libraries, but my search may have been overly focused on `Duration` specifically. For our case we will just continue using jsonpb and abstract it into a common library so we can swap the implementation to protojson if its plausible in the future. Thanks for the help here.

**Comment by neild** [comment]
Closing: Users who depend on `jsonpb` quirks can continue to use `jsonpb` indefinitely. It's better for `protojson` to be fully standards-compliant than to indefinitely support incompatible Go-only behavior from `jsonpb`.

The fact that `jsonpb` is kind-of-but-not-really compatible with the standard protobuf JSON encoding is unfortunate, and doesn't leave any perfect options.
