### ISSUE TITLE
RegisterXXXServer with `grpc.ServiceRegistrar`

### ISSUE THREAD

**Issue by defool** [golang/protobuf#1378]
**Is your feature request related to a problem? Please describe.**
Can not register server by `grpc.ServiceRegistrar`, I need something like https://github.com/grpc/grpc-go/issues/3966

**Describe the solution you'd like**

Change this line
`https://github.com/golang/protobuf/blob/master/internal/gengogrpc/grpc.go#L156`

to 

```
g.P("func Register", service.GoName, "Server(s ", grpcPackage.Ident("ServiceRegistrar"), ", srv ", serverType, ") {")
```

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by neild** [comment]
Closing: gRPC changes should happen in the gRPC repository.
