### ISSUE TITLE
github.com\golang\protobuf\proto\proto3_proto\proto3.pb.go file is referring to testdata folder/package

### ISSUE THREAD

**Issue by ShanthkumarS079** [golang/protobuf#138]
proto3.pb.go file is referring to testdata folder.
Is this testadata folder has test files .?
Is proto3.pb.go file is a test file.

I believe as per go the testdata <packages> shouldn't referred from go source code.

**Comment by dsymonds** [comment]
I don't understand what you're asking, but proto3.pb.go is for the tests.
