### ISSUE TITLE
Inconsistent types imports when generating Go code.

### ISSUE THREAD

**Issue by FairlySadPanda** [golang/protobuf#1380]
**What version of protobuf and what language are you using?**
protoc-gen-go v1.26.0
protoc        v3.15.8

**What did you do?**
Generated the same Go code using the same versions of protoc and protoc-gen-go on two different machines.

**What did you expect to see?**
The generated code is consistent.

**What did you see instead?**
On one machine the code that is generated uses the google.golang.org/protobuf locations for anypb and timestamppb imports. On the other machine, the generated code uses the github.com/golang/protobuf locations for any and timestamp:

Machine A:
```// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: xxx.proto

package messaging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)
```

Machine B:
```// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: xxx.proto

package messaging

import (
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment?**
Both machines are using Ubuntu 20.04 via WSL2 to generate the code.

The code that generates this gets the timestamp and any definitions as so:

```import google/protobuf/timestamp.proto```

**Comment by neild** [comment]
You are probably using different versions of `google/protobuf/any.proto` on the two machines. The import path for the associated package is taken from the `go_package` option in this file.

**Comment by FairlySadPanda** [comment]
Bingo: a quirk of the compiler which would have required quite a bit of lateral thinking to spot.
