### ISSUE TITLE
Different count of white spaces between key and value after Marshal proto message

### ISSUE THREAD

**Issue by lebovski** [golang/protobuf#1381]
**What version of protobuf and what language are you using?**
Version: v1.26.0
Language: go1.17.1 linux/amd64

**What did you do?**
Marshal proto to json:
```go
func DumpProtobufToStream(m proto.Message, writer io.Writer) error {
	const indent = 4

	marshaller := &protojson.MarshalOptions{
		Indent:          strings.Repeat(" ", indent),
		EmitUnpopulated: true,
		UseProtoNames:   true,
		UseEnumNumbers:  true,
	}

	data, err := marshaller.Marshal(m)
	if err != nil {
		return errors.Wrap(err, "marshal message")
	}

	_, err = io.Copy(writer, bytes.NewReader(data))
	if err != nil {
		return errors.Wrap(err, "copy")
	}

	return nil
}
````

Proto message example:
```proto
message Error {
    int32 code = 1;
    string msg = 2;
}
```

Test (unstable)
```go
func TestDumpProtobufToStream(t *testing.T) {
	data := doserr.Success
	extraspace := ":  \""
	expected := `{
    "code": 200,
    "msg": "succeeded",
}`

	buf := &bytes.Buffer{}

	err := DumpProtobufToStream(data, buf)
	require.NoError(t, err)

	require.False(t, strings.Contains(buf.String(), extraspace), buf.String())
	require.Equal(t, expected, buf.String())
}
```

**What did you expect to see?**
Single space between key and value.
```
{
    "code": 200,
    "msg": "succeeded",
}
```

**What did you see instead?**
Two space between key and value (unstable reproduce).
```
{
    "code":  200,
    "msg":  "succeeded",
}
```

**Comment by neild** [comment]
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#unstable-text:

> Why does the output of prototext keep changing?
>
> We make no promises about the long-term stability of Go's implementation of the text format. There is no canonical specification of the protobuf text format, and we would like to preserve the ability to make improvements in the prototext package output in the future. Since we don't promise stability in the package's output, we've deliberately introduced instability to discourage users from depending on it.
>
> To obtain some degree of stability, we recommend passing the output of prototext through the txtpbfmt program. The formatter can be directly invoked in Go using parser.Format.

**Comment by dsnet** [comment]
If you want an output that is stable and safe for byte-for-byte comparisons, then follow #1121

**Comment by neild** [comment]
Closing: Expected behavior.
