### ISSUE TITLE
Creating a resolver for creating a google.proto.any

### ISSUE THREAD

**Issue by jamie-macdonald** [golang/protobuf#1383]
Hi 

I cannot see any example of where a resolver has been created to work with google.protobuf.any type.  Are you Able to point me in the direction of this? 

My unmarsheller is breaking because of it and it would be good to resolve this.

**Comment by neild** [comment]
[`protoregistry.Types`](https://pkg.go.dev/google.golang.org/protobuf/reflect/protoregistry#Types) implements the `proto.UnmarshalOptions.Resolver` interface, and `protoregistry.GlobalTypes` is a global registry.
