### ISSUE TITLE
protojson decode error message echo back the user request input, potential security risk

### ISSUE THREAD

**Issue by balala888** [golang/protobuf#1384]
In particular, this line https://github.com/protocolbuffers/protobuf-go/blob/master/encoding/protojson/decode.go#L340

If my understanding is correct, when the protobuf expects a type of bool, and when we pass in a string, this error message will bubble up, echoing back the user input in the API response, which may cause the service to be subject to XSS attack. (I am using proto-grpc-gateway hosting an HTTP API). Should we remove the user input from the error message? Or is there another way to replace this error with something else in the API response?

I have been trying to override the ErrorHandler, but  I have to do regex on the message content to replace it, which is not very ideal. 

Thanks!

**Comment by cybrcodr** [comment]
It is intended for `protojson` errors to pinpoint out the offending input.  I do agree though that applications/services using `protojson` should be careful in surfacing its error message as is.  I'm not familiar with the proto-grpc-gateway, but I think you should file a bug on that project instead.

**Comment by neild** [comment]
Closing as intended behavior.
