### ISSUE TITLE
duplicate codes

### ISSUE THREAD

**Issue by 63818569** [golang/protobuf#1385]
The following code is repeated several times in the file https://github.com/protocolbuffers/protobuf-go/blob/master/internal/impl/codec_gen.go.
```go
	if len(b) >= 1 && b[0] < 0x80 {
		v = uint64(b[0])
		n = 1
	} else if len(b) >= 2 && b[1] < 128 {
		v = uint64(b[0]&0x7f) + uint64(b[1])<<7
		n = 2
	} else {
		v, n = protowire.ConsumeVarint(b)
	}
```
In addition,  The following code has been implemented in the protowire/ConsumeVarint function.
```go
        if len(b) >= 1 && b[0] < 0x80 {
		v = uint64(b[0])
		n = 1
	} else if len(b) >= 2 && b[1] < 128 {
		v = uint64(b[0]&0x7f) + uint64(b[1])<<7
		n = 2
	}
```
Why is it required outside the protowire/ConsumeVarint function?

**Comment by dsnet** [comment]
It's for performance. Many of the functions in `codec_gen.go` are in the hot-path, so avoiding the function call to `protowire.ConsumeVarint` provides a noticeable performance benefit.

**Comment by neild** [comment]
As @dsnet says: This is manually inlined for performance.
