### ISSUE TITLE
encoding/protojson: Add unmarshal option to allow parsing boolean value from string

### ISSUE THREAD

**Issue by kagaya85** [golang/protobuf#1386]
**Is your feature request related to a problem? Please describe.**
In some situation, the bool type value in Json not follow the standard value, like `"true"` or `"True"` strings, so it may cause a invalid value panic when unmarshal it to proto struct. 

example:

```json
{
	"booltype": "true"
}
```

```protobuf
message Bootstrap {
  bool booltype = 1;
}
```

and will get a panic:
```
panic: proto: invalid value for bool type: "true"
```

I'd like to submit a change to `encoding/protojson` that add an unmarshal option like`AllowParseBool` which will try to parse the string value, like using `strconv.ParseBool` or just allow only specific strings to be parsed.

**Describe the solution you'd like**
Add a new option `AllowParseBool` in `UnmarshalOptions`, and the default is `false` which mean not change the original behavior

```go
type UnmarshalOptions struct {
	...
	// If AllowParseBool is set, accept string values as booleans.
	// "true","True" for true and "false", "False" for false, or using strconv.ParseBool
	// Any other value is considered an error
	AllowParseBool bool
	...
}
```
**Describe alternatives you've considered**
I've considered other ways like to allow override unmarshal logic, but this may introduce more complexity. If we have any other better solutions, please tell me :)

**Additional context**
I'd like to work on this if the community accept it.

**Comment by dsnet** [comment]
The [proto3 JSON mapping](https://developers.google.com/protocol-buffers/docs/proto3#json) is clear that the only valid values for bool are `true` and `false`. It does not allow for any variant of it where it is escaped as a JSON string.

Furthermore, [the C++ implementation](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.util.json_util#JsonParseOptions) provides no options to parse stringified `"true"` and `"false"` into a boolean.

Since the goal of this project is to be compliant with the wider protobuf project, I don't see how this feature can be provided.

**Comment by kagaya85** [comment]
Hi @dsnet , thanks for your reply, I agree we need to maintain compatibility with the proto3 standard. I think the JSON mapping defined how Proto3 encoding in JSON ensure that marshal proto struct to JSON will follow this rule.

IMHO, add this option in unmarshal procedure will not break this rule and will provide more flexible options for different business scenarios. I also find a similar `parseBool` in Java utils which accept a string type boolean value, see: https://github.com/protocolbuffers/protobuf/blob/edc8a3182811cc39272549ff894793e1fff4aaab/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L1821

So, is there any possibility of providing this feature in protojson?

**Comment by neild** [comment]
The goal of the `protojson` package is to provide an implementation of protobuf JSON encoding/decoding that interoperates with other protobuf implementations. Accepting input that other implementations do not accept is contrary to that goal--we do not want there to be data which can be parsed by one implementation but not by others.

If the Java protobuf JSON parser accepts string values for bools, that's unfortunate, but not a reason for the Go parser to be broken as well. If all or most parsers (Java, C++, etc.) accept string values for bools, then perhaps the specification should be changed to match reality. If the spec needs changing, that's a decision that needs to be made by the overall protobuf maintainers, not the ones of the Go implementation. See: https://developers.google.com/protocol-buffers/docs/faq#can_i_add_new_features_to_protocol_buffers

We will not add an option to customize the inputs and outputs of the (un)marshaler unless that option also exists in other implementations.

**Comment by kagaya85** [comment]
OK I got it, thanks you for the explanation
