### ISSUE TITLE
how to judge if this field has an explicit "optional" label in pb2

### ISSUE THREAD

**Issue by wangjingpei** [golang/protobuf#1387]
how to judge if this field has an explicit "optional" label in pb2, I use code bollow, but it seemed doesn't work
if field.AsFieldDescriptorProto().Label != nil && field.GetLabel() == descriptor.FieldDescriptorProto_LABEL_OPTIONAL {
	RawOptional = true
}

**Comment by neild** [comment]
What type is `field`? What doesn't work? There is no type with an `AsFieldDescriptorProto` method in this module. Perhaps you're using some other implementation?

In `google.golang.org/protobuf/reflect/protoreflect`, the [`FieldDescriptor.HasOptionalKeyword`](https://pkg.go.dev/google.golang.org/protobuf/reflect/protoreflect#FieldDescriptor) method reports whether the `optional` keyword was explicitly specified for a field.
