### ISSUE TITLE
Preserve unknown fields when unmarshalling from JSON

### ISSUE THREAD

**Issue by xyzzyz** [golang/protobuf#1390]
Currently, there is no way to preserve unknown fields when unmarshalling messages from JSON using protojson module. (I guess that unknown fields are not serialized to JSON either, but I haven't confirmed that). I suppose this is a result of a misguided design choice originally made for proto3 to always drop unknown fields, which since than, thankfully, has been reverted and fixed, in C++ protobuf and also in golang protobuf, for regular protobuf serialization. However, this has not been fixed in protojson.

Right now, the default behavior of protojson is that it simply errors out whenever it encounters unknown fields in JSON objects. This is rather strange default, to put it mildly, given that protobufs were designed to enable forward compatibility, and are commonly used this way. This is not the default behavior that golang protobuf library has when deserializing from regular protobuf wire format. 

Worse, the only way to not error out is to set DiscardUnknown field in UnmarshallerOptions to true. This means that unknown fields are either resulting in parsing error, or are dropped altogether, and there is no way to preserve them.

The behavior of protojson library should be:
1) by default, if JSON object has entries that do not match the protobuf schema, those entries are preserved in an unknown field set, same way they are for objects parsed from regular wire format
2) by default, when a proto message object has some elements in its unknown field set, those elements are by default serialized into JSON
3) the DiscardUnknown option in Unmarshaller behaves as it does right now: it discards unknown fields. Make it false by default.
4) add corresponding DiscardUnknown option to Marshal to drop unknown fields when serialized into JSON. Make it false by default.

**Describe alternatives you've considered**
See any past discussion on behavior of proto libraries with respect to unknown fields. This issue is settled now, and it's only golang JSON library that hasn't caught up with the resolution.

**Comment by xyzzyz** [comment]
One difficulty here is that since JSON messages include field names, but not tag numbers, there is no way to preserve unknown fields on the JSON -> message -> proto wire format route. One could do it on JSON -> message -> JSON route, though.

**Comment by neild** [comment]
I agree that the lack of preservation of unknown fields is a significant gap in the JSON encoding. You should use the binary encoding instead if this is important.

To the best of my knowledge, no protobuf implementations preserve unknown fields from JSON. We are unlikely to add this to the Go implementation alone. If the feature is added, it should be done in a coordinated fashion across all supported implementations to ensure consistent behavior. I suggest opening an issue at https://github.com/protocolbuffers/protobuf/issues if you want to pursue this.

**Comment by xyzzyz** [comment]
This makes sense to me. 

I wrote a comment here to complain that even if you don't preserve unknown field, the current default behavior of returning error on unknown fields instead of silently discarding them, is completely unreasonable, and C++ implementation doesn't do so, but then I went and checked, and in fact, the JSON-format feature of C++ implementation does in fact error out on unknown fields, unless you set ignore_unknown_fields = true in JsonParseOptions, just like the Go implementation here, despite the default behavior in binary format mode being to not error on unknown fields. 

There are some threads about this in the protobuf tracker, e.g.
https://github.com/protocolbuffers/protobuf/issues/1389
https://github.com/protocolbuffers/protobuf/issues/2838
https://github.com/protocolbuffers/protobuf/issues/2289

Either way, I think you can close this issue, as it's not going to get ever fixed before proto4.

**Comment by xyzzyz** [comment]
Closing.
