### ISSUE TITLE
Comparing two dynamicpb.NewMessage from two different protoregistry.Files

### ISSUE THREAD

**Issue by edwardIshaq** [golang/protobuf#1395]
Hello 👋 
I"m trying to build a dynamic `protoregistry.Files` registry that we can dynamically parse and use `.proto` during runtime.
I would like to write a test to confirms that objects created with these two registries are **equal** but I"m running into some trouble. My hypothesis is that its due to different object addresses or something like that because the content of these MessageDescriptors and the actual messages seem to be the same in every other aspect.

The test is constructed as follows:
Assuming I have 2 copies of `protoregistry.Files` deployed on two services I"m able to parse the same exact `.proto` file and get a MessageDescriptor for the message in that file, inspect it has the proper fields etc, create a new objects and have these objects be equal 

```golang
CustomProtoRegistry struct {
        version string 
	fileRegistry *protoregistry.Files
}

func NewRegistryWithVersion(v string) *CustomProtoRegistry {
	files := new(protoregistry.Files)
	return &CustomProtoRegistry{
		version:       version,
		fileRegistry:  files,
	}
}

func (spr * CustomProtoRegistry) DynamicMessageDescriptorByName(fullName pref.FullName) (protoreflect.MessageDescriptor, error) {
	if d, err := spr.fileRegistry.FindDescriptorByName(fullName); err != nil {
		return nil, err
	} else if msgDesc, ok := d.(pref.MessageDescriptor); !ok {
		return nil, fmt.Errorf("failed to find MessageDescriptor named: %s", fullName)
	} else {
		return msgDesc, nil
	}
}


registryA := NewRegistryWithVersion("AAAA")
registryA.RegisterProtoFile("demo.proto")
var msgDescA protoreflect.MessageDescriptor = registryA.DynamicMessageDescriptorByName("full.package.name")
msgTypeA := dynamicpb.NewMessageType(msgDescA)
msgA := dynamicpb.NewMessage(msgDescA)
// msgA.SetFields(...) and set values 

registryB := NewRegistryWithVersion("BBBB")
registryB.RegisterProtoFile("demo.proto")
var msgDescB protoreflect.MessageDescriptor = registryB.DynamicMessageDescriptorByName("full.package.name")
msgTypeB := dynamicpb.NewMessageType(msgDescB)
msgB := dynamicpb.NewMessage(msgDescB)
// msgB.SetFields(...) and set values 

// Compare the two:
outBytesA, _ := proto.Marshal(msgA)
outBytesB, _ := proto.Marshal(msgB)

// ✅ Gives the same exact bytes 
if bytes.Compare(outBytes, inBytes) != 0 { // equals 0  
	t.Fatalf("bytes dont match")
}

// 🛑 This seems to fail  
if msgTypeA.Descriptor() != msgTypeB.Descriptor() {
    	t.Fatalf("descriptor dont match")
}

// 🛑 This seems to fail  as well
if !proto.Equal(msgA, msgB) {
	t.Fatalf("message values not equal!")
}

```

this might be okay as in there is no reason to worry as long as the `proto.Marshal()` is returning the same exact bytes which is what I would expect but I"m not super comfortable with the rest of comparisons that seem to fail.

Note: the same checks pass if I'm using the same registry aka: `registryB := registryA`
Your help is much appreciated 🙏

**Comment by puellanivis** [comment]
I think, that because they could potentially load separate `RegisterProtoFile` with a different `full.package.name` that we wouldn’t be able to guarantee that they’re compatible? I’m not completely sure how we could ensure that `msgTypeA.Descriptor()` is identical in form to `msgTypeB.Descriptor()` but it would absolutely require some amount of semantic equality testing, rather than a simple equality test.

I’m pretty certain that the `proto.Equal` comes back `false` precisely because the `Descriptor() != Descriptor()` line above it.

**Comment by edwardIshaq** [comment]
Yeah, `proto.Equal` did fail on that early check of the `Descriptors` as you noted @puellanivis 
https://github.com/protocolbuffers/protobuf-go/blob/f62736dede0a74248d862247dbcb53ab69582a05/proto/equal.go#L46

I guess the question becomes, is there a canonical way to comparing these type descriptors semantically ? 
otherwise I guess I'll have to settle with `bytes.Equal` comparison at the end of the day

**Comment by dsnet** [comment]
Can you print the output of:
```go
cmp.Diff(msgA, msgB, protocmp.Transform())
```

That should tell us what is different.

**Comment by edwardIshaq** [comment]
Hi @dsnet, 
`cmp.Diff` returns no difference in this case
```go
fmt.Println("diff = ", cmp.Diff(msgA, msgB, protocmp.Transform()))
// prints:  diff =  
```

**Comment by neild** [comment]
The following line is a bit odd, because a `protoreflect.MessageDescriptor` is an interface type and is not normally passed around as a pointer. (Unless this is a `*("github.com/jhump/protoreflect/desc".MessageDescriptor)`?)

```
var msgDescA *protoreflect.MessageDescriptor = registryA.fileRegistry.FindDescriptorByName("full.package.name")
```

You don't show how the `protoreflect.MessageDescriptor`s are constructed, but in two descriptors are `==` only if they are the same object. If you create two `MessageDescriptors` from the same `DescriptorProto`, those descriptors will be different values and will not compare as equal.

`proto.Equal(a, b)` returns false if `a` and `b` have different `MessageDescriptor`s, even if the contents of those descriptors are structurally equivalent.

**Comment by edwardIshaq** [comment]
Hi @neild 

You're right about them not being a pointer. I'll update the snippet up top.
These are the supposed to be `protoreflect.MessageDescriptor`
The way I'm currently constructing them: 

```go
func (spr * CustomProtoRegistry) DynamicMessageDescriptorByName(fullName pref.FullName) (pref.MessageDescriptor, error) {
	if d, err := spr.fileRegistry.FindDescriptorByName(fullName); err != nil {
		return nil, err
	} else if msgDesc, ok := d.(pref.MessageDescriptor); !ok {
		return nil, fmt.Errorf("failed to find MessageDescriptor named: %s", fullName)
	} else {
		return msgDesc, nil
	}
}
```

**Comment by edwardIshaq** [comment]
So to reflect back, those two messages created by two different `protoregistry.Files` (even though they load the same .proto file) will never be `proto.equal` in this case. And that is the result of directly comparing their `protoreflect.MessageDescriptors`  as we [currently have here](https://github.com/protocolbuffers/protobuf-go/blob/f62736dede0a74248d862247dbcb53ab69582a05/proto/equal.go#L46) since they are in fact different objects.
This might not be the intended purpose of the `Files` registry.

The main reason I chose to have a different registry for each version is that I want my server to be able to load different versions of the same proto message during runtime without conflicting on the fullName message. These different versions of the message would be sent by different clients wrapped up in an `anypb.Any` message in this case.

**Comment by neild** [comment]
Fundamentally, `proto.Equal` works on messages of the same type, where "the same type" includes having the same descriptor.

It's fine to have multiple registries with distinct descriptors if that's what your use case needs, but you will not be able to use `proto.Equal` to compare messages across those registries. If that's an operation you need to support, you will need to define your own form of equality.

**Comment by edwardIshaq** [comment]
I guess that clears thing up for me. I'm fine without using `proto.Equal` for messages generated on different registries. that should be fine since we have the `bytes.Equal` providing the needed validation at this stage. I'm also considering checking the fields and options on the descriptors in case I needed a bit deeper comparison in this case. 

Thank you all for looking into this 🙏 
Much appreciated
