### ISSUE TITLE
run fieldalignment on generated proto cause panic

### ISSUE THREAD

**Issue by fahmifan** [golang/protobuf#1396]
**What version of protobuf and what language are you using?**
Version: v1.25.0

**What did you do?**
I run `fieldalignment -fix ./...` on a repository that contains generated profobuf and run it as usual.

**What did you expect to see?**
When i call an rpc it should do as is

**What did you see instead?**
Instead it panic, but not all rpc got panic, I still don't know what the cause. 

This is the panic log
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x2db0a0]
goroutine 8348 [running]:
google.golang.org/protobuf/internal/impl.(*MessageInfo).initOnce(0x400023dc00)
	/home/ubuntu/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go1.16/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message.go:84 +0xa0
google.golang.org/protobuf/internal/impl.(*MessageInfo).init(...)
	/home/ubuntu/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go1.16/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message.go:72
google.golang.org/protobuf/internal/impl.(*messageState).ProtoMethods(0x4006e52580, 0x12cb340)
	/home/ubuntu/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go1.16/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message_reflect_gen.go:30 +0x60
google.golang.org/protobuf/proto.protoMethods(...)
	/home/ubuntu/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go1.16/pkg/mod/google.golang.org/protobuf@v1.25.0/proto/proto_methods.go:18
google.golang.org/protobuf/proto.MarshalOptions.marshal(0x4006000001, 0x0, 0x0, 0x0, 0x1a053d8, 0x4006e52580, 0x19c7f18, 0x4006e52580, 0x400828d8c8, 0xa2608, ...)
	/home/ubuntu/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go1.16/pkg/mod/google.golang.org/protobuf@v1.25.0/proto/encode.go:143 +0x30
google.golang.org/protobuf/proto.MarshalOptions.MarshalAppend(0x1000001, 0x0, 0x0, 0x0, 0x19c7f18, 0x4006e52580, 0x14cb300, 0x19e1848, 0x4006a41020, 0x13042c0, ...)
	/home/ubuntu/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go1.16/pkg/mod/google.golang.org/protobuf@v1.25.0/proto/encode.go:125 +0x78
github.com/golang/protobuf/proto.marshalAppend(0x0, 0x0, 0x0, 0x19e1848, 0x4006e52580, 0x400699a800, 0x400828d9e8, 0xa1110, 0x4000c24e98, 0x0, ...)
	/home/ubuntu/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go1.16/pkg/mod/github.com/golang/protobuf@v1.4.3/proto/wire.go:40 +0x90
github.com/golang/protobuf/proto.Marshal(...)
	/home/ubuntu/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go1.16/pkg/mod/github.com/golang/protobuf@v1.4.3/proto/wire.go:23
google.golang.org/grpc/encoding/proto.codec.Marshal(0x14cb300, 0x4006e52580, 0x400828da48, 0xa2144, 0x400828da48, 0x1a030, 0x40006e2000)
	/home/ubuntu/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go1.16/pkg/mod/google.golang.org/grpc@v1.36.0/encoding/proto/proto.go:45 +0x54
google.golang.org/grpc.encode(0xffff5e77b938, 0x280d368, 0x14cb300, 0x4006e52580, 0x280d368, 0x1c748, 0x40087fdb18, 0x949c7c, 0x19ec480)
	/home/ubuntu/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go1.16/pkg/mod/google.golang.org/grpc@v1.36.0/rpc_util.go:592 +0x44
google.golang.org/grpc.(*Server).sendResponse(0x400697a1c0, 0x19fc0b8, 0x4006a42d80, 0x4005c39000, 0x14cb300, 0x4006e52580, 0x0, 0x0, 0x40008fb290, 0x0, ...)
	/home/ubuntu/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go1.16/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:1006 +0x5c
google.golang.org/grpc.(*Server).processUnaryRPC(0x400697a1c0, 0x19fc0b8, 0x4006a42d80, 0x4005c39000, 0x400697eb10, 0x2638230, 0x0, 0x0, 0x0)
	/home/ubuntu/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go1.16/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:1252 +0x4a0
google.golang.org/grpc.(*Server).handleStream(0x400697a1c0, 0x19fc0b8, 0x4006a42d80, 0x4005c39000, 0x0)
	/home/ubuntu/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go1.16/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:1540 +0xa70
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x4000857010, 0x400697a1c0, 0x19fc0b8, 0x4006a42d80, 0x4005c39000)
	/home/ubuntu/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go1.16/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:878 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/ubuntu/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go1.16/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:876 +0x1f8

```

**Anything else we should know about your project / environment?**
Go version 1.16

**Comment by neild** [comment]
This sounds like you used `fieldalignment` to modify the generated protobuf code?

This is not supported and will not work. The protobuf implementation only supports the *exact* code produced by `protoc-gen-go`. Modifications to that code are never supported, and will in many cases (such as this one) fail in exciting and difficult to diagnose ways.

**Comment by fahmifan** [comment]
@neild yes, the generated protobuf code is modified by the `fieldalignment`, but it's just the struct field, is it still not safe ?

**Comment by dsnet** [comment]
> is it still not safe ?

It was never safe. The generated code needs a strict correlation between the fields in the `.proto` file and the generated Go struct. If you want to reorder the fields, then I recommend doing so in the `.proto` file.

**Comment by fahmifan** [comment]
Oh okeey, thanks for the answer

**Comment by puellanivis** [comment]
🙁 I’m sorry, I don’t think I was clear enough in Issue #1392. I would strongly advise against ever running `fieldalignment` automatically.

Reordering struct fields is such a minimal low-yield performance “optimization” that I had never even thought about it. I should have been more clear that doing so is almost certainly a case of “premature optimization is the root of all evil.”

Reordering of fields for performance—like all performance optimizations—should only ever be done when you have metrics pointing to that specific thing being a performance bottleneck.

Automated tools can be nice, but running every struct in your project against `fieldalignment` is going to yield so many false positives, that it’s certainly only going to make your life harder, not better. Even with manually written structs, fields are often ordered and blocked to show _semantic locality_, which improves the readability of code. Automated reordering of structs is likely to destroy that semantic locality and just like all optimization will result in harder to read amd harder to maintain code.

**Comment by fahmifan** [comment]
@puellanivis yes we do struct field realignment in our CI so it's not affecting our code. And we have a usecase after we implemented `fieldalignment` there is a huge memory reduction around 50%. But we resolve this issue by exclude the generated proto in our CI
