### ISSUE TITLE
[encoding/protojson] Add marshal option `EmitUnpopulatedEnum` to control emit unpopulated enum field.

### ISSUE THREAD

**Issue by j2gg0s** [golang/protobuf#1399]
**Is your feature request related to a problem? Please describe.**

With `encoding/protojson`, we marshal enum to string.
However, it will skip enum field with value zero.

**Describe the solution you'd like**
Use one new marshal option `EmitUnpopulatedEnum` to control wheate emit unpopulate for enum field

**Describe alternatives you've considered**

**Additional context**

**Comment by puellanivis** [comment]
We already provide the option `EmitUnpopulated`, can you explain how/why the existing solution is inappropriate for your proposed use?

**Comment by j2gg0s** [comment]
enum field with value 0 should not be viewed as zero.
I can use `EmitUnpopulated` to rech this, but i don't think it's good enough.

Such message
```
message ABC {
  enum Status {
    X = 0;
    Y = 1;
  }
  Status status = 1;
  string name = 2;
}
```
With `EmitUnpopulated`:  `{"status":"X","name":""}`
I want: `{"status":"X"}`

**Comment by puellanivis** [comment]
Such a narrow and specific option is not listed in the proto3 language standards: https://developers.google.com/protocol-buffers/docs/proto3#json_options

The feature does not exist for C++ https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.util.json_util#JsonPrintOptions (and likely not for Java, or python)

Java does provide the ability to specific a field descriptor that will force unpopulated fields to be printed if they are in the field descriptor.

Python does not provide this capability.

I wonder as well, if your specific problem could be solved with:
```
message ABC {
  enum Status {
    UNSET = 0; // or UNKNOWN
    X = 1;
    Y = 2;
  }
  Status status = 1;
  string name = 2;
}
```

**Comment by neild** [comment]
Options which customize the behavior of marshal functions need to be consistent across protobuf implementations. As a general rule of thumb, an option must be present in the C++ and Java implementations for us to consider adding it to the Go one. To add new options across implementations, the place to start is the greater protobuf issue tracker: https://github.com/protocolbuffers/protobuf/issues
