### ISSUE TITLE
Generation of repeated structs

### ISSUE THREAD

**Issue by primeMover2011** [golang/protobuf#14]
From  http://golang.org/doc/effective_go.html#slices

> Slices hold references to an underlying array, 
> and if you assign one slice to another, 
> both refer to the same array.

When I generate the following proto holding the following messages

    message AmessageWithAString
    {
	    required string aString = 1;
    }

    message RepeatedString 
    {
	    repeated AmessageWithAString PointerToSlice = 1;
    }
	
the generator generates 

    type RepeatedString struct {
    	PointerToSlice   []*AmessageWithAString `protobuf:"bytes,1,rep" json:"PointerToSlice,omitempty"`
    	XXX_unrecognized []byte                 `json:"-"`
    }

shouldn't it generate
**PointerToSlice   []AmessageWithAString**
instead?

**Comment by dsymonds** [comment]
It's working as intended. You need pointers to messages almost everywhere else.
