### ISSUE TITLE
Golang: Missing custom JSON tag

### ISSUE THREAD

**Issue by normanjaeckel** [golang/protobuf#1400]
**What version of protobuf and what language are you using?**
Version: libprotoc 3.17.3 Golang

**What did you do?**
I have a message with customized json field name. The file `test.proto` looks like this:

```protobuf
syntax = "proto3";
option go_package = "github.com/myorg/myrepo/mypkg";

service MyService {
   rpc MyRemoteProcedure(MyMessage) returns (MyResponse);
}

message MyMessage {
    string my_field = 1 [ json_name ="yet_another_name" ];
}

message MyResponse {}
```

**What did you expect to see?**

The json tag should be `yet_another_name`.

```golang
type MyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyField string `protobuf:"bytes,1,opt,name=my_field,json=yet_another_name,proto3" json:"yet_another_name,omitempty"`
}
```

**What did you see instead?**

But it isn't.

```golang
type MyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyField string `protobuf:"bytes,1,opt,name=my_field,json=yet_another_name,proto3" json:"my_field,omitempty"`
}
```

**Anything else we should know about your project / environment?**

I think the bug is here: https://github.com/protocolbuffers/protobuf-go/blob/master/cmd/protoc-gen-go/internal_gengo/main.go#L716

The function should respect `field.Desc.HasJSONName()` and use `field.Desc.JSONName()` is this case. But I am not sure and I really do not understand all this great magic here. (But I really like it at all.)

Thanks in advance.

**Comment by puellanivis** [comment]
This has already been extensively discussed, and we cannot “fix” this without breaking other people’s code. See: Hyrum’s Law

Just one of the many issues that have been opened before: https://github.com/golang/protobuf/issues/1307

**Comment by normanjaeckel** [comment]
Ok, I understand this although I am a little bit sad. Nevertheless thanks for the quick answer.
