### ISSUE TITLE
Oneof field written not by field number order 

### ISSUE THREAD

**Issue by Karasiq** [golang/protobuf#1404]
Message serialized by java:
![image](https://user-images.githubusercontent.com/7199719/148776909-59fc3c19-6b22-434e-aaa5-e9aa3ff4020e.png)

Same with golang:
![image](https://user-images.githubusercontent.com/7199719/148777218-705e34b1-40d0-47b7-b20d-ce1932cc05b4.png)

(Field 2 which declared as oneof{2,13} was written in the end)

The standard doesnt require the field order to be sequential, though i suggest implementing ordered field write in "deterministic mode" or by default to have more compatibility between languages.

**Comment by puellanivis** [comment]
As noted, the standard neither requires nor specifies a canonical field order. As such, all implementations must be prepared to receive fields in any order†.

There is no reason why this package needs to or should go out of its way to force a deterministic order that is not canonically specified.

†: repeated entries must remain in order relative to each other.

**Comment by neild** [comment]
As @puellanivis says, protobufs do not have a canonical serialization form. Different implementations can and do produce different bytes to serialize the same message.

A deterministic, canonical serialization form is a common request, but this is a feature that would need to be added to all supported implementations in a coordinated fashion. The [main protobuf issue tracker](https://github.com/protocolbuffers/protobuf/issues) would be the place to request this.
