### ISSUE TITLE
googling "protoc-gen-go" gets you the old package

### ISSUE THREAD

**Issue by jmhodges-color** [golang/protobuf#1406]
When [googling "protoc-gen-go"](https://www.google.com/search?q=protoc-gen-go), the first result is the pkg.go.dev site for deprecated package `github.com/golang/protobuf/protoc-gen-go`, instead of the correct https://pkg.go.dev/google.golang.org/protobuf@v1.27.1/cmd/protoc-gen-go (at time of writing).

This might be a `pkg.go.dev` bug, instead, but I'm making a ticket here so that y'all are aware.

**Comment by neild** [comment]
Unfortunate, but not much we can do about it. We don't control search results. The `github.com/golang/protobuf` module is marked as deprecated and links to the newer module, so anyone using `go get` with it will get an appropriate warning.
