### ISSUE TITLE
Add custom Go tags in Message type for reflection

### ISSUE THREAD

**Issue by sir-farfan** [golang/protobuf#1408]
Hello, I've been looking around if there's a way to add custom tags to the generated GoLang structure of a message, I came across some "gogo/protobuf" thing but I don't understand what's it about (yet) and doesn't seem to do it anyway, not sure.

I'd like to use the generated Go structure of the message in order to save and retrieve from sources that support reflection, as an example, I want to add a custom "db" tags to map the gRPC/JSON fields correctly to DB column names:

```
message Student {
  string ID = 1; // `db:"Code"`
  string Name = 2; // `db:"FullName"`
}
```

Is it possible?

**Comment by meling** [comment]
Yes. But you will need to use external tools for that; such support will not be added to the protoc-gen-go tool.

I use [protopatch](https://github.com/alta/protopatch) to add some tags; [see here](https://github.com/quickfeed/quickfeed/blob/master/ag/ag.proto) for an example proto file.

I think there are other alternatives as well, but I’ve not tried others myself… (we used to use gogo to do it before)

Be sure that you’ll get some people telling you not to do this, but it’s worked well for us. We avoid lots of manual translation. Sure there are things that still needs your attention, but I love how we can augment proto types with our own methods.

**Comment by sir-farfan** [comment]
Looks like what I want to do, thanks!

**Comment by neild** [comment]
I won't tell you not to do this, but note that modifying the generated protobuf code in any way is explicitly not supported in any way. A future protobuf release could break this workflow without warning.

As for a supported way of adding additional field tags, we are very unlikely to ever add highly language-specific generation options like this. Protobufs are a language- and implementation-neutral data interchange format; options for attaching language-specific metadata work against that.
