### ISSUE TITLE
Add an option to model oneof fields as unions when using protojson

### ISSUE THREAD

**Issue by adit-hotstar** [golang/protobuf#1409]
**Is your feature request related to a problem? Please describe.**

We're currently using [ts-proto](https://www.npmjs.com/package/ts-proto) to generate TypeScript interfaces for JSON-encoded protobuf data sent by the server. On the server, we use protojson to encode the messages to JSON. This works all right until it comes to oneof values. For example, consider the following protobuf schema with a oneof value.

```protobuf
message Example {
  oneof data {
    string foo = 1;
    bool bar = 2;
  }
}
```

Following are some example JSON-encoded messages which follow the above schema.

```json
{
  "foo": "Hello World!"
}

{
  "bar": true
}
```

As you can see, the oneof fields are modeled flatly in the JSON-encoded message. It would be better to model the oneof fields as unions, as you can see in the following examples.

```json
{
  "data": {
    "$case": "foo",
    "foo": "Hello World!"
  }
}

{
  "data": {
    "$case": "bar",
    "bar": true
  }
}
```

The ts-proto library I mentioned earlier supports this format. If you set the option `oneof=unions` then ts-proto will generate a sum type instead of a product type with optional fields. It would be great if protojson also supported generating unions as an option.

**Describe the solution you'd like**

I would like to add a new bool option named `OneOfUnions` to the [`MarshalOptions`](https://pkg.go.dev/google.golang.org/protobuf@v1.27.1/encoding/protojson#MarshalOptions) type in protojson. This option would default to false. When set to false it would follow the old logic and model oneof fields flatly. When set to true it would model oneof fields as unions.

**Describe alternatives you've considered**

Manually converting the flat oneof fields into unions. This would be extremely tedious and wouldn't scale.

**Additional context**

* [OneOf Handling](https://www.npmjs.com/package/ts-proto#oneof-handling) section of the ts-proto README file.

**Comment by puellanivis** [comment]
This package is constrained to the standard https://developers.google.com/protocol-buffers/docs/proto3#json while this option might be desirable and useful, we need to keep strong compatibility with the other implementations, and such a change to the encoding would require buy off from the whole protobuf community.

As such, the proper place to suggest this change would be with the main protobuf project: https://github.com/protocolbuffers/protobuf

**Comment by neild** [comment]
As @puellanivis says, we can not and will not add Go-specific options that customize the output of `Marshal` functions. Protocol buffers are a language-neutral interchange format; any changes to the binary, text, or JSON encodings need to be made in a coordinated fashion across all implementations. If you want to propose such a change, you will need to address it to the main protobuf project, not the Go implementation.
