### ISSUE TITLE
wkt: ``UnmarshalJSON`` should support string "null"

### ISSUE THREAD

**Issue by j2gg0s** [golang/protobuf#1410]
**What version of protobuf and what language are you using?**
v1.27.1

**What did you do?**
I use `structpb.Struct` with sql orm [bun](https://github.com/uptrace/bun), it support encode/decode struct field by json when write/read to sql.

The question is that: 
when marshal with `(*structpb.Struct)(nil)` , `encoding/json` will not call `structpb.Struct.MarshalJSON`, and we will got string "null", 
but when unmarshal "null", `structpb.Struct.UnmarshalJSON` can't deal with `null`.

The error:
```
panic: proto: syntax error (line 1:1): unexpected token null [recovered]
        panic: proto: syntax error (line 1:1): unexpected token null
```

The example:
```
package main

import (
	"encoding/json"
	"fmt"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/types/known/structpb"
)

type CommonGolangStruct struct {
	Name string
}

func ExampleMain() {
	var cgs *CommonGolangStruct
	raw, err := json.Marshal(cgs)
	if err != nil {
		panic(err)
	}
	// null
	fmt.Println(string(raw))

	cgs = new(CommonGolangStruct)
	err = json.Unmarshal(raw, cgs)
	if err != nil {
		panic(err)
	}

	var wkt *structpb.Struct
	raw, err = protojson.Marshal(wkt)
	if err != nil {
		panic(err)
	}
	// {}
	fmt.Println(string(raw))

	wkt = new(structpb.Struct)
	err = protojson.Unmarshal(raw, wkt)
	if err != nil {
		panic(err)
	}

	var wktJSON *structpb.Struct
	raw, err = json.Marshal(wktJSON)
	if err != nil {
		panic(err)
	}
	// null
	fmt.Println(string(raw))

	wktJSON = new(structpb.Struct)
	err = json.Unmarshal(raw, wktJSON)
	if err != nil {
	} else {
		panic(fmt.Errorf("expected error: unmarshal wkt by encoding/json"))
	}

	// Output:
	// null
	// {}
	// null
}
```

**What did you expect to see?**
``Struct.UnmarshalJSON`` should deal with string ``null``

**Comment by neild** [comment]
`json.Marshal` takes a value to marshal, but `json.Unmarshal` takes a pointer to a value to unmarshal into. So your `Unmarshal` call should be:

```
wktJSON = new(structpb.Struct)
err = json.Unmarshal(raw, &wktJSON) // note &
```

Do this, and you'll get the behavior you expect.

**Comment by j2gg0s** [comment]
> panic(fmt.Errorf("expected error: unmarshal wkt by encoding/json"))

Yes, it will not return error anymore.

However, the behavior of structpb.Struct and CommonGolangStruct is still different.
We can unmarshal null with ptr of CommonGolangStruct, but we need unmarshal null with ptr of ptr of structpb.Struct

```
        cgs := CommonGolangStruct{}
        if err := json.Unmarshal([]byte("null"), &cgs); err != nil {
                panic(err)
        }
        fmt.Println(cgs.Name)

        wkt := structpb.Struct{}
        wktPtr := &wkt
        if err := json.Unmarshal([]byte("null"), &wktPtr); err != nil {
                panic(err)
        }
        if wktPtr == nil {
                fmt.Println("wktPtr is nil")
        }
        fmt.Println(wkt.Fields)

        // Output:
        //
        // wktPtr is nil
        // map[]
```

**Comment by puellanivis** [comment]
So, the WKTs are unmarshalling according to the proto3 JSON mapping rules, even when being unmarshaled through `encoding/json`. According to the proto3 JSON mapping rules, `null` is not a valid unmarshalling for `structpb.Struct`. So, you’re running into an inconsistency with the proto3 JSON mapping rules, and the more generic `encoding/json` library rules for generically handling structs that do not implement `json.Unmarshaller`.

I’m not sure how we could (or want) to make unmarshalling `structpb.Struct` consistent with unmarshalling any arbitrary Golang struct that does not implement `json.Unmarshaller`.
