### ISSUE TITLE
go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead

### ISSUE THREAD

**Issue by yuqx1561** [golang/protobuf#1417]
go get -u -v github.com/hashicorp/consul
 
![image](https://user-images.githubusercontent.com/51982585/156081888-3bb6d1c3-8cc6-4bff-b91a-54f2bf77eaae.png)

**Comment by neild** [comment]
Yes, `github.com/golang/protobuf` is deprecated. Can you clarify what you're reporting here?

**Comment by harryzcy** [comment]
README says that `github.com/golang/protobuf` is superseded by the [google.golang.org/protobuf](https://pkg.go.dev/google.golang.org/protobuf) module. But [go.mod](https://github.com/protocolbuffers/protobuf-go/blob/master/go.mod) of `google.golang.org/protobuf` still uses `github.com/golang/protobuf` as a dependency. 

Is it the intended behavior or will `github.com/golang/protobuf` be eventually removed?

**Comment by puellanivis** [comment]
This is intentional. https://github.com/protocolbuffers/protobuf-go/blob/v1.28.0/internal/weakdeps/doc.go#L5-L11

If your program does not actually use `github.com/golang/protobuf` then it will not be pulled into your binary.
