### ISSUE TITLE
Indeterminate line breaks and spaces

### ISSUE THREAD

**Issue by bootun-yh** [golang/protobuf#1423]
when I try to generate `pb.go`, there will be some indeterminate spaces and line breaks in the code I generate:
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/100668952/158312981-fd95b8f4-b698-4803-b03a-2d93064f27fa.png">
Not all codes are like this. Some have it and some don't, this leads to different files generated by me and other members of the team. Due to the premature time, they don't remember the specific git commit of `protoc-gen-go`, the only thing they can be sure of is that they use version 1.3.2 of `protoc-gen-go`.  

Is there a better solution than letting others change the version of `protoc-gen-go`?

**Comment by dsnet** [comment]
> Is there a better solution than letting others change the version of protoc-gen-go?

Not really. Fundamentally, the only way to prevent different team members submitting conflicting versions of generated code is to use the exact same generator.

You'll need to make sure all members of the team are using the same version of `protoc-gen-go` built from the same version of Go. The formatting logic is determined by the Go toolchain, and therefore what version of Go is used to build `protoc-gen-go` becomes relevant.

For this reason, it makes the most sense to have every download the pre-built binaries:  https://github.com/golang/protobuf/releases

**Comment by usernameisnull** [comment]
no, the same protoc-gen-go version in ubuntu and Mac will generate different comments,like:
![image](https://github.com/golang/protobuf/assets/3390414/8dcf62bb-a2ec-4c16-aee8-5cd2da60824a)
