### ISSUE TITLE
How to filter out sensitive fields from a proto object of type interface{} 

### ISSUE THREAD

**Issue by praveenvaltix** [golang/protobuf#1428]
We use proto3 for our APIs and structs. We have a need to log the API request payload for internal analysis and troubleshooting. In many of our APIs, we have sensitive data like passwords, integration keys, etc. We use the extension "google.protobuf.FieldOptions" to indicate which fields have "sensitive" data. I am looking for a generic function using reflect or otherwise, to make a copy of the original payload (object interface{}) by stripping out or obfuscating the "sensitive data fields" which we will then marshal using jsonpb. Our current approach is the following, but we are stuck on how to either omit or obfuscate the "sensitive data fields".

E.g message:

```
extend google.protobuf.FieldOptions {
    bool dataSensitive                       = 50010;
}

message ProfileProperties {
    string name = 1; 
    string integrationKey = 2 [(dataSensitive) = true];
}
```

E.g code to filter out sensitive data.

```
func filterOutSensitiveData(req interface{}) error {
	var err error

	reqMsg, ok := req.(descriptor.Message)
	if !ok {
		log.Printf("req (%v) does not implement descriptor.Message", req)
		err = fmt.Errorf("Not a proto")
		return err
	}

	_, md := descriptor.ForMessage(reqMsg)
	reqValue := reflect.ValueOf(req).Elem()

	for _, field := range md.GetField() {
		fieldByNameValue := reqValue.FieldByName(strings.Title(field.GetName()))
		_, err = proto.GetExtension(field.GetOptions(), E_DataSensitive)
		if err == nil {
			log.Printf("Print sensitive data field: %s", field.GetName())
                         // TODO: filter out 
		} 

		log.Printf("Print type %v ", field.GetType())

		// nested structure
		if field.GetType() == descriptorpb.FieldDescriptorProto_TYPE_MESSAGE {
			elem := fieldByNameValue.Type().Elem()
			newElem := reflect.New(elem)
			filterOutSensitiveData(newElem.Interface())
		}
	}

	return nil
}
```

Any pointers on how to "set a empty or dummy value" for the sensitive data fields will be appreciated.

**Comment by neild** [comment]
See the reflection example here:
https://go.dev/blog/protobuf-apiv2

The example in the blog post doesn't recurse into submessages, but extending it to do so should be straightforward.

If you want to copy the non-sensitive fields rather than clearing the sensitive ones, the `proto.Clone` implementation is a good starting point.

**Comment by praveenvaltix** [comment]
Thanks @neild for the quick response. I will go through this in detail - it looks spot on and relevant.

**Comment by dsnet** [comment]
Have you seen the [protorange](https://pkg.go.dev/google.golang.org/protobuf/reflect/protorange) package? There's an example that does something similar.

**Comment by praveenvaltix** [comment]
Thank you @neild @dsnet for the tips. Following code worked for us.

```
func filterOutSensitiveData(req interface{}) error {
	var err error

	reqMsg, ok := req.(descriptor.Message)
	if !ok {
		log.Printf("req (%v) does not implement descriptor.Message", req)
		err = fmt.Errorf("Not a proto")
		return err
	}

	_, md := descriptor.ForMessage(reqMsg)
	reqValue := reflect.ValueOf(req)
	if reqValue.IsNil() {
		return nil
	}
	reqValue = reqValue.Elem()

	for _, field := range md.GetField() {
		fieldByNameValue := reqValue.FieldByName(strings.Title(field.GetName()))
		_, err = proto.GetExtension(field.GetOptions(), E_DataSensitive)
		if err == nil {
			//log.Printf("Print sensitive data field: %s value: %v", field.GetName(), fieldByNameValue)
			fieldByNameValue.SetString("(sensitive data redacted)")
		}

		// nested structure
		if field.GetType() == descriptorpb.FieldDescriptorProto_TYPE_MESSAGE {
			elem := fieldByNameValue.Interface()
			filterOutSensitiveData(elem)
		}
	}

	return nil
}

```
