### ISSUE TITLE
protoc-gen-go distributed binary for v1.28.0 is unexpected version v1.28.0-devel

### ISSUE THREAD

**Issue by gcangussu** [golang/protobuf#1429]
**What version of protobuf and what language are you using?**
Version: protoc-gen-go v1.28.0 (linux/amd64) (pre-built binary from GitHub releases page: [protoc-gen-go.v1.28.0.linux.amd64.tar.gz](https://github.com/protocolbuffers/protobuf-go/releases/download/v1.28.0/protoc-gen-go.v1.28.0.linux.amd64.tar.gz))

**What did you do?**
Building any .proto file using protoc-gen-go.

Alternatively running `protoc-gen-go --version`.

**What did you expect to see?**
```go
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
```

```shell
$ protoc-gen-go --version
protoc-gen-go v1.28.0
```

**What did you see instead?**
```go
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0-devel
// 	protoc        v3.20.0
```

```shell
$ protoc-gen-go --version
protoc-gen-go v1.28.0-devel
```

The pre-built binary available on [GitHub v1.28.0 release page](https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.28.0) for linux/amd64 is of version `v1.28.0-devel`. It should be `1.28.0` without the "devel" suffix.

**Anything else we should know about your project / environment?**
Debian Bullseye official docker image
protoc v3.20.0

**Comment by stapelberg** [comment]
Thanks for the report. This seems to have been an issue with the release binaries. We have updated the release binaries on GitHub, and now the reported version is `protoc-gen-go v1.28.0` as expected.
