### ISSUE TITLE
Panic on SetField with dynamicpb.Message types

### ISSUE THREAD

**Issue by emcfarlane** [golang/protobuf#1432]
**What version of protobuf and what language are you using?**
protobuf@v1.28.0 go1.18.0

**What did you do?**
Call SetField on a go type with a dynamic type.

https://github.com/emcfarlane/larking/blob/7767296b89b124569288fddcf0502ea38171c005/examples/library/main_test.go#L15-L34
```go
func TestDynamicSet(t *testing.T) { 
 	d, err := protoregistry.GlobalFiles.FindDescriptorByName("larking.examples.library.Book") 
 	if err != nil { 
 		t.Fatal(err) 
 	} 
 	md := d.(protoreflect.MessageDescriptor) 
 	msg := dynamicpb.NewMessage(md) 
  
 	req := &apipb.CreateBookRequest{ 
 		Parent: "/shelves/one", 
 	} 
 	x := req.ProtoReflect() 
 	rd := x.Descriptor() 
 	fd := rd.Fields().ByName("book") 
  
 	v := protoreflect.ValueOf(msg) 
 	x.Set(fd, v)  // Fails here
  
 	t.Log("x", x) 
 } 
```

As part of a PR to my project https://github.com/emcfarlane/larking/pull/55
Protobuffer is defined here: https://github.com/emcfarlane/larking/blob/7767296b89b124569288fddcf0502ea38171c005/examples/library/apipb/library.proto

**What did you expect to see?**

I expected the dynamicpb.Message to be converted to the Go type and set in the Field of the protobuffer.

**What did you see instead?**

Fails as type dynamicpb.Message doesn't equal the go type.
```sh
$ go test -v -run=TestDynamicSet
=== RUN   TestDynamicSet
--- FAIL: TestDynamicSet (0.00s)
panic: invalid type: got *dynamicpb.Message, want *apipb.Book [recovered]
        panic: invalid type: got *dynamicpb.Message, want *apipb.Book

goroutine 36 [running]:
testing.tRunner.func1.2({0x16f4220, 0xc0003695a0})
        /usr/local/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1392 +0x39f
panic({0x16f4220, 0xc0003695a0})
        /usr/local/go/src/runtime/panic.go:838 +0x207
google.golang.org/protobuf/internal/impl.(*messageConverter).GoValueOf(0xc000369440, {{}, 0x17e6e40?, 0xc0003678c0?, 0x8?})
        /Users/edward/pkg/mod/google.golang.org/protobuf@v1.28.0/internal/impl/convert.go:458 +0x3f4
google.golang.org/protobuf/internal/impl.fieldInfoForMessage.func4({0xc000184e90?}, {{}, 0x17e6e40?, 0xc0003678c0?, 0xc0003678c0?})
        /Users/edward/pkg/mod/google.golang.org/protobuf@v1.28.0/internal/impl/message_reflect_field.go:445 +0xd0
google.golang.org/protobuf/internal/impl.(*messageState).Set(0xc000367900, {0x1928278?, 0xc0001c44b0?}, {{}, 0x17e6e40?, 0xc0003678c0?, 0x1da2220?})
        /Users/edward/pkg/mod/google.golang.org/protobuf@v1.28.0/internal/impl/message_reflect_gen.go:91 +0x10b
github.com/emcfarlane/larking/examples/library.TestDynamicSet(0xc0003981a0)
        /Users/edward/src/github.com/emcfarlane/larking/examples/library/main_test.go:31 +0x1c8
testing.tRunner(0xc0003981a0, 0x1856318)
        /usr/local/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1486 +0x35f
exit status 2
FAIL    github.com/emcfarlane/larking/examples/library  0.268s
```

**Anything else we should know about your project / environment?**

**Comment by puellanivis** [comment]
Go is strictly typed, so you cannot take the `*dynamicpb.Message` and use it as the concrete type that is the equivalent protobuf message.

You can fix this by using the strict type directly, instead of using a dynamic message. You should only use the `dynamicpb` when you do not have the concrete type available directly.

**Comment by emcfarlane** [comment]
@puellanivis Yes the go types are different `*dynamicpb.Message` and `*apipb.Book`. I though the behaviour should be that protobuffer types are respected. Both types are the same underlying type proto type of `larking.examples.library.Book`. 

Does the opposite fail of assigning a go type to a dynamic's type field?
 If this isn't a behaviour issue please close! Thanks.

In my case, I've fixed this by looking up the MessageType before using dynamicpb, e.g.:
```go
mt, err := protoregistry.GlobalTypes.FindMessageByName("larking.examples.library.Book") 
```

**Comment by puellanivis** [comment]
Yes, trying to assign both ways between `*dynamicpb.Message` and `*apipb.Book` will fail because of the strict typing. I tried to look a bit for something that would convert `*dynamicpb.Message` into the concrete underlying type, but I don’t think it exists. The concrete type has to be compiled in, and `dynamicpb` is intentionally supposed to be much more flexible than that, so it would have to return an `error` in case the type were not concretely available anyways.

I’m kind of grasping around here, as I’m not deeply familiar with how `dynamicpb` all works.

**Comment by emcfarlane** [comment]
Maybe the dyanmic protos could wrap the go type, if available? Then the types could be converted easily? I'm guessing this would have some edge cases with one-to-many relation of descriptors to descriptorTypes: https://pkg.go.dev/google.golang.org/protobuf/reflect/protoreflect#hdr-Go_Type_Descriptors

Closing, as I do think it makes sense to panic in this case.

**Comment by puellanivis** [comment]
Yeah, there might be some ways to get it working, but it might be a hefty amount of work to get it right.
