### ISSUE TITLE
protoc-gen-mirco: plugin output is unparseable

### ISSUE THREAD

**Issue by mafa1993** [golang/protobuf#1439]
protoc --proto_path=./  --mirco_out=./ --go_out=./ proto/greeter.proto      
--mirco_out: protoc-gen-mirco: Plugin output is unparseable: hello go 2012\n\350\216\267\345\217\226\345\210\260\347\232\204\345\206\205\345\256\271 \023proto/greeter.proto\032\010\010\003\020\021\030\003\"\000z\357\277\275\003\n

go env

set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=F:\learn\golang\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=F:\learn\golang
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\git仓库\go微服务学习\go\src\go_micro_learn\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build470620846=/tmp/go-build -gno-record-gcc-switches

protoc version 
protoc --version
libprotoc 3.17.3

**Comment by mafa1993** [comment]
syntax = "proto3";

service Greeter {
    rpc Hello(HelloRequest) returns (HelloResponse) {}
}

message HelloRequest {
    string name = 1;
}

message HelloResponse {
    string greeting = 2;
}

**Comment by puellanivis** [comment]
```
--mirco_out: protoc-gen-mirco: Plugin output is unparseable: hello go
```
This line indicates that the problem is in the `protoc-gen-mirco` binary, a binary not supported by this issue board.
