### ISSUE TITLE
The messagev2 method cannot be used to make protoface Messagev1 is converted to protecteflect ProtoMessage

### ISSUE THREAD

**Issue by shenqidebaozi** [golang/protobuf#1443]
I tried to use the messagev2 method to convert message, but it didn't work correctly. It returned me a non nil, empty message, so I couldn't marshal it correctly
```
	v2 := proto.MessageV2(msg)
	resolver := grpcurl.AnyResolverFromDescriptorSourceWithFallback(source)
	m := protojson.MarshalOptions{
		Resolver: anyResolver{resolver},
	}
	b, err := m.Marshal(v2)
```

**Comment by znkr** [comment]
Please provide more details and ideally a small program to reproduce the error you are seeing.
