### ISSUE TITLE
Panic: nil pointer dereference

### ISSUE THREAD

**Issue by gandio12138** [golang/protobuf#1445]
hi， Here is my stack error log:
```
/data/go/pkg/mod/google.golang.org/protobuf@v1.27.1/encoding/protowire/wire.go , line: 450 , function: google.golang.org/protobuf/encoding/protowire.AppendString ] [file: /data/go/pkg/mod/google.golang.org/protobuf@v1.27.1/internal/impl/codec_gen.go , line: 5026 , function: google.golang.org/protobuf/internal/impl.appendStringNoZeroValidateUTF8 ] [file: /data/go/pkg/mod/google.golang.org/protobuf@v1.27.1/internal/impl/encode.go , line: 139 , function: google.golang.org/protobuf/internal/impl.(*MessageInfo).marshalAppendPointer ] [file: /data/go/pkg/mod/google.golang.org/protobuf@v1.27.1/internal/impl/codec_field.go , line: 238 , function: google.golang.org/protobuf/internal/impl.appendMessageInfo ] ]
```
go version
go 1.15.15

**Comment by puellanivis** [comment]
Your stack error log seems to be malformated, and lacking signficant amounts of data from the `panic` that we should be able to use to help point in the direction of the problem.

**Comment by gandio12138** [comment]
this is graylog:

message
{"logTime":"1652039991136318354","showTime":"2022-05-09T03:59:51.136318354+08:00","logLevel":"[ERROR]","message":{"traceId":"","spanId":"","content":"[panic日志:runtime error: invalid memory address or nil pointer dereference [file: /home/jenkins/agent/workspace/go-game-luck-money/src/go_common/common/game_common/utils/util.go , line: 51 , function: go_common/common/game_common/utils.CheckPanic ]      [file: /usr/lib/go/src/runtime/panic.go , line: 969 , function: runtime.gopanic ]      [file: /usr/lib/go/src/runtime/panic.go , line: 212 , function: runtime.panicmem ]      [file: /usr/lib/go/src/runtime/signal_unix.go , line: 742 , function: runtime.sigpanic ]      [file: /usr/lib/go/src/runtime/memmove_amd64.s , line: 175 , function: runtime.memmove ]      [file: /data/go/pkg/mod/google.golang.org/protobuf@v1.27.1/encoding/protowire/wire.go , line: 450 , function: google.golang.org/protobuf/encoding/protowire.AppendString ]      [file: /data/go/pkg/mod/google.golang.org/protobuf@v1.27.1/internal/impl/codec_gen.go , line: 5026 , function: google.golang.org/protobuf/internal/impl.appendStringNoZeroValidateUTF8 ]      [file: /data/go/pkg/mod/google.golang.org/protobuf@v1.27.1/internal/impl/encode.go , line: 139 , function: google.golang.org/protobuf/internal/impl.(*MessageInfo).marshalAppendPointer ]      [file: /data/go/pkg/mod/google.golang.org/protobuf@v1.27.1/internal/impl/codec_field.go , line: 238 , function: google.golang.org/protobuf/internal/impl.appendMessageInfo ]     ]","callPath":"\nUNKNOWN/print_stack.go:70\nUNKNOWN/print_stack.go:24\ngo_common/common/game_common/utils/util.go:51\nruntime/panic.go:969"},"event_id":"","stack":"print_stack.go:70","processid":"Game_Lucky_Money","extra":null}
message_callPath
UNKNOWN/print_stack.go:70
UNKNOWN/print_stack.go:24
go_common/common/game_common/utils/util.go:51
runtime/panic.go:969

**Comment by puellanivis** [comment]
Unfortunately, this stacktrace does not help point any further to what might be going on. In a proper `panic` stacktrace, you’ll see some of the function arguments. Like this:
```
github.com/puellanvivis/project/package.Function({0x0, 0x3ff0000000000000, 0x0, 0x0}, {0x0, 0x0, 0x3ff0000000000000, 0x0})
```

Without the values of the parameters that were on the call-stack, we can’t even take any sort of a guess as to what went wrong. It could be (and often is) some sort of memory corruption. Caused by software, or hardware. And could come from basically any package.

No less, your stack trace cuts off at `google.golang.org/protobuf@v1.27.1/internal/impl/codec_field.go` which 🤷‍♀️ who knows what was calling into this private method.
