### ISSUE TITLE
Create structpb.UnmarshalTo similar to anypb

### ISSUE THREAD

**Issue by salrashid123** [golang/protobuf#1448]
anypb supports an easy way to to unmarshall and set option using the [anypb.UnmarshalTo()](https://pkg.go.dev/google.golang.org/protobuf@v1.28.0/types/known/anypb#hdr-Unmarshaling_an_Any).

This FR is to extend that to `structpb` as well.

My usecase maybe specific but its like this:

Google cloud logging's [AuditLog](https://pkg.go.dev/google.golang.org/genproto@v0.0.0-20220505152158-f39f71e6c8f3/googleapis/cloud/audit#AuditLog) returns a some fields as `structpb.Struct`

```
Request *structpb.Struct `protobuf:"bytes,16,opt,name=request,proto3" json:"request,omitempty"`
```

the data returned has a *string* `@type` field included that defines the message itself

![audit](https://user-images.githubusercontent.com/11149054/167630065-877d77f2-afa4-42bf-9622-e806dc9f8456.png)

the way to parse it now is something likethis:

```golang
g := &storagepb.GetIamPolicyRequest{} //  storagepb "google.golang.org/genproto/googleapis/storage/v1"
iamRequestStruct, err := audit_data.Request.MarshalJSON()
err = protojson.UnmarshalOptions{
    DiscardUnknown: true,
}.Unmarshal(iamRequestStruct, g)
```

which work but i think it'd be easier if `structpb` supported the same format as `anypb`:

```golang
err := structpb.UnmarshalTo(audit_data.Request., &g, proto.UnmarshalOptions{
    DiscardUnknown: true,
})
```

**Comment by puellanivis** [comment]
🤔 Sounds pretty reasonable. I don’t really see any particularly big reason why we should force a JSON round-trip work around.

BUt it _seems_ like there is a disconnect in definitions and generated data. A `structpb` should not be producing a `@type` field, that’s an `anypb` feature. 😕 It just happens that they’re essentially compatible deifnitions.

**Comment by salrashid123** [comment]
Usign the `structpb` here for cloud logging  was done to accomodate arbitrary data (it could send back a protobuf or just standalone json, i think)

```
field Request *structpb.Struct
The operation request. This may not include all request parameters, such as those that are too large, privacy-sensitive, or duplicated elsewhere in the log record. It should never include user-generated data, such as file contents. When the JSON object represented here has a proto equivalent, the proto name will be indicated in the `@type` property.
```

the idea there is to inspect the data and then apply specific treatment (its awkward)

if we were just dealign with proto, sending `anypb` and using its [functions](https://pkg.go.dev/google.golang.org/protobuf/types/known/anypb#hdr-Unmarshaling_an_Any)  would be the way as you mentioned.

the more i think about this...this FR is to accomodate a specific apis' idiosyncracy so i'm ok with the workaround and closing

---

for ref, cloud logging also allows for mutiple assignable types to get sent down (eg, [logging.LogEntry](https://pkg.go.dev/google.golang.org/genproto/googleapis/logging/v2#LogEntry) allows for:

```
Resource  `protobuf:"bytes,8,opt,name=resource,proto3" json:"resource,omitempty"`
	// The log entry payload, which can be one of multiple types.
	//
	// Types that are assignable to Payload:
	//	*LogEntry_ProtoPayload
	//	*LogEntry_TextPayload
	//	*LogEntry_JsonPayload
```

which if its a [LogEntry.ProtoPayload](https://pkg.go.dev/google.golang.org/genproto/googleapis/logging/v2#LogEntry_ProtoPayload) is an `anypb.Any`  and i can deal with that easily with the anypb functions...

**Comment by puellanivis** [comment]
Hm… it seems that the `anypb` `UnmarshalTo` is done via defering the actual unmarshalling until that call… the JSON version skips all of that by loading the resolved message and unmarshalling the JSON directly to that message rather than having at any point the `anypb.Any` struct instantiated.

I don’t think there’s any standards compliant way we could really ensure that we could treat this idiosyncratic use of `structpb.Struct` conflated with `anypb.Any`.

One should be able to write something using `protoreflect` if one _really_ wants to avoid a round-trip marshal/unmarshal. But yeah, I think this is a kind of one-off case, and specific to this API, so the workaround is more reasonable than trying to write a general purpose `protoreflect` based already-unmarshaled `structpb.Struct` into an arbitrary other type like `anypb.Any` does.

**Comment by salrashid123** [comment]
thanks.  i'll stick with the workaround.  for this specific api, i'll ask to document the worksarounds in cloud logging docs (in various languages, if feasible even!). 

fyi, envoyproxy (which in in cpp) uses something called [typed_config](https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/extension#extension-configuration) declarations which i think has to be anypb's.
