### ISSUE TITLE
googleapis/google/type

### ISSUE THREAD

**Issue by peter-edge** [golang/protobuf#145]
I'm pretty sure this is pushing my luck here a bit, so this will be closed pretty quickly, but these are REALLY useful sometimes: https://github.com/googleapis/googleapis/tree/master/google/type

Re: eliminating fragmentation

**Comment by dsymonds** [comment]
Yeah, not going to happen here. Everything in that repo probably needs mapping to, say, google.golang.org/googleapis/blah instead.
