### ISSUE TITLE
Handling of "Any" types in jsonpb could be better

### ISSUE THREAD

**Issue by ravenblackx** [golang/protobuf#1450]
# Problem

We have a message with Any fields, where we only care to unmarshal the types that we recognize. In the current implementation, jsonpb.Unmarshaler allows for "AllowUnknownFields: true", but does not have anything similar for unknown Any types.

Unmarshaling an unknown Any type errors out of the whole unmarshal.

We can set an AnyResolver, but there's no simple way to try the default behavior first and *fall back* to the AnyResolver (which would allow me to just return an Empty{})

We can implement the other path inside our AnyResolver, calling `protoregistry.GlobalTypes.FindMessageByURL(typeURL)` ourselves, but then the AnyResolver has to return a proto.Message not a protoreflect.Message. messageType.New() would do the trick here if it wasn't for mismatched library versions, but even if it worked, this is getting to be a moderately sized amount of code to indicate "just don't error out if you hit an unrecognized type in Any".

# Solutions that would help

1. Additional option to jsonpb.Unmarshaler `IgnoreUnrecognizedAnyFields: true`
2. AnyResolver returns a type instead of a message (it gets converted to a type moments later anyway)
3. Some way of having AnyResolver act as a fallback rather than it taking priority over the registry
4. Some way of having AnyResolver, when taking priority, easily try the default behavior and then only on error do custom behavior (i.e. instead of having a branch that's taken when there is no AnyResolver, have an exported default AnyResolverDefault that performs the behavior of that branch - that way a replacement AnyResolver could choose to first call AnyResolverDefault, intercept errors and do custom behavior.

**Comment by cybrcodr** [comment]
Use [protojson.UnmarshalOptions](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson#UnmarshalOptions) instead of the deprecated `jsonpb` package instead.

You'll still need to write your own Resolver but can use `protoregistry` package for message types that you want out of the registry.  As for "just don't error out if you hit an unrecognized type in Any", you'll need to provide some replacement message type for the "unrecognized type".

**Comment by ravenblackx** [comment]
Ah, if we're using a deprecated api then that's likely the crux of the problem. Thanks!

**Comment by fedemengo** [comment]
```go
type ProtoResolver interface {
	protoregistry.MessageTypeResolver
	protoregistry.ExtensionTypeResolver
	RegisterMessage(mt protoreflect.MessageType) error
}

var protoResolver ProtoResolver

func init() {
	protoResolver = new(protoregistry.Types)

	type1 := protoimpl.X.MessageTypeOf(&proto.Type1{})
	type2 := protoimpl.X.MessageTypeOf(&proto.Type2{})

	protoResolver.RegisterMessage(type1)
	protoResolver.RegisterMessage(type2)
}

func f() {
	unmarshaler := protojson.UnmarshalOptions{
		Resolver: protoResolver,
	}

        if err := unmarshaler.Unmarshal(body, &data); err != nil {
		return fmt.Errorf("cannot unmarshal: %w", err)
	}
}
```
