### ISSUE TITLE
Deprecated: Use the "google.golang.org/protobuf/proto" package instead.

### ISSUE THREAD

**Issue by Banyc** [golang/protobuf#1451]
**What version of protobuf and what language are you using?**
Version: (e.g., `v1.1.0`, `89a0c16f`, etc)

libprotoc 3.17.3

either proto2 or proto3

**What did you do?**
If possible, provide a recipe for reproducing the error.
A complete runnable program is good with `.proto` and `.go` source code.

```
protoc -I./ --go_out=./ xxx.proto
```

```go
import "google.golang.org/protobuf/proto"
```

```go
body := &aaa.yyy{}
proto.Unmarshal(bytes, body)
                       ^missing method ProtoReflect
```

**What did you expect to see?**

no errors

**What did you see instead?**

`body` is `missing method ProtoReflect`

The `import` in `xxx.pb.go`

```go
import proto "github.com/golang/protobuf/proto"
```

is `Deprecated: Use the "google.golang.org/protobuf/proto" package instead.`

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment?**

Linux

**Comment by Banyc** [comment]
`xxx.pb.go` says `// DO NOT EDIT!`

**Comment by Banyc** [comment]
For those who is hitting the same issue:

It turns out I was using a way out-of-dated `protoc`.
Latest compilers are here <https://github.com/protocolbuffers/protobuf/releases>.
The tool is required to installed manually tho.

**Comment by Banyc** [comment]
@puellanivis Thanks for the speedy reply!

I then just followed the guidance again to solve the `protoc-gen-go` problem by

```
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
```

according to <https://developers.google.com/protocol-buffers/docs/gotutorial#compiling-your-protocol-buffers> but the `import` is still the deprecated `"github.com/golang/protobuf/proto"`

**Comment by Banyc** [comment]
It seems like the guidance (the link above) is not relevant anymore since it does not mention `protoc-gen-grpc`

**Comment by puellanivis** [comment]
No, the listed package is the current package relevant to the document.

When you type `protoc-gen-go --version` what do you get? If it doesn’t say `1.28.0` or prints some sort of error message, then you’re not using the most recent version, and it’s likely you do not have your `$GOPATH/bin` directory in your `PATH` ahead of wherever your package-manager-installed `protoc-gen-go` binary is installed.

**Comment by Banyc** [comment]
@puellanivis Thanks for the hints and suggestions. I found the `which protoc-gen-go` sits in a weird location.

**Comment by puellanivis** [comment]
`protoc-gen-go` is a `protoc` plugin, and it is not intended to be executed directly from the command-line, but rather through `protoc --go_opt=`

The way the `protoc` plugin system works, is that it invokes the plugin, and writes the binary protobuf file descriptor to its standard in, and the plugin then takes that compiled interpretation and dumps out the go code. So, if you attempt to start it from the command-line directly, it’s just going to sit there and wait for input, the same as `cat`.

**Comment by samnayak1** [comment]
But my plugin is still importing deprecated `github.com/golang/protobuf/proto` instead of the new one. I think I initially installed the old plugin using `go get -u github.com/golang/protobuf/proto` but I deleted that file. Infact, I reinstalled the whole Go binary and executables and reinstalled it including 

```
sudo apt install protbuf-compiler
sudo apt install golang-goprotobuf-dev
go install google.org/protobuf/cmd/protogen-gen-go@latest
go install google.golang.org/gprc/cmd/protoc-gen-go-grpc@latest
export PATH="$PATH:$(go env GOPATH)/bin"
```

to find the same problem when I enter 

`protoc --proto_path=proto proto/*.proto --go_out=plugins=grpc:pb`

on 
```
syntax="proto3";
message Computer{
     string name=1;
     uint32 cores=2;
     uint32 min_ghz=3;
     uint32 max_ghz=4;
}
```

```
import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)
// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package 
```


versions:
```
protoc --version libprotoc 3.6.1
protoc-gen-go-grpc --version protoc-gen-go-grpc 1.2.0
go version  go1.21.1 linux/amd64
```

**Comment by puellanivis** [comment]
Note, that because of your `$PATH` ordering, you are getting `/usr/bin/protoc-gen-go` before your `google.golang.org/gprc/cmd/protoc-gen-go-grpc@latest` binary.

You need to uninstall `golang-goprotobuf-dev` in order to remove it from your path. Or, you could reorder your `$PATH` to put `/home/hp/go/bin` ahead of `/usr/bin`.

**Comment by samnayak1** [comment]
Thank you so much @puellanivis it works
