### ISSUE TITLE
options: add json_tag option for overwrite omitempty

### ISSUE THREAD

**Issue by tonybase** [golang/protobuf#1452]
Overwrite JSON naming convention (snake_case, camelCase or PascalCase):
eg:
```
-json_tag=camelCase
-json_tag=omitempty,nocase
-json_tag=omitempty,camelCase // snake_case/PascalCase
```

Later we maybe use [go-json-experiment](https://github.com/go-json-experiment/json) instead of protojson.

**Comment by puellanivis** [comment]
We do not intend to and any of these options: https://github.com/golang/protobuf/issues/1164 the json tags themselves are largely regarded as a mistake in the first place. And we will not be rolling out any “new” features unilaterally, like being able to change the casing on JSON tags, or removing `omitempty`, these features must be done as a part of the specification _first_ with the main protobuf project.

We do however intend to use the new currently experimental JSON library when it has stabilized, and brought into the standard package.

**Comment by tonybase** [comment]
OK, thanks for your reply.

**Comment by NateRoiger** [comment]
The language specification mentions emitting default values.

> **Emit fields with default values:** Fields with default values are omitted by default in proto3 JSON output. An implementation may provide an option to override this behavior and output fields with their default values.

https://developers.google.com/protocol-buffers/docs/proto3#json_options

Should this ticket can be re-opened?

**Comment by cybrcodr** [comment]
See [protojson.MarshalOptions.EmitUnpopulated](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson#MarshalOptions).
