### ISSUE TITLE
JSON serialisation for repeated WKT wrapper messages

### ISSUE THREAD

**Issue by srikrsna** [golang/protobuf#1454]
Given a message like,
```proto
message FloatTest {
  repeated google.protobuf.FloatValue f32 = 1;
}
```
And the test,
```go
func TestProtoJsonFloat(t *testing.T) {
	var f testv1.FloatTest
	f.F32 = []*wrapperspb.FloatValue{
		nil,
		{},
	}
	data, err := protojson.Marshal(&f)
	if err != nil {
		t.Fatal(err)
	}
	s := string(data)
	t.Log(s)
}
```
prints
```json
{"f32":[0,0]}
```
Shouldn't this be
```json
{"f32":[null,0]}
```

**Comment by neild** [comment]
In the protobuf data model, repeated fields can't contain missing/unset values. The Go generated code uses `nil` values to indicate unset non-repeated fields, but inside a repeated message field a `nil` value is just an empty message.
