### ISSUE TITLE
zero check for timestamppb

### ISSUE THREAD

**Issue by abdullahskartal** [golang/protobuf#1457]
**Is your feature request related to a problem? Please describe.**

I would like to check zero value for timestamppb but it seems not possible.

```
import  "google.golang.org/protobuf/types/known/timestamppb"

func main() {
	ts := &timestamppb.Timestamp{}
	fmt.Println(ts.IsValid()) // True

	fmt.Println(ts.CheckValid()) // nil

	fmt.Println(ts.AsTime().IsZero()) // False

	if ts == nil {
		fmt.Println("kartal") // not printing
	}

	fmt.Println(ts.AsTime()) // 1970-01-01 00:00:00 +0000 UTC
}
```

I believe we shouldn't check if time is unix default time.

**Describe the solution you'd like**
1) We can create IsZero function as go's Time module and check default or zero values.
2) If value is the default Unix timestamp we can send it as zero when casting to the Time module.
3) Changing default value 1970 to zero (i'm not fan of this)

**Comment by cybrcodr** [comment]
I take it that by "zero value" of the Timestamp proto, you meant that both the `seconds` and the `nanos` proto fields are set to 0.  Why not just compare those fields directly?  i.e.

```
func main() {
	ts := &timestamppb.Timestamp{}
	fmt.Println(ts.GetSeconds() == 0 && ts.GetNanos() == 0)  // true
	fmt.Println(ts.AsTime().Unix() == 0)  // true
}
```

If you convert it to Go's Time type, you can use `Unix()` and compare against 0.

**Comment by molon** [comment]
But how about `nil`? ` nil != &timestamppb.Timestamp{} `

```
func (x *Timestamp) AsTime() time.Time {
	if x == nil {
		return time.Time{}
	}
	return time.Unix(int64(x.GetSeconds()), int64(x.GetNanos())).UTC()
}
```

**Comment by molon** [comment]
> That code is indeed buggy, but where are you getting that code from? That’s not what this project has: https://github.com/protocolbuffers/protobuf-go/blob/v1.28.0/types/known/timestamppb/timestamp.pb.go#L206-L208
> 
> ```go
> func (x *Timestamp) AsTime() time.Time {
> 	return time.Unix(int64(x.GetSeconds()), int64(x.GetNanos())).UTC()
> }
> ```

Sorry, I originally meant to express that using `time.Time{}` and `(*timestamppb.Timestamp)nil` for equality is a more reasonable design.
But I suddenly don't think so now. Since it is named `timestamp`, it should default 0.

**Comment by adg** [comment]
I think that the `Timestamp.AsTime` method is buggy. If the `Timestamp` is `nil` then it should return a `time.Time{}` (the zero value), not the Unix epoch time in UTC. A zero `time.Time` is different to the Unix epoch time (a totally valid `time.Time`, and a valid `timestamppb.Timestamp`). The current behavior does not permit the `*timestamppb.Timestamp` to express a zero time, when it has a perfectly valid way to do so (`nil`).

See: https://go.dev/play/p/hSdxcsC-laJ

I propose changing the `AsTime` method to this:
```
// AsTime converts x to a time.Time.
func (x *Timestamp) AsTime() time.Time {
        if x == nil {
                return time.Time{}
        }
        return time.Unix(int64(x.GetSeconds()), int64(x.GetNanos())).UTC()
}
```

**Comment by molon** [comment]
> I think that the `Timestamp.AsTime` method is buggy. If the `Timestamp` is `nil` then it should return a `time.Time{}` (the zero value), not the Unix epoch time in UTC. A zero `time.Time` is different to the Unix epoch time (a totally valid `time.Time`, and a valid `timestamppb.Timestamp`). The current behavior does not permit the `*timestamppb.Timestamp` to express a zero time, when it has a perfectly valid way to do so (`nil`).
> 
> See: https://go.dev/play/p/hSdxcsC-laJ
> 
> I propose changing the `AsTime` method to this:
> 
> ```
> // AsTime converts x to a time.Time.
> func (x *Timestamp) AsTime() time.Time {
>         if x == nil {
>                 return time.Time{}
>         }
>         return time.Unix(int64(x.GetSeconds()), int64(x.GetNanos())).UTC()
> }
> ```

In actual use, it is indeed more convenient. 👍
Imagine in the scenario of json marshal/unmarshal:
```
	type A struct {
		DeletedAt *tspb.Timestamp `json:"deletedAt,omitempty"`
	}
	type B struct {
		DeletedAt time.Time `json:"deletedAt,omitempty"`
	}
```
In an expressive sense, `A{} == B{}` is definitely more convenient, otherwise the conversion statement must be written separately for each time.
And if `omitempty` is used, things get complicated when we want A's `marshal` to be `unmarshal` to B. This is extremely painful when we customize json `marshaler/unmarshaler`.
Even if I look at the meaning of the `DeletedAt` field of `A` alone, how can I express that it has not been deleted? In the current situation, perhaps I should write as `DeletedAt: tspb.New(time.Time{})`.

Of course, it is not advisable to modify the original `AsTime` method, maybe a new method can be added, such as `ToTime`

**Comment by puellanivis** [comment]
The value of an unset or not-appearing Message is its zero value, for a `tspb` that is the unix epoch, not the golang epoch.

https://go.dev/play/p/FYCPo92SNgr this invariant must be true, but the proposed “if x == nil { return time.Time{} }` would fail it.

It would be extremely weird for `GetSeconds()` and `GetNanos()` to both return `0` and then the `AsTime()` to return something other than what those zero values mean: the unix epoch.

Worst, it would be inconsistent with all the other big-4 languages. Having one language that ascribes a different semantic to a not-appearing `Timestamp` than every other language is a great way to cause bugs.

> Even if I look at the meaning of the DeletedAt field of A alone, how can I express that it has not been deleted?

Not appearing (the `nil` value) is the same semantic as the default value. There is no reason to treat midnight at the start of `0001-01-01` as a “it has not been deleted” anymore than the unix epoch.

**Comment by adg** [comment]
Makes sense to me. I withdraw my objections.

**Comment by molon** [comment]
> The value of an unset or not-appearing Message is its zero value, for a `tspb` that is the unix epoch, not the golang epoch.
> 
> https://go.dev/play/p/FYCPo92SNgr this invariant must be true, but the proposed “if x == nil { return time.Time{} }` would fail it.
> 
> It would be extremely weird for `GetSeconds()` and `GetNanos()` to both return `0` and then the `AsTime()` to return something other than what those zero values mean: the unix epoch.
> 
> Worst, it would be inconsistent with all the other big-4 languages. Having one language that ascribes a different semantic to a not-appearing `Timestamp` than every other language is a great way to cause bugs.
> 
> > Even if I look at the meaning of the DeletedAt field of A alone, how can I express that it has not been deleted?
> 
> Not appearing (the `nil` value) is the same semantic as the default value. There is no reason to treat midnight at the start of `0001-01-01` as a “it has not been deleted” anymore than the unix epoch.

You are right. My thinking is too one-sided.

**Comment by puellanivis** [comment]
No problems. Human brains be like that.

**Comment by Aravindharigoppula** [comment]
so, whats concluded here to check for a nil time? is it to compare GetSeconds() and GetNanos() against zero?

**Comment by blackgreen100** [comment]
@Aravindharigoppula use `IsValid` or `CheckValid` before `AsTime`. I wrote a summary here: https://stackoverflow.com/a/78005115/4108803
