### ISSUE TITLE
Error in compiling android-s-qpr3-beta-1

### ISSUE THREAD

**Issue by Aquarices** [golang/protobuf#1458]
Hi Engs:
When I sync the code from AOSP of android-s-qpr3-beta-1 and start to build the code. I got some error.
error: external/golang-protobuf/Android.gen.bp:1252:1: "golang-protobuf-reflect-protorange" depends on undefined module "go-cmp"
error: external/golang-protobuf/Android.gen.bp:1252:1: "golang-protobuf-reflect-protorange" depends on undefined module "go-cmp-cmpopts" 
I tried the command "go get -u github.com/google/go-cmp/cmp" but the issue is still there.
---
https://android.googlesource.com/platform/external/golang-protobuf/+/refs/heads/android-s-qpr3-beta-1

**Comment by lfolger** [comment]
Hi Aquarices,

this look to be an issue with the AOSP and not with go protobufs.

I recommend reporting the issue there.
