### ISSUE TITLE
json_name is not working in java protobuff serialization with spring boot maven.

### ISSUE THREAD

**Issue by dirisina-abhiram** [golang/protobuf#1459]
Hi,

I'm facing issue with json_name field not working as part of json serialization when used the following modules with spring boot. : 

Versions : 

`<java.version>1.8</java.version>
        <protobuf-java.version>3.21.1</protobuf-java.version>
        <protobuf-java-format.version>1.4</protobuf-java-format.version>`

jars : com.google.protobuf:protobuf-java:3.21.1, 
com.googlecode.protobuf-java-format:protobuf-java-format:1.4

Plugin : org.xolstice.maven.plugins
<plugin>
                <groupId>org.xolstice.maven.plugins</groupId>
                <artifactId>protobuf-maven-plugin</artifactId>
                <version>0.6.1</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                            <goal>compile-js</goal>
                        </goals>
                        <configuration>
                            <protocArtifact>com.google.protobuf:protoc:3.21.1:exe:${os.detected.classifier}
                            </protocArtifact>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
 
Spring boot message convertor : ProtobufHttpMessageConverter

Can you please let me know if `json-name` field option at all works in java serialization or works only in go.
Appreciate any pointers in this regard.

**Comment by puellanivis** [comment]
It seems that your problem relates to the Java implementation of protobuf, this repo is narrowly for only Golang protobuf concerns.
