### ISSUE TITLE
Generator code requires Go 1.6.

### ISSUE THREAD

**Issue by tswast** [golang/protobuf#146]
The commit https://github.com/golang/protobuf/commit/c75fbf01dc6cb73649c4cd4326182c3e44aa9dbb uses `strings.LastIndexByte`, which I believe was introduced in Go 1.6. We should update the README to say Go 1.6 is required, if this requirement was intentional.

**Comment by tswast** [comment]
This broke the Go sample build in the main protobuf repo. See: https://github.com/google/protobuf/issues/1305

**Comment by dsymonds** [comment]
My mistake. I thought that function had been there for much longer. Easy enough to fix.

Weird that it took a week for this to manifest...

**Comment by dsymonds** [comment]
`api/go1.5.txt` in the Go tree implies that `strings.LastIndexByte` was actually added in Go 1.5.

**Comment by tswast** [comment]
Okay, either way the README says Go 1.4, so we should update it. In the meantime, I'll get the protobuf repo using later versions of Go.

**Comment by dsymonds** [comment]
Yeah, automated CI systems should probably just stick with the latest stable Go release.

I'll update the README. I think it's reasonable to expect at least Go 1.5 these days.

**Comment by dsymonds** [comment]
Actually, it's so easy to leave it supporting Go 1.4 I'll do that instead.
