### ISSUE TITLE
 (constant -4 of type uintptr) overflows uintptr

### ISSUE THREAD

**Issue by 13567436138** [golang/protobuf#1465]
**What version of protobuf and what language are you using?**
Version: (e.g., `v1.1.0`, `89a0c16f`, etc)

**What did you do?**
If possible, provide a recipe for reproducing the error.
A complete runnable program is good with `.proto` and `.go` source code.

**What did you expect to see?**
# google.golang.org/protobuf/internal/impl
../../../../go/pkg/mod/google.golang.org/protobuf@v1.26.0/internal/impl/pointer_unsafe.go:141:16: unsafe.Sizeof(unsafe.Pointer(nil)) - unsafe.Sizeof((MessageState literal)) (constant -4 of type uintptr) overflows uintptr
**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment?**

**Comment by 13567436138** [comment]
```
package main

import (
        "github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm"
        "github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/types"
        "github.com/golang/protobuf/proto"
)

func main() {
        proxywasm.SetVMContext(&vmContext{})
}

type vmContext struct {
        // Embed the default VM context here,
        // so that we don't need to reimplement all the methods.
        types.DefaultVMContext
}

// Override types.DefaultVMContext.
func (*vmContext) NewPluginContext(contextID uint32) types.PluginContext {
        return &pluginContext{}
}

type pluginContext struct {
        // Embed the default plugin context here,
        // so that we don't need to reimplement all the methods.
        types.DefaultPluginContext
}

// Override types.DefaultPluginContext.
func (*pluginContext) NewHttpContext(contextID uint32) types.HttpContext {
        return &httpHeaders{contextID: contextID}
}

type httpHeaders struct {
        // Embed the default http context here,
        // so that we don't need to reimplement all the methods.
        types.DefaultHttpContext
        contextID uint32
}

type Metadata struct{
	filter_metadata []map[string]Struct
}

// Override types.DefaultHttpContext.
func (ctx *httpHeaders) OnHttpRequestHeaders(numHeaders int, endOfStream bool) types.Action {
        path :=[]string{"plugin_vm_id"}
        data,err := proxywasm.GetProperty(path) 
        if err != nil {
                proxywasm.LogCritical("failed to get property")
        }

        proxywasm.LogCriticalf("property(%s): %s", "plugin_vm_id",string(data))
        
        path=[]string{"route_metadata"}
        data,err = proxywasm.GetProperty(path)
        
        if err != nil {
                proxywasm.LogCritical("failed to get property")
        }
        var data2 Metadata;
        err = proto.Unmarshal(data, data2)
        proxywasm.LogCriticalf("property(%s): %s", "route_metadata",string(data2.(type)))
        return types.ActionContinue
}



```

**Comment by puellanivis** [comment]
The report here is fairly incomplete. It’s impossible to tell what might be happening here. The particular message you report could maybe be a result of the arch/os combinationation that you’re trying to use, but you have not included any information about what `GOOS` or `GOARCH` you’re using, nor what version of go you’re using. And there are no repro steps given.

Also, the included code is both incomplete, and erroneous. e.g. `proto.Unmarshal(…)` should only ever take a pointer as its second argument, passing in a non-pointer of type `Metadata` should not work. As well, the second argument needs to be a protobuf Message type, and there is no indication here that type `Metadata` is actually a generated protobuf type.
