### ISSUE TITLE
Publish protoc-gen-go binaries for arm64

### ISSUE THREAD

**Issue by anuraaga** [golang/protobuf#1466]
Currently, the protoc-gen-go published binaries only include amd64 and 386

https://github.com/protocolbuffers/protobuf-go/releases

It would be great to include arm64 as well, at least for linux and darwin where it is getting more common now. It would mostly be a change to this line

https://github.com/protocolbuffers/protobuf-go/blob/master/integration_test.go#L379

If the GitHub actions is the only way tests are run in the project, then there wouldn't be a significant change in testing, because darwin and windows are already not tested.

https://github.com/protocolbuffers/protobuf-go/blob/master/.github/workflows/test.yml#L10

if the tests are run externally as well in a way I can't see that supports those platforms, e.g. kokoro, then it would need to be configured to ensure coverage doesn't go down with the addition of the arch.

**Comment by lfolger** [comment]
New patch release including arm64 binaries is now available at https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.28.1

**Comment by stapelberg** [comment]
I have successfully verified that the darwin/arm64 protoc-gen-go starts up on my M1 macbook air, and that the linux/arm64 protoc-gen-go starts up on my Raspberry Pi 4 👍

**Comment by anuraaga** [comment]
Thanks for the quick response, this is awesome!
