### ISSUE TITLE
descriptorpb has not been updated since protoc v3.16.0

### ISSUE THREAD

**Issue by jhump** [golang/protobuf#1478]
The `google.golang.org/protobuf/types/descriptorpb` package has not been updated in 17 months.

In that time, several changes have been made to `descriptor.proto`:
* [March 22, 2021](https://github.com/protocolbuffers/protobuf/blame/3322c0b92a5001ade92608d75891d63c749d624d/src/google/protobuf/descriptor.proto#L503)
* [February 1, 2022](https://github.com/protocolbuffers/protobuf/blame/3322c0b92a5001ade92608d75891d63c749d624d/src/google/protobuf/descriptor.proto#L616-L619)
* [June 21, 2022](https://github.com/protocolbuffers/protobuf/blame/3322c0b92a5001ade92608d75891d63c749d624d/src/google/protobuf/descriptor.proto#L94-L95)
* [July 8, 2022](https://github.com/protocolbuffers/protobuf/blame/3322c0b92a5001ade92608d75891d63c749d624d/src/google/protobuf/descriptor.proto#L923-L933)

**Comment by jhump** [comment]
Actually, those last two are still unreleased. But the latest protoc release, v21.5, does have the first two changes above. It would be nice to re-generate `descriptorpb` so latest of this repo matches latest release of protoc.

**Comment by stapelberg** [comment]
Fixed with https://go.googlesource.com/protobuf/+/692f4a24f8dc0d375508fc41e657920d411b5b68, thank you!
