### ISSUE TITLE
jsonpb: Unmarshal error for Oneof field with Capital First Letter

### ISSUE THREAD

**Issue by awalterschulze** [golang/protobuf#148]
In test_objects.proto I changed the field names to have a first letter as a capital.

```proto
message MsgWithOneof {
  oneof union {
    string Title = 1;
    int64 Salary = 2;
  }
}
```

This produces an error
```
unknown field "salary" in jsonpb.MsgWithOneof
```

So technically the fieldname isn't salary anymore, it is Salary, but this is what it marshals to and this is what the tags say it should be

```go
type MsgWithOneof_Salary struct {
	Salary int64 `protobuf:"varint,2,opt,name=Salary,json=salary,oneof"`
}
```

**Comment by stevvooe** [comment]
We actually saw this issue, as well. It was very odd, as it only worked with the specific package from the unit tests. Once `MsgWithOneof` is pulled out of the package, it will not deserialize the json with a oneof field.

If more details are required, please let me know.

cc @aluzzardi

**Comment by dsymonds** [comment]
jsonpb is specified to accept either the .proto original name, or the camelCase name. In this case, that means the acceptable set should be {`Salary`,`salary`}. It does indeed sound like a bug.

It looks like a bug specific to oneofs.
