### ISSUE TITLE
Is this function implemented?

### ISSUE THREAD

**Issue by Super-zhw** [golang/protobuf#1480]
Hello, it has been 4 years, has this [#681](https://github.com/golang/protobuf/issues/681) function been implemented?

**Comment by puellanivis** [comment]
The issue linked to was closed as “will not implement”. There is no particular reason why anyone should need to be able to compile multiple `proto` files into one `pb.go` file. Go allows for multiple files to exist in one package, and so one should just generate the several `pb.go` files to the same package. Done.

**Comment by Super-zhw** [comment]
thanks
