### ISSUE TITLE
data race in proto.Marshal

### ISSUE THREAD

**Issue by wy7980** [golang/protobuf#1492]
WARNING: DATA RACE
Read at 0x00c000290f10 by goroutine 14:
  google.golang.org/protobuf/internal/impl.sizeStringPtr()
      /home/xxxx/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/codec_gen.go:5043 +0x7c
  google.golang.org/protobuf/internal/impl.(*MessageInfo).sizePointerSlow()
      /home/xxxx/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/encode.go:79 +0x25a
  google.golang.org/protobuf/internal/impl.(*MessageInfo).sizePointer()
      /home/xxxx/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/encode.go:56 +0x75
  google.golang.org/protobuf/internal/impl.sizeMessageInfo()
      /home/xxxx/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/codec_field.go:232 +0xaa
  google.golang.org/protobuf/internal/impl.(*MessageInfo).sizePointerSlow()
      /home/xxxx/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/encode.go:79 +0x25a
  google.golang.org/protobuf/internal/impl.(*MessageInfo).sizePointer()
      /home/xxxx/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/encode.go:56 +0x75
  google.golang.org/protobuf/internal/impl.(*MessageInfo).size()
      /home/xxxx/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/encode.go:40 +0x67
  google.golang.org/protobuf/internal/impl.(*MessageInfo).size-fm()
      /home/xxxx/go/pkg/mod/google.golang.org/protobuf@v1.28.1/internal/impl/encode.go:33 +0x67
  google.golang.org/protobuf/proto.MarshalOptions.marshal()
      /home/xxxx/go/pkg/mod/google.golang.org/protobuf@v1.28.1/proto/encode.go:156 +0x1ab
  google.golang.org/protobuf/proto.MarshalOptions.MarshalAppend()
      /home/xxxx/go/pkg/mod/google.golang.org/protobuf@v1.28.1/proto/encode.go:125 +0xca
  github.com/golang/protobuf/proto.marshalAppend()
      /home/xxxx/go/pkg/mod/github.com/golang/protobuf@v1.5.2/proto/wire.go:40 +0xed
  github.com/golang/protobuf/proto.Marshal()

I got the data race in proto.Marshal() for goroutines, is the function safe for goroutine?
ps: when use sync.Mutex to lock the marshal, it is ok.

**Comment by puellanivis** [comment]
It would be more helpful to see the full output of the race detected. You’ve posted the READ part of the data race, but not where the coincident WRITE happens.

What I think is going on is that you’re spinning off a Marshal in a goroutine, and then modifying the underlying message value in parallel. That would not be thread safe. But it’s difficult to tell exactly what’s wrong here. Like I said, it _looks_ like from the code that is triggering the read, that this is happening because you’re changing an underlying `Field *string` from a proto2 message?

**Comment by wy7980** [comment]
>Yes, I have solved the problem. It's not the problem of `Marshal()`, but the assignment of protobuf message. Thanks for your reply.
