### ISSUE TITLE
Cannot send a proto message without a client

### ISSUE THREAD

**Issue by evgenipetrov9** [golang/protobuf#1493]
I'm trying to send a proto message manually so I can skip a giant switch to determine the type of the request via reflect.  
The idea is to make it completely dynamic.
Here's a server interceptor that reproduces the issue, but not a full example since you need a proto file, etc.  
```go
func MustJSONDecode(b []byte, i interface{}) {
	err := json.Unmarshal(b, i)
	if err != nil {
		panic(err)
	}
}

func serverInterceptor(ctx context.Context,
	req interface{},
	info *grpc.UnaryServerInfo,
	handler grpc.UnaryHandler) (interface{}, error) {
	start := time.Now()
	data, err := json.Marshal(req)
	if err != nil {
		logrus.Errorf("cannot marshal")
		return handler(ctx, req)
	}
	// Get the reflect value of the request
	// so we can find the message type
	request := reflect.ValueOf(req)
	p := reflect.New(request.Type()).Interface()
	MustJSONDecode(data, p)
	// Get the MessageType from a string
	mt, err := protoregistry.GlobalTypes.FindMessageByName(protoreflect.FullName(strings.Trim(fmt.Sprintf("%T", p), "*")))
	if err != nil {
		logrus.Errorf("cannot find proto message: %s", err.Error())
		return handler(ctx, req)
	}
	// Create an empty Proto Message from the type
	protom := mt.New()
	// We need a proto message
	protomessage := protom.Interface()
	// Unmarshal the previously exported data into the empty message
	err = protojson.Unmarshal(data, protomessage)
	if err != nil {
		logrus.Errorf("cannot unmarshal: %s", err.Error())
		return handler(ctx, req)
	}
	logrus.Warnf("1: %T, %#v", p, p)
	logrus.Warnf("2: %T, %#v", req, req)
	logrus.Warnf("3: %T, %s", req, data)
	// Create a connection so we can send a message
	// without the client
	conn, err := grpc.Dial("localhost:8000", grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		logrus.Errorf("cannot dial: %s", err.Error())
		return handler(ctx, req)
	}
	var unaryStreamDesc = &grpc.StreamDesc{ServerStreams: false, ClientStreams: false}
	stream, _ := grpc.NewClientStream(ctx, unaryStreamDesc, conn, info.FullMethod)
	// Try to send the message manually
	// THIS IS WHERE IT ERRORS
	err = stream.SendMsg(protomessage)
	if err != nil {
		logrus.Errorf("cannot send: %s", err.Error())
		return handler(ctx, req)
	}
	h, err := handler(ctx, req)
	if !strings.Contains(fmt.Sprintf("%T", req), "health") {
		logrus.Warnf(
			"Request - Method:%s   Duration:%s    Error:%v\n",
			info.FullMethod,
			time.Since(start),
			err)
	}
	return h, err
}
```
Output:  
```
[WARN] 1: **proto_stubs.MyRequest, (**proto_stubs.MyRequest)(0xc0000100b8)                                  
[WARN] 2: *proto_stubs.MyRequest, &proto_stubs.MyRequest{Key:\"Testkey\", XXX_NoUnkeyedLiteral:struct {}{}, XXX_un
recognized:[]uint8(nil), XXX_sizecache:0}                                                                                                                                                              
[WARN] 3: *proto_stubs.MyRequest, {\"Key\":\"Testkey\"}  
[ERROR] cannot send: rpc error: code = Internal desc = grpc: error while marshaling: failed to marshal, message is *impl.messageIfaceWrapper, want proto.Message
```
The error from Send(): `cannot send: rpc error: code = Internal desc = grpc: error while marshaling: failed to marshal, message is *impl.messageIfaceWrapper, want proto.Message`  
It's weird, since the `protomessage` variable IS a proto.Message, in fact if I try to cast it, the linter complains that it's already from the same type.
I've tried to convert it to a V1 message, but it panics with a nil pointer error on Send() in that case.  
  
I know the code doesn't make much sense, but this is an attempt at an Minimum Reproducible Example, in reality what I'm trying to do is record the incoming GRPC proto messages (success) and try to reconstruct them by using protoregistry (seems okay) and send them without a client (fail).
Cheers.

**Comment by synenka** [comment]
It's hard for me to understand what's happening here. Have you tried using https://github.com/go-delve/delve? If you put a breakpoint on the line where it errors(`err = stream.SendMsg(protomessage)`) it should give you more information on what's going on there.

**Comment by evgenipetrov9** [comment]
The code is pretty bad yeah, I've have reached a solution though. GRPC didn't like sending messages from an interceptor, so once I isolated that ... it almost worked. Turns out it needs V1 message for the SendMsg to work, not a V2 message, and also a RecvMsg even if you don't need the response (depending on whether it's streaming or not).
