### ISSUE TITLE
export protojson "typeFieldDesc" 

### ISSUE THREAD

**Issue by Patrick0308** [golang/protobuf#1497]
**Is your feature request related to a problem? Please describe.**
I want to write a myself  protojson marshaler.  I cannot  implement protoreflect.FieldDescriptor. It's not a problem. However I also want implement typeURLFieldRanger.  I cannot do it. 
In protojson encoder define the typeFieldDesc.
```
// typeFieldDesc is a synthetic field descriptor used for the "@type" field.
var typeFieldDesc = func() protoreflect.FieldDescriptor {
	var fd filedesc.Field
	fd.L0.FullName = "@type"
	fd.L0.Index = -1
	fd.L1.Cardinality = protoreflect.Optional
	fd.L1.Kind = protoreflect.StringKind
	return &fd
}()
```
 https://github.com/protocolbuffers/protobuf-go/blob/7a48e2b66218ba306ed801e42126b374aefce255/encoding/protojson/encode.go#L150

**Describe the solution you'd like**
Move "typeFieldDesc" to reflect package or other package then export it.
Or just export it on protojson package.

**Describe alternatives you've considered**

**Additional context**

**Comment by Patrick0308** [comment]
Actually now I can implement own protojson marshaler, but unmarshaler cant because of typeURLFieldRanger.

**Comment by dsnet** [comment]
You don't need access to this type, you can construct it locally:
```go
// typeFieldDesc is a synthetic field descriptor used for the "@type" field.
type typeFieldDesc struct{ protoreflect.FieldDescriptor }

func (typeFieldDesc) Kind() protoreflect.Kind         { return protoreflect.StringKind }
func (typeFieldDesc) Index() int                      { return -1 }
func (typeFieldDesc) FullName() protoreflect.FullName { return "@type" }
func (typeFieldDesc) JSONName() string                { return "@type" }
func (typeFieldDesc) TextName() string                { return "@type" }
func (typeFieldDesc) IsMap() bool                     { return false }
func (typeFieldDesc) IsList() bool                    { return false }
func (typeFieldDesc) IsExtension() bool               { return false }
```

And modify the `typeURLFieldRanger.Range` method as follows:
```diff
  func (m typeURLFieldRanger) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
- 	if !f(typeFieldDesc, protoreflect.ValueOfString(m.typeURL)) {
+ 	if !f(typeFieldDesc{}, protoreflect.ValueOfString(m.typeURL)) {
  		return
  	}
  	m.FieldRanger.Range(f)
  }
```

**Comment by Patrick0308** [comment]
@dsnet Thanks, it works.
