### ISSUE TITLE
how to use protojson to unmarshal json with lowerCamelCase fields

### ISSUE THREAD

**Issue by horacimacias** [golang/protobuf#1508]
**Is your feature request related to a problem? Please describe.**
Yes. Related to unmarshaling json that was produced by marshaling a protobuf message.

**Describe the solution you'd like**
I'd like to be able to unmarshal json with the same level of flexibility I have when marshaling.
For example, I have an instance of `User` and I marshal it using `UseProtoNames: false` which should result in lowerCamelCase name in JSON field names.
I'm expecting to be able to take that json and use protojson to Unmarshal and get a valid `User` back.

So far, I get an `unknown field` error when using `protojson.Unmarshal`

**Describe alternatives you've considered**
Using other json marshal/unmarshal modules such as encoding/json or jsonpb

**Additional context**
I believe UnmarshalOptions should have the same flags MarshalOptions has.

**Comment by puellanivis** [comment]
There is no need for such an option. Proto3 JSON standards already require the unmarshaller to accept both the converted `lowerCamelCase`† and `proto_field_name`.

> Proto3 JSON parsers are required to accept both the converted lowerCamelCase name and the proto field name.
https://developers.google.com/protocol-buffers/docs/proto3#json

†: N.B.: this is the “converted lowerCamelCase` name, which is not necessarily itself actually `lowerCamelCase` if it started with a capital letter.
