### ISSUE TITLE
proposal: implement TextMarshaler/TextUnmarshaler for well-known types

### ISSUE THREAD

**Issue by bashtian** [golang/protobuf#152]
Right now well-known types can only be used easily with the jsonpb package. I propose to implement the encoding interfaces to the well-known type packages. This would make it easier to use the types with other packages, especially the standard json package.

I can create a pull request if the proposal is accepted.

**Comment by dsymonds** [comment]
What would the output be? The jsonpb package implements the only WKT-specific encoding that has been defined.

**Comment by bashtian** [comment]
The output would be the same as the jsonpb package. Maybe it only makes sense for the Timestamp and Duration package, but I think these are the most important ones. 

Switching to jsonpb is unfortunately not an option for me because it's much slower than the standard json package for the complex protobuf message I tested and marshalling timestamps as a string is the only thing that does not work for me with the standard json package.

**Comment by dsymonds** [comment]
jsonpb is the only supported mechanism for proto <-> JSON transformations. Sorry it is slow, though that's a little surprising since most of its effort merely falls back on encoding/json. You could file a bug about its performance. But implementing TextMarshaler and friends isn't going to be sufficient to get correct output from the encoding/json package.

**Comment by dsnet** [comment]
The `jsonpb` package exists to be a compliant implementation of the JSON<->ProtoBuf specification. The `encoding/json` library is not sufficiently powerful enough to satisfy the specification.

Adding `TextMarshaler` and `TextUnmarshaler` is beyond the scope of other encoding we want to support.
