### ISSUE TITLE
protoc generate file grpc_pb was error

### ISSUE THREAD

**Issue by quyenhl16** [golang/protobuf#1529]
Hi, I got this issue. I create a file .proto
![image](https://user-images.githubusercontent.com/115155436/223774076-8fbaf170-6322-4dec-ba64-f88888bfc2ac.png)
then I generate the file *grpc_pb.go with protoc. But it has some error
![image](https://user-images.githubusercontent.com/115155436/223774873-26fa371b-c0be-409c-85d8-936bbad88953.png)

( I think the *grpc_fb.go file doesn'n generate struct for SumRequest and SumResponse in my case).
How can I fix this issue.

**Comment by puellanivis** [comment]
Golang requires two protoc plugins for generating grpc go code. https://pkg.go.dev/google.golang.org/protobuf/cmd/protoc-gen-go is what you’re missing (this generates the `message` structs) and https://pkg.go.dev/google.golang.org/grpc/cmd/protoc-gen-go-grpc which is what you have (this generates the gRPC specific code, but _not_ the underlying messages.)

**Comment by quyenhl16** [comment]
> Golang requires two protoc plugins for generating grpc go code. https://pkg.go.dev/google.golang.org/protobuf/cmd/protoc-gen-go is what you’re missing (this generates the `message` structs) and https://pkg.go.dev/google.golang.org/grpc/cmd/protoc-gen-go-grpc which is what you have (this generates the gRPC specific code, but _not_ the underlying messages.)

Thank you, but i've installed 2 plugins for generating grpc go code before :
$ go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
$ go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
(According to grpc.io docs).

**Comment by quyenhl16** [comment]
> Golang requires two protoc plugins for generating grpc go code. https://pkg.go.dev/google.golang.org/protobuf/cmd/protoc-gen-go is what you’re missing (this generates the `message` structs) and https://pkg.go.dev/google.golang.org/grpc/cmd/protoc-gen-go-grpc which is what you have (this generates the gRPC specific code, but _not_ the underlying messages.)

Thank you for supporting me !
