### ISSUE TITLE
Cache deserialized objects make the “proto.Unmarshal“ function too memory intensive

### ISSUE THREAD

**Issue by csz062211** [golang/protobuf#1531]
When I cached the deserialized objects to the global cache, proto.Unmarshal function took up a lot of memory（using pprof watch）. If I cached the deserialized objects to another custom object, it would be much less，I'd like to know if the original data []byte is cached When I cached the deserialized objects to the global cache？thanks.

**Comment by stapelberg** [comment]
What do you mean by “deserialize objects to the global cache”?

Can you share a minimal program that shows the problem you run into please?

**Comment by csz062211** [comment]
When I use a local cache (such as bigcache) to store the deserialized pb object

**Comment by csz062211** [comment]
When I use a local cache (such as bigcache) to store the deserialized pb object,
![image](https://user-images.githubusercontent.com/28662473/225028381-f22dd11a-be40-4db5-bb1d-383ba8820506.png)
![image](https://user-images.githubusercontent.com/28662473/225028382-942871e1-9311-4639-b32b-d8c2896e7c2c.png)
![image](https://user-images.githubusercontent.com/28662473/225028462-f3648ed7-b09f-4e6e-bdbb-4d6b11e25688.png)
 When I assign a pb object to another object and save it
![image](https://user-images.githubusercontent.com/28662473/225029648-146e0c59-a459-4240-9c39-1be553ac83c9.png)
![image](https://user-images.githubusercontent.com/28662473/225029789-4e719259-bec0-4710-9de0-790fbc735b66.png)
Memory usage is down 700MB，both object fields are the same, and the memory gap should not be that large

**Comment by stapelberg** [comment]
Can you try if storing the result of https://pkg.go.dev/google.golang.org/protobuf/proto#Clone instead helps?

**Comment by csz062211** [comment]
> I’m still confused how bigcache could be working here. It’s calling `set(…)` an unexported function, so whatever bigcache you’re using here has to be locale to your package.



> I’m still confused how bigcache could be working here. It’s calling `set(…)` an unexported function, so whatever bigcache you’re using here has to be locale to your package.

sorry,this is just a demo, I want to express that this object is saved globally (also a global map, slice...)，The memory used difference between directly saving an unmarshaled object and assigning this unmarshaled object to an object with the same field  is quite large,  so I would say if directly saving an unmarshaled object globally would keep the original binary data there as well?

**Comment by csz062211** [comment]
> Can you try if storing the result of https://pkg.go.dev/google.golang.org/protobuf/proto#Clone instead helps?

I tried，the memory footprint is about the same as storing the deserialized object directly，Normally, the two object fields are the same, there should be no gap is so big，does saving the deserialized object directly cause the original binary data array not to be freed?

**Comment by puellanivis** [comment]
🤔 Well, there are unknown fields data, but I wouldn’t expect that to show up from `reflect.New` but there is also a bunch of message state data that could also be contributing. It’s hard to really say without concrete examples on hand.

**Comment by csz062211** [comment]
> 🤔 Well, there are unknown fields data, but I wouldn’t expect that to show up from `reflect.New` but there is also a bunch of message state data that could also be contributing. It’s hard to really say without concrete examples on hand.

It occurred to me that pb objects hold Pointers but my custom objects hold values, so this is probably the storage of extra Pointers, thanks!
