### ISSUE TITLE
[protobuf-go] An option to marshal proto3 int64/fixed64/uint64 to JSON number, not to JSON string

### ISSUE THREAD

**Issue by ono-kohei-1263** [golang/protobuf#1533]
When marshaling proto3 messages to JSON with `protojson.Marshal`, I would like to transfer proto3 int64/fixed64/uint64 values to JSON numbers, not to JSON strings.  Is it acceptable to add an option into `protojson.MarshalOptions` to make proto3 int64/fixed64/uint64 values be transferred to JSON numbers?

**Comment by puellanivis** [comment]
This needs to be brought up with the mainline protobuf repo: https://github.com/protocolbuffers/protobuf

This repo is a Golang implementation of the standard presented by the mainline, which does not provide any option for this marshal option, and such a marshal option would generate standards non-compliant JSON.
