### ISSUE TITLE
Unfortunately, the generation of context will not change until there are two releases of Go with type aliases. Thus, when Go1.10 is released, we'll make the change.

### ISSUE THREAD

**Issue by Akaslove99** [golang/protobuf#1537]
Unfortunately, the generation of context will not change until there are two releases of Go with type aliases. Thus, when Go1.10 is released, we'll make the change.

_Originally posted by @dsnet in https://github.com/golang/protobuf/issues/326#issuecomment-335977324_

**Comment by puellanivis** [comment]
In the time since, we have released a new API, and this one uses the stdlib `context`.
