### ISSUE TITLE
Importing well-known types

### ISSUE THREAD

**Issue by jpvg10** [golang/protobuf#1544]
Hello. Apologies in advance if this is not the right place to ask or if the question doesn't make much sense (since I am a newbie).

I am trying to use `empty.proto`. My `.proto` file looks like this:
```
syntax = "proto3";
import "google/protobuf/empty.proto";
option go_package = "go-example/grpc";

package controller;

service Controller {
  rpc SayHello(HelloMessage) returns (google.protobuf.Empty) {}
}

message HelloMessage {
  string name = 1;
}
```

I understand that `github.com/golang/protobuf` has been replaced by `google.golang.org/protobuf`. However when I run:
```
protoc --go_out=. --go_opt=paths=source_relative \
    --go-grpc_out=. --go-grpc_opt=paths=source_relative \
    proto/controller.proto
```

The import in the generated files looks like this:
```
import (
	empty "github.com/golang/protobuf/ptypes/empty"
//...
)
```

Therefore my `go.mod` looks like this:
```
require (
	github.com/golang/protobuf v1.5.3
	google.golang.org/grpc v1.55.0
	google.golang.org/protobuf v1.30.0
)
```

Is it possible to fix this so that `empty` gets imported from `google.golang.org/protobuf` instead? Thank you!

Go version: 1.18.1
Protoc version: 3.12.4
OS: Ubuntu 22.04

**Comment by neild** [comment]
You're using an old version of `empty.proto`. More recent ones should reference the `google.golang.org/protobuf` package.

**Comment by jpvg10** [comment]
I'm sorry, can you explain how? That is exactly what I want to do. 

Just doing this in my `.proto` file doesn't work:
```diff
- import "google/protobuf/empty.proto";
+ import "google.golang.org/protobuf/empty.proto";
```

I get this error when compiling:
```
google.golang.org/protobuf/empty.proto: File not found.
proto/controller.proto:3:1: Import "google.golang.org/protobuf/empty.proto" was not found or had errors.
proto/controller.proto:11:37: "google.protobuf.Empty" is not defined.
```

What I get from [this issue](https://github.com/golang/protobuf/issues/1411) is that the well-known types should be being imported from https://github.com/protocolbuffers/protobuf but that's not what's happening in my case.

**Comment by jpvg10** [comment]
You are right, thank you! I had installed with `apt` and thought it was ok because in [the guide](https://grpc.io/docs/protoc-installation/) it said only to check that the version was 3+.
Updating to 3.15.8 solved the problem.
For reference (in case anyone stumbles upon this issue in the future), when using the type in your code, now it's `emptypb.Empty` (not `empty.Empty`).
