### ISSUE TITLE
Maintaining a plugin

### ISSUE THREAD

**Issue by asim** [golang/protobuf#155]
Hey @dsymonds. I'm maintaining a fork of protobuf here https://github.com/micro/protobuf so I can support custom code generation for micro much like grpc. I've been doing it for a while but now as things move around I wonder whether it's the best approach. Do you recommend a better way to maintain a plugin for code generation?

Cheers
Asim

**Comment by zellyn** [comment]
If you're doing it solely to add another plugin-plugin, you can copy just `protoc-gen-go/main.go` and not have to maintain a fork of everything else.

Other options are writing your own completely separate plugin, and generating extra files. For instance, you could generate `foo.micro.pb.go` alongside `foo.pb.go` in the same package. But you likely want the `g.P()` and other plumbing in your own plugin, so the first option is probably still simpler.

**Comment by asim** [comment]
Thanks very much. The first method it is!
