### ISSUE TITLE
Deprecated module github.com/golang/protobuf being used

### ISSUE THREAD

**Issue by SuzukiHonoka** [golang/protobuf#1557]
**What version of protobuf and what language are you using?**
Version: v1.31.0
Lang: Go

**What did you do?**
Deprecated module github.com/golang/protobuf.
Deprecation notice: Use the "google.golang.org/protobuf" module instead. 

**What did you expect to see?**
No deprecated module used

**What did you see instead?**
Deprecated module used

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
```
"C:\Program Files\Go\bin\go.exe" mod why -m github.com/golang/protobuf #gosetup
# github.com/golang/protobuf
google.golang.org/grpc/credentials
github.com/golang/protobuf/proto
```
**Anything else we should know about your project / environment?**
No

**Comment by puellanivis** [comment]
Looking up where the dependency occurs demonstrates that this is a known and expected condition:
```
import (
	// Ensure that any program using "github.com/golang/protobuf"
	// uses a version that wraps this module so that there is a
	// unified view on what protobuf types are globally registered.
	_ "github.com/golang/protobuf/proto"
)
```

I’m going to go ahead and just directly close this issue since this is known and expected, and there is no actionable response. We will not be removing the dependency.

**Comment by jroper** [comment]
If you're not going to remove the dependency, then clearly the use of dependency is not deprecated, and there shouldn't be a deprecation warning.

I've just spent an hour going through my code trying to work out where this dependency was coming from - protoc-gen-go and protoc-gen-go-grpc also both still emit code that depends on it. It's not ok to waste peoples time like that with warnings that they must ignore.

**Comment by puellanivis** [comment]
The use of the dependency is not deprecated, but the package itself is still deprecated, and one should use `google.golang.org/protocolbuffer` instead instead.

We cannot handle how your deprecation checker is checking deprecations, and we cannot turn off the deprecation warning in that tool. Realistically, it should only ever be checking the direct dependencies of your code, as upstream users of a package cannot remove downstream dependencies of their direct dependencies.
