### ISSUE TITLE
Capitalization for common initialisms?

### ISSUE THREAD

**Issue by peter-edge** [golang/protobuf#156]
I actually might be against this, I like that `id` maps to `Id`, `url `maps to `Url`, etc, but there's an issue that was filed over at https://github.com/google/protobuf/issues/1321 so it's at least worth a discussion - any thoughts on changing the generator to output capitalizations for https://github.com/golang/lint/blob/master/lint.go#L719 ?

**Comment by dsymonds** [comment]
No, we won't do this. There's a never-ending list, we'll get it wrong, and it's simpler to stick with the current mechanical translation. We don't hold machine-generated code to the same high standard as human-written code.

**Comment by sleaze** [comment]
But humans have to then consume and interact with this non-idiomatic machine-generated code.

It's not a never ending list.  This only ensures / forces that things get ugly..

**Comment by sleaze** [comment]
But humans have to then consume and interact with this non-idiomatic machine-generated code.

It's not a never ending list - just put the initialisms from `golint`.

Refusing to acknowledge and / or fix this defect only ensures and forces that things continue to be generated in an ugly way, needlessly.

**Comment by manishrjain** [comment]
FWIW, I think Go linter should relax its rules on ID, URL etc. being capitalized.

**Comment by yaronsumel** [comment]
you can use `github.com/gogo/protobuf/gogoproto`
```
message C {
	optional int64 size = 1 [(gogoproto.customname) = "MySize"];
}
```
```
type C struct {
	MySize		*int64
}
```

**Comment by sleaze** [comment]
Thanks @yaronsumel , will give it a try.
