### ISSUE TITLE
Timestamp error and missing/unclear documentation

### ISSUE THREAD

**Issue by Kiura** [golang/protobuf#157]
1) Documentation:
I was not able to find any documentation that I should `import "google/protobuf/timestamp.proto";` and write `google.protobuf.Timestamp` instead of `Timestamp` as it says in the official docs: [google/proto3#json](https://developers.google.com/protocol-buffers/docs/proto3#json)
and not sure if this is even correct way

2) Timestamp error:
Using `google.protobuf.Timestamp` I finally managed to compile the proto files but when I run the go code it throws an error: `cannot find package "google/protobuf".`

Spent whole day trying to figure out what the problem no luck
```bash
$ which protoc
/usr/local/bin/protoc

$ protoc --version
libprotoc 3.0.0

$ go version
go version go1.6 darwin/amd64
```
P.S. the `pb.go` files will be used with `postgres` database so Timestamps are very important (using int64 would be problematic).

Any help is highly appreciated

**Comment by forkloop** [comment]
You can use [`timestamp.proto`](https://github.com/golang/protobuf/blob/master/ptypes/timestamp/timestamp.proto) in this package by importing it

`import "protobuf/ptypes/timestamp/timestamp.proto";`

**Comment by Kiura** [comment]
Thanks @forkloop, gonna check this later )

**Comment by dsymonds** [comment]
Sorry, I'm still waiting for google/protobuf#1361 to be merged, which will address (2). (1) doesn't have a great answer right now.
