### ISSUE TITLE
Update internal/benchmarks to work with fleetbench

### ISSUE THREAD

**Issue by stapelberg** [golang/protobuf#1570]
https://github.com/protocolbuffers/protobuf-go/blob/f4a6c1f6e5c183174c1ea206ed49916e8f1dd1e8/internal/benchmarks/download_benchdata.bash#L17 is broken because the datasets no longer exist.

The benchmark should be adjusted to work with https://github.com/google/fleetbench instead.

**Comment by puellanivis** [comment]
Isn’t this a duplicate of https://github.com/golang/protobuf/issues/1524

**Comment by stapelberg** [comment]
Definitely. Thanks for pointing that out, I didn’t see that one.
