### ISSUE TITLE
Support for optional fields

### ISSUE THREAD

**Issue by wim07101993** [golang/protobuf#1595]
When declaring a field as [optional](https://protobuf.dev/programming-guides/proto3/#field-labels) the protoc-gen-go compiler exits with the error: `protos/test.proto: This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set.`

Is this still experimental? It was added in [v1.22.0](https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.22.0) almost 4 years ago.

command: `protoc --go_out "generated" protos/test.proto`

proto file: 
```
syntax = "proto3";

package option_test;

option go_package = "grpc_test";

message OptionMessage {
  optional int32 value = 1;
}
```

```
$ protoc --version
libprotoc 3.12.4
```

```
$ protoc-gen-go --version
protoc-gen-go v1.28.1
```

**Comment by neild** [comment]
That error message is printed by `protoc`, not the Go code generator.

I believe the most recent version of `protoc` is 25.3:
https://github.com/protocolbuffers/protobuf/releases

**Comment by wim07101993** [comment]
Indeed, the version I had came from the Ubuntu package manager but hasn't been updated since 2020... The latest releases from github seem to work.
