### ISSUE TITLE
How to write my own plugin for generator RPC

### ISSUE THREAD

**Issue by guileen** [golang/protobuf#16]
I notice this tool have support generate grpc output, but I'd like to implement my own RPC for some reasons.

So I wonder if can you provide a tool generate rpc interfaces without dependencies on grpc, or can you give me some information about how to write my own generator?

One more question, to provide flexibility of my RPC framework, to easy change my generator, can I write a plugin use a python but generate code of golang?

**Comment by dsymonds** [comment]
Writing a plugin is not really documented or well supported, but shouldn't be hard. Just follow the example of grpc.

**Comment by guileen** [comment]
Thank you.

**Comment by ceram1** [comment]
How can I link my own plugin? Write a new file like [link_grpc.go](https://github.com/golang/protobuf/blob/master/protoc-gen-go/link_grpc.go)?

**Comment by vimalk78** [comment]
`$ protoc ./helloworld.proto --go_out=plugins=grpc:. `

is it possible that that i write my own plugin and invoke it along with grpc plugin?
`$ protoc ./helloworld.proto --go_out=plugins=grpc+myplugin:. `

do i need to mandatory build my plugin into `protoc-gen-go` ?
if no, then how will the `protoc-gen-go` find `myplugin` ?
