### ISSUE TITLE
unmergeable types should panic instead of logging

### ISSUE THREAD

**Issue by aybabtme** [golang/protobuf#160]
In https://github.com/golang/protobuf/blob/master/proto/clone.go#L204, logging the problem instead of returning-an-error/panic'ing leads to silent failures, loss of data and subtle rage inducing bugs.

Since the API would be broken if the call signature was modified to return an error, I suggest that the call panic instead of logging. This way code that incorrectly expects `proto.Merge` to merge their types would panic (and hopefully be fixed) instead of proceeding silently with corrupted state.

**Comment by dsymonds** [comment]
Maybe, but it shouldn't be possible to even trigger that line. It was mainly there for development.

Do you have a situation where it has actually arisen?

**Comment by aybabtme** [comment]
Yes, I'm seeing it occur quite often. I'm away for the next few weeks but
after that, I'd be happy to try and make a reproducer.

On Wednesday, 13 April 2016, David Symonds <notifications@github.com> wrote:

> Maybe, but it shouldn't be possible to even trigger that line. It was
> mainly there for development.
>
> Do you have a situation where it has actually arisen?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/golang/protobuf/issues/160#issuecomment-209180834>
>


-- 

Cheers,

--
Antoine Grondin

*Live long and prosper*

**Comment by dsymonds** [comment]
Please do. I'm not aware of any way to trigger that log line.

**Comment by aybabtme** [comment]
Should be safe to panic then ;)

On Wednesday, 13 April 2016, David Symonds <notifications@github.com> wrote:

> Please do. I'm not aware of any way to trigger that log line.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/golang/protobuf/issues/160#issuecomment-209310763>
>


-- 

Cheers,

--
Antoine Grondin

*Live long and prosper*

**Comment by dsnet** [comment]
The `dev` branch uses a new implementation of `Merge`. Over time the old will be killed off.
