### ISSUE TITLE
please consider semantic versioning

### ISSUE THREAD

**Issue by onlyjob** [golang/protobuf#161]
Please consider assigning version numbers and tagging releases. Tags/releases
are useful for downstream package maintainers (in [Debian](http://debian.org) and other distributions) to export source tarballs, automatically track new releases and to declare dependencies between packages. Read more in the [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

Versioning provides additional benefits to encourage vendoring of a particular (e.g. latest stable) release contrary to random unreleased snapshots.

Thank you.

See also

 * http://semver.org/
 * https://en.wikipedia.org/wiki/Software_versioning

**Comment by dsymonds** [comment]
Considered, but it doesn't make sense here. This package generally seeks to stay stable, but also its HEAD is what's supported in other places.

**Comment by onlyjob** [comment]
> but also its HEAD is what's supported in other places.

Without tags there are no other options but to use HEAD: no wonder it is used in other places.

**Comment by dsymonds** [comment]
That doesn't really give a reason why people would use an old version. If they want to pin a particular version, they can vendor this package.

**Comment by onlyjob** [comment]
Fair enough, thanks.
