### ISSUE TITLE
undefined: descriptorpb.Default_FileOptions_PhpGenericServices

### ISSUE THREAD

**Issue by erkanrua** [golang/protobuf#1617]
When I tried to docker run it gives error in descriptor. 

docker run --rm -it -e GOOS=windows -v "%cd%:/xk6" ^
  grafana/xk6 build v0.43.1 --output k6.exe ^
  --with github.com/mostafa/xk6-kafka@v0.17.0 ^
  --with github.com/grafana/xk6-output-influxdb@v0.3.0

![resim](https://github.com/golang/protobuf/assets/4141463/1e16d864-5486-4642-a830-bfc941af5a28)

**Comment by puellanivis** [comment]
Recommend following the directions here: https://github.com/protocolbuffers/protobuf/issues/16163

**Comment by stapelberg** [comment]
Should be fixed by updating to a more recent version of Go Protobuf, closing.
