### ISSUE TITLE
structpb.Struct.MarshalJSON is not consistent

### ISSUE THREAD

**Issue by zchenyu** [golang/protobuf#1628]
I was running Go unit tests that seem to fail depending on the run / machine. It seems the way MarshalJSON handles spaces is inconsistent. Sometimes it outputs

```
{"x":"1","y":2}
```

and sometimes
```
{"x":"1", "y":2}
```

But I haven't figured out exactly what causes one or the other yet. Is there a way to make it consistent?

**Comment by cybrcodr** [comment]
That is intended.  The MarshalJSON method uses the protojson.Marshal func underneath.  And the [description](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson#Marshal) mentions ...

> Do not depend on the output being stable. Its output will change across different builds of your program, even when using the same version of the protobuf module.

It's best not to compare JSON strings.  Note that there is also no standard in the ordering of JSON fields.

**Comment by zchenyu** [comment]
Makes sense. Makes it a bit annoying to use in unit tests (e.g. mocks), but I'll figure it out.

**Comment by puellanivis** [comment]
You can use [`cmp.Compare`](https://pkg.go.dev/github.com/google/go-cmp/cmp) and [`protocmp`](https://pkg.go.dev/google.golang.org/protobuf/testing/protocmp)  to test the semantics of the protobuf messages, rather than testing indirectly their serialization.

**Comment by zchenyu** [comment]
The issue we have is that we pass the serialized JSON to a mocked function. e.g.
```
mockClient.On("Foo", `{"x": 1}`)
```

So it's not just a simple assertion on the proto value.
