### ISSUE TITLE
--gofast_out option in protoc discards inline comments from .proto files

### ISSUE THREAD

**Issue by charlie103** [golang/protobuf#1629]
When using the --gofast_out option with protoc to generate Go code, inline comments from the .proto files are discarded. This behavior is different from the --go_out option, which retains these comments. I would like to understand the reason behind this difference and if there is a way to preserve inline comments while using --gofast_out.

**Comment by puellanivis** [comment]
We don’t maintain the `protoc-gen-gofast` plugin. You would have to ask them. https://github.com/gogo/protobuf/blob/v1.3.2/protoc-gen-gofast
