### ISSUE TITLE
protocmp: add SortSlices option

### ISSUE THREAD

**Issue by ash2k** [golang/protobuf#1651]
**Is your feature request related to a problem? Please describe.**

I need to compare two protobuf messages in tests. I use cmp + protocmp for that. A message has a repeated field but for that certain type (repeated message) ordering doesn't matter.

**Describe the solution you'd like**

I'd like to have a `protocmp.SortSlices()` option for `protocmp.Transform()` so that slices are sorted before they are transformed. There are probably other options that are applicable.

**Describe alternatives you've considered**

[`cmpopts.SortSlices()`](https://pkg.go.dev/github.com/google/go-cmp@v0.6.0/cmp/cmpopts#SortSlices) doesn't work because the slice/repeated field is a field, it's not top level. So, protocmp transforms it into `protocmp.Message` and hence `cmpopts.SortSlices()` doesn't work on it when used with the actual field element type.

**Additional context**

I'm going to use `cmpopts.SortSlices()` with filtering + `protocmp.Message` as a workaround but this is quite a hassle.

**Comment by dsnet** [comment]
Hi, `protocmp` already has [`protocmp.SortRepeated`](https://pkg.go.dev/google.golang.org/protobuf/testing/protocmp#SortRepeated) and [`protocmp.SortRepeatedFields`](https://pkg.go.dev/google.golang.org/protobuf/testing/protocmp#SortRepeatedFields). Is there a reason those don't suite your needs?

**Comment by ash2k** [comment]
Wow, I overlooked that function. Thank you!
