### ISSUE TITLE
Any interest in an Equal method for oneof wrappers?

### ISSUE THREAD

**Issue by ghjm** [golang/protobuf#1653]
**Is your feature request related to a problem? Please describe.**
If you have two variables holding oneof wrappers, and you don't know which oneof choice they are, there is no convenient way to test them for equality.

**Describe the solution you'd like**
I would like oneof wrappers to have an Equal method so you can compare them, similarly to how you compare other protobuf-go types.

**Describe alternatives you've considered**
I considered using `proto.Equal`, `protocmp`, etc., but this doesn't work because the wrappers are not `proto.Message` types.  I also considered implementing this as a plugin, but as far as I can see there is no way for a plugin to modify the generated interface definition.

**Additional context**
Generating an `Equal` method for the oneof wrapper types turns out to be pretty easy:

```
diff --git a/cmd/protoc-gen-go/internal_gengo/main.go b/cmd/protoc-gen-go/internal_gengo/main.go
index a4c4595e..3474df6b 100644
--- a/cmd/protoc-gen-go/internal_gengo/main.go
+++ b/cmd/protoc-gen-go/internal_gengo/main.go
@@ -848,6 +848,7 @@ func genMessageOneofWrapperTypes(g *protogen.GeneratedFile, f *fileInfo, m *mess
                ifName := oneofInterfaceName(oneof)
                g.P("type ", ifName, " interface {")
                g.P(ifName, "()")
+               g.P("Equal (that any) bool")
                g.P("}")
                g.P()
                for _, field := range oneof.Fields {
@@ -873,6 +874,14 @@ func genMessageOneofWrapperTypes(g *protogen.GeneratedFile, f *fileInfo, m *mess
                for _, field := range oneof.Fields {
                        g.P("func (*", field.GoIdent, ") ", ifName, "() {}")
                        g.P()
+                       g.P("func (this *", field.GoIdent, ") Equal(that any) bool {")
+                       g.P("v, ok := that.(*", field.GoIdent, ")")
+                       g.P("if !ok {")
+                       g.P("return false")
+                       g.P("}")
+                       g.P("return v.Equal(that)")
+                       g.P("}")
+                       g.P()
                }
        }
 }
```

I'm happy to sign up for the CLA, go through the gerrit process, etc., but wanted to get some feedback from a team member first.  Would this contribution likely be accepted?

**Comment by puellanivis** [comment]
Very quickly, I can tell you, don’t use `this` as the receiver. It seems there’s also a bug in this, you do a type conversion of `that` to `v`, and then `return v.Equal(that)`? That would infinitely recurse until the program crashes, right?

I think this problem might be more difficult that you’re making it out to be… or, easier: `reflect.DeepEqual` should surely work? And cover all the corner cases, and pitfalls?

**Comment by ghjm** [comment]
I'm happy to rename the receiver.

The `v.Equal` call would infinitely recurse if it was calling the interface type, but it isn't - it's calling the concrete type.  Because the concrete types already have their own `Equal` methods, all the corner cases are already handled (or if not, this is a bug in the already-existing code).  All we have to do in the wrapper type is determine whether or not this is the same concrete type, and if so, pass the request off to the concrete type implementation of `Equal`.

**Comment by puellanivis** [comment]
But this would generate, as a for instance:
```go
func (*MyMessage_Foo_) isMyOneof() {}

func (this *MyMessage_Foo_) Equal(that any) bool {
	v, ok := that.(*MyMessage_Foo_)
	if !ok {
		return false
	}
	return v.Equal(that)
}
```

In the `return v.Equal(that)`, we just type-coerced `that` into `v` with the same concrete type as `this`, meaning it will invoke this very receiver method when `v.Equal()` is called, down the chain from the first call of `this.Equal(that)` to the indefinite progression of `that.Equal(that)` calls until the program crashes.

https://go.dev/play/p/2w3xqPdg43m here’s a complete mock up in the playground for you demonstrating that the program exits without returning a value, when `that` is the same concrete type as `this`.

> … if it was calling the interface type, but it isn't - it's calling the concrete type.

I am unsure where you got this notion from, but even when calling a receiver method on an interface, it _always_ calls the concrete type’s receiver method. In fact, you cannot even use an interface type or even a pointer to an interface type as a receiver in a receiver method. It wouldn’t make sense anyways, because as mentioned, receiver method calls through an interface are invoked on their concrete types.

That is, you also could not change this code to:
```go
func (this isMyMessage_MyOneof) Equal(that any) bool {
	// this function signature fails to compile with the message:
	// <filename>:<lineno>:7: invalid receiver type isMyMessage_MyOneof (pointer or interface type)
}
```

**Comment by ghjm** [comment]
Ok, you're right, I was confused.  I need to use `reflect.DeepEqual`:

```
diff --git a/cmd/protoc-gen-go/internal_gengo/main.go b/cmd/protoc-gen-go/internal_gengo/main.go
index d34efa9b..7026fea2 100644
--- a/cmd/protoc-gen-go/internal_gengo/main.go
+++ b/cmd/protoc-gen-go/internal_gengo/main.go
@@ -793,6 +793,7 @@ func genMessageOneofWrapperTypes(g *protogen.GeneratedFile, f *fileInfo, m *mess
                ifName := oneofInterfaceName(oneof)
                g.P("type ", ifName, " interface {")
                g.P(ifName, "()")
+               g.P("Equal (that any) bool")
                g.P("}")
                g.P()
                for _, field := range oneof.Fields {
@@ -817,6 +818,14 @@ func genMessageOneofWrapperTypes(g *protogen.GeneratedFile, f *fileInfo, m *mess
                for _, field := range oneof.Fields {
                        g.P("func (*", field.GoIdent, ") ", ifName, "() {}")
                        g.P()
+                       g.P("func (t *", field.GoIdent, ") Equal(that any) bool {")
+                       g.P("v, ok := that.(*", field.GoIdent, ")")
+                       g.P("if !ok {")
+                       g.P("return false")
+                       g.P("}")
+                       g.P("return reflect.DeepEqual(t, v)")
+                       g.P("}")
+                       g.P()
                }
        }
 }
```

**Comment by puellanivis** [comment]
OK, this code doesn’t crash, but `reflect.DeepEqual(this, that)` already implements a check for ensuring the types are the same. So we can also remove that code. So now we have:
```golang
func (t *MyMessage_Foo_) Equal(that any) bool {
	return reflect.DeepEqual(t, that)
}
```
