### ISSUE TITLE
jsonpb Unmarshalling support for Struct and Value wkt

### ISSUE THREAD

**Issue by rohitsaboo** [golang/protobuf#166]
Do we have support in jsonpb for unmarshalling Struct and Value wkt? If not, is there any plan to add any?

**Comment by dsymonds** [comment]
Yes, Struct and Value are supported by jsonpb. What are you missing?

**Comment by rohitsaboo** [comment]
For some reason, I'm seeing error messages of the form, 'unknown field "xxx" in structpb.Struct/Value',
and the fields in the protobufs are empty.

Also, I cannot find a unit test that is unmarshalling to be sure I'm doing things correctly.

**Comment by dsymonds** [comment]
The spec is at https://developers.google.com/protocol-buffers/docs/proto3#json, mentioned in the jsonpb package docs. You could also just marshal a populated structpb.Struct to see what the format is meant to look like.

Feel free to open a new issue if you find a bug.

**Comment by rohitsaboo** [comment]
Hey David, I'm looking to unmarshal from json and not marshal. There are test cases for marshaling structs, but none for unmarshalling.

**Comment by dsymonds** [comment]
You indicated you didn't know whether you were doing things right, which I took to mean you weren't sure what a JSON format Struct is meant to look like. I suggested marshaling from jsonpb to see what it looks like.

If you have specific input data that isn't parsed, show it. I can't help you with anything else. The code in jsonpb works to the best of my knowledge.

**Comment by rohitsaboo** [comment]
Hey David,

Here's a somewhat minimal example:

The proto looks like
```
syntax = "proto3";

package test;

import "google/protobuf/struct.proto";

message Activity {
  Person actor = 3;
}

message Person {
  google.protobuf.Value location = 9;
}
```

The json looks like:
```
{
    "actor": {
        "location": {
            "objectType": "place",
            "displayName": "Denver, CO"
        }
    }
}
```

The unmarshalled proto comes out to
```
actor: <
  location: <
  >
>
```
with the error message `unknown field "objectType" in structpb.Value`

**Comment by dsymonds** [comment]
Yes, and what happens in the other direction? i.e. start with the proto that you expect, and see what jsonpb produces.

**Comment by rohitsaboo** [comment]
We get the correct json in the other direction (with the indentation and ordering as below):
```json
{
  "actor": {
    "location": {
          "displayName": "Denver, CO",
          "objectType": "place"
        }
  }
}
```

The code to populate the proto looks a bit ugly, but here it is:
```go
	a := test.Activity{
		Actor: &test.Person{
			Location: &stpb.Value{
				Kind: &stpb.Value_StructValue{
					StructValue: &stpb.Struct{
						Fields: map[string]*stpb.Value{
							"objectType":  &stpb.Value{Kind: &stpb.Value_StringValue{"place"}},
							"displayName": &stpb.Value{Kind: &stpb.Value_StringValue{"Denver, CO"}},
						},
					},
				},
			},
		},
	}
	result, _ := (&jsonpb.Marshaler{Indent: "  ", OrigName: true}).MarshalToString(&a)
	fmt.Println(result)

```

**Comment by dsymonds** [comment]
Okay, that's more useful. Thanks.

I'll look into this later.

**Comment by Cedric-Venet** [comment]
Any update on this? this make grp gateway useless for us as we use several Struct in our message

**Comment by calbach** [comment]
Should be fixed by https://github.com/golang/protobuf/commit/18c9bb3261723cd5401db4d0c9fbc5c3b6c70fe8.

**Comment by cybrcodr** [comment]
Closing this now.  Feel free to file another issue if there are problems with the implementation.
