### ISSUE TITLE
protojson.Unmarshal drops nested struct in error case

### ISSUE THREAD

**Issue by nataliescottdavidson** [golang/protobuf#1660]
**What version of protobuf and what language are you using?**
google.golang.org/protobuf v1.36.0

**What did you do?**
`protojson.Unmarshal` behaves differently than `encoding/json` in the case when there are field type mismatch errors. It will unmarshal some fields, but drop the nested struct that contains the error field.

```
  func TestNestedUnmarshalWithError(t *testing.T) {
	jsonString := `{"baz": "buzz", "containsError": {"bang": "fizz", "intButWeGetString":"sillystring"}}`

	// encoding/json behavior
	var jsonOutput gobindings.Struct
	err := json.Unmarshal([]byte(jsonString), &jsonOutput)

	// error is expected
	assert.Equal(t, "json: cannot unmarshal string into Go struct field NestedStruct.containsError.intButWeGetString of type int32", err.Error())

	// but we get all the good fields still
	expected := gobindings.Struct{
		Baz:           "buzz",
		ContainsError: &gobindings.NestedStruct{Bang: "fizz"},
	}
	assert.Equal(t, expected.String(), jsonOutput.String())

	// protojson
	var protojsonOutput gobindings.Struct
	err = protojson.Unmarshal([]byte(jsonString), &protojsonOutput)
	assert.Equal(t, "proto: (line 1:71): invalid value for int32 field intButWeGetString: \"sillystring\"", err.Error())

	// we lost containsError { bang: "fizz"} !! bang didn't do anything wrong!!
	assert.Nil(t, protojsonOutput.ContainsError)

	// we still have fields outside the nested struct that contains the error though
	assert.Equal(t, "buzz", protojsonOutput.Baz)
}
```

**What did you expect to see?**
Expected output to contain fields in the nested struct. Expected behavior to have parity with `encoding/json`

**What did you see instead?**
Nested struct was nil.

**Anything else we should know about your project / environment?**
```
syntax = "proto3";
package my.package;

option go_package = "./gobindings"; // golang

message NestedStruct {
	string bang = 1;
	int32 intButWeGetString = 2;
}

message Struct {
	string baz = 1;
	NestedStruct containsError = 2;
}
```
Full reproduction and generated go bindings here https://github.com/nataliescottdavidson/protojson_unmarshal_drops_nested_struct_in_error_case

**Comment by puellanivis** [comment]
The only guarantee made by `protojson.UnmarshalOptions.Unmarshal` is:
> If it returns an error, the given message may be partially set.

I understand Hyrum’s Law, but the expectation that error-case code will be the same behavior across two package is not necessarily a sound one. Especially, when the contract spells out that in the error case, the target has an undefined state.

**Comment by nataliescottdavidson** [comment]
Fair enough
