### ISSUE TITLE
encoding.json Marshallers for some of the well known types

### ISSUE THREAD

**Issue by rohitsaboo** [golang/protobuf#169]
Right now, the only way to support transformation of the well known types between proto and json is jsonpb and unfortunately, some well known types such as Struct and Values are not yet supported for transforming from json to proto. (Also, while I haven't investigated this, others have reported here that jsonpb is ~6x slower.)

It will be useful to have some marshallers and unmarshalers for some of the simpler, more commonly used well known types so that one can use these with encoding.json.

If the proposal sounds good, I can create changelists for a few of these well known types.

**Comment by bcmills** [comment]
Arguably *all* generated message types ought to implement `json.Marshaler` and `json.Unmarshaler` (calling `jsonpb` under the hood).  But that's a separate issue; I don't think adding a special-case for WKTs is appropriate.

**Comment by cybrcodr** [comment]
Support for WKT have been implemented in 18c9bb3261723cd5401db4d0c9fbc5c3b6c70fe8

**Comment by cybrcodr** [comment]
Sorry, I missed out the subtle wording here for referring to encoding/json.Marshaler.  I closed this bug as 18c9bb3261723cd5401db4d0c9fbc5c3b6c70fe8 added support for WKT in jsonpb.

bcmills@ did file related issue #256 for supporting the general case of using encoding/json.
