### ISSUE TITLE
Question on fully qualified proto name in `RegisterType`

### ISSUE THREAD

**Issue by drombosky** [golang/protobuf#171]
I recently updated my `protoc` and `github.com/golang/protobuf/proto/...` and started seeing a warning messages when running my program:
```
proto: duplicate proto type registered: service.Resource
```

I have my messages split into a `request` and `response` folders, and the services are split up after that:
```
$GOPATH/src/project/requests/service/service.pb.go
$GOPATH/src/project/response/service/service.pb.go
```
The service deals with the same resources so each `service.pb.go` will have a type named `Resource`, although the shape will be different.

I'm not using any of the features that use the [`MessageType`](https://github.com/golang/protobuf/blob/8d92cf5fc15a4382f8964b08e1f42a75c0591aa3/proto/properties.go#L846) function, but I'm not feeling great about the [panic comment](https://github.com/golang/protobuf/blob/8d92cf5fc15a4382f8964b08e1f42a75c0591aa3/proto/properties.go#L833) in the `RegisterType` function. I should note that I am using `syntax = "proto2";` in my `.proto` files.

My questions are:
1. Is there a reason why the fully qualified proto name only includes the import name and not the full package path?
2. What are the future implications of having duplicate proto types?
3. What is the time frame for adding in that `panic`?

Thanks!

**Comment by dsymonds** [comment]
The protocol buffer world has its own namespace. In that namespace, names are qualified by the package name alone. This is a cross-language thing, so there's no notion of "full package path".

In your, you'll want to fix your layout so it doesn't have that duplicate. There's a number of places where it will cause issues, so better to remedy it now before it gets harder.

Consider merging your request/response proto packages. The grpc-go samples show how it's normally done.
