### ISSUE TITLE
jsonpb - enum can have uint32 values that doesnt not match declared enum constant

### ISSUE THREAD

**Issue by mrsinham** [golang/protobuf#174]
For example if we have :

```
message Example {
	optional Test test = 1;
}

enum Test {
	test1 = 1;
	test2 = 2;
}

```
And we send :

```
{
	"test":0
}

```
or :

```
{
	"test":3
}

```
The message is accepted by the jsonpb.Unmarshaler. It is possible to check the numeric value ? 

Thanks a lot

**Comment by dsymonds** [comment]
I can't see anything specific in the jsonpb spec, but the wire format (which is meant to be roughly equivalent) doesn't say that enums are closed. Enum values that aren't known about are left up to the implementation, and Go (like C++, I believe) permits any int32 value for an enum, in both the wire format and jsonpb.
