### ISSUE TITLE
generator is not using the proto json_name as json tag

### ISSUE THREAD

**Issue by bashtian** [golang/protobuf#176]
The field name is used instead:

https://github.com/golang/protobuf/blob/master/protoc-gen-go/generator/generator.go#L1777-L1778

Should I create a pull request?

**Comment by dsymonds** [comment]
It's working as intended. The `json_name` from the FieldDescriptorProto is specific to the JSON spec for proto3, and is used by the `jsonpb` package, but the `json` tag is legacy, and follows a different naming scheme.
