### ISSUE TITLE
message marshal crashed bug

### ISSUE THREAD

**Issue by BigTong** [golang/protobuf#177]
steps:
1,  add log for proto/encode.go
 191     func (p *Buffer) EncodeRawBytes(b []byte) error {
 192         p.EncodeVarint(uint64(len(b)))
 193
 194         //debug log
 195         if p == nil {
 196                 fmt.Println("p is nil")
 197                 // return errors.New("p is nil")
 198         }
 199         fmt.Printf("b len %d\n", len(b))
 200         if b == nil {
 201                 fmt.Println("b is nil")
 202                 fmt.Printf("nil b len %d\n", len(b))
 203                 // return errors.New("b is nil")
 204         }
 205
 206         p.buf = append(p.buf, b...)
 207         return nil
 208 }

2, the log output
b len 18484
b is nil
nil b len 18484
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x43ff27]

goroutine 10327146 [running]:
github.com/golang/protobuf/proto.(*Buffer).EncodeRawBytes(0xc249c8b380, 0x0, 0x4834, 0x5000, 0x0, 0x0)
        /home/services/go/src/github.com/golang/protobuf/proto/encode.go:206 +0x4bc
github.com/golang/protobuf/proto.(*Buffer).enc_proto3_slice_byte(0xc249c8b380, 0xc2080ea280, 0xc2459db000, 0x0, 0x0)
        /home/services/go/src/github.com/golang/protobuf/proto/encode.go:710 +0x220
github.com/golang/protobuf/proto.(*Buffer).enc_struct(0xc249c8b380, 0xc20810c8c0, 0xc2459db000, 0x0, 0x0)

**Comment by loverszhaokai** [comment]
@BigTong , I got this error two.  😢

**Comment by BigTong** [comment]
go 1.4.2 always crashed;
go 1.5.4  && go 1.6.2 sometimes crashed

**Comment by dsymonds** [comment]
There's no way to have both `len(b) > 0` and `b == nil` unless you have a race condition in your program. Have you tried running it under gotsan?

**Comment by loverszhaokai** [comment]
@dsymonds , what do you mean by `gotsan` ?

**Comment by BigTong** [comment]
@dsymonds what do you mean? does it mean thread safe problem? but  it crashed when lock this marshal function.

**Comment by dsymonds** [comment]
Use the `-race` flag with `go test` or whatever.

**Comment by BigTong** [comment]
no

**Comment by BigTong** [comment]
I just run with "nohup   ./xxxx > xxx.log 2>&1 & "
