### ISSUE TITLE
Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2". How to update to proto3 for golang?

### ISSUE THREAD

**Issue by MiteshSharma** [golang/protobuf#182]
Getting above error while running protoc, on looking around found that need to update protoc version. Current version is : 
$ protoc --version
libprotoc 2.6.1

How to update it to 3.0.0 version? Is this bug fixed in latest code?  

Run to install : go get -u github.com/golang/protobuf/{proto,protoc-gen-go}

**Comment by dsymonds** [comment]
You need to get protoc 3 from github.com/google/protobuf. This repo is only for the Go plugin.

**Comment by MiteshSharma** [comment]
thanks for pointing in right direction.

**Comment by MiteshSharma** [comment]
This is not relevant but if you can guide how to fix this issue:
protoc-gen-gofast: program not found or is not executable
--gofast_out: protoc-gen-gofast: Plugin failed with status code 1.

**Comment by dsymonds** [comment]
gofast isn't here.

**Comment by MiteshSharma** [comment]
gotit. Thanks

**Comment by awalterschulze** [comment]
gofast is part of github.com/gogo/protobuf it allows you to use gogoprotobuf purely as a code generator and still use golang/protobuf as your proto library.
It only generates the extra Marshal, Unmarshal and Size methods to speed up marshaling and unmarshaling.

**Comment by MiteshSharma** [comment]
Thanks awalterschulze for explaining.
