### ISSUE TITLE
proto3 map serialization calls json not jsonpb

### ISSUE THREAD

**Issue by mwitkow** [golang/protobuf#184]
While browsing through the code I saw that:
https://github.com/golang/protobuf/blob/master/jsonpb/jsonpb.go#L457
calls

``` go
b, err := json.Marshal(k.Interface())
```

Is that correct? Can't map keys be messages that may be well known-types? Would they be handled correctly through that?

**Comment by dsymonds** [comment]
Map keys are very restricted. Message types are not allowed. It's approximately only integers, bools and strings, all of which are marshaled correctly by the standard json package.

**Comment by mwitkow** [comment]
Oh, makes sense. I thought this was related to map values where messages
are allowed.

Thanks for clarifying  maybe a comment would be useful? ☺️
