### ISSUE TITLE
proto test

### ISSUE THREAD

**Issue by zweite** [golang/protobuf#190]
➜  proto git:(master) make test
go install
make install
go install
make -C testdata
rm -f test.pb.go
make test.pb.go
protoc --go_out=. test.proto
test.proto:494:3: Expected "required", "optional", or "repeated".
test.proto:494:6: Expected field name.
test.proto:495:3: Expected "required", "optional", or "repeated".
test.proto:495:6: Expected field name.
test.proto:496:3: Expected "required", "optional", or "repeated".
test.proto:496:6: Expected field name.
test.proto:497:3: Expected "required", "optional", or "repeated".
test.proto:497:6: Expected field name.
make[2]: *** [test.pb.go] Error 1
make[1]: *** [regenerate] Error 2
make: *** [generate-test-pbs] Error 2
➜  proto git:(master) ✗ pwd
$GOPATH/src/github.com/golang/protobuf/proto

**Comment by awalterschulze** [comment]
protoc should probably be at least version 3.
What does protoc --version say?

**Comment by zweite** [comment]
➜  proto git:(master) ✗ protoc --version
libprotoc 2.6.1

**Comment by zweite** [comment]
thank @awalterschulze
