### ISSUE TITLE
protoc-gen-go: Not extracted TrailingComments

### ISSUE THREAD

**Issue by inada-s** [golang/protobuf#191]
https://github.com/golang/protobuf/blob/e51d002c610dbe8c136679a67a6ded5df4d49b5c/protoc-gen-go/generator/generator.go#L991

When the loc.LeadingComments is nil and loc.TrailingComments is not nil, the loc.TrailingComments is not extracted.
Is this intended?

**Comment by dsymonds** [comment]
It was intended. Very few people use trailing comments, and even when they are used they are often not suitable for converting into comments in the generated code.

**Comment by inada-s** [comment]
I understood it.
thanks.
