### ISSUE TITLE
jsonpb convert underscores to camelcase, that is not what i wanted.

### ISSUE THREAD

**Issue by khadgarmage** [golang/protobuf#193]
Jsonpb convert underscores to camelcase, that is not what i wanted. for example:
>{"ttt_aaa":"fdasfdsa"}

After UnmarshalNext and Unmarshal,the result is like this:
>{"tttAaa":"fdasfdsa"}

Is it have a way to output like this? Thanks.
>{"ttt_aaa":"fdasfdsa"}

**Comment by zombiezen** [comment]
If you set `Marshaler.OrigName` to true, then `Marshal` will work as you want.

**Comment by khadgarmage** [comment]
@zombiezen Thanks~

**Comment by rustambek96** [comment]
> If you set `Marshaler.OrigName` to true, then `Marshal` will work as you want.

THANK YOU!! YOU SAVED MY LIFE
