### ISSUE TITLE
Naming convention with leading underscore field names

### ISSUE THREAD

**Issue by myitcv** [golang/protobuf#201]
Please can you point me towards the convention that is being followed [here](https://github.com/golang/protobuf/blob/c75fbf01dc6cb73649c4cd4326182c3e44aa9dbb/protoc-gen-go/generator/name_test.go#L46)?

Adding the context here for discussion, a field with a leading underscore is converted (and therefore generated) as follows:

```
_my_field_name_2 -> XMyFieldName_2
```

**Comment by neild** [comment]
The fields in generated proto messages must be exported--i.e., they need to start with a capital letter. (If they weren't exported, code outside the generated package wouldn't be able to access the field, which would not be terribly useful.) A leading underscore is converted to an X to preserve this property.

**Comment by myitcv** [comment]
@neild @zombiezen sorry, I should have been clearer with the question.

I fully understand the initial capitalisation so that the field is exported; what I don't understand is why:

```
_my_field_name_2 -> XMyFieldName_2
```

and not:

```
_my_field_name_2 -> MyFieldName_2
```

Why the use of `X`?

**Comment by neild** [comment]
Ah, sorry for the misunderstanding.

I'm not certain why that precise behavior was chosen, although adding an initial X does prevent conflicts when two fields differ only in an initial underscore.
