### ISSUE TITLE
jsonpb ignores MarshalJSON method if present

### ISSUE THREAD

**Issue by t15k** [golang/protobuf#206]
In encoding/json custom serialisation of an object can be done by having the type implement Marshaller. This feature is not supported in jsonpb. Is it by design? Have there been previous discussion on this?

My use case is a piece of logic, forwarding message to a services, which expect some fields to be in a human readable form. In some cases we would therefore like to have structs present themselves as plain text and not as nested object JSON objects.

For example:

```
<observation:<city:New York,temperature:28,unit:CELC>>
```

Should become:

```
{"observation": "28 degrees celsius in New York"}
```

Not

```
{"observation": {"city": "New York", "temerature": 28, "unit": "CELC"}}
```

Any thoughts on how to go about his?

**Comment by zombiezen** [comment]
An interesting use-case, but I'm not sure how protobuf would support it in a language-agnostic way.  This sort of logic is application-specific, so I don't think we should build support for it into the proto package.

One way you could solve it is by writing a separate JSON wire struct &mdash; usually a good idea anyway, since it whitelists what keys you proxy:

```go

func marshalDatumJSON(datum *mypb.Datum) ([]byte, error) {
  type jsonDatum struct {
    Observation string `json:"observation"`
  }
  ob := fmt.Sprintf("%d degrees %s in %s", datum.Observation.GetTemperature(), unitName(datum.Observation.GetUnit()), datum.Observation.GetCity())
  return json.Marshal(&jsonDatum{
    Observation: ob,
  })
}
```

**Comment by t15k** [comment]
Thanks for a quick reply.
Sorry if not being clear. This was a consideration in the context of the jsonpb package, not the proto package it self.

If we could serialise with the encoding.json package, we could do something like:

    func (o *Observation) MarshalJSON() ([]byte, error) {
        return []byte("\"%d degrees %s in %s\"", o.GetTemperature(), unitName(o.GetUnit(), o.GetCity())
    }

This will attach a method to Observation, that will be used when serialising that type. This is useful, as it will introduce the custom serialisation, no matter where in a data structure Observation occurs. The example above will require duplication of the full structure of the original message.

Consider this structure:

    message Archive {
        // lots of fields
        repeated Report reports = 20;
    }
    message Report {
        string reporter_name = 1;
        repeated Observation observations = 2;
       // more fields
    }

If this structure is what you want, except the serialisation of Observation, it quickly involves as lot of seemingly redundant copy code, writing wire structs for Archive and Report, which also needs to be maintained. Also if the type, for which custom serialisation is needed, is reused in many data structures, the task of writing wire structs grows significantly.

If the jsonpb implementation took the json Marshaller in consideration when serialising, that would save considerable effort. Then only the custom logic would need to be written, in one function.

Is it by design the Marshaller should be disregarded in jsonpb, or would it be an option to add support for it?

**Comment by zombiezen** [comment]
I see. In general, we don't recommend adding your own code in the same package as the generated code, but I don't see too much harm in allowing support for it in jsonpb.

**Comment by t15k** [comment]
Thanks. I'll take a look at an implementation, and send a diff/MR you way, when I have something.

**Comment by t15k** [comment]
Hi @zombiezen.
Here's a shot at an implementation. Please take a look at:
https://github.com/golang/protobuf/compare/master...t15k:use-json-Marshaller?expand=1

**Comment by bcmills** [comment]
I think it would be a mistake to make jsonpb marshal to anything other than we well-defined protobuf JSON mapping (https://developers.google.com/protocol-buffers/docs/proto3#json).

Part of the point of protocol buffers is that they are interoperable between languages and implementations.  If what you want is "your own incompatible protobuf-like JSON format", that doesn't belong in the mainline protobuf package.

Other alternatives to consider include:

* Making the custom proto field a `string` and post-processing it separately to do the custom conversion.
* Putting the protobuf inside a larger struct with its own `MarshalJSON` method and using `encoding/json` to encode/decode it instead of `jsonpb`.  (Within your `MarshalJSON` method you could call out to `jsonpb` to decode other submessages explicitly.)

**Comment by t15k** [comment]
Thanks for the feedback. Sorry to hear your concerns.

On the alternatives
1.  Adding a custom field. Leaving fields for that practice in the core data, does not seem like the best approach to me, it makes the data structures harder to understand, and someone will use those fields other purposes not originally intended, cluttering the data even more.
2.  For large messages that will involve extra work, and extra code, which leaves more room for mistakes and bugs. Having the the option of hooking in with just a few line of code, is a powerful feature. I do know that in some communities that kind wrapping, even with the work and code overhead, is considered good practice. But, I think it's better to leave that kind of decisions to the engineers using the library. Also, to me, having to do fully wrap an re-implement feels unnatural with some of the features in Golang, like function sets.

Now on your concerns about interoperability:
First, I don't think engineers will be confused on when it's possible to read the JSON back in, adding a custom serialiser is a very explicit act.
Second, JSON is mostly useful interoperating with systems _not_ using Proto Buffers. If both system use Proto Buffers, the binary wire format is a better option for serialisation, size and speed considered.  Now for interoperability with systems not using Proto Buffers, there are systems where en engineer has full control of the JSON being produced or consumed, like a Javascript client in a browser (I do know the JS Proto implementation is improving), and there are systems where the engineer has little control of how the JSON is produced or consumed, like when exporting to a Redshift system. Now, I find in the later case, that it's extremely useful to have the ability to customise output, without having to re-implement messages in their entirety.

The Google add-on types included in the Proto Buffer project already requires custom serialisation (the XXXWellKnownTypes), extending that option to code outside the proto package, would be a powerful feature.

Hope this leaves some room for re-consideration.
The encoding/json mechanism for hooking in custom serialisation may not be best option for Proto Buffers though. Using an existing mechanism from the Go standard packages just felt right to me. Happy to hear some thoughts on that.

**Comment by bcmills** [comment]
> Having the the option of hooking in with just a few line of code, is a powerful feature.

It may be a powerful feature, but it's also one that explicitly encourages the construction of payloads that are not portable to other (conforming) JSON protobuf implementations.

> JSON is mostly useful interoperating with systems not using Proto Buffers. If both system use Proto Buffers, the binary wire format is a better option for serialisation, size and speed considered.

Sure, but the key phrase there is "interoperating".  The JSON protobuf format differs from the binary format, but it's still a *standardized* subset of JSON: the mappings from the contents of a .proto file to a JSON object and back are well-defined.

> The Google add-on types included in the Proto Buffer project already requires custom serialisation

Those "custom" serializations are standardized across protobuf implementations:
https://developers.google.com/protocol-buffers/docs/proto3#json

What you are proposing is support for a hook to allow non-standard serialization.  At that point, you're talking about "a protobuf-like JSON format", not "the JSON protobuf format" - and the former simply does not belong in the protobuf package.
