### ISSUE TITLE
protoc-gen-go set  ,import_path=mypackage_path 

### ISSUE THREAD

**Issue by likeprogrames** [golang/protobuf#212]
rezult:
import proto "mypackage_pathgithub.com/golang/protobuf/proto"

github.com/golang/protobuf/protoc-gen-go/generator/generator.go 1325
g.P("import " + g.Pkg["proto"] + " " + strconv.Quote(g.ImportPrefix+"github.com/golang/protobuf/proto"))

???
g.P("import " + g.Pkg["proto"] + " " + strconv.Quote("github.com/golang/protobuf/proto"))

**Comment by jmasonISP** [comment]
This is a duplicate of #181
