### ISSUE TITLE
proposal: proto: add EmitDefaults option to TextMarshaler

### ISSUE THREAD

**Issue by michael-berlin** [golang/protobuf#215]
By default, fields with zero values values are omitted from the output.

It would be nice to have control over this behavior. The `jsonpb.Marshaler` type has the option `EmitDefaults` exactly for this case. It would be nice to have a similar option in `TextMarshaler`.

**Comment by dsnet** [comment]
The `golang/protobuf` project is intended to be a faithful implementation of protocol buffers. It is not in the business of inventing new semantics. The C++ text marshaler has no option for this, so we won't add one either.

The fact that `jsonpb` has an `EmitDefaults` option is a historical mistake and not to be replicated.
