### ISSUE TITLE
Support Deserializing Any in Go's jsonpb

### ISSUE THREAD

**Issue by gdbelvin** [golang/protobuf#216]
Conversion of Proto3's Any type between JSON and Proto is currently unimplemented. When is implementation planned?
https://github.com/golang/protobuf/blob/master/jsonpb/jsonpb.go#L586

**Comment by ewang** [comment]
Running into issues w/ deserializing Any as well. Is there any guidance on how ptypes.UnmarshalAny/MarshalAny can be used within jsonpb?

**Comment by cybrcodr** [comment]
This should be fixed by https://github.com/golang/protobuf/commit/18c9bb3261723cd5401db4d0c9fbc5c3b6c70fe8.
