### ISSUE TITLE
Feature Request: getter method for scalar values

### ISSUE THREAD

**Issue by kerinin** [golang/protobuf#220]
The compiled code currently generates getter methods for pointer fields, which makes it convenient to call into deeply nested messages.  It would be nice if similar methods existed returning the default value of scalar fields.  For example, given the following messages:

``` proto
message Foo {
  Bar bar = 1;
}
message Bar {
  Baz baz = 1;
}
message Baz {
  string value = 1;
}
```

Compare the readability of testing the value of a nested value:

``` go
var foo *Foo

// Without scalar getters
if baz := foo.GetBar().GetBaz(); baz != nil {
  if baz.value != "" {
    // do something...
  }
}

// With scalar getters
if foo.GetBar().GetBaz().GetValue() != "" {
  // do something...
}
```

It's not a huge difference but the improved readability adds up in cases where you need to do a lot of checks like this.  It also feels more consistent - I don't have to constantly try to remember if a value has an accessor or not, or spend time trying to decide if I should use getters or just access the fields directly.

**Comment by bcmills** [comment]
I don't have a strong opinion on the getter methods, but I do want to point out that your "without" comparison case is significantly more verbose than it ought to be:

```go
// Without scalar getters
if baz := foo.GetBar().GetBaz(); baz != nil && baz.value != "" {
  // do something...
}
```

**Comment by bictorman** [comment]
We are sorely needing this, not because of verbosity but because we pre-process gRPC request in an interceptor, and currently we need to resort to reflexion to extract the field that is common to all our request.

If we could use instead have an interface type assertion it would be much cleaner.

**Comment by yurisklar** [comment]
+1

**Comment by LMMilewski** [comment]
This is fixed by https://github.com/golang/protobuf/commit/da116c3771bf4a398a43f44e069195ef1c9688ef
