### ISSUE TITLE
Support ListValue well known type

### ISSUE THREAD

**Issue by calbach** [golang/protobuf#221]
https://developers.google.com/protocol-buffers/docs/proto3#json

**Comment by atombender** [comment]
Is this issue referring to the fact that `ListValue` is serialized as `{"values": [value]}` instead of just `[value]`?

**Comment by chriswhelix** [comment]
Yes, and agree.

**Comment by cybrcodr** [comment]
Should be fixed by https://github.com/golang/protobuf/commit/18c9bb3261723cd5401db4d0c9fbc5c3b6c70fe8.
