### ISSUE TITLE
Incorrect import for 'google/protobuf/descriptor.proto' 

### ISSUE THREAD

**Issue by mcos** [golang/protobuf#222]
I'm extending protobuf `FileOptions` to add some extra custom namespacing options for a project of mine. When I compile my file, which looks like this (simplified):

``` proto
import 'google/protobuf/descriptor.proto';

extend google.protobuf.FileOptions {
  string namespace = 50002;
}
```

The resultant `go` file has the following import:

``` proto
import google_protobuf "google/protobuf"
```

and I get the following error trying to compile it:

```
$(GOPATH)/src/github.com/foo/bar.pb.go:18:8: cannot find package "google/protobuf" in any of:
$(GOPATH)/src/github.com/robinpowered/robin-entities/vendor/google/protobuf (vendor tree)
/usr/local/Cellar/go/1.6.3/libexec/src/google/protobuf (from $GOROOT)
$(GOPATH)/src/google/protobuf (from $GOPATH)
```

The import should look like this:

``` proto
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"
```

I was able to fix it by adding the `M` parameter to the `--go_out` flag:

```
--go_out=plugins=grpc,Mgoogle/protobuf/descriptor.proto=github.com/golang/protobuf/protoc-gen-go/descriptor
```

Should this behavior be expected?

**Comment by LMMilewski** [comment]
I think that what you do is correct (at least that what I always do). @zombiezen will know whether that's the preferred approach.

**Comment by zombiezen** [comment]
Your copy of descriptor.proto should include a `go_package`.  How are you obtaining this file?

**Comment by mcos** [comment]
I'm using the `descriptor.proto` from my protobuf installation.

This is the `go_package` from that file: https://github.com/google/protobuf/blob/3b001ca6ba6fb51f5e55b1596fb3ce09ee9981e8/src/google/protobuf/descriptor.proto#L43

It differs a lot from one that works: https://github.com/google/protobuf/blob/3b001ca6ba6fb51f5e55b1596fb3ce09ee9981e8/src/google/protobuf/timestamp.proto#L37

Maybe there's something up in the `descriptor` `Makefile` here: https://github.com/golang/protobuf/blob/1f49d83d9aa00e6ce4fc8258c71cc7786aec968a/protoc-gen-go/descriptor/Makefile

**Comment by Merovius** [comment]
I'm having a similar problem with google/protobuf/any.proto. The protobuf repo comes with precompiled versions of well-known types in the ptypes subdirectory. Why doesn't the compiler rewrite imports of well-known types to that? It's a dependency of any usage of proto anyway.

**Comment by neild** [comment]
The problem (as I see it):

The `go_package` option specifies the directory the proto compiler writes the generated package to. For descriptor.proto, that's `github.com/golang/protobuf/protoc-gen-go/descriptor`.

The `go_package` option also specifies the generated package name. For descriptor.proto, that's `descriptor`. (I mention this for completeness; it isn't important here.)

The package import path, however, is specified by the proto package name. For descriptor.proto, that's `google.protobuf`, so the import path is `google/protobuf`. That's obviously wrong, and the only way to fix it is to pass a M parameter to every invocation of `--go_out`.

However, there's a simple and obvious fix: `go_package` should specify the import path as well as the output directory. Conveniently, these are identical if the output directory is relative to `GOPATH`, so it's just a matter of using the current value as the import path.

This is a trivial change; I've tested it locally and it seems to work perfectly. Unless someone has a reason not to, I think we should do this.

**Comment by mrxliu** [comment]
so rubbish.

**Comment by jhump** [comment]
Pretty sure this can be closed.

**Comment by vaishalig2693** [comment]
Sorry to comment on a closed issue, but I am getting this issue on Centos Machine but not on Mac. 
protoc --version on centos : 3.3.0
protoc --version on Mac : 3.2.0
I am not able to figure out what can the actual issue.
Descriptor.proto - https://github.com/golang/protobuf/blob/master/protoc-gen-go/descriptor/descriptor.proto#L43

**Comment by jhump** [comment]
@vaishalig2693, what does the bad import line look like in your protoc 3.3.0 CentOS environment? Maybe it's possible you're using different versions of the `protoc-gen-go` plugin and/or have different versions of the golang/protobuf Go package?

**Comment by neild** [comment]
Two things to check:

1. Find the `descriptor.proto` that's being used by `protoc` in your CentOS environment. It might be useful to use `strace` to verify exactly which file it's reading. Verify that this file has a `option go_package = ...` line.
2. Make sure that you have an up-to-date `protoc-gen-go` in your CentOS environment and that `protoc` is using it.
