### ISSUE TITLE
Why was types moved to ptypes

### ISSUE THREAD

**Issue by awalterschulze** [golang/protobuf#223]
https://github.com/golang/protobuf/commit/127091107ff5f822298f1faa7487ffcf578adcf6
I am busy merging well known types into a fork of golang/protobuf
I would just like to know, since I'll probably prefer to keep the well known types in the types folder instead of the ptypes folder.

**Comment by zombiezen** [comment]
At the moment, I'm not sure (cc @okdave for comment).  I like ptypes as a name since it aligns with advice around [package names](https://golang.org/doc/effective_go.html#package-names).  In some ways, I think this is very similar to #218 (about to respond there more fully).

**Comment by okdave** [comment]
I think this was a discussion between @dsymonds and r; I wasn't involved in the reasoning (the main reason I can think of is that `types` might be confused with Go types).

**Comment by awalterschulze** [comment]
Thanks good to know.
