### ISSUE TITLE
How to differentiate unset value and zero value in protobuf3?

### ISSUE THREAD

**Issue by wanghq** [golang/protobuf#225]
As described in https://developers.google.com/protocol-buffers/docs/reference/go-generated#singular-scalar-proto2, the field type changed from pointer to raw type.

For example, if I want to update a product's title but not the price, I can just set the `Title` and leave the `Price` unpopulated. How to achieve this without pointer (proto3)? Thanks.
```
// proto2
type Product struct {
  Title *string
  Price *int64
}
// proto3
type Product struct {
  Title string
  Price int64
}
```

**Comment by bcmills** [comment]
proto3 does not allow application code to distinguish between unset and default scalar values.  (This is true across proto3 implementations in all languages, not just in Go.)

For encoding incremental updates to messages, use [FieldMask](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.FieldMask).

**Comment by wanghq** [comment]
Referencing this great discussion on [issue setting empty values](https://github.com/google/go-github/issues/19)
