### ISSUE TITLE
FieldMask is missing from ptypes directory.

### ISSUE THREAD

**Issue by tswast** [golang/protobuf#226]
I see https://github.com/google/protobuf/blob/master/src/google/protobuf/field_mask.proto is missing a go_package identifier and it does not appear in the ptypes directory with the other common proto files.

This file is needed for me to write the conformance tests in https://github.com/google/protobuf/tree/master/conformance and surely the FieldMask type would be needed in some cloud APIs.

**Comment by zombiezen** [comment]
This is a dupe of #218.  Please continue discussion there.
