### ISSUE TITLE
error when exec stringer cmd in Go1.7

### ISSUE THREAD

**Issue by xfxdev** [golang/protobuf#229]
In my project, I use 'stringer' to generate the string of enum, the code like this:
```
type myType uint8
//go:generate stringer -output constants_string.go -type=myType
const (
	myType1 myType = iota
	myType2
	myType3
)
```
In **Go1.6**, when I exec 'go generate' cmd it works well and will generate constants_string.go file.
but when I upgrade to **Go1.7**, the cmd 'go generate' has error below:

```
go generate test/main
stringer: checking package: main.go:5:2: could not import
github.com/golang/protobuf/proto (reading export data:
/Users/.../Development/workspace/project/go/pkg/darwin_amd64/
github.com/golang/protobuf/proto.a: unknown version: v1	proto
?/Users/.../Development/workspace/proje)
constant.go:18: running "stringer": exit status 1
```
my go-protobuf is the last version, so , how to solve this problem? thanks!

**Comment by zombiezen** [comment]
Sounds like you need to recompile your copy of stringer.

**Comment by xfxdev** [comment]
@zombiezen 
I delete the pkg dir and reinstall all package, now it works well, thx!
