### ISSUE TITLE
gcloud sdk 

### ISSUE THREAD

**Issue by themihai** [golang/protobuf#23]
I'm trying to deploy an application on GAE VM. Although I'm not using the protobuf package in my app the goapp command throws the error below: 
/Users/xyz/google-cloud-sdk/bin/goapp deploy ./

github.com/golang/protobuf/proto/decode.go:219: undefined: structPointer
github.com/golang/protobuf/proto/decode.go:219: undefined: field
github.com/golang/protobuf/proto/properties.go:65: undefined: structPointer
github.com/golang/protobuf/proto/properties.go:73: undefined: structPointer
github.com/golang/protobuf/proto/properties.go:82: undefined: structPointer
github.com/golang/protobuf/proto/properties.go:166: undefined: field

**Comment by themihai** [comment]
protobuf/proto/pointer_reflect.go  should include the appengine vm tag `` // +build appengine appenginevm``

**Comment by dsymonds** [comment]
No, the code is correct as is. The problem is whatever tool you are using is not properly interpreting build tags and is ignoring pointer_unsafe.go, which is fine to use on Managed VMs.
