### ISSUE TITLE
enum generated of map[string]int32 should be map[string]MyEnum

### ISSUE THREAD

**Issue by richunger** [golang/protobuf#234]
For an enum MyEnum which generates:
```
type MyEnum int32
...
var MyEnum_value = map[string]int32{
  ...
}
```
Shouldn't it generate a `map[string]MyEnum` instead? That way you could do:
```
var foo MyEnum
foo = MyEnum_value["FOO"]
```

The only other place this map is used (in unmarshalling) just casts it to an int64 anyway, so it should be fine.

**Comment by dsymonds** [comment]
No, it's intended. Those maps are principally for internal use (e.g. for the text formatter) and having them all be the same type (`map[string]int32`) means that the code doesn't need reflection to operate on them. They are used fairly rarely in human-written code.
