### ISSUE TITLE
wrong size calculation for slice of structs with marshalers

### ISSUE THREAD

**Issue by awalterschulze** [golang/protobuf#236]
The tagcode is size is counted twice
here
https://github.com/golang/protobuf/blob/master/proto/encode.go#L1006
and here
https://github.com/golang/protobuf/blob/master/proto/encode.go#L1017

**Comment by bcmills** [comment]
I have a fix pending.  Might be a couple days before I can pull it into GitHub.

**Comment by awalterschulze** [comment]
Ok but its a one line fix.
Just delete
https://github.com/golang/protobuf/blob/master/proto/encode.go#L1017

**Comment by bcmills** [comment]
Yeah, and then you need to add tests, and fix other issues the new tests uncover, and synchronize a couple different repos...

A proper fix is more than one line.  It's on the way.

**Comment by awalterschulze** [comment]
fair enough :-)

**Comment by awalterschulze** [comment]
+1
