### ISSUE TITLE
Codegen plugin outside repo

### ISSUE THREAD

**Issue by breerly** [golang/protobuf#245]
Is it possible to create a codegen plugin outside the repo?

For example, it looks like the GRPC's plugin is actually located in this repo?

https://github.com/grpc/grpc-go/blob/master/Makefile#L18

How would another RPC system write a plugin?

Thanks

**Comment by bcmills** [comment]
You would need to compile the plugin into the protoc-gen-go binary.

(See [protoc-gen-go/link_grpc.go](https://github.com/golang/protobuf/blob/master/protoc-gen-go/link_grpc.go) for how this is done for `grpc`.)
