### ISSUE TITLE
Setting `jsonpb.Marshaler`'s EmitDefaults causes the opposite behavior

### ISSUE THREAD

**Issue by liranp** [golang/protobuf#246]
Hi,

When using `jsonpb.Marshaler` with `EmitDefaults` (true or false) the opposite behavior occurs.

Here is a gist which reproduces this:

https://gist.github.com/liranp/4ac9a76719f3875dbca64f74a5061670

The offending line is [jsonpb.go:189](https://github.com/golang/protobuf/blob/master/jsonpb/jsonpb.go#L189):

```go
if !m.EmitDefaults {
   ...
}
```

Should be:

```go
if m.EmitDefaults {
   ...
}
```

Also, [jsonpb_test.go:352](https://github.com/golang/protobuf/blob/master/jsonpb/jsonpb_test.go#L352) seems to be wrong.

**Comment by dsymonds** [comment]
Are you mixing up "emit" and "omit"? The former, which is in this API, means to produce, but the latter means to not produce. To "emit defaults" means to include default values in the output.

**Comment by liranp** [comment]
Oh! My bad. You're definitely right :)
