### ISSUE TITLE
oneof type not decoded in proto3

### ISSUE THREAD

**Issue by songtianyi** [golang/protobuf#251]
#### example proto

````
syntax = "proto3";
package rrfp;

message Message {
	Head hd = 10;
	Body by	= 20;
}

message Head {
	string sesionNo	= 10;
	string uniqueId	= 20;
}

message Body {
	oneof msgType {
		ExampleEchoRequest example_echo_request = 10;
		ExampleEchoResponse example_echo_response = 20;
	}
}

message ExampleEchoRequest {
	string msg = 10;
}
message ExampleEchoResponse {
	string msg = 10;
}
````
#### example marshal & unmarshal code
````
package main

import (
	"fmt"
	"rrframework/utils"
	"./proto/rrfp"
	"rrframework/serializer/protobuf/proto"
)

func main() {
	msg := new(rrfp.Message)
	msg.Hd = &rrfp.Head{
		rrutils.NewV4().String(),
		"rrfp.ExampleEchoRequest",
	}
	msg.By = &rrfp.Body{
		MsgType: &rrfp.Body_ExampleEchoRequest{
			ExampleEchoRequest: &rrfp.ExampleEchoRequest{ Msg: "hello world!" },
		},
	}
	fmt.Println("before marshal:", msg)
        b, err := proto.Marshal(msg)
        if err != nil {
            fmt.Println(err)
            return
        }

	// unmarshal
	m := new(rrfp.Message)
	if err := proto.Unmarshal(b, m); err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println("after unmarshal:", m)
	fmt.Println("m.GetBy()", m.GetBy())
	fmt.Println("m.GetBy().GetMsgType()", m.GetBy().GetMsgType())
	fmt.Println("m.GetBy().GetExampleEchoRequest()", m.GetBy().GetExampleEchoRequest())
}

````
#### Here it's the output of code above. 
Nothing in m.GetBy(). I'm not sure it's a bug or i haven't used oneof type properly.
````
before marshal: hd:<sesionNo:"9a422afd-e36c-4660-8b9a-86da38946de0" uniqueId:"rrfp.ExampleEchoRequest" > by:<example_echo_request:<msg:"hello world!" > >
after unmarshal: hd:<sesionNo:"9a422afd-e36c-4660-8b9a-86da38946de0" uniqueId:"rrfp.ExampleEchoRequest" > by:<>
m.GetBy()
m.GetBy().GetMsgType() <nil>
m.GetBy().GetExampleEchoRequest() <nil>
````

**Comment by bcmills** [comment]
Your example code discards an error:
```go
	b, _ := proto.Marshal(msg)
```

That's an important data point: does Marshal return an error?  If so, what?

**Comment by songtianyi** [comment]
@bcmills 
Sorry, my mistake. But the error returned is nil.

**Comment by songtianyi** [comment]
I tried to checkout if the program has encoded oneof type in func **enc_struct**
````
    // Do oneof fields.
    if prop.oneofMarshaler != nil {
        fmt.Println("haha oneof")
        m := structPointer_Interface(base, prop.stype).(Message)
        if err := prop.oneofMarshaler(m, o); err == ErrNil {
            return errOneofHasNil
        } else if err != nil {
            return err
        }
    }
````
The string i try to print out didn't show up in the result. Variable **prop.oneofMarshaler** is nil.

**Comment by bcmills** [comment]
I notice that your import path is `"rrframework/serializer/protobuf/proto"` rather than `""github.com/golang/protobuf/proto"`.  Please provide steps to reproduce the error using the mainline proto package without `rrframework`.

**Comment by songtianyi** [comment]
@bcmills 
I tried as you said, it works. So i was confused what's going wrong with my golang/protobuf code which **cloned from official git**.
Then i updated my golang/protobuf code to the **latest** from official git, it works well as using "github.com/golang/protobuf/proto". But when i checkout the master branch to commit **da116c3771bf4a398a43f44e069195ef1c9688ef**, the issue described before **occured** again.
My problem was solved with your help 👍 , thanks a lot. But i think commit **da116c3771bf4a398a43f44e069195ef1c9688ef** is doing wrong with proto3.

**Comment by bcmills** [comment]
The `protobuf` package uses a registration mechanism.  The packages generated by the protocol compiler will only register with the package at the path known to it (i.e. `"github.com/golang/protobuf/proto"`).

**Comment by songtianyi** [comment]
@bcmills 
You mean they are not exactly the same after some proto files compiled? The package which the protocol compiler using has been changed?

**Comment by bcmills** [comment]
The packages output by the protocol compiler register themselves with exactly one `proto` package: the one passed to the protocol compiler.  If you have some other `proto` package in your source tree, they won't know about it and won't register with it.

**Comment by songtianyi** [comment]
@bcmills 
Understood. thanks a lot 👍
