### ISSUE TITLE
protoc-gen-go: duplicated fileDescriptor13 redeclared in this block

### ISSUE THREAD

**Issue by thomasmodeneis** [golang/protobuf#259]
Hi,

I'm having issues with compiling, its trowing me this error:
test/get_package_details.pb.go:116: fileDescriptor13 redeclared in this block
        previous declaration at test/get_facilities.pb.go:78

This are the blocks that are with the duplication problem:
```
func (*GetPackageDetailsResponse) Descriptor() ([]byte, []int) {
return fileDescriptor13, []int{1}
}
```

```
func init() {
proto.RegisterFile("github.com/test/test/get_facilities.proto", fileDescriptor13)
}
```

Right now I'm finding it very difficult to identify the cause + the version that is used to compile the proto files, its such a complicated problem; The team I'm working with, decided it was a good idea to host their own protobuf fork, compile and use that specific version, and progressively update the fork.

I've identified the commit version that is causing me this error:
`https://github.com/golang/protobuf/commit/a66a4fa9a8dd2304462f7aad7161e8bf53eee461`

I would like to understand a bit better about the problem, right now I'm not sure if its all related to protobufs, or if there is something else "homemade" that is causing me this problems, as well how to work around this, specially the fact that the protoc-gen-go has no `protoc-gen-go --version`, correct me if I'm wrong but how can I identify the version the protoc-gen-go is currently using ? Should I base myself on what `protoc --version` returns ?

Also, I would like to understand another thing:
Given I have installed protoc-gen-go on my GOPATH, but I have another inside /vendor folder and I'm using this one to compile with the following command: `$$PATH:$$PWD/vendor/protobuf/bin/protobuild.sh` (have in mind protobuild.sh is using the compiled protoc-gen-go inside vendor)

Which version will be used ? the version inside PATH or the version inside vendor folder ?

Cheers.

**Comment by neild** [comment]
Yes, this sort of thing can't happen after 9d4962b4.

**Comment by neild** [comment]
> I would like to understand a bit better about the problem, right now I'm not sure if its all related to protobufs, or if there is something else "homemade" that is causing me this problems, as well how to work around this, specially the fact that the protoc-gen-go has no protoc-gen-go --version, correct me if I'm wrong but how can I identify the version the protoc-gen-go is currently using ? Should I base myself on what protoc --version returns ?

There's unfortunately no way to tell what version of protoc-gen-go you're using at the moment. We should fix that.

> Given I have installed protoc-gen-go on my GOPATH, but I have another inside /vendor folder and I'm using this one to compile with the following command: $$PATH:$$PWD/vendor/protobuf/bin/protobuild.sh (have in mind protobuild.sh is using the compiled protoc-gen-go inside vendor)

The `protoc` compiler will use the `protoc-gen-go` on your `PATH` (not `GOPATH`). You can also override it with `--plugin=protoc-gen-go=/path/to/your/protoc-gen-go`.
