### ISSUE TITLE
Incorrect import path for descriptor.proto

### ISSUE THREAD

**Issue by pongad** [golang/protobuf#270]
`descriptor/descriptor.go` depends on `"google.golang.org/genproto/protobuf"` for proto artifacts generated from [descriptor.proto](https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.proto).  The import path should instead be `github.com/golang/protobuf/protoc-gen-go/descriptor`.

CC https://github.com/google/go-genproto/issues/18

**Comment by Kulak** [comment]
If project is loaded in Eclipse GO, then it catches this error.  I had to change import line to be:

    protobuf "github.com/golang/protobuf/descriptor"

**Comment by natefinch** [comment]
I'm hitting this problem, too.

**Comment by neild** [comment]
Many apologies for the delay in addressing this, and thank you for the fix.
