### ISSUE TITLE
Pack() and Unpack() for the Any type

### ISSUE THREAD

**Issue by F21** [golang/protobuf#277]
The documentation shows the the libraries for C++ and Java contains `pack()` and `unpack()` to safely serialize values to be used with the `Any` type.

It would be nice if these methods can be implemented in the golang library as well, to make working with `Any` easier.

**Comment by bcmills** [comment]
Does the [`ptypes`](https://godoc.org/github.com/golang/protobuf/ptypes)` package not do what you need?

**Comment by F21** [comment]
Thanks, `MarshalAny()` and `UnmarshalAny()` should do it.
