### ISSUE TITLE
Deserializing dynamic/any types from envelopes.

### ISSUE THREAD

**Issue by rogeralsing** [golang/protobuf#281]
Another cross post from Gogo protobuf.
https://github.com/gogo/protobuf/issues/255

In Proto.Actor, we have this bit of code for deserializing any proto message from our envelope type like so:

```go
func deserialize(message *MessageEnvelope) proto.Message {
	t1 := proto.MessageType(message.TypeName) //get the go type from the proto type name
        t := t1.Elem() 
	intPtr := reflect.New(t) //create an instance of the type
	instance := intPtr.Interface().(proto.Message)  //get the message data from the envelope
	proto.Unmarshal(message.MessageData, instance) //fill the instance with the data 

	return instance
}
```

This works, but it feels somewhat hacky to have to resort to reflection here.

In C# using Protobuf, we only need to do:

```csharp
public static object Deserialize(string typeName, ByteString bytes)
{
    var parser = TypeLookup[typeName];
    var o = parser.ParseFrom(bytes);
    return o;
}
```

I can however not see any such infrastructure in Go. 
Is there a better way of solving the above or is that as good as it gets?

I do know about protobuf "Any" types, but AFAIK, not all languages have support for that yet.
Making the Any type a no go for cross platform integration (please correct me if Im wrong)
https://developers.google.com/protocol-buffers/docs/proto3#any
>Currently the runtime libraries for working with Any types are under development.

**From a reply on the Gogo tracker:**

Yes this almost exactly what the Any type does.
Hmmm
If golang/protobuf rather registers a new function

    proto.RegisterMessage(func () proto.Message {
       return &generatedType{}
    })

Then you would simply be able to call the function.
Maybe you can take this issue up with them.
If they change it, then we can merge it into gogoprotobuf.

**Comment by bcmills** [comment]
Any is a regular proto3 message type (defined in a .proto file): any language which supports proto3 at all should be compatible with it.

The only thing special about Any is that the proto runtime library for most languages has extra decoding support. (For Go, that's the ptypes package.)

**Comment by bcmills** [comment]
And, FWIW, if your generated gogoprotobuf type implements `proto.Message` you should already be able to use `ptypes` with it as long gogoprotobuf (or your application) calls [`proto.RegisterType`](https://godoc.org/github.com/golang/protobuf/proto#RegisterType) with appropriate arguments.

**Comment by rogeralsing** [comment]
The ptypes lib requires you to still pass in an instance of the expected Go type into `UnmarshallAny`, which still forces you to know upfront what kind of object it is you want to deserialize.

I'm not seeing how I can use ptypes to get an actual instance out of it w/o resorting to reflection before the call?
What am I missing?

**Comment by bcmills** [comment]
Use [ptypes.DynamicAny](https://godoc.org/github.com/golang/protobuf/ptypes#DynamicAny).

**Comment by rogeralsing** [comment]
Thanks, that however leads us back to #279
Using Any type seems broken on Windows, when using protoc as the mapped paths to the imports cannot be resolved. but that is a separate issue.
