### ISSUE TITLE
Converting an arbitary value to a struct.Value with jsonpb

### ISSUE THREAD

**Issue by F21** [golang/protobuf#285]
I am using grpc to build a GraphQL server. With GraphQL, the response is some arbitrary JSON depending on what fields the client requested in the query. I currently have it working with a custom JSON codec and modified generated GRPC code, but it would be nice to not have to modify the generated GRPC code to allow code-gen for other languages.

In terms of GraphQL, the library I am using will return a [graphql.Response](https://godoc.org/github.com/neelance/graphql-go#Response). The problem is that in the response structure, `Data` is an `interface{}`. Without grpc, I would just pass the `graphql.Response` to `json.Marhsal` to get the resulting JSON.

However, since I want to use `jsonpb`, is there some way to turn an `interface{}` into a `struct.Value` automatically?

**Comment by cybrcodr** [comment]
Sorry for the late response.  I noticed that graphql.Response.Data is now a json.RawMessage which will marshal directly to the JSON bytes within.  I'm guessing this is no longer an issue then.  Feel free to reopen if there's still a problem or you have more related questions.
