### ISSUE TITLE
JSON encoding of Int?

### ISSUE THREAD

**Issue by kellrott** [golang/protobuf#288]
It seems the when the JSON encoder encounters an Int64, it encodes it as string. The logic can be found at https://github.com/golang/protobuf/blob/master/jsonpb/jsonpb.go#L502 So that when it finds an integer is manually quotes it into a string.
This seems wrong. And it causes problems in my code (having to manually reconvert back to an int on the client side). Am I missing something?

**Comment by bcmills** [comment]
If you're interacting with JSON-encoded protocol buffers, you need string-to-int conversion on the client side anyway.  See https://developers.google.com/protocol-buffers/docs/proto3#json.
