### ISSUE TITLE
invalid import path in descriptor/descriptor.go

### ISSUE THREAD

**Issue by junghoahnsc** [golang/protobuf#292]
Hello,

`descriptor/descriptor.go` is importing `"google.golang.org/genproto/protobuf"`
https://github.com/golang/protobuf/blob/master/descriptor/descriptor.go#L46,
but it's removed.

Shouldn't it be `github.com/golang/protobuf/protoc-gen-go/descriptor` ?

Thanks,

**Comment by bcmills** [comment]
It is, as of https://github.com/golang/protobuf/commit/f0b293ef371b932d8fddb6841432a7a4404d5fe0.
