### ISSUE TITLE
why `kind` （ptypes/struct/struct.proto)

### ISSUE THREAD

**Issue by RyanKung** [golang/protobuf#294]
https://github.com/golang/protobuf/blob/master/ptypes/struct/struct.proto#L65

So I have to do:
```
data := protobuf.Value{}
data.Kind = &protobuf.Value_StringValue{StringValue: "bar"}
```

It's strange, I mean it's setting a `value` to the `kind` property of the Obj.
I think it should be like

`data.Value = &protobuf.Value_StringValue{StringValue: "bar"}`

or other better way

**Comment by bcmills** [comment]
That's how it's defined upstream:
https://github.com/google/protobuf/blob/master/src/google/protobuf/struct.proto

You can write it as a Go literal like:

```go
data := protobuf.Value{
  Kind: &protobuf.Value_StringValue{StringValue: "bar"},
}
```

**Comment by RyanKung** [comment]
Yeah, I know where/how it defined, I just think it's, uh, ugly.
