### ISSUE TITLE
Any reason for not using golang.org/x/protobuf import path?

### ISSUE THREAD

**Issue by karalabe** [golang/protobuf#3]
@dsymonds 

As almost all other tools (e.g. oauth2) uses it, why does this repo use the barebone github path instead of the vanity ones? Wouldn't it make more sense to switch over?

**Comment by dsymonds** [comment]
`protobuf` is a Google-linked technology, much more so than oauth2 and similar, and is pretty independent of the Go project itself. It could perhaps be something like google.golang.org/protobuf, but I'm not sure it actually buys much.

@robpike and @adg might have thoughts.

**Comment by robpike** [comment]
I agree with David. It's fine as is.

**Comment by dsymonds** [comment]
In the interest of closure I'm going to close this bug. We can always revisit this down the track.

**Comment by karalabe** [comment]
Ok, I can accept the reasoning. Was just curious if it's by design or if it was just accidentally forgotten. Thx!
