### ISSUE TITLE
go test failed

### ISSUE THREAD

**Issue by chai2010** [golang/protobuf#30]
```
go test github.com/golang/protobuf/proto
# github.com/golang/protobuf/proto
proto3_test.go:38:2: no buildable Go source files in C:\go\gopkg.stable\src\github.com\golang\protobuf\proto\proto3_proto
FAIL    github.com/golang/protobuf/proto [setup failed]
```

**Comment by dsymonds** [comment]
If you want to run tests, run `make test` from that directory.

**Comment by chai2010** [comment]
make test failed on windows:

```
mingw32-make test
go install
make install
process_begin: CreateProcess(NULL, make install, ...) failed.
make (e=2):
Makefile:40: recipe for target 'generate-test-pbs' failed
mingw32-make: *** [generate-test-pbs] Error 2
```

**Comment by dsymonds** [comment]
Sorry, I don't have a Windows machine and don't have any idea why that's failing for you.

**Comment by chai2010** [comment]
And the `testdata\test.pb.go` exists, i think `proto3_proto\proto3.pb.go` also need exist.

I have `protoc.exe`(ver3.0.0) and `protoc-gen-go.exe`, but i don't know how to generate `proto3_proto\proto3.pb.go`.
Can you help me?

If `protoc.exe`(ver3.0.0) and `protoc-gen-go.exe` works, i can try to fix the Makefile issue.

**Comment by chai2010** [comment]
I suggest reopen this issue, and change the tittle to: `make test failed on windows`
