### ISSUE TITLE
Compile failure about *.pb.go

### ISSUE THREAD

**Issue by leonwanghui** [golang/protobuf#300]
Hi everyone,
I'm a new guy and I started to use grpc a couple of days ago. I followed the tutorial (http://www.grpc.io/docs/quickstart/go.html#build-the-example) to set up all pre-configurations and after I made modifies with my *.proto, I use protoc to generate my *.pb.go, then I found an error when I want to build this file:
***undefined: grpc.SupportPackageIsVersion4***
But if I remove this line in *.pb.go, then everything works well.
IMO, the latest version of grpc is v3.2.x, so I have no idea where does this error comes. I would appreciate it if anyone could give some suggestions.

**Comment by dsnet** [comment]
Sounds like you don't have the `grpc` package available. This is a question better asked on https://github.com/grpc/grpc
