### ISSUE TITLE
protoc-gen-go hangs on mac OS X sierra

### ISSUE THREAD

**Issue by brobits** [golang/protobuf#303]
I have installed protobuf-3.0.0, built from source and installed on my system, from [here](https://developers.google.com/protocol-buffers/)

I have a working go compiler (go1.8 darwin/amd64)

I have run `go get -u github.com/golang/protobuf/{proto,protoc-gen-go}` and have obtained a `protoc-gen-go` binary in `$GOPATH/bin`

But, when I run `proto-gen-go`, even without parameters, execution hangs.  `protoc --go_out` works just fine.

Has anyone run into this before?  What could cause these hangs?  Any shared dependencies which could cause this?

*Edit*

I have found this digging through docs:

> provides a protoc-gen-go binary which protoc uses when invoked with the --go_out command-line flag. The --go_out flag tells the compiler where to write the Go source files. The compiler creates a single source file for each .proto file input.

Looks like this is just a case of misusing protoc-gen-go: it's intended to be invoked by protoc, not directly invoked.  Would be nice to have an error if it's directly invoked rather than hanging, though.

**Comment by brobits** [comment]
It also appears dtrace is denied somewhere in the call stack:

```
open("/dev/urandom\0", 0x0, 0x0)		 = 3 0
dtrace: error on enabled probe ID 2134 (ID 163: syscall::read:return): invalid kernel access in action #12 at DIF offset 92
close(0x3)		 = 0 0
__pthread_sigmask(0x3, 0x0, 0x127B058)		 = 0 0
bsdthread_register(0x104E7C0, 0x0, 0x0)		 = -1 Err#22
dtrace: error on enabled probe ID 2132 (ID 165: syscall::write:return): invalid kernel access in action #12 at DIF offset 92
dtrace: error on enabled probe ID 2132 (ID 165: syscall::write:return): invalid kernel access in action #12 at DIF offset 92
dtrace: error on enabled probe ID 2132 (ID 165: syscall::write:return): invalid kernel access in action #12 at DIF offset 92
select(0x0, 0x0, 0x0, 0x0, 0x7FFF5FBFF378)		 = 0 0
select(0x0, 0x0, 0x0, 0x0, 0x7FFF5FBFF378)		 = 0 0
dtrace: error on enabled probe ID 2132 (ID 165: syscall::write:return): invalid kernel access in action #12 at DIF offset 92
```

**Comment by danlg** [comment]
@brobits how did you solve it ?

**Comment by larzen** [comment]
I have the same behavior. I have mac OS X sierra 10.12.6, go 1.8.3.

Any news on how to fix it?

**Comment by cybrcodr** [comment]
Just fyi.  The protobuf repo release page https://github.com/google/protobuf/releases does have links to zip files containing the pre-built protoc binary as well, e.g. protoc-3.3.0-osx-x86_64.zip.  Ones with prefix protoc- contains pre-built binary for a specific platform.

**Comment by ClayShentrup** [comment]
`brew install protoc`

**Comment by brobits** [comment]
@danlg everyone else here is correct: while `protoc-gen-go` produces golang bindings for protocol buffers, it must be invoked by `protoc`.  unfortunately, I don't think `go get -u https://.../protoc-gen-go` also provides the `protoc` binary, which must be directly invoked.

short answer: install `protoc` from source, then run `protoc` to generate Golang bindings.   `protoc` will call into `protoc-gen-go`.

**Comment by puellanivis** [comment]
It should be noted: execution does not hang. It is instead blocking on reading from STDIN.

If you hit CTRL-D, to signal an EOF for STDIN, then execution will quit with a log message `protoc-gen-go: error:no files to generate`

**Comment by dsnet** [comment]
#239 should help address accidental direct invocation of protoc-gen-go

**Comment by brobits** [comment]
@puellanivis good find, although I do wish it were better documented to prevent new users from scratching their heads when they invoke this directly from a shell and don't produce anything on STDIN, effectively thinking execution is hanging on something besides input.

**Comment by dsnet** [comment]
@mayank-dixit, that is a question for [Homebrew package manager](https://github.com/Homebrew). This repository is only responsible for implementing protocol buffers for Go, and not how that code is distributed to other operating systems and platforms.

**Comment by ephemeral** [comment]
@mayank-dixit `brew install protobuf`

**Comment by wildneuro** [comment]
> @mayank-dixit `brew install protobuf`

Thanks, worked!
