### ISSUE TITLE
when "repeated field items has nil element" occur, protobuf send data will timeout

### ISSUE THREAD

**Issue by wednesdaysunny** [golang/protobuf#307]
Hello:
        when I set response a array, and array has only on element, and this element is nil, it will occur "repeated field items has nil element" error, and when this error occur, protobuf send data will timeout, can you help me?
        Thank you very much.

**Comment by rvegas** [comment]
I have the same problem, did you find a solution?

**Comment by metrue** [comment]
@wednesdaysunny  You may need to post out your source then people can see what's going on here?

**Comment by dsnet** [comment]
Closing issue as stale. There is insufficient information to address this. If you have a reproduction, file a new issue. Thanks.

**Comment by ryanking8215** [comment]
I had the same problem. 

I built a sample at https://github.com/ryanking8215/pb_nil_element

**Comment by neild** [comment]
Repeated fields aren't allowed to contain `nil` messages, and many operations (`Marshal`, probably others) will panic if they encounter one.

The v2 API does permit `nil` values in repeated message fields, but until it is released you'll need to avoid them.

**Comment by calthomson** [comment]
@neild 

> The v2 API does permit nil values in repeated message fields, but until it is released you'll need to avoid them.

Is there documentation about that change somewhere, like a roadmap?
