### ISSUE TITLE
Remove references to RawMessage

### ISSUE THREAD

**Issue by tamird** [golang/protobuf#311]
The code contains a few references to this type, including `type raw interface { Bytes() []byte }` which is supposed to be implemented by `RawMessage`. Unfortunately, that method signature is not as uncommon as one would hope, which can cause bad interactions when that function is implemented on generated structs or their constituent fields (e.g. via github.com/gogo/protobuf's `customtype` option).

My question is: is RawMessage still a thing? If yes, what is it? If no, would you accept a PR removing "support" for it?

cc @dsymonds

**Comment by bcmills** [comment]
It's an internal thing.  It is supposed to allow for certain functions (e.g. proxy servers) to work with serialized protocol messages directly without the overhead of marshaling and unmarshaling.

I agree that the interface we use to detect it is awkwardly broad.

**Comment by bcmills** [comment]
(We can't remove it, but perhaps we can make it less prone to collisions.)

**Comment by tamird** [comment]
Does it need to stay an interface? I could imagine replacing `raw` with `type RawMessage []byte`. What do you think?

**Comment by bcmills** [comment]
It has to correspond to some exported concrete type somewhere, or else nobody can use it.

It might make sense to promote to a concrete type into the `proto` package itself, though.

**Comment by bcmills** [comment]
The proposed change would need a bit of a complicated internal migration.  Unfortunately, I don't think this will work as a PR (sorry!).

**Comment by tamird** [comment]
No problem. What can I do to help?

**Comment by tamird** [comment]
Hello. Now that `dev` is a thing, is there something to be done to move this forward? Is it even still a problem?

**Comment by dsnet** [comment]
I'm out-of-office for 2 weeks. I'm not going to think about this till I get back.

**Comment by dsnet** [comment]
Support `RawMessage` was a gross hack that I wish was never added. I'm okay with changing the signature of the internal type to be something like `ProtoRawBytes()` to avoid conflicts and define that on the internal `RawMessage` type.

@bcmills, do you forsee any issues with that?

**Comment by bcmills** [comment]
None that I can immediately think of.

**Comment by dsnet** [comment]
Alright, I'll work on making the appropriate changes internally and push it to `dev`.

**Comment by tamird** [comment]
(this issue has remained open because #482 was merged to `dev`, and `master` is still the primary branch).

**Comment by dsnet** [comment]
Closing this as the merge work will be tracked in #479.
