### ISSUE TITLE
proposal: add ptypes.MustTimestampProto, ptypes.MustTimestamp

### ISSUE THREAD

**Issue by kevinburke** [golang/protobuf#319]
Currently ptypes.Timestamp and ptypes.TimestampProto return two values, a value and an error. In many cases we can assume that a time.Time is well formed, e.g. the nanosecond value is in the proper range.

It would be nice to add ptypes.MustTimestamp or similar which panics if the timestamp is out of range.

**Comment by bcmills** [comment]
An exported `Must` function in a Go API generally signals something that ought to be done at init-time (e.g. `regexp.MustCompile`, `template.Must`).  `TimestampProto` is rarely called during init, so a `Must` function for it would be confusing: it would send the signal "someone thinks you should call this in an `init` function", but we don't actually think that in general.

I've seen enough inappropriate use of `Must` functions in code reviews to believe that folks tend to see those as reasonable defaults for run-time behaviors in production code (e.g. CLIs).  They're not: passing a bad flag to a CLI should result in a helpful error message, not a giant goroutine dump.

----

That said, we already have a change pending to add a `TimestampNow` function for the common use-case of constructing a `Timestamp` message from a call to `time.Now()`, which we really do know is safe for the next 6000 years or so.  We should go ahead and export that to the public repo.
