### ISSUE TITLE
go get -u github.com/golang/protobuf/{proto,protoc-gen-go}" gives an error - no buildable Go source files in proto3_proto

### ISSUE THREAD

**Issue by dmitris** [golang/protobuf#32]
When I run ```go get -u github.com/golang/protobuf/{proto,protoc-gen-go}``` as instructed in README I keep getting the following error (with Go 1.4.2 on Linux and Mac):
```
$ go get -u -t -v -f github.com/golang/protobuf/{proto,protoc-gen-go}
github.com/golang/protobuf (download)
package github.com/golang/protobuf/proto
	imports github.com/golang/protobuf/proto/proto3_proto
	imports github.com/golang/protobuf/proto/proto3_proto
	imports github.com/golang/protobuf/proto/proto3_proto: no buildable Go source files in /home/dmitris/go/src/github.com/golang/protobuf/proto/proto3_proto
```

Should this error be ignored? (the protobuf directory does get checked out, and you can ```go install ./...``` in it).  But ignoring errors seem contrary to the Go spirit :smile:  - maybe it would be possible to add a dummy file in https://github.com/golang/protobuf/tree/master/proto/proto3_proto to prevent the error (not sure what is the standard and recommended way to deal with such - would be interested since it comes up in other places as well).  Thanks!

**Comment by dsymonds** [comment]
I don't know why that file was missing. I'll add it.
