### ISSUE TITLE
Version tags?

### ISSUE THREAD

**Issue by jsha** [golang/protobuf#328]
For users of grpc, matching versions between the grpc support package and protoc-gen-go is important. Would you consider tagging releases? Right now on the letsencrypt/boulder project, we check out a specific commit id to make sure we are using a compatible version. It would be nicer to check out a semantically versioned tag.

Thanks,
Jacob

**Comment by dghubble** [comment]
I agree it would be valuable to have semantic release tags every so often. However, the authors seem to have closed 3 prior issues asking for this as well.

**Comment by jsha** [comment]
Thanks for pointing that out! Hopefully release tags are more appealing now, since https://github.com/golang/protobuf/issues/264 has demonstrated a concrete use case where versioned releases are important. That issue was my motivation for filing this issue: We were unable to upgrade our protoc-gen-go and grpc packages in Boulder for several months because of an incompatibility at HEAD.

**Comment by sulliwane** [comment]
With [go dep](https://github.com/golang/dep) arriving soon in every gopher's toolbox, a [semver](http://semver.org/) versioning for protobuf (git tag -a v1.0.0 -m 'v1.0.0') would be awsome!

Related issues:
* https://github.com/golang/protobuf/issues/384
* https://github.com/golang/protobuf/issues/260
* https://github.com/golang/protobuf/issues/389
* https://github.com/golang/protobuf/issues/161
* https://github.com/golang/protobuf/issues/69

**Comment by AlekSi** [comment]
[v1.0.0](https://github.com/golang/protobuf/tree/v1.0.0) is tagged! 🎉 See this [go-nuts thread](https://groups.google.com/d/topic/golang-nuts/F5xFHTfwRnY/discussion).

**Comment by dsnet** [comment]
I guess this is done then. :)

**Comment by AlekSi** [comment]
Next request 😆: #502.
