### ISSUE TITLE
jsonpb should support custom JSON serialization

### ISSUE THREAD

**Issue by jhump** [golang/protobuf#331]
This would be done by delegating to the message if it implements `json.Marshaler` or `json.Unmarshaler`.

FWIW, this could simplify how the well-known types are handled, e.g. no need to special-case them in this package. (So, in a way, this issue relates to #169.)

Both the binary and text encodings already support the same concept, where a message can implement a particular interface (proto.Marshaler/proto.Unmarshaler, encoding.TextMarshaler/encoding.TextUnmarshaler) to customize serialization/de-serialization. This just extends that same concept to JSON encoding/decoding.

I've also opened a pull request that implements the change: https://github.com/golang/protobuf/pull/325

I think consistency with binary and text marshaling is a reasonable justification for the change. But I also have my own reason for the change: allow users of a [dynamic message library](https://godoc.org/github.com/jhump/protoreflect/dynamic) to use `jsonpb` as they would with any other `proto.Message`.

**Comment by jhump** [comment]
ping

**Comment by jhump** [comment]
@bcmills, pinging you since `git blame` identifies you as the last to touch the jsonpb package. Mind giving this a brief glance?

**Comment by bcmills** [comment]
"Last to touch the package" isn't a great heuristic.  I think @dsnet, @cherrymui, and @randall77 have been working on proto stuff lately.

**Comment by jhump** [comment]
>"Last to touch the package" isn't a great heuristic.

Agreed, it isn't. But outsiders have pretty poor visibility into anything better, and I was hoping to get some feedback on this vs. letting it languish like so many other issues and pull requests.

Thanks for tagging the relevant folks!

**Comment by dsnet** [comment]
\cc @cybrcodr, who will be handling some of the jsonpb-related PRs and issues.

**Comment by jhump** [comment]
@cybrcodr: ping

**Comment by cybrcodr** [comment]
I think this sounds reasonable for dynamic messages.  But it would be better for WKT's JSON (de)serialization be as implemented right now.  I'll review your PR soon.

**Comment by dsnet** [comment]
Fixed in #325
