### ISSUE TITLE
unmarshal - bad map data tag

### ISSUE THREAD

**Issue by piotrkowalczuk** [golang/protobuf#334]
Hi guys,

Im getting such error on server side: `grpc: failed to unmarshal the received message proto: bad map data tag 98`.

Server protobuf version: `2bc9827a78f95c6665b5fe0abd1fd66b496ae2d8`
Client protobuf version: `2bc9827a78f95c6665b5fe0abd1fd66b496ae2d8`

It happens for message like:

```
message Request {
    map<string, bool> sort = 1;
}
```

cheers

**Comment by tiaguinho** [comment]
Can you show the message sent?

**Comment by piotrkowalczuk** [comment]
Problem solved. `FileDescriptor` on client side was different. `go get -u` and regeneration fixed the problem.
