### ISSUE TITLE
Question: move to Go 1.7+ stdlib 'context' package?

### ISSUE THREAD

**Issue by gyuho** [golang/protobuf#336]
Following https://github.com/golang/protobuf/pull/326 and https://github.com/golang/protobuf/pull/326#issuecomment-290830498

So `golang/protobuf`'s plan is wait until Go 1.9?
We just want to know the timeline (c.f. https://github.com/coreos/etcd/issues/6174, https://github.com/coreos/etcd/issues/7790).

Any updates?

Thanks!

**Comment by gyuho** [comment]
I talked to @dfawley yesterday in person. And think we are ok with waiting for type alias in Go 1.9.

Thanks.

**Comment by Tim15** [comment]
Any updates on this?

**Comment by dfawley** [comment]
See https://github.com/grpc/grpc-go/issues/711 for some discussion on why we are not going to do this until Go 1.9 is grpc-go's oldest supported version (tl;dr: we need everyone to have type aliases to avoid breaking backward grpc/protoc compatibility).

**Comment by dsnet** [comment]
Unfortunately, the generation of context will not change until there are two releases of Go with type aliases. Thus, when Go1.10 is released, we'll make the change.
