### ISSUE TITLE
fatal error: runtime: bsdthread_register error

### ISSUE THREAD

**Issue by jmygit** [golang/protobuf#351]
Environment:
OS X El Capitan
CommandLineTools version 7
Go version 1.7
Protobuf c++ tar 2.4.1
go get -u -v github.com/golang/protobuf/proto
go get -u -v github.com/golang/protobuf/protoc-gen-go

Everything works fine in OS X Yosemite

protoc --go_out=. test.proto 
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x11ab0ca, 0x21)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0x7fff5fbffa80 sp=0x7fff5fbffa60
runtime.goenvs()
	/usr/local/go/src/runtime/os_darwin.go:108 +0xa0 fp=0x7fff5fbffab0 sp=0x7fff5fbffa80
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:486 +0xa1 fp=0x7fff5fbffaf0 sp=0x7fff5fbffab0
runtime.rt0_go(0x7fff5fbffb20, 0x1, 0x7fff5fbffb20, 0x0, 0x1, 0x7fff5fbffc58, 0x0, 0x7fff5fbffc66, 0x7fff5fbffc82, 0x7fff5fbffc92, ...)
	/usr/local/go/src/runtime/asm_amd64.s:158 +0x183 fp=0x7fff5fbffaf8 sp=0x7fff5fbffaf0
--go_out: protoc-gen-go: Plugin failed with status code 2.

**Comment by dsnet** [comment]
I don't have a Mac machine with that environment to repro this issue. Does this still occur when you use Go1.8.1?

`protoc-gen-go` doesn't use any unsafe, so I highly suspect that this is not an issue specific to protoc-gen-go, but possibly the Go runtime. I remember OSX having a history of introducing breaking changes that the Go toolchain is not happy with.

**Comment by dsnet** [comment]
Closing as stale. If this is still happening, feel free to re-file the issue or re-open. Thanks.
