### ISSUE TITLE
Protobuf reference page refers to non existant types. 

### ISSUE THREAD

**Issue by estsauver** [golang/protobuf#353]
For example, https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Enum

This doesn't seem to exist anywhere in the code base.

**Comment by estsauver** [comment]
Found that it was in the "type" file. Perhaps adding an annotation to the docs would be helpful?

**Comment by cybrcodr** [comment]
Are you referring to this repo's README.md page or the [Protobuf developers guide](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Enum)?

If former, I don't see any mention of it in README.md.  If latter, you can try to send request to protobuf@googlegroups.com.

**Comment by estsauver** [comment]
Sure, will send to group.
