### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by dsnet** [golang/protobuf#357]
We are gradually moving to have all Go protobuf work developed on github, but we need to have an integration bot setup (probably Travis CI). This CI should be testing on all versions of Go down to whatever version of Go that AppEngine is still running.

\cc @cybrcodr

**Comment by awalterschulze** [comment]
Its also good to test different protoc versions.

These might be useful
https://github.com/gogo/protobuf/blob/master/install-protobuf.sh
https://github.com/gogo/protobuf/blob/master/.travis.yml

**Comment by cybrcodr** [comment]
Added simple travis config for now #379 .  I've yet to enable travis run on this, still waiting for admin access.

Thanks for the pointer for using different protoc version.  We'll evaluate which versions to test against.

**Comment by tamird** [comment]
@cybrcodr you still need to enable travis-ci for this repository. See https://travis-ci.org/golang/protobuf

**Comment by cybrcodr** [comment]
I enabled it and have made another fix in #381 .   I've verified that it is working now.

@dsnet and I have decided to use only one version of protoc for now.  Do let us know if there is a good reason to have different ones.
