### ISSUE TITLE
Access a field option from the generated code

### ISSUE THREAD

**Issue by siadat** [golang/protobuf#358]
Given the following proto

```proto
syntax = "proto3";
package proto;
import "google/protobuf/descriptor.proto";

extend google.protobuf.FieldOptions {
    string xmlattr = 50001;
}

message person {
    string name = 1 [(xmlattr)="abcd"];
}
```

How can I access the `xmlattr` field option value from an instance of the generated code (e.g. the Person Go struct)?

I've been able to access some of the properties of the field with

```go
import pb "path/to/generated/proto"
import proto "github.com/gogo/protobuf/proto"
//...
proto.GetProperties(reflect.TypeOf(pb.Person{}))
```

I couldn't find any way to fetch the `xmlattr` extended field option.

**Comment by siadat** [comment]
Would it be a good idea to implement access to field option values as a feature?

**Comment by bcmills** [comment]
You can access it using the  [descriptor] (https://godoc.org/github.com/golang/protobuf/descriptor) package, but if you need to access it frequently you'll probably want to do some kind of caching.

**Comment by siadat** [comment]
@bcmills Thank you, this is what I was looking for.
