### ISSUE TITLE
proposal: proto: allow iterating over registered proto.Messages

### ISSUE THREAD

**Issue by siadat** [golang/protobuf#362]
I want to iterate through all the structs and perform some kind of caching on some of them (continuing #358).

While looking, I noticed that `proto.RegisterType` is called for all the generated types and I could access them with their name. The problem is that I don't know the names.

To clarify a bit more, I'm looking for something like the values stored in the underlying [protoTypes](https://github.com/golang/protobuf/blob/5bdfda0a01d81b6b1694960c0d8d84c49c10d0ab/proto/properties.go#L829) map, or the [topMsgs](https://github.com/golang/protobuf/blob/47eb67eaf5cab63c58956d4d4ce86b03ad5eaa03/protoc-gen-go/generator/generator.go#L1262) slice.

**Comment by dsnet** [comment]
This functionality will not be added to v1, but will be available in the v2 API via [`protoregistry.Files.RangeFiles`](https://github.com/golang/protobuf/blob/05828dba448b3ac7c48281a44a02e3269d5420be/reflect/protoregistry/registry.go#L217-L221) or [`protoregistry.Types.RangeMessages`](https://github.com/golang/protobuf/blob/05828dba448b3ac7c48281a44a02e3269d5420be/reflect/protoregistry/registry.go#L42).
