### ISSUE TITLE
Missing "null" field in JSON

### ISSUE THREAD

**Issue by vaporz** [golang/protobuf#367]
Hi,
I'm using "jsonpb.Marshaler.EmitDefaults=true" to output a JSON with zero values, which decide "Whether to render fields with zero values".
But for a Pointer field with zero value "nil", the key is missing from the output JSON.
According to The Go Programming Language Specification:

> Each element of such a variable or value is set to the zero value for its type: false for booleans, 0 for integers, 0.0 for floats, "" for strings, and nil for pointers, functions, interfaces, slices, channels, and maps.

So, "nil" is the zero value for pointers, am I correct?
Is it OK to output a JSON key with "null"? Or what's the main concern with it?
Thank you!

**Comment by dsnet** [comment]
\cc @cybrcodr

**Comment by cybrcodr** [comment]
This should have been fixed already in commit 7a211bcf3bce0e3f1d74f9894916e6f116ae83b4.  Please make sure you are using source after that commit.

The following testcase in current master shows that it should produce JSON null value...
https://github.com/golang/protobuf/blob/master/jsonpb/jsonpb_test.go#L375

If you are still encountering a bug, please share proto message definition and code.

Thanks.

**Comment by vaporz** [comment]
Great! Thanks a lot!
I'll test later.
