### ISSUE TITLE
assign a zero to a field which type int32, and the proto3 just filters this filed out,just like it is unset!

### ISSUE THREAD

**Issue by panjf2000** [golang/protobuf#368]
i got a proto3 struct and it has a field which is type int32,after i assign a zero(which is a real value i need) to this field,and it just filtered this field out like it is unset,this field just did't show up.
how can get this field when it is zero?

**Comment by cybrcodr** [comment]
Are you referring to JSON serialization of the proto message?  If so, the default for jsonpb.Marshaler's EmitDefaults field is false -- https://github.com/golang/protobuf/blob/master/jsonpb/jsonpb.go#L66.  Zero for int32 is the default value, and hence it will be omitted in the JSON output.  If you desire to have such default values be emitted, set EmitDefaults to true.  This will emit all fields with Go "zero" values.

**Comment by bradfitz** [comment]
It is a defining feature of proto3 that there's no difference between an implicit (unset) zero value and an explicit zero value. proto3 does not have per-field "field is set" bits like proto2.

See https://developers.google.com/protocol-buffers/docs/proto3#default

**Comment by panjf2000** [comment]
@cybrcodr @bradfitz thx man! i got it.
