### ISSUE TITLE
Support for output with unexported struct names

### ISSUE THREAD

**Issue by bruth** [golang/protobuf#38]
This is a request to support generating code that uses lowercase struct names so they are not exported in the package they target. The motivation is to reduce the API footprint exposed to end users. For example, in a project I am working on I define a set of methods that use the protobuf structs internally, but I don't want them to be exposed themselves: http://godoc.org/github.com/chop-dbhi/origins/dal

**Comment by dsymonds** [comment]
We won't support that use case. Generated protocol buffer code should be in its own package, not mixed with your own code.

**Comment by bruth** [comment]
Thank you for responding.
