### ISSUE TITLE
Deserializing oneof not working

### ISSUE THREAD

**Issue by jrozner** [golang/protobuf#380]
I'm building a game server in Go that communicates with some atmega microcontroller based devices. On he hardware side I'm using [nanopb](https://github.com/nanopb/nanopb) as the protobuf implementation and this on the server side. Using the following specification I'm not seeing the oneof data being deserialized on the Go side when sent from the microcontroller side. Testing it with just nanopb everything works fine. Am I doing something wrong or is there a bug/incompatibility here? The msgType field does however deserialize correctly.

```protobuf
syntax = "proto3";

message Heartbeat {
  uint32 identifier = 1;
}

message Message {
  uint32 msgType = 1;

  oneof payload {
    Heartbeat heartbeat = 2;
  }
}
```

```go
	buf := make([]byte, length, length)
	read, err := conn.Read(buf)
	if err != nil {
		log.Printf("error reading message: %s\n", err)
		return
	}

	if read != int(length) {
		log.Printf("unexpected message length; expecting %d and received %d\n", length, read)
		return
	}

	fmt.Printf("%#v\n", buf)
	var message Message
	err = proto.Unmarshal(buf, &message)
	if err != nil {
		log.Println(err)
		return
	}

	fmt.Printf("%d\n", message.MsgType)

	switch x := message.Payload.(type) {
	case *Message_Heartbeat:
		fmt.Printf("%#v\n", x.Heartbeat)
	case nil:
		log.Println("type isn't set")
	default:
		log.Println("nope, shit isn't working")
	}
```

When sending the following data this is the output from the Go side. Not the 0x0a in there is the length of the message that is being read to determine the length of the messages by the server and client. It's read off the wire and not placed into the buffer the protobuf deserializes from
```
00000000: 0a08 0212 0608 effd b6f5 0d              ...........
```

```
[]byte{0x8, 0x2, 0x12, 0x6, 0x8, 0xef, 0xfd, 0xb6, 0xf5, 0xd}
2
2017/06/21 09:50:52 type isn't set
```

**Comment by jrozner** [comment]
For what it's worth I've also verified the message data using the Rust protobuf crate and it deserializes correctly with that. I'm assuming this is an issue in the Go implementation around handling oneofs.

**Comment by cybrcodr** [comment]
Sorry, I've not looked into this much, but I wonder if it's a compatibility issue.  With just using this implementation for marshaling and unmarshalling

```
	m := &pb.Message{
		MsgType: 2,
		Payload: &pb.Message_Heartbeat{
			Heartbeat: &pb.Heartbeat{
				Identifier: 10,
			},
		},
	}

	fmt.Printf("message %+v\n", m)
	data, err := proto.Marshal(m)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Printf("marshaled message %#v\n", data)

	m2 := &pb.Message{}
	err = proto.Unmarshal(data, m2)
	fmt.Printf("unmarhaled message %#v\n", m2)
	fmt.Printf("%#v\n", m2.GetHeartbeat())
```

I get the following output ...

```
message msgType:2 heartbeat:<identifier:10 >
marshaled message []byte{0x8, 0x2, 0x12, 0x2, 0x8, 0xa}
unmarhaled message &foo.Message{MsgType:0x2, Payload:(*foo.Message_Heartbeat)(0xc42000c040)}
&foo.Heartbeat{Identifier:0xa}
```

I could be wrong on this, but based on the following spec ...
https://developers.google.com/protocol-buffers/docs/encoding

The first 2 bytes 0x8 0x2 is for the message Message.msgType tag 1 and value 2.
The bytes 0x12 0x2 is for following embedded message (which is type 2) and uses tag 2.
The last 2 bytes 0x8 0xa is for the (embedded) message Heartbeat.identifier tag 1 and value 10.

Perhaps try out nanopb again with above code and see what you get.
