### ISSUE TITLE
process: start publishing binary releases

### ISSUE THREAD

**Issue by zombiezen** [golang/protobuf#384]
(Opening this up as a backlog item, not saying we're going to get to this right now.)

This would improve the experience of first-time setup of protoc, since we can say just to download a few binaries.  Not sure at what frequency these should be generated (maybe even every commit?).

**Comment by twoism** [comment]
Just tagging releases with the source code at the very least would be really helpful. gRPC does this [https://github.com/grpc/grpc-go/releases](https://github.com/grpc/grpc-go/releases) and it makes dependency management much more reasonable. Especially when you have 10s of projects all with a random git SHA in their `glide.yaml`.

**Comment by dsnet** [comment]
We have begun tagging releases. I don't think it's necessary to keep an issue open regarding this.
