### ISSUE TITLE
no way to access data for unrecognized extensions

### ISSUE THREAD

**Issue by jhump** [golang/protobuf#385]
Access to extensions is provided by top-level functions in the `proto` package (in `extensions.go`). But they omit any way to query for the values of unrecognized extensions (as raw unparsed bytes).

My immediate use case is to be able to re-parse custom method options on a descriptor proto using a dynamic extension registry (not limited to just linked-in extensions). This allows a "server browser" tool to show more useful information about a server's exposed services instead of just "unknown fields/extensions". Using the [server reflection API](https://godoc.org/google.golang.org/grpc/reflection), the client can easily ask the server for all known extensions and then re-parse the descriptors (for example, using a [dynamic message](https://godoc.org/github.com/jhump/protoreflect/dynamic)).

For symmetry with how C++ and Java libraries support extension and unknown fields, it would be preferred for unrecognized extensions to end up in `XXX_unrecognized` instead of hidden inside of a map of unparsed extension values that is inaccessible. (It used to be accessible via the `ExtensionMap()` method, but that is no longer generated by protoc-gen-go.)

I also brought this up on the protobuf mailing list, where I think @xfxyjwf expressed a similar sentiment:
https://groups.google.com/d/topic/protobuf/HTNFwKLxtRg/discussion

I believe this could be addressed by merely changing the unmarshalling code to append the data to `XXX_unrecognized` instead of storing in the map when the looked up `*ExtensionDesc` is nil.

**Comment by jhump** [comment]
@dsnet any updates on how/when this issue might be resolved?

**Comment by jhump** [comment]
@dsnet, what do you think about #420 as a solution for this? Unlike #386, it has no compatibility issues. Instead, it increases API surface area by one method.

**Comment by dsnet** [comment]
I'll take a look. With Go1.9 out the door, I'm swinging my attention back over to protos.

**Comment by dsnet** [comment]
Closing as fixed with #583. Track #479 for the merging of `dev` into `master`.
