### ISSUE TITLE
grpc: return responses in addition to errors

### ISSUE THREAD

**Issue by mcos** [golang/protobuf#390]
When returning an error response from client-side calls, the response output is returned as `nil` (https://github.com/golang/protobuf/blob/6a1fa9404c0aebf36c879bc50152edcc953910d2/protoc-gen-go/grpc/grpc.go#L291). It would be beneficial to have the response (`out`, in the linked snippet) in addition to the error, since partial responses can be returned from the server-side call.

**Comment by dsnet** [comment]
\cc @dfawley, @paranoiacblack

**Comment by dfawley** [comment]
FYI, this is discussed in https://github.com/grpc/grpc/issues/12824 and https://github.com/golang/protobuf/pull/435.
