### ISSUE TITLE
Missing support for the deprecated option

### ISSUE THREAD

**Issue by tsl0922** [golang/protobuf#396]
**Syntax:**

```protobuf
int32 old_field = 6 [deprecated=true];
```

https://blog.golang.org/godoc-documenting-go-code

> Sometimes a struct field, function, type, or even a whole package becomes redundant or unnecessary, but must be kept for compatibility with existing programs. To signal that an identifier should not be used, add a paragraph to its doc comment that begins with "Deprecated:" followed by some information about the deprecation.

**Comment by paranoiacblack** [comment]
@tsl0922 Is this only a documentation enhancement? As in, whereever there is a deprecated proto field, guarantee that the generated pb.go file explicitly documents fields as "Deprecated:" like mentioned in that article. Is there something else to it?

**Comment by dsnet** [comment]
That should be it. golang/go#10909 documents "Deprecated:" as special. Tools like `golint` and `godoc` will treat deprecated specially by either warning on their usage or hiding them from documentation (golang/go#17056).
