### ISSUE TITLE
Questions on how to use ptypes properly

### ISSUE THREAD

**Issue by guodongx** [golang/protobuf#399]
Hi,

I am trying to use any/timestamp in the ptype.
So in my .proto file, I have 
import "google/protobuf/any.proto";

But when it generates the .pb.go file, it genertes 'import google_protobuf "google/protobuf"'
I am expecting it to actually generate 'import google_protobuf "github.com/golang/protobuf/ptypes/any"'
Wondering which part I could possibly configure incorrectly.

**Comment by guodongx** [comment]
actually looks like I just need to vendor ptypes pkg and then do go install on it.

**Comment by cybrcodr** [comment]
Proto packages "google/protobuf/..." for well known types (WKTs) are translated to different language specific paths/packages.

If you look at the proto source file, there's "option go_package" which specifies the Go package for types defined in that file, and they are all under github.com/golang/protobuf/ptypes/...  Just for comparison, Java ones are generated with com.google.protobuf package instead.

We do host the generated WKTs in this repo as you've noticed and hence you can reference them directly if you have this repo in your GOPATH.

Hope this answers your questions.
