### ISSUE TITLE
process: missing CONTRIBUTING.md

### ISSUE THREAD

**Issue by binarycrusader** [golang/protobuf#401]
No CONTRIBUTING.md file is present in the protobuf repo, so it's unclear whether a CLA is required for contributions.  Based on pull requests, it looks like one is.  Please consider adding a CONTRIBUTING.md file to your repository.

**Comment by dsnet** [comment]
https://github.com/golang/protobuf/blob/v1.4.0-rc.3/CONTRIBUTING.md
