### ISSUE TITLE
proto: Unmarshal should silently skip unknown map fields

### ISSUE THREAD

**Issue by awalterschulze** [golang/protobuf#403]
https://github.com/golang/protobuf/blob/master/proto/decode.go#L868

I think we should, since maps should be interchangeable with repeated messages containing a key and value field.  The messages with extra fields should also be compatible with maps, since they are compatible with messages with only a key and a value.

**Comment by dsnet** [comment]
I checked what the C++ implementation does:
* It ignores any tags other than 1 or 2.
* If tags 1 or 2 are missing, then it assumes the zero value.
* If a tag is repeated, the later takes precedence.
* It ignores tags with the wrong wire type (e.g., tag 1 with a wire type of Fixed32, when it expects Bytes).
