### ISSUE TITLE
jsonpb: fix unmarshal tests to not compare using strings from proto.MarshalTextString

### ISSUE THREAD

**Issue by cybrcodr** [golang/protobuf#405]
Current unmarshaling tests calls proto.MarshalTextString and compares the resulting string.  This is not a good comparison since MarshalTextString may not reflect the actual underlying data, e.g. nil vs empty slice.  It's better to just use proto.Equal.

**Comment by cybrcodr** [comment]
Fyi.  I just realized that proto.Equal may not be the correct solution.  In the case of nil vs empty slice, proto.Equal will not detect the difference.  Anyways, we should still update the tests accordingly and not use MarshalTextString.

**Comment by dsnet** [comment]
Closing this since jsonpb will be completely rewritten with its own set of tests.
