### ISSUE TITLE
jsonpb: No way to disable HTML escaping

### ISSUE THREAD

**Issue by pauln** [golang/protobuf#407]
While working on shifting [Truss](https://github.com/TuneLab/truss/) to use `jsonpb` in order to [improve its JSON support](https://github.com/TuneLab/truss/pull/227), it's come to light that there's no way to disable HTML escaping for strings.  Perhaps a new option could be added to `jsonpb.Marshaler` which sets / is passed through to [`Encoder.SetEscapeHTML`](https://godoc.org/encoding/json#Encoder.SetEscapeHTML) to make this configurable?

As a brief spot of context, Truss currently uses `Encoder.SetEscapeHTML` to disable HTML escaping as the encoded JSON is sent directly as an HTTP response (with appropriate content-type).

**Comment by dsnet** [comment]
Closing this as the associated PR is also closed.

We've decided the policy for new `jsonpb` options is that it must be providing some functionality that is fundamentally impossible to do as a post-processing step. Altering the string-encoding is something that can be done a JSON->JSON transformation.
