### ISSUE TITLE
protoc-gen-go: improve package doc

### ISSUE THREAD

**Issue by jhump** [golang/protobuf#413]
The files generated by protoc-gen-go include a package doc comment that is usually inappropriate. 

```go
/*
Package <pkg> is a generated protocol buffer package.

It is generated from these files:
	<some-file>.proto
	<some-other-file>.proto

It has these top-level messages:
	<SomeMessage>
	<SomeOtherMessage>
*/
```

While this information makes for a useful comment, it not very good godoc. It can't, for example, explain the purpose of the package nor can it provide an overview for any non-generated code in the package. It also makes no reference to GRPC services, which for some packages will actually be the purpose of the package.

Ideally, the tool would not output any package doc comments at all, and just allow developer to provide their own package doc in a separate file.

Also, because the tool emits the above comment as package doc, it only generates a single such comment and puts it (arbitrarily) in the first generated file. It would be actually be more useful if this were just a file comment that appeared in *every* file (not package doc) and showed the name of the one source file and top-level messages for that single file.

**Comment by neild** [comment]
Package docs are no more.
