### ISSUE TITLE
macos protoc can't produce code for service

### ISSUE THREAD

**Issue by Kilmar** [golang/protobuf#419]
OS: macOs Sierra 10.12.5
Proto: libprotoc 3.4.0

Command protoc --go_out=plugins=grpc:. *.proto never produce output for service. Running exactly same command on any debian od fedora distribution will produce correct output for service but never in macOs. Even examples in https://github.com/grpc/grpc-go/tree/master/examples are not working.

**Comment by cybrcodr** [comment]
Works for me ...
```
$GOPATH/src/google.golang.org/grpc/examples/helloworld/helloworld$ protoc --version
libprotoc 3.4.0

$GOPATH/src/google.golang.org/grpc/examples/helloworld/helloworld$ protoc --go_out=plugins=grpc:. helloworld.proto

$GOPATH/src/google.golang.org/grpc/examples/helloworld/helloworld$ git st
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean
```

Resulting helloworld.pb.go produced the same copy.  If  I removed plugins=grpc option, it would then not produce the services code.

Do make sure you have the latest protoc-gen-go.

**Comment by dsnet** [comment]
Closing due to lack of traffic. Please file a new issue if this continues to be an issue. Thanks.
