### ISSUE TITLE
Move to json-iterator

### ISSUE THREAD

**Issue by jzelinskie** [golang/protobuf#422]
Kubernetes just replaced its JSON usage with [json-iterator](https://github.com/json-iterator/go).
Since it's 100% API compatible with `encoding/json`, I think it's possible to replace usage of `encoding/json` in the jsonpb package with this library to get some performance gains.

This definitely would optimize the tight loop of projects like [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway/).

I'm making this issue, since I know that some projects might be averse to including new dependencies. So please give me your thoughts and if it sounds reasonable, I'll open a PR.

**Comment by thockin** [comment]
Json-iterator passes a lot of tests, but it could always use more eyes on it for compat and sanity.

**Comment by dsnet** [comment]
Currently the protobuf repo only really has dependencies on the standard library and that's goal we would like to maintain.

That being said, if `json-iterator` is API compatible with `encoding/json`, can't users that really care about performance vendor `json-iterator` into `vendor/encoding/json`?

**Comment by dsnet** [comment]
The `jsonpb` is fairly non-performant. In some cases it even does a unmarshal->marshal->unmarshal loop through the standard library to do its work. Switching to json-iterator is just a stop gap to improve performance. Really, the entire `jsonpb` library needs to be refactored. It may be worth just writing the parsing and formatting logic ourselves. Most of the complexity of the `encoding/json` package comes from the fact that it is so reflection heavy, which we can actually mostly avoid in `jsonpb` once we have a legit protobuf reflection API.
