### ISSUE TITLE
Importing definitions fails because of incorrect package path

### ISSUE THREAD

**Issue by jpoz** [golang/protobuf#43]
When I import some of google's proto definitions the generated code imports a package that does not exist.

Example: 

```proto
syntax = "proto3";

import "google/protobuf/timestamp.proto";

package bar;

message Foo {
  google.protobuf.Timestamp start = 1;
  google.protobuf.Timestamp finish = 2;
}
```

Generated code:

```go
package bar

import proto "github.com/golang/protobuf/proto"
import google_protobuf "google/protobuf"

...
```

The import of `google_protobuf` fails.

* Should I be building the `google_protobuf` package and adding it manually to my `GOPATH`?
* Is there a directive I'm missing to tell the protoc generator to build dependencies?
* Bug in golang/protobuf? Where would i start looking to add a fix?

**Comment by dsymonds** [comment]
protoc-gen-go needs to be told what import path to generate for packages that it can't guess.

The simplest option is to run protoc from a directory where the subdir holding the .proto file will be the import path (e.g. in `$GOPATH/src`).

The next best option is to pass one or more `M` parameters to specify the mapping of .proto file to import path. See `protoc-gen-go/plugin/Makefile` in this repo for an example of that.
