### ISSUE TITLE
protobuf golang initialize optional issue

### ISSUE THREAD

**Issue by vegeta34** [golang/protobuf#431]
I have a proto struct:
message MsgHead{
	required MesType msgtype = 1;
	optional uint32 result = 2;
	optional string errmsg = 3;
}
when I use golang to init this struct, and did not init result and errmsg(they are optional), when compile it reports this: too few values in struct initializer
I thought optional is no need to initialize, is that right? Any one know what's the problem?

**Comment by cybrcodr** [comment]
Proto fields translate to Go struct fields.  Proto optional translates to Go pointers allowing for the nil value to represent corresponding field as not set.  The Go struct for MsgHead will contain at least 3 exported fields.  Struct literals have rules specified in https://golang.org/ref/spec#Composite_literals.

> An element list that does not contain any keys must list an element for each struct field in the order in which the fields are declared.

Or as long as you specify the key for the field(s) you're setting, then you can omit the other fields, e.g.

`m := &MsgHead{Msgtype: &MesType{}}`
