### ISSUE TITLE
make test of protocol-gen-go/testdata fails

### ISSUE THREAD

**Issue by thaolinhvu** [golang/protobuf#432]
Hello, 
When I try running make test , it fails.
This is the error message -

make -B my_test/test.pb.go
make[1]: Entering directory '/home/debianpi/network-server/src/github.com/golang/protobuf/protoc-gen-go/testdata'
protoc --go_out=Mmulti/multi1.proto=github.com/golang/protobuf/protoc-gen-go/testdata/multi:. my_test/test.proto
my_test/test.proto: warning: Import multi/multi1.proto but not used.
make[1]: Leaving directory '/home/debianpi/network-server/src/github.com/golang/protobuf/protoc-gen-go/testdata'
sed -i -e '/return.*fileDescriptor/d' my_test/test.pb.go
sed -i -e '/^var fileDescriptor/,/^}/d' my_test/test.pb.go
sed -i -e '/proto.RegisterFile.*fileDescriptor/d' my_test/test.pb.go
gofmt -w my_test/test.pb.go
diff -w my_test/test.pb.go my_test/test.pb.go.golden
1c1
< // Code generated by protoc-gen-go.
---
> // Code generated by protoc-gen-go. DO NOT EDIT.
3d2
< // DO NOT EDIT!
322c321
< 	XMyFieldName_2                *int64 `protobuf:"varint,3,opt,name=_my_field_name_2,json=myFieldName2" json:"_my_field_name_2,omitempty"`
---
> 	XMyFieldName_2                *int64 `protobuf:"varint,3,opt,name=_my_field_name_2,json=MyFieldName2" json:"_my_field_name_2,omitempty"`
Makefile:47: recipe for target 'golden' failed
make: *** [golden] Error 1

So actually the files my_test/test.pb.go  and my_test/test.pb.go.golden have different json Names.
They differentiate in the first letter. But it said that we mustn't edit the files.
I tried changing it but the test still fails.
What should I do? 
Thank you

**Comment by cybrcodr** [comment]
Make sure you have GOPATH env set properly.  Based on the error message, I'm guessing you are running 'make test' under protobuf/protoc-gen-go directory.

**Comment by paranoiacblack** [comment]
I tried to reproduce this but I couldn't figure it out. Is this an older version of protoc than the required minimum? Please reopen if this continues to occur.
