### ISSUE TITLE
github.com/golang/protobuf/protoc-gen-go can not be found

### ISSUE THREAD

**Issue by zamberform** [golang/protobuf#439]

**Comment by xzenon** [comment]
Have same problem.

**Comment by cybrcodr** [comment]
Can you provide more details on what you are trying to do and what fails?

To use protoc-gen-go, you'll need to grab the code from this repo and install, see https://github.com/golang/protobuf#installation.

**Comment by xzenon** [comment]
I have installed Go compiler and tools.
Then when I do `go get -u github.com/golang/protobuf/protoc-gen-go` nothing happens, nothing installed.
I've followed the solution from [here](https://github.com/golang/protobuf/issues/365#issuecomment-305240878) and successfully installed manually.

**Comment by cybrcodr** [comment]
Running `go get -u github.com/golang/protobuf/protoc-gen-go` should download the repo into $GOPATH/src/github.com/golang/protobuf and built protoc-gen-go in $GOPATH/bin.  If you didn't explicitly set $GOPATH, the default (on Unix systems) is $HOME/go.

Anyways, good to know that you're able to install the compiler now.  Closing out this issue.

**Comment by arulsenthil** [comment]
@cybrcodr  It downloads the repo but doesn't build
I have configured GOPATH in windows env variables. I have installed other packages like mux and all installed well in GOPATH. However when I tried to install protoc-gen with this command
go get -u github.com/golang/protobuf/protoc-gen-go
it has installed the repo in GOPATH\src  but not the executable in bin. I manually built it like this
go to dir  GOPATH\src\github.com\golang\protobuf and execute this command:
go install github.com/golang/protobuf/protoc-gen-go

referred by the [link](https://github.com/golang/protobuf/issues/365#issuecomment-305240878) given by @xzenon

**Comment by cybrcodr** [comment]
The instructions at https://github.com/golang/protobuf#installation uses `go get -d -u` which does not install.  It does provide a more recommended approach of checking out a particular tag first and then run `go install` on it.

Hmm ... I couldn't easily verify it on Windows, but I find it strange that a `go get -u` (without -d) will not install.

Anyways, the instructions on the doc is better as it pins protoc-gen-go to a particular tag.
