### ISSUE TITLE
protobuf3 default JSON encoding

### ISSUE THREAD

**Issue by philips** [golang/protobuf#44]
In the proto3 there are encodings for different types, in particular the Timestamp type. Where is that code implemented? I am having a hard time figuring it out.  https://developers.google.com/protocol-buffers/docs/proto3#json

cc @sym3tri

**Comment by dsymonds** [comment]
The newly added jsonpb package (see 67cbcad) is the official vehicle for JSON support. There's not yet any support for Timestamp and friends yet.

**Comment by philips** [comment]
Thank you for the update!

**Comment by dsymonds** [comment]
553c764 adds `jsonpb` support for Duration and Timestamp according to the spec. Other types will follow.

**Comment by dsymonds** [comment]
c6184d3 adds `jsonpb` support for the types in `wrappers.proto`.

**Comment by dsymonds** [comment]
552c7b9 adds `jsonpb` support for Struct and NullValue.

I think that's all we have covered right now.
