### ISSUE TITLE
Creating a custom type for Mongo's ID's

### ISSUE THREAD

**Issue by EwanValentine** [golang/protobuf#442]
Apologies, I raised a similar ticket a while back but I just thought I'd raise a more specific question than my previous closed ticket. https://github.com/golang/protobuf/issues/393

For some context, when you generate protobuf code, say... 

```
message Hello {
  string id = 1;
}
```

You would get

```go
type Hello struct {
  Id string
}
```

Which means I have to do a bunch of conversion in order to use these structs as Mongodb models. As Mongodb's mgo driver requires a `bson.ObjectId` custom type for the ID field. Also the ID field is all uppercase as per Golang's own linting/style guide. Whereas protobuf generates them as `Id`. 

So given that, is there a way I can create a custom type which would generate mgo compatible ID fields? Such as... 

```
message Hello {
  BsonID id = 1;
}
```
generates...

```go
type Hello struct {
    ID bson.ObjectId
}
```
I just wondered how to go about creating a custom type for this use-case?

I noticed someone had a PR of a similar nature a while back which wasn't approved/merged: https://github.com/golang/protobuf/pull/320 

Thanks in advance!

**Comment by pbdeuchler** [comment]
We use `bytes` in our proto definitions and it works very well

**Comment by EwanValentine** [comment]
@pbdeuchler Do you need to manually convert between the two at runtime still?

**Comment by EwanValentine** [comment]
Oh yeah it is just bytes under the hood! https://godoc.org/github.com/pkg/bson#ObjectId

**Comment by dsnet** [comment]
Closing this in favor of #52.

**Comment by bazaglia** [comment]
@EwanValentine @pbdeuchler have you tried the official mongodb go driver? I couldn't get it working: `could not greet: rpc error: code = Unknown desc = cannot decode objectID into a *[]byte
exit status 1`

**Comment by amsokol** [comment]
Hi, look at this one:
https://github.com/amsokol/mongo-go-driver-protobuf
It supports ObjectId also.

**Comment by mihai1voicescu** [comment]
ObjectId can be replaced with a simple string in proto now

**Comment by mihai1voicescu** [comment]
Unfortunately I put that project on hold before I could finish but this is what I used:
```
message Person {
    string  id = 1 [(tagger.tags) = "bson:\"_id,omitempty\""];
```
Which generates:
```
type Person struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id,omitempty"`
```

As far as I remember (so I might be wrong) you are then free to insert the structs in Mongo and it will generate an ID if the `struct.id == ""` which you can get with:
```
query, err := itemCol.InsertOne(ctx, &req.Item)
...
oid, ok := query.InsertedID.(primitive.ObjectID)
	if !ok {
		panic("Unable to convert")
	}

	res := mn.CreateResponse{Id: oid.Hex()}
```
Note that I had one more problem with the ID, but I can't remember what it was or if I solved it.

Hope it helps! If not maybe you can post the exact exception/st/problem.

Please note that I am not an expert in go so the above code might not be production ready.

**Comment by pravchuk** [comment]
Has this been solved or not yet?
