### ISSUE TITLE
proto3: int64 missing json "string" tag

### ISSUE THREAD

**Issue by pullstringjeremy** [golang/protobuf#443]
Running into an issue interoperating between json and protobuf when working across languages when using the int64 type.  As per [proto3 spec](https://developers.google.com/protocol-buffers/docs/proto3#json), the expected json representation for an int64 is a string.  Accordingly, when serializing to json from other languages (e.g. python's [MessageToJson](https://github.com/google/protobuf/blob/master/python/google/protobuf/json_format.py)) int64 data is serialized to a string.

However, when attempting to call [`json.Unmarshal()`](https://golang.org/pkg/encoding/json/#Unmarshal), I'm seeing the following error:

`json: cannot unmarshal string into Go struct field Test.data of type int64`

In investigating further, this looks to be because the generated go code looks like this

```go
type Test struct {
	Data int64 `protobuf:"varint,1,opt,name=data" json:"data,omitempty"`
}
```

which is notably missing the ",string" tag (e.g. see [here](https://stackoverflow.com/a/21152548/4582273))

Can the `",string"` json tag be added so this interoperates correctly, or at least can there be an option to generate it with this tag added?, e.g.

```go
Data int64 `protobuf:"varint,1,opt,name=data" json:"data,string,omitempty"`
```
-----------
For reference, here is the example proto I am using:

```protobuf
syntax = "proto3";

package mytest;

message Test {
    int64 data = 1;
}
```

**Comment by cybrcodr** [comment]
Use the [jsonpb](github.com/golang/protobuf/jsonpb) package for marshaling and unmarshaling between protobufs and JSON.

**Comment by dsnet** [comment]
Adding the json tags was a mistake because it gives the mistaken notion that the standard library `json` package and `jsonpb` are compatible. Currently, it is not possible to implement the JSON<->PB spec with `json` tags alone. I would like to see the `json` tags removed in the future.
