### ISSUE TITLE
MTIME bytes are set in the gzipped FileDescriptor in some Go builds

### ISSUE THREAD

**Issue by lleveque** [golang/protobuf#448]
While setting up a CI script that checks our compiled model (in Go), I stumbled upon a difference in generated files between the CI build and my local build.

The (only) difference lies in the gzipped FileDescriptor at the end of file.pb.go.
Local machine :
```go
var fileDescriptor0 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, [...]
}
```
CI server :
```go
var fileDescriptor0 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, [...]
}
```
The bytes with offset 4-7 in a gzip file [correspond to the MTIME timestamp](http://www.gzip.org/zlib/rfc-gzip.html), which is "the most recent modification time of the original file being compressed".

On my local machine, MTIME seems to be set to 0, which is default when last modification time is unavailable (which I believe to be correct because we are gzipping "on the fly" in [protoc-gen-go](https://github.com/golang/protobuf/blob/master/protoc-gen-go/generator/generator.go#L2671)).
Also, changing the last modification time on my file doesn't have any effect on the four MTIME bytes : they are always set to 0x00, 0x00, 0x00, 0x00.

On my CI server, I'm not sure what those decode to, but definitely not zero (my guess is 2288912640 which is not really a valid timestamp). Again, changing the last modification time on the proto file doesn't have any effect on the four MTIME bytes : they *always* read 0x00, 0x09, 0x6e, 0x88.

On both machines :
- protoc version is 3.4.0
- protoc-gen-go is at HEAD
- input file content is the same
- inflating both those gzipped FileDescriptors with compress/gzip produces the exact same output (i.e. the MTIME bytes don't have any impact on the protobuf model, fortunately)
- the timezones are different on the two machines (2 hours apart), but I don't think it has any impact.

Does anyone know what's happening ?

___

**Comment by lleveque** [comment]
Ok, well... I now know what was happening : Go version was 1.7 on CI server and 1.9 on my machine.

For those interested, here is the bugfix introduced in 1.8 in compress/gzip : https://github.com/golang/go/commit/b4e714e59efd21f9140a3e8e2b0182c74bfde437

**Comment by dsnet** [comment]
As a more general note, any changes to the `flate` algorithm is going to cause the generated output file to differ. Thus, it's very important that the same Go version be used to ensure consistent build outputs.
