### ISSUE TITLE
Why i can not upgrade to version 3? Help me ~~ 

### ISSUE THREAD

**Issue by jiangdl** [golang/protobuf#449]
`protoc --version`
`libprotoc 3.4.0`
and has been running:
`go get -u github.com/golang/protobuf/protoc-gen-go`
it means protoc version is 3.4.0 and protoc-gen-go is latest version
and also had already added 
`syntax = "proto3";`
at a.proto file head
when i run 
`protoc --go_out=. a.proto`
the Code generated by protoc-gen-go also contains 
`
// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
`
and
`
var fileDescriptor0 = []byte{
	// 120 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x33, 0xd4, 0x4f,
	0xcd, 0x2b, 0xc9, 0x2c, 0xa9, 0xd4, 0x4f, 0x4a, 0xcc, 0xc9, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x2c, 0x33, 0xd4, 0x83, 0x88, 0x2a, 0x45, 0x71, 0xb1, 0x38, 0x25, 0xe6, 0xe4, 0x08,
	0xc9, 0x72, 0x71, 0x15, 0xe4, 0x17, 0x67, 0x96, 0x64, 0xe6, 0xe7, 0xc5, 0x57, 0x48, 0x30, 0x2a,
	0x30, 0x6a, 0x30, 0x05, 0x71, 0xc2, 0x44, 0x22, 0x50, 0xa4, 0x2b, 0x25, 0x98, 0x50, 0xa5, 0x23,
	0x85, 0x44, 0xb8, 0x58, 0x13, 0xf3, 0xd2, 0x73, 0x52, 0x25, 0x98, 0xc1, 0x32, 0x10, 0x8e, 0x13,
	0xcf, 0x2a, 0x26, 0x84, 0x4d, 0x49, 0x6c, 0x60, 0xbb, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x01, 0x63, 0xdb, 0x39, 0x93, 0x00, 0x00, 0x00,
}
`

**Comment by ivucica** [comment]
You have not stated exactly which problem you have.

**Comment by jiangdl** [comment]
Why in the generated file "proto package needs to be updated"?
I has already upgraded to the protoc3

**Comment by cybrcodr** [comment]
Are you asking why the generated code has the following line even if you have `syntax = "proto3";` in your proto?

const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

That line has nothing to do with proto syntax version.  It is the proto package version used by the generated code instead.  Simply put, the protoc-gen-go binary that you use to generate the .pb.go files should be from the same version as the proto package library.

**Comment by jiangdl** [comment]
How can we make them consistent?
 I have run this cmd：
`go get -u github.com/golang/protobuf/protoc-gen-go`
this means that it has been updated to the latest version of protoc-gen-go

**Comment by cybrcodr** [comment]
That is correct.  Are you experiencing any compilation errors?

There is nothing wrong with the generated comments.  It's just a hint in case you see a compilation error for that line to let you know that you may have a mismatch.  If there are no compilation errors for the generated code then you should be fine.

**Comment by jiangdl** [comment]
no error
but .pb.go include fileDescriptor0 that is the product of proto2?

**Comment by cybrcodr** [comment]
Just to be clear.  The generated code will have the following lines ...

```
// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package
```

And also ...
```
var fileDescriptor0 = []byte{
...
```

The comment about "proto package needs to be updated" pertains to the const _ declaration.  If that's not what you're seeing, can you post your proto definition?

Sorry if I misunderstood your original question.

**Comment by jiangdl** [comment]
of course, I have two .proto files: 
ball.proto
`syntax = "proto3";
package v1.entity;

option csharp_namespace = "v1.entity";

message Ball {
    float position_x = 1;
    float position_y = 2;
    float angle = 3;
}`
other is entity.proto:
`syntax = "proto3";
package v1.entity;

import "v1/entity/ball.proto";

option csharp_namespace = "v1.entity";

message Entity {
    repeated Ball balls = 1;
}`

**Comment by cybrcodr** [comment]
I generated the pb.go files and I don't see anything unusual.  The generated code has the following ...
```
// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package
```

and towards the end, each file has the fileDescriptor variable.  The comment above is meant for the const _ definition to make sure that the file is using the Go proto package version 2, that is not the same as proto syntax version.  It is not describing the fileDescriptor variable either.

**Comment by jiangdl** [comment]
ok，thanks very much

**Comment by meysam81** [comment]
I got some issue toward this, and commenting a closed issue won't kill anybody so here's the deal. I am running ```dep``` package inside a Dockerfile, so I got the following errors and can't continue. Also can't figure what's wrong either.
```
github.com/golang/dep/internal/importers/vndr                                                                                                                                                                                         [70/1604]
github.com/golang/dep/internal/importers                                                                                                                                                                                                       
github.com/golang/dep/cmd/dep                                                                                                                                                                                                                  
Removing intermediate container 3efa7432f884                                                                                                                                                                                                   
 ---> c215b26e7e46                                                                                                                                                                                                                             
Step 5/12 : RUN dep init && dep ensure                                                                                                                                                                                                         
 ---> Running in 6430d76a5194                                                                                                                                                                                                                  
Importing configuration from govendor. These are only initial constraints, and are further refined during the solve process.                                                                                                                   
Importing configuration from govendor. These are only initial constraints, and are further refined during the solve process.                                                                                                                   
  Locking in master (e2103e2) for transitive dep github.com/sean-/seed                                                                                                                                                                         
  Locking in v0.1.0 (37e2e1f) for transitive dep github.com/go-log/log                                                                                                                                                                         
  Locking in v1.0.0 (b2f7b8e) for transitive dep github.com/micro/h2c                                                                                                                                                                          
  Locking in  (d5fe4b5) for transitive dep github.com/hashicorp/go-cleanhttp                                                                                                                                                                   
  Using ^1.2.0 as constraint for direct dep github.com/golang/protobuf                                                                                                                                                                         
  Locking in v1.2.0 (aa810b6) for direct dep github.com/golang/protobuf            
  Locking in v0.1.0 (ce8abaa) for transitive dep github.com/hashicorp/memberlist
  Locking in  (5a380f2) for transitive dep github.com/mitchellh/mapstructure
  Locking in master (f0300d1) for transitive dep github.com/armon/go-metrics
  Locking in master (a581a57) for transitive dep github.com/micro/go-rcache
  Locking in v1.1.0 (9b3b1e0) for transitive dep github.com/google/uuid
  Locking in v1.0.0 (27df809) for transitive dep github.com/hashicorp/go-immutable-radix
  Locking in v0.5.0 (20f1fb7) for transitive dep github.com/hashicorp/golang-lru
  Locking in master (cbfa944) for transitive dep github.com/micro/go-log
  Locking in master (fa3f638) for transitive dep github.com/hashicorp/go-msgpack
  Locking in v0.3.0 (f21a4df) for transitive dep golang.org/x/text
  Locking in v1.4.0 (0bddfa2) for transitive dep github.com/hashicorp/consul
  Locking in master (6bb64b3) for transitive dep github.com/hashicorp/go-rootcerts
  Locking in v1.0.0 (886a7fb) for transitive dep github.com/hashicorp/go-multierror
  Locking in v1.0.0 (8a6fb52) for transitive dep github.com/hashicorp/errwrap
  Locking in master (2d4f591) for transitive dep github.com/micro/util
  Locking in  (19bbd39) for transitive dep github.com/hashicorp/serf
  Using master as constraint for direct dep golang.org/x/net
  Locking in master (927f977) for direct dep golang.org/x/net
  Locking in master (e92cdb5) for transitive dep github.com/hashicorp/go-sockaddr
  Locking in master (ff983b9) for transitive dep golang.org/x/crypto
  Using ^0.17.0 as constraint for direct dep github.com/micro/go-micro
  Locking in v0.17.0 (461df8d) for direct dep github.com/micro/go-micro
  Locking in master (9c3770d) for transitive dep github.com/micro/mdns
  Locking in v1.0.0 (ae18d6b) for transitive dep github.com/mitchellh/go-homedir
  Locking in v1.1.2 (44a8c5f) for transitive dep github.com/miekg/dns
  Locking in master (1b0c979) for transitive dep github.com/micro/cli
  Locking in v1.0.0 (a38c501) for transitive dep github.com/mitchellh/hashstructure
  Locking in v0.8.1 (ba968bf) for transitive dep github.com/pkg/errors
  Locking in master (cb59ee3) for transitive dep golang.org/x/sys
Removing intermediate container 6430d76a5194
 ---> cbda7a7232c1
Step 6/12 : RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo .
 ---> Running in 18cba6d4d370
# gotut/consignment-service/vendor/github.com/micro/go-micro/registry/gossip/proto
vendor/github.com/micro/go-micro/registry/gossip/proto/gossip.pb.go:21:11: undefined: proto.ProtoPackageIsVersion3
# gotut/consignment-service/vendor/github.com/miekg/dns
vendor/github.com/miekg/dns/dnssec_keyscan.go:295:7: undefined: strings.Builder
vendor/github.com/miekg/dns/msg_helpers.go:270:8: undefined: strings.Builder
vendor/github.com/miekg/dns/serve_mux.go:43:9: undefined: strings.Builder
vendor/github.com/miekg/dns/types.go:432:10: undefined: strings.Builder
vendor/github.com/miekg/dns/types.go:456:10: undefined: strings.Builder
vendor/github.com/miekg/dns/types.go:484:10: undefined: strings.Builder
vendor/github.com/miekg/dns/types.go:505:29: undefined: strings.Builder
vendor/github.com/miekg/dns/types.go:515:28: undefined: strings.Builder
The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo .' returned a non-zero code: 2
Makefile:6: recipe for target 'build' failed
make: *** [build] Error 2

```

**Comment by ivucica** [comment]
It's inappropriate to use issues as a support mechanism. It's very inappropriate to use it when the issue is unrelated to this project.

**Comment by meysam81** [comment]
@ivucica You're right man, my bad.
And for those who came across my issue, [this](https://github.com/golang/dep/issues/2083#issuecomment-453850370) solved my problem.

**Comment by dongzhanjun0817** [comment]
What is the difference between ProtoPackageIsVersion3 and ProtoPackageIsVersion2?
How to make ProtoPackageIsVersion2 to ProtoPackageIsVersion3?
