### ISSUE TITLE
protoc-gen-go compile error "use of internal package not allowed" on go1.[4,5]

### ISSUE THREAD

**Issue by dhubler** [golang/protobuf#45]
dhubler@duck ~/work/conf2/conf2-restconf $ go get -u github.com/golang/protobuf/proto
dhubler@duck ~/work/conf2/conf2-restconf $ go get -u github.com/golang/protobuf/protoc-gen-go
package github.com/golang/protobuf/protoc-gen-go
	imports github.com/golang/protobuf/proto
	imports github.com/golang/protobuf/protoc-gen-go/descriptor
	imports github.com/golang/protobuf/protoc-gen-go/generator
	imports github.com/golang/protobuf/protoc-gen-go/plugin
	imports github.com/golang/protobuf/protoc-gen-go/internal/grpc
	imports github.com/golang/protobuf/protoc-gen-go/internal/grpc
	imports github.com/golang/protobuf/protoc-gen-go/internal/grpc: use of internal package not allowed
dhubler@duck ~/work/conf2/conf2-restconf $ env | grep GO
GOROOT=/home/dhubler/work/conf2/go
GOPATH=/home/dhubler/work/conf2/conf2-restconf
dhubler@duck ~/work/conf2/conf2-restconf $ go version
go version devel +71859ef Mon Jun 22 06:57:19 2015 +0000 linux/amd64

**Comment by dsymonds** [comment]
The go tool at tip is broken when dealing with internal packages. See golang/go#11307.
