### ISSUE TITLE
Scalar Value Types Problems repeated string --> why not []*string pass by reference

### ISSUE THREAD

**Issue by shiywang** [golang/protobuf#450]
according to scalar value types in golang  
```
.proto Type                Golang Type
string               -->      *string
```
But why  `repeated string --> []string`  instead of `repeated string -->  []*string` ?

My user case is here:
I'm using reflect to set value to `Message` struct, roughly like this:
```
v := reflect.ValueOf(msg).Elem()
switch v.Field(i).Interface().(type) {
         case *bool:
                      var tmpBool bool
                      cmd.Flags().BoolVarP(&tmpBool, name, shorthand, bVal, usage) 
		      v.Field(i).Set(reflect.ValueOf(&tmpBool))
         case []string:
                      var tmpSliceString []string
		      cmd.Flags().StringSliceVarP(&tmpSliceString, name, shorthand, defaultValue, usage)
                      v.Field(i).Set(reflect.ValueOf(tmpSliceString))   //set the SliceFlag here
...


My message struct is below:
type Test struct {
	BoolFlag         *bool    `protobuf:"varint,1,opt,name=BoolFlag" json:"BoolFlag,omitempty"`
	StringFlag       *string  `protobuf:"bytes,2,opt,name=StringFlag" json:"StringFlag,omitempty"`
	Int32Flag        *int32   `protobuf:"varint,3,opt,name=Int32Flag" json:"Int32Flag,omitempty"`
	SliceFlag        []string `protobuf:"bytes,4,rep,name=SliceFlag" json:"SliceFlag,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}
```
the value `tmpBool` is currently only initial but it may be changed in other places, so pass a `*bool` can make my message perceive the changes, but `[]string` without pointer only copy the value which initial just empty, but that value may changed, but message can't perceive that.

is there any way to generate []*string maybe ? if not, is there any workaround here?
Thanks

**Comment by shiywang** [comment]
I've find a workaround here using an extra message 
```
message Slice {
    repeated string value = 1;
}
```
but still wondering why not `repeated string --> []*string`

**Comment by dsnet** [comment]
The `proto2` format allows for optional values. Since Go lacks [optional types](https://github.com/golang/go/issues/7054) or [unions types](https://github.com/golang/go/issues/19412), it resorted to using pointers to indicate the difference between a set zero value and an unset value. As for slices, there is no need to make that distinction.

Furthermore, I don't think it's feasible to add an option just to allow generating `[]*string` instead of `[]string`.
