### ISSUE TITLE
jsonpb: Any type has "type.googleapis.com/" prefix

### ISSUE THREAD

**Issue by thetechnick** [golang/protobuf#452]
I am starting to use the Any-type for error/status details and some custom messages.
Because I am using the awesome grpc-gateway (https://github.com/grpc-ecosystem/grpc-gateway) my application can also provide a http/json api.

When converting any objects to JSON a `@type` field is added which includes the concrete type the any object contains. But I am wondering about the `type.googleapis.com/` prefix. This prefix does not include any useful information (right now?) and I cant find documentation why it is even added (links are highly appreciated).

I want to avoid that Users of my API might be confused to search in googles API documentation for error types of my application, so I would like to change this prefix to point to `type.<myapp>.<cool TLD>` where I am able to host documentation about the types used by my application.

**Example**
```
{
  "code": 3,
  "message": "bad request",
  "details": [
    {
      "@type": "type.googleapis.com/<some custom error type>",
      "field": "device",
      "description": "device can not be empty"
    }
  ]
}
```

**Comment by dsnet** [comment]
What is the proto package and name of message you are putting the `Any` message? The type URL should be generated from that.

\cc @cybrcodr Seems like a jsonpb issue.

**Comment by cybrcodr** [comment]
The default type URL for a message type is type.googleapis.com/\<packagename\>.\<messagename\>. If you want to change the prefix, you need to set the TypeUrl field of your Any message, e.g.
```go
m := &Message{
    AnyField: any.Any{
        TypeUrl: "foobar.com/fancy.Error",
        Value: bytes,
    },
}
```

There is a testcase for this in https://github.com/golang/protobuf/blob/master/jsonpb/jsonpb_test.go#L405.

**Comment by thetechnick** [comment]
@cybrcodr Thanks for pointing this out.
I think I overlooked this, because I was using `ptypes.MarshalAny()` where you can`t override the default.
