### ISSUE TITLE
Protoc go output with grpc plugin in super-directory doesn't work

### ISSUE THREAD

**Issue by Xjs** [golang/protobuf#456]
On Windows 10, `protoc --go_out=plugins=grpc:../output input.proto` doesn't work (even if `../output` directory exists). Error message:

```plugins=grpc;..\output/: No such file or directory```

`protoc --go_out=plugins=grpc:output input.proto` and even `protoc --go_out=plugins=grpc:./output input.proto` do work (with existing `./output` directory of course).

I'm not sure if this issue is correctly placed here, or rather in https://github.com/grpc/grpc or in https://github.com/google/protobuf.

**Comment by paranoiacblack** [comment]
I'm on Windows 10 attempting to compile the math proto in https://github.com/paranoiacblack/gots and this seems to work fine. I'm only unable to reproduce this issue if the specified directory indeed doesn't exist. I downloaded the `protoc` binary via `Chocolatey`, which distributes `libprotoc 3.2.0`.

Please check which version of `protoc` this fails on and re-open if upgrading to a newer version does not resolve this issue.

**Comment by Xjs** [comment]
I have `protoc` installed via `mingw64`, and it appears to be `libprotoc 3.5.0`. However, using your linked repository, I can reproduce the issue:

`$ git clone https://github.com/paranoiacblack/gots.git`
`$ cd gots`
`$ mkdir test`
`$ cd math`
`$ protoc --go_out=plugins=grpc:../test/ math.proto`

Output:
`plugins=grpc;..\test\/: No such file or directory`

As noted above, the issue only occurs when attempting to output into a ../something subdirectory of the parent directory AND using the grpc plugin. All of the below work fine.

`protoc --go_out=../test/ math.proto`
`protoc --go_out=plugins=grpc:. math.proto`
Even `protoc --go_out=plugins=grpc:.. math.proto`

**Comment by puellanivis** [comment]
I noticed something in both of these reports: `plugins=grpc;..\output/` and `plugins=grpc;..\test\/`…

And noting the now explicit mention of MinGW, happened upon this: http://www.mingw.org/wiki/Posix_path_conversion

The answer is: MinGW and/or MSYS are mangling your paths, and you’re actually calling `protoc --go_out=plugins=grpc;..\\test\\ math.proto`, which the compiler is correctly rejecting.

The solution is to turn off the path mangling (the specifics vary a bit), but anyways protoc, grpc and protoc-gen-go are all behaving as intented. Your shell is just performing unexpected magic.

**Comment by Xjs** [comment]
Oh, I see. Thank you. Although... if the path protoc actually tries to parse reads "..\test", that would be a correct path specification under Windows, so it should be made to work, shouldn't it?

**Comment by puellanivis** [comment]
It’s possible, but there is also the colon to semi-colon mangling going on, which means it’s likely trying to parse `grpc;..\test` rather than `..\test`…

I’m not entirely sure why `--go_out=plugin=grpc:./output` works, though… but frankly, after banging my head on this stuff so long (this is why “magic considered harmful”), I’m inclined to just go, “magic” and be done with it. 😉
