### ISSUE TITLE
The first letter of type/field name is always uppercase in generated pb.go codes.

### ISSUE THREAD

**Issue by updogliu** [golang/protobuf#46]
The first letter of type/field name is always uppercase in generated pb.go codes, making it no way to create non-exported struct/field with protobuf in Go. Is this by design?

**Comment by dsymonds** [comment]
Yes, that's by design. You wouldn't be able to use those structs otherwise.

**Comment by updogliu** [comment]
Doesn't the following package structure make sense?
package abc:
logic.go
data.pb.go

The structs in data.pb.go are only supposed to be used by logic.go, and not outside package abc.

**Comment by dsymonds** [comment]
Nope. Generated protos are supposed to be in their own package. You aren't meant to add your own code alongside it.

**Comment by libreoscar** [comment]
But what if I need to define methods on the pb generated struct? Aliasing them will cause tons of conversions between the original pb structs and the aliases. Any cleverness applicable at here?

**Comment by dsymonds** [comment]
You don't. You define your own types as you need.

**Comment by beenotung** [comment]
My approach is to use script to rename the generated struct
