### ISSUE TITLE
Unable to unmarshal RFC3339 date to timestamp.Timestamp

### ISSUE THREAD

**Issue by diegofu** [golang/protobuf#466]
Can't unmarshal a JSON data with RFC3339 format date into to `timestamp.Timestamp`
```
package main

import (
	"encoding/json"
	"fmt"

	google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
)

type Date struct {
	Time *google_protobuf.Timestamp `json:"time"`
}

func main() {
	date := `{"time": "1985-04-12T23:20:50.52Z"}`
	var d Date

        // This throws an "json: cannot unmarshal string into Go struct field Date.time of type timestamp.Timestamp{}" Error
	json.Unmarshal([]byte(date), &d)
}
```

This works fine when trying to unmarshal the same json into `time.Time`

This is a problem when trying to unmarshal json into protobuf generated golang with type `google.protobuf.Timestamp`

**Comment by cybrcodr** [comment]
You'll need to use the [github.com/golang/protobuf/jsonpb](https://godoc.org/github.com/golang/protobuf/jsonpb) package.
