### ISSUE TITLE
GO Protobuf dependency on native code [c++ or other]

### ISSUE THREAD

**Issue by jay11ca39** [golang/protobuf#467]
As per the documentation:

Prerequisite of using the golang protobuf is to install c++ protobuf code.
But, I think it is required for protobuf compiler only.

Question:
For every call i.e. serailization/deserialization/or other is golang library is calling native c++ code or all the logics are written in golang protobuf library.

In simple words, is there any native interface being used for every call from golang API or it is purely written in golang.

**Comment by cybrcodr** [comment]
The generated Go code for the protobuf is all in Go. 

To generate Go code from proto files, you need the protoc compiler and the Go compiler plugin (protoc-gen-go).  See instructions here -- https://developers.google.com/protocol-buffers/docs/gotutorial#compiling-your-protocol-buffers.

The generated Go protobuf code has dependency on the Go package github.com/golang/protobuf/proto.  So, you typically want to keep a copy of github.com/golang/protobuf repo under your GOPATH when compiling the generated code.

**Comment by jay11ca39** [comment]
Hi @cybrcodr ,
Thanks for the reply..

I am able to generate the code and able to use serialization/Deserialization in my GO sample application.

But my question : 
Apart from go code generation from proto file.
Is there is any native call happen when my application call any of the API of GO protobuf sdk or all the logic of protobuf is written in go layer itself.

**Comment by dsnet** [comment]
Aside from code generation, the rest of Go protobufs is written in Go. The `proto` package does however make heavy use of `unsafe` for performance reasons, but the `unsafe` code does not call `cgo`, so imposes no OS-level dependencies. 

Does that answer your question?

**Comment by jay11ca39** [comment]
Hello @dsnet ,
Yes, that is what i was looking for.
SO, Other than code generation, there is no native protobuf library or code is required for Go protbuf to work..
Thanks for your reply..
