### ISSUE TITLE
Adding sub-plugin to protoc-gen-go

### ISSUE THREAD

**Issue by ashi009** [golang/protobuf#475]
Hi all, 

It's nice that protoc-gen-go supports sub-plugins, which helped me avoids lots of boilerplates I used to write for protoc plugin.

The problem with adding a sub-plugin is that, there is no way to reuse the existing `main.go` when use the package as a whole. The two options are either 
- to copy the content of main file and add additional import to register my plugin, or
- to fork this repo and add a few more files to this package.

Both options makes it difficult for me to keep things up-to-date with the upstream. Could you suggest a better way to do this?

Thanks!

**Comment by awalterschulze** [comment]
I created this
https://github.com/gogo/protobuf/blob/master/vanity/command/command.go

And then it is easily usable like this:
https://github.com/gogo/protobuf/blob/master/protoc-gen-gofast/main.go

**Comment by dsnet** [comment]
The plugin mechanism was originally designed just for grpc and not too much though was put into how it is used today. There aren't any plans to improve plugin support for now given that other areas of Go protobufs require more attention.

Forking the repo or copying the content of the main file are fine approaches for now.

**Comment by dsnet** [comment]
Support for plugins in general needs to be discussed. If we decide to provide first-class support for plugins, there will probably be an entire redesign.

Closing this in favor of the umbrella issue #547.
