### ISSUE TITLE
process: merge dev branch into master

### ISSUE THREAD

**Issue by afiune** [golang/protobuf#479]
Hi, 👋 

This is a simple **question** in regards the release process of this repository;

> **When does 'dev' branch gets merge to 'master'?**

Thanks in advance.
  
![tenor-174386324](https://user-images.githubusercontent.com/5712253/34618553-1807615a-f20d-11e7-800a-eabc4d0647f8.gif)

**Comment by dsnet** [comment]
Official announcement made: https://groups.google.com/forum/#!topic/golang-nuts/F5xFHTfwRnY

Target date: April 30th.

**Comment by dsnet** [comment]
This happened.
