### ISSUE TITLE
How to identify version

### ISSUE THREAD

**Issue by Kulak** [golang/protobuf#480]
I am looking at an older copy of protoc-gen-go on Linux and I am not sure what version I have.  How do I location the version?

I tried passing -h option directly and application seems to expect STDIN as it just sits waiting and does nothing.

Thank you

**Comment by dsnet** [comment]
Unfortunately, there is currently no mechanism to bake version information into the compiled binary. As a result there is also no API to retrieve such information.

We should probably fix this for `protoc-gen-go`, but it's not a high priority item.
