### ISSUE TITLE
Invalid UTF-8 in strings are not rejected

### ISSUE THREAD

**Issue by dsnet** [golang/protobuf#484]
The proto2 and proto3 specifications state that the string type must be encoded as valid UTF-8. Currently the Go implementation neither checks that the string is valid when marshaling, nor checks that the string is valid when unmarshaling. This is contrary to the stated specification and the C++ implementation, which does reject these cases.

However, making this change is likely to break a number of users.

**Comment by dsnet** [comment]
Change made on `dev` branch.

**Comment by orian** [comment]
For a people googling, in some cases a protobuf message created in Go is causing a Java exception: "com.google.protobuf.InvalidProtocolBufferException: Protocol message had invalid UTF-8"

This bug was a reason for that.

**Comment by glasser** [comment]
We're interested in using this soon. What's the status of the dev branch? Is it likely to be released to master at some point?

**Comment by dsnet** [comment]
#479. It's happening on April 30th.
