### ISSUE TITLE
jsonpb: make Marshal and Unmarshal use []byte directly

### ISSUE THREAD

**Issue by ldelossa** [golang/protobuf#485]
Hello,

Currently we are required to instantiate a Marhaler/UnMarshaler object. The more notable one of these objects is the Marshaler. A simpler interface may be to create a `DefaultMarshal` method in this package which marshals a protobuf buffer into a byte array keeping this usage more aligned to the standard library? My current assumption is that we instantiate in order to hold configuration state in the Marshaler object - if this is not the case then my understand is not correct and this may not be feasible.

**Comment by dsnet** [comment]
I don't quite understand what you are asking for. Can you give some example code?

**Comment by ldelossa** [comment]
Taking a look here: 
https://github.com/ldelossa/userd/blob/grpc-support/usershandler.go#L44

I have to to the following to the following to write a byte array to the ResponseWriter

```
		var j *bytes.Buffer
		marshaler := &jsonpb.Marshaler{}
		marshaler.Marshal(j, u)
		w.Write(j.Bytes())
		return
```

The normal standard library is simpler - it would just be

```
j, err := json.Marshal(u)
w.Write(j)
```

Introducing a method such as jsonpb.DefaultMarshal() could then be used

```
j, err := jsonpb.DefaultMarshal(u)
w.Write(j)
```

This would keep things more aligned to the standard library.

**Comment by dsnet** [comment]
Ah, you're reporting regarding the `jsonpb` package. Yes, that package could use a refactoring. I'm in the process of drafting up plans to clean up that package.

For future reports, it would be helpful to be specific regarding what you are talking about.

**Comment by ldelossa** [comment]
@dsnet whoops sorry! for some reason I thought I was in a jsonpb specific repo. My apologies.

**Comment by Sytten** [comment]
Bump!

**Comment by ldelossa** [comment]
@dsnet I was going to attempt a PR to add new mthods but i noticed you tagged it as pending-v2. Should I hold off?

**Comment by dsnet** [comment]
@ldelossa, yes please. This is new API is already implemented in v2.

**Comment by MeNsaaH** [comment]
@dsnet when will the v2 be released?

**Comment by dsnet** [comment]
The [next major revision](https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.20.0) has been released. See the [`protojson`](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson) package.
