### ISSUE TITLE
jsonpb: Marshaler don't respect json.Marshal's specification

### ISSUE THREAD

**Issue by jmzwcn** [golang/protobuf#487]
such as: json's MarshalJSON/UnmarshalJSON interface/tag:`json:",inline"

I find the result is different when I adopt marshaler.Marshal&&json.Marshal to encode  NOT-well-known types[e.g. k8s's object(service/deployment/ingress)].

native json.Marshal(ingress) 's result:
```json
{
    "metadata": {
        "name": "ingress1",
        "namespace": "default"
    },
    "spec": {
        "rules": [
            {
                "host": "www.a.com",
                **"http": {**
                    "paths": [
                        {
                            "path": "/a",
                            "backend": {
                                "serviceName": "a",
                                "servicePort": 81
                            }
                        }
                    ]
                }
            }
        ]
    }
}
```
but jsonpb.Marshaler's result:
```json
{
    "metadata": {
        "name": "ingress1",
        "namespace": "default"
    },
    "spec": {
        "rules": [
            {
                "host": "www.a.com",
                **"ingressRuleValue":** {
                    "http": {
                        "paths": [
                            {
                                "path": "/a",
                                "backend": {
                                    "serviceName": "a",
                                    "servicePort": 81
                                }
                            }
                        ]
                    }
                }
            }
        ]
    }
}
```
the above is just for tag:`json:",inline", actually this issue also happen when decode a json to pb.

**Comment by dsnet** [comment]
I'm not sure what you are asking for. Can you give a code example?

**Comment by jmzwcn** [comment]
json.Marshal("ingress") 's format:
{
    "metadata": {
        "name": "ingress1",
        "namespace": "default"
    },
    "spec": {
        "rules": [
            {
                "host": "www.a.com",
                **"http": {**
                    "paths": [
                        {
                            "path": "/a",
                            "backend": {
                                "serviceName": "a",
                                **"servicePort": 81**
                            }
                        }
                    ]
                }
            }
        ]
    }
}

**Comment by jmzwcn** [comment]
jsonpb.Marshaler's result:
```json
{
    "metadata": {
        "name": "ingress1",
        "namespace": "default"
    },
    "spec": {
        "rules": [
            {
                "host": "www.a.com",
                **"ingressRuleValue":** {
                    "http": {
                        "paths": [
                            {
                                "path": "/a",
                                "backend": {
                                    "serviceName": "a",
                                    "servicePort": 81
                                }
                            }
                        ]
                    }
                }
            }
        ]
    }
}
```

**Comment by jmzwcn** [comment]
the above is just for tag:`json:",inline", actually this issue also happen when decode a json to struct.

**Comment by dsnet** [comment]
You going to need to provide more information. What are the relevant Go types of the data structures near what's going wrong.

**Comment by jmzwcn** [comment]
a case:
https://github.com/kubernetes/api/blob/master/extensions/v1beta1/types.go#L673

**Comment by dsnet** [comment]
There are many things going wrong here:
* I see `json` tags with the `inline` directive. This does not exist in the standard library (see golang/go#6213).
* The generated protobufs are by `gogo/protobuf`, which is not fully compatible with `golang/protobuf/jsonpb` when extended features are used.
* There are hand-crafted protobufs, which are not compatible with the `jsonpb` package.

I'm inclined to mark this as "wont-fix" since there are just too many wrong things stacked upon each other.

**Comment by jmzwcn** [comment]
1. actually standard lib json.Marshal have already support ",inline" tag as above json.Marshal(ingress) 's ouput.
2. jsonpb.Unmarshal couldn't parse the json-str like json.Unmarshal, which is not related to gogo/protobuf and golang/protobuf I think.

**Comment by dsnet** [comment]
1. It doesn't. It's working by chance because `IngressRuleValue` is an anonymous field. This has nothing to do with the standard library `json` package.
2. It can't parse it because the destination isn't even a valid Go protobuf message.

**Comment by dsnet** [comment]
Not to mention, the following:
```
IngressRuleValue `json:",inline,omitempty" protobuf:"bytes,2,opt,name=ingressRuleValue"`
```
is inconsistent with itself:
1. It's an anonymous field.
2. The `json` tag indicates that it is unnamed.
3. But, the protobuf tag gives it an explicit name.

I don't see how you can reasonably expect sane behavior in this situation.

**Comment by jmzwcn** [comment]
Follow standard golang/json.Marshal/Unmarshal behavior, I think it is a good choice, isn't it?

**Comment by dsnet** [comment]
We can't. The `protobuf` tag explicitly tells us that there is a field name. This struct is poorly constructed and inconsistent with itself. I'm marking this as won't fix as this is an issue with Kubernetes.
