### ISSUE TITLE
jsonpb: When marshaling to JSON, a timestamp should trim all fractional digits if possible

### ISSUE THREAD

**Issue by ochen** [golang/protobuf#488]
According to the proto3 to JSON specification, the JSON representation of a timestamp field

> Uses RFC 3339, where generated output will always be Z-normalized and uses **0**, 3, 6 or 9 fractional digits.

However, the jsonpb package will always use 3,6,9 fractional digits, leaving a timestamp with integer seconds ends with a suffix `.000Z`. I think this may be incomplete.

**Comment by dsnet** [comment]
I noticed this also not long ago.

**Comment by dsnet** [comment]
Fixed by #490
