### ISSUE TITLE
go clone implementation for empty maps vs zero length maps vs nil

### ISSUE THREAD

**Issue by karlmutch** [golang/protobuf#495]
When using the clone feature of protobuf the maps produced do not exactly mirror the input being cloned.  A zero length map will result in a nil value.

The desired behavior would be that a zero length map would be further tested to see if the value was a nil or an empty map and the cloned map would respect the input

**Comment by dsnet** [comment]
Clone is meant to be equivalent to the following:
```go
m2 := reflect.New(reflect.ValueOf(m).Type().Elem()).Interface().(proto.Message)
b, _ := proto.Marshal(m)
proto.Unmarshal(b, m2)
return m2
```

Since the protobuf specification makes no distinction between an empty map and an unset map, it is a mistake for Clone to make that distinction in Go as well.

Thus, I'm inclined to say that this is working as intended.
