### ISSUE TITLE
Please keep a changelog

### ISSUE THREAD

**Issue by AlekSi** [golang/protobuf#502]
Since we have v1.0.0 now 🎉, please create and [keep a changelog](http://keepachangelog.com/).

Simple `CHANGELOG.md` file in the repo and/or releases with descriptions in the [releases tab](https://github.com/golang/protobuf/releases) (like grpc-go [does](https://github.com/grpc/grpc-go/releases)) will work.

**Comment by dsnet** [comment]
Closing this. When v1.1.0 is tagged, it will include a list of changes relative to v1.0.0.

**Comment by tangxinfa** [comment]
Why not set tag to v2.0.0, because in v1.0.0, github.com/golang/protobuf/protoc-gen-go/grpc/grpc.go 's generatedCodeVersion set to 3, and in v1.1.0 it set to 4, hopes the following will works:
     go get -u gopkg.in/golang/protobuf.v1/protoc-gen-go    # for generatedCodeVersion set to 3
     go get -u gopkg.in/golang/protobuf.v2/protoc-gen-go    # for generatedCodeVersion set to 4
