### ISSUE TITLE
non-standard import "github.com/golang/protobuf/proto" in standard package

### ISSUE THREAD

**Issue by puneetmathur-87** [golang/protobuf#503]
Not able to use the protoc generated code due to the error while running i.e. non-standard import "github.com/golang/protobuf/proto" in standard package.

Please help.

![image](https://user-images.githubusercontent.com/33253497/35637655-db0ed2fa-06da-11e8-8141-480e989bff86.png)

**Comment by paranoiacblack** [comment]
I'm not sure what IDE you're using or which command generates that error. Can you elaborate on how you encountered this? Also, does the package that uses this proto fail to compile with the `go` tool?

The proto import you have is totally fine, compare to my simple math server: https://github.com/paranoiacblack/gots/blob/master/math/math.pb.go.

**Comment by dsnet** [comment]
I believe your setup of GOROOT and GOPATH may be mixed up: https://stackoverflow.com/questions/36901658/error-non-standard-import-gopkg-in-yaml-v2-in-standard-package

**Comment by paranoiacblack** [comment]
@puneetmathur-87 Please re-open if you can provide more information about this problem and the suggestion solutions are not working.
