### ISSUE TITLE
support custom message validation in JSONPB when checking for required fields

### ISSUE THREAD

**Issue by jhump** [golang/protobuf#509]
Pull request #472 added new checks to ensure that messages are valid -- e.g. any field that is required is actually present.

I'm filing this issue primarily to support dynamic message implementations (such as [this](https://github.com/jhump/protoreflect/blob/7bbb1c81639c21de5c473d7c2b397fc3aba9ebe2/dynamic/dynamic_message.go#L57), which works fine in `master`, but does not work in `dev`).

Attempts to use `jsonpb` to marshal/unmarshal a dynamic message can now result in a panic:

```
panic: reflect.Value.Interface: cannot return value obtained from unexported field or method 
```

This happens if the message struct contains any unexported pointer values that are non-nil (including slice or map fields that contain a non-nil pointer element). When examining a message, it uses `val.Interface().(proto.Message)` to see if the pointer is a nested message which needs to be recursively checked.

1. I would like to be able to customize this check, for example by having the message provide a `ValidateRecursive()` method which can be called *instead* of using the default check.
2. It would be really nice if this check (as implemented, for generated messages) were an exported function in the `proto` package, such as:
```go
proto.CheckRequiredFields(proto.Message) error
```

I have a fix that addresses the first bullet.

The second bullet would, of course, allow `jsonpb` to share code with the `proto` package for checking that required fields are present. But it would *also* make it easier for messages to implement `ValidateRecursive()` since they could call this exported function to apply default logic (if applicable), and they could also use it to apply normal validation for nested message fields.

**Comment by dsnet** [comment]
Adding `ValidateRecursive` would work in the short term, but it seems to be just a band-aid on a bigger problem. I believe that #364 is the proper solution for this. There needs to be a agreed-upon API for all messages can interact with the `proto` and `jsonpb` without baking in ad-hoc special cases.

I know I have been saying #364 is the solution for many problems, and I truly believe it is. I'm still working on the API design, and it's really tricky to get the details right with all the edge cases of the protobuf specification.

The being said, modifying the logic of `jsonpb` to at least not panic is fine.

**Comment by jhump** [comment]
> Adding `ValidateRecursive` would work in the short term, but it seems to be just a band-aid on a bigger problem.

I agree. And a behaviorally complete message interface would be awesome!

I suppose an alternate resolution might be to just have `jsonpb`, when performing this check, ignore unexported fields and fields that don't have a protobuf tag (as is likely to happen with non-generated message implementations).

I think that would effectively make this check a no-op when marshaling and unmarshaling my dynamic message implementation. (My implementation already does this check [internally](https://github.com/jhump/protoreflect/blob/6789aeb40b62c4608d11f2b1fa133cc18a341ffb/dynamic/json.go#L347) anyway.)

**Comment by dsnet** [comment]
> I suppose an alternate resolution might be to just have jsonpb, when performing this check, ignore unexported fields and fields that don't have a protobuf tag (as is likely to happen with non-generated message implementations).

A fix of this nature sounds fine. Want to send a PR taking that approach?

**Comment by jhump** [comment]
> A fix of this nature sounds fine. Want to send a PR taking that approach?

Sure

**Comment by dsnet** [comment]
#510 should restore the prior behavior. We'll let #364 be the long term solution.
