### ISSUE TITLE
jsonpb: Accept interface{} instead of proto.Message

### ISSUE THREAD

**Issue by icholy** [golang/protobuf#512]
Since `jsonpb.Unmarshaler.Unmarshal` only accepts types that implement `proto.Message`, there's no way to unmarshal a into a slice.

**Comment by dsnet** [comment]
Hi, thanks for the request, but I'm going to close this as "working-as-intended". There is no way we can switch the function signature without breaking compatibility.

Functionality that you are seeking could be satisfied by #256. If we made each `proto.Message` also satisfy `json.Marshaler` and `json.Unmarshaler`. In that case, you could pass a slice of generated messages to the standard library `json.Unmarshal` and things would work as you expect.

**Comment by icholy** [comment]
@dsnet what about exporting additional methods?

**Comment by dsnet** [comment]
I don't understand your question. What about exported methods?

**Comment by icholy** [comment]
@dsnet instead of changing the existing methods, we could add additional methods that take an interface.

**Comment by dsnet** [comment]
Ah. No, we won't be adding new functions. That adds complexity and more user confusion. #256 is a much better approach for what you desire.
