### ISSUE TITLE
protoc-gen-go generator missing type in printer

### ISSUE THREAD

**Issue by Tommy-42** [golang/protobuf#517]
Hello I had a strange error today while trying to generate some custom code: 
`2018/02/19 14:10:09 protoc-gen-gogo: error:unknown type in printer: int64` 

Looking into the `P()` implementation I am seeing 
```
func (g *Generator) P(str ...interface{}) {
	if !g.writeOutput {
		return
	}
	g.WriteString(g.indent)
	for _, v := range str {
		switch s := v.(type) {
 			...
		case int:
			fmt.Fprintf(g, "%d", s)
		case *int32:
			fmt.Fprintf(g, "%d", *s)
		case *int64:
			fmt.Fprintf(g, "%d", *s)
		case float64:
			fmt.Fprintf(g, "%g", s)
		case *float64:
			fmt.Fprintf(g, "%g", *s)
		default:
			g.Fail(fmt.Sprintf("unknown type in printer: %T", v))
		}
	}
	g.WriteByte('\n')
}
```

There is no case for `case int32:` && `case int64:` ? there is any reason for that ?

If not, an open a PR is available.

Best regards,

**Comment by neild** [comment]
The generator package's interface isn't really intended for general-purpose use. (README.md describes it as "not supported and subject to incompatible changes without notice".) Given that the package API is intentionally unsupported as it is, I think that extending it to support additional uses would be a mistake.

**Comment by awalterschulze** [comment]
Although it is something really simple to fix and the current behavior of only printing pointers to int64 and int32 and not int64 and int32 themselves is very weird.
Are you sure you don't want to make this fix?

**Comment by neild** [comment]
I'm going to close this.

The generator package is not a supported public interface. If we make a change to it to support an additional external use, we are implicitly committing to supporting that use in the future. It's simply not practical to do that with the package API as it stands, and I don't want to give the false impression that we can do so.

**Comment by dsnet** [comment]
Discussion about whether to more strongly support plugins and if so, how is over at #547.
