### ISSUE TITLE
Unexpected quotes around Int64Value fields

### ISSUE THREAD

**Issue by briansorahan** [golang/protobuf#519]
Migrating the discussion from https://github.com/gogo/protobuf/issues/387
Is it expected that jsonpb.Marshaler adds quotes around google.protobuf.Int64Value fields?

**Comment by dsnet** [comment]
Yes. See https://developers.google.com/protocol-buffers/docs/proto3#json.

The fundamental issue is that most JSON parsers interpret numbers as an float64, which is problematic because it cannot represent the full extent of an int64 losslessly. For that reason, int64 is represented as a string, as opposed to a number. It's really unfortunate.

**Comment by frojasg** [comment]
Do you have a more concrete example when this happens?

**Comment by puellanivis** [comment]
> Do you have a more concrete example when this happens?

```json
{
  "unsafe_int_value": 9007199254740993,
}
```

You can get a sense for what happens in this case with https://play.golang.org/p/PhNVDK8iJKy

While go’s JSON parser will parse that value with full precision into an int64, Javascript itself (and by extension technically how JSON is defined) treats it as a float64, which means it loses one bit of precision at the end, and after being cast back and forth through a float64, it comes out equal to 9007199254740992 (2^53). Larger values will lose even more precision.

**Comment by frojasg** [comment]
makes sense. Thank you.

**Comment by dsnet** [comment]
@puellanivis is correct. In case you're wondering why we choose to always encode int64 and uint64 as strings even when it is below 2^53, it is to make it clear and up front that the type is a string as opposed to more surprisingly (even though the current behavior is surprising) switch types when the number is above a certain value.
