### ISSUE TITLE
[dev] protoc-gen-go: use different name for newly generated Marshal and Unmarshal

### ISSUE THREAD

**Issue by awalterschulze** [golang/protobuf#530]
The current golang/protobuf API allows the user to write their own Marshal and Unmarshal methods.
https://github.com/golang/protobuf/blob/0a4f71a498b7c4812f64969510bcb4eca251e33a/proto/encode.go#L232
This allows them to write efficient versions of these methods.
Yes, you can write even more efficient marshaling code than the code that gogoprotobuf generates using the specifics of a message.

The new `dev` branch generates Marshal and Unmarshal methods for all messages, that refer back to the library.  Although this can be nice and solves some other problems, this will break other users' code and give the following compile error:

```
./pop.go:36:6: method redeclared: MyType.Marshal
	method(*MyType) func([]byte, bool) ([]byte, error)
	method(MyType) func() ([]byte, error)
```

I would like to not remove this option from users.
I propose that these method names be changed to not break users' code.

I discovered this while merging the dev branch into gogoprotobuf.
I can easily check whether someone generates a Marshal method and then not generate the table Marshal method, but I cannot check whether someone has manually written an even more efficient Marshal method.

**Comment by dsnet** [comment]
I wasn't fond of the new methods we added for the table-driven optimization. I believe they added to the technical-debt of protobufs. I'm also not fond of the `Marshal([]byte, bool)` signature, which assumes that deterministic is the only option we would ever support.

I'll perform the cleanup work inside Google and rename this.

**Comment by awalterschulze** [comment]
Thank you so much :)
Also don't forgot about `Unmarshal` as well.

**Comment by awalterschulze** [comment]
This needs to be reopen.  The order of the type asserts does not allow for the generated Marshalers and Unmarshalers to be called.
See my diff in gogoprotobuf
https://github.com/gogo/protobuf/commit/100bcd0687076c996fc028e90de0a162b440a171
Would it possible to swap the order of the type asserts for all the Marshal and Unmarshal type asserts to first check for generated Marshal and Unmarshal methods, before falling back to the generated XXX_Unmarshal and XXX_Marshal methods?
