### ISSUE TITLE
proposal: proto: make protos comparable

### ISSUE THREAD

**Issue by tomfitzhenry** [golang/protobuf#531]
It's useful for protos to be comparable, so they can be put in map keys. They're data, after all. This is [supported in the Java protobuf library](https://github.com/google/protobuf/blob/a6037c5230c0ccb6531f80cef909dbfe37257884/java/core/src/main/java/com/google/protobuf/AbstractMessage.java#L138-L152), and I can see it was a common idiom in the Golang library, before protos were made non-comparable.
 
Golang protos are non-comparable because they include XXX_unrecognized slices which are non-comparable.

The only solutions I can think of are either golang language limitations with v2 proposals, or a
bit gross:

* slices be made comparable https://golang.org/issue/23725
* map keys use a custom equality (in which case they could use proto.Equals) https://golang.org/issue/21829
* XXX_unrecognized be stored in a comparable variable-length data type (string
  seems to be the only option. eww)
* generate proto structs data type that don't include the XXX_unrecognized field
  (eww). This is what library users like myself end up doing by hand.

**Comment by dsnet** [comment]
Whether a `proto.Message` is comparable or not (and usable by maps) is currently defined by the language specification. Without help from the language, I don't think we can provide a satisfactory answer to this issue.

With Go2 being seriously considered, let's put this issue on hold until something upstream changes.

**Comment by neild** [comment]
I don't see any way we can do this.

* Repeated fields necessarily make messages non-comparable.
* Fields of type `bytes` necessarily make messages non-comparable.
* Submessages, while technically comparable, are not practically so. (Pointer equality is not a useful comparison.)
* A field set to its default value is equal to an unset field. This cannot be represented with struct comparability.
* The performance optimizations on the dev branch add an `XXX_sizecache` field which, while technically comparable, is not practically so.

If Go 2 were to add an overloadable `==` operator, we certainly could support it, but that's much too speculative to consider at this time. I think we should just close this.

**Comment by dsnet** [comment]
Furthermore, equality is ill-defined for protos. For example, is equal suppose to:
* Compare unknown fields fields?
* Compare the encoded bytes of `Any`? Or should it try any unmarshal it first? What if it cant?
* Similarly, what should it do with field extensions?

You could strictly define what equality means (that's what `proto.Equal` does), but I am certain that the definition will be very surprising to various users at various points. Using protos as a key seems dangerous given the complexity of protobufs.

**Comment by tomfitzhenry** [comment]
> Furthermore, equality is ill-defined for protos.

Fair point. I can see that there isn't a reasonable default equality (and if in doubt, leave it out).

AFAICT, C++ also doesn't implement a default equality, and instead has [message_differencer, which captures some of these definitions of equality]( https://github.com/google/protobuf/blob/9dc0a4d5cf181845c4c8ca6c482ec38cc1835bbc/src/google/protobuf/util/message_differencer.h#L347-L378).

**Comment by dsnet** [comment]
The fact that message_differencer provides many ways to adjust the comparison is indicative that people won't agree what the right definition of equality should be ;)

**Comment by awalterschulze** [comment]
So technically I agree, in general protos cannot be used as map keys, but protos which have no repeated fields or maps technically can.

Also its probably an edge case, but in the case where this is something a user wants to do, they will end up copying between the generated struct and the struct they actually want to use.  This is something gogoprotobuf strives to avoid.  So generated marshaling and unmarshaling methods is meh, but avoiding these types of copies is where real speed and maintainability can be gained.

For this reason [gogoprotobuf](https://github.com/gogo/protobuf) includes an option to not generate the XXX_unrecognized field.
The golang/protobuf `dev` branch contains more XXX fields which will be added and this will probably result in another option to also turn off the generation of those fields in gogoprotobuf.  I am guessing this will be a contribution coming from the community.
 
Also using protos as map keys is not the only reason you would want to turn off generation of XXX_fields.  One less pointer for the garbage collector to worry about, aesthetics and efficiency of not allocating more memory to copy bytes you don't care about and finally not breaking the API.
But it depends on the use case and that is why this is an option.

Sorry if this was rambly, but I didn't get a lot of sleep.

**Comment by tomfitzhenry** [comment]
> The fact that message_differencer provides many ways to adjust the comparison is indicative that people won't agree what the right definition of equality should be ;)

Indeed! That's why I mentioned it.

> For this reason gogoprotobuf includes an option to not generate the XXX_unrecognized field.

At the moment I cannot change proto libraries, but this is good to know, thanks.
