### ISSUE TITLE
Proto3 Nested Message Getter is not useful

### ISSUE THREAD

**Issue by mwitkow-io** [golang/protobuf#54]
Take this generated code:

```go
type FlagId struct {
	Deployment *DeploymentId `protobuf:"bytes,1,opt,name=deployment" json:"deployment,omitempty"`
	Name       string        `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *FlagId) Reset()         { *m = FlagId{} }
func (m *FlagId) String() string { return proto.CompactTextString(m) }
func (*FlagId) ProtoMessage()    {}

func (m *FlagId) GetDeployment() *DeploymentId {
	if m != nil {
		return m.Deployment
	}
	return nil
}
```

What is the purpose of this Getter? It will not be called on a `nil` `m *FlagId`.
I actually hoped it would create an new instance of the type behind the `Deployment` field, but it seems to not do anything other than a normal `m.Deployment` would.

I really hoped it would create a new instance if it was nil, this way I could solve the problem in without reflection:
https://github.com/gengo/grpc-gateway/issues/32

**Comment by dsymonds** [comment]
The point is so that deeply nested proto types (e.g. message field in a message that's a field of another message, etc.) can be traversed simply, and without regard for nil message pointers along the way. You can write m.GetFoo().GetBar().GetBaz() and only check for nil right at the end.

If you don't find it useful, don't use it.

**Comment by mwitkow-io** [comment]
Oh, didn't know you could do `m.GetFoo().GetBar().GetBaz()`.

That's pretty cool. However, it doesn't strike me as immediately obvious. Is there a place where such things are documented? Like golang/protobuf Tips&Tricks? ;)

**Comment by dsymonds** [comment]
It's mentioned in the README and in the package doc, perhaps not so explicitly.

**Comment by omanamos** [comment]
Is there a reason why the getters don't follow a similar pattern to the C++ API, which allows you to call mutable_field() and creates an object if it doesn't already exist.

Otherwise I end up writing a block like this every time I access a sub message field:
```
if msg.Field == nil {
  msg.Field = &pb.FieldMsg{}
}
```
