### ISSUE TITLE
README.md, proto: remove usage of group from example

### ISSUE THREAD

**Issue by wellsjo** [golang/protobuf#564]
From Google's documentation:
https://developers.google.com/protocol-buffers/docs/proto#groups
```
Groups
Note that this feature is deprecated and should not be used when creating new message types – use nested message types instead.
```

**Comment by dsnet** [comment]
Where are you seeing groups being advertised?

**Comment by wellsjo** [comment]
In the README, right after
> Consider file test.proto, containing

There is a code example that uses a group

**Comment by dsnet** [comment]
Ah. Got it. I was searching for "groups" instead and didn't see that.

**Comment by tmcrain** [comment]
I'll take a look!
