### ISSUE TITLE
proto: Buffer.Marshal is quadratic on dev branch

### ISSUE THREAD

**Issue by rhysh** [golang/protobuf#566]
I attempted to update an application I maintain from github.com/golang/protobuf v1.0.0 to the dev branch, but encountered a significant regression in CPU and memory usage.

My application has a message type with a single "repeated" field. It uses `proto.Buffer` to build a large serialized instance of that message out of many smaller ones by calling `Marshal` with each smaller message. It does not pre-allocate the `proto.Buffer`.

In v1.0.0, `proto.Buffer.Marshal` is based on straightforward use of `append`, which amortizes the cost of allocating a new byte slice when the existing one fills: https://github.com/golang/protobuf/blob/v1.0.0/proto/encode.go#L160-L164

In the dev branch, `proto.Buffer.Marshal` tries to be clever and allocate only as much memory as it needs immediately: https://github.com/golang/protobuf/blob/9c8fb7a95075eb047ab75e702de52f68ff360f17/proto/table_marshal.go#L2666-L2669

The memory allocations in my real program are attributed to line 2668, `p.buf = append(make([]byte, 0, newCap), p.buf...)`

The application could be written differently, but that's how it's worked for the past couple years. This is the first application I've attempted to update to protobuf's dev branch.

---

Here's a reproducer.

With the master branch at v1.0.0, it shows:

```
$ go test -bench=. -count=5
goos: darwin
goarch: amd64
pkg: repro
BenchmarkProtoBuffer-8   	 3000000	       569 ns/op	     143 B/op	       6 allocs/op
BenchmarkProtoBuffer-8   	 3000000	       520 ns/op	     143 B/op	       6 allocs/op
BenchmarkProtoBuffer-8   	 3000000	       529 ns/op	     143 B/op	       6 allocs/op
BenchmarkProtoBuffer-8   	 3000000	       530 ns/op	     143 B/op	       6 allocs/op
BenchmarkProtoBuffer-8   	 3000000	       514 ns/op	     143 B/op	       6 allocs/op
PASS
ok  	repro	11.106s
```

With the dev branch at 9c8fb7a95075eb047ab75e702de52f68ff360f17, it shows:

```
$ go test -bench=. -count=5
goos: darwin
goarch: amd64
pkg: repro
BenchmarkProtoBuffer-8   	  500000	    180284 ns/op	 1004276 B/op	       8 allocs/op
BenchmarkProtoBuffer-8   	  300000	    104283 ns/op	  604249 B/op	       8 allocs/op
BenchmarkProtoBuffer-8   	  300000	    101552 ns/op	  604249 B/op	       8 allocs/op
BenchmarkProtoBuffer-8   	  300000	     99059 ns/op	  604249 B/op	       8 allocs/op
BenchmarkProtoBuffer-8   	  300000	     97260 ns/op	  604249 B/op	       8 allocs/op
PASS
ok  	repro	211.799s
```

```
package repro

import (
	"testing"

	"github.com/golang/protobuf/proto"
	"github.com/golang/protobuf/ptypes/struct"
)

func BenchmarkProtoBuffer(b *testing.B) {
	b.ReportAllocs()
	var buf proto.Buffer
	for i := 0; i < b.N; i++ {
		value := &structpb.Value{Kind: &structpb.Value_BoolValue{BoolValue: true}}
		msg := &structpb.ListValue{Values: []*structpb.Value{value}}

		err := buf.Marshal(msg)
		if err != nil {
			b.Fatalf("buf.Marshal(%q); err = %v", msg, err)
		}
	}

	var msg structpb.ListValue
	err := proto.Unmarshal(buf.Bytes(), &msg)
	if err != nil {
		b.Fatalf("proto.Unmarshal(); err = %v", err)
	}
	if have, want := len(msg.Values), b.N; have != want {
		b.Errorf("len(msg.Values); %d != %d", have, want)
	}
}
```

The total cost in time and memory is O(N^2) in the dev branch rather than O(N) in v1.0.0, but here's the benchstat output with the values of N that `go test` chose for its default benchtime of 1 second:
```
name           old time/op    new time/op    delta
ProtoBuffer-8     532ns ± 7%   12006ns ±28%   +2155.00%  (p=0.008 n=5+5)

name           old alloc/op   new alloc/op   delta
ProtoBuffer-8      143B ± 0%    87705B ±28%  +61232.03%  (p=0.008 n=5+5)

name           old allocs/op  new allocs/op  delta
ProtoBuffer-8      6.00 ± 0%      8.00 ± 0%     +33.33%  (p=0.008 n=5+5)
```

**Comment by dsnet** [comment]
Thank you for the report and reproduction. I'll take a look tomorrow.

\cc @randall77 @LMMilewski

**Comment by rhysh** [comment]
Hi @dsnet , what's the path forward for this bug? Will a patch start within Google and bubble out to the open source copy, or are you interested in a pull request?

**Comment by dsnet** [comment]
I haven't had time yet investigate this (might be a trivial fix). If you want to submit a PR to the dev branch, that'd be great. I'll be happy to review.

**Comment by rhysh** [comment]
I have a fix and a test case now. I don't know how sensitive the proto.Buffer.Marshal method is to changes, and the benchmark results I'm getting with my laptop (while I use it) are pretty noisy. I also haven't verified that my change addresses the original problem I saw in my application.

I plan to check that and to submit the change by the end of tomorrow.

@dsnet which benchmarks (out of the 105 in the dev branch) are the most important?

**Comment by dsnet** [comment]
> @dsnet which benchmarks (out of the 105 in the dev branch) are the most important?

None of them. The benchmarks in this repo aren't that great. Of the 105, did any get drastically worse? If not, I'm not too concerned about them.

Instead, I would run benchmarks on: https://github.com/google/protobuf/blob/master/benchmarks/go_benchmark_test.go.

**Comment by lihailei2016** [comment]
@rhysh @dsnet @jmhodges After you found proto.Marshal, some of the memory in the library will not be automatically recycled, which will cause a heap. This should be a bug. I found it through pprof tool analysis.
