### ISSUE TITLE
declaring variables in import generation

### ISSUE THREAD

**Issue by awalterschulze** [golang/protobuf#57]
https://github.com/golang/protobuf/blob/master/protoc-gen-go/internal/grpc/grpc.go#L116

Depending on the plugin order generation this could result in variables being declared in between import statements, which is invalid go.
Luckily golang/protobuf has just one plugin, so this should not be a problem, but in go1.5 this is a problem for gogo/protobuf.
https://github.com/gogo/protobuf/pull/83
I could easily fix this in gogo/protobuf, but I think this might cause problems for you later as well.  At which point I'll have to undo my fix and merge in your fix :(

**Comment by dsymonds** [comment]
I see. We need to generate the `var _ pkg.Blah` in the regular `Generate` method, not in the `GenerateImports` part.

That should be an easy fix. I'll do that this week.

**Comment by awalterschulze** [comment]
Excellent.
Thank you very much :)

**Comment by dsymonds** [comment]
FYI, I don't think there's anything Go 1.5 specific about this bug. It was always a problem when there was more than one plugin.

**Comment by awalterschulze** [comment]
I agree it is a bug either way, but for some reason this bug is only triggered in my go1.5 users and not by me in go.14
Anyway thank you very much for the fix.
