### ISSUE TITLE
jsonpb: marshalling json.RawMessage returns base64 encoded string

### ISSUE THREAD

**Issue by lnshi** [golang/protobuf#586]
Problem is at this line: https://github.com/golang/protobuf/blob/master/jsonpb/jsonpb.go#L598

Refer here: 

https://groups.google.com/forum/#!topic/Golang-Nuts/38ShOlhxAYY,

and 

https://stackoverflow.com/questions/24229205/marshalling-json-rawmessage-returns-base64-encoded-string

Pls fix, thank u.

**Comment by dsnet** [comment]
Hi. This issue lacks sufficient information. What is the proto message that you are even marshaling? How did you get a `json.RawMessage` in it?

**Comment by lnshi** [comment]
@dsnet Those two discussion topics are just for ur information.

The proto definition can be referred here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/tensor.proto#L57

    repeated bytes string_val = 8;

According to my debug to https://github.com/golang/protobuf/blob/master/jsonpb/jsonpb.go#L598, the input `v` is a byte slice, so:

    [73 32 97 109 32 97 32 115 116 114 105 110 103]

after the `json.Marshal(v.Interface())` returned, the returned `b` is changed to:

    [83 83 66 104 98 83 66 104 73 72 78 48 99 109 108 117 90 119 61 61]

it represents the base64 encoded string of the original string!

Hope i provided sufficient info.

**Comment by dsnet** [comment]
This is not enough information. How is this generated?

A field of `repeated bytes string_val = 8;` should be generated as a `[]string`, where does `json.RawMessage` come into place?
