### ISSUE TITLE
Potential Breaking Change in b4deda0 or recent?

### ISSUE THREAD

**Issue by steve-gray** [golang/protobuf#593]
Working on a project that uses GRPC streaming to send data between services, and we're finding that after this last week or so, if we do a full `dep ensure -update` for our repos,  marshal and unmarshal is partially working.

Here's the lockfile entry for the commit we'd been on previously:

````
[[projects]]
  name = "github.com/golang/protobuf"
  packages = [
    "proto",
    "ptypes",
    "ptypes/any",
    "ptypes/duration",
    "ptypes/timestamp"
  ]
  revision = "e09c5db296004fbe3f74490e84dcd62c3c5ddb1b"
  version = "v1.1.0"
````

We're using this command to generate the protos:

````
protoc --go_out=plugins=grpc,import_path=protos:. *.proto
````

The behaviour is:

- String()'ing the deserialized message shows all fields present and accounted for in the buffer.
- Examining the individual fields reveals they're all at their blank/zero values.

Simply reverting back from master/head b4deda0 down to e09c5db296004fbe3f74490e84dcd62c3c5ddb1b causes the issue to disappear.

**Comment by dsnet** [comment]
Can you give more details about what exactly is shown to be different? It's hard to debug without specific reproductions.

**Comment by dsnet** [comment]
Closing as stale.
