### ISSUE TITLE
The redis queue takes the protobuf data warning

### ISSUE THREAD

**Issue by zhaoyun666** [golang/protobuf#595]
![image](https://user-images.githubusercontent.com/13768589/39610423-b8f8c5f4-4f82-11e8-96d9-3bfcd111da0e.png)
操作系统：
Linux version 2.6.32-431.29.2.el6.x86_64 (mockbuild@c6b9.bsys.dev.centos.org)
分支：master

**Comment by dsnet** [comment]
This error indicates that a proto message contained invalid UTF-8 for a proto message with a `string` field.

The [protobuf specification says regarding `strings`](https://developers.google.com/protocol-buffers/docs/proto):
> A string must always contain UTF-8 encoded or 7-bit ASCII text.

Instead, you should switch the proto field type to the `bytes`.

**Comment by dsnet** [comment]
Closing as stale.
