### ISSUE TITLE
Nested message types

### ISSUE THREAD

**Issue by bendemaree** [golang/protobuf#6]
I have a Protobuf message that takes an optional message of a type I created. However, the optional message type is just a wrapper of nested types. The goal was to be able to specify a thing generically by saying that it's simply something of a Type and not a RedType or GreenType. Polymorphism.

I've messed with all of this to make it concise and easier to read.

```protobuf
package interfaces;

message Wrapper {
    optional Type data = 1;
}

message Type {
    message RedType {
        required int64 id;
        required string red_type_property;
    }

    message GreenType {
        required int64 id;
        required string green_type_property;
    }
}
```

The issue is, when I go to work with this in Go:

```go
mydata := &interfaces.Type_RedType{
    Id: 20,
    RedTypeProperty: "propval",
}

mywrapper := &interfaces.Wrapper{
    Data: mydata,
}
```

Not surprisingly, you can't use something that is a `Type_RedType` in place of a more general `Type` when setting the struct value of `Data`.

```
cannot use mydata (type *interfaces.Type_RedType) as type *interfaces.Type in field value
```

Is there a language feature of Go I can use here? I tried a type conversion from `RedType` to `Type` without expecting much and it didn't work. Am I misusing this library? Or is this a terrible idea to begin with, which is what has landed me here?

Any & all help appreciated. Hopefully this is an easy one to answer.

**Comment by dsymonds** [comment]
Protocol buffers do not have polymorphism at all. Try composing rather than inheriting.

**Comment by logrusorgru** [comment]
Will provide type Any from Proto3 this functionality? Or is it better not to deceive their hopes? Currently I use a reflection and an intermediate type like here ([ref.](https://github.com/google/protobuf/issues/198))
```proto
message Any {
  string type_url = 1;
  bytes value = 2;
}

message MyIntermediateType {
    // some fields
    string field = 1;
    // interface{}
    Any any = 2;
}
```
...And unmarshal it, then detect type of `any`, unmarshal `any` and build new struct.
There is an [example application](https://github.com/logrusorgru/gopb3any).
