### ISSUE TITLE
protobuf3 support for "Any"

### ISSUE THREAD

**Issue by grepory** [golang/protobuf#60]
Is there an idiomatic way to support Any's in messages in Go? I have been struggling with reflect for a couple of days, and I think if I'm having this much trouble, I must be doing it wrong.

**Comment by grepory** [comment]
An example:

from a .proto:

```
type TestCheckRequest struct {
	MaxHosts  int32      `protobuf:"varint,1,opt,name=max_hosts" json:"max_hosts,omitempty"`
	Deadline  *Timestamp `protobuf:"bytes,2,opt,name=deadline" json:"deadline,omitempty"`
	CheckSpec *Any       `protobuf:"bytes,3,opt,name=check_spec" json:"check_spec,omitempty"`
}

type HttpCheck struct {
	Name     string    `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Path     string    `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Protocol string    `protobuf:"bytes,3,opt,name=protocol" json:"protocol,omitempty"`
	Port     int32     `protobuf:"varint,4,opt,name=port" json:"port,omitempty"`
	Verb     string    `protobuf:"bytes,5,opt,name=verb" json:"verb,omitempty"`
	Target   *Target   `protobuf:"bytes,6,opt,name=target" json:"target,omitempty"`
	Headers  []*Header `protobuf:"bytes,7,rep,name=headers" json:"headers,omitempty"`
	Body     string    `protobuf:"bytes,8,opt,name=body" json:"body,omitempty"`
}
```

I would put an HttpCheck object in the CheckSpec field on a TestCheckRequest message.

Unmarshaling this has proven difficult.

**Comment by chai2010** [comment]
You can use `google/protobuf/any.proto`:
https://github.com/chai2010/notepadplus-protobuf/blob/master/testdata/googleapis/google/protobuf/any.proto

**Comment by grepory** [comment]
Yeah. I'm just not going to use Any.

**Comment by grepory** [comment]
I figured it out, for posterity's sake:

We're going with a combination of a type switch and:

```
var (
	logger   = logging.GetLogger("checker")
	registry = make(map[string]reflect.Type)
)

func init() {
	registry["HttpCheck"] = reflect.TypeOf(HttpCheck{})
}

func UnmarshalAny(any *Any) (interface{}, error) {
	class := any.TypeUrl
	bytes := any.Value

	instance := reflect.New(registry[class]).Interface()
	err := proto.Unmarshal(bytes, instance.(proto.Message))
	if err != nil {
		return nil, err
	}
	logger.Debug("instance: %v", instance)

	return instance, nil
}
```

This could be made more elegant, but it works for now.

**Comment by jmhodges** [comment]
For folks like me coming to this from gooling around, there's now helper functions at [ptypes.MarshalAny](https://godoc.org/github.com/golang/protobuf/ptypes#MarshalAny) and [ptypes.UnmarshalAny](https://godoc.org/github.com/golang/protobuf/ptypes#UnmarshalAny)
