### ISSUE TITLE
no XXX_* fields in oneof generated structs

### ISSUE THREAD

**Issue by minaevmike** [golang/protobuf#606]
I have a simple proto message
```
message BucketKey {
     string key = 1;
}

message ObjectId {
     string id = 1;
}

message Request {
    oneof path {
        BucketKey bucket_key = 2;
        ObjectId object_id = 3;
    }
    string version = 4;
}

```
So proto gen go generate some routine code where path is interface with implementations in `Request_BucketKey` and `Request_ObjectId`. But this structs(`Request_BucketKey` and `Request_ObjectId`) doesn't have `XXX_NoUnkeyedLiteral` `XXX_unrecognized` `XXX_sizecache`, which were introduced in laster protobuf release. Is it a bug, or it's ok?

**Comment by dsnet** [comment]
It should have these XXX fields. Have you tried updating `protoc-gen-go`?

You can do so with:
```go get -u github.com/golang/protobuf/protoc-gen-go```

**Comment by minaevmike** [comment]
i have master of protoc-gen-go

**Comment by dsnet** [comment]
Ah, my mistake, I misread. The wrapper structs for oneofs do not have any XXX fields. They exist as a type safe way to work around the lack of union types in Go.

**Comment by minaevmike** [comment]
ok, thank you.
