### ISSUE TITLE
Feature request: A new file option 'go_import_path'

### ISSUE THREAD

**Issue by ceram1** [golang/protobuf#61]
I use ```-I$GOPATH/src``` to include protos, but it's path does not match somtimes.
As golang does not work in simillar way with other langauges, an extra option is required.

Example usecase:
golang package: [appcore-project/cdt-go/country](https://github.com/appcore-project/cdt-go/tree/98dabfd349fb3e84ca581985f80bff178c0f86a8/country)
protobuf: [appcore-project/protos/appcore/cdt/country/country.proto](https://github.com/appcore-project/protos/blob/aa863f53e672c1dd479d833fe0d21c2e6a3fedbe/appcore/cdt/country/country.proto)

**Comment by jerrodrurik** [comment]
Closed, as prefix is enough for my usecase.

**Comment by ceram1** [comment]
Closed, as prefix is enough for my usecase.
