### ISSUE TITLE
jsonpb: "oneof" does not validate overlapping keys

### ISSUE THREAD

**Issue by atombender** [golang/protobuf#618]
Consider a message such as this:

```
message Change {
  oneof Change {
    Create create = 1;
    Update update = 1;
    Delete delete = 2;
  }
}
```

If a client passes this:

```json
{
  "change": {
    "create": {"id": "123", "title": "foo"},
    "update": {"id": "123", "title": "bar"}
  }
}
```

then the choice is random. The relevant logic in `jsonpb.go` simply iterates over all `oneof` properties and consumes all of them. The last property wins, but since JSON keys is unordered according to spec, which property wins is random.

For the above fictional API, an inattentive developer might expect the result of the update to set `title` to `bar`, and it might even work occasionally, but generally this will result in confusing results.

`jsonpb.go` has an option `AllowUnknownFields` to reject unknown fields. But _unconsumed_ data is an equally important error case that should be validated, since the client will not be aware that part of the data has been silently ignored.

I can submit a PR if there's consensus.

**Comment by dsnet** [comment]
The specification says:
> For fields in one oneof, only the field that is set will be serialized in JSON. When parsing, *if multiple fields in a same oneof exist in the JSON input, parsing should fail.*

So the behavior you are describing is indeed a bug. PR welcome, thank you.

**Comment by puellanivis** [comment]
The `OneofProperties` should contain a `Field` field that contains the golang field index to which the specific field is assignable. Each separate Oneof should be assigned to a different internal field, and all protobuf fields that assign to the same oneof, should be assigned to the same internal field.

So it should be the case that both of these are true: `prop.OneofTypes["a"].Field == prop.OneofTypes["b"].Field` and `prop.OneofTypes["a"].Field != prop.OneofTypes["c"].Field`.

**Comment by dsnet** [comment]
The new [`protojson`](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson) package addresses this issue and has been released as part of [`google.golang.org/protobuf@v1.20.0`](https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.20.0).
