### ISSUE TITLE
Custom Option when building an rpc

### ISSUE THREAD

**Issue by FreekingDean** [golang/protobuf#620]
Hi all! Im trying to write an RPC generator (similar to twirp). I have some custom options set on a service & method to signify their descriptive names & their ID's IE: Service A has an ID of 1.

I'm currently extending service options & using my own custom option, but I can't seem to figure out how to pull that info out from the ServiceOptions https://godoc.org/github.com/golang/protobuf/protoc-gen-go/descriptor#ServiceOptions
What is the best way to do this?

Also I'd ask in some IRC, but I didn't see one, sorry if this is the wrong place!

**Comment by meling** [comment]
Here is an example of how we define method options; I assume service options are similar:
[gorums.proto](https://github.com/relab/gorums/blob/master/gorums.proto)
(PS: you need to generate the corresponding `.pb.go` file; see the Makefile):

Here is how we use it for testing:
[storage.proto](https://github.com/relab/gorums/blob/master/dev/storage.proto)

The plugin/compiler is (partially) here:
[ext.go](https://github.com/relab/gorums/blob/master/plugins/gorums/ext.go)
[gorums.go](https://github.com/relab/gorums/blob/master/plugins/gorums/gorums.go#L282)

I think these are most of the relevant files. Let me know if this helps or you need more information.

**Comment by FreekingDean** [comment]
Oh! TIL about gogo/protobuf :)

This is super helpful, thank you :)

**Comment by dsnet** [comment]
It seems that there is not really anything for us to do here. Let me know if I'm assessing this incorrectly.
