### ISSUE TITLE
proto: implementation of (*Test).GetReps is missing from the package documentation

### ISSUE THREAD

**Issue by musiphil** [golang/protobuf#626]
The package documentation (in proto/lib.go) contains am example called `test.proto` and the resulting file `test.pb.go`. `(*Test).GetReps` is missing from the latter file, though it has the implementation of the corresponding `GetXXX` methods for all the other fields in the message `Test`.
```
$ grep -F 'func (m *Test) Get' lib.go
	func (m *Test) GetUnion() isTest_Union {
	func (m *Test) GetLabel() string {
	func (m *Test) GetType() int32 {
	func (m *Test) GetOptionalgroup() *Test_OptionalGroup {
	func (m *Test) GetNumber() int32 {
	func (m *Test) GetName() string {
```

**Comment by dsnet** [comment]
The package documentation on `proto` has been re-written. This is no longer relevant.
