### ISSUE TITLE
protoc-gen-go is in my shell path but protoc cant find it

### ISSUE THREAD

**Issue by kksharma1618** [golang/protobuf#629]
Hey,

I am using ubuntu bionic. Just started with protobuf.

protoc is in path (version 3.5.1)
protoc-gen-go is in path (~/go/bin. and its in my path)

I am getting this error though while generating go
```
protoc-gen-go: program not found or is not executable
--go_out: protoc-gen-go: Plugin failed with status code 1.
```

Info
```
$ which protoc-gen-go
$ type protoc-gen-go
protoc-gen-go is /home/krishna/go/bin/protoc-gen-go
$ protoc-gen-go
^C
$ protoc -I helloworld/ helloworld/helloworld.proto --go_out=plugins=grpc:helloworld
protoc-gen-go: program not found or is not executable
--go_out: protoc-gen-go: Plugin failed with status code 1.
$ protoc -I helloworld/ helloworld/helloworld.proto --go_out=plugins=helloworld
protoc-gen-go: program not found or is not executable
--go_out: protoc-gen-go: Plugin failed with status code 1.
$ protoc --version
libprotoc 3.5.1
```
Not sure what I am doing wrong.

**Comment by kksharma1618** [comment]
My apologies. 
I downloaded the zip from https://github.com/google/protobuf/releases for linux and copied zip/bin/protoc to my path, but failed to copy zip/include to /usr/local/include. Copying the include folder fixed the issue.

Closing it.

**Comment by coolseven** [comment]
> My apologies.
> I downloaded the zip from https://github.com/google/protobuf/releases for linux and copied zip/bin/protoc to my path, but failed to copy zip/include to /usr/local/include. Copying the include folder fixed the issue.
> 
> Closing it.

Hi, I went into the exact same problem today , but when i unzipped the release file, I did not find any file or folder named 'include' or 'zip' in it, did I mis-understand something ? thank you .

**Comment by siasalar** [comment]
you could update GOPATH as well to fix this issue:

export PATH=$PATH:$HOME/go/bin, in order to add the GOPATH and
export PATH=$PATH:/usr/local/go/bin, in order to add GOROOT
