### ISSUE TITLE
Map of string 2 enum jsonpb

### ISSUE THREAD

**Issue by jeb2239** [golang/protobuf#633]
https://github.com/golang/protobuf/blob/05f48f4eaf0e05663b562bab533cdd472238ce29/jsonpb/jsonpb_test.go#L389

Is there away to do `map<string , repeated MyEnum> mp` Or some how fake this behavior using ListValue?

**Comment by cybrcodr** [comment]
Your question is not the same as the commented out test entry.  Your question is particular to defining a map in proto.  You can't specify a map value to be repeated, but you can have a message that contains repeated field(s).

message A {
   map<string, B> m = 1;
}

enum Enum {
    X = 0;
    Y = 1;
}

message B {
    repeated Enum = 1;
}
