### ISSUE TITLE
README.md: markdown format issues

### ISSUE THREAD

**Issue by unlikezy** [golang/protobuf#635]
https://github.com/golang/protobuf/blob/master/README.md#writes-githubcomgolangprotobufpxpbgo
The '#' before these two lines make them as titles, which may be confused when reading.
![image](https://user-images.githubusercontent.com/3445204/41266583-22b0064a-6e2a-11e8-805d-be5b8005d4d4.png)

**Comment by Aaronong** [comment]
@dsnet  Please do help to review and merge. :) 

![image](https://user-images.githubusercontent.com/11691740/42525286-5788a43a-84a5-11e8-845b-3df62f06bde2.png)
