### ISSUE TITLE
【Question】How to deal with proto denpdency in big repo?Copy or reference?

### ISSUE THREAD

**Issue by longXboy** [golang/protobuf#638]
Our team uses a big mono repo like google. All microservices are a separate folder and placed in the same repo. The following shows the directory structure of one of our microservices:
service/main/identify
├── cmd
├── conf
├── dao
├── http
├── model
├── proto<here is *.proto and *.pb.go>
├── rpc
│   ├── client
│   └── server
└── service

Previously we used HTTP communication. Now we plan to migrate to grpc, but we don't know how to store proto files in each microservices. Now we think of two options:
1, copy
Manage the proto file by copying. If service A depends on service B, then service A needs to copy all proto files of service B into their own directory and generate the code. There is no direct interdependence between each service. A little copying is better than a little dependency.
2, dependent
Each project exposes its own proto folder, relies on the proto folder, and manages permissions and builds through Bazel, but this greatly reduces Bazel's build speed when there are too many
proto dependencies.
So if it is yours, how will you choose? Or any other suggestions？

**Comment by cybrcodr** [comment]
Given that you have a mono repo, I would avoid copying to ensure using the same version of protos across all services and apps.

I could be wrong on this, but if you are using Bazel, then proto-generated Go files can be produced during build time and can have corresponding import package path defined by where the rule resides.  If you do duplicate protos, then each duplicated proto may not have the same package path, which may cause problems if used on the same binary.  I'm not clear on how using duplicates/copies can improve Bazel's build speed.

You can differentiate protos that are exposed by the service vs ones that are only used within using Bazel's visibility rules.  Having a proto directory for each service sounds good, and/or have a  directory outside of the services for all commonly shared proto definitions.  Having a single source of truth for a proto definition is better.

Hope that helps.

**Comment by longXboy** [comment]
@cybrcodr thanks a lot!
