### ISSUE TITLE
proto: undefined: proto.InternalMessageInfo

### ISSUE THREAD

**Issue by sobhanthakur** [golang/protobuf#642]
I am trying to compile lora-app-server source code. Whenever i run make command after make api. i get following errors

 github.com/brocaar/lora-app-server/api
api/application.pb.go:89:46: undefined: proto.InternalMessageInfo
api/application.pb.go:170:47: undefined: proto.InternalMessageInfo
api/application.pb.go:209:43: undefined: proto.InternalMessageInfo
api/application.pb.go:262:44: undefined: proto.InternalMessageInfo
api/application.pb.go:362:46: undefined: proto.InternalMessageInfo

Any solution is welcome

**Comment by dsnet** [comment]
The `InternalMessageInfo` type was added recently, so it means that your `proto` package has not been updated. You probably need to update the package:
```
go get -u github.com/google/protobuf/proto
```

Keep in mind that vendoring directories may caused additional complications, so you'll have to check whether you're vendoring the `proto` package as well.

**Comment by soundrussian** [comment]
I'm having the same issue. Updated protoc:

```
protoc --version
libprotoc 3.6.0
```

The generated .go file won't compile:
```
store/store.pb.go:78:27: undefined: proto.InternalMessageInfo
store/store.pb.go:312:28: undefined: proto.InternalMessageInfo
store/store.pb.go:387:25: undefined: proto.InternalMessageInfo
store/store.pb.go:685:28: undefined: proto.InternalMessageInfo
store/store.pb.go:783:28: undefined: proto.InternalMessageInfo
store/store.pb.go:849:29: undefined: proto.InternalMessageInfo
store/store.pb.go:889:30: undefined: proto.InternalMessageInfo
store/store.pb.go:946:26: undefined: proto.InternalMessageInfo
store/store.pb.go:1019:27: undefined: proto.InternalMessageInfo
store/store.pb.go:1059:29: undefined: proto.InternalMessageInfo
store/store.pb.go:1059:29: too many errors
```

Updating the package doesn't help:

```
# go get -u github.com/google/proto
package github.com/google/protobuf/proto: cannot find package "github.com/google/protobuf/proto" in any of:
	/usr/local/go/src/github.com/google/protobuf/proto (from $GOROOT)
	/go/src/github.com/google/protobuf/proto (from $GOPATH)
```

**Comment by dsnet** [comment]
My mistake, it should be:
```
go get -u github.com/golang/protobuf/proto
```

**Comment by soundrussian** [comment]
Thanks, the problem was in old package in `/vendor/github.com/golang/protobuf`, just removed it, and the problem is gone

**Comment by dsnet** [comment]
Great to hear.

**Comment by YJinHai** [comment]
Hello, same problem. I have updated proto, but I still reported an error
`
proto/consignment/consignment.pb.go:61:33: undefined: proto.InternalMessageInfo
proto/consignment/consignment.pb.go:131:31: undefined:proto.InternalMessageInfo
proto/consignment/consignment.pb.go:193:30: undefined:proto.InternalMessageInfo
proto/consignment/consignment.pb.go:246:32: undefined:proto.InternalMessageInfo
`

And the strange thing is, maybe a week or two ago, there was no such thing as that, but today, please, thank you

**Comment by zuochangqin** [comment]
运行glide get github.com/golang/protobuf,将protobuf放到glide依赖里面
