### ISSUE TITLE
protoc-gen-go: confused about declaration location for simple imports

### ISSUE THREAD

**Issue by LeoAdamek** [golang/protobuf#646]
Hi,

I’m just getting started with using protobufs (for gRPC) so this might be a rookie mistake, but I'm having trouble referencing types from other packages.

As an example I've created [this gist](https://gist.github.com/LeoAdamek/330647a6fcf90acbb2f08ae93d7a67ff) which defines two pb packages.

I've built them using:

    protoc -I. --go_out=plugins=grpc:go/common common.proto
    protoc -I. --go_out=plugins=grpc:go/sample sample.proto

I’d expect to see either a reference to `common.EntityRef` in `go/sample/sample.pb.go` or a definition for `EntityRef` which matches the one in `go/common/common.pb.go` but instead there's a reference to `EntityRef` and no definition at all, so `sample.pb.go` cannot build.

What am I doing wrong when using common types?

-Leo

**Comment by dsnet** [comment]
This does look like either a bug in `protoc-gen-go` or the `grpc` plugin where it thinks that `EntityRef` is declared within the same package.

Some observations of strange behavior:
* If a proto import path is only a single file (e.g., `import "common.proto"`), the generator seems to think that the declaration of `EntityRef` is within the same Go package even though they exist in different proto packages. However, if you move the proto file to a sub-directory as `dir/common.proto`, it works as expected.

\cc @neild

**Comment by dsnet** [comment]
The logic in `protoc-gen-go` to derive the import path when lacking a `go_package` option is fundamentally problematic. It is impossible for it to derive one that works in all circumstances. We'll be moving towards a future where `go_package` is required and `protoc-gen-go` will one day complain if it is not set (with helpful guidance of course).
