### ISSUE TITLE
ptypes for money.proto

### ISSUE THREAD

**Issue by ahmetb** [golang/protobuf#647]
Hi, I'm writing a utility package (similar to [ptypes](https://godoc.org/github.com/golang/protobuf/ptypes)) for `money.proto` at https://github.com/googleapis/googleapis/blob/master/google/type/money.proto (Go package for this is at https://godoc.org/google.golang.org/genproto/googleapis/type/money)

I'm not sure where should this go. I assume since it's part of `googleapis/googleapis` and not `google/protobuf` (like [timestamp.proto](https://github.com/google/protobuf/blob/master/src/google/protobuf/timestamp.proto)), it does not belong to ./ptypes here.

Where should this go? To its own repository?

**Comment by dsnet** [comment]
The `golang/protobuf` repo is only concerned about proto messages defined within the "google.protobuf" proto package. Any other "common" protos should be handled elsewhere like the cloud repos.

That said some of the "google.protobuf" protos are currently generated in `genproto`, which is confusing for users.

**Comment by ahmetb** [comment]
@dsnet thanks, I'm applying for a `google/go-pbmoney` repo. Let me know if it's a bad idea/name.

**Comment by jba** [comment]
That repo name seems a bit narrow. There are many well-known types in googleapis, and maybe more than just money deserves a utility package.

**Comment by dsnet** [comment]
Closing this issue as it is unrelated to golang/protobuf.

**Comment by ahmetb** [comment]
For the record, the library is now available at https://github.com/google/go-pbmoney .
