### ISSUE TITLE
deterministic marshaling for non regenerated code

### ISSUE THREAD

**Issue by awalterschulze** [golang/protobuf#648]
It seems that the Marshal method is called when deterministic is true or false.
https://github.com/golang/protobuf/blob/master/proto/table_marshal.go#L227-L232

This might be a non deterministic generated Marshal method in a library used by a user pulling in the newer version of golang/protobuf, where they are able to set deterministic to true.

Even if we modify this code to rather be

```go
if u.hasmarshaler && !deterministic {
		...
}
```

We also have to worry about
https://github.com/golang/protobuf/blob/master/proto/table_marshal.go#L310-L314
Which means that if there is a Marshaler the size cache is not set, but the non generated marshal function assumes that it is set.

How do we solve this?

**Comment by dsnet** [comment]
The unfortunate reality is that we can't reconcile this issue in the present API. If deterministic marshaling is enabled, it will just have to be a best effort as it is impossible to know whether custom implementations are deterministic or not.

The design of the [`protoiface` API](https://docs.google.com/document/d/19kfhro7-CnBdFqFk7l4_HmwaH2JT_Rhw5-2FLWLEGGk/edit#heading=h.o9txp09ylzju) is intended to enable to safer way for custom implementations to coexist.

**Comment by awalterschulze** [comment]
@dsnet ^^ ?

**Comment by dsnet** [comment]
Strict erroring for custom unmarshalers sounds good to me. Would you like to submit a PR?

**Comment by awalterschulze** [comment]
That is great to hear :)

Just checking you mean marshalers and not unmarshalers, right?

**Comment by dsnet** [comment]
Correct.

**Comment by awalterschulze** [comment]
@jmarais is working on a pull request.

Thank you so much :)
