### ISSUE TITLE
jsonpb: Cannot unmarshal string into float or double

### ISSUE THREAD

**Issue by kyleconroy** [golang/protobuf#649]
With the following protocol buffer file

```
syntax = "proto3";
package example
option go_package = "example"

message Foo {
  float bar = 1;
}
```

I would expect this test to pass.

```
package twitter

import (
	"strings"
	"testing"

	"github.com/golang/protobuf/jsonpb"
	"github.com/kyleconroy/example"
)

const foo = `
{"bar": "1.0"}
`

func TestLoadFloat(t *testing.T) {
	m := jsonpb.Unmarshaler{}
	f := example.Foo{}
	if err := m.Unmarshal(strings.NewReader(foo), &f); err != nil {
		t.Fatal(err)
	}
}
```

It does not

```
--- FAIL: TestLoadFlaot (0.00s)
	foo_test.go:26: json: cannot unmarshal string into Go value of type float32
```

The [language guide](https://developers.google.com/protocol-buffers/docs/proto3#json) suggests that floats and doubles should be supported as strings.

> JSON value will be a number or one of the special string values "NaN", "Infinity", and "-Infinity". **Either numbers or strings are accepted**. Exponent notation is also accepted.

**Comment by jhump** [comment]
@kyleconroy, are you sure you have the latest version of the repo checked out? I am pretty sure this issue was recently addressed: https://github.com/golang/protobuf/pull/630

**Comment by kyleconroy** [comment]
That was the problem, as I was using v1.10. When can we expect another release?
