### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by sbuss** [golang/protobuf#659]
The 1.1.0 release contains a commit (#499) which was reverted (#628). Please create a new release which has the roll back.

Thanks!

**Comment by dsnet** [comment]
#660 will need to land before a new release can be cut.

**Comment by dsnet** [comment]
Just an update. I've been chasing down some failures that have been affecting a small number of targets. I want to understand what's going on before making a release.

**Comment by dsnet** [comment]
Done. https://github.com/golang/protobuf/releases/tag/v1.2.0
