### ISSUE TITLE
Support tag numbers as field names in generated JSON

### ISSUE THREAD

**Issue by tiziano88** [golang/protobuf#66]
Currently the current

```proto
message Foo {
  int32 bar = 2;
}
```

is serialized to JSON like

```json
{
  "bar": 111
}
```

but other proto libraries (e.g. [Dart](https://github.com/dart-lang/dart-protobuf/blob/master/lib/src/protobuf/generated_message.dart#L555)) use tag numbers as field names instead:

```json
{
  "2": 111
}
```

If desirable, it should be easy enough to add a new option to the JSONPB [Marshaller](https://github.com/golang/protobuf/blob/master/jsonpb/jsonpb.go#L61) (e.g. `NumericTags`) to enable this behaviour. I think decoding should be possible from both formats even without knowing in advance which one was used (although I have not verified this).

If this is something that could be considered, I am happy to prepare a PR.

**Comment by dsymonds** [comment]
No, that's not part of the JSON spec for protocol buffers (https://developers.google.com/protocol-buffers/docs/proto3#json).
