### ISSUE TITLE
protoc-gen-go: include standalone comments in generated code

### ISSUE THREAD

**Issue by ronny** [golang/protobuf#666]
Cross-posted from https://github.com/google/protobuf/issues/4983 - filing here as well as per suggested.

**Describe the problem you are trying to solve.**

I'm trying to pass information (in the form of standalone comment block at the top of the proto file) to our build tooling where it only has access to the generated files but not the source proto files.

**Describe the solution you'd like**

Include standalone leading comments at the top of the proto file in the generated pb.go. files.

**Describe alternatives you've considered**

I worked around this limitation by attaching comments to various definitions (message, service, etc) to get them included in the generated files.

**Comment by natdm** [comment]
Do you mean adding things like `//go:generate` at the top of the proto file should be carried over to the generated file? I 100% agree. 

The other thing that's missing is passing comments on from fields.

```
message T {
    string id = 1; // validate:gt=5
}
```

Should be able to generate
```
type T struct {
    ID string // validate:gt=5
}
```

Right now that comment gets dropped. Really kills code generation.

**Comment by pthornton** [comment]
This would also be very useful for structs that are mapped to json/yaml.

```
type Network struct {
	Members []string `yaml:"members,omitempty"`
	Type string `yaml:"type,omitempty"`
	Gateway string `yaml:"gateway,omitempty"`
}
```

**Comment by siawyoung** [comment]
This would be useful for `godoc` as well, when reading documentation for generated files.

**Comment by dsnet** [comment]
In the [v1.20.0 release](https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.20.0), a larger degree of standalone comments are now preserved in the generated code.
