### ISSUE TITLE
protos importing another protos in different packages not working

### ISSUE THREAD

**Issue by degaglani** [golang/protobuf#672]
Example:
src/test/foo/a.proto:
`package foo;
message t1{
    string a = 1;
}`

src/test/bar/b.proto:
`package bar;
import "foo/a.proto";
message t2{
   string b = 1;
   foo.t1 test = 2;
}`

executing these commands in src/test folder:
protoc --go_out=. foo/a.proto
protoc --go_out=. bar/b.proto

While compiling b.proto, throws error:
Import "foo/a.proto" was not found or had errors

**Comment by neild** [comment]
You're missing a `-I.`; the proto compiler doesn't add the current directory to the import path by default.

**Comment by degaglani** [comment]
Tried -I. as well.  Same issue

**Comment by neild** [comment]
```
cd src/test
protoc -I. --go_out=. bar/b.proto
```
