### ISSUE TITLE
go get github.com/golang/protobuf fail with lpackage github.com/golang/protobuf: no Go files

### ISSUE THREAD

**Issue by tuhaolam** [golang/protobuf#676]
lpackage github.com/golang/protobuf: no Go files in xxx

**Comment by dsnet** [comment]
Hi, can you try:
```
go get -u github.com/golang/protobuf/proto
```
instead?

**Comment by dsnet** [comment]
Closing, as we try to the issue tracker about actionable items. Let me know if you're still running into an  issue.

**Comment by josvegit** [comment]
both go get -u github.com/golang/protobuf and go get github.com/golang/protobuf gives the exact same problem, "no go files in $GOPATH/src/github.com/golang/protobuf"

**Comment by josvegit** [comment]
$GOPATH/src/github.com/golang/protobuf

![image](https://user-images.githubusercontent.com/24354568/81378638-e5894a80-9107-11ea-8767-b3cfca732fb1.png)

**Comment by neild** [comment]
`github.com/golang/protobuf` is not a package, and contains no `.go` files. As Joe said above, you probably want

```
go get -u github.com/golang/protobuf/proto
```

instead.

**Comment by josvegit** [comment]
my bad, thanks
