### ISSUE TITLE
Better struct representation

### ISSUE THREAD

**Issue by kyessenov** [golang/protobuf#686]
**Is your feature request related to a problem? Please describe.**
We have a big proto that has many nested structs in it:
```proto
message X {
  google.protobuf.Struct y = 1; // This should be message Y
}
message Y {
  google.protobuf.Struct z = 1; // This should be message Z
}
message Z {
...
}
```

Using the generated code, to create an instance of `X` we have to marshal instances of Y and Z to JSON to get back a struct (round-tripping through JSON seems to be the only way to get a struct from a proto). That means deeply-nested messages are serialized many times over.

**Describe the solution you'd like**
What we want instead is to use some wrapper of `proto.Message` instead of `types.Struct` for the value of the struct field. Then the serializer can serialize message as a struct when necessary, and that would happen only once.

**Describe alternatives you've considered**
An extension to gogo was filed here: https://github.com/gogo/protobuf/issues/458

**Additional context**
The original problem arises from the use of https://github.com/envoyproxy/data-plane-api

**Comment by kyessenov** [comment]
Maybe I'm thinking out loud and this is far out there, but something like below would make it less clunky:
```go
type X {
  y proto.Message;
}

func test() *X {
   return &X{y: &Y{z: &Z{}}}
}
```

Compare this to using something like [MessageToStruct](https://github.com/envoyproxy/go-control-plane/blob/master/pkg/util/struct.go#L30):
```go
func test() *X {
   return &X{
    y: MessageToStruct(&Y{
      z: MessageToStruct(&Z{}),
    })}
}
```

**Comment by kyessenov** [comment]
Let me put it another way. Currently, if a proto has a struct field, then its content is "frozen" in a struct state. This is correct from proto semantics, but makes it hard to operate on fields of this proto. For proto-producer heavy code, there is also significant performance cost, since struct need to be converted repeatedly. It's difficult to share internal structs-within-structs, unless top-level structs are manually crafted.

My suggestion is to optimize for the proto-producer oriented code when desired. Every proto can be converted to a struct, so the proto library can take of serializing to messages to structs internally.

**Comment by dsnet** [comment]
To my knowledge, no other language special-cases the generated code of Struct in this way. The `golang/protobuf` project is intended to be a faithful implementation of protocol buffers without inventing its own new semantics. As such we won't be making this change.
