### ISSUE TITLE
APIv2: encoding/textpb: unmarshaler allows duplicate extensions

### ISSUE THREAD

**Issue by dsnet** [golang/protobuf#687]
Parsing the following into [MyMessage](https://github.com/golang/protobuf/blob/b27b920f9e71b439b873b17bf99f56467623814a/proto/test_proto/test.proto#L263-L290):
```
[test_proto.Ext.text] = "hello"
[test_proto.Ext.text] = "hello"
```
does not result in an error even though the extension is specified twice.

For defined fields, it [does complain about duplicate fields](https://github.com/golang/protobuf/blob/b27b920f9e71b439b873b17bf99f56467623814a/proto/text_parser.go#L659-L662), and it should does so as well for extensions.

**Comment by dsnet** [comment]
\cc @cybrcodr, does v2 text implementation fix this?

**Comment by cybrcodr** [comment]
Yes.  This is fixed in V2.  It will return an error complaining that the non-repeated field is repeated.

**Comment by dsnet** [comment]
The new [`prototext`](https://pkg.go.dev/google.golang.org/protobuf/encoding/prototext) package addresses this issue and has been released as part of [`google.golang.org/protobuf@v1.20.0`](https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.20.0).
