### ISSUE TITLE
Error - undefined: RawMessage when tring to use go get github.com/mainflux/mainflux

### ISSUE THREAD

**Issue by srados** [golang/protobuf#688]
In case when mainflux is used as a library
`go get github.com/mainflux/mainflux` fails with the message undefined: RawMessage

Rason for this are missing `protoc` generated files.
I think those files should either be generated during the build process or added to the repo.

More info on `protoc` generation in question can be found here https://mainflux.readthedocs.io/en/latest/dev-guide/

**Comment by anovakovic01** [comment]
We should add generated files to repo, so just remove it from `.gitignore` and commit them.

**Comment by srados** [comment]
sorry, wrong repo
