### ISSUE TITLE
proto: incorrect size of encoded repeated fields

### ISSUE THREAD

**Issue by gudvinr** [golang/protobuf#689]
**What version of protobuf and what language are you using?**
Version: b27b920

**What did you do?**
Unfortunately I can't provide code to reproduce behavior because it's statistically hard to catch an error.

I have such message structure:
```proto
message MsgKey {
	required uint32 key_1 = 1;
	required uint32 key_2 = 2;
}

message SomeOtherInfo {
	required uint32 id    = 1;
	repeated int64 arr_1  = 2 [packed = true];
	repeated uint32 arr_2 = 3 [packed = true];
}

message Payload {
	required sint32 val_1 = 1;
	optional sint32 val_2 = 2 [default = 0];
	optional uint32 id    = 3;
}

message Info {
	message SubMsg {
		required MsgKey key         = 1;
		repeated SomeOtherInfo info = 2;
	}

	required uint64 id       = 1;
	repeated Payload payload = 2;
	repeated SubMsg msgs     = 3;
}

message RootMessage {
	repeated Info info = 1;
};
```

And **sometimes** I'm getting incorrectly marshaled `RootMessage` in a way that it _seems_ to be packed correctly but puts wrong size to its header.

Example of payload that encoded wrong:
```
0A750805120408001801120508D0031802120508C8011803120508D0031804120408321805120408281806120408781807120408001808120508D00518091204084E180A1204083A180B12040840180C12040800180D12040800180E12040800180F120508C8011810120408541811120408001812
```

As you can see from the header its body lenght is `0x75` (or 117) but if you try to feed that message to `protoc --decode_raw` without schema you'll get an error:
```
$ echo -ne '<hex_message_content>' | xxd -r -p - | protoc --decode_raw
Failed to parse input.
```

But when I change length in header manually to `0x73` (115 which is correct size) it becomes readable:
<details><summary><b>Click to expand</b></summary>
<p>

```
1 {
  1: 5
  2 {
    1: 0
    3: 1
  }
  2 {
    1: 464
    3: 2
  }
  2 {
    1: 200
    3: 3
  }
  2 {
    1: 464
    3: 4
  }
  2 {
    1: 50
    3: 5
  }
  2 {
    1: 40
    3: 6
  }
  2 {
    1: 120
    3: 7
  }
  2 {
    1: 0
    3: 8
  }
  2 {
    1: 720
    3: 9
  }
  2 {
    1: 78
    3: 10
  }
  2 {
    1: 58
    3: 11
  }
  2 {
    1: 64
    3: 12
  }
  2 {
    1: 0
    3: 13
  }
  2 {
    1: 0
    3: 14
  }
  2 {
    1: 0
    3: 15
  }
  2 {
    1: 200
    3: 16
  }
  2 {
    1: 84
    3: 17
  }
  2 {
    1: 0
    3: 18
  }
}
```
</p></details>

And there's an example of data of same message that encoded correctly:
```
0A730801120408001801120508D0031802120508C8011803120508D0031804120408001805120408001806120408781807120408001808120508D00518091204084E180A1204083A180B12040840180C12040800180D12040800180E12040800180F120508C8011810120408001811120408001812
```

**Comment by gudvinr** [comment]
Yep. You were right.
Tried to investigate race conditions and found a place where protobuf works in thread-unsafe manner.

**Comment by puellanivis** [comment]
Wait, is it _protobuf_ working in the thread-unsafe manner, or your code working in the thread-unsafe manner?

If the race-condition is in protobuf, rather than just closing this issue, we should at the very least know and document when it can occur, or even better, figure out a resolution so that it is thread-safe.

**Comment by gudvinr** [comment]
@puellanivis no, this is not a protobuf issue. Sorry for mistake.
AFAIK protobuf encoder doesn't use any synchronization between goroutines so this is what user should handle by himself.

And in my particular case I call encoding procedure and another one that modifies data at the same time. Classic example of race condition. But it was tricky to find so I ran an app with race detector as @dsnet suggested.
