### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by onlyjob** [golang/protobuf#69]
Please consider assigning version numbers and tagging releases. Tags/releases
are quite useful for downstream package maintainers (in [Debian](http://debian.org) and other distributions) to export source tarballs, automatically track new releases and to declare dependencies between packages. Read more in the [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

Thank you.

**Comment by dsymonds** [comment]
We don't make releases. We generally keep any particular revision of this repo functional, but other packages using this repo as a dependency should vendor it if its stability is critical. We only occasionally make breaking changes.

**Comment by onlyjob** [comment]
Having formal releases is a good practice and you can tag new releases only significant amount of changes is accumulated. It would be helpful if you make releases once in a while so I hope you might think more about it and also check release policies of other popular projects. Thanks.
