### ISSUE TITLE
proto: TextMarshaler emits invalid text when expanding Any with bad type_url

### ISSUE THREAD

**Issue by agoode** [golang/protobuf#690]
**What version of protobuf and what language are you using?**
Version: b27b920f9e71b439b873b17bf99f56467623814a

**What did you do?**
```
package main

import (
	"fmt"
	"log"

	"github.com/golang/protobuf/proto"
	"github.com/golang/protobuf/ptypes"
	"github.com/golang/protobuf/ptypes/empty"
)

func main() {
	a, err := ptypes.MarshalAny(&empty.Empty{})
	if err != nil {
		log.Fatalf("MarshalAny: %v", err)
	}
	a.TypeUrl, err = ptypes.AnyMessageName(a) // Return TypeUrl part after "/"
	if err != nil {
		log.Fatalf("AnyMessageName: %v", err)
	}
	tm := proto.TextMarshaler{ExpandAny: true}
	s := tm.Text(a)
	fmt.Print(s)
	if err := proto.UnmarshalText(s, a); err != nil {
		log.Fatalf("UnmarshalText: %v", err)
	}
}
```

**What did you expect to see?**
no error, but transparent round trip.

**What did you see instead?**
2018/08/24 13:25:23 UnmarshalText: line 1.22: unrecognized extension "google.protobuf.Empty"

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment?**

This does not match the C++ implementation, which falls back to not expanding an invalid Any message.

**Comment by dsnet** [comment]
There are other aspects of the text format where Go and C++ diverges in behavior especially in relation to the Any type. In the past, I have been told by the protobuf team that inter-operation between languages via the text format is not an explicit goal. That said, Go should diverge unnecessarily.

Strictly speaking "my.proto.package.My.Message.Type" is a valid URL according to RFC 3986. It's just that it is a URL with only a path segment. More specifically, a path segment that happens to be exactly the fully qualified name of a protobuf declaration.

The disadvantage of the C++ fallback is a loss in readable output. It means that Any messages are not serialized to the output in text form, but rather as an escaped strings with the binary serialization.

I wonder if a better approach is to actually allow `[google.protobuf.Empty]` when unmarshaling Any. From a protobuf type system perspective, there is no ambiguity. If a message type name is "google.protobuf.Empty", then it implies that there cannot possibly be an extension also named "google.protobuf.Empty". Similarly, an extension of some given name implies that there cannot possibly be a message type with the same name.

**Comment by agoode** [comment]
Nowhere in the [Any docs](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Any) does it say that `type_url` must contain a `/`, but this is assumed strictly by C++ and Go in many cases. This is probably a mistake in the documentation of Any.

In Go, `type_url` is already required to have a slash in `AnyMessageName()`, `Is()`, and `UnmarshalAny()`:
https://github.com/golang/protobuf/blob/master/ptypes/any.go

If you are sure there is no ambiguity with allowing slashless Any text unmarshaling, I would love to have this feature! I am currently trying to parse years of textproto files that have been written with expanded slashless Any.

But even if we improve `UnmarshalText()` in Go, I think changing the output to avoid unpacking slashless Any is important since no current parser in Go, Python, or C++ can read the output currently.

**Comment by dsnet** [comment]
The new [`prototext`](https://pkg.go.dev/google.golang.org/protobuf/encoding/prototext) package addresses this issue and has been released as part of [`google.golang.org/protobuf@v1.20.0`](https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.20.0).
