### ISSUE TITLE
Custom options not working when options are imported from another proto file

### ISSUE THREAD

**Issue by yogeshpandey** [golang/protobuf#693]
**What version of protobuf and what language are you using?**
Version: (v1.2.0)

**What did you do?**
i have two proto files . **goof.proto and sampleservice.proto**.
In goof.proto I have defined some custom options. which i am trying to use in sampleservice.proto.
But generating code of sampleservice.proto is not generating custom options extension code. 

**code: goof.proto**
_syntax = "proto3";

import "google/protobuf/descriptor.proto";

extend google.protobuf.FieldOptions {
    string http_param_name = 50001;
    string http_param_type = 50002;
}

extend google.protobuf.MethodOptions {
    string http_method = 50001;
    string http_path = 50002;
    string http_accept = 50003;
    string http_content = 50004;
}_

**code : sampleservice.proto**

_syntax = "proto3";

import "goof.proto";

message UserRequest {
 string uidx = 1 [(http_param_name)= "uidx",(http_param_type)="path"];
};

message User {
 string name=1; //http:"name"
 string uidx=2;

};

service UserService {
 rpc GetUser (UserRequest) returns (User) {
    option (http_method) = "GET";
    option (http_path) = "/v1/user";
    option (http_accept) = "application/json";
    option (http_content) = "application/json";

 };
};_

**What did you expect to see?**
The custom options code should get generated. although if i copy paste the custom options definition in sampleservice.proto. It generate the custom extension code

**What did you see instead?**
No custom option code is available
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment?**

**Comment by yogeshpandey** [comment]
Not an issue.
Options can be accessed via following code
m := UserRequest{}

_, md := descriptor.ForMessage(&m)
ex, err := proto.GetExtension(md.Field[0].Options, b.E_HttpParamName) 
fmt.Printf("MyMessage.GetExtension: %+v, %+v\n", *ex.(*string), err)

**Comment by fananchong** [comment]
@yogeshpandey how i can get custom  method options

**Comment by vladg9** [comment]
@fananchong what do you mean by how you can get custom options? can you give some more context about what you are trying to do?
