### ISSUE TITLE
Cannot install package 

### ISSUE THREAD

**Issue by leduy99** [golang/protobuf#703]
When I install the protobuf through go get, I received this message:
"- go get "github.com/golang/protobuf/proto"
- package github.com/golang/protobuf/proto: /home/leduy99/Go/src/github.com/golang/protobuf exists but /home/leduy99/Go/src/github.com/golang/protobuf/.git does not - stale checkout?"
How can I fix this? Thanks a lot :smile:

**Comment by dsnet** [comment]
Hi, it seems that you already have copy the protobuf repo already downloaded into `$GOPATH/src/github.com/golang/protobuf/proto` that was not cloned from `git`? If you have no local changes, you could probably just delete `$GOPATH/src/github.com/golang/protobuf` and rerun `go get github.com/golang/protobuf/proto`.

**Comment by leduy99** [comment]
Thank you very much :D I successfully fixed it ^^

**Comment by dsnet** [comment]
Wonderful to hear!

**Comment by abhisamant7** [comment]
thanks for help @dsnet
