### ISSUE TITLE
oneof: not enough error checks

### ISSUE THREAD

**Issue by awalterschulze** [golang/protobuf#71]
This is minor, but I thought I should let you know anyway.
I think canFail should always be true.

https://github.com/golang/protobuf/blob/master/protoc-gen-go/generator/generator.go#L2051
All the 
```
b.Encode...
```
methods can return an error.

I found these using
github.com/kisielk/errcheck

These lines also require an error check
https://github.com/golang/protobuf/blob/master/protoc-gen-go/generator/generator.go#L2109
https://github.com/golang/protobuf/blob/master/protoc-gen-go/generator/generator.go#L2118

**Comment by dsymonds** [comment]
They return an `error` so the methods all fit a particular pattern, but most of them are statically known to always return a nil `error`. We deliberately avoid generating code to check those to keep the code bloat down.

**Comment by awalterschulze** [comment]
Cool :)
I settled for
```
_ = b.Encode
```
This way the errcheck tool knows that you intend to ignore the error.
