### ISSUE TITLE
newly introduced go vet errors

### ISSUE THREAD

**Issue by awalterschulze** [golang/protobuf#72]
Not that important, but everything else vets, so why not.

protobuf$ go vet ./...
jsonpb/jsonpb_test.go:296: pb.MsgWithOneof_Title composite literal uses unkeyed fields
jsonpb/jsonpb_test.go:331: pb.MsgWithOneof_Salary composite literal uses unkeyed fields
exit status 1
proto/all_test.go:1305: result of fmt.Sprintf call not used
proto/clone_test.go:238: pb.Communique_Number composite literal uses unkeyed fields
proto/clone_test.go:241: pb.Communique_Name composite literal uses unkeyed fields
proto/clone_test.go:244: pb.Communique_Number composite literal uses unkeyed fields
proto/clone_test.go:251: pb.Communique_Name composite literal uses unkeyed fields
proto/clone_test.go:254: pb.Communique_Name composite literal uses unkeyed fields
proto/equal_test.go:185: pb.Communique_Number composite literal uses unkeyed fields
proto/equal_test.go:186: pb.Communique_Number composite literal uses unkeyed fields
proto/equal_test.go:191: pb.Communique_Number composite literal uses unkeyed fields
proto/equal_test.go:197: pb.Communique_Number composite literal uses unkeyed fields
proto/equal_test.go:198: pb.Communique_Name composite literal uses unkeyed fields
proto/size_test.go:129: pb.Communique_Number composite literal uses unkeyed fields
proto/size_test.go:130: pb.Communique_Name composite literal uses unkeyed fields
proto/text_test.go:219: pb.Communique_Number composite literal uses unkeyed fields
proto/text_test.go:221: pb.Communique_Msg composite literal uses unkeyed fields
proto/text_test.go:225: pb.Communique_Msg composite literal uses unkeyed fields
exit status 1

**Comment by dsymonds** [comment]
The oneof struct wrappers are specified to only ever have one field, for reasons including so that you don't have to write out the highly redundant struct field key.

**Comment by awalterschulze** [comment]
Fair enough :)
Personally I don't think this should be part of vet anyway.
I actually think its safer to declare an instance of a struct without fieldnames, since then when you add a new field to the struct definition you can easily go and fix compile errors and fill the in the appropriate new field value for every situation.  Just like we do with function parameters :)

**Comment by dsymonds** [comment]
I guess the intent of the check is to permit the struct to evolve without breaking code (per the Go 1 compatibility guarantee), but it doesn't apply in this case.
