### ISSUE TITLE
Including a Timestamp makes Unmarshal return EOF

### ISSUE THREAD

**Issue by bohdantrotsenko** [golang/protobuf#730]
**What version of protobuf and what language are you using?**

    $ protoc --version
    libprotoc 3.6.1
    $ sha256sum `which protoc`
    caed977a6a8c0318dfa5e67b6b03205d26905916e621c8c0f456350f7b6a6e45  /usr/local/bin/protoc
    $ go version
    go version go1.11.1 linux/amd64
    $ cd go/src/github.com/golang/protobuf && git rev-parse HEAD
    ddf22928ea3c56eb4292a0adbbf5001b1e8e7d0d

**What did you do?**
I found out that unmarshalling messages that include a Timestamp *in a direct scenario* leads to EOF error.

The simplest demo is https://github.com/bohdantrotsenko/go-proto-issue

In brief, the message:

    message TimeInfo {
    	string Smth = 1;
    	google.protobuf.Timestamp Moment = 2;
    }

the code:

	res := &TimeInfo{}
	err = res.XXX_Unmarshal(serialized)
	if err != nil {
		t.Fatal(err) // <-- this fails with "unexpected EOF" unless grpc test is run first.
    }

**What did you expect to see?**
unmarshalled message

**What did you see instead?**
"unexpected EOF" error

**Anything else we should know about your project / environment?**
This was surprising, since I have a working service running for almost a year. And indeed, including a grpc setup fixes the problem. 

I found out the running a grpc setup makes further unmarshalling take a different execution path in https://github.com/golang/protobuf/blob/master/proto/table_unmarshal.go#L57 but couldn't debug the correct setup.

**Comment by dsnet** [comment]
The `XXX_Unmarshal` and `XXX_Marshal` methods are not meant to be called directly. Doing so invalidates certain assumptions it makes about the message state. Replacing those calls with `proto.Unmarshal` and `proto.Marshal` fixes the issue.

**Comment by johnknelsonintific** [comment]
I am receiving the same error even though I am using `proto.Unmarshal`. Has anyone else received this error?

**Comment by puellanivis** [comment]
We probably would need to see some code, or repro of your situation in order to help out.

**Comment by johnknelsonintific** [comment]
@puellanivis oops, false alarm of sorts, I am having trouble with `Timestamp` but the trouble is before unmarshalling - specifically with base64 encoding a serialized protobuf which includes nested `Timestamp` fields. Could be related but definitely a different issue - disregard!
