### ISSUE TITLE
proto.Size returns 0 for proto3 oneof zero values

### ISSUE THREAD

**Issue by awalterschulze** [golang/protobuf#74]
```
syntax = "proto3";

message SampleOneof {
  oneof test_oneof {
    bool Field1 = 1;
    float Field2 = 2;
}
```

If I set the Field1 to false and call proto.Size it returns 0 where it should return 2.
Basically  in properties.go the setEncAndDec method should only set enc_proto3_... and size_proto3_... when proto3 is true and oneof is false.

**Comment by dsymonds** [comment]
Actually it needs fixing elsewhere. They still need to use size_proto3_... because that's how the oneof wrapper structs are laid out.

**Comment by awalterschulze** [comment]
Thank you very much :)
