### ISSUE TITLE
proto: unmarshal json data from ios

### ISSUE THREAD

**Issue by FatChou** [golang/protobuf#744]
last question in go repo: https://github.com/golang/go/issues/28597#issue-377425091

<details><summary><code>objc class of config.pb.go</code></summary><br><pre>
@interface CoreConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field Config.Inbound with unsupported type: []*v2ray.com/core.InboundHandlerConfig

// skipped field Config.Outbound with unsupported type: []*v2ray.com/core.OutboundHandlerConfig

// skipped field Config.App with unsupported type: []*v2ray.com/core/common/serial.TypedMessage

// skipped field Config.Transport with unsupported type: *v2ray.com/core/transport.Config

// skipped field Config.Extension with unsupported type: []*v2ray.com/core/common/serial.TypedMessage

// skipped field Config.XXX_NoUnkeyedLiteral with unsupported type: struct{}

- (NSData*)xxX_unrecognized;
- (void)setXXX_unrecognized:(NSData*)v;
- (int32_t)xxX_sizecache;
- (void)setXXX_sizecache:(int32_t)v;
// skipped method Config.Descriptor with unsupported parameter or return types

// skipped method Config.GetApp with unsupported parameter or return types

// skipped method Config.GetExtension with unsupported parameter or return types

// skipped method Config.GetInbound with unsupported parameter or return types

// skipped method Config.GetOutbound with unsupported parameter or return types

// skipped method Config.GetTransport with unsupported parameter or return types

- (void)protoMessage
- (void)reset
- (NSString*)string;
- (void)xxX_DiscardUnknown;
- (NSData*)xxX_Marshal:(NSData*)b deterministic:(BOOL)deterministic error:(NSError**)error;
// skipped method Config.XXX_Merge with unsupported parameter or return types

- (long)xxX_Size;
- (BOOL)xxX_Unmarshal:(NSData*)b error:(NSError**)error;
@end
</pre></details>
<details><summary><code>I am trying another way of parsing like this:</code></summary><br><pre>
    CoreConfig *coreConfig = [[CoreConfig alloc] init];
    [coreConfig setXXX_unrecognized:jsonData];//设置配置数据
    NSLog(coreConfig.string);

    log in console like this:
15{1:"\"inbound\":[{\n\"port\":"4:496:566:441:"\"protocol\":\"socks\",\n"4:324:324:"omainOverride\":[\"tls\",\"http\"],\n\"settings\":{\n\"auth\":\"noauth\"\n}\n}]"}1:"\"outbound\":[{\n\"proto"12{13:/*unknownwiretype7*/}4:"\"shadowsocks\",\n\"settings\":{\n\"servers"4:"[{\n\"address\":\"106.14.142.155\",\n"4:324:324:324:3413:1869116517}4:"\"chacha20\",\n\"password\":\"123\",\n"4:324:324:324:/*unexpectedEOF*/13:/*unknownwiretype7*/14:/*unexpectedEOF*/4:/*unexpectedEOF*/4:566{7:561:"}]\n}\n}]\n}"1:/*unexpectedEOF*/
</pre></details>

</pre></details>
<details><summary><code>Raw json data</code></summary><br><pre>
    {
    "inbound": [{
        "port": 1080,
        "protocol": "socks",
        "domainOverride": ["tls", "http"],
        "settings": {
            "auth": "noauth"
        }
    }],
    "outbound": [{
        "protocol": "shadowsocks",
        "settings": {
            "servers": [{
                "address": "ip",
                "method": "chacha20",
                "password": "123",
                "port": 8388
            }]
        }
    }]
}

</pre></details>

What I don’t understand in console is：
1.unknown wire type 7
2.unexpected EOF
Why is there such a log situation, is it normal?

**Comment by dsnet** [comment]
The XXX fields and methods should not be interacted with directly. Doing so is certainly going to result in buggy behavior. Furthermore, the `XXX_unrecognized` field is also not supposed to hold JSON data. Thus, I'm not surprised that you're seeing errors.

As mentioned in [my last comment](https://github.com/golang/go/issues/28597#issuecomment-435964480), you'll need to use the `jsonpb` package to perform JSON marshaling and unmarshaling.
