### ISSUE TITLE
jsonpb: does not support FieldMask

### ISSUE THREAD

**Issue by nodirt** [golang/protobuf#745]
Go implementation of JSONPB does not support well-known proto type [FieldMask](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/field_mask.proto), which has [special JSON encoding](https://github.com/protocolbuffers/protobuf/blob/cd95c791497747043200755a4e45e1ead98e85b3/src/google/protobuf/field_mask.proto#L180).

**What version of protobuf and what language are you using?**
Version: ddf22928ea3c56eb4292a0adbbf5001b1e8e7d0d

**What did you do?**

```go
package main

import (
	"fmt"

	"google.golang.org/genproto/protobuf/field_mask"

	"github.com/golang/protobuf/jsonpb"
)

func main() {
	fm := &field_mask.FieldMask{Paths: []string{"a", "b"}}
	m := &jsonpb.Marshaler{}
	marshaled, _ := m.MarshalToString(fm)
	fmt.Println(marshaled)
	// expected: "a,b"
	// actual: {paths: ["a", "b"]}

	fm = &field_mask.FieldMask{}
	marshaled = "a,b"
	err := jsonpb.UnmarshalString(marshaled, fm)
	fmt.Println("error:", err)
}
```
**What did you expect to see?**

```
"a,b"
nil
```

**What did you see instead?**

```
{"paths":["a","b"]}
error: invalid character 'a' looking for beginning of value
```

**Comment by dsnet** [comment]
Thanks for filing. I marked with with "api-v2" since I rewrote the whole `jsonpb` package and the new implementation handles this.

See https://go-review.googlesource.com/c/protobuf/+/134495/1/encoding/jsonpb/known.go#94

**Comment by AlexAPB** [comment]
Can we get a status update on this? I think this may be better suited under a `bug` rather than an `enhancement` request.

**Comment by cybrcodr** [comment]
This is implemented in v2, which we're not quite ready for a release yet.  v1 will get the change when we update it to use v2 underneath.  The release may take a while though.

**Comment by AlexAPB** [comment]
Do you have any public documents discussing v2 timelines/details?

**Comment by cybrcodr** [comment]
https://github.com/golang/protobuf/issues/364#issuecomment-384123374 provides links to v2 design details.  We don't have published timelines.  You can follow updates on our repo at https://go.googlesource.com/protobuf.

**Comment by dsnet** [comment]
The new [`protojson`](import "google.golang.org/protobuf/encoding/protojson") package addresses this issue and has been released as part of [`google.golang.org/protobuf@v1.20.0`](https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.20.0). There are no plans to backport support of `FieldMask` to the older `jsonpb` implementation. Fixing it sadly breaks too many users who assume the incorrect behavior for `FieldMask`.
