### ISSUE TITLE
Why were the {M, Un}arshalJSON Methods for Enums Removed in Proto3

### ISSUE THREAD

**Issue by frankgreco** [golang/protobuf#750]
Is appears like like the `MarshalJSON` and `UnmarshalJSON` methods for enums were removed in proto3 as evidence by [this](https://github.com/gogo/protobuf/blob/e5d5b02ea0b3c4fd2a996e909ffa0f3421d6c91b/protoc-gen-gogo/generator/generator.go#L1563-L1583) code. 

What is the workaround for proto3? Currently I have to manually implement these methods.

**Comment by cybrcodr** [comment]
The code you're referencing is on the [gogo/protobuf repo](https://github.com/gogo/protobuf).  Please file an issue there instead.

**Comment by frankgreco** [comment]
my apologies

**Comment by frankgreco** [comment]
@cybrcodr It appears like the same code exists in this project:

https://github.com/golang/protobuf/blob/master/protoc-gen-go/generator/generator.go#L1422-L1432

Do you know why these were removed? The blame says this was done for proto3 but I fail to see what is proto2 specific about it.

**Comment by frankgreco** [comment]
Perhaps this is why:

Examine this function:

https://github.com/golang/protobuf/blob/8d0c54c1246661d9a51ca0ba455d22116d485eaa/proto/lib.go#L473-L498

A comment says that the old style is that enums are ints and the new style is enums are strings. Maybe at one time, it was in the proposal to have enums as string for proto3. However, in proto3, enums are still ints.

**Comment by cybrcodr** [comment]
Sorry, I'm not familiar with the history of these changes.

The [jsonpb](https://godoc.org/github.com/golang/protobuf/jsonpb) package in this repo provides the functionality for JSON marshaling and unmarshaling proto messages.

**Comment by cybrcodr** [comment]
You're right that jsonpb only supports marshaling of proto.Message.  I believe that is intended and consistent with binary marshaling.

I'm not very familiar with the database driver interfaces, but seems like one will still need to write wrapper implementations for the Scanner and Valuer interfaces for proto enums.

Btw, the Go type for proto enum has been int32.  The jsonpb.Marshaler with default options will try to marshal an enum using its corresponding enum name but will marshal out an integer value if the value is unknown.
