### ISSUE TITLE
README.md: fix install instructions when used with modules

### ISSUE THREAD

**Issue by kakulukia** [golang/protobuf#751]
**What version of protobuf and what language are you using?**
Version: none yet

**What did you do?**
I followed the installation instructions telling me to `go get -u github.com/golang/protobuf/protoc-gen-go`

**What did you expect to see?**
Something.

**What did you see instead?**
go: cannot find main module; see 'go help modules'

**Anything else we should know about your project / environment?**
Ubuntu with a fresh installation of go

**Comment by neild** [comment]
This command doesn't work with module support turned on in the `go` command. The following will work for now:

```
GO111MODULE=off go get -u github.com/golang/protobuf/protoc-gen-go
```

We need to update the documentation with something that will continue to work after module support is enabled by default.

**Comment by neild** [comment]
Reopening, because this really is a problem with the documentation. (And thanks for reporting it!)

**Comment by dsnet** [comment]
> This command doesn't work with module support turned on in the go command.

I'm not sure how to reproduce this failure. On `go1.11`, I run `go get -u github.com/golang/protobuf/protoc-gen-go` and it works regardless of whether I invoke it inside or outside the repo root.

**Comment by neild** [comment]
Set `GO111MODULE=on` and it should fail.

**Comment by dsnet** [comment]
This issue is blocked on https://github.com/golang/go/issues/24250 since there are limitations to the Go toolchain for what can be done here.

**Comment by dsnet** [comment]
On Go1.16, you can install a binary from outside a module with:
```
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
```
