### ISSUE TITLE
support embedding message

### ISSUE THREAD

**Issue by unlikezy** [golang/protobuf#752]
My request might be similar to #192 
Given the proto definition:
```
synatx = "proto3";
package test;
message Req1 {
    string user_id = 1;
    uint64 timestamp = 2;
    uint64 region_id = 3;
     string req1_fff1 = 10;
     string req1_fff2 = 11;
}
message Req2 {
    string user_id = 1;
    uint64 timestamp = 2;
    uint64 region_id = 3;
     string req2_fff1 = 10;
     string req2_fff2 = 11;
}
// more reqs definition....
```
As you can see, every Req definition needs some common fileds(1~3).
I have to repeate them(might be a lot) in every message.
You might suggest to seperate these fields into a new message, like this:
```
message CommonFields {
    string user_id = 1;
    uint64 timestamp = 2;
    uint64 region_id = 3;
}
message Req1 {
     CommonFields common_fields = 1;
     string req1_fff1 = 10;
     string req1_fff2 = 11;
}
message Req2 {
     CommonFields common_fields = 1;
     string req2_fff1 = 10;
     string req2_fff2 = 11;
}
````

But we are using grpcgateway, and the json proto is required by our company MUST be the former way:
(there might be a lot other reasons for people need proto be in this way)
```
message Req1 {
    string user_id = 1;
    uint64 timestamp = 2;
    uint64 region_id = 3;
     string req1_fff1 = 10;
     string req1_fff2 = 11;
}
```

The problem will be well solved if protobuf provide a syntax suger like this:
```
message Req1 {
      CommonFields;
     string req1_fff1 = 10;
     string req1_fff2 = 11;
}
```

what protoc should do is to treat this definition as below:
```
message Req1 {
    string user_id = 1;
    uint64 timestamp = 2;
    uint64 region_id = 3;
     string req1_fff1 = 10;
     string req1_fff2 = 11;
}
```
This solution seems quite straightforward.

**Comment by neild** [comment]
Yes, this request is best filed against https://github.com/protocolbuffers/protobuf. Closing this one as a duplicate.
