### ISSUE TITLE
GetOptions returns nil, but GetField show options available

### ISSUE THREAD

**Issue by sbezverk** [golang/protobuf#758]
**What version of protobuf and what language are you using?**
Version: 93b26e6a70e37abb14f2f88194949312b0592a84

**What did you do?**

	req := csi.CreateVolumeRequest{
		Secrets: map[string]string{"secret1": "secret1", "secret2": "secret2"},
	}
	_, md := descriptor.ForMessage(&req)
	fmt.Printf("%+v\n", md.GetField())
	opts := md.GetOptions()

md.GetField shows that `options` exists in the output.
```
[name:"name" number:1 label:LABEL_OPTIONAL type:TYPE_STRING json_name:"name"  name:"parameters" number:2 label:LABEL_REPEATED type:TYPE_MESSAGE type_name:".csi.v1.CreateVolumeRequest.ParametersEntry" json_name:"parameters"  name:"secrets" number:3 label:LABEL_REPEATED type:TYPE_MESSAGE type_name:".csi.v1.CreateVolumeRequest.SecretsEntry" json_name:"secrets" options:<[csi.v1.csi_secret]:true > ]
```

**What did you expect to see?**

opts has a non-nil value

**What did you see instead?**

opts is `nil`

```
syntax = "proto3";
package csi.v1;

import "google/protobuf/descriptor.proto";

option go_package = "csi";

extend google.protobuf.FieldOptions {
  bool csi_secret = 1059;
}

service Controller {
  rpc CreateVolume (CreateVolumeRequest)
    returns (CreateVolumeResponse) {}
}

message CreateVolumeRequest {
  string name = 1;
  map<string, string> parameters = 2;
  map<string, string> secrets = 3 [(csi_secret) = true];
}

message CreateVolumeResponse {
    string name = 1;
    map<string, string> parameters = 2;
    map<string, string> secrets = 3 [(csi_secret) = true];
  }
```

**Comment by dsnet** [comment]
I'm not sure what you are trying to show...

`md.GetField()` is a different field from `md.GetOptions()`, so printing the former tells you nothing about the later.

**Comment by sbezverk** [comment]
@dsnet thanks for your reply. Maybe it is my misunderstanding but according to the output of GetField() `options:<[csi.v1.csi_secret]:true >` is there.

**Comment by dsnet** [comment]
That only tells me that there is a sub-field also named "options" as returned by "md.GetField", but it tells me nothing about "md.GetOptions".

**Comment by dsnet** [comment]
I'm not sure how to help you. The proto file you posted does not seem related to the code snippet you posted.

What is the type returned by `descriptor.ForMessage(&req)`? It seems to be a protobuf message, but which one? It does not look like any of the messages in the proto file you're showing.

**Comment by sbezverk** [comment]
@dsnet the code I pasted it was just an attempt to try to access options. I was trying different ways but no success.
descriptor.ForMessage(&req) returns two values  (fd *protobuf.FileDescriptorProto, md *protobuf.DescriptorProto)

it looks like Options should be accessible with `opts := md.GetOptions()`
