### ISSUE TITLE
proposal: unwrapped request response

### ISSUE THREAD

**Issue by egonelbre** [golang/protobuf#770]
Currently protoc-gen-go generates interfaces that hide the method arguments and responses. It would be clearer if the request/response types were "unwrapped".

For example:

```
service Database {
  rpc Put(PutRequest) returns (EmptyResponse);
  rpc Get(GetRequest) returns (GetResponse);
}

message PutRequest {
  string path = 1;
  bytes  data = 2;
}

message EmptyResponse {}

message GetRequest {
  string path = 1;
}

message GetResponse {
  bytes  data = 1;
}
```

It currently generates interfaces:

```
func (Database) Put(ctx context.Context, req *PutRequest) (*EmptyResponse, error) { ... }
func (Database) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) { ... }
```

However it would look nicer and clearer if the request/response could be implemented as:

```
func (Database) Put(ctx context.Context, path string, data []byte) error { ... }
func (Database) Get(ctx context.Context, path string) ([]byte, error) { ... }
```

I understand that it wouldn't work for all scenarios, however it would be nicer code for common cases.

_First requested in https://github.com/gogo/protobuf/issues/517_

**Proposal**

Version "Option". Based on a option instead of generating the "wrapped" interfaces, generate the "unwrapped" versions.

Version "Wrapped". Based on a option additionally generate a Register that takes the unwrapped service implementation as an argument.

**Alternatives**

These wrappers can be written manually, which adds overhead.

Separate wrapper generator could be used on top of protobuf, which would be somewhat annoying to use.

**Comment by neild** [comment]
The only generation we do for services is for gRPC. If you have suggestions for changes to the gRPC generator, they should be filed here:
https://github.com/grpc/grpc-go/issues

(For historical reasons, the gRPC service generator currently lives in this repository and is linked into the protoc-gen-go command, but it's separate from general-purpose protobufs.)

**Comment by neild** [comment]
Yeah, the gRPC generator really should be in the gRPC repo. I have hopes of fixing that at some point, but that's a ways off.
