### ISSUE TITLE
not install protoc-gen-go

### ISSUE THREAD

**Issue by tdytaylor** [golang/protobuf#773]
env： windows10 64, golang 1.11
when i execute  : go get github.com/golang/protobuf/protoc-gen-go
i have get the trouble：
$GOPATH\src\github.com\golang\protobuf\protoc-gen-go\descriptor\descriptor.pb.go:21: undefined: proto.ProtoPackageIsVersion3
E:$GOPATH\src\github.com\golang\protobuf\protoc-gen-go\descriptor\descriptor.pb.go:379: undefined: proto.InternalMessageInfo
$GOPATH\src\github.com\golang\protobuf\protoc-gen-go\descriptor\descriptor.pb.go:441: undefined: proto.InternalMessageInfo
$GOPATH\src\github.com\golang\protobuf\protoc-gen-go\descriptor\descriptor.pb.go:569: undefined: proto.InternalMessageInfo
$GOPATH\src\github.com\golang\protobuf\protoc-gen-go\descriptor\descriptor.pb.go:673: undefined: proto.InternalMessageInfo
$GOPATH\src\github.com\golang\protobuf\protoc-gen-go\descriptor\descriptor.pb.go:730: undefined: proto.InternalMessageInfo
$GOPATH\src\github.com\golang\protobuf\protoc-gen-go\descriptor\descriptor.pb.go:786: undefined: proto.InternalMessageInfo
$GOPATH\src\github.com\golang\protobuf\protoc-gen-go\descriptor\descriptor.pb.go:855: undefined: proto.InternalMessageInfo
$GOPATH\src\github.com\golang\protobuf\protoc-gen-go\descriptor\descriptor.pb.go:959: undefined: proto.InternalMessageInfo
$GOPATH\src\github.com\golang\protobuf\protoc-gen-go\descriptor\descriptor.pb.go:1015: undefined: proto.InternalMessageInfo
$GOPATH\src\github.com\golang\protobuf\protoc-gen-go\descriptor\descriptor.pb.go:1015: too many errors

**Comment by dsnet** [comment]
It seems that you're running on Windows (due to backslashes). I'm not sure why this isn't working. `github.com/golang/protobuf/protoc-gen-go` is in the same repository as `github.com/golang/protobuf/proto`, so the dependency on `proto` should have been updated at the same time.

Have you tried `go get -u github.com/golang/protobuf/protoc-gen-go`? Have you tried manually updating the protobuf repo?

**Comment by dsnet** [comment]
Closing this as this repo uses the issue tracker mainly for problems that are actionable on our end. This sounds like a problem with the setup of the Go toolchain and/or $GOPATH on your system. Feel free to respond to my comment above and we can go from there.
