### ISSUE TITLE
protoc generate go file error for "expected 'IDENT', found 'import'"

### ISSUE THREAD

**Issue by Alllfred** [golang/protobuf#774]
When try "protoc --go_out=plugins=micro:./ core_user/core_user_service.proto", the protoc-gen-go report error for
```
18/12/19 16:42:51 protoc-gen-go: error:bad Go source code was generated: 7:1: expected 'IDENT', found 'import'
    1   // Code generated by protoc-gen-go. DO NOT EDIT.
    2   // source: core_user/core_user_service.proto
    3
    4
    5   package
    6
    7   import (
    8   fmt "fmt"
    9   math "math"
   10   proto "github.com/golang/protobuf/proto"
   11   )
   12
   13   // Reference imports to suppress errors if they are not otherwise used.
   14   var _ = proto.Marshal
   15   var _ = fmt.Errorf
   16   var _ = math.Inf
```

It seems like `gofmt` not work?

**Comment by puellanivis** [comment]
The code should be:
```
package PACKAGE_NAME

import …
```

Something is causing it to not include a package name. Perhaps we could add some logic to avoid emitting an empty package name, but the problem centrally lies in the `.proto` very likely. Perhaps there is a `option go_package = "";` or something similar. Without seeing the source `.proto` file it is only possible to guess though.

**Comment by dsnet** [comment]
Closing as stale since no `.proto` file was provided.

**Comment by mancini0** [comment]
I encountered the same error when I 1)did not use an equal sign after --proto_path and 2) used a squiggly ~ alias for home instead of the full path /home/ronmexico/......

protoc --proto_path=/home/ronmexico/open-exchange/proto --go_out=$GOPATH ox.proto

**Comment by automaticalldramatic** [comment]
Had a similar problem and my relative path was wrong 🙄. The errors sound like I have made a mistake i can never recover from, my girlfriend might leave me and I might have to sell my kidney but then it turns out your relative path is wrong and all is fine. Anyways, heres what my generate looked like -

```go
// go:generate protoc auth/auth.proto --go_out=plugins=grpc,paths=source_relative:./ ./auth/auth.proto
```
