### ISSUE TITLE
proto3 not support when use go mod

### ISSUE THREAD

**Issue by shukyoo** [golang/protobuf#777]
Im using go1.11, run "go mod tidy" and it download v1.2.0(the latest tag), but it not support proto3!
broken with " undefined: proto.ProtoPackageIsVersion3" when build.

**Comment by dsnet** [comment]
Go modules only manages Go package dependencies, and not binary dependencies. This is almost certainly happening because you are using a version of `protoc-gen-go` that is beyond `v1.2.0`. Follow the directions in https://github.com/golang/protobuf#installation for how to install a particular version of `protoc-gen-go`. Let me know if this still doesn't work.

**Comment by zserge** [comment]
Not sure why this is closed. A common pattern is to include build tool dependencies in some `tools.go` file with a build tag excluding it from the regular builds, but still allowing you to control the exact versions. Then using `go install` installs all the build tools of the specific versions, making builds more or less environment-independent. Example: https://github.com/golang/go/issues/25922

Here the latest tag in protobuf is far from being actually the latest, and `go get` with modules enabled downloads version 1.2.0, which is often not what's expected. I would suggest re-opening this issue until the recent up-to-date version gets a proper git tag.

**Comment by neild** [comment]
Note that the title of this issue is wrong: The up-to-date version is 1.2.0, which supports proto3. The version of the package including the symbol `ProtoPackageIsVersion3` is unreleased; that symbol refers (admittedly confusingly) to a revision of the proto package's internal support API and not the version 3 protocol buffer specification.

**Comment by wantg** [comment]
@neild 

There is only 1 and 2 in 1.2.0

![screen shot 2019-01-08 at 5 46 55 pm](https://user-images.githubusercontent.com/963880/50822857-ac06ca80-136d-11e9-9cf2-71179d22f68f.png)

**Comment by lockp111** [comment]
You really should add a new tag
I can install right version protoc-gen-go but not every one
When I use go-micro@0.17.0 ,it run error: `undefined: proto.ProtoPackageIsVersion3`

**Comment by emurmotol** [comment]
Build error still present ```undefined: proto.ProtoPackageIsVersion3```

**Comment by fdmsantos** [comment]
Exist any workaround? Same happens here. I can't use proto3 with go modules

**Comment by fdmsantos** [comment]
I have the same problem.

I use a temporary workaround
Run:

` go get github.com/golang/protobuf@master`

this will update your go modules to use master branch, and the build will work fine.

**Comment by jiusanzhou** [comment]
I have the same problem.

I follow @fdmsantos 's step, but things don't work fine.

I enter the directory of `github.com/golang/protobuf`, found that the tag of the code is not `master`, and I can not find `ProtoPackageIsVersion3 = true` in the `lib.go`.

I use my way to fix this problem:
1. `git pull origin master` in `github.com/golang/protobuf`.
2. remove tag `v1.2.0` of `github.com/golang/protobuf` in `go.mod` file.

Things work well for me. :tada:

**Comment by jiusanzhou** [comment]
1. `go get github.com/golang/protobuf@master`
2. `go mod vendor` re-vendor

Things work fine for me.

If you are not sure, you can open `go.mod`, checkout the version tag of `github.com/golang/protobuf` should be `v0.0.0 ...`, and you can find `ProtoPackageIsVersion3 = true` in the `proto/lib.go`, if you have vendor directory in your project, check it first. That will be fine.

**Comment by evmar** [comment]
I just ran into this as well, as a first time user of proto and go.  I think you should reopen this bug, because the install instructions from your website plainly don't work.

**Comment by calarasmihail** [comment]
> 1. go get github.com/golang/protobuf@master

Produce this: go: cannot use path@version syntax in GOPATH mode

**Comment by jiusanzhou** [comment]
> 
> 
> **@jiusanzhou**
> 
> > 1. go get github.com/golang/protobuf@master
> 
> Produce this: go: cannot use path@version syntax in GOPATH mode

Looks like your project in GOPATH directory. You can try to enable gomod with command `export GO111MODULE=on`
