### ISSUE TITLE
oneof: generated code uses pointers for non-primitive types

### ISSUE THREAD

**Issue by tamird** [golang/protobuf#78]
See: https://github.com/golang/protobuf/blob/535a10468679b4cf155f6a7afdf53b554633fc09/proto/testdata/test.pb.go#L2031

There's no need for this to be a pointer, since the union interface is implemented for a pointer of the wrapping struct. The downside of using a pointer here is that it results in an additional allocation.

**Comment by dsymonds** [comment]
While what you say is true, it's a pointer for symmetry with all the other occurrences of messages.

**Comment by awalterschulze** [comment]
Please just think about this for another few seconds before dismissing this.

**Comment by atombender** [comment]
This should be reopened and addressed.
