### ISSUE TITLE
What is the "proto package version"?

### ISSUE THREAD

**Issue by MakotoE** [golang/protobuf#787]
In `README.md`, it says:

> If you need a particular version of `protoc-gen-go` (e.g., to match your `proto` package version), one option is...

It also says:

> Grab the code from the repository and install the `proto` package. The simplest way is to run `go get -u github.com/golang/protobuf/protoc-gen-go`.

I'm confused as to what `proto` is. In the second quote, it implies that the `proto` package is `github.com/golang/protobuf/protoc-gen-go`. But in the first quote, it differentiates `protoc-gen-go` and `proto`, saying that they might have different versions.

What I really would like to know is how I can find out what version of `protoc-gen-go` I need.

**Comment by cybrcodr** [comment]
`protoc-gen-go` is the command-line generator tool used by protoc to generate the .pb.go files.  The reference to `proto package` refers to the Go `github.com/golang/protobuf/proto` package.  It is generally preferred to use the same version of the Go package as the generator.

The instructions provided in that bullet point describes how to check out the repo at a particular version (e.g. v1.2.0) and build `protoc-gen-go`.  That repo will also contain the Go `proto package` at that same version and hence can be used when building your Go code that uses that package.

For stable releases, do use the version tags.  v1.2.0 is currently the latest.

**Comment by MakotoE** [comment]
@cybrcodr I appreciate the reply. That clears up everything.
