### ISSUE TITLE
Support generated code use package in right way without option go_package

### ISSUE THREAD

**Issue by alx696** [golang/protobuf#791]
**Is your feature request related to a problem? Please describe.**
Without `option go_package`, generated code lost import define, have different package name but placed in one directory.

**Describe the solution you'd like**
Auto generated code with `package` in right way. 

**Describe alternatives you've considered**
1. Re-use `import_path`, define the base import path of import proto in generated code. Such as `lilu.red/project_name`, son.pb.go will import father from: `lilu.red/project_name/auto/grpc/father`
2. Generate folders like Java. `package auto.grpc.father;` will generated directory `auto/grpc/father`. Its better to distinguish the same name struct in different package.
>  Currently: `option go_package` need to be defined in every proto file, and not support batch generation #790 . `package auto.grpc.son` in generated code is `package auto_grpc_son`, lost import, and put then in same place(Golang not allow different package in one directory)!!

**Additional context**
father.proto
```
syntax = "proto3";

package auto.grpc.father;
//option go_package = "lilu.red/proto/auto/grpc/father";

message Info {
  string name = 1;
}
```

son.proto
```
syntax = "proto3";

package auto.grpc.son;
//option go_package = "lilu.red/proto/auto/grpc/son";

import "father.proto";

service SonService {
  rpc Insert (Info) returns (Info) {
  }
}

message Info {
  string id = 1; //auto set
  string name = 2;
  father.Info father = 3;
}
```

**Comment by dsnet** [comment]
We're moving towards a world where we double down on the presence of `go_package`. Any logic that tries to derive the Go package path from the information in protobuf alone leads to insanity in some way or another. The `go_package` option is the only way to have a sane understanding of how proto files relate to one another in the Go language.
