### ISSUE TITLE
proposal: export grpc plugin or support add new plugin for protoc-gen-go

### ISSUE THREAD

**Issue by chai2010** [golang/protobuf#80]
I fork the `protoc-gen-go/main.go` to create a new plugin for protoc-gen-go.
But the `grpc` is a internal package, can't import into other outside package.

https://github.com/chai2010/protorpc/tree/master/protoc-gen-go

**Comment by dsymonds** [comment]
We don't support that package boundary, which is why it's internal. You should fork the whole thing if you want to customise it.
