### ISSUE TITLE
proto: func (*Buffer) Marshal(pb message) failure conds

### ISSUE THREAD

**Issue by isiddi4** [golang/protobuf#800]
Hi there, 
I'm new at this whole "asking questions on github" thing so forgive me if this isn't the place for my question or if my question isn't well formatted.

Given the following bit of example code:
```
func foo(pb Message) ([]byte, error) {
    var b []byte
    buff := proto.NewBuffer(b)
    buff.SetDeterministic(true)

    if err := buff.Marshal(pb); err != nil {
        return b, errors.Wrap(err, "could not marshal message")
    }

    return buff.Bytes(), nil
}
```
in what scenarios should buff.Marshal(pb) throw an error besides pb == nil?

Thanks

**Comment by neild** [comment]
If pb is missing any required fields (proto2 only), or if it contains any string fields with invalid UTF-8 (proto3 only).

There might be some other cases I'm not thinking of, but those are the ones that come to mind.
