### ISSUE TITLE
Getting original string message from a proto.Message

### ISSUE THREAD

**Issue by nairan** [golang/protobuf#803]
Hi team, I have a noob question - 

I am getting a message that implements proto's Message interface. I need to get the original []byte out of the message and then do some manipulation on the original []byte. Is there a way to do so?

If I call String() - I will get original []byte along with implementation specific texts, like this: `msg_body:"what I want"`

Thank you for any hints!

**Comment by dsnet** [comment]
Once a message has been parsed from the `[]byte`, the original slice is no longer available. You can re-marshal the `[]byte` by calling [`proto.Marshal`](https://godoc.org/github.com/golang/protobuf/proto#Marshal) on the message.
