### ISSUE TITLE
parsing go.mod: unexpected module path "golang.org/x/lint"

### ISSUE THREAD

**Issue by acim** [golang/protobuf#804]
**What version of protobuf and what language are you using?**
Version: (e.g., `v1.1.0`, `89a0c16f`, etc)

go 1.12, protobuf 1.3.0

**What did you do?**
If possible, provide a recipe for reproducing the error.
A complete runnable program is good with `.proto` and `.go` source code.

> 
> Using Docker executor with image golang:1.12 ...
> $ ${APT_GET} update
> Get:1 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
> Ign:2 http://deb.debian.org/debian stretch InRelease
> Get:3 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]
> Get:4 http://deb.debian.org/debian stretch Release [118 kB]
> Get:5 http://deb.debian.org/debian stretch Release.gpg [2434 B]
> Get:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [474 kB]
> Get:7 http://deb.debian.org/debian stretch-updates/main amd64 Packages [11.1 kB]
> Get:8 http://deb.debian.org/debian stretch/main amd64 Packages [7084 kB]
> Fetched 7874 kB in 1s (4784 kB/s)
> Reading package lists...
> $ ${APT_GET} -y install libprotobuf-dev protobuf-compiler
> Reading package lists...
> Building dependency tree...
> Reading state information...
> The following additional packages will be installed:
>   libprotobuf-lite10 libprotobuf10 libprotoc10 zlib1g-dev
> The following NEW packages will be installed:
>   libprotobuf-dev libprotobuf-lite10 libprotobuf10 libprotoc10
>   protobuf-compiler zlib1g-dev
> 0 upgraded, 6 newly installed, 0 to remove and 17 not upgraded.
> Need to get 2643 kB of archives.
> After this operation, 14.1 MB of additional disk space will be used.
> Get:1 http://deb.debian.org/debian stretch/main amd64 zlib1g-dev amd64 1:1.2.8.dfsg-5 [205 kB]
> Get:2 http://deb.debian.org/debian stretch/main amd64 libprotobuf10 amd64 3.0.0-9 [681 kB]
> Get:3 http://deb.debian.org/debian stretch/main amd64 libprotobuf-lite10 amd64 3.0.0-9 [125 kB]
> Get:4 http://deb.debian.org/debian stretch/main amd64 libprotobuf-dev amd64 3.0.0-9 [954 kB]
> Get:5 http://deb.debian.org/debian stretch/main amd64 libprotoc10 amd64 3.0.0-9 [626 kB]
> Get:6 http://deb.debian.org/debian stretch/main amd64 protobuf-compiler amd64 3.0.0-9 [52.8 kB]
> debconf: delaying package configuration, since apt-utils is not installed
> Fetched 2643 kB in 0s (56.5 MB/s)
> Selecting previously unselected package zlib1g-dev:amd64.
> (Reading database ... 
> (Reading database ... 5%
> ...
> (Reading database ... 100%
> (Reading database ... 15092 files and directories currently installed.)
> Preparing to unpack .../0-zlib1g-dev_1%3a1.2.8.dfsg-5_amd64.deb ...
> Unpacking zlib1g-dev:amd64 (1:1.2.8.dfsg-5) ...
> Selecting previously unselected package libprotobuf10:amd64.
> Preparing to unpack .../1-libprotobuf10_3.0.0-9_amd64.deb ...
> Unpacking libprotobuf10:amd64 (3.0.0-9) ...
> Selecting previously unselected package libprotobuf-lite10:amd64.
> Preparing to unpack .../2-libprotobuf-lite10_3.0.0-9_amd64.deb ...
> Unpacking libprotobuf-lite10:amd64 (3.0.0-9) ...
> Selecting previously unselected package libprotobuf-dev:amd64.
> Preparing to unpack .../3-libprotobuf-dev_3.0.0-9_amd64.deb ...
> Unpacking libprotobuf-dev:amd64 (3.0.0-9) ...
> Selecting previously unselected package libprotoc10:amd64.
> Preparing to unpack .../4-libprotoc10_3.0.0-9_amd64.deb ...
> Unpacking libprotoc10:amd64 (3.0.0-9) ...
> Selecting previously unselected package protobuf-compiler.
> Preparing to unpack .../5-protobuf-compiler_3.0.0-9_amd64.deb ...
> Unpacking protobuf-compiler (3.0.0-9) ...
> Setting up libprotobuf10:amd64 (3.0.0-9) ...
> Processing triggers for libc-bin (2.24-11+deb9u3) ...
> Setting up libprotobuf-lite10:amd64 (3.0.0-9) ...
> Setting up libprotoc10:amd64 (3.0.0-9) ...
> Setting up zlib1g-dev:amd64 (1:1.2.8.dfsg-5) ...
> Setting up protobuf-compiler (3.0.0-9) ...
> Setting up libprotobuf-dev:amd64 (3.0.0-9) ...
> Processing triggers for libc-bin (2.24-11+deb9u3) ...
> $ go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
> go: finding github.com/dgrijalva/jwt-go v3.2.0+incompatible
> go: finding github.com/go-chi/chi v3.3.2+incompatible
> go: finding github.com/DataDog/datadog-go v0.0.0-20180822151419-281ae9f2d895
> go: finding github.com/cznic/b v0.0.0-20181118192635-3e14204ac75d
> go: finding github.com/gosimple/slug v1.1.1
> go: finding github.com/syndtr/goleveldb v0.0.0-20181105012736-f9080354173f
> go: finding github.com/Smerity/govarint v0.0.0-20150407073650-7265e41f48f1
> go: finding github.com/go-redis/redis v6.12.0+incompatible
> go: finding github.com/hashicorp/go-multierror v1.0.0
> go: finding gopkg.in/vmihailenco/msgpack.v2 v2.9.1
> go: finding github.com/matttproud/golang_protobuf_extensions v1.0.1
> go: finding github.com/hashicorp/serf v0.8.1
> go: finding github.com/mschoch/smat v0.0.0-20160514031455-90eadee771ae
> go: finding github.com/facebookgo/freeport v0.0.0-20150612182905-d4adf43b75b9
> go: finding github.com/rainycape/unidecode v0.0.0-20150907023854-cb7f23ec59be
> go: finding github.com/daaku/go.zipexe v0.0.0-20150329023125-a5fe2436ffcb
> go: finding github.com/prometheus/client_model v0.0.0-20171117100541-99fa1f4be8e5
> go: finding github.com/uber/jaeger-lib v1.5.0
> go: finding github.com/opentracing-contrib/go-stdlib v0.0.0-20180313041242-367231351874
> go: finding github.com/pierrec/xxHash v0.1.1
> go: finding github.com/fortytw2/leaktest v1.3.0
> go: finding github.com/dnaeon/go-vcr v0.0.0-20180607100630-8b144be0744f
> go: finding github.com/onsi/gomega v1.4.2
> go: finding github.com/pelletier/go-toml v1.2.0
> go: finding github.com/smartystreets/assertions v0.0.0-20180927180507-b2de0cb4f26d
> go: finding github.com/glycerine/goconvey v0.0.0-20180728074245-46e3a41ad493
> go: finding github.com/hashicorp/consul v1.4.0
> go: finding github.com/prometheus/common v0.0.0-20180518154759-7600349dcfe1
> go: finding github.com/BurntSushi/toml v0.3.1
> go: finding github.com/kardianos/osext v0.0.0-20170510131534-ae77be60afb1
> go: finding github.com/robfig/cron v0.0.0-20180505203441-b41be1df6967
> go: finding github.com/facebookgo/subset v0.0.0-20150612182917-8dac2c3c4870
> go: finding github.com/mattn/go-isatty v0.0.4
> go: finding github.com/inconshreveable/mousetrap v1.0.0
> go: finding github.com/bradfitz/gomemcache v0.0.0-20170208213004-1952afaa557d
> go: finding golang.org/x/sync v0.0.0-20181108010431-42b317875d0f
> go: finding github.com/facebookgo/stats v0.0.0-20151006221625-1b76add642e4
> go: finding github.com/tecbot/gorocksdb v0.0.0-20181010114359-8752a9433481
> go: finding github.com/steveyen/gtreap v0.0.0-20150807155958-0abe01ef9be2
> go: finding github.com/onsi/ginkgo v1.6.0
> go: finding github.com/sean-/seed v0.0.0-20170313163322-e2103e2c3529
> go: finding github.com/gwenn/yacr v0.0.0-20180527135820-fa408d8ebf1b
> go: finding github.com/pascaldekloe/goe v0.0.0-20180627143212-57f6aae5913c
> go: finding golang.org/x/sys v0.0.0-20181128092732-4ed8d59d0b35
> go: finding github.com/boltdb/bolt v1.3.1
> go: finding github.com/blevesearch/bleve v0.7.0
> go: finding github.com/mitchellh/mapstructure v0.0.0-20180511142126-bb74f1db0675
> go: finding github.com/facebookgo/grace v0.0.0-20170218225239-4afe952a37a4
> go: finding github.com/glycerine/go-unsnap-stream v0.0.0-20180323001048-9f0cb55181dd
> go: finding go.uber.org/atomic v1.3.2
> go: finding github.com/facebookgo/clock v0.0.0-20150410010913-600d898af40a
> go: finding golang.org/x/net v0.0.0-20181114220301-adae6a3d119a
> go: finding github.com/armon/go-metrics v0.0.0-20180917152333-f0300d1749da
> go: finding github.com/uber-go/atomic v1.3.2
> go: finding github.com/miekg/dns v1.0.15
> go: finding github.com/golang/protobuf v1.2.1-0.20181127190454-8d0c54c12466
> go: finding github.com/spf13/pflag v1.0.1
> go: finding google.golang.org/grpc v1.16.0
> go: finding github.com/nsqio/go-nsq v1.0.7
> go: finding github.com/philhofer/fwd v1.0.0
> go: finding github.com/smartystreets/goconvey v0.0.0-20181108003508-044398e4856c
> go: finding golang.org/x/text v0.3.0
> go: finding golang.org/x/image v0.0.0-20180601115456-af66defab954
> go: finding github.com/satori/go.uuid v1.2.0
> go: finding github.com/hpcloud/tail v1.0.0
> go: finding github.com/grpc-ecosystem/grpc-opentracing v0.0.0-20180507213350-8e809c8a8645
> go: finding github.com/uber/jaeger-client-go v2.14.0+incompatible
> go: finding github.com/hashicorp/go-rootcerts v0.0.0-20160503143440-6bb64b370b90
> go: finding github.com/hashicorp/go-msgpack v0.0.0-20150518234257-fa3f63826f7c
> go: finding gopkg.in/yaml.v2 v2.2.1
> go: finding github.com/hashicorp/hcl v0.0.0-20180404174102-ef8a98b0bbce
> go: finding github.com/facebookgo/stack v0.0.0-20160209184415-751773369052
> go: finding github.com/hashicorp/go-immutable-radix v1.0.0
> go: finding github.com/oschwald/geoip2-golang v1.2.1
> go: finding github.com/cznic/strutil v0.0.0-20181118192634-2ae56eb84c8e
> go: finding github.com/rs/cors v1.4.0
> go: finding github.com/client9/misspell v0.3.4
> go: finding github.com/edsrzf/mmap-go v0.0.0-20170320065105-0bce6a688712
> go: finding gopkg.in/fsnotify.v1 v1.4.7
> go: finding github.com/hashicorp/go-retryablehttp v0.5.0
> go: finding github.com/GeertJohan/go.rice v0.0.0-20170420135705-c02ca9a983da
> go: finding github.com/mitchellh/go-homedir v1.0.0
> go: finding github.com/mailru/easyjson v0.0.0-20180606163543-3fdea8d05856
> go: finding github.com/pmezard/go-difflib v1.0.0
> go: finding github.com/magiconair/properties v1.8.0
> go: finding github.com/codahale/hdrhistogram v0.0.0-20161010025455-3a0bb77429bd
> go: finding github.com/hashicorp/go-uuid v1.0.0
> go: finding github.com/leekchan/accounting v0.0.0-20161211142212-a35854c07593
> go: finding github.com/facebookgo/ensure v0.0.0-20160127193407-b4ab57deab51
> go: finding github.com/spf13/afero v1.1.1
> go: finding github.com/hashicorp/memberlist v0.1.0
> go: finding golang.org/x/crypto v0.0.0-20180904163835-0709b304e793
> go: finding github.com/circonus-labs/circonus-gometrics v2.2.4+incompatible
> go: finding github.com/jmhodges/levigo v0.0.0-20161115193449-c42d9e0ca023
> go: finding github.com/mgutz/logxi v0.0.0-20161027140823-aebf8a7d67ab
> go: finding github.com/remyoudompheng/bigfft v0.0.0-20170806203942-52369c62f446
> go: finding github.com/spf13/cast v1.2.0
> go: finding github.com/stretchr/testify v1.2.2
> go: finding google.golang.org/genproto v0.0.0-20181127195345-31ac5d88444a
> go: finding github.com/golang/lint v0.0.0-20180702182130-06c8688daad7
> go: finding github.com/golang/snappy v0.0.0-20180518054509-2e65f85255db
> go: finding github.com/cznic/mathutil v0.0.0-20181118192635-6b113ba17c23
> go: finding github.com/facebookgo/httpdown v0.0.0-20160323221027-a3b1354551a2
> go: finding github.com/disintegration/imaging v1.4.2
> go: finding github.com/mattn/go-colorable v0.0.9
> go: finding github.com/jtolds/gls v4.2.1+incompatible
> go: finding golang.org/x/sys v0.0.0-20180909124046-d0be0721c37e
> go: finding github.com/prometheus/client_golang v0.8.0
> go: finding github.com/blevesearch/go-porterstemmer v1.0.1
> go: finding github.com/RoaringBitmap/roaring v0.4.9
> go: finding github.com/tv42/httpunix v0.0.0-20150427012821-b75d8614f926
> go: finding github.com/nicksnyder/go-i18n v1.10.0
> go: finding golang.org/x/net v0.0.0-20180826012351-8a410e7b638d
> go: finding github.com/hashicorp/go-cleanhttp v0.5.0
> go: finding github.com/golang/protobuf v1.2.0
> go: finding github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
> go: finding github.com/hashicorp/yamux v0.0.0-20181012175058-2f1d1f20f75d
> go: finding gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
> go: finding gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
> go: finding github.com/hashicorp/errwrap v1.0.0
> go: finding github.com/tinylib/msgp v1.0.2
> go: finding github.com/peterbourgon/diskv v2.0.1+incompatible
> go: finding github.com/gregjones/httpcache v0.0.0-20190212212710-3befbb6ad0cc
> go: finding golang.org/x/tools v0.0.0-20180828015842-6cd1fcedba52
> go: finding github.com/kisielk/gotool v1.0.0
> go: finding golang.org/x/oauth2 v0.0.0-20180821212333-d2e6202438be
> go: finding golang.org/x/lint v0.0.0-20180702182130-06c8688daad7
> go: finding github.com/blevesearch/blevex v0.0.0-20180227211930-4b158bb555a3
> go: finding github.com/oschwald/maxminddb-golang v1.3.0
> go: finding github.com/google/btree v0.0.0-20180124185431-e89373fe6b4a
> go: finding github.com/prometheus/procfs v0.0.0-20180612222113-7d6f385de8be
> go: finding golang.org/x/net v0.0.0-20180906233101-161cd47e91fd
> go: finding gopkg.in/square/go-jose.v2 v2.1.6
> go: finding github.com/golang/mock v1.1.1
> go: finding github.com/opentracing/opentracing-go v1.0.2
> go: finding gopkg.in/olivere/elastic.v5 v5.0.69
> go: finding github.com/mgutz/ansi v0.0.0-20170206155736-9520e82c474b
> go: finding google.golang.org/genproto v0.0.0-20180831171423-11092d34479b
> go: finding github.com/spf13/jwalterweatherman v0.0.0-20180109140146-7c0cea34c8ec
> go: finding google.golang.org/appengine v1.3.0
> go: finding github.com/gopherjs/gopherjs v0.0.0-20181103185306-d547d1d9531e
> go: finding google.golang.org/genproto v0.0.0-20180817151627-c66870c02cf8
> go: finding github.com/hashicorp/golang-lru v0.5.0
> go: finding github.com/willf/bitset v1.1.3
> go: finding cloud.google.com/go v0.26.0
> go: finding github.com/hashicorp/go-sockaddr v0.0.0-20180320115054-6d291a969b86
> go: finding github.com/blevesearch/segment v0.0.0-20160915185041-762005e7a34f
> go: finding golang.org/x/sys v0.0.0-20180830151530-49385e6e1522
> go: finding golang.org/x/sync v0.0.0-20180314180146-1d60e4601c6f
> go: finding github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
> go: finding github.com/davecgh/go-spew v1.1.1
> go: finding github.com/samuel/go-zookeeper v0.0.0-20180130194729-c4fab1ac1bec
> go: finding golang.org/x/net v0.0.0-20181106065722-10aee1819953
> go: finding github.com/fsnotify/fsnotify v1.4.7
> go: finding github.com/circonus-labs/circonusllhist v0.1.0
> go: finding github.com/pkg/errors v0.8.0
> go: finding honnef.co/go/tools v0.0.0-20180728063816-88497007e858
> go: finding google.golang.org/appengine v1.1.0
> go: finding github.com/couchbase/vellum v0.0.0-20180611210756-980bce45b36d
> go: finding github.com/spf13/viper v1.0.2
> go: finding github.com/spf13/cobra v0.0.3
> go: finding golang.org/x/net v0.0.0-20180724234803-3673e40ba225
> go: finding github.com/mitchellh/go-testing-interface v1.0.0
> go: finding github.com/golang/protobuf/protoc-gen-go latest
> go: finding github.com/golang/protobuf/proto latest
> go: finding github.com/golang/protobuf v1.3.0
> go: downloading github.com/golang/protobuf v1.3.0
> go: extracting github.com/golang/protobuf v1.3.0
> go: finding golang.org/x/sync latest
> go: finding google.golang.org/genproto latest
> go: finding golang.org/x/net latest
> go: finding golang.org/x/lint v0.0.0-20190227174305-5b3e6a55c961
> go: finding honnef.co/go/tools v0.0.0-20190102054323-c2f93a96b099
> go: finding golang.org/x/net v0.0.0-20190213061140-3a22650c66bd
> go: finding google.golang.org/grpc v1.19.0
> go: finding golang.org/x/tools v0.0.0-20190226205152-f727befe758c
> go: finding golang.org/x/lint latest
> go: finding golang.org/x/tools latest
> go: finding google.golang.org/appengine v1.4.0
> go: finding honnef.co/go/tools latest
> go: finding golang.org/x/exp v0.0.0-20190121172915-509febef88a4
> go: finding golang.org/x/exp latest
> go: finding golang.org/x/tools v0.0.0-20190114222345-bf090417da8b
> go: finding golang.org/x/oauth2 latest
> go: finding golang.org/x/lint v0.0.0-20181026193005-c67002cb31c3
> go: finding github.com/golang/glog latest
> go: finding cloud.google.com/go v0.36.0
> go: finding github.com/golang/mock v1.2.0
> go: finding golang.org/x/sys latest
> go: finding cloud.google.com/go v0.34.0
> go: finding golang.org/x/sync v0.0.0-20181221193216-37e7f081c4d4
> go: finding golang.org/x/net v0.0.0-20190108225652-1e06a53dbb7e
> go: finding golang.org/x/text v0.3.1-0.20180807135948-17ff2d5776d2
> go: finding honnef.co/go/tools v0.0.0-20190106161140-3f1c8253044a
> go: finding golang.org/x/tools v0.0.0-20181030000716-a0a13e073c7b
> go: finding golang.org/x/oauth2 v0.0.0-20181203162652-d668ce993890
> go: finding github.com/google/pprof v0.0.0-20181206194817-3ea8567a2e57
> go: finding github.com/google/go-cmp v0.2.0
> go: finding github.com/google/btree v0.0.0-20180813153112-4030bb1f1f0c
> go: finding google.golang.org/grpc v1.17.0
> go: finding github.com/googleapis/gax-go/v2 v2.0.3
> go: finding github.com/google/martian v2.1.0+incompatible
> go: finding github.com/google/btree latest
> go: finding google.golang.org/genproto v0.0.0-20190201180003-4b09977fb922
> go: finding github.com/golang/lint latest
> go: finding go.opencensus.io v0.18.0
> go: finding golang.org/x/time v0.0.0-20181108054448-85acf8d2951c
> go: finding golang.org/x/build v0.0.0-20190111050920-041ab4dc3f9d
> go: finding google.golang.org/api v0.1.0
> go: finding golang.org/x/time latest
> go: github.com/golang/lint@v0.0.0-20190227174305-5b3e6a55c961: parsing go.mod: unexpected module path "golang.org/x/lint"
> go get: error loading module requirements

**What did you expect to see?**

Fetching requirements properly.

**What did you see instead?**

Can't fetch requrements.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment?**

After I pinned protobuf to version 1.2.0, the pipeline worked again.

go get github.com/golang/protobuf/{proto@v1.2.0,protoc-gen-go@v1.2.0}

**Comment by acim** [comment]
I just realized that pinning protobuf fixed the build step, but in the lint step the problem again appeared but this is probably related to golint itself, not protobuf, sorry.

**Comment by acim** [comment]
grpc upgrade to 1.19.0 and pinning protobuf stuff to 1.2.0 helped, so there is maybe an issue here with the latest release dependencies.

**Comment by dsnet** [comment]
As of #808, `golang/protobuf` no longer has any external dependencies listed in the `go.mod` file.

**Comment by dmitshur** [comment]
@dsnet Thank you for doing that!

Are you planning on making a new semver tag, so that `go get github.com/golang/protobuf@latest` resolves to a version with the newly empty `go.mod` file (instead of `v1.3.0`, which still has a [bigger go.mod](https://github.com/golang/protobuf/blob/v1.3.0/go.mod#L4-L6))?

**Comment by negbie** [comment]
Same here.
go: github.com/golang/lint@v0.0.0-20190313153728-d0100b6bd8b3: parsing go.mod: unexpected module path "golang.org/x/lint"

**Comment by dsnet** [comment]
Done. `v1.3.1` has been tagged.
