### ISSUE TITLE
there might be a bug at mergeAny in "proto/clone.go"

### ISSUE THREAD

**Issue by galric** [golang/protobuf#81]
code :

    case reflect.Map:
        if in.Len() == 0 {
            return
        }
        if out.IsNil() {
            out.Set(reflect.MakeMap(in.Type()))
        }

maybe:

	case reflect.Map:
		if in.IsNil() {
			return
		}
		if out.IsNil() {
			out.Set(reflect.MakeMap(in.Type()))
		} 
		if in.Len() == 0 {
			return
		}

when merging an empty map

**Comment by dsymonds** [comment]
No, there's no semantic distinction between a nil and empty map in protocol buffers. They are considered equivalent.
