### ISSUE TITLE
jsonpb: json unmarshaling error for enum in array of struct

### ISSUE THREAD

**Issue by peterableda** [golang/protobuf#813]
**What version of protobuf and what language are you using?**
1.2.1

**What did you do?**
repro.proto
```
syntax = "proto3";

package repro;

enum Type {
  A = 0;
  B = 1;
}

message Thing {
  Type type = 1;
  string name = 2;
}

message TheThing {
  int32 id = 1;
  repeated Thing things = 4;
}
```

repro-test.go
```
package main

import (
	"log"
	"strings"

	"github.com/brewm/gobrewmmer/api/repro"
	"github.com/gogo/protobuf/jsonpb"
)

func main() {
	t := &repro.TheThing{
		Id: 1,
		Things: []*repro.Thing{
			{
				Name: "a",
				Type: repro.Type_A,
			},
			{
				Name: "b",
				Type: repro.Type_B,
			},
		},
	}

	m := jsonpb.Marshaler{}
	tJson, err := m.MarshalToString(t)
	if err != nil {
		log.Fatal("json marshaling error: ", err)
	}
	println(tJson)

	um := jsonpb.Unmarshaler{}
	unserialized := &repro.TheThing{}
	err = um.Unmarshal(strings.NewReader(tJson), unserialized)
	if err != nil {
		log.Fatal("json unmarshaling error: ", err)
	}
}
```

**What did you expect to see?**
Mashal/Unmarshal should work.

**What did you see instead?**
```
$ go run ./api/repro-test.go
{"id":1,"things":[{"name":"a"},{"type":"B","name":"b"}]}
2019/03/07 20:23:07 json unmarshaling error: unknown value "B" for enum repro.Type
exit status 1
```

**Comment by dsnet** [comment]
This project is for `golang/protobuf` for which `gogo/protobuf` is forked from. Does this fail when using the `github.com/golang/protobuf/jsonpb` package?
* If yes, can you provide the generated `.pb.go` file for the `repro` package? If it contains confidential information, can you please reduce your situation to a minimal reproduction?
* If no, then you may want to file this over at https://github.com/gogo/protobuf.

**Comment by peterableda** [comment]
Thanks, this was confusing... golang/protobuf works for me.
