### ISSUE TITLE
errUnimplemented redeclared in this block

### ISSUE THREAD

**Issue by praveenvaltix** [golang/protobuf#817]
**What version of protobuf and what language are you using?**
Version: (e.g., `v1.1.0`, `89a0c16f`, etc)
v3.6.0, Golang

**What did you do?**
If possible, provide a recipe for reproducing the error.
A complete runnable program is good with `.proto` and `.go` source code.
We have multiple proto files in the same go package.

**What did you expect to see?**
Compiles are failing.

**What did you see instead?**
We use go get for the following packages.
        "google.golang.org/grpc"
        "github.com/golang/protobuf/protoc-gen-go"
        "github.com/golang/protobuf/ptypes"
        "github.com/golang/protobuf/jsonpb"
        "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway"
        "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger"

For the last 3 hours our builds failing due to the following reason:
errUnimplemented redeclared in this block

This seems like a issue if anyone has more than 1 proto file in the same package. 

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment?**

**Comment by dsnet** [comment]
I see the issue, thanks for the report.

**Comment by praveenvaltix** [comment]
I think that method should be implemented per class.

**Comment by praveenvaltix** [comment]
@dsnet can you please let us know if you have merged? We are unfortunately not using go dep or module. Do you have a recommendation on how to use a different version  of this package using "go get"?
