### ISSUE TITLE
GPRC service with no RPC methods no longer compiles?

### ISSUE THREAD

**Issue by Martin2112** [golang/protobuf#819]
Hi,

Just checking if this was an intentional change or something unsupported that's "just worked" by accident before. Our Travis builds just broke. We have a service like this:

`service TrillianLogSequencer {}`

The generated code no longer builds as of today but was OK last week:

```
../trillian_log_sequencer_api.pb.go:11:2: imported and not used: "google.golang.org/grpc/codes"
../trillian_log_sequencer_api.pb.go:12:2: imported and not used: "google.golang.org/grpc/status"
```

Example:

https://travis-ci.org/google/trillian/jobs/507856974

If I add a dummy RPC to the service the problem goes away.

Thanks!

**Comment by dsnet** [comment]
Thanks for report. Fixed in #820.
