### ISSUE TITLE
Proto3 JSON map wire format should be compatible with proto2 per the spec

### ISSUE THREAD

**Issue by annismckenzie** [golang/protobuf#82]
Per the proto3 spec (https://developers.google.com/protocol-buffers/docs/proto3#backwards-compatibility): `The map syntax is equivalent to the following on the wire, so protocol buffers implementations that do not support maps can still handle your data`.
```protobuf
    message MapFieldEntry {
        key_type key = 1;
        value_type value = 2;
    }

    repeated MapFieldEntry map_field = N;
```

The `jsonpb` package should be able to correctly marshal to and unmarshal from maps serialized this way.

**Comment by dsymonds** [comment]
I'm not sure that's right. That quote defers to the binary wire format, not the JSON format (whose spec is yet to be published).

**Comment by annismckenzie** [comment]
My bad. :( The protobuf implementation for PHP doesn't have native maps support for proto3 yet and compiles maps down to the wire format you see above. It has a JSON codec which is why it's dumping maps to the repeated array syntax. I'll find a workaround. Sorry for the noise – closing.
