### ISSUE TITLE
APIv2:  Add MarshalInto() method to allow callers to control buffer allocations

### ISSUE THREAD

**Issue by richardartoul** [golang/protobuf#822]
I'm currently using [this library](https://github.com/jhump/protoreflect) and brought up [the issue](https://github.com/jhump/protoreflect/issues/176) on that repo, and they referred me here for suggesting new APIs.

**Is your feature request related to a problem? Please describe.**
I'm unable to control byte slice allocations when marshaling protobufs. This makes using reflection on the hot path in my code base significantly more expensive than it needs to be and leads to very high CPU utilization, memory utilization, and G.C pressure in situations where pooling the buffers could eliminate all of those issues almost entirely.

**Describe the solution you'd like**
I'd like a `MarshalInto` method that allows me to pass in a []byte into which the protbuf should be marshaled

**Describe alternatives you've considered**
I don't have any other alternative interfaces that seem reasonable to me, although I'm open to any suggestions that allow me to control allocations

**Comment by neild** [comment]
In the v1 API, you can use a `proto.Buffer` to marshal into an existing `[]byte`:
https://godoc.org/github.com/golang/protobuf/proto#Buffer

We haven't finalized the v2 API yet, but at the moment there's a `MarshalAppend` method which does the same thing:
https://go.googlesource.com/protobuf/+/refs/heads/master/proto/encode.go#58

An open question is whether we should eventually have a less-convenient but better-performing API. (Optional, of course.) The requirement that the entire message be marshaled into a single, contiguous memory region puts some limits on optimization.
