### ISSUE TITLE
godep issue

### ISSUE THREAD

**Issue by Quentin-M** [golang/protobuf#83]
Hi,

As the [Godep's README](https://github.com/tools/godep/blob/master/Readme.md) says: 
```
Godep does not copy:
- files from source repositories that are not tracked in version control.
- _test.go files.
- testdata directories.
```

However, `proto/proto3_proto/proto3.pb.go`, which is not named as a test file, imports `proto/testdata`. Thus, any go app that relies on protobuf or that has a dependency using protobuf could vendor its deps using godep. Some other vendoring tools don't include test files by default either.

A simple work-around would be to use `godep save -t ./...` to vendor test files as well but I believe that it is not the right approach.

**Comment by dsymonds** [comment]
I'm not too familiar with godep. Can't you just delete proto/proto3_proto/proto3.pb.go in your vendored copy?

**Comment by ecnahc515** [comment]
@dsymonds I generally think people try to avoid adding custom modifications regarding vendoring, as it means you're likely to experience conflicts later down the line. Could the subdefaults stuff be moved into it's own package separated from the testdata package so we don't have to pull in all the testdata package?

**Comment by dsymonds** [comment]
Sorry, I don't feel the need to bend to Godep's conventions on this.

**Comment by ecnahc515** [comment]
@dsymonds I think this is an issue with any vendoring solution, not just Godeps. It's rather annoying to have to make manual edits especially. I don't think anyone wants to maintain patches to their vendored libraries either.

**Comment by dsymonds** [comment]
It's only an issue with a vendoring tool that drops parts of the repo. Perhaps Godeps could check that its pruning isn't going to leave a dangling dependency edge.
