### ISSUE TITLE
cannot vendor protoc-gen-go if not imported in module .go code

### ISSUE THREAD

**Issue by codeliger** [golang/protobuf#830]
**What version of protobuf and what language are you using?**
Version: v1.3.1

**What did you do?**

`go build -mod=vendor sourcefile.go`

**What did you expect to see?**
I expected my go.mod dependency of `github.com/golang/protobuf` to be included in the vendor folder, even though it doesnt exist as an import in any of my go files because i need the packages `proto` and `protoc-gen-go`

I should be able to include a vendored dependency thats not directly needed by my go source code files to allow my dockerfile to build vendored `.proto` files without pregenerating them and commiting them to a repo. The reason for this is to ensure other users of my library do not ignore the `.proto` file and just use `*.pb.go` which could possibly be out of sync with its related .proto. If they have to use `protoc` everytime they pull my .proto file from my package then they are guarunteed to be in sync.

**What did you see instead?**

`/home/$USER/dev/go/src/github.com/username/modulename/vendor/github.com/golang/protobuf/proto no such file or directory` 

**go.mod**
```
go 1.12

require (
	github.com/confluentinc/confluent-kafka-go v0.11.6
	github.com/go-redis/redis v6.15.2+incompatible
	github.com/golang/protobuf v1.3.1 // indirect
	github.com/onsi/ginkgo v1.8.0 // indirect
	github.com/onsi/gomega v1.5.0 // indirect
	github.com/pkg/errors v0.8.1 // indirect
	gitlab.dv/username/modulename v0.0.0-20190403143051-76fe0c9dbba9
	go.uber.org/zap v1.9.1
)

module github.com/username/modulename
```
> excluded module directive

**Comment by dsnet** [comment]
What actionable fix are expecting from the `golang/protobuf` project? This seems more specific to the Go toolchain. Is their something you expect for us to change in our `go.mod` file to fix this?

**Comment by codeliger** [comment]
I will report this into the main golang repo issues.
