### ISSUE TITLE
proto: TextMarshaler should support `AnyResolver` for adding dynamic message support to "expanded Any syntax"

### ISSUE THREAD

**Issue by jhump** [golang/protobuf#835]
I have code that downloads message schemas dynamically ([grpcurl](https://github.com/fullstorydev/grpcurl)) and also supports the text format.

It would be ideal if users could provide `Any` messages using the [expanded Any syntax](https://github.com/golang/protobuf/blob/master/proto/text.go#L207) and also if the tool could print `Any` messages in responses using the expanded Any syntax. However, the current support only works if the payload of the `Any` message is registered with the `proto` package; e.g. compiled and linked into the binary. This will never be the case for `grpcurl` (except for payloads with descriptor and well-known types).

The `jsonpb` package supports an `AnyResolver`: pluggable support for instantiating a message instance given a type URL. Ideally, the exact same interface could be used in the text format, to extend support for expanded Any syntax to include dynamically processed/parsed schemas and descriptors.

**Comment by jhump** [comment]
@dsnet: If this sounds like something that might be accepted as a patch for the v1 API, I'm happy to contribute it.

Even if not, I wanted to put it on your radar as something I'd like to see handled in the v2 API. IIRC, support for `Any` messages in the v2 API will differ from the `AnyResolver` interface I added to the `jsonpb` package. But as long as the text format has analogous support, my need would be satisfied.

**Comment by dsnet** [comment]
This seems like sufficiently advanced functionality that we should hold off on this functionality until v2.

The v2 implementation currently supports custom resolvers: https://github.com/golang/protobuf/blob/872b50047a285b51cdbd767985719925eca2ec9a/encoding/textpb/encode.go#L41-L45

\cc @cybrcodr

**Comment by dsnet** [comment]
The new [`prototext`](https://pkg.go.dev/google.golang.org/protobuf/encoding/prototext) package addresses this issue and has been released as part of [`google.golang.org/protobuf@v1.20.0`](https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.20.0).
