### ISSUE TITLE
jsonpb unable to unmarshal enums stored as string when marshalling

### ISSUE THREAD

**Issue by ayushi-agarwal** [golang/protobuf#836]
**What version of protobuf and what language are you using?**
Master

**What did you do?**
Did marshalling using marshaller.MarshalToString(report)
report is a proto which has a enum field
Then did jsonpb.UnmarshalString(field, report)
Got this error : Error:  unknown value "ProductModelA" for enum configs.ClusterConfigProto_ProductModel
This error comes on line 891

**What did you expect to see?**
no error

**What did you see instead?**
error mentioned above

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment?**

**Comment by puellanivis** [comment]
Without seeing at least the relevant parts of your `.proto` file, we cannot really advise anything.

I wrote up a quick-and-dirty attempt to reproduce your issue, but my code was able to marshal and unmarshal back-and-forth properly.
```
test$ ./bin/linux.x86_64/test 
{"field":"ProductModelA"} <nil>
field:ProductModelA  <nil>
```

**Comment by liuliqiang** [comment]
hello, i get the same trouble like this, my proto is:

```
syntax = "proto3";

package io.liqiang.demo;

enum SIZE {
    LARGE = 0;
    MEDIUM = 1;
    SMALL = 2;
}

message Laptop {
    SIZE size = 2;
}
```

and my Go code is：

```
import (
	"fmt"

	"github.com/liuliqiang/<paths>/demos"

	"github.com/golang/protobuf/jsonpb"
)

func main() {
	l := io_liqiang_demo.Laptop{
		Size: io_liqiang_demo.SIZE_LARGE,
	}

	marshaler := jsonpb.Marshaler{OrigName:true}
	if b, err := marshaler.MarshalToString(&l); err != nil {
		panic(err)
	} else {
		fmt.Println(b)
	}
}
```

and when i run this code, i get the result:

```
✗ protoc --version
libprotoc 3.6.1
✗ go run main.go
{}
```

following is my dep lock file for all package version:

```
[[projects]]
  digest = "1:1d82405f30f13f12539bc10a480ac0c8e2a0852d95d568af38ee232a3f4e2d1b"
  name = "github.com/golang/protobuf"
  packages = [
    "jsonpb",
    "proto",
    "ptypes/struct",
  ]
  revision = "b5d812f8a3706043e23a9cd5babf2e5423744d30"
  version = "v1.3.1"
```

**Comment by puellanivis** [comment]
Default values are omitted in Javascript.

**Comment by dsnet** [comment]
What @puellanivis said is correct. The JSON serializer omits default values. This behavior is specified by the protobuf<->JSON documentation.

**Comment by stevenwangnarvar** [comment]
Hi @dsnet, but I think the key is `SIZE` is enum, so if I set 
```
	l := io_liqiang_demo.Laptop{
		Size: io_liqiang_demo.SIZE_SMALL,
	}
```
result is:
```
{
"size": "SMALL"
}
```
So I think the correct output is for 
```
	l := io_liqiang_demo.Laptop{
		Size: io_liqiang_demo.SIZE_LARGE,
	}
```
should be 
```
{
"size": "LARGE"
}
```

**Comment by dsnet** [comment]
@stevenwangnarvar I think your describing a different issue than what this issue was originally about. Can you file a new issue with a minimal reproduction?

**Comment by stevenwangnarvar** [comment]
@dsnet, sure I created a new ticket https://github.com/golang/protobuf/issues/918.
