### ISSUE TITLE
[Un]Marshaling partially

### ISSUE THREAD

**Issue by oguzyildiz1991** [golang/protobuf#839]
**Is your feature request related to a problem? Please describe.**
Sometimes I only need to get 1 field of a protobuf object, and I have to Unmarshal the entire thing, an unnecessary latency overhead

**Describe the solution you'd like**
I'd like to optionally specify which fields to unmarshal (like, giving the field numbers, and the unmarshaller would ignore the fields that are not requested)

**Describe alternatives you've considered**
-
**Additional context**
-

**Comment by dsnet** [comment]
Without a major change to the generated API, this can't be supported. If we had an opaque message representation, then we can load contents of a field lazily on demand.

**Comment by oguzyildiz1991** [comment]
Thanks for the response! I didn't mean it as a lazy loading, it's more of an "ignore the non-selected fields and un/marshal everything else now" kind of a method

**Comment by dsnet** [comment]
The `golang/protobuf` project is intended to be a faithful implementation of protocol buffers. Since the ability to select specific fields to unmarshal is not a feature of other implementation (especially the C++ one), it's not a feature we can provide. We do not intend to invent new semantics.
