### ISSUE TITLE
APIv2: encoding/prototext unable to parse message list field w/o field separator

### ISSUE THREAD

**Issue by cybrcodr** [golang/protobuf#842]
Field separator is optional if field value is a message or list of messages.  Current decoder does not handle the latter when field separator is missing --

https://go.googlesource.com/protobuf/+/27c2a76c850826490ae8ae43d46a4d1276b57ceb/internal/encoding/text/decode.go#97

For empty list, internal/encoding/text package does not have enough context whether list is for message type or not.

Rewriting the decoder to token-based approach will solve this issue.

**Comment by puellanivis** [comment]
As the non-JSON text format of protobuf has (intentionally) no defined standard, it would be helpful to understand what is producing your messages with missing field separators, and why you think the field separator is optional in the given cases.

Any “guarantee” of compatibility in non-JSON text formats is really limited to what the individual library generates, i.e. if the Go packages only generate messages with field separators, then it need not accept messages that are missing field separators.

That said, there is a best-effort attempt made to try and ensure that these non-JSON text formats are largely compatible within the various languages. However, as there is no standardization is not a guarantee.

If you need _any_ guarantees about processing protobufs to/from any particular encoding, you must use the officially standardized ones: binary wire-format, or JSON.

**Comment by dsnet** [comment]
> However, as there is no standardization is not a guarantee.

I've been internally pushing at Google to get text format specified and have that specification be open-sourced. There is a draft of the specification written, and at the moment, this behavior is on it.

> Any “guarantee” of compatibility in non-JSON text formats is really limited to what the individual library generates

As much as I dislike the philosophy of "the C++ implementation is the specification", that has unfortunately became the de-facto standard, and the specification being develop functionally specifies of the current C++ implementation does, even if the behavior is utterly strange like in this situation.

> you must use the officially standardized ones: binary wire-format, or JSON.

Even though those are more "standardized", even binary and JSON are ill-specified in a number of areas as Herbie and I had the fun of discovering.

**Comment by puellanivis** [comment]
> There is a draft of the specification written, and at the moment, this behavior is on it.

Cool! The lack of specification has been quite a bit of a complicating factor in discussing any aberrant behavior in the non-JSON text format. Also, confusion from users as to why it sometimes just didn’t interoperate well.

> … the specification being develop functionally specifies of the current C++ implementation does, even if the behavior is utterly strange like in this situation.

So, this is from the C++ implementation (I kind of figured). The C++ behavior always was the de facto standard, and I think widely the assumption was that there was a specification and that C++ was the reference for that specification. 🤷‍♀

If this is something that is expected to be in the specification, then there’s no harm in pushing for it now. Better to be ahead of the ball, than behind it.
