### ISSUE TITLE
go: github.com/golang/lint@v0.0.0-20190313153728-d0100b6bd8b3: parsing go.mod: unexpected module path "golang.org/x/lint"

### ISSUE THREAD

**Issue by pennkao** [golang/protobuf#846]
$ go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Penn\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=F:\go-path
set GOPROXY=https://goproxy.io
set GORACE=
set GOROOT=F:\go\win
set GOTMPDIR=
set GOTOOLDIR=F:\go\win\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=F:\go-project\shippy\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\

go.mod

module shippy
go 1.12

require (
	golang.org/x/crypto v0.0.0-20190426145343-a29dc8fdc734 // indirect
	golang.org/x/lint v0.0.0-20190409202823-959b441ac422 // indirect
	golang.org/x/net v0.0.0-20190501004415-9ce7a6920f09 // indirect
	golang.org/x/sys v0.0.0-20190429190828-d89cdac9e872 // indirect
	golang.org/x/text v0.3.2 // indirect
	golang.org/x/tools v0.0.0-20190501045030-23463209683d // indirect
)

go: finding golang.org/x/tools latest
go: finding golang.org/x/sys latest
go: finding golang.org/x/net latest
go: finding golang.org/x/lint latest
go: finding golang.org/x/sync latest
go: finding golang.org/x/crypto latest
go: finding github.com/micro/go-micro/server latest
go: finding github.com/micro/go-micro/client latest
go: finding github.com/micro/go-plugins/broker/nats latest
go: finding github.com/golang/protobuf/proto latest
go: finding github.com/micro/go-micro/metadata latest
go: finding github.com/labstack/gommon/log latest
go: finding github.com/jinzhu/gorm/dialects/postgres latest
go: finding github.com/micro/go-micro/cmd latest
go: finding gopkg.in/mgo.v2 latest
go: finding github.com/micro/go-plugins/broker latest
go: finding github.com/jinzhu/gorm/dialects latest
go: github.com/golang/lint@v0.0.0-20190313153728-d0100b6bd8b3: parsing go.mod: unexpected module path "golang.org/x/lint"
go: github.com/testcontainers/testcontainer-go@v0.0.2: parsing go.mod: unexpected module path "github.com/testcontainers/testcontainers-go"
go: finding github.com/coreos/go-etcd v2.0.0+incompatible
go: finding github.com/armon/consul-api v0.0.0-20180202201655-eb2c6b5be1b6
go: finding gonum.org/v1/gonum v0.0.0-20190312223110-e28f136e01a8
go: finding github.com/willf/bitset v1.1.10
go: finding github.com/xordataexchange/crypt v0.0.3-0.20170626215501-b2862e3d0a77
go: finding github.com/spf13/cast v1.3.0
go: finding github.com/ugorji/go/codec v0.0.0-20181204163529-d75b2dcb6bc8
go: error loading module requirements

**Comment by dsnet** [comment]
This is almost certainly due to a stale checkout of this repository.

The latest tagged version has absolutely zero dependencies:
https://github.com/golang/protobuf/blob/v1.3.1/go.mod
