### ISSUE TITLE
APIv2: naming of packages under types

### ISSUE THREAD

**Issue by dsnet** [golang/protobuf#849]
Related to #848, but broken out to avoid cluttering the discussion there.

Currently, we have the following packages (package path and name):
* `types/descriptor` with package `descriptor_proto`
* `types/known` with package `known_proto`
* `types/plugin` with package `plugin_proto`

Currently, this:
* Violates the general principle where `path.Base(packagePath) == packageName`
* Registers all of the well-known types, so long as one of them is used. This is contrary to the behavior in other languages.

Ideally, our generated protos should:
* Not violate conventional package path/name style
* Avoid registering all well-known types together
* Have a consistent naming style for all package names. If we break up the well-known types, the [`struct.proto`](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/struct.proto) and [`type.proto`](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/type.proto) have a naming conflict with keywords in Go if we trivially use the `.proto` file name for the Go package name.

As such, I propose the following layout:
* `types/descriptorpb`
* `types/known/anypb`
* `types/known/apipb`
* `types/known/durationpb`
* `types/known/emptypb`
* `types/known/fieldmaskpb`
* `types/known/sourcecontextpb`
* `types/known/structpb`
* `types/known/timestamppb`
* `types/known/typepb`
* `types/known/wrapperspb`
* `types/pluginpb`

The package name is the base of the package path. The name is derived from the `.proto` file name by replacing the `.proto` with `pb` and removing all underscores (e.g., `source_context.proto` -> `sourcecontextbp`).

Alternatively, we could replace `.proto` with `_proto` (e.g., `source_context.proto` -> `source_context_proto`). Since the name is long, people would be expected to rename the import as they likely do today already.

\cc @neild, @cybrcodr

**Comment by cybrcodr** [comment]
I like the proposal.  Breaking up the well-known types into separate Go packages is a good thing.

**Comment by dsnet** [comment]
Fixed by https://go-review.googlesource.com/c/protobuf/+/177380
