### ISSUE TITLE
Unable to Marshal a oneof

### ISSUE THREAD

**Issue by wari** [golang/protobuf#85]
Given the following proto

```protobuf
syntax = "proto3";

package people;

message Identity {
    uint64 message_id = 1;
    string name = 2;
    string email = 3;
    string address = 4;
    string details = 5;
}

message Identities {
    uint64 message_id = 1;
    repeated Identity ids = 2;
}

enum payload_type {
    IDENTITY = 0;
    IDENTITIES = 1;
}

message Incoming {
    uint64 message_id = 1;
    payload_type type = 2;
    oneof payload {
        Identity identity = 3;
        Identities identities = 4;
    }
}
```

And the following code:
``` go
incoming := &people.Incoming{MessageId: counter, Type: people.PayloadType_IDENTITY}

inId := &people.Incoming_Identity{}
id := &people.Identity{}
generateRandomID(i) // Just populates Identity with valid data
inId.Identity = id
incoming.Payload = inId

data, err := proto.Marshal(t)
if err != nil {
	log.Println("Marshalling error", err)
}
```
Marshalling, I get the following error:
```
proto: no encoder for Payload people.isIncoming_Payload [GetProperties]
```
I've probably populated Payload wrongly or something, how to I set this properly?

Thanks

**Comment by dsymonds** [comment]
You'll get a compile-time error if you try to populate Payload incorrectly.

It looks like your version of `github.com/golang/protobuf/proto` is out of date.

**Comment by wari** [comment]
After looking closely at the import statement, i realized that the goimports imported gogo version of proto. Fixed! Thanks @dsymonds

**Comment by awalterschulze** [comment]
Is the gogo version not working?

**Comment by wari** [comment]
@awalterschulze The gogo version has a different way of handling oneof which kind of remove the oneof type. At least that's what I gather from reading the generated output.

**Comment by awalterschulze** [comment]
Do you have the newest version.
It should be pretty much the same as golang/protobuf.

**Comment by wari** [comment]
@awalterschulze you are correct, it looks like they are API compatible, except for `gogoslick` which did not create the `const payloadType_IDENTITY`, instead, it's just `const IDENTITY`

**Comment by awalterschulze** [comment]
Yes that is one of the features of gogoslick it removes the enum prefixes.
I should add more documentation for the vanity binaries.
https://github.com/gogo/protobuf/issues/81
If this is breaking anything please report an issue with gogoprotobuf.
Sorry David for taking over this issue.
