### ISSUE TITLE
APIv2: text marshal API

### ISSUE THREAD

**Issue by neild** [golang/protobuf#850]
The v1 API provides the following functions for text (un)marshaling:

```go
func MarshalText(w io.Writer, pb protoiface.MessageV1) error {}
func MarshalTextString(pb protoiface.MessageV1) string {}
func UnmarshalText(s string, pb protoiface.MessageV1) error {}

func (*TextMarshaler) Marshal(w io.Writer, pb protoiface.MessageV1) error {}
func (*TextMarshaler) Text(pb protoiface.MessageV1) string {}
```

The new API currently contains:

```go
func Marshal(m protoreflect.ProtoMessage) ([]byte, error) {}
func Unmarshal(m protoreflect.ProtoMessage, b []byte) error {}

func (MarshalOptions) Marshal(m protoreflect.ProtoMessage) ([]byte, error) {}
func (UnmarshalOptions) Unmarshal(m protoreflect.ProtoMessage, b []byte) error {}
```

I think there are some places where the ergonomics of the new API could be improved:

* There should be an easy way to convert a message into a string. Compare:

   ```go
   fmt.Println(proto.MarshalTextString(m))
   ```

   ```go
   b, _ := textpb.Marshal(m) // And what do I do if there's an error?
   fmt.Println(string(b))
   ```

* There should be a default indentation level for multi-line output. Currently, the default is compact output, with multi-line output specified by passing an indentation string in via `MarshalOptions`. Since the user is not only allowed but required to choose their own indentation level, this will result in a lot of inconsistent output. I think we should default to multi-line output (which is vastly more readable for messages of any size) with a default indentation level, with compact output opted into via a `Compact` bool on `MarshalOptions`.

* `Unmarshal`'s first parameter is the message to marshal into. While this does follow the usual Go parameter ordering of (destination, source), it is inconsistent with other every other function named `Unmarshal` I can find:
    * [`asn1.Unmarshal`](https://godoc.org/encoding/asn1#Unmarshal)
    * [`json.Unmarshal`](https://godoc.org/encoding/json#Unmarshal)
    * [`xml.Unmarshal`](https://godoc.org/encoding/xml#Unmarshal)
    * [`proto.UnmarshalText`](https://godoc.org/github.com/golang/protobuf/proto#UnmarshalText)

**Comment by dsnet** [comment]
Related: the desire for `fmt.Println(proto.MarshalTextString(m))` is almost certainly because the generated `String` method is compact by default. Should this be multilined?

**Comment by neild** [comment]
Occasions when I've wanted a multiline string have definitely far outnumbered cases when I'd have been unhappy with one.

No idea how much pain changing it would cause.

Note that the removal of `String` from `proto.Message` means that even if we did make the method return multiline output by default, we'd probably still want to have a function that takes a `Message` and returns a `string`.

**Comment by dsnet** [comment]
https://golang.org/cl/177258 switches unmarshal ordering.

**Comment by neild** [comment]
I think the `String` method is a distraction; perhaps we should change it, but I think it's reasonable to want to convert a message to a string using `prototext` rather than relying on the specific message's `String` method. e.g., I should be able to take an old generated message or a message from some other implementation and get text output.

I propose:

```go
package prototext
// MarshalString returns the given proto.Message in textproto format.
func MarshalString(m proto.Message) string {
  b, _ := MarshalOptions{AllowPartial: true}.Marshal(m)
  return string(b)
}
```

Another question is indentation. I feel we should have a default indentation level for multi-line output, to encourage consistency. I propose:

```go
package prototext
type MarshalOptions struct {
  // If Compact is true, messages are formatted on a single line.
  Compact bool

  // If Indent is a non-empty string and Compact is false, entries for a Message are
  // preceded by the indent and trailed by a newline. Indent can only be
  // composed of space or tab characters.
  //
  // If Indent is the empty string and Compact is false, a default indentation is used.
  Indent string
}
```

The `protojson` package also has support for indentation. We could either add a `Compact` bool to `protojson.MarshalOptions` for consistency with `prototext` (indent by default) or leave it as-is for consistency with `encoding/json` (no indentation by default). I have no particular opinion on which is better.

**Comment by puellanivis** [comment]
```
  // If Indent is the empty string and Compact is false, a default indentation is used.
```

I think this sort of thing would be highly unintuitive. It might programmatically be the easiest thing, but its also “clever“, and surprising.

**Comment by neild** [comment]
Do you have an alternate suggestion for how to make indentation the default, with a default indentation level?

We could make the options structs opaque, so that you need to write `opts.SetIndent("  ")` rather than using a composite literal, but that doesn't seem very convenient.

**Comment by puellanivis** [comment]
Indeed, the `json` Marshaller does not have a default indention, but then it is often used as a kind of “wire format”, where machines are digesting the messages, rather than people. But the prototext format is almost always intended for debugging use, and is therefore should be first-class human readable. In that case, a default indention type is much more desirable.

This is like the frustrating problem of proto2 having non-zero defaults… we need someway to track a difference between `it is the zero value because I did not set it, and I want the default` and `it is the zero value because I intentionally want it to be the zero value`.

I think the only way we could really do something “correctly” here is by reworking the whole entire semantics to provide a useful default zero value. And… I just do not even know where we would start going about providing a useful default zero value in this case, except as you have described. And whatever could possibly exist is likely a huge departure away from current semantics that it would have to work entirely different. :confused: 

It might just be that even though this is “clever” and surprising, it might just be the most simple compromise possible.

**Comment by cybrcodr** [comment]
The initial thinking when prototext and protojson MarshalOptions were written was to make these consistent.  However, as mentioned here and in real use cases, compact JSON is preferable by default due to more usages of it as a wire format while multi-line text is preferable by default due to more usages of it for human readability.

I opt for being practical and go with what makes sense for each.  Hence, I agree with @neild's proposal for MarshalOptions above and can make the change.

I'm not quite convinced about the need for MarshalString as I think having String return multi-line output may suffice.

**Comment by cybrcodr** [comment]
While I've sent out https://golang.org/cl/187858 to update prototext per discussion above.  I'm having second thoughts about having the 2 options Compact and Indent as @puellanivis indicated as "surprising".

First off, we seem to agree that the default indentation for prototext and protojson should be different.  protojson should be compact by default and allow user-configured indentation, while prototext should be multi-line by default.

In that respect, perhaps it is ok to not provide a user-configured indentation option for prototext given that V1 does not have that option to begin with.  This would keep the options simpler and no surprises.

**Comment by puellanivis** [comment]
:woman_shrugging: I don’t know if we can definitively say that there would be no use-case for non-default indentation in prototext. We’re not offering it now, but is it something we really need?

I’m probably inclined to agree that we don’t need to provide a compact format, though…

**Comment by dsnet** [comment]
> The initial thinking when prototext and protojson MarshalOptions were written was to make these consistent.

I still stand by the consistency principle. I prefer to see the default behavior of JSON and text marshal to either **both** be indented, or **both** not indented. Hence, I'm not someone who "[agrees] that the default indentation for prototext and protojson should be different".

I agree with @neild that if indentation is desired (whether explicitly or by default), the user should not have to choose exactly what the indent looks like. Personally, I'm fine with @neild's original suggestion in https://github.com/golang/protobuf/issues/850#issuecomment-492383838.

**Comment by neild** [comment]
Summary of my understanding of offline discussion today:

```go
// Convert m to a multi-line text string with default indent.
s = prototext.Format(m)

// Convert m to a single-line text string.
s = prototext.MarshalOptions{Compact: true}.Format(m)

// Convert m to a multi-line text string with non-default indent.
s = prototext.MarshalOptions{Indent: "\t"}.Format(m)
```

And the same for `protojson`.

Consistency in behavior (default multi-line in both cases) seems preferable to different indentation defaults for text/JSON. Most text usage observed in Google prefers multi-line, so that seems like a reasonable default. Multi-line JSON output when you don't need it is mostly harmless.

Not entirely decided is whether there should be an `Indent` field at all; we don't necessarily need to permit configuring the indentation prefix. Perhaps we should leave it out to start with and add it back if it turns out to be necessary. Whether it's there or not, I feel pretty strongly that there needs to be a good default.
