### ISSUE TITLE
process aborted because float exception on ppc64le platfrom 

### ISSUE THREAD

**Issue by huafj** [golang/protobuf#855]
**What version of protobuf and what language are you using?**
Version: 3.6.1 and 3.7.1

**What did you do?**
My python module which import xxx_pb.py. When I call this module through c code, it will cause the process aborted because float point exception. The root cause is google/protobuf/internal/decoder.py contains the following code:
_POS_INF = 1e10000
_NEG_INF = -_POS_INF
_NAN = _POS_INF * 0

The  operation Infinity X zero whill cause invalid operation. And on ppc64le platform, it will terminate the process. 

For example 

#include<Python.h>
#include<fenv.h>
#include <fenv.h>

int main()
{
   Py_Initialize();
   if ( !Py_IsInitialized() ) {
        return -1;
   }
   PyRun_SimpleString("import google.protobuf.internal.decoder");
  feenableexcept(FE_INVALID | FE_DIVBYZERO | FE_OVERFLOW);

}

When I assign float('nan') to _NAN directly, I can avoid this issue.

**Comment by puellanivis** [comment]
I believe you have the wrong protobuf repo. This one is specifically for golang, and does not do anything with python.

**Comment by huafj** [comment]
you know，I just installed protobuf through pip. I also tried protobuf 3.1.0，same issue!

**Comment by puellanivis** [comment]
Again, this repo is specifically for the golang and only the golang protobuffers. You should be addressing your issues with python’s protobufs here: https://github.com/protocolbuffers/protobuf

**Comment by dsnet** [comment]
Closing as unrelated to Go.
