### ISSUE TITLE
I think the XXX_ field is real bad idea,what happen if i remove them from the code

### ISSUE THREAD

**Issue by lvhuat** [golang/protobuf#856]
I'm using the message in the cache and flush them into file/db at some time. it's small in memory and fast when write files.

But not any more after the XXX_ fields were put in generated structs.

```proto
message SmallDecimal {
    bool neg = 1;
    uint64 value = 2;
    int32 exp = 3;
}

message Order {
    uint64 orderId = 1;
    SmallDecimal amount = 2;
    SmallDecimal price = 3;
    uint64 timestamp = 4;
}
```

```golang

type NoXXXSmallDecimal struct {
	neg   bool
	value uint64
	exp   int32
}

type NoXXXOrder struct {
	orderId   uint64
	amount    *NoXXXSmallDecimal
	price     *NoXXXSmallDecimal
	timestamp uint64
}

func main() {
	fmt.Println("Sizeof SmallDecimal", unsafe.Sizeof(SmallDecimal{}))
	fmt.Println("Sizeof Order", unsafe.Sizeof(Order{}))

	fmt.Println("Sizeof NoXXXSmallDecimal", unsafe.Sizeof(NoXXXSmallDecimal{}))
	fmt.Println("Sizeof NoXXXOrder", unsafe.Sizeof(NoXXXOrder{}))
}
```
I have do a lot of things to reduce the copy of memory and the cost of memory.
```cmd
Sizeof SmallDecimal 56
Sizeof Order 64
Sizeof NoXXXSmallDecimal 24
Sizeof NoXXXOrder 32
```

What it would happen  if i remove the XXX_* field by comment [generateInternalStructFields](https://github.com/golang/protobuf/blob/master/protoc-gen-go/generator/generator.go#L2109) in proto-gen-go?

**Comment by dsnet** [comment]
The `XXX_unrecognized` fields are to support unknown fields. If you're using proto3, they were a proto language change added by https://github.com/protocolbuffers/protobuf/issues/272.

I filed two other issues to address the root problem you are hitting: #857, #858
