### ISSUE TITLE
Keys are sorted before map<> values are encoded.

### ISSUE THREAD

**Issue by jcgregorio** [golang/protobuf#86]
Keys are sorted before map<> values are encoded. This is unnecessary since map<> value order is undefined:

  https://developers.google.com/protocol-buffers/docs/proto#maps-features
  https://developers.google.com/protocol-buffers/docs/proto3#maps

The sorting is done here:

  https://github.com/golang/protobuf/blob/master/proto/encode.go#L1119 

I found this because it caused me a performance issue. The proto I was encoding had a map<string, bytes> with 300K entries and the keys are 100 char strings that have long stretches of common prefixes, ie there are large set of keys that only vary in the last 20 chars or so. The sort ended up taking up 40% of the encode time.

**Comment by dsymonds** [comment]
We did this to match the C++ behaviour, just like we write fields in tag order even though the order is technically unspecified. There's room for performance improvements though.

**Comment by awalterschulze** [comment]
Ok I am not complaining about sorting the map keys, but you say it is to match the C++ behaviour, yet here they seem to disagree https://groups.google.com/forum/#!topic/protobuf/7do1mgl-5LM maybe you could help?  Or did I paraphrase incorrectly?

**Comment by dsymonds** [comment]
There was a miscommunication. I got told that map keys should be sorted, but that only applies to the text format. I'll have a change to remove the sorting soon.

**Comment by jcgregorio** [comment]
Thanks!
