### ISSUE TITLE
How add a custom types ?

### ISSUE THREAD

**Issue by danieagle** [golang/protobuf#864]
Hi!
   
  I now need add types as Int (math/big) and
decimal (https://github.com/ericlagergren/decimal) in my protobuff code and 
in future others types, too
  Please, someone can explain how? :-)

  Very very very Thanks in Advance! :-)

  p.s.: I'm a newbee in golang and protobuff :-)

**Comment by dsnet** [comment]
Protocol buffers are intended to be a data interchange format that works well across different programming languages. As such, it provides decent generated types for all languages, but is not great in any one language. Allowing specialized types causes the proto source files to end up being overly geared towards one language or another.
