### ISSUE TITLE
How to generate pb2 go source file

### ISSUE THREAD

**Issue by RaymondReddington** [golang/protobuf#865]
protoc always generates pb3 source file while the syntax is proto2 in .proto file.

the version tag in source file:
const _ = proto.ProtoPackageIsVersion3

**Comment by puellanivis** [comment]
This is not Protobuf 3, this is a a specific version of the `proto` library itself independent of the proto3 or proto2 version. These constants are used to ensure lock-step upgrades of pb generated code and the `proto` library that it depends on.

**Comment by dsnet** [comment]
`ProtoPackageIsVersion3` deals with the version of the Go `proto` package and exists since [v1.3.0](https://github.com/golang/protobuf/releases/tag/v1.3.0)
