### ISSUE TITLE
APIv2: track breaking changes

### ISSUE THREAD

**Issue by dsnet** [golang/protobuf#867]
This is a meta-issue for tracking any breaking changes that occur before the final v2 release. Since v2 is not yet released, we reserve the right to make breaking changes to improve the API to be as good as it can be.

The CL (changelist) that introduces a breaking change will be posted here as a comment. Subscribe to this issue to be notified of breakages. We try to batch multiple breaking changes close together in time to reduce user churn.

**Comment by robbertvanginkel** [comment]
Is there any rough idea of when api-v2 will become stable/available/recommended?

**Comment by dsnet** [comment]
We're aspirationally aiming for GopherCon 2019, which would be the end of July. However, this is aspirational. If the v2 is not where we would like it to be (i.e., incomplete, buggy, etc...), then we will delay. We estimate that the amount of work left is on the order of months, not years.

**Comment by dsnet** [comment]
Breaking changes:
* [CL/182537](https://golang.org/cl/182537): reflect/protoregistry: remove Files.RangeFilesByPath method
* [CL/175987](https://golang.org/cl/175987): reflect/protoreflect: remove bool output for Descriptor.Parent method
* [CL/176942](https://golang.org/cl/176942): reflect/protoreflect: remove FieldDescriptor.{Oneof,Extendee} methods
* [CL/174938](https://golang.org/cl/174938): reflect/protoreflect: remove {Enum,Message}.Type methods
* [CL/182597](https://golang.org/cl/182597): reflect/protoreflect: remove KnownFields and UnknownFields interfaces

**Comment by dsnet** [comment]
Minor change:
* [CL/182638](https://go-review.googlesource.com/c/protobuf/+/182638): reflect/protodesc: use Resolver interface

**Comment by neild** [comment]
Exceedingly minor change:

* [CL/182980](https://golang.org/cl/182980): encoding/proto{json,text}.MarshalOptions.Resolver must also resolve extensions

**Comment by dsnet** [comment]
Minor change:
* [CL/183101](https://go-review.googlesource.com/c/protobuf/+/183101): internal/fileinit: remove package

This only affects generated code; the fix is to regenerate the `.pb.go` files.

**Comment by dsnet** [comment]
Breaking change:
* [CL/183700](https://go-review.googlesource.com/c/protobuf/+/183700): remove Files.Find{Enum,Message,Extension,Service}ByName

**Comment by neild** [comment]
Breaking change:

* [CL/183678](https://go-review.googlesource.com/c/protobuf/+/183678): all: remove protoreflect.Message.Len

**Comment by dsnet** [comment]
Behavior change:
* [CL/184837](https://go-review.googlesource.com/c/protobuf/+/184837): reflect/protodesc: enforce strict validation

This CL enforces that the input file descriptors are well-formed according to the same rules as the C++ `protoc` implementation.

**Comment by kyessenov** [comment]
@dsnet Is there a new estimate on the release date of v2?
We're looking at evaluating replacing golang/protobuf over gogo/protobuf in the context of https://github.com/envoyproxy/data-plane-api (cc @htuch).

**Comment by neild** [comment]
@kyessenov We don't have a solid date yet, although I'm pretty confident in saying "before the end of the year".

**Comment by dsnet** [comment]
Unfortunately we are behind schedule on v2 release. It should occur shortly after [all issues with the "blocks-v2" label are resolved](https://github.com/golang/protobuf/issues?q=is%3Aissue+is%3Aopen+label%3Ablocks-v2). We still hope that it happens within a month or two, but should definitely happen before the end of the year.

One of the ways that we have confidence in the quality of the v2 release is that we have switch most of production Go code at Google to be using the v2 implementation internally. However, this effort is taking longer than expected due to the need to support a variety of legacy and deprecated features. If you have additional questions/comments about the release process for v2, please file another issue.

Since there are a number of people subscribed to this thread, I'm locking this thread so that only updates about breaking changes are posted from here on out.

**Comment by neild** [comment]
* [CL/187857](https://golang.org/cl/187857): reflect/prototype: drop Extension

The rest of the prototype package will probably follow soon.

**Comment by dsnet** [comment]
* [CL/189198](https://go-review.googlesource.com/c/protobuf/+/189198): compiler/protogen, cmd/protoc-gen-go: use alternative comments API

**Comment by neild** [comment]
Breaking changes:

* [CL/189199](https://golang.org/cl/189199): all: refactor extensions, add proto.GetExtension etc.

This CL changes the `protoreflect.{Message,Enum,Extension}`Type types to no longer implement the corresponding `Descriptor` interface. (They still have a has-a relationship with the descriptor.)

Accessing extension fields in a `protoreflect.Message` now requires a `protoreflect.ExtensionTypeDescriptor` (which implements `FieldDescriptor`) instead of an `ExtensionType` (which doesn't any more). `ExtensionType.Descriptor` returns an `ExtensionTypeDescriptor`.

* [CL/189340](https://golang.org/cl/c/189340): all: drop reflect/prototype package

The `prototype` package is removed as unnecessary.

**Comment by neild** [comment]
Breaking change:

* [CL/189563](https://go-review.googlesource.com/c/protobuf/+/189563): all: unify protoV1.ExtensionDesc and proto.ExtensionType
* [CL/189564](https://go-review.googlesource.com/c/protobuf/+/189564): internal/impl: clean up obsolete ExtensionInfo fields/funcs

The `protoiface.ExtensionDescV1` type is removed. (And lots of other internal refactoring, but I believe that's the only breaking API change.) This is unlikely to affect anyone.

**Comment by dsnet** [comment]
Minor breaking change:
* [CL/191039](https://golang.org/cl/191039): compiler/protogen: export Plugin.FilesByPath

**Comment by neild** [comment]
Breaking change:

* [CL/193598](https://go-review.googlesource.com/c/protobuf/+/193598): remove NewMessage methods

Superseded by the more general-purpose Message.NewField, List.NewElement, and Map.NewValue.

**Comment by neild** [comment]
Breaking change:

* [CL/199060](https://go-review.googlesource.com/c/protobuf/+/199060): remove {Enum,Message,Extension}Type.GoType methods

Removed to simplify the interface, and because there are now better ways to do just about everything they were used for.

**Comment by neild** [comment]
Minor breaking change:

* [CL/204897](https://go-review.googlesource.com/c/protobuf/+/204897): remove nullability from repeated extension fields

`m.Has(extensionTypeDescriptor)` will now return false for a zero-length repeated extension field.

**Comment by neild** [comment]
Breaking change:

* [CL/206017](https://go-review.googlesource.com/c/protobuf/+/206017): remove deprecated APIs

The `(*Files).Register` and `(*Types).Register` functions in the `protoregistry` package have been replaced by type-safe `Register{File,Enum,Message,Extension}` methods.

The `protoregistry.NewFiles` and `protoregistry.NewTypes` functions are gone. (Just call `Register...`)

The `protoregistry.Type` type is removed (nothing references it any more).

**Comment by dsnet** [comment]
Minor breaking change:
* [CL/207077](https://golang.org/cl/207077): testing/protocmp: switch Enum.Number to be a method

**Comment by neild** [comment]
* [CL/209018](https://go-review.googlesource.com/c/protobuf/+/209018/2): reflect/protoreflect: add {Message,List,Map}.IsValid
* [CL/209019](https://go-review.googlesource.com/c/protobuf/+/209019/3): all: fix reflection behavior for empty lists and maps

Minor addition to some protoreflect types, only affecting implementations of those types.

Brought reflection behavior for empty lists and maps in line with documentation. Technically not a breaking change (just doing what the documentation said!), but it would have been easy to depend on the previous behavior by accident.

**Comment by neild** [comment]
* [CL/215718](https://go-review.googlesource.com/c/protobuf/+/215718)
* [CL/215719](https://go-review.googlesource.com/c/protobuf/+/215719)

Changes to the fast-path `ProtoUnmarshal` method: It moves into the `protoreflect.Message` interface, and the method signature changes a bit.

Performance improvement (avoids an interface->interface type conversion, which is expensive) and future-proofing.

**Comment by neild** [comment]
* [CL/219145](https://golang.org/cl/219145): proto: remove shallow merge support, and MergeOptions

Shallow merges were well-defined, but we're debating whether that definition is useful. Dropped support for shallow merges for now, since this isn't a v1 feature we need to preserve.

**Comment by neild** [comment]
* [CL/220117](https://golang.org/cl/220117): reflect/protoreflect: add List.AppendMutable and Map.Mutable

Convenience methods on protoreflect's `List` and `Map` types.

**Comment by neild** [comment]
* [CL/219505](https://golang.org/cl/219505): all: fast-path method refactoring

One last change to the fast-path method signatures, for consistency and future expansion.

**Comment by neild** [comment]
APIv2 is released. No more breaking changes!
