### ISSUE TITLE
non-intuitive output directory

### ISSUE THREAD

**Issue by aryzing** [golang/protobuf#872]
**What version of protobuf and what language are you using?**
Version: libprotoc 3.8.0, Go

**What did you do?**
protoc api/service.proto --go_out=plugins=grpc:api

**What did you expect to see?**
For the output to be in the destination folder `api` (as specified by the args to --go_out)

**What did you see instead?**
The output was put inside `api/api` directory (it created a directory named `api` inside `api`. To get the desired results, I need to specify my target directory as `..` which is totally counter-intuitive.

I'm aware of the `paths` flag, and i was looking for a `paths=cwd` or similar where I can actually specify the output directory based on where I'm running the command from.

**Comment by neild** [comment]
`protoc api/service.proto --go_out=plugins=grpc,paths=source_relative:.` probably does what you want (puts the output in `api/service.pb.go`).

The `paths=source_relative` option causes the output for `path/to/some.proto` to be `path/to/some.pb.go`. Setting the output directory to `.` (the current directory) will cause every `.pb.go` file to be generated alongside the corresponding `.proto` file.
