### ISSUE TITLE
Generated go import not working

### ISSUE THREAD

**Issue by jakobmaier** [golang/protobuf#88]
When I generate the go file out of an *.proto definition, the file contains the import

`import proto "code.google.com/p/goprotobuf/proto"` which can not be resolved / does not exist.

I think the import should be `import proto "github.com/golang/protobuf/proto"` instead (which is working correctly after `go get -u github.com/golang/protobuf/proto` as described in the readme).

**Comment by dsymonds** [comment]
Sounds like you have an old version of `protoc-gen-go` installed. See the README for installation instructions.
