### ISSUE TITLE
Server method arg names Feature.

### ISSUE THREAD

**Issue by clearcodecn** [golang/protobuf#884]
**Is your feature request related to a problem? Please describe.**
I want my ide auto complete the code implement the server interfaces.
but no method arg names in the code, I need to add them every time.

**Describe the solution you'd like**
when generate the code add the method args names. 

eg:
```
type FooServer interface {
	GetFoo(context.Context, *Request) (*Resp, error)
}
```
My IDE generate this code:
```
type myServer {}

func(m *myServer) GetFoo(context.Context, *Request) (*Resp, error){
}

```
and what I need is this:

```
type myServer {}

func(m *myServer) GetFoo(ctx context.Context, in *Request) (*Resp, error){
}

```

and if the sign have the arg names in there interface definition, IDE will auto complete them.

That can help me save many time.

**Comment by dsnet** [comment]
Can you be more specific about what you would like us to do? Is there something actionable on our end? This seems more like an issue with the IDE auto-completion implementation than with `golang/protobuf` specifically.

**Comment by clearcodecn** [comment]
![x](https://user-images.githubusercontent.com/34591322/60380613-f9413a80-9a7a-11e9-8abf-a8900dd05199.gif)

Hope to add arg names to method.

**Comment by dsnet** [comment]
Oh, I see. Your auto-completion tool attempts to derive the variable name from the method in the interface.

I'm going to close this as infeasible. Fundamentally, `protoc-gen-go` has no additional information that your auto-completion tool doesn't have already.

The very same problem that your auto-completion tool has is the same problem that we have. When your autocompletion tool sees an interface method without variable names, it either has to:
* Not emit them (which is apparently what it does now).
* Choose something sort of reasonable from the type. This is imperfect and won't satisfy all cases.

We have the exact same problem in `protoc-gen-go`. When we try to generate the interface methods, we have no idea what to name the variable, so we either:
* Don't emit them (which is what we do).
* Choose something sort of reasonable from the type (which will be imperfect).

`protoc-gen-go` is in the business of trying to be much more exact and trying to do less guess work. It seems like the wrong place to make this change. On the other hand, an auto-completion tool by its nature is fuzzy, and seems to be a more appropriate place to attempt to derive a variable name.

**Comment by clearcodecn** [comment]
as you generate the Client interface with arg names, why can't generate the server?

```
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
}

```
