### ISSUE TITLE
APIv2: decide reset behavior of unmarshal

### ISSUE THREAD

**Issue by dsnet** [golang/protobuf#890]
There are 3 unmarshal functions:
* `proto.Unmarshal`
* `encoding/protojson.Unmarshal`
* `encoding/prototext.Unmarshal`

Currently, `proto.Unmarshal` does not reset the message when unmarshaling, while the later 2 do. I believe these should be consistent.

If the message is not reset, then there needs to be well-defined merge semantics for the serialization. Such semantics exist for wire and text serialization. However, JSON lacks any defined merge semantics and we should not invent any.

Given that JSON has no merge semantics, it seems to me that all 3 `Unmarshal` functions should default to reseting the message (to be consistent within our module). To provide merge-semantics, we should provide a `AvoidReset` option for wire and text unmarshaling.

\cc @neild @cybrcodr

**Comment by cybrcodr** [comment]
V1 text unmarshaling does reset the message, while interestingly V1 JSON unmarshaling does not.

Having consistency in V2 would be nice, and I like your suggestion.

**Comment by dsnet** [comment]
Something to investigate: The C++ [`JsonStringToMessage`](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.util.json_util#JsonStringToMessage.details) function takes in a `*Message`. Investigate whether they clear this message or merge into it. If it merges, then there is existing precedence of merge-semantics in JSON.

**Comment by cybrcodr** [comment]
On head, [JsonStringToMessage source](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/util/json_util.cc#L259) shows it calls into `JsonToBinaryString` which constructs a serialized binary and then calls `Message::ParseFromString` which resets the message.

**Comment by neild** [comment]
Not resetting by default has the downside of being a change from v1 and not being entirely obvious. (C++/Java put "Merge" in the name of the non-resetting functions, which makes it very clear that they preserve existing data in the message.) I think this makes me lean slightly toward reset-by-default as being the best approach.

Defaulting to the better performing version is appealing, though.

**Comment by dsnet** [comment]
> Not resetting by default has the downside of being a change from v1

Another downside is how a migration tool would work to make a semantically equivalent transform from v1 to v2.

If the tool sees:
```go
protoV1.Unmarshal(b, m)
```
It would have to re-write it to:
```go
protoV2.Reset(m)
protoV2.Unmarshal(b, m)
```
unless it can prove m is empty. A cursory glance over code at Google shows that a majority of call-sites have something like:
```go
var m foopb.MyMessage
err := proto.Unmarshal(b, &m)
```
or
```go
m := new(foopb.MyMessage)
err := proto.Unmarshal(b, &m)
```
in which case, the logic to prove emptiness may be fairly easy for this common case.

**Comment by cybrcodr** [comment]
The original posted suggestion by @dsnet does provide a solution for v1 wrapping v2 via an option for binary and text unmarshaling, i.e. making the default for all v2 APIs consistent while having the v1 wrapper use the option to preserve v1 compatibility in its API.  JSON unmarshaling can implement such option at later point when a spec is defined.

I would suggest a different option name though, say `Merge` or `AllowMerge` or something.

When you mentioned that there's an existing merge semantic for text proto serialization, I take it you meant whatever the C++ lib does.

**Comment by neild** [comment]
I'm going through Google code to clean up uses of `RequiredNotSetError`, and one thing which strikes me is that almost every call to `Unmarshal` really should be `UnmarshalMerge`. I'm sprinkling in `Merge: true` as I do this cleanup, but it seems clear that the vast majority of users going forward are going to get a reset that they don't really need.

Perhaps this is irrelevant; it adds a minor performance cost to unmarshal operations, but that's it.

But I think we should consider one last time what we want for a default. The arguments in favor of reset-by-default were, I believe:

1. Easier automatic rewrites from APIv1 to APIv2.
1. `protojson` has no merge semantics.

We can fix the automatic rewrite problem by adding a `Reset` field to the options; then an automatic v1->v2 rewrite becomes:

```go
err := proto.Unmarshal(b, m) // old
```

```go
err := (proto.UnmarshalOptions{Reset: true}).(b, m) // new
```

The new version is more verbose, but that's okay--it encourages someone to go remove the `Reset: true` if they don't want it.

The lack of JSON merge semantics could be addressed by returning an error if a merge would be required, as suggested by @dsnet. For efficiency, we can probably just consider fields that are set in the JSON. That's a form of merge semantics, but it seems like a harmless one.

Or perhaps we should stick with what we have as good enough. Most people won't care about the performance cost, and adding `Merge: true` to a few extreme hot-path functions (RPC packages, etc.) will probably be enough.

**Comment by puellanivis** [comment]
I don’t know that having `Merge: true` is so bad. Similar to having it alternatively `Reset: true` it might just encourage people to actually think about if they really need the other functionality or not.

Make the common case simple, and the rare case hard.

**Comment by neild** [comment]
It makes me a bit sad, because most `Unmarshal` calls are going to be a little bit less efficient than they should be, but sticking with the current semantics seems like the best option. The only downside is a small performance cost, avoidable by setting `Merge: true`.
