### ISSUE TITLE
jsonpb: allow invalid enums to be unmarshalled

### ISSUE THREAD

**Issue by marwan-at-work** [golang/protobuf#893]
JSONPB allows a JSON string to be unmarshalled into a proto struct. However, the JSON string cannot enforce that the enum string will always be correct. Bad user input is always expected. 

For example, for the following enum proto declaration: 

```proto
message Input {
  TrafficLight light = 1;
} 

enum TrafficLight {
  UNKNOWN = 0;
  RED = 1;
  YELLOW = 2;
  GREEN = 3;
}
```

The user can send a json that looks like this: 

```
{ "light": "purple" } 
```

If we used `jsonpb.Unmarshaler{}` to process the above json, we would get an error saying that "purple" is not a known enum. That default behavior sounds fine, but a lot of the times, we want to gracefully handle that type of error and return it to the client. 

Currently, there's no way to gracefully handle a user-input error [here](https://github.com/golang/protobuf/blob/master/jsonpb/jsonpb.go#L899)

One solution is to return an error that can be programmatically asserted. However, this means that the unmarshalling could be interrupted half way through and that the struct is not fully processed. 

Therefore, I think the Unmarshaler struct should take `AllowInvalidEnums` boolean as an option so that if there's bad user input, the unmarshaller would just set the default value of `in32` and continue processing. 

This should be a backwards-compatible change since the default remains the same. 

One thing that's worth noting is that if the JSON did not have a string representation of the enum such as ` { "light": 33983 } `, then the Unmarshaler does not care about validating the enum actually exists.

**Comment by dsnet** [comment]
The `golang/protobuf` project is intended to be a faithful implementation of protocol buffers and does not intend to invent new semantics not present in other implementations. The [C++ JSON parser](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.util.json_util#JsonParseOptions) provides no such feature, so we cannot accept this change.

If you believe this is an important feature, you should petition for it at the main protobuf project at https://github.com/protocolbuffers/protobuf/issues

**Comment by marwan-at-work** [comment]
@dsnet done [here](https://github.com/protocolbuffers/protobuf/issues/6355) -- thanks!
