### ISSUE TITLE
reflect/protoreflect: add methods for looking up source locations

### ISSUE THREAD

**Issue by dsnet** [golang/protobuf#899]
A common operation when dealing with `google.protobuf.SourceCodeInfo` is to [look up a source location by the path](https://github.com/protocolbuffers/protobuf/blob/f2cfe2c834a522ec553891451f7725c79bb57b09/src/google/protobuf/descriptor.proto#L799). In a vast majority of situations, there is only one source location for a given path. However, it is possible that a single path maps to multiple source locations. What would the API look like to handle that situation?

[CL/183157](https://go-review.googlesource.com/c/protobuf/+/183157) originally attempted to add convenience methods for looking up by path. The CL contains discussions about some edge cases with the original API design. As a result, I submitted the CL without any convenience methods. This issue tracks whether any should be added and what exactly the API should look like.

The `protoreflect.SourceLocations` has a `doNotImplement` marker embedded in it, so it prevents any casual implementations of the interface. This provides us the flexibility to adding methods to it in the future.

**Comment by jhump** [comment]
I have started work on migrating my `protoreflect` to use APIv2. I can basically drop two packages entirely (`desc` and `dynamic`, replaced by `protoreflect` and `dynamicpb` in APIv2), but I've got a lot of other functionality that would be great if it worked with APIv2.

I'm now realizing that this API is sorely missed. Some of the other functionality I had took advantage of the fact that a `desc.Descriptor` provided a source location for the descriptor.

So I've written my own lookups, that take a `Descriptor` and return a `SourceLocation` but feel that these would be super-helpful in the core library.

Thinking about the API, I believe what you originally proposed is right, except that `ByPath` should return a slice of matching locations:

```go
type SourceLocations interface {
	// Len reports the number of source locations in the proto file.
	Len() int
	// Get returns the ith SourceLocation. It panics if out of bounds.
	Get(i int) SourceLocation

	// ByDescriptor returns the SourceLocation corresponding to
	// d. If there is more than one SourceLocation for the path that
	// corresponds to d, only the first is returned.
	ByDescriptor(d Descriptor) SourceLocation

	// ByPath returns all SourceLocations for the given path.
	ByPath(path ...int32) []SourceLocation
}
```

WDYT?

**Comment by dsnet** [comment]
In your proposed API, why does `ByDescriptor` operate based on a policy of "first occurrence wins", while `ByPath` operates on a policy of returning all occurrences?

**Comment by jhump** [comment]
Because a descriptor element is generally expected to have exactly one source location. But some of the intermediate paths contain multiple. For example the path prefix that corresponds to the `messages` field of the File Descriptor will have multiple locations, one for each message. But the path to a _particular message_ (e.g. corresponds to the `messages` field _plus_ an index) will have only one.

**Comment by dsnet** [comment]
> Because a descriptor element is generally expected to have exactly one source location.

Under what circumstance is that not true?

For:
```go
// ByPath returns all SourceLocations for the given path.
ByPath(path ...int32) []SourceLocation
```
Is this a copy or a reference to some internally stored set of source locations?

**Comment by jhump** [comment]
> Under what circumstance is that not true?

For actual descriptors, I know of none, at least none in practice emitted by protoc. Perhaps it's a question to the core protobuf team? It would be nice if the doc for the [SourceCodeInfo](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/descriptor.proto#L754) type could be made more clear and more specific on the matter.

**Comment by jhump** [comment]
> Is this a copy or a reference to some internally stored set of source locations?

Good question. I guess it would need to be a copy or it would need to be something other than a slice to prevent mutations.

**Comment by dsnet** [comment]
Thus far, the data structures in the `protoreflect` package have gone to some lengths to ensure an immutable API, it would be a bit inconsistent to leak mutability here. Between the options of copying the slice, or returning a reference, I'd prefer copying. However, that obviously has performance disadvantages.

An alternative API could be something like this:
```go
type SourceLocations interface {
    ...

    // ByPath returns the SourceLocation for the given path.
    // If multiple SourceLocation exist for the same path,
    // then SourceLocation.Next index can be used to identify the
    // index of the next SourceLocation.
    ByPath(path SourcePath) SourceLocation
}

type SourceLocation struct {
    ...

    // Next returns the index of the next SourceLocation with the same Path,
    // otherwise it is zero.
    Next int
}
```

Advantages:

* Preserves immutability
* Optimizes for the use-cases when there is generally only one `SourceLocation` for the given path.

Disadvantages:
* It's functionally makes all the SourceLocations a linked-list, which is clunkier to work with than a `[]SourceLocation` for the case where someone cares about multiple source locations.

**Comment by jhump** [comment]
@dsnet, I like that approach! But it made me think of another. I think there is advantage in not having to add a `Next` attribute to each location:

```go
ByDescriptor(d Descriptor) (SourceLocation, index int)
ByPath(path ...int32) (loc SourceLocation, index int)
```

As long as locations for the same path are contiguous, then callers could use the returned index to find fetch entries and then examine whether they are for the same path or not. Like your approach, this also makes them more consistent with one another and optimizes for the case that someone is interested in only the first location for a path.

Admittedly, a caller that wants to iterate all locations for a path is more verbose and clunky than your code example.

```go
loc, index := sources.ByPath(path)
for index >= 0 {
    fmt.Println(loc)
    index++
    if index >= sources.Len() {
        break
    }
    loc = sources.Get(index)
    // no std lib function for this; must use open-source lib or write it (trivial)
    if !slices.Int32sEqual(loc.Path, path) {
        break
    }
}
```

Anyhow, I do like your idea. This is just riffing along similar lines as an alternate, to see what you think.

**Comment by dsnet** [comment]
It doesn't seem like a significant increase in API surface to add a `Next` field to `SourceLocation`. The fact that there's no easy want to compare a `[]int32` does make returning the index alone quite complicated.

At the moment, I like the `SourceLocation.Next` approach the most of all the options discussed. I'm open to other ideas.

Did you want to implement this or me?

**Comment by jhump** [comment]
> Did you want to implement this or me?

I appreciate the question. I'm being pulled in a lot of directions lately, so I won't likely get to this anytime soon. But I also suspect it's not a high priority for you or your team. So perhaps I'll get to it first. Having said that though, if time goes by and you don't see a PR, it's fine to assume I won't get to it.

**Comment by dsnet** [comment]
I started some work on this: https://golang.org/cl/238000

**Comment by puellanivis** [comment]
Spit-balling an idea, could `SourceLocation` be able to implement such that it is basically an iterator pattern:
```
paths := source.ByPath(path)
for paths.Next() {
  loc := paths.Location()
  // do stuff with loc.
}
```

This seems like it would make the single-path case much harder, but in that case, maybe a `paths.First()` function?

**Comment by dsnet** [comment]
Fixed with https://go-review.googlesource.com/c/protobuf/+/238000
