### ISSUE TITLE
APIv2: reflect/prototype: decide representation of repeated fields in Extension.GoType

### ISSUE THREAD

**Issue by dsnet** [golang/protobuf#901]
The documented representation for a [repeated extension is a `*[]T`](https://github.com/golang/protobuf/blob/74615a3960987b289525a30e98dec5800c11db16/reflect/prototype/type.go#L170) instead of `[]T`. This is done so that the interface{} representation of a repeated field can implemented the full feature set of a `protoreflect.List`.

However, a `*[]T` is cumbersome to work with. Consider switching this to be `[]T` instead.

**Comment by neild** [comment]
https://golang.org/cl/192458 changes this to `[]T`. Many yaks were shaved to bring us this change.
