### ISSUE TITLE
google.golang.org/grpc: move protoc-gen-go-grpc into grpc module

### ISSUE THREAD

**Issue by dsnet** [golang/protobuf#903]
We intend to hand off ownership of `protoc-gen-go-grpc` to the `google.golang.org/grpc` project. This issue tracks coordination between `google.golang.org/protobuf` and `google.golang.org/grpc` to accomplish this.

**Comment by dsnet** [comment]
Note to self: we need to port the unimplemented server types to the new implementation.

**Comment by dsnet** [comment]
This still needs to happen, but probably after the first rc1 release.

**Comment by dsnet** [comment]
The logic has been moved to be an internal package of v1. Moving to grpc can happen shortly after but doesnt block release.

**Comment by pjediny** [comment]
Did I miss this in the release notes? I wanted to try new v2 protobuf implementation today, but cannot because of the missing `protoc-gen-go-grpc`. Is there any ETA for the generator in the `google.golang.org/grpc` module?

**Comment by neild** [comment]
Adding a generator to the gRPC module is in progress; for now, you can use `github.com/golang/protobuf/protoc-gen-go` at version `v1.4.0-rc.2` or later, which includes an integrated version of the gRPC generator as before.

**Comment by dsnet** [comment]
The current error message produced by [`protoc-gen-go` is unhelpful for users](https://github.com/golang/protobuf/blob/e358d430e7ff8437491e82ab41e4665400644c9f/cmd/protoc-gen-go/main.go#L39) since `protoc-gen-go-grpc` doesn't exist yet.

We should update that message to point to the updated gRPC documentation when it's ready.

\cc @merovius

**Comment by dsnet** [comment]
Done with https://github.com/grpc/grpc-go/pull/3453
