### ISSUE TITLE
google.golang.org/genproto: move google.protobuf.* types into protobuf module

### ISSUE THREAD

**Issue by dsnet** [golang/protobuf#904]
The `google.golang.org/protobuf` project is taking ownership of all well-known types. However, some of them are currently owned by `google.golang.org/genproto` and will need to be moved through the use of type aliases. This issue tracks the release coordination between the two projects.

**Comment by dsnet** [comment]
This still needs to happen, but probably after the first rc1 release.

**Comment by dsnet** [comment]
To ensure users use a sufficient new version of `genproto` once fieldmask is moved over we need to do one of the following:
* Have a dependency on `genproto`. This is unfortunately, because it means that the transitive tree of `genproto` dependencies become our dependencies. :(
* Add a hack to `protoregistry` to check for duplicate registrations of fieldmask. If so, we panic at init-time with a warning to users to upgrade to a newer version of `genproto`.

**Comment by puellanivis** [comment]
> If so, we panic at init-time with a warning to users to upgrade to a newer version of genproto.

:grimacing: what if someone is depending upon a `.pb.go` file that they did not or cannot compile?

**Comment by neild** [comment]
We've removed the packages which conflict with genproto from the current repo. The only one which we were using was `field_mask.proto`, and it was only used in tests. We'd like to change the canonical location of these packages, but it doesn't need to block the release.

**Comment by dsnet** [comment]
Fixed with https://github.com/googleapis/go-genproto/commit/cb27e3aa201319f013ddb1872c3111662191a225
