### ISSUE TITLE
ClientConn.Target() not found

### ISSUE THREAD

**Issue by Cjen1** [golang/protobuf#910]
**What version of protobuf and what language are you using?**
v 1.14.0 and go

**What did you do?**
I'm using the etcd clientv3 package and to get the target of a request I am using:
`client.ActiveConnection.Target()`

**What did you expect to see?**
Compiling correctly

**What did you see instead?**
`client.ActiveConnection.Target undefined (type func() *grpc.ClientConn has no field or method Target`

**Anything else we should know about your project / environment?**
Looking at my local `/go/src/go.etcd.io/etcd/vendor/google.golang.org/grpc/clientconn.go` it has the method available.

**Comment by dsnet** [comment]
This project is for Go protobufs. You probably want to file this issue over at https://github.com/grpc/grpc-go/issues
