### ISSUE TITLE
Repeat messages with different types

### ISSUE THREAD

**Issue by alihalabyah** [golang/protobuf#917]
I have a case in which I need to repeat messages with different types as below:

```
message StringRoutingParam {
  string key = 1;
  string value = 2;
}

message NumberRoutingParam {
  string key = 1;
  float value = 2;
}

message BoolRoutingParam {
  string key = 1;
  bool value = 2;
}
```

The reason I want it this way is because I want a proper JSON in which the boolean appears as a boolean not as a string, same goes to numbers.

Any suggestions?

**Comment by cybrcodr** [comment]
Is it ok for the field name to be different for each type?

```
message RoutingParam {
    string key = 1;
    oneof value {
        string string_value = 2;
        float float_value = 3;
        bool bool_value = 4;
    }
}
```

**Comment by dsnet** [comment]
This question more so about the protobuf type system rather than the Go implementation of it. @cybrcodr's suggestion is probably the closest analogy to what you want in protobuf. If you have further question, I recommend sending them to https://groups.google.com/forum/#!forum/protobuf.
