### ISSUE TITLE
proto: can't skip unknown wire type 4

### ISSUE THREAD

**Issue by Qinsam** [golang/protobuf#919]
protoc 2.4.1  
golang/protobuf/proto 1.3.2

I serialize a message and write it to redis with c++,
then I read it from redis and Unmarshal it with go, it's create an error "proto: can't skip unknown wire type 4"

I make sure that the proto file is same.

If marshal it with go ,unmarshal is success.

**Comment by dsnet** [comment]
Without code that we can run as a reproduction, there's nothing much we can do to help.

**Comment by Qinsam** [comment]
> 
> 
> Without code that we can run as a reproduction, there's not much we can do to help.

The problem has been solved.

**Comment by dselans** [comment]
Running into the same issue. @Qinsam what was the fix?
