### ISSUE TITLE
self describing messages or polymorphic messages

### ISSUE THREAD

**Issue by acornejo** [golang/protobuf#92]
Have a server that will receive one of a few (30+) different messages (each with very different set of fields) from a client.

Based on each message it will perform some state affection operations and issue a series of messages back to the client.

Planned to use the extension feature of protobuf, but haven't found any example code in go to do it.

The now semi canonical Cat & Dog example is:

```protobuf
package zoo;

message Animal {
  extensions 100 to max;

  enum Type {
    Cat = 1;
    Dog = 2;
  }

  required Type type = 1;
}

message Cat {
  extend Animal {
    required Cat animal = 100; // Unique Animal extension number
  }

  // These fields can use the full number range.
  optional bool declawed = 1;
}

message Dog {
  extend Animal {
    required Dog animal = 101; // Unique Animal extension number
  }

  // These fields can use the full number range.
  optional uint32 bones_buried = 1;
}
```

So now the question is, if I receive a Buffer, and I know that it contains either a Cat or Dog message, how would I go about getting a Cat or Dog struct as appropriate?

Ideally it would be something like (pseudo code)

```go
animal := &zoo.Animal{}
err = proto.Unmarshal(data, animal)

if (animal.GetType() == animal.Cat)
   cat := animal.extension[zoo.Cat.animal]
   // do stuff with cat
else if (animal.GetType() == animal.Dog)
   dog := animal.extension[zoo.Dog.animal]
   // do stuff with dog
```

Unfortunately the above doesn't really work, so what to do?

**Comment by dsymonds** [comment]
Protocol buffers are not a self-describing serialisation scheme. You need to signal the type somehow independently.

**Comment by acornejo** [comment]
I think you misinterpreted my question. I am in search for how to use goprotobuf for a polymorphic use case (using protobuf extensions).

There are examples on how to do this for the C++, java and python bindings, but no example on how to do it with go (and the code generated for each target is different enough that the obvious things don't work)

**Comment by dsymonds** [comment]
So for a given `Animal` you wish to fetch a given extension? The proto package (see https://godoc.org/github.com/golang/protobuf/proto) has a `GetExtension` function for this.
