### ISSUE TITLE
APIv2: Handle native time.Time in serialized structs

### ISSUE THREAD

**Issue by tandr** [golang/protobuf#921]
**Is your feature request related to a problem? Please describe.**
Looking at the https://golang.org/cl/187857 I see handling of regular types, but not the time.Time which I used very often. If I understood the intent correctly, it should allow to handle "direct" structs with proto serialization

**Describe the solution you'd like**
Extend default registration of types with time.Time (and maybe time.Duration)?

**Comment by dsnet** [comment]
Duplicate of #414
