### ISSUE TITLE
Specific checked out version of protobuf package requires merging

### ISSUE THREAD

**Issue by niketagrawal** [golang/protobuf#923]
To solve the issue in https://github.com/golang/protobuf/issues/763 I went ahead and installed a specific version of protoc-gen-go using the following steps directly quoting as mentioned in https://github.com/golang/protobuf

1. GIT_TAG="v1.2.0" # change as needed
2. go get -d -u github.com/golang/protobuf/protoc-gen-go
3. git -C "$(go env GOPATH)"/src/github.com/golang/protobuf checkout $GIT_TAG
4. go install github.com/golang/protobuf/protoc-gen-go

I could solve the issue after following these steps but the checkout process in step 3 is interrupting setup of another application.checked out in $GOPATH/src/github.com/docker/ 

Below is the error that is noticed while trying to setup the new application as mentioned above. The error points to the protobuf repository that I checked out earlier.

```
 $GOPATH/src/github.com/golang/protobuf; git pull --ff-only
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

package github.com/golang/protobuf/protoc-gen-go/descriptor: exit status 1
direct.mk:40: recipe for target 'setup' failed
make: *** [setup] Error 1
```

The git status of the culprit repository as pointed by the error above shows that a particular commit has been checked out and it is not on a branch indeed
```
:~/$GOPATH/src/github.com/golang/protobuf/$ git status
HEAD detached at v1.3.0
nothing to commit, working tree clean
```

To fix this should I execute git pull on the $GOPATH/src/github.com/golang/protobuf/ repository? Will that replace the existing v1.3.0 version (which solved https://github.com/golang/protobuf/issues/763) and open the issue again? 
If git pull is the solution, which option should I use? git pull origin <HEAD, api-v1, api-v2, dev, fix-race or master> ?

**Comment by dsnet** [comment]
I'm not quite sure what this is asking, so I'm unsure how to help. It seems that you're running more into `git` troubles than anything protobuf specific.

> HEAD, api-v1, api-v2, dev, fix-race or master

You should be using the `master` branch. All tags are made from that.
