### ISSUE TITLE
APIv2: Roadmap

### ISSUE THREAD

**Issue by ronnylt** [golang/protobuf#930]
It would be great to know in which stage of the APIv2 migration plan we are according to [Go Protocol Buffer API Improvements](https://goo.gl/wwiPVx)

What users can do at this point in order to help with testing and validation?

**Comment by dsnet** [comment]
You can follow all of the [`blocks-v2` label](https://github.com/golang/protobuf/milestone/2). When they are all gone, the release will be soon afterwards.
