### ISSUE TITLE
APIv2: consider removing GoType from protoreflect

### ISSUE THREAD

**Issue by neild** [golang/protobuf#938]
Internally, we use the `GoType` method of types in `protoreflect` in only three places in the `impl` package. From a cursory inspection, I think all of these can be removed. We should consider dropping the `GoType` method.

`GoType` is arguably not possible to use correctly. Messages created by the `dynamicpb` message package all have the same Go type, for example; the assumption that you can create a new, empty message with `reflect.Zero(mt.GoType())` (as seen in one place) is not a sound one.

If we do remove `GoType`, we might want to add a `Zero` method to `MessageType`, similar to the existing one on `ExtensionType`.

**Comment by dsnet** [comment]
If we remove `GoType`, then I feel even more strongly that #905 needs to provide type check functions for both `interface{}` and for `protoreflect.Value`.

Looking over all my pending CLs, I do actually use `GoType` in a few places for v1 to wrap v2. However, all of them can be migrated to simply allocate a new value and then call `reflect.TypeOf` on the result. There is a slight performance hit, but whatever. I can cache the result.
