### ISSUE TITLE
channel with protobuf

### ISSUE THREAD

**Issue by jayeshcodezeros** [golang/protobuf#943]
I want to send channel in message to server using gRPC, can we have a type to send channel in protobuf message

**Comment by neild** [comment]
This is not possible, for a variety of reasons. Protobufs are a cross-platform data serialization format; channels are neither cross-platform nor data.

**Comment by jayeshcodezeros** [comment]
@neild got it, can we send mutex in message ?

**Comment by puellanivis** [comment]
Just shallow copying a mutex breaks the functionality of a mutex. Copying a mutex between computers necessarily breaks the functionality of a mutex.

No, you cannot transfer a mutex.
