### ISSUE TITLE
reflect/protoreflect: add a way to go from a Message(Type?) to an Enum

### ISSUE THREAD

**Issue by neild** [golang/protobuf#946]
Given a `protoreflect.Message`, you can get a complete reflective description of an enum field as a `EnumDescriptor` and an `EnumNumber`. You cannot, however, get the Go type for the field.

It seems like this should be possible.

Strawman proposal: Add two new methods to `MessageType`.

```go
interface MessageType {
  // FieldEnumType is the EnumType of a field if the field kind is EnumKind.
  // It returns nil for any other field kind.
  FieldEnumType(fd FieldDescriptor) EnumType

  // FieldMessageType is the MessageType of a field if the field kind is MessageKind or GroupKind.
  // It returns nil for any other field kind.
  FieldMessageType(fd FieldDescriptor) MessageType
}
```

This provides a way to traverse the tree of typed descriptors.

```go
// Get the Enum value of fd in m.
e := m.Type().FieldEnumType(fd).New(m.Get(fd))
```

**Comment by neild** [comment]
Another approach would be to add a `FieldType` to make the `*Descriptor` and `*Type` trees map more directly. As I recall, we discussed this approach early in the design of the protoreflect package.

**Comment by dsnet** [comment]
What does this do return for dynamic message (if I recall the implementation correctly), does not care about the exact Go type of the message or enum field?

More broadly, the currently proposed API assumes that for some parent concrete type T, there can only be exactly one concrete field type R for a given field.

**Comment by dsnet** [comment]
Also, presumably you would want to add an `EnumType` and `MessageType` methods to `ExtensionType` to the moral equivalent there.

**Comment by neild** [comment]
Dynamic messages would return a dynamic `EnumType`.

Message values always have both proto and Go type information; every `protoreflect.Value` that contains a message can be associated with a `MessageType`.

Enum values, in contrast, don't have Go type information. Not only is a `protoreflect.Value` that contains an enum value not associated with an `EnumType`, there's no way to get the `EnumType`.

I don't think providing a way to get the `EnumType` makes any assumptions that we're not already making for message values.

**Comment by neild** [comment]
I agree that this would also require methods on `ExtensionType`; just figured that out myself.

**Comment by dsnet** [comment]
Overall, I think the idea is worth exploring. I think there were a few places where I did:
```go
mt := m.NewField(fd).Message().Type()
```
just to get the `MessageType` for a sub-field. However, it's silly allocating a new message just to get it's type.

My main concerns with this is that `MessageType` and `ExtensionType` are interfaces that can be implemented by the user. Adding more methods makes it harder to implement (which may be a good thing), but also easier to implement incorrectly (this is more concerning). For example, this should be a guaranteed property of the API:
```go
fd := mt.Descriptor().Fields().Get(...)
mt.FieldEnumType(fd).Descriptor() == fd.Enum() // Should always report true
```
However, my concern is alleviated since `testing/prototest` can validate this invariant.

**Comment by neild** [comment]
Yeah, the `FieldMessageType` isn't strictly necessary since you can allocate a new message and get its type as in your example. But as you say it feels a bit silly to allocate a message just to get its type.

**Comment by neild** [comment]
One sticky question: How would this handle maps? What does `m.FieldMessageType(someMapField)` return?

**Comment by neild** [comment]
Conclusion after offline discussion: This would be nice to have, but the amount of API surface required to support it is too large.

**Comment by dsnet** [comment]
In the past few days, I've seen at least 3 real usages where users are jumping through hoops to work around the lack of this API. I think we should seriously consider how to provide this. The map issue is certainly gnarly, but it could be argued that the lack of this API is causes code to be written that is equally or even more gnarly.

**Comment by dsnet** [comment]
Fixed with https://go-review.googlesource.com/c/protobuf/+/236777
