### ISSUE TITLE
documentation request for reserved keyword

### ISSUE THREAD

**Issue by carnott-snap** [golang/protobuf#954]
During the course of investigation on #945 it was recommended that I not use a language feature, `reserved` fields, instead preferring to create a newly namespaced proto file: see [previous comment](https://github.com/golang/protobuf/issues/945#issuecomment-531091065).

Since this was passed as part of the resolution to the aforementioned bug, I wanted to get this fix written up as documentation. While it sounded to me like the `reserved` feature was deprecated, please correct me if this is incorrect. I have also read through the [Go tutorial](https://developers.google.com/protocol-buffers/docs/gotutorial), as well as the [proto3 spec](https://developers.google.com/protocol-buffers/docs/proto3) and cannot find reference to this suggestion.

**Comment by dsnet** [comment]
I'm confused, where is it recommended that `reserved` fields are deprecated in #945? The only mention of it was from you.

It seems that your struggles with versioning goes beyond simply Go modules. Fundamentally, the protobuf language assumes that name declarations are universally unique. Any "major" versions of Go code generated from protobuf files must be source from a different protobuf namespace. This is not unique to Go protobufs. If this requirement problematic for you, there's not much we can do about it here. This project is about implementing protobufs in Go, and we're not in control of the protobuf language.

**Comment by carnott-snap** [comment]
> I'm confused, where is it recommended that reserved fields are deprecated in #945? The only mention of it was from you.

You recommended that I not use `reserved` fields, but did not go so far as to explicitly list them as deprecated. I was simply hoping this ticket could get your recommendations documented so others would not fall victim to this issue.

> Any "major" versions of Go code generated from protobuf files must be sourced from files in a different protobuf namespace.

Again,tThis suggestion is immensely helpful, but not documented, and frequently done by my peers. Where could it be homed, so that it is more discoverable?


> This is not unique to Go protobufs. If this requirement is problematic for you, there's not much we can do about it here. This project is about implementing protobufs in Go, and we're not in control of the protobuf language.

I guess I was thinking that a new (incompatible) version of this library could be developed that maintained the protobuf wire compatibility guarantees at the Go language/library level, but maybe this may be improbable. That being said, I agree with your prognosis, and can work with the upstream protobuf community. Apologies for the hassle here on the topic.

**Comment by dsnet** [comment]
> You recommended that I not use reserved fields, but did not go so far as to explicitly list them as deprecated.

I'm don't see myself mentioning that. Do you have a link?

**Comment by carnott-snap** [comment]
I am citing the following comments:

> https://github.com/golang/protobuf/issues/945#issuecomment-531091065
> You'll notice that the Google APIs have the version number as part of the protobuf package. Thus, the v2 version of the BigTable API lives in the google.bigtable.v2 namespace.

> https://github.com/golang/protobuf/issues/945#issuecomment-531317601
> Have you tried using a different proto package namespace for the .proto files associated with v2?

> https://github.com/golang/protobuf/issues/954#issuecomment-534764284
> Any "major" versions of Go code generated from protobuf files must be sourced from files in a different protobuf namespace.

And applied the following associative logic:
- `reserved` keyword (specifically when used for field sunset, not field pre-reservation) leads to Go code major version
- major version requires requires different protobuf namespace
- qed: `reserved` keyword requires use of different protobuf namespace

**Comment by dsnet** [comment]
It would help if you didn't jump to conclusions based on shaky "proofs" like this. I still don't understand the premise.

> reserved keyword (specifically when used for field sunset, not field pre-reservation) leads to Go code major version

Where did I mention `reserved` keywords?

**Comment by carnott-snap** [comment]
> It would help if you didn't jump to conclusions based on shaky "proofs" like this. I still don't understand the premise.

Apologies for not making my reasoning more clear, I will do this in the future. If I make a breaking change to generated Go code, via use of the `reserved` keyword, what is the correct resolution?

> Where did I mention `reserved` keywords?

My ticket, #945, specifically requests how to deal with breaking changes caused by usage of the `reserved` keyword. You do not call it out, however it was my understanding that the discussion related was in the context of that feature.

**Comment by neild** [comment]
Closing, since there's no recommendation not to use `reserved`.

**Comment by carnott-snap** [comment]
> Closing, since there's no recommendation not to use `reserved`.

How do we use the keyword without breaking compatibility guarantees?

**Comment by puellanivis** [comment]
That’s a question more appropriate for the wider protobuf community, rather than focusing so narrowly only on the Go package team.

**Comment by neild** [comment]
The `reserved` keyword reserves a field name or number. How you use it is up to you.

Inside Google's monorepo, `reserved` is used to prevent reuse of fields which have been removed from the codebase. Compatibility guarantees are not a concern, because monorepo.

Outside of a monorepo, one might use it in code that has no compatibility guarantee, or which is not part of a public API, or which has a compatibility guarantee permitting fields to be removed. One might also use it when defining a new version of a message that is intended to be wire-compatible with the old one.

Or you might not use it. Not every feature is useful for every user.

**Comment by carnott-snap** [comment]
> @puellanivis:
> That’s a question more appropriate for the wider protobuf community, rather than focusing so narrowly only on the Go package team.

What is the correct channel to bring up this discussion?

> @neild:
> The `reserved` keyword reserves a field name or number. How you use it is up to you.

I totally agree it makes sense for pre-reservation, my concern is about sunset/post-reservation. Currently peers have a lot of confusion about how to use modules and `reserved` correctly within the Go ecosystem, thus I was hoping to have the docs suggest best practices.

> One might also use it when defining a new version of a message that is intended to be wire-compatible with the old one.

Am I to understand that the following will work:
- release proto with message and rpc: `v1`
- sunset field in message, and release new proto with message and rpc: `v2`
- send message from v1 client to v2 server (or vice versa)
I thought that global uniqueness requirements would not allow using `v1` as `v2`, even still would not WKTs like `any` should break?
