### ISSUE TITLE
APIv2: conversion functions between v1/v2 Message types

### ISSUE THREAD

**Issue by neild** [golang/protobuf#956]
We need a simple way to turn a protoV1.Message into a protoV2.Message, at the least. The impl package has a function which does this already, so it's hopefully just a matter of providing an exported API somewhere.

**Comment by dsnet** [comment]
Does this belong in the v1 `github.com/golang/protobuf` or v2 `google.golang.org/protobuf` module?

I argue that it should be the former since you would only need to do this when bridging v1 and v2. If you were in a pure v2 world, you would never need this functionality.

**Comment by neild** [comment]
Not sure.

The argument for putting it in v2 is that it lets a package with `protoV1.Message` in an exported API that can't be changed still entirely remove the dependency on `github.com/golang/protobuf`.

**Comment by dsnet** [comment]
We decided to put `MessageV1Of`, `MessageV2Of`, and `ReflectMessageOf` in the v1 `proto` package.
