### ISSUE TITLE
How does the first proto file import the message in the second file?(Go)

### ISSUE THREAD

**Issue by gavin-yeh** [golang/protobuf#968]
b.proto
`syntax = "proto3";`
`package b;`

`/** Command 命令 */`
`message Command {`
`    int32 type =      1;  // 種類`
`    bytes content =   2;  // 命令`
`};`

-------------------------------------------------------------------------

a.proto
`syntax = "proto3";`
`package a;`

`import "b.proto";`

`message S {`
`    b.Command cmd =          3;  // 命令`
`};`

-------------------------------------------------------------------------

I use the following syntax to create a file:
protoc --go_out=plugins=grpc:. a.proto --proto_path=.

a.pb.go

...
type S struct {
	`Cmd *Command`    // error mgs : undefined: Command
 ....
}

...

How can this be solved?

**Comment by puellanivis** [comment]
You at the very least need to also compile b.proto.

**Comment by gavin-yeh** [comment]
After I compile b.proto, a.proto is still wrong, and there is no automatic association. Is there a solution?

**Comment by dsnet** [comment]
We a moving towards a world where the `go_package` option is required for generating any `.pb.go`. One cannot expect `protoc-gen-go` to know where a remote reference is located in the Go namespace if that information is not available somewhere. The `go_package` option records precisely the information needed. Lacking it, we can't connect the protobuf namespace to the Go namespace in a way that works for all situations (as you are evidently observing). There are some rules that `protoc-gen-go` follows when `go_package` is missing, but they almost never do what users expect.
