### ISSUE TITLE
APIv2: figure out handling of zero-length packed extension fields

### ISSUE THREAD

**Issue by neild** [golang/protobuf#975]
Given a repeated extension field with a non-packed encoding, what do we do when unmarshaling wire data containing a zero-length packed value for the field?

Currently, we parse this as a zero-length list. (`m.Has(xd)==true`, `m.Get(xd).List().Len()==0`.) However, there is no way to represent this using the non-packed encoding of repeated fields, so if we marshal the message out again the field vanishes. This violates the expectation that unmarshaling and remarshaling a message should leave it unchanged.

**Comment by dsnet** [comment]
For non-extensions repeated fields, isn't it already the case that:
* unmarshaling a packed zero-length field results `m.Has(fd) == false` and `m.Get(fd).List().Len() == 0`
* marshaling the above results in the field disappearing (thus, already violating the expectation that round-trip unmarshal+marshal should leave the message unchanged).

**Comment by dsnet** [comment]
To be specific, I propose `m.Has(xd)` report false for repeated extension fields if and only if `m.Get(xd).List().Len() == 0`.

**Comment by puellanivis** [comment]
I mean, the only way to do anything else would be to treat `[]thing{}` differently from `[]thing(nil)` like JSON does. But there are plenty of good reasons already existing on why that sort of behavior should be avoided.

**Comment by neild** [comment]
Fixed by [CL 204897](https://go-review.googlesource.com/c/protobuf/+/204897).
