### ISSUE TITLE
[libprotobuf ERROR google/protobuf/io/zero_copy_stream_impl.cc:118] close() failed: Bad file descriptor

### ISSUE THREAD

**Issue by ajay-collab** [golang/protobuf#976]
creation of Tensorrt engine started throwing this. Any clue?

**Comment by puellanivis** [comment]
This repo is for the golang implementation of protobuf. You appear to be referencing an issue for the C++ implementation.

**Comment by dsnet** [comment]
Closing as inactionable for us (the Go library team).
