### ISSUE TITLE
Move fuzz corpus elsewhere?

### ISSUE THREAD

**Issue by dsnet** [golang/protobuf#980]
The [`internal/fuzz/wire/corpus`](https://github.com/golang/protobuf/tree/api-v2/internal/fuzz/wire/corpus) directory contains the start of a fuzzing corpus for the wire format. My experience with fuzzing is that the corpus can really grow in size over time as the fuzzer explores more branch cases. Do we want these in our repo, or should this live elsewhere?

**Comment by dsnet** [comment]
\cc @neild

**Comment by neild** [comment]
This contains only the seed corpus (a starting point to help get the fuzzer bootstrapped) and interesting test cases discovered by fuzzing. The full working corpus is managed by OSS-Fuzz:
https://google.github.io/oss-fuzz/advanced-topics/corpora/

I think it's fine to keep a minimal corpus here as a test case for the fuzz function.

**Comment by dsnet** [comment]
Ah. Got it. A non-growing corpus is acceptable. Closing.
