### ISSUE TITLE
APIv2: Go type of scalar extension fields differs from v1

### ISSUE THREAD

**Issue by neild** [golang/protobuf#981]
Currently:

v1: `proto.SetExtension(m, pb.E_OptionalString, proto.String("value"))`
v2: `proto.SetExtension(m, pb.E_OptionalString, "value")`

I think the current v2 behavior is unintentional; I don't believe I realized that v1 represented singular scalar extension fields to the user as a `*T` rather than a `T`. The v1 API doesn't permit a `(*T)(nil)` value for an extension, so there's no reason I can see for this to be a pointer.

However, if this changes, it should be a change we make intentionally rather than accidentally. The non-pointer form is simpler to work with and avoids unnecessary allocations, but adds another stumbling block for migration.

**Comment by dsnet** [comment]
At least in my mind, this was a deliberate decision for several reasons:
* The v1 API exposed "double" presence for scalars. First through the `HasExtension` API, and second through the nil-ness of the pointer. The v2 API only exposes one form of presence through `HasExtension`, which is the correct way to test for presence.
* The v2 API is more consistent with the future opaque API where `MyMessage.SetFooField` takes in a `T`, not a `*T` for scalars.
* The v2 API is also simpler and more performant. Why bother boxing a scalar on the heap?

**Comment by puellanivis** [comment]
Sounds like the new behavior is the way forward. proto3 in part got rid of “default as anything other than zero value” for more or less similar reasons. Supporting the presence tests through pointers requires boxing scalars, requires helper functions that just box a scalar onto the heap to provide a pointer for scalar literals, and just generally making everyone’s life just a little harder.

Sure, it’s a bit of a migration obstacle, but of all the changes, I think it’s one of the lowest hurdles in this process to overcome. :laughing:

**Comment by neild** [comment]
Sounds good, so long as we're making the change deliberately.
