### ISSUE TITLE
protoc-gen-go: better Any representation

### ISSUE THREAD

**Issue by kyessenov** [golang/protobuf#986]
(This is similar to Struct issue filed earlier https://github.com/golang/protobuf/issues/686)

We have a large nested proto with Any used for polymorphism:
```proto
message X {
  google.protobuf.Any y = 1; // This should be message Y
}
message Y {
  google.protobuf.Any z = 1; // This should be message Z
}
message Z {
...
}
```

Our program constructs this proto in steps due to its size, each time making a pass over the whole structures. Whenever a field is needed to be changed in a nested proto (e.g. `z`), the code has to de-serialize and re-serialize the proto.

The request is to provide an alternative Go representation for `Any` fields, using `proto.Message` as the type. This way the marshaller can produce bytes as the very last step, instead of forcing intermediate byte representation at runtime.

/cc @howardjohn

**Comment by neild** [comment]
We're not going to get to any significant changes until APIv2 is released (one thing at a time!), but we should look into a better Any representation.

Just representing an Any as a proto.Message seems like it should be sufficient, but perhaps I'm missing something.

**Comment by puellanivis** [comment]
With good enough reflection, we should be able to just use a `proto.Message` easy enough. I think in the current APIv1, it was just very hard to get anything done with a raw `*proto.Message`.

**Comment by kyessenov** [comment]
In my opinion, it would be good to get some provision to change the type of the `Any` field before the major version is released. Using any type that is not concrete `Any` in place of it (`proto.Message` or some special any interface) sounds good to me.

**Comment by dsnet** [comment]
Representing an `Any` as a `proto.Message` would be nice, but is not how other language implementations represent `Any` under the hood. In general, we avoid features that the other language implementations don't do. That is, we're hesitant to trail-blaze on new features.

**Comment by dsnet** [comment]
Our policy is to avoid any features or representation that's different from what the other major language implementations do. Since they (e.g., C++ and Java) represent `Any` as a flat message and instead rely on other functionality to convert `Any` to the concrete underlying representation, we will continue to do so as well. If there's a significant change in the entire protobuf ecosystem regarding this, then we can revisit this.
