### ISSUE TITLE
suggest generate file with protoc and protoc-gen-go version

### ISSUE THREAD

**Issue by CNSumi** [golang/protobuf#987]
such as 

```
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: omg.proto
// protoc: libprotoc 3.6.1
// protoc-gen-go: v1.3.2
```
difference version of protoc and protoc-gen-go generated result has huge difference, sometimes hard to diff and commit

**Comment by dsnet** [comment]
Duplicate of #524. Already fixed in https://golang.org/cl/186117
