### ISSUE TITLE
Why doesn't a nil ptypes.timestamp convert to a zero-value time?

### ISSUE THREAD

**Issue by elliotw23** [golang/protobuf#990]
If a field is a `ptypes.timestamp` type and no value is supplied, the `ptypes.Timestamp` function will convert to `time.Unix(0, 0).UTC()`, which comes out to `1970-01-01 00:00:00 +0000`, which is not the golang zero-value for time (`time.Time{} = 0001-01-01 00:00:00 +0000`). I thought the convention in protobuf was to output the language-specific zero-value for the given type, but in this case the pattern is not followed. Reasons?

**Comment by cybrcodr** [comment]
[google.protobuf.Timestamp](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Timestamp) has its own semantics.

> **seconds** Represents seconds of UTC time since Unix epoch 1970-01-01T00:00:00Z.
