### ISSUE TITLE
Why  protobuf is not installed under $GOPATH/src

### ISSUE THREAD

**Issue by leexuehan** [golang/protobuf#991]
**My go version: 1.13**

### command:

```
go get -d -u github.com/golang/protobuf/protoc-gen-go

```

### result:

protoc installed under $PATH/pkg/mod

**Comment by dsnet** [comment]
This is not relevant to `golang/protobuf`, but more so the `go` toolchain. The location has to do with what version of Go you are using and whether you are operating in module mode:

https://golang.org/doc/go1.12#modules
