### ISSUE TITLE
protoc-gen-go: missing service definition in generated Go files

### ISSUE THREAD

**Issue by r3code** [golang/protobuf#993]
**What version of protobuf and what language are you using?**
Version: libprotoc 3.10.1

**What did you do?**
`protoc -I. --go_out=plugins=paths=source_relative,grpc:gen_buggy\go\ *.proto`

**What did you expect to see?**
Generated Go file contains *APIClient and *APIServer functions.
Or error reported of inconsistent or incompatible params.

**What did you see instead?**
Generated Go file does not contain *APIClient and *APIServer functions.
No errors generated. 

**Anything else we should know about your project / environment?**
This one `protoc -I. --go_out=plugins=grpc,paths=source_relative:gen\go *.proto` generates go code correct.

Example proto-file:
```
syntax = "proto3";

package protocgengo.test.bug_source_related;

option go_package = "bug_source_related";

service AuthAPI {   
  rpc Login (LoginQuery) returns (LoginAnswer) {} 
}
             
message LoginQuery {
  string auth_token = 1; // required; 
} 

message LoginAnswer {  
  string error = 1;   
}
        
```

**Comment by r3code** [comment]
Relatred #544

**Comment by dsnet** [comment]
This project is no longer responsible for generating the service bindings as that behavior is moving over to the `grpc-go` project.
