### ISSUE TITLE
jsonpb: jsonProperties allocates a huge amount of memory

### ISSUE THREAD

**Issue by strobil** [golang/protobuf#994]
**What version of protobuf and what language are you using?**
github.com/golang/protobuf v1.3.2
grpc-ecosystem/grpc-gateway v1.9.6
google.golang.org/grpc v1.25.1

go version go1.13.4 linux/amd64

**What did you do?**
I am using [wrk](https://github.com/wg/wrk) for stress testing an grpc service.
I have noticed that under high incoming request rate my app memory instantly grow up.
Using go profiler, i figure out that the top1 function that allocates memory in my project is jsonpb.jsonProperties.

Running wrk with these params:

> Running 30s test @ http://127.0.0.1:8080/TvService/GetChannels
  8 threads and 128 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.97s   981.12ms   8.01s    77.89%
    Req/Sec     5.96      5.94    40.00     78.45%
  579 requests in 30.04s, 2.43GB read
Requests/sec:     19.27
Transfer/sec:     82.82MB

After test is complete i use pprof tool to download heap debug info.

> go tool pprof -alloc_space http://localhost:6060/debug/pprof/heap

I've got these results:

> (pprof) top 15
> Showing nodes accounting for 54.80GB, 98.84% of 55.44GB total
> Dropped 142 nodes (cum <= 0.28GB)
> Showing top 15 nodes out of 62
>       flat  flat%   sum%        cum   cum%
>    14.92GB 26.92% 26.92%    20.60GB 37.16%  github.com/golang/protobuf/jsonpb.jsonProperties
>    11.49GB 20.72% 47.64%    11.49GB 20.72%  strings.genSplit
>     7.22GB 13.03% 60.67%     7.22GB 13.03%  bytes.makeSlice
>     5.35GB  9.65% 70.32%    12.49GB 22.53%  github.com/golang/protobuf/jsonpb.(*errWriter).write
>     2.69GB  4.85% 75.17%     2.69GB  4.85%  reflect.packEface
>     2.19GB  3.94% 79.11%     2.19GB  3.94%  reflect.(*structType).Field
>     2.13GB  3.83% 82.95%     2.13GB  3.83%  encoding/json.Marshal
>     1.73GB  3.12% 86.06%     1.73GB  3.12%  google.golang.org/grpc.(*parser).recvMsg
>     1.51GB  2.73% 88.79%     2.20GB  3.97%  google.golang.org/grpc/encoding/proto.marshal
>     1.49GB  2.70% 91.48%     1.49GB  2.70%  github.com/golang/protobuf/proto.unmarshalStringPtr
>     1.30GB  2.34% 93.83%     1.30GB  2.34%  reflect.New
>     1.06GB  1.91% 95.73%    40.64GB 73.31%  github.com/golang/protobuf/jsonpb.(*Marshaler).marshalValue
>     0.69GB  1.24% 96.97%     0.69GB  1.24%  github.com/golang/protobuf/proto.(*Buffer).grow
>     0.60GB  1.08% 98.05%    40.64GB 73.31%  github.com/golang/protobuf/jsonpb.(*Marshaler).marshalObject
>     0.44GB  0.78% 98.84%     0.44GB  0.78%  github.com/golang/protobuf/proto.pointer.appendPointer

So, during 30 seconds this functtion is allocated about 15Gb of memory.

**What did you expect to see?**
Low memory allocation 

**What did you see instead?**
High memory allocation

**Anything else we should know about your project / environment?**
I am using grpc-ecosystem/grpc-gateway that encodes/decodes my requests to json.
Stress testing is done over grpc-gateway using json.

**Comment by dsnet** [comment]
The v2 protojson library completely re-writes the `jsonpb` library with zero shared code. I doubt this is an issue in v2.

**Comment by dsnet** [comment]
The [`protojson`](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson) package is a complete rewrite of the protobuf-to-JSON implementation.
