### ISSUE TITLE
What' the difference of github.com/golang/protobuf and github.com/google/protobuf ?

### ISSUE THREAD

**Issue by beef9999** [golang/protobuf#995]

**Comment by neild** [comment]
* `github.com/google/protobuf`: Big repo containing the protocol buffer compiler, some standard `.proto` files like `google/protobuf/descriptor.proto`, and implementations for a number of languages including C++, Java, and Python.
* `github.com/golang/protobuf`: Go implementation of protocol buffers, including a protocol buffer compiler plugin and support packages.
* `google.golang.org/protobuf`: New Go implementation of protocol buffers. In development. Not released yet.
