### ISSUE TITLE
json tag in .proto

### ISSUE THREAD

**Issue by JCzz** [golang/protobuf#998]
I am trying to generate go structs incl. json tags.

I can do this in .proto:

    string name = 1 [json_name="item.name, omitempty"];

But that only generates - **json=item.name** and only **json:"name,omitempty"**

    Name string `protobuf:"bytes,1,opt,name=name,json=item.name, omitempty,proto3" json:"name,omitempty"`

But I need:- **json:"item.name,omitempty"** Note the tag is missing "item.".
And it looks like no matter what you put in json_name it is not reflected in **"json:"**

Du you know how to set json tags?

**Comment by puellanivis** [comment]
Do not put a space between `json_name="item.name, omitempty"`

Also, adding a comma there with intent to add `omitempty` is not the proper way to do that.

**Comment by rubens21** [comment]
I think it is actually a bug on the protoc Golang code generator.
It is always using the property name (in this case `name`), not the value in the option.

When I try something like `string name = 1 [json_name="something"];` in my proto file, I get:
```
`protobuf:"bytes,1,opt,name=name,json=something,proto3" json:"name,omitempty"`
```

Shouldn't that be `json:"something,omitempty"`?

**Comment by dsnet** [comment]
The `json_name` option in the `.proto` file has nothing to do with the generated `json` tag, but rather with the name used in the official protobuf-to-JSON mapping: https://developers.google.com/protocol-buffers/docs/proto3#json, which is implemented in the [`jsonpb`](https://godoc.org/github.com/golang/protobuf/jsonpb) package.

If you want finer granularity control of the generated `json` tags, then this is a subset of #52.
