### ISSUE TITLE
jsonpb: how to support map[string][]string?

### ISSUE THREAD

**Issue by mangatmodi** [golang/protobuf#999]
**Version**: v1.3.1
**Update**: Same error in v1.3.2 also

I have a JSON which contains a field which is of type `map[string][]string` e.g. - 
```json
{

      "attributes": {
        "app_only": [
          "0"
        ],
        "brand": [
          "ABC"
        ],
        "color_family": [
          "brown"
        ],
        "fabric_material": [
          "Leather"
        ],
        "gender": [
          "unisex"
        ],
        "lhr": [
          "Flat"
        ],
        "name": [
          "ABC"
        ],
        "occasion": [
          "Casual"
        ]

}

```

I understand that `jsonpb` uses the mapping from [here](https://developers.google.com/protocol-buffers/docs/proto3#json). However, since `protobuff` doesn't support repeated in the key/value of a map, I am struggling to find the correct schema in the `protobuff`. 

I tried `map <string, google.protobuf.Any>` which fails with the following error message - `json: cannot unmarshal array into Go value of type map[string]*json.RawMessage`

The error is returned when `jsonpb` tries to unmarshal the array value at line - `https://github.com/golang/protobuf/blob/v1.3.1/jsonpb/jsonpb.go#L670`

Is it possible to support such schema in **ProtobuffV3**? If yes, what schema should I use?

**Comment by neild** [comment]
I do not believe there is any mapping of this data into something that `jsonpb` will accept.

Protocol buffers aren't intended to represent arbitrary JSON. There's a JSON representation of any given protocol buffer message, but not vice-versa.

**Comment by mangatmodi** [comment]
Thanks @neild. I suspected same.
